### ISSUE TITLE
tarantool: ./src/box/key_def.c:136: key_def_copy: Assertion `sz == key_def_copy_size(dest)' failed.

### ISSUE THREAD

**Issue by ligurio** [tarantool/tarantool#10095]
**Bug description**

*    OS: Linux
*    OS Version: 22.04
*    Architecture: amd64

Tarantool 3.2.0-entrypoint-56-g05d03a1c58
Target: Linux-x86_64-Debug
Build options: cmake . -DCMAKE_INSTALL_PREFIX=/usr/local -DENABLE_BACKTRACE=TRUE
Compiler: GNU-11.4.0
C_FLAGS: -fexceptions -funwind-tables -fasynchronous-unwind-tables -fno-common -msse2 -Wformat -Wformat-security -Werror=format-security -fstack-protector-strong -fPIC -fmacro-prefix-map=/home/sergeyb/sources/MRG/tarantool=. -std=c11 -Wall -Wextra -Wno-gnu-alignof-expression -fno-gnu89-inline -Wno-cast-function-type -Werror -g -ggdb -O0 
CXX_FLAGS: -fexceptions -funwind-tables -fasynchronous-unwind-tables -fno-common -msse2 -Wformat -Wformat-security -Werror=format-security -fstack-protector-strong -fPIC -fmacro-prefix-map=/home/sergeyb/sources/MRG/tarantool=. -std=c++11 -Wall -Wextra -Wno-invalid-offsetof -Wno-gnu-alignof-expression -Wno-cast-function-type -Werror -g -ggdb -O0 

**Steps to reproduce**

Actually, there are no exact steps to reproduce.

**Actual behavior**

```
$ taskset 0xef ./tarantool vinyl.lua --workers 50 --test_duration 10                                         
Random seed: 1717594941                                                                                                                            
CLEANUP                                                                                                                                            
SETUP                                                                                                                                              
2024-06-05 16:42:21.703 [752207] main/104/vinyl.lua I> Tarantool 3.2.0-entrypoint-56-g05d03a1c58 Linux-x86_64-Debug                                
2024-06-05 16:42:21.703 [752207] main/104/vinyl.lua I> log level 5 (INFO)                                                                          
2024-06-05 16:42:21.703 [752207] main/104/vinyl.lua I> wal/engine cleanup is paused                                                                
2024-06-05 16:42:21.703 [752207] main/104/vinyl.lua I> mapping 67108864 bytes for memtx tuple arena...                                             
2024-06-05 16:42:21.703 [752207] main/104/vinyl.lua I> Actual slab_alloc_factor calculated on the basis of desired slab_alloc_factor = 1.044274    
2024-06-05 16:42:21.704 [752207] main/104/vinyl.lua I> mapping 16777216 bytes for vinyl tuple arena...
2024-06-05 16:42:21.711 [752207] main/104/vinyl.lua I> update replication_synchro_quorum = 1                                                       
2024-06-05 16:42:21.711 [752207] main/104/vinyl.lua I> instance uuid c94669a8-0bb2-4871-99a3-e0d6f3aa6836                                          
2024-06-05 16:42:21.711 [752207] main/104/vinyl.lua I> initializing an empty data directory                                                        
2024-06-05 16:42:21.733 [752207] main/104/vinyl.lua I> assigned id 1 to replica c94669a8-0bb2-4871-99a3-e0d6f3aa6836                               
2024-06-05 16:42:21.733 [752207] main/104/vinyl.lua I> update replication_synchro_quorum = 1                                                       
2024-06-05 16:42:21.733 [752207] main/104/vinyl.lua I> replicaset uuid 8cfeba4a-6af8-41bf-9644-bd315366e616                                        
2024-06-05 16:42:21.734 [752207] snapshot/101/main I> saving snapshot `./00000000000000000000.snap.inprogress'                                     
2024-06-05 16:42:21.746 [752207] snapshot/101/main I> done                                                                                         
2024-06-05 16:42:21.746 [752207] main/104/vinyl.lua I> ready to accept requests                                                                    
2024-06-05 16:42:21.746 [752207] main/105/gc I> wal/engine cleanup is resumed                                                                      
2024-06-05 16:42:21.746 [752207] main/104/vinyl.lua/box.load_cfg I> set 'memtx_memory' configuration option to 1048576                             
2024-06-05 16:42:21.746 [752207] main/104/vinyl.lua/box.load_cfg I> set 'vinyl_memory' configuration option to 10485760                            
2024-06-05 16:42:21.746 [752207] main/104/vinyl.lua/box.load_cfg I> set 'vinyl_cache' configuration option to 4                                    
2024-06-05 16:42:21.746 [752207] main/104/vinyl.lua/box.load_cfg I> set 'vinyl_timeout' configuration option to 4                                  
2024-06-05 16:42:21.746 [752207] main/104/vinyl.lua/box.load_cfg I> set 'vinyl_max_tuple_size' configuration option to 12831                       
2024-06-05 16:42:21.747 [752207] main/104/vinyl.lua/box.load_cfg I> set 'checkpoint_wal_threshold' configuration option to 231                     
2024-06-05 16:42:21.747 [752207] main/104/vinyl.lua/box.load_cfg I> set 'checkpoint_interval' configuration option to 18                           
2024-06-05 16:42:21.748 [752207] main/104/vinyl.lua/vinyl I> FINISH BOX.CFG                                                                        
2024-06-05 16:42:21.748 [752207] main/104/vinyl.lua/vinyl I> CREATE A SPACE                                                                        
2024-06-05 16:42:21.748 [752207] main/104/vinyl.lua/vinyl I> {"format":[{"name":"name_1","type":"boolean"},{"name":"name_2","type":"integer"},{"nam
e":"name_3","type":"number"},{"name":"name_4","type":"boolean"},{"name":"name_5","type":"double"},{"name":"name_6","type":"string"},{"name":"name_7
","type":"boolean"},{"name":"name_8","type":"decimal"}],"if_not_exists":true,"is_local":false,"field_count":0,"engine":"vinyl"}                    
2024-06-05 16:42:21.748 [752207] main/106/checkpoint_daemon I> scheduled next checkpoint for Wed Jun  5 16:42:41 2024                              
2024-06-05 16:42:21.749 [752207] main I> WAL threshold exceeded, triggering checkpoint                                                             
2024-06-05 16:42:21.753 [752207] snapshot/101/main I> saving snapshot `./00000000000000000001.snap.inprogress'                                     
2024-06-05 16:42:21.754 [752207] main/104/vinyl.lua/vinyl I> FINISH SETUP                                                                          
2024-06-05 16:42:21.755 [752207] snapshot/101/main I> done     

<snipped>

2024-06-05 16:42:21.808 [752207] main/162/WORKER #49/vinyl I> ["INDEX_ALTER_OP",[]]
2024-06-05 16:42:21.809 [752207] main/162/WORKER #49/vinyl I> ERROR: Unsupported index type supplied for index 'idx_97' in space 'test_55'
2024-06-05 16:42:21.809 [752207] main/115/WORKER #2/vinyl I> ["INDEX_ALTER_OP",[]]
2024-06-05 16:42:21.809 [752207] main/115/WORKER #2/vinyl I> ERROR: Unsupported index type supplied for index 'idx_97' in space 'test_55'
2024-06-05 16:42:21.809 [752207] main/129/WORKER #16/vinyl I> ["INDEX_ALTER_OP",[]]
2024-06-05 16:42:21.809 [752207] main/129/WORKER #16/vinyl I> ERROR: Unsupported index type supplied for index 'idx_97' in space 'test_55'
2024-06-05 16:42:21.809 [752207] main/128/WORKER #15/vinyl I> ["INDEX_ALTER_OP",[]]
tarantool: ./src/box/key_def.c:136: key_def_copy: Assertion `sz == key_def_copy_size(dest)' failed.
Aborted (core dumped)
```

coredump and tarantool binary: [gh-10095-core.zip](https://github.com/user-attachments/files/15592184/gh-10095-core.zip)

Backtrace:

```
#0  __pthread_kill_implementation (no_tid=0, signo=6, threadid=130131161815744) at ./nptl/pthread_kill.c:44
#1  __pthread_kill_internal (signo=6, threadid=130131161815744) at ./nptl/pthread_kill.c:78
#2  __GI___pthread_kill (threadid=130131161815744, signo=signo@entry=6) at ./nptl/pthread_kill.c:89
#3  0x0000765a84e42476 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#4  0x0000765a84e287f3 in __GI_abort () at ./stdlib/abort.c:79
#5  0x0000765a84e2871b in __assert_fail_base (fmt=0x765a84fdd130 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", 
    assertion=0x6469839c8a28 "sz == key_def_copy_size(dest)", file=0x6469839c8a14 "./src/box/key_def.c", line=136, function=<optimized out>)
    at ./assert/assert.c:92
#6  0x0000765a84e39e96 in __GI___assert_fail (assertion=0x6469839c8a28 "sz == key_def_copy_size(dest)", 
    file=0x6469839c8a14 "./src/box/key_def.c", line=136, function=0x6469839c8f40 <__PRETTY_FUNCTION__.19> "key_def_copy") at ./assert/assert.c:101
#7  0x000064698366b50f in key_def_copy (dest=0x646985a5e900, src=0x646985a40f20) at /home/sergeyb/sources/MRG/tarantool/src/box/key_def.c:136
#8  0x0000646983143d6d in vinyl_index_update_def (index=0x64698591da40) at /home/sergeyb/sources/MRG/tarantool/src/box/vinyl.c:926
#9  0x00006469831cee1f in index_update_def (index=0x64698591da40) at /home/sergeyb/sources/MRG/tarantool/src/box/index.h:843
#10 0x00006469831d5b9f in ModifyIndex::alter (this=0x765a8240f4b0, alter=0x765a8240f430)
    at /home/sergeyb/sources/MRG/tarantool/src/box/alter.cc:1332
#11 0x00006469831d52ba in alter_space_do (stmt=0x765a8240f290, alter=0x765a8240f430) at /home/sergeyb/sources/MRG/tarantool/src/box/alter.cc:1044
#12 0x00006469831d9db5 in on_replace_dd_index (event=0x765a8240f038) at /home/sergeyb/sources/MRG/tarantool/src/box/alter.cc:2654
#13 0x00006469833c03e6 in trigger_run_list (list=0x765a65080ac0, event=0x765a8240f038)
    at /home/sergeyb/sources/MRG/tarantool/src/lib/core/trigger.cc:100
#14 0x00006469833c0508 in trigger_run (list=0x6469858e1ef0, event=0x765a8240f038)
    at /home/sergeyb/sources/MRG/tarantool/src/lib/core/trigger.cc:133
#15 0x00006469831bb7f1 in space_on_replace (space=0x6469858e1e50, txn=0x765a8240f038) at /home/sergeyb/sources/MRG/tarantool/src/box/space.c:997
#16 0x00006469831f6ba6 in txn_commit_stmt (txn=0x765a8240f038, request=0x765a65080c40) at /home/sergeyb/sources/MRG/tarantool/src/box/txn.c:678
#17 0x000064698320a5ba in box_process_rw (request=0x765a65080c40, space=0x6469858e1e50, result=0x765a65080d40)
    at /home/sergeyb/sources/MRG/tarantool/src/box/box.cc:508
#18 0x0000646983217447 in box_process1 (request=0x765a65080c40, result=0x765a65080d40) at /home/sergeyb/sources/MRG/tarantool/src/box/box.cc:3731
#19 0x000064698321808d in box_replace (space_id=288, tuple=0x765a82475240 "\226\315\002", tuple_end=0x765a824752b4 'P' <repeats 200 times>..., 
    result=0x765a65080d40) at /home/sergeyb/sources/MRG/tarantool/src/box/box.cc:3931
#20 0x0000646983321c0a in lbox_replace (L=0x401c2180) at /home/sergeyb/sources/MRG/tarantool/src/box/lua/index.c:80
#21 0x00006469833f4cc7 in lj_BC_FUNCC () at buildvm_x86.dasc:811
#22 0x000064698340283f in lua_pcall (L=0x401c2180, nargs=1, nresults=-1, errfunc=0)
    at /home/sergeyb/sources/MRG/tarantool/third_party/luajit/src/lj_api.c:1173
#23 0x0000646983367afc in luaT_call (L=0x401c2180, nargs=1, nreturns=-1) at /home/sergeyb/sources/MRG/tarantool/src/lua/utils.c:687
#24 0x000064698335dd1c in lua_fiber_run_f (ap=0x765a82413290) at /home/sergeyb/sources/MRG/tarantool/src/lua/fiber.c:426
#25 0x00006469830c4147 in fiber_cxx_invoke(fiber_func, typedef __va_list_tag __va_list_tag *) (f=0x64698335dc5f <lua_fiber_run_f>, 
    ap=0x765a82413290) at /home/sergeyb/sources/MRG/tarantool/src/lib/core/fiber.h:1311
#26 0x0000646983396bd1 in fiber_loop (data=0x0) at /home/sergeyb/sources/MRG/tarantool/src/lib/core/fiber.c:1159
#27 0x00006469837800f6 in coro_init () at /home/sergeyb/sources/MRG/tarantool/third_party/coro/coro.c:108
```

**Expected behavior**

no crash

**Comment by locker** [comment]
Short reproducer:

```lua
local fiber = require('fiber')

box.cfg{}

local s = box.schema.create_space('test', {engine = 'vinyl'})
s:create_index('pk')
s:create_index('sk', {parts = {2, 'unsigned'}})
s.index.sk:alter({parts = {2, 'unsigned', 1, 'unsigned'}})
os.exit(0)
```

**Comment by locker** [comment]
This is an ancient bug introduced in 64817066ff60ea440004ef4518b54d34a64efe29 (2.2.0-611-g64817066ff60).
