### ISSUE TITLE
tarantool: ./src/box/tuple_compare.cc:250: int mp_compare_decimal(const char*, const char*): Assertion `ret != NULL' failed.

### ISSUE THREAD

**Issue by ligurio** [tarantool/tarantool#10107]
**Bug description**

*    OS: Linux
*    OS Version: 22.04
*    Architecture: amd64

Tarantool 3.2.0-entrypoint-56-g05d03a1c58
Target: Linux-x86_64-Debug
Build options: cmake . -DCMAKE_INSTALL_PREFIX=/usr/local -DENABLE_BACKTRACE=TRUE
Compiler: GNU-11.4.0
C_FLAGS: -fexceptions -funwind-tables -fasynchronous-unwind-tables -fno-common -msse2 -Wformat -Wformat-security -Werror=format-security -fstack-protector-strong -fPIC -fmacro-prefix-map=/home/sergeyb/sources/MRG/tarantool=. -std=c11 -Wall -Wextra -Wno-gnu-alignof-expression -fno-gnu89-inline -Wno-cast-function-type -Werror -g -ggdb -O0 
CXX_FLAGS: -fexceptions -funwind-tables -fasynchronous-unwind-tables -fno-common -msse2 -Wformat -Wformat-security -Werror=format-security -fstack-protector-strong -fPIC -fmacro-prefix-map=/home/sergeyb/sources/MRG/tarantool=. -std=c++11 -Wall -Wextra -Wno-invalid-offsetof -Wno-gnu-alignof-expression -Wno-cast-function-type -Werror -g -ggdb -O0 

**Steps to reproduce**

Actually, there are no exact steps to reproduce.

**Actual behavior**

```
[1] ~/sources/snippets/tarantool-tools$ taskset 0xef ./tarantool vinyl.lua --workers 200 --test_duration $((30*60)) --engine vinyl                 
Random seed: 1717679777                                                                                                                            
CLEANUP                                                                                                                                            
SETUP                                                                                                                                              
2024-06-06 16:16:17.943 [1032052] main/104/vinyl.lua I> Tarantool 3.2.0-entrypoint-56-g05d03a1c58 Linux-x86_64-Debug                               
2024-06-06 16:16:17.943 [1032052] main/104/vinyl.lua I> log level 5 (INFO)                                                                         
2024-06-06 16:16:17.943 [1032052] main/104/vinyl.lua I> wal/engine cleanup is paused                                                               
2024-06-06 16:16:17.943 [1032052] main/104/vinyl.lua I> mapping 67108864 bytes for memtx tuple arena...                                            
2024-06-06 16:16:17.943 [1032052] main/104/vinyl.lua I> Actual slab_alloc_factor calculated on the basis of desired slab_alloc_factor = 1.044274   
2024-06-06 16:16:17.943 [1032052] main/104/vinyl.lua I> mapping 16777216 bytes for vinyl tuple arena...                                            
2024-06-06 16:16:17.950 [1032052] main/104/vinyl.lua I> update replication_synchro_quorum = 1                                                      
2024-06-06 16:16:17.950 [1032052] main/104/vinyl.lua I> instance uuid 9876c4db-9261-438e-9a31-ce9587a2fe0f                                         
2024-06-06 16:16:17.951 [1032052] main/104/vinyl.lua I> initializing an empty data directory                                                       
2024-06-06 16:16:17.973 [1032052] main/104/vinyl.lua I> assigned id 1 to replica 9876c4db-9261-438e-9a31-ce9587a2fe0f                              
2024-06-06 16:16:17.974 [1032052] main/104/vinyl.lua I> update replication_synchro_quorum = 1                                                      
2024-06-06 16:16:17.974 [1032052] main/104/vinyl.lua I> replicaset uuid fabb3d48-b6fe-4932-8cf5-ddc0aca1c0dd                                       
2024-06-06 16:16:17.976 [1032052] snapshot/101/main I> saving snapshot `./00000000000000000000.snap.inprogress'                                    
2024-06-06 16:16:17.987 [1032052] snapshot/101/main I> done                                                                                        
2024-06-06 16:16:17.988 [1032052] main/104/vinyl.lua I> ready to accept requests                                                                   
2024-06-06 16:16:17.988 [1032052] main/105/gc I> wal/engine cleanup is resumed                                                                     
2024-06-06 16:16:17.988 [1032052] main/104/vinyl.lua/box.load_cfg I> set 'memtx_memory' configuration option to 1048576                            
2024-06-06 16:16:17.988 [1032052] main/104/vinyl.lua/box.load_cfg I> set 'vinyl_memory' configuration option to 10485760                           
2024-06-06 16:16:17.988 [1032052] main/104/vinyl.lua/box.load_cfg I> set 'vinyl_cache' configuration option to 4                                   
2024-06-06 16:16:17.988 [1032052] main/104/vinyl.lua/box.load_cfg I> set 'vinyl_timeout' configuration option to 1                                 
2024-06-06 16:16:17.988 [1032052] main/104/vinyl.lua/box.load_cfg I> set 'vinyl_max_tuple_size' configuration option to 93597                      
2024-06-06 16:16:17.988 [1032052] main/104/vinyl.lua/box.load_cfg I> set 'checkpoint_wal_threshold' configuration option to 436                    
2024-06-06 16:16:17.988 [1032052] main/104/vinyl.lua/box.load_cfg I> set 'checkpoint_interval' configuration option to 59 
2024-06-06 16:16:17.990 [1032052] main/104/vinyl.lua/vinyl I> FINISH BOX.CFG                                                                       
2024-06-06 16:16:17.990 [1032052] main/104/vinyl.lua/vinyl I> CREATE A SPACE                                                                       
2024-06-06 16:16:17.990 [1032052] main/104/vinyl.lua/vinyl I> {"format":[{"name":"name_1","type":"decimal"},{"name":"name_2","type":"boolean"},{"name":"name_3","type":"boolean"},{"name":"name_4","type":"decimal"},{"name":"name_5","type":"decimal"},{"name":"name_6","type":"uuid"},{"name":"name_7","type":"string"},{"name":"name_8","type":"boolean"}],"if_not_exists":true,"is_local":false,"field_count":0,"engine":"vinyl"}                    
2024-06-06 16:16:17.990 [1032052] main/106/checkpoint_daemon I> scheduled next checkpoint for Thu Jun  6 16:17:34 2024                             
2024-06-06 16:16:17.992 [1032052] main/104/vinyl.lua/vinyl I> ERROR: Can't create or modify index 'idx_1' in space 'test_1': primary key must be un
ique ({"unique":false,"parts":[["name_1"],["name_2"],["name_3"],["name_4"]],"if_not_exists":false,"bloom_fpr":0.22,"type":"TREE"})                 
2024-06-06 16:16:17.996 [1032052] main I> WAL threshold exceeded, triggering checkpoint                                                            
2024-06-06 16:16:17.996 [1032052] main/104/vinyl.lua/vinyl I> FINISH SETUP  

<snipped>

2024-06-06 16:16:19.308 [1032052] main/179/WRK #66/vinyl I> ["SELECT_OP",[["978465488988",false,false,"11906549410","540934988252"]]]
2024-06-06 16:16:19.308 [1032052] main/249/WRK #136/vinyl I> ["SELECT_OP",[["616480171344",false,false,"615336942821","41850166946"]]]
2024-06-06 16:16:19.308 [1032052] main/223/WRK #110/vinyl I> ["SELECT_OP",[["847356092408",false,false,"859627501068","393581584348"]]]
2024-06-06 16:16:19.309 [1032052] main/132/WRK #19/vinyl I> ["SELECT_OP",[["334999508566",true,true,"307315568864","763916721729"]]]
2024-06-06 16:16:19.309 [1032052] main/164/WRK #51/vinyl I> ["SELECT_OP",[["588381090551",true,true,"227374203854","853313784739"]]]
tarantool: ./src/box/tuple_compare.cc:250: int mp_compare_decimal(const char*, const char*): Assertion `ret != NULL' failed.
Aborted (core dumped)
```

Backtrace:

```c++
#3  0x00007e5089242476 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#4  0x00007e50892287f3 in __GI_abort () at ./stdlib/abort.c:79
#5  0x00007e508922871b in __assert_fail_base (fmt=0x7e50893dd130 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", 
    assertion=0x5e236104e5c9 "ret != NULL", file=0x5e236104e341 "./src/box/tuple_compare.cc", line=250, function=<optimized out>)
    at ./assert/assert.c:92
#6  0x00007e5089239e96 in __GI___assert_fail (assertion=0x5e236104e5c9 "ret != NULL", file=0x5e236104e341 "./src/box/tuple_compare.cc", line=250, 
    function=0x5e236104e598 "int mp_compare_decimal(const char*, const char*)") at ./assert/assert.c:101
#7  0x00005e2360cd3f18 in mp_compare_decimal (lhs=0x5e23629f3c6f "\327\001", rhs=0x5e23629f3c05 "\303\327\001")
    at /home/sergeyb/sources/MRG/tarantool/src/box/tuple_compare.cc:250
#8  0x00005e2360cd4c88 in tuple_compare_field (field_a=0x5e23629f3c65 "\327\001", field_b=0x5e23629f3c05 "\303\327\001", type=9 '\t', coll=0x0)
    at /home/sergeyb/sources/MRG/tarantool/src/box/tuple_compare.cc:551
#9  0x00005e2360cda30e in key_part_compare_fields<false, false, false, false> (was_null_met=0x7e505b880639, 
    field_b=0x5e23629f3c05 "\303\327\001", field_a=0x5e23629f3c65 "\327\001", part=0x5e23626f1950)
    at /home/sergeyb/sources/MRG/tarantool/src/box/tuple_compare.cc:675
#10 key_compare_and_skip_parts<false, false> (key_a=0x7e505b8805e8, key_b=0x7e505b8805e0, part_count=5, key_def=0x5e23626f1800, 
    was_null_met=0x7e505b880639) at /home/sergeyb/sources/MRG/tarantool/src/box/tuple_compare.cc:908
#11 0x00005e2360cd6d26 in key_compare_parts<false, false> (key_a=0x5e23629f3c65 "\327\001", key_b=0x5e23629f3c05 "\303\327\001", part_count=5, 
    key_def=0x5e23626f1800, was_null_met=0x7e505b880639) at /home/sergeyb/sources/MRG/tarantool/src/box/tuple_compare.cc:921
#12 0x00005e2360cd92b6 in tuple_compare_sequential<false, false, false> (tuple_a=0x5e23629f3c40, tuple_a_hint=18446744073709551615, 
    tuple_b=0x5e23629f3be0, tuple_b_hint=18446744073709551615, key_def=0x5e23626f1800)
    at /home/sergeyb/sources/MRG/tarantool/src/box/tuple_compare.cc:1022
#13 0x00005e236083a111 in tuple_compare (tuple_a=0x5e23629f3c40, tuple_a_hint=18446744073709551615, tuple_b=0x5e23629f3be0, 
    tuple_b_hint=18446744073709551615, key_def=0x5e23626f1800) at /home/sergeyb/sources/MRG/tarantool/src/box/key_def.h:1077
#14 0x00005e236083a788 in vy_stmt_compare (a=0x5e23629f3c40, a_hint=18446744073709551615, b=0x5e23629f3be0, b_hint=18446744073709551615, 
    key_def=0x5e23626f1800) at /home/sergeyb/sources/MRG/tarantool/src/box/vy_stmt.h:427
#15 0x00005e236083b4e0 in vy_apply_result_does_cross_pk (old_stmt=0x5e23629f3c40, result=0x7e5086898540 "\231\327\001", 
    result_end=0x7e5086898580 'P' <repeats 200 times>..., cmp_def=0x5e23626f1800, col_mask=18446744073709551614)
    at /home/sergeyb/sources/MRG/tarantool/src/box/vy_upsert.c:53
#16 0x00005e236083b915 in vy_apply_upsert_on_terminal_stmt (upsert=0x5e2362a4f380, stmt=0x5e23629f3c40, cmp_def=0x5e23626f1800, 
    suppress_error=true) at /home/sergeyb/sources/MRG/tarantool/src/box/vy_upsert.c:139
#17 0x00005e236083bc83 in vy_apply_upsert (new_stmt=0x5e2362a4f380, old_stmt=0x5e23629f3c40, cmp_def=0x5e23626f1800, suppress_error=true)
    at /home/sergeyb/sources/MRG/tarantool/src/box/vy_upsert.c:204
#18 0x00005e236083c8b5 in vy_entry_apply_upsert (new_entry=..., old_entry=..., cmp_def=0x5e23626f1800, suppress_error=true)
    at /home/sergeyb/sources/MRG/tarantool/src/box/vy_upsert.h:76
#19 0x00005e236083cce4 in vy_history_apply (history=0x7e505b880a80, cmp_def=0x5e23626f1800, keep_delete=true, upserts_applied=0x7e505b880a64, 
    ret=0x7e505b880ac0) at /home/sergeyb/sources/MRG/tarantool/src/box/vy_history.c:106
#20 0x00005e236081f44d in vy_read_iterator_apply_history (itr=0x7e5049340110, ret=0x7e505b880ac0)
    at /home/sergeyb/sources/MRG/tarantool/src/box/vy_read_iterator.c:886
#21 0x00005e236081f667 in vy_read_iterator_next (itr=0x7e5049340110, result=0x7e505b880b30)
    at /home/sergeyb/sources/MRG/tarantool/src/box/vy_read_iterator.c:930
#22 0x00005e23607e06e0 in vinyl_iterator_primary_next (base=0x7e5049340090, ret=0x7e505b880c10)
    at /home/sergeyb/sources/MRG/tarantool/src/box/vinyl.c:3656
#23 0x00005e2360779be2 in iterator_next (it=0x7e5049340090, ret=0x7e505b880c10) at /home/sergeyb/sources/MRG/tarantool/src/box/index.cc:645
#24 0x00005e23608acd69 in box_select (space_id=512, index_id=0, iterator=3, offset=8, limit=106, key=0x7e5086898241 "\327\001", 
    key_end=0x7e5086898261 "PPPPPPP\340Q\030a#^", packed_pos=0x7e505b880ce8, packed_pos_end=0x7e505b880cf0, update_pos=false, port=0x7e505b880d00)
    at /home/sergeyb/sources/MRG/tarantool/src/box/box.cc:3851
#25 0x00005e23609c0373 in lbox_select (L=0x4086f460) at /home/sergeyb/sources/MRG/tarantool/src/box/lua/misc.cc:445
#26 0x00005e2360a89cc7 in lj_BC_FUNCC () at buildvm_x86.dasc:811
#27 0x00005e2360a9783f in lua_pcall (L=0x4086f460, nargs=1, nresults=-1, errfunc=0)
    at /home/sergeyb/sources/MRG/tarantool/third_party/luajit/src/lj_api.c:1173
#28 0x00005e23609fcafc in luaT_call (L=0x4086f460, nargs=1, nreturns=-1) at /home/sergeyb/sources/MRG/tarantool/src/lua/utils.c:687
#29 0x00005e23609f2d1c in lua_fiber_run_f (ap=0x7e50868172b0) at /home/sergeyb/sources/MRG/tarantool/src/lua/fiber.c:426
#30 0x00005e2360759147 in fiber_cxx_invoke(fiber_func, typedef __va_list_tag __va_list_tag *) (f=0x5e23609f2c5f <lua_fiber_run_f>, 
```

**Expected behavior**

**Comment by locker** [comment]
Duplicate of #10099.

**Comment by locker** [comment]
Duplicate of #10099.
