### ISSUE TITLE
Attempting to access freed Gcudata memory

### ISSUE THREAD

**Issue by mandesero** [tarantool/tarantool#10177]
**Bug description**

ASAN detected an access to already freed GCudata memory.

* OS: Linux
* OS Version: Debian 11
* Architecture: amd64

**`tarantool --version` output:**
Tarantool 3.2.0-entrypoint-84-g9d3859b24
Target: Linux-x86_64-Debug
Build options: cmake . -DCMAKE_INSTALL_PREFIX=/usr/local -DENABLE_BACKTRACE=TRUE
Compiler: Clang-14.0.0
```
C_FLAGS: -fexceptions -funwind-tables -fasynchronous-unwind-tables -fno-common -msse2 -fsanitize=fuzzer-no-link -fsanitize=address -fsanitize-blacklist=/home/mandesero/tarantool/asan/asan.supp  -fmacro-prefix-map=/home/mandesero/tarantool=. -std=c11 -Wall -Wextra -fsanitize=alignment,bool,bounds,builtin,enum,float-cast-overflow,float-divide-by-zero,function,integer-divide-by-zero,return,shift,unreachable,vla-bound -fno-sanitize-recover=alignment,bool,bounds,builtin,enum,float-cast-overflow,float-divide-by-zero,function,integer-divide-by-zero,return,shift,unreachable,vla-bound -Wno-gnu-alignof-expression -Wno-cast-function-type -Werror -Werror -g -ggdb -O0
CXX_FLAGS: -fexceptions -funwind-tables -fasynchronous-unwind-tables -fno-common -msse2 -fsanitize=fuzzer-no-link -fsanitize=address -fsanitize-blacklist=/home/mandesero/tarantool/asan/asan.supp  -fmacro-prefix-map=/home/mandesero/tarantool=. -std=c++11 -Wall -Wextra -fsanitize=alignment,bool,bounds,builtin,enum,float-cast-overflow,float-divide-by-zero,function,integer-divide-by-zero,return,shift,unreachable,vla-bound -fno-sanitize-recover=alignment,bool,bounds,builtin,enum,float-cast-overflow,float-divide-by-zero,function,integer-divide-by-zero,return,shift,unreachable,vla-bound -Wno-invalid-offsetof -Wno-gnu-alignof-expression -Wno-cast-function-type -Werror -Werror -g -ggdb -O0
```
**Steps to reproduce**

```
cd tarantool/third_party/luajit
git checkout mandesero/dlmalloc-instr
```

```
cmake -S . -B . -DENABLE_WERROR=ON -DENABLE_ASAN=ON -DENABLE_UB_SANITIZER=ON -DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION=OFF -DENABLE_FUZZER=ON -DTEST_BUILD=ON -DCMAKE_BUILD_TYPE=RelWithDebInfo -DFIBER_STACK_SIZE=640Kb -DLUAJIT_ENABLE_GC64=ON -DCMAKE_BUILD_TYPE=Debug && make -j
cd test
gdb --args ../src/tarantool -i
(tarantool) \set output lua
```

**Actual behavior**

```
ERROR: AddressSanitizer: use-after-poison on address 0x7ffff27b4ddc

READ of size 4 at 0x7ffff27b4ddc thread T0
[Detaching after fork from child process 171534]
    #0 0x555557b3a6de in lua_field_inspect_table /home/mandesero/tarantool/src/lua/serializer.c:369:11
    #1 0x555557b39c02 in luaL_tofield /home/mandesero/tarantool/src/lua/serializer.c:588:10
    #2 0x5555579ba063 in luaL_checkfield /home/mandesero/tarantool/src/lua/serializer.h:329:6
    #3 0x5555579b8c76 in dump_root /home/mandesero/tarantool/src/box/lua/serialize_lua.c:948:2
    #4 0x5555579b7779 in lua_encode /home/mandesero/tarantool/src/box/lua/serialize_lua.c:999:6
    #5 0x5555579a1fac in lbox_console_format_lua /home/mandesero/tarantool/src/box/lua/console.c:126:12
    #6 0x555557ea4608 in lj_BC_FUNCC /home/mandesero/tarantool/third_party/luajit/src/lj_vm.S:852
    #7 0x555557ecf1ca in lua_pcall /home/mandesero/tarantool/third_party/luajit/src/lj_api.c:1173:12
    #8 0x555557b2926e in luaT_call /home/mandesero/tarantool/src/lua/utils.c:689:6
    #9 0x555557ae9389 in lua_main /home/mandesero/tarantool/src/lua/init.c:916:11
    #10 0x555557ae0c54 in run_script_f /home/mandesero/tarantool/src/lua/init.c:1158:7
    #11 0x5555568d39b3 in fiber_cxx_invoke(int (*)(__va_list_tag*), __va_list_tag*) /home/mandesero/tarantool/src/lib/core/fiber.h:1308:10
    #12 0x555557c0e92b in fiber_loop /home/mandesero/tarantool/src/lib/core/fiber.c:1153:18
    #13 0x555558c33858 in coro_init /home/mandesero/tarantool/third_party/coro/coro.c:108:3

Address 0x7ffff27b4ddc is a wild pointer inside of access range of size 0x000000000004.
SUMMARY: AddressSanitizer: use-after-poison /home/mandesero/tarantool/src/lua/serializer.c:369:11 in lua_field_inspect_table
```

***Notes***
tarantool/src/lua/serializer.c:369:11: `if (cfg->encode_load_metatables) {`

`cfg=0x7ffff27b4dc0` is part of GCudata allocated in `lj_udata_new (L=0x7ffff4b663b8, sz=136, env=0x7ffff4b67ea8) at /home/mandesero/tarantool/third_party/luajit/src/lj_udata.c:26`, where `ud=0x7ffff27b4d90,`.

Then `ud` is freed

BT:
```
#0  lj_alloc_free (msp=0x7ffff4b66030, ptr=0x7ffff27b4d90) at /home/mandesero/tarantool/third_party/luajit/src/lj_alloc.c:1592
#1  0x000055555801ea2a in lj_alloc_f (msp=0x7ffff4b66030, ptr=0x7ffff27b4d90, osize=184, nsize=0) at /home/mandesero/tarantool/third_party/luajit/src/lj_alloc.c:1742
#2  0x0000555557f54045 in lj_mem_free (g=0x7ffff4b66418, p=0x7ffff27b4d90, osize=184) at /home/mandesero/tarantool/third_party/luajit/src/lj_gc.h:119
#3  lj_udata_free (g=0x7ffff4b66418, ud=0x7ffff27b4d90) at /home/mandesero/tarantool/third_party/luajit/src/lj_udata.c:35
#4  0x0000555557efc863 in gc_sweep (g=0x7ffff4b66418, p=0x7ffff27b56a0, lim=12) at /home/mandesero/tarantool/third_party/luajit/src/lj_gc.c:415
#5  0x0000555557efda8f in gc_onestep (L=0x7ffff4b663b8) at /home/mandesero/tarantool/third_party/luajit/src/lj_gc.c:693
#6  0x0000555557efcbd9 in lj_gc_step (L=0x7ffff4b663b8) at /home/mandesero/tarantool/third_party/luajit/src/lj_gc.c:745
#7  0x0000555557efec96 in lj_gc_step_jit (g=0x7ffff4b66418, steps=0) at /home/mandesero/tarantool/third_party/luajit/src/lj_gc.c:778
``` 

**Expected behavior**

```
(tarantool) \set language lua
 - true # no asan error
```

**Comment by Gumix** [comment]
Looks similar to:
- https://github.com/tarantool/tarantool/issues/7404
