### ISSUE TITLE
Segmentation fault in tuple_compare_slowpath

### ISSUE THREAD

**Issue by ligurio** [tarantool/tarantool#10238]
**Bug description**

* OS: Linux
* OS Version: Ubuntu 22.04
* Architecture: amd64

Tarantool 3.2.0-entrypoint-124-g5208ea473b
Target: Linux-x86_64-Debug
Build options: cmake . -DCMAKE_INSTALL_PREFIX=/usr/local -DENABLE_BACKTRACE=TRUE
Compiler: GNU-11.4.0
C_FLAGS: -fexceptions -funwind-tables -fasynchronous-unwind-tables -fno-common -msse2 -Wformat -Wformat-security -Werror=format-security -fstack-protector-strong -fPIC -fmacro-prefix-map=/home/sergeyb/sources/MRG/tarantool=. -std=c11 -Wall -Wextra -Wno-gnu-alignof-expression -fno-gnu89-inline -Wno-cast-function-type -Werror -g -ggdb -O0
CXX_FLAGS: -fexceptions -funwind-tables -fasynchronous-unwind-tables -fno-common -msse2 -Wformat -Wformat-security -Werror=format-security -fstack-protector-strong -fPIC -fmacro-prefix-map=/home/sergeyb/sources/MRG/tarantool=. -std=c++11 -Wall -Wextra -Wno-invalid-offsetof -Wno-gnu-alignof-expression -Wno-cast-function-type -Werror -g -ggdb -O0

**Steps to reproduce**

```
$ ./build/src/tarantool test/fuzz/lua/test_engine.lua --test_duration $((10*60)) --engine memtx --workers 1000
```

**Actual behavior**

```
2024-07-12 11:16:27.033 [3871453] main/320/WRK #207/test.fuzz.lua.test_engine I> BSIZE_OP []
2024-07-12 11:16:27.033 [3871453] main/320/WRK #207/test.fuzz.lua.test_engine I> TX_ROLLBACK []
2024-07-12 11:16:27.034 [3871453] main/320/WRK #207/test.fuzz.lua.test_engine I> DELETE_OP [["0d7ba872-9a69-41e5-990e-4fcbe8be3986",91369382095.466,343623642873]]
2024-07-12 11:16:27.034 [3871453] main/323/WRK #210/test.fuzz.lua.test_engine I> INDEX_DELETE_OP [{"unique":true,"parts":[{"fieldno":3,"sort_order":"asc","type":"uuid","exclude_null":false,"is_nullable":false},{"fieldno":1,"sort_order":"asc","type":"double","exclude_null":false,"is_nullable":false},{"fieldno":2,"sort_order":"asc","type":"unsigned","exclude_null":false,"is_nullable":false}],"hint":true,"id":0,"type":"TREE","space_id":512,"name":"idx_1"},["03e02d5a-2b3a-4102-9fc4-d27663d67761",95549861415.022,307337052083]]
2024-07-12 11:16:27.034 [3871453] main/324/WRK #211/test.fuzz.lua.test_engine I> LEN_OP []
2024-07-12 11:16:27.034 [3871453] main/325/WRK #212/test.fuzz.lua.test_engine I> INDEX_DROP_OP [{"unique":true,"parts":[{"fieldno":3,"sort_order":"asc","type":"uuid","exclude_null":false,"is_nullable":false},{"fieldno":1,"sort_order":"asc","type":"double","exclude_null":false,"is_nullable":false},{"fieldno":2,"sort_order":"asc","type":"unsigned","exclude_null":false,"is_nullable":false}],"hint":true,"id":0,"type":"TREE","space_id":512,"name":"idx_1"}]
2024-07-12 11:16:27.035 [3871453] main/325/WRK #212/test.fuzz.lua.test_engine I> ERROR: opname "INDEX_DROP_OP", err "Field 2 was not found in the tuple", args [{"unique":true,"parts":[{"fieldno":3,"sort_order":"asc","type":"uuid","exclude_null":false,"is_nullable":false},{"fieldno":1,"sort_order":"asc","type":"double","exclude_null":false,"is_nullable":false},{"fieldno":2,"sort_order":"asc","type":"unsigned","exclude_null":false,"is_nullable":false}],"hint":true,"id":0,"type":"TREE","space_id":512,"name":"idx_1"}]
2024-07-12 11:16:27.035 [3871453] main/325/WRK #212/test.fuzz.lua.test_engine I> SNAPSHOT_OP []
2024-07-12 11:16:27.035 [3871453] main/325/WRK #212/test.fuzz.lua.test_engine I> TX_COMMIT []
2024-07-12 11:16:27.035 [3871453] main/325/WRK #212/test.fuzz.lua.test_engine I> FORMAT_OP [[{"name":"field_1","type":"double"},{"name":"field_2","type":"unsigned"},{"name":"field_3","type":"uuid"},{"name":"field_4","type":"integer"},{"name":"field_5","type":"string"},{"name":"field_6","type":"number"},{"name":"field_7","type":"boolean"},{"name":"field_8","type":"decimal"},{"name":"field_9","type":"datetime"},{"name":"field_10","type":"array"},{"name":"field_11","type":"map"}]]
tarantool: ./src/box/tuple_compare.cc:750: int tuple_compare_slowpath(tuple*, hint_t, tuple*, hint_t, key_def*) [with bool is_nullable = false; bool has_optional_parts = false; bool has_json_paths = false; bool is_multikey = false; bool has_desc_parts = false; hint_t = long unsigned int]: Assertion `has_optional_parts || (field_a != NULL && field_b != NULL)' failed.
Aborted (core dumped)
```

tarantool binary and coredump 
[gh-10238.zip](https://github.com/user-attachments/files/16190831/gh-10238.zip)

```c++
#0  __pthread_kill_implementation (no_tid=0, signo=6, threadid=139761015700160) at ./nptl/pthread_kill.c:44
#1  __pthread_kill_internal (signo=6, threadid=139761015700160) at ./nptl/pthread_kill.c:78
#2  __GI___pthread_kill (threadid=139761015700160, signo=signo@entry=6) at ./nptl/pthread_kill.c:89
#3  0x00007f1ca4e42476 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#4  0x00007f1ca4e287f3 in __GI_abort () at ./stdlib/abort.c:79
#5  0x00007f1ca4e2871b in __assert_fail_base (fmt=0x7f1ca4fdd130 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", 
    assertion=0x556c7cc44b00 "has_optional_parts || (field_a != NULL && field_b != NULL)", file=0x556c7cc43b41 "./src/box/tuple_compare.cc", 
    line=750, function=<optimized out>) at ./assert/assert.c:92
#6  0x00007f1ca4e39e96 in __GI___assert_fail (assertion=0x556c7cc44b00 "has_optional_parts || (field_a != NULL && field_b != NULL)", 
    file=0x556c7cc43b41 "./src/box/tuple_compare.cc", line=750, 
    function=0x556c7cc449b0 "int tuple_compare_slowpath(tuple*, hint_t, tuple*, hint_t, key_def*) [with bool is_nullable = false; bool has_optional_parts = false; bool has_json_paths = false; bool is_multikey = false; bool has_de"...) at ./assert/assert.c:101
#7  0x0000556c7c8c89d5 in tuple_compare_slowpath<false, false, false, false, false> (tuple_a=0x556c7d059a6c, tuple_a_hint=2882303761517117441, 
    tuple_b=0x556c7d76906c, tuple_b_hint=2882303761517117441, key_def=0x556c7d0d73e0)
    at /home/sergeyb/sources/MRG/tarantool/src/box/tuple_compare.cc:750
#8  0x0000556c7c362fce in tuple_compare (tuple_a=0x556c7d059a6c, tuple_a_hint=2882303761517117441, tuple_b=0x556c7d76906c, 
    tuple_b_hint=2882303761517117441, key_def=0x556c7d0d73e0) at /home/sergeyb/sources/MRG/tarantool/src/box/key_def.h:1077
#9  0x0000556c7c36e27b in NS_USE_HINT::bps_tree_memtx_tree_find_ins_point_elem (tree=0x556c7d0d9278, arr=0x7f1c9804c010, size=27, elem=..., 
    exact=0x7f1c31a80357) at /home/sergeyb/sources/MRG/tarantool/src/lib/salad/bps_tree.h:2077
#10 0x0000556c7c36f969 in NS_USE_HINT::bps_tree_memtx_tree_collect_path (tree=0x556c7d0d9278, new_elem=..., path=0x7f1c31a803a0, 
    leaf_path_elem=0x7f1c31a80370, exact=0x7f1c31a80357) at /home/sergeyb/sources/MRG/tarantool/src/lib/salad/bps_tree.h:3508
#11 0x0000556c7c3766fc in NS_USE_HINT::memtx_tree_insert (t=0x556c7d0d9278, new_elem=..., replaced=0x7f1c31a806b0, successor=0x7f1c31a806c0)
    at /home/sergeyb/sources/MRG/tarantool/src/lib/salad/bps_tree.h:6045
#12 0x0000556c7c378bc1 in memtx_tree_index_replace<true> (base=0x556c7d0d9240, old_tuple=0x0, new_tuple=0x556c7d76906c, 
    mode=DUP_REPLACE_OR_INSERT, result=0x7f1c31a80768, successor=0x7f1c31a80748) at /home/sergeyb/sources/MRG/tarantool/src/box/memtx_tree.cc:1228
#13 0x0000556c7c38833f in index_replace (index=0x556c7d0d9240, old_tuple=0x0, new_tuple=0x556c7d76906c, mode=DUP_REPLACE_OR_INSERT, 
    result=0x7f1c31a80768, successor=0x7f1c31a80748) at /home/sergeyb/sources/MRG/tarantool/src/box/index.h:917
#14 0x0000556c7c38fa78 in memtx_tx_history_add_insert_stmt (stmt=0x7f1c003bb290, old_tuple=0x556c7cf5ea0c, new_tuple=0x556c7d76906c, 
    mode=DUP_REPLACE, result=0x7f1c31a809e8) at /home/sergeyb/sources/MRG/tarantool/src/box/memtx_tx.c:2000
#15 0x0000556c7c3901c1 in memtx_tx_history_add_stmt (stmt=0x7f1c003bb290, old_tuple=0x556c7cf5ea0c, new_tuple=0x556c7d76906c, mode=DUP_REPLACE, 
    result=0x7f1c31a809e8) at /home/sergeyb/sources/MRG/tarantool/src/box/memtx_tx.c:2158
#16 0x0000556c7c3a57ce in memtx_space_replace_all_keys (space=0x556c7d05a720, old_tuple=0x556c7cf5ea0c, new_tuple=0x556c7d76906c, 
    mode=DUP_REPLACE, result=0x7f1c31a809e8) at /home/sergeyb/sources/MRG/tarantool/src/box/memtx_space.c:328
#17 0x0000556c7c3a5a4a in memtx_space_replace_tuple (space=0x556c7d05a720, stmt=0x7f1c003bb290, old_tuple=0x556c7cf5ea0c, 
    new_tuple=0x556c7d76906c, mode=DUP_REPLACE) at /home/sergeyb/sources/MRG/tarantool/src/box/memtx_space.c:399
#18 0x0000556c7c3a619d in memtx_space_execute_update (space=0x556c7d05a720, txn=0x7f1c003bb038, request=0x7f1c31a80c10, result=0x7f1c31a80b78)
    at /home/sergeyb/sources/MRG/tarantool/src/box/memtx_space.c:538
#19 0x0000556c7c430c88 in space_execute_dml (space=0x556c7d05a720, txn=0x7f1c003bb038, request=0x7f1c31a80c10, result=0x7f1c31a80b78)
    at /home/sergeyb/sources/MRG/tarantool/src/box/space.c:1364
#20 0x0000556c7c47e690 in box_process_rw (request=0x7f1c31a80c10, space=0x556c7d05a720, result=0x7f1c31a80d30)
    at /home/sergeyb/sources/MRG/tarantool/src/box/box.cc:491
#21 0x0000556c7c48b58d in box_process1 (request=0x7f1c31a80c10, result=0x7f1c31a80d30) at /home/sergeyb/sources/MRG/tarantool/src/box/box.cc:3731
#22 0x0000556c7c48c3da in box_update (space_id=280, index_id=0, key=0x7f1ca24e3240 "\221\315\002", 
    key_end=0x7f1ca24e3244 "\221\223\241=\a\233\202\244name\247field_1\244type\246double\202\244name\247field_2\244type\250unsigned\202\244name\247field_3\244type\244uuid\202\244name\247field_4\244type\247integer\202\244name\247field_5\244type\246string\202\244name\247field_6\244type\246number\202\244name\247field_7\244type\247boolean\202\244name\247fie"..., 
    ops=0x7f1ca24e3244 "\221\223\241=\a\233\202\244name\247field_1\244type\246double\202\244name\247field_2\244type\250unsigned\202\244name\247field_3\244type\244uuid\202\244name\247field_4\244type\247integer\202\244name\247field_5\244type\246string\202\244name\247field_6\244type\246number\202\244name\247field_7\244type\247boolean\202\244name\247fie"..., ops_end=0x7f1ca24e336b 'P' <repeats 200 times>..., index_base=1, 
    result=0x7f1c31a80d30) at /home/sergeyb/sources/MRG/tarantool/src/box/box.cc:3967
#23 0x0000556c7c596a26 in lbox_index_update (L=0x409fa958) at /home/sergeyb/sources/MRG/tarantool/src/box/lua/index.c:113
#24 0x0000556c7c66e247 in lj_BC_FUNCC () at buildvm_x86.dasc:811
#25 0x0000556c7c67bdbf in lua_pcall (L=0x409fa958, nargs=4, nresults=-1, errfunc=0)
    at /home/sergeyb/sources/MRG/tarantool/third_party/luajit/src/lj_api.c:1173
#26 0x0000556c7c5df5cc in luaT_call (L=0x409fa958, nargs=4, nreturns=-1) at /home/sergeyb/sources/MRG/tarantool/src/lua/utils.c:689
#27 0x0000556c7c5d4399 in lua_fiber_run_f (ap=0x7f1ca248a160) at /home/sergeyb/sources/MRG/tarantool/src/lua/fiber.c:435
#28 0x0000556c7c338187 in fiber_cxx_invoke(fiber_func, typedef __va_list_tag __va_list_tag *) (f=0x556c7c5d42dc <lua_fiber_run_f>, 
    ap=0x7f1ca248a160) at /home/sergeyb/sources/MRG/tarantool/src/lib/core/fiber.h:1311
#29 0x0000556c7c6101bc in fiber_loop (data=0x0) at /home/sergeyb/sources/MRG/tarantool/src/lib/core/fiber.c:1162
#30 0x0000556c7ca04576 in coro_init () at /home/sergeyb/sources/MRG/tarantool/third_party/coro/coro.c:108
```

**Expected behavior**

no crash

**Comment by locker** [comment]
The crash was caused by `ERRINJ_TUPLE_FIELD`, which causes `tuple_field_raw` return `NULL` instead of a tuple field:

```
(gdb) p errinjs[ERRINJ_TUPLE_FIELD]
$96 = {name = 0x556c7cbfbba4 "ERRINJ_TUPLE_FIELD", type = ERRINJ_BOOL, {bparam = true, iparam = 1, dparam = 4.9406564584124654e-324}}
```

https://github.com/tarantool/tarantool/blob/b0b32bff022caeffd64ca687baab908f25fa2fcb/src/box/tuple.h#L1045

**Comment by ligurio** [comment]
A list of error injections used in the test has been updated, see https://github.com/tarantool/tarantool/issues/10236#issuecomment-2225347088
