### ISSUE TITLE
cdata finalizer is not called for object created in finalizer

### ISSUE THREAD

**Issue by nshy** [tarantool/tarantool#10246]
Found in `3.2.0-entrypoint-116-gbf01fb200`.

```lua
local ffi = require('ffi')
ffi.cdef[[
void *malloc(size_t size);
void free(void *ptr);
]]
local a = newproxy(true)
getmetatable(a).__gc = function(_)
    local p = ffi.C.malloc(1)
    ffi.gc(p, ffi.C.free)
end
os.exit()
```

With ASAN build of Tarantool:
```
$ ./build-asan-debug/src/tarantool test.lua

=================================================================
==1327110==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 1 byte(s) in 1 object(s) allocated from:
    #0 0x653c5dd13e09 in malloc (/home/shiny/dev/tarantool/build-asan-debug/src/tarantool+0x1244e09) (BuildId: 37888f30512a78b3a7c638bc109f1b5c5fdf0d05)
    #1 0x653c5f37dd71 in lj_vm_ffi_call /home/shiny/dev/tarantool/build-asan-debug/third_party/luajit/src/lj_vm.S:2736
    #2 0x653c5f6a3a10 in lj_ccall_func /home/shiny/dev/tarantool/third_party/luajit/src/lj_ccall.c:1166:5
    #3 0x653c5f49c062 in lj_cf_ffi_meta___call /home/shiny/dev/tarantool/third_party/luajit/src/lib_ffi.c:230:15
    #4 0x653c5f37b4f6 in lj_BC_FUNCC /home/shiny/dev/tarantool/build-asan-debug/third_party/luajit/src/lj_vm.S:811

SUMMARY: AddressSanitizer: 1 byte(s) leaked in 1 allocation(s).
```

**Comment by Buristan** [comment]
This is a misuse of the LuaJIT FFI API. The finalizer function isn't supposed to be used for any new object creation. See the rationale [here](https://github.com/LuaJIT/LuaJIT/issues/896#issuecomment-1250348504).
Also, such allocation may raise the OOM error, whose behaviour is not well defined in the Lua Reference Manual, see more details [here](https://github.com/LuaJIT/LuaJIT/pull/946#issuecomment-1418947894).
