### ISSUE TITLE
SIGSEGV in bps_tree_memtx_tree_process_replace

### ISSUE THREAD

**Issue by ligurio** [tarantool/tarantool#10245]
**Bug description**

* OS: Linux
* OS Version: Ubuntu 22.04
* Architecture: amd64

Tarantool 3.2.0-entrypoint-124-g5208ea473b
Target: Linux-x86_64-Debug
Build options: cmake . -DCMAKE_INSTALL_PREFIX=/usr/local -DENABLE_BACKTRACE=TRUE
Compiler: GNU-11.4.0
C_FLAGS: -fexceptions -funwind-tables -fasynchronous-unwind-tables -fno-common -msse2 -Wformat -Wformat-security -Werror=format-security -fstack-protector-strong -fPIC -fmacro-prefix-map=/home/sergeyb/sources/MRG/tarantool=. -std=c11 -Wall -Wextra -Wno-gnu-alignof-expression -fno-gnu89-inline -Wno-cast-function-type -Werror -g -ggdb -O0 
CXX_FLAGS: -fexceptions -funwind-tables -fasynchronous-unwind-tables -fno-common -msse2 -Wformat -Wformat-security -Werror=format-security -fstack-protector-strong -fPIC -fmacro-prefix-map=/home/sergeyb/sources/MRG/tarantool=. -std=c++11 -Wall -Wextra -Wno-invalid-offsetof -Wno-gnu-alignof-expression -Wno-cast-function-type -Werror -g -ggdb -O0

**Steps to reproduce**

```
./build/src/tarantool test/fuzz/lua/test_engine.lua --test_duration $((10*60)) --engine memtx --workers 1000
```

**Actual behavior**

```c++
Please file a bug at https://github.com/tarantool/tarantool/issues
Attempting backtrace... Note: since the server has already crashed, 
this may fail as well
#1  0x558e0d745492 in crash_collect+256
#2  0x558e0d745ece in crash_signal_cb+100
#3  0x7eff3e642520 in __sigaction+80
#4  0x558e0d4b1b26 in _ZN11NS_USE_HINTL35bps_tree_memtx_tree_process_replaceEPNS_26bps_tree_memtx_tree_commonEPNS_28bpsmemtx_tree_leaf_path_elemE15me+79
#5  0x558e0d4b8738 in NS_USE_HINT::memtx_tree_insert(NS_USE_HINT::memtx_tree*, memtx_tree_data<true>, memtx_tree_data<true>*, memtx_tree_data<true>*)+251
#6  0x558e0d4babc1 in int memtx_tree_index_replace<true>(index*, tuple*, tuple*, dup_replace_mode, tuple**, tuple**)+278
#7  0x558e0d4ca33f in index_replace+80
#8  0x558e0d4cf39c in memtx_tx_story_link_top+607
#9  0x558e0d4cfd91 in memtx_tx_story_reorder+498
#10 0x558e0d4d251d in memtx_tx_history_rollback_added_story+564
#11 0x558e0d4d28f7 in memtx_tx_history_rollback_stmt+343
#12 0x558e0d4dee65 in memtx_engine_rollback_statement(engine*, txn*, txn_stmt*)+204
#13 0x558e0d5a9b3a in engine_rollback_statement+52
#14 0x558e0d5ab7a8 in txn_rollback_one_stmt+197
#15 0x558e0d5ab9f8 in txn_rollbackAborted (core dumped)
```

tarantool binary and coredump [gh-10245.zip](https://github.com/user-attachments/files/16196026/gh-10245.zip)

```c++
#0  __pthread_kill_implementation (no_tid=0, signo=6, threadid=139634748414656) at ./nptl/pthread_kill.c:44
#1  __pthread_kill_internal (signo=6, threadid=139634748414656) at ./nptl/pthread_kill.c:78
#2  __GI___pthread_kill (threadid=139634748414656, signo=signo@entry=6) at ./nptl/pthread_kill.c:89
#3  0x00007eff3e642476 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#4  0x00007eff3e6287f3 in __GI_abort () at ./stdlib/abort.c:79
#5  0x0000558e0d745f77 in crash_signal_cb (signo=11, siginfo=0x558e0f4b08f0, context=0x558e0f4b07c0)
    at /home/sergeyb/sources/MRG/tarantool/src/lib/core/crash.c:203
#6  <signal handler called>
#7  0x0000558e0d4b1b26 in NS_USE_HINT::bps_tree_memtx_tree_process_replace (tree=0x558e0f66a998, leaf_path_elem=0x7efeaf0804d0, new_elem=..., 
    replaced=0x7efeaf080810) at /home/sergeyb/sources/MRG/tarantool/src/lib/salad/bps_tree.h:3571
#8  0x0000558e0d4b8738 in NS_USE_HINT::memtx_tree_insert (t=0x558e0f66a998, new_elem=..., replaced=0x7efeaf080810, successor=0x7efeaf080820)
    at /home/sergeyb/sources/MRG/tarantool/src/lib/salad/bps_tree.h:6047
#9  0x0000558e0d4babc1 in memtx_tree_index_replace<true> (base=0x558e0f66a960, old_tuple=0x7eff302d4ae4, new_tuple=0x7eff30040a04, 
    mode=DUP_REPLACE, result=0x7efeaf0808b8, successor=0x7efeaf0808c0) at /home/sergeyb/sources/MRG/tarantool/src/box/memtx_tree.cc:1228
#10 0x0000558e0d4ca33f in index_replace (index=0x558e0f66a960, old_tuple=0x7eff302d4ae4, new_tuple=0x7eff30040a04, mode=DUP_REPLACE, 
    result=0x7efeaf0808b8, successor=0x7efeaf0808c0) at /home/sergeyb/sources/MRG/tarantool/src/box/index.h:917
#11 0x0000558e0d4cf39c in memtx_tx_story_link_top (new_top=0x7efe500600c8, old_top=0x7efe500629c0, idx=0, is_new_tuple=false)
    at /home/sergeyb/sources/MRG/tarantool/src/box/memtx_tx.c:1156
#12 0x0000558e0d4cfd91 in memtx_tx_story_reorder (story=0x7efe500629c0, old_story=0x7efe500600c8, idx=0)
    at /home/sergeyb/sources/MRG/tarantool/src/box/memtx_tx.c:1369
#13 0x0000558e0d4d251d in memtx_tx_history_rollback_added_story (stmt=0x7efe50be52f0)
    at /home/sergeyb/sources/MRG/tarantool/src/box/memtx_tx.c:2278
#14 0x0000558e0d4d28f7 in memtx_tx_history_rollback_stmt (stmt=0x7efe50be52f0) at /home/sergeyb/sources/MRG/tarantool/src/box/memtx_tx.c:2377
#15 0x0000558e0d4dee65 in memtx_engine_rollback_statement (engine=0x558e0f4defa0, txn=0x7efe50be5038, stmt=0x7efe50be52f0)
    at /home/sergeyb/sources/MRG/tarantool/src/box/memtx_engine.cc:650
#16 0x0000558e0d5a9b3a in engine_rollback_statement (engine=0x558e0f4defa0, txn=0x7efe50be5038, stmt=0x7efe50be52f0)
    at /home/sergeyb/sources/MRG/tarantool/src/box/engine.h:382
#17 0x0000558e0d5ab7a8 in txn_rollback_one_stmt (txn=0x7efe50be5038, stmt=0x7efe50be52f0) at /home/sergeyb/sources/MRG/tarantool/src/box/txn.c:367
#18 0x0000558e0d5ab9f8 in txn_rollback_to_svp (txn=0x7efe50be5038, svp=0x0, run_triggers=false)
    at /home/sergeyb/sources/MRG/tarantool/src/box/txn.c:416
#19 0x0000558e0d5aed35 in txn_rollback_stmt (txn=0x7efe50be5038) at /home/sergeyb/sources/MRG/tarantool/src/box/txn.c:1203
#20 0x0000558e0d5acd12 in txn_commit_stmt (txn=0x7efe50be5038, request=0x7efeaf080c30) at /home/sergeyb/sources/MRG/tarantool/src/box/txn.c:688
#21 0x0000558e0d5c0700 in box_process_rw (request=0x7efeaf080c30, space=0x558e0f4e63c0, result=0x7efeaf080d38)
    at /home/sergeyb/sources/MRG/tarantool/src/box/box.cc:508
#22 0x0000558e0d5cd58d in box_process1 (request=0x7efeaf080c30, result=0x7efeaf080d38) at /home/sergeyb/sources/MRG/tarantool/src/box/box.cc:3731
#23 0x0000558e0d5ce1d3 in box_replace (space_id=288, tuple=0x7eff3a785240 "\226\315\002", tuple_end=0x7eff3a78528e 'P' <repeats 200 times>..., 
    result=0x7efeaf080d38) at /home/sergeyb/sources/MRG/tarantool/src/box/box.cc:3931
#24 0x0000558e0d6d86f6 in lbox_replace (L=0x40deff50) at /home/sergeyb/sources/MRG/tarantool/src/box/lua/index.c:84
#25 0x0000558e0d7b0247 in lj_BC_FUNCC () at buildvm_x86.dasc:811
#26 0x0000558e0d7bddbf in lua_pcall (L=0x40deff50, nargs=4, nresults=-1, errfunc=0)
    at /home/sergeyb/sources/MRG/tarantool/third_party/luajit/src/lj_api.c:1173
#27 0x0000558e0d7215cc in luaT_call (L=0x40deff50, nargs=4, nreturns=-1) at /home/sergeyb/sources/MRG/tarantool/src/lua/utils.c:689
#28 0x0000558e0d716399 in lua_fiber_run_f (ap=0x7eff3bc8e010) at /home/sergeyb/sources/MRG/tarantool/src/lua/fiber.c:435
#29 0x0000558e0d47a187 in fiber_cxx_invoke(fiber_func, typedef __va_list_tag __va_list_tag *) (f=0x558e0d7162dc <lua_fiber_run_f>, 
    ap=0x7eff3bc8e010) at /home/sergeyb/sources/MRG/tarantool/src/lib/core/fiber.h:1311
#30 0x0000558e0d7521bc in fiber_loop (data=0x0) at /home/sergeyb/sources/MRG/tarantool/src/lib/core/fiber.c:1162
#31 0x0000558e0db46576 in coro_init () at /home/sergeyb/sources/MRG/tarantool/third_party/coro/coro.c:108
```

**Expected behavior**

no crash

**Comment by sergepetrenko** [comment]
Seems related to #10551

**Comment by nshy** [comment]
```c
 (gdb) f 5
Downloading source file /home/sergeyb/sources/MRG/tarantool/src/lib/salad/bps_tree.h
#5  0x0000558e0d4b1b26 in NS_USE_HINT::bps_tree_memtx_tree_process_replace (
    tree=0x558e0f66a998, leaf_path_elem=0x7efeaf0804d0, new_elem=...,
    replaced=0x7efeaf080810)
    at /home/sergeyb/sources/MRG/tarantool/src/lib/salad/bps_tree.h:3571
warning: 3571	/home/sergeyb/sources/MRG/tarantool/src/lib/salad/bps_tree.h: No such file or directory
 (gdb) l
warning: Source file is more recent than executable.
3566				 bps_tree_elem_t new_elem, bps_tree_elem_t *replaced)
3567	{
3568		leaf_path_elem->block = (struct bps_leaf *)
3569			bps_tree_touch_block(tree, leaf_path_elem->block_id);
3570		struct bps_leaf *leaf = leaf_path_elem->block;
3571		assert(leaf_path_elem->insertion_point < leaf->header.size);
3572	
3573		if (replaced)
3574			*replaced = leaf->elems[leaf_path_elem->insertion_point];
3575	
 (gdb) p leaf
$1 = (NS_USE_HINT::bpsmemtx_tree_leaf *) 0x0
 (gdb) p errinjs[ERRINJ_INDEX_ALLOC].bparam
$4 = true
```

Block touching returned `NULL` due to injection. So the issue is similar to #10551 yet rollback is not caused by WAL failure. The
TXN is aborted so PR #10564 should fix this issue too. Yet we'd better add test for this execution path too.

```c
 (gdb) p cord_ptr->fiber->storage.txn->status
$7 = TXN_ABORTED
```

**Comment by nshy** [comment]
0 estimation in case we decide to handle data OOM on top level as the issue will not be possible then.

**Comment by mkostoevr** [comment]
It seems it must be fixed already by #10564. @nshy, is it?

**Comment by nshy** [comment]
> It seems it must be fixed already by [#10564](https://github.com/tarantool/tarantool/pull/10564). [@nshy](https://github.com/nshy), is it?
Yes but I'd like to add a test.

**Comment by nshy** [comment]
non zere estimate) Looks like idea to handle data OOM on top level need more thought and we will not count on it now.

**Comment by drewdzzz** [comment]
MVCC OOM is moved here: https://github.com/tarantool/tarantool/issues/11602
