### ISSUE TITLE
SIGSEGV in lj_trace_unwind

### ISSUE THREAD

**Issue by ligurio** [tarantool/tarantool#10290]
**Bug description**

* OS: Linux
* OS Version: Ubuntu 24.04 LTS
* Architecture: amd64

tarantool version: 33670eae8afe425a0cd17067a114e7130b58bbd7

Tarantool 3.2.0-entrypoint-154-gfc3196dca
Target: Linux-x86_64-RelWithDebInfo
Build options: cmake . -DCMAKE_INSTALL_PREFIX=/usr/local -DENABLE_BACKTRACE=TRUE
Compiler: GNU-13.2.0
C_FLAGS: -fexceptions -funwind-tables -fasynchronous-unwind-tables -fno-common -msse2 -Wformat -Wformat-security -Werror=format-security -fstack-protector-strong -fPIC -fmacro-prefix-map=/home/ubuntu/tarantool=. -std=c11 -Wall -Wextra -Wno-gnu-alignof-expression -fno-gnu89-inline -Wno-cast-function-type -O2 -g -DNDEBUG -ggdb -O2 
CXX_FLAGS: -fexceptions -funwind-tables -fasynchronous-unwind-tables -fno-common -msse2 -Wformat -Wformat-security -Werror=format-security -fstack-protector-strong -fPIC -fmacro-prefix-map=/home/ubuntu/tarantool=. -std=c++11 -Wall -Wextra -Wno-invalid-offsetof -Wno-gnu-alignof-expression -Wno-cast-function-type -O2 -g -DNDEBUG -ggdb -O2 

**Steps to reproduce**

How to run:

Just type `./build/src/tarantool test/fuzz/lua/test_engine.lua --workers 1000 --test_duration $((30*60)) --engine memtx --verbose`.

**Actual behavior**

```c++
#1  0x648c59befe22 in crash_signal_cb+162
#2  0x7643bac45320 in __sigaction+80
#3  0x648c59c7c8fa in lj_trace_unwind+26
#4  0x648c59c3c8bd in err_unwind_jit+125
#5  0x7643bc1d4539 in _Unwind_GetTextRelBase+10617
#6  0x7643bc1d4c11 in _Unwind_RaiseException+785
#7  0x648c59c3c9c9 in lj_err_throw+105
#8  0x648c59c3cc1a in lj_err_mem+106
#9  0x648c59c3f2b3 in lj_mem_realloc+115
#10 0x648c59c47899 in lj_tab_resize+521
#11 0x648c59c3ed34 in gc_onestep+1444
#12 0x648c59c3ef3c in lj_gc_step+92
#13 0x648c59c3f043 in lj_gc_step_jit+67
#14 0x648c4567aea5 in ??+0
```

no coredump unfortunately

**Expected behavior**

no crash

**Comment by ligurio** [comment]
Tarantool 3.2.0-entrypoint-217-g830f27bba
Target: Linux-x86_64-RelWithDebInfo
Build options: cmake . -DCMAKE_INSTALL_PREFIX=/usr/local -DENABLE_BACKTRACE=TRUE
Compiler: Clang-18.1.3
C_FLAGS: -fexceptions -funwind-tables -fasynchronous-unwind-tables -fno-common -msse2 -Wformat -Wformat-security -Werror=format-security -fstack-protector-strong -fPIC -fmacro-prefix-map=/home/ubuntu/tarantool=. -std=c11 -Wall -Wextra -Wno-gnu-alignof-expression -Wno-cast-function-type -O2 -g -DNDEBUG -ggdb -O2 
CXX_FLAGS: -fexceptions -funwind-tables -fasynchronous-unwind-tables -fno-common -msse2 -Wformat -Wformat-security -Werror=format-security -fstack-protector-strong -fPIC -fmacro-prefix-map=/home/ubuntu/tarantool=. -std=c++11 -Wall -Wextra -Wno-invalid-offsetof -Wno-gnu-alignof-expression -Wno-cast-function-type -O2 -g -DNDEBUG -ggdb -O2 

tarantool commit hash 830f27bbaf94dadcacc66a7f543e0e5feec3988d

```c++
#0  __pthread_kill_implementation (no_tid=0, signo=6, threadid=<optimized out>) at ./nptl/pthread_kill.c:44
#1  __pthread_kill_internal (signo=6, threadid=<optimized out>) at ./nptl/pthread_kill.c:78
#2  __GI___pthread_kill (threadid=<optimized out>, signo=signo@entry=6) at ./nptl/pthread_kill.c:89
#3  0x00007a3787e4526e in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#4  0x00007a3787e288ff in __GI_abort () at ./stdlib/abort.c:79
#5  0x00005c63f8ebbe52 in crash_signal_cb (signo=<optimized out>, siginfo=<optimized out>, context=<optimized out>)
    at /home/ubuntu/tarantool/src/lib/core/crash.c:203
#6  <signal handler called>
#7  0x00005c63f8f5181d in lj_trace_unwind (J=J@entry=0x404a95f8, addr=101583490990822, ep=ep@entry=0x7a36c66808bc)
    at /home/ubuntu/tarantool/third_party/luajit/src/lj_trace.c:962
#8  0x00005c63f8f0a8ca in err_unwind_jit (version=<optimized out>, actions=<optimized out>, uexclass=5500374307216568836, 
    uex=<optimized out>, ctx=0x7a36c6680b20) at /home/ubuntu/tarantool/third_party/luajit/src/lj_err.c:512
#9  0x00007a378b183539 in _Unwind_RaiseException_Phase2 (exc=exc@entry=0x7a378b157990, context=context@entry=0x7a36c6680b20, 
    frames_p=frames_p@entry=0x7a36c6680c10) at ../../../src/libgcc/unwind.inc:64
#10 0x00007a378b183c11 in _Unwind_RaiseException (exc=0x7a378b157990) at ../../../src/libgcc/unwind.inc:136
#11 0x00005c63f8f0a978 in err_raise_ext (g=0x404a93b8, errcode=4) at /home/ubuntu/tarantool/third_party/luajit/src/lj_err.c:730
#12 lj_err_throw (L=L@entry=0x412f5530, errcode=errcode@entry=4) at /home/ubuntu/tarantool/third_party/luajit/src/lj_err.c:746
#13 0x00005c63f8f0aa14 in lj_err_mem (L=L@entry=0x412f5530) at /home/ubuntu/tarantool/third_party/luajit/src/lj_err.c:789
#14 0x00005c63f8f0c955 in lj_mem_realloc (L=L@entry=0x412f5530, p=0x7a378b15ab00, p@entry=0x0, osz=osz@entry=0, nsz=201326592)
    at /home/ubuntu/tarantool/third_party/luajit/src/lj_gc.c:882
#15 0x00005c63f8f15c5b in newhpart (L=0x412f5530, t=0x404b54c0, hbits=<optimized out>)
    at /home/ubuntu/tarantool/third_party/luajit/src/lj_tab.c:64
#16 lj_tab_resize (L=0x412f5530, t=0x404b54c0, asize=0, hbits=<optimized out>)
    at /home/ubuntu/tarantool/third_party/luajit/src/lj_tab.c:279
#17 0x00005c63f8f0c2f1 in gc_onestep (L=0x404a95f8, L@entry=0x412f5530) at /home/ubuntu/tarantool/third_party/luajit/src/lj_gc.c:721
#18 0x00005c63f8f0c5f8 in lj_gc_step (L=0x412f5530) at /home/ubuntu/tarantool/third_party/luajit/src/lj_gc.c:745
#19 lj_gc_step_jit (g=<optimized out>, steps=0) at /home/ubuntu/tarantool/third_party/luajit/src/lj_gc.c:778
#20 0x00005c63bfe542e7 in ?? ()
#21 0x00000000404a953c in ?? ()
#22 0x00005c63f8efe8d3 in lj_BC_FUNCC () at /home/ubuntu/tarantool/build/third_party/luajit/src/lj_vm.S:811
#23 0x00005c63f8f06095 in lua_pcall (L=0x404a95f8, L@entry=0x412f5530, nargs=<optimized out>, nresults=nresults@entry=-1, 
    errfunc=errfunc@entry=0) at /home/ubuntu/tarantool/third_party/luajit/src/lj_api.c:1173
#24 0x00005c63f8ea2d8f in luaT_call (L=0x404a95f8, L@entry=0x412f5530, nargs=-1075494170, nreturns=1230254596, nreturns@entry=-1)
    at /home/ubuntu/tarantool/src/lua/utils.c:695
#25 0x00005c63f8e9c311 in lua_fiber_run_f (ap=<optimized out>) at /home/ubuntu/tarantool/src/lua/fiber.c:435
#26 0x00005c63f8d11fa9 in fiber_cxx_invoke (f=0x7a378b15ab00, ap=0x5c63bfe542e6) at /home/ubuntu/tarantool/src/lib/core/fiber.h:1324
#27 0x00005c63f8ec25c5 in fiber_loop (data=<optimized out>) at /home/ubuntu/tarantool/src/lib/core/fiber.c:1162
#28 0x00005c63f912bc61 in coro_init () at /home/ubuntu/tarantool/third_party/coro/coro.c:108
```

tarantool binary and coredump: **TO BE UPLOAD SOON**
