### ISSUE TITLE
vy_point_lookup: Assertion `tx == NULL || tx->state == VINYL_TX_READY' failed.

### ISSUE THREAD

**Issue by ligurio** [tarantool/tarantool#10517]
**Bug description**

Assertion is triggered in 
`tarantool: ./src/box/vy_point_lookup.c:219: vy_point_lookup: Assertion 'tx == NULL || tx->state == VINYL_TX_READY' failed.`.

* OS: Linux
* OS Version: Ubuntu 24.04
* Architecture: amd64

Tarantool 3.3.0-entrypoint-35-g9519fe930
Target: Linux-x86_64-Debug
Build options: cmake . -DCMAKE_INSTALL_PREFIX=/usr/local -DENABLE_BACKTRACE=TRUE
Compiler: GNU-13.2.0
C_FLAGS: -fexceptions -funwind-tables -fasynchronous-unwind-tables -fno-common -msse2 -Wformat -Wformat-security -Werror=format-security -fstack-protector-strong -fPIC -fmacro-prefix-map=/home/ubuntu/tarantool=. -std=c11 -Wall -Wextra -Wno-gnu-alignof-expression -fno-gnu89-inline -Wno-cast-function-type -Werror -g -ggdb -O0 
CXX_FLAGS: -fexceptions -funwind-tables -fasynchronous-unwind-tables -fno-common -msse2 -Wformat -Wformat-security -Werror=format-security -fstack-protector-strong -fPIC -fmacro-prefix-map=/home/ubuntu/tarantool=. -std=c++11 -Wall -Wextra -Wno-invalid-offsetof -Wno-gnu-alignof-expression -Wno-cast-function-type -Werror -g -ggdb -O0 

**Steps to reproduce**

```
seed=$RANDOM; ./build/src/tarantool ./test/fuzz/lua/test_engine.lua --workers 5000 --test_duration $((60*60)) --engine vinyl --verbose --seed $seed 2>&1 | tee vinyl.log; echo $seed
```

The random seed was 6748.

**Actual behavior**

```
<snipped>

2024-09-04 12:59:52.149 [1666807] main/2991/WRK #2877 I> vinyl checkpoint started
2024-09-04 12:59:52.149 [1666807] main/106/checkpoint_daemon I> scheduled next checkpoint for Wed Sep  4 13:01:09 2024
tarantool: ./src/box/vy_point_lookup.c:219: vy_point_lookup: Assertion `tx == NULL || tx->state == VINYL_TX_READY' failed.
```

```c++
#0  __pthread_kill_implementation (no_tid=0, signo=6, threadid=<optimized out>) at ./nptl/pthread_kill.c:44
#1  __pthread_kill_internal (signo=6, threadid=<optimized out>) at ./nptl/pthread_kill.c:78
#2  __GI___pthread_kill (threadid=<optimized out>, signo=signo@entry=6) at ./nptl/pthread_kill.c:89
#3  0x00007c1343c4526e in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#4  0x00007c1343c288ff in __GI_abort () at ./stdlib/abort.c:79
#5  0x00007c1343c2881b in __assert_fail_base (fmt=0x7c1343dd01e8 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", 
    assertion=assertion@entry=0x57d9ca84c9c0 "tx == NULL || tx->state == VINYL_TX_READY", 
    file=file@entry=0x57d9ca84c909 "./src/box/vy_point_lookup.c", line=line@entry=219, 
    function=function@entry=0x57d9ca84cbd0 <__PRETTY_FUNCTION__.3> "vy_point_lookup") at ./assert/assert.c:94
#6  0x00007c1343c3b507 in __assert_fail (assertion=0x57d9ca84c9c0 "tx == NULL || tx->state == VINYL_TX_READY", 
    file=0x57d9ca84c909 "./src/box/vy_point_lookup.c", line=219, function=0x57d9ca84cbd0 <__PRETTY_FUNCTION__.3> "vy_point_lookup")
    at ./assert/assert.c:103
#7  0x000057d9ca226b4f in vy_point_lookup (lsm=0x57d9cbf3caa0, tx=0x7c10411bdb70, rv=0x7c10411bdbd8, key=..., ret=0x7c1076a80b20)
    at /home/ubuntu/tarantool/src/box/vy_point_lookup.c:219
#8  0x000057d9ca1ddffc in vy_get_by_secondary_tuple (lsm=0x57d9cbf46260, tx=0x7c10411bdb70, rv=0x7c10411bdbd8, entry=..., result=0x7c1076a80ba0)
    at /home/ubuntu/tarantool/src/box/vinyl.c:1342
#9  0x000057d9ca1e5045 in vinyl_iterator_secondary_next (base=0x7c104087e550, ret=0x7c1076a80c30) at /home/ubuntu/tarantool/src/box/vinyl.c:3778
#10 0x000057d9ca179771 in iterator_next (it=0x7c104087e550, ret=0x7c1076a80c30) at /home/ubuntu/tarantool/src/box/index.cc:639
#11 0x000057d9ca17a5d3 in generic_index_count (index=0x57d9cbf46260, type=ITER_ALL, key=0x7c108638b241 'P' <repeats 200 times>..., part_count=0)
    at /home/ubuntu/tarantool/src/box/index.cc:926
#12 0x000057d9ca1754e5 in index_count (index=0x57d9cbf46260, type=ITER_ALL, key=0x7c108638b241 'P' <repeats 200 times>..., part_count=0)
    at /home/ubuntu/tarantool/src/box/index.h:895
#13 0x000057d9ca178d13 in box_index_count (space_id=512, index_id=1, type=2, key=0x7c108638b241 'P' <repeats 200 times>..., 
    key_end=0x7c108638b241 'P' <repeats 200 times>...) at /home/ubuntu/tarantool/src/box/index.cc:486
#14 0x000057d9ca3c2a18 in lbox_index_count (L=0x41012680) at /home/ubuntu/tarantool/src/box/lua/index.c:282
#15 0x000057d9ca498d87 in lj_BC_FUNCC () at buildvm_x86.dasc:811
#16 0x000057d9ca4a68cb in lua_pcall (L=0x41012680, nargs=4, nresults=-1, errfunc=0) at /home/ubuntu/tarantool/third_party/luajit/src/lj_api.c:1173
#17 0x000057d9ca40a2de in luaT_call (L=0x41012680, nargs=4, nreturns=-1) at /home/ubuntu/tarantool/src/lua/utils.c:695
#18 0x000057d9ca3ff00a in lua_fiber_run_f (ap=0x7c1086356838) at /home/ubuntu/tarantool/src/lua/fiber.c:435
#19 0x000057d9ca158143 in fiber_cxx_invoke(fiber_func, typedef __va_list_tag __va_list_tag *) (f=0x57d9ca3fef4d <lua_fiber_run_f>, 
    ap=0x7c1086356838) at /home/ubuntu/tarantool/src/lib/core/fiber.h:1324
#20 0x000057d9ca43ae79 in fiber_loop (data=0x0) at /home/ubuntu/tarantool/src/lib/core/fiber.c:1162
#21 0x000057d9ca819eb1 in coro_init () at /home/ubuntu/tarantool/third_party/coro/coro.c:108
```

tarantool binary + vinyl.log + workdir content + coredump: https://drive.google.com/file/d/1Cj4WSbonfy2N18PLweciT1_7ls_sFvqd/view?usp=sharing

**Expected behavior**

assertion is not violated

**Comment by locker** [comment]
Reproducer:

```lua
local fiber = require('fiber')

box.cfg{}

local s = box.schema.space.create('test', {engine = 'vinyl'})
s:create_index('pk')
s:create_index('sk', {parts = {2, 'unsigned'}})
s:insert({1, 10})
s:insert({2, 20})
s:insert({3, 30})
s:insert({4, 40})

box.begin()

s:replace({4, s:get(3)[2] * 2})

fiber.new(function()
    s:delete(3)
    box.error.injection.set('ERRINJ_VY_DELAY_PK_LOOKUP', false)
end)
box.error.injection.set('ERRINJ_VY_DELAY_PK_LOOKUP', true)
s.index.sk:select()

box.commit()

os.exit(0)
```

This bug is impossible to reproduce without using the error injection because it injects a yield where it can't possibly happen otherwise.
