### ISSUE TITLE
Fix LSAN reports in SQL code

### ISSUE THREAD

**Issue by nshy** [tarantool/tarantool#10532]
In scope of #10211 are going to fix almost all memory leaks and other LSAN reports. One of the unfixed issues is LSAN reports for SQL code, so we still will have this suppressions:

```
# asan/lsan.supp file
leak:sql_prepare_and_execute
leak:sqlParser
```

```
 [053] 
[053] [test-run server "app_server"] Last 15 lines of the log file /tmp/t/053_sql-tap/start-transaction.test.lua.vinyl.tarantool.log:
[053] 
[053] Indirect leak of 576 byte(s) in 3 object(s) allocated from:
[053]     #0 0x5629e88ed06e in malloc (/__w/tarantool/tarantool/src/tarantool+0x46906e) (BuildId: bc6864341c657cad00d4f72ef810cdf39d8eafa9)
[053]     #1 0x5629e92e3062 in key_def_dup /__w/tarantool/tarantool/src/box/key_def.c:144:24
[053] 
[053] Indirect leak of 15 byte(s) in 1 object(s) allocated from:
[053]     #0 0x5629e88ed06e in malloc (/__w/tarantool/tarantool/src/tarantool+0x46906e) (BuildId: bc6864341c657cad00d4f72ef810cdf39d8eafa9)
[053]     #1 0x5629e8869c2f in strndup (/__w/tarantool/tarantool/src/tarantool+0x3e5c2f) (BuildId: bc6864341c657cad00d4f72ef810cdf39d8eafa9)
[053]     #2 0x5629e896da12 in index_def_new /__w/tarantool/tarantool/src/box/index_def.c:105:14
[053] 
[053] Indirect leak of 2 byte(s) in 1 object(s) allocated from:
[053]     #0 0x5629e88d6f4d in strdup (/__w/tarantool/tarantool/src/tarantool+0x452f4d) (BuildId: bc6864341c657cad00d4f72ef810cdf39d8eafa9)
[053]     #1 0x5629e896da4a in index_def_new /__w/tarantool/tarantool/src/box/index_def.c:111:21
[053] 
```

Let's fix them too.

**Comment by locker** [comment]
Consider dropping of the following tests after removing the SQL suppressions:

```
* sql-tap/gh-3083-ephemeral-unref-tuples.test.lua
* sql-tap/gh-3332-tuple-format-leak.test.lua
```

The test checks that there are no leaks by trying to run out of memory, which is pointless if ASAN is enabled. The tests take too long, especially on ASAN-enabled builds. Here are the test times (in seconds) reported by test-run on asan-debug-clang workflow:

```
* 500.39 sql-tap/gh-3083-ephemeral-unref-tuples.test.lua:vinyl
* 428.49 sql-tap/gh-3332-tuple-format-leak.test.lua:vinyl
* 324.37 sql-tap/gh-3083-ephemeral-unref-tuples.test.lua:memtx
* 227.26 sql-tap/gh-3332-tuple-format-leak.test.lua:memtx
```
