### ISSUE TITLE
Assertion is triggered: vy_cache_add: Assertion `cmp == 0'\'' failed.

### ISSUE THREAD

**Issue by ligurio** [tarantool/tarantool#10558]
**Bug description**

* OS: Linux
* OS Version: Ubuntu 24.04
* Architecture: amd64

Tarantool 3.3.0-entrypoint-60-ge88d3325e
Target: Linux-x86_64-Debug
Build options: cmake . -DCMAKE_INSTALL_PREFIX=/usr/local -DENABLE_BACKTRACE=TRUE
Compiler: GNU-13.2.0
C_FLAGS: -fexceptions -funwind-tables -fasynchronous-unwind-tables -fno-common -msse2 -Wformat -Wformat-security -Werror=format-security -fstack-protector-strong -fPIC -fmacro-prefix-map=/home/ubuntu/tarantool=. -std=c11 -Wall -Wextra -Wno-gnu-alignof-expression -fno-gnu89-inline -Wno-cast-function-type -Werror -g -ggdb -O0 
CXX_FLAGS: -fexceptions -funwind-tables -fasynchronous-unwind-tables -fno-common -msse2 -Wformat -Wformat-security -Werror=format-security -fstack-protector-strong -fPIC -fmacro-prefix-map=/home/ubuntu/tarantool=. -std=c++11 -Wall -Wextra -Wno-invalid-offsetof -Wno-gnu-alignof-expression -Wno-cast-function-type -Werror -g -ggdb -O0 

**Steps to reproduce**

```
./build/src/tarantool ./test/fuzz/lua/test_engine.lua --workers 1000 --test_duration $((1*60*60)) --engine vinyl --verbose --seed 29205
```

**Actual behavior**

```
<snipped>

2024-09-11 06:58:31.833 [9665] main/598/WRK #483/..test.fuzz.lua.test_engine I> ERROR: opname "SELECT_OP", err "Transaction has been aborted by conflict", args ["TREE",[821222621280,279302353263,835594869975,"namkluhucl","175869115741","b6ea69fb-0ab6-4664-a54f-9b5cc0b5438a",993728511948.48,false]]
2024-09-11 06:58:31.833 [9665] main/598/WRK #483/..test.fuzz.lua.test_engine I> ERROR: opname "TX_COMMIT", err "Transaction has been aborted by conflict", args []
tarantool: ./src/box/vy_cache.c:383: vy_cache_add: Assertion `cmp == 0' failed.

FIN
```

Backtrace:

```c++
#0  __pthread_kill_implementation (no_tid=0, signo=6, threadid=<optimized out>) at ./nptl/pthread_kill.c:44
#1  __pthread_kill_internal (signo=6, threadid=<optimized out>) at ./nptl/pthread_kill.c:78
#2  __GI___pthread_kill (threadid=<optimized out>, signo=signo@entry=6) at ./nptl/pthread_kill.c:89
#3  0x0000711b7ee4526e in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#4  0x0000711b7ee288ff in __GI_abort () at ./stdlib/abort.c:79
#5  0x0000711b7ee2881b in __assert_fail_base (fmt=0x711b7efd01e8 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", 
    assertion=assertion@entry=0x59cd014b1a3f "cmp == 0", file=file@entry=0x59cd014b1809 "./src/box/vy_cache.c", line=line@entry=383, 
    function=function@entry=0x59cd014b2038 <__PRETTY_FUNCTION__.15> "vy_cache_add") at ./assert/assert.c:94
#6  0x0000711b7ee3b507 in __assert_fail (assertion=0x59cd014b1a3f "cmp == 0", file=0x59cd014b1809 "./src/box/vy_cache.c", line=383, 
    function=0x59cd014b2038 <__PRETTY_FUNCTION__.15> "vy_cache_add") at ./assert/assert.c:103
#7  0x000059cd00e96997 in vy_cache_add (cache=0x59cd0389a0d0, curr=..., prev=..., is_first=false, key=..., order=589505315)
    at /home/ubuntu/tarantool/src/box/vy_cache.c:383
#8  0x000059cd00e88bb1 in vy_read_iterator_cache_add (itr=0x711b04924b68, entry=...)
    at /home/ubuntu/tarantool/src/box/vy_read_iterator.c:981
#9  0x000059cd00e48d98 in vinyl_iterator_primary_next (base=0x711b04924ae8, ret=0x711a9a980c20)
    at /home/ubuntu/tarantool/src/box/vinyl.c:3727
#10 0x000059cd00ddd777 in iterator_next (it=0x711b04924ae8, ret=0x711a9a980c20) at /home/ubuntu/tarantool/src/box/index.cc:639
#11 0x000059cd00f17896 in box_select (space_id=512, index_id=0, iterator=2, offset=0, limit=390, 
    key=0x711aa3a47241 <incomplete sequence \317>, key_end=0x711aa3a4728d 'P' <repeats 200 times>..., packed_pos=0x711a9a980cf8, 
    packed_pos_end=0x711a9a980d00, update_pos=false, port=0x711a9a980d10) at /home/ubuntu/tarantool/src/box/box.cc:3875
#12 0x000059cd0102f958 in lbox_select (L=0x403b0ab0) at /home/ubuntu/tarantool/src/box/lua/misc.cc:445
#13 0x000059cd010fd277 in lj_BC_FUNCC () at buildvm_x86.dasc:811
#14 0x000059cd0110adbb in lua_pcall (L=0x403b0ab0, nargs=4, nresults=-1, errfunc=0)
    at /home/ubuntu/tarantool/third_party/luajit/src/lj_api.c:1173
#15 0x000059cd0106e7c0 in luaT_call (L=0x403b0ab0, nargs=4, nreturns=-1) at /home/ubuntu/tarantool/src/lua/utils.c:695
#16 0x000059cd010634ec in lua_fiber_run_f (ap=0x711abf9cf808) at /home/ubuntu/tarantool/src/lua/fiber.c:435
#17 0x000059cd00dbc143 in fiber_cxx_invoke(fiber_func, typedef __va_list_tag __va_list_tag *) (f=0x59cd0106342f <lua_fiber_run_f>, 
    ap=0x711abf9cf808) at /home/ubuntu/tarantool/src/lib/core/fiber.h:1324
#18 0x000059cd0109f35b in fiber_loop (data=0x0) at /home/ubuntu/tarantool/src/lib/core/fiber.c:1162
#19 0x000059cd0147e498 in coro_init () at /home/ubuntu/tarantool/third_party/coro/coro.c:108
```

tarantool binary + coredump + workdir content + log: https://drive.google.com/file/d/14aX_uq3UhwVm5ULauccv5OHPHglJ8E7r/view?usp=sharing

I've found similar bugs:
- https://github.com/tarantool/tarantool/issues/10512, fixed 5 days ago, fix (9dbaa6a9bc0d65984b417f8a76aa8373b6125d16) is included
- https://github.com/tarantool/tarantool/issues/2685, fixed by Roman Tsisyk on Aug 16, 2017
- https://github.com/tarantool/tarantool/issues/5054, found by internal customer, closed as can't reproduce

**Expected behavior**

assertion is not violated

**Comment by locker** [comment]
Reproducer:

```lua
os.execute('rm -rf [0-9]*')

local fiber = require('fiber')

box.cfg()

local s = box.schema.space.create('test', {engine = 'vinyl'})
s:create_index('pk')

s:insert({1})
s:insert({10})
box.snapshot()

s:select({}, {limit = 1})

box.error.injection.set('ERRINJ_VY_READ_PAGE_DELAY', true)

fiber.create(function()
    box.begin({txn_isolation = 'read-committed'})
    s:select({}, {limit = 10})
    box.commit()
end)

fiber.create(function()
    s:select({}, {limit = 10})
end)

box.error.injection.set('ERRINJ_WAL_DELAY', true)
fiber.create(function()
    s:replace({5})
end)

box.error.injection.set('ERRINJ_VY_READ_PAGE_DELAY', false)
fiber.sleep(1)
box.error.injection.set('ERRINJ_WAL_DELAY', false)

os.exit(0)
```

**Comment by locker** [comment]
Another reproducer:

```lua
os.execute('rm -rf [0-9]*')

local fiber = require('fiber')
local json = require('json')

local function p(v)
    print(json.encode(v))
end

box.cfg{log_level = 'warn'}

local s = box.schema.space.create('test', {engine = 'vinyl'})
s:create_index('pk')

s:insert({10})
box.snapshot()

box.error.injection.set('ERRINJ_VY_READ_PAGE_DELAY', true)
fiber.create(function()
    s:select({}, {limit = 10})
end)
fiber.sleep(0.1)

box.error.injection.set('ERRINJ_WAL_DELAY', true)
fiber.create(function()
    s:replace({5})
end)
fiber.sleep(0.1)

box.error.injection.set('ERRINJ_VY_READ_PAGE_DELAY', false)
fiber.sleep(0.1)

box.begin{txn_isolation = 'read-committed'}
p({'cache is on', s:select({}, {limit = 10})})
box.cfg{vinyl_cache = 0}
p({'cache is off', s:select({}, {limit = 10})})
box.commit()

box.error.injection.set('ERRINJ_WAL_DELAY', false)
os.exit(0)
```

It doesn't crash Tarantool, but clearly demonstrates that `select` results are different with and without the cache. This discrepancy may be a source of various cache bugs like the one described in this issue.

```
["cache is on",[[10]]]
["cache is off",[[5],[10]]]
```

**Comment by locker** [comment]
The issue was introduced in commit 588170a77c9aba3d0cf898d0134286c6ffd46339 (2.11.0-entrypoint-603-g588170a77c9a), which added support of the "read-confirmed" isolation level for Vinyl.
