### ISSUE TITLE
Segmentation fault in tuple_format

### ISSUE THREAD

**Issue by ligurio** [tarantool/tarantool#10555]
**Bug description**

* OS: Linux
* OS Version: Ubuntu 24.04
* Architecture: amd64

Tarantool 3.3.0-entrypoint-60-ge88d3325e
Target: Linux-x86_64-Debug
Build options: cmake . -DCMAKE_INSTALL_PREFIX=/usr/local -DENABLE_BACKTRACE=TRUE
Compiler: GNU-13.2.0
C_FLAGS: -fexceptions -funwind-tables -fasynchronous-unwind-tables -fno-common -msse2 -Wformat -Wformat-security -Werror=format-security -fstack-protector-strong -fPIC -fmacro-prefix-map=/home/ubuntu/tarantool=. -std=c11 -Wall -Wextra -Wno-gnu-alignof-expression -fno-gnu89-inline -Wno-cast-function-type -Werror -g -ggdb -O0 
CXX_FLAGS: -fexceptions -funwind-tables -fasynchronous-unwind-tables -fno-common -msse2 -Wformat -Wformat-security -Werror=format-security -fstack-protector-strong -fPIC -fmacro-prefix-map=/home/ubuntu/tarantool=. -std=c++11 -Wall -Wextra -Wno-invalid-offsetof -Wno-gnu-alignof-expression -Wno-cast-function-type -Werror -g -ggdb -O0 

**Steps to reproduce**

- Apply a patch to the test

```diff
diff --git a/test/fuzz/lua/test_engine.lua b/test/fuzz/lua/test_engine.lua
index 7c26161f6..fa50c46d9 100644
--- a/test/fuzz/lua/test_engine.lua
+++ b/test/fuzz/lua/test_engine.lua
@@ -847,12 +847,15 @@ local ops = {
         func = len_op,
         args = function(_) return end,
     },
+    --[[
     FORMAT_OP = {
         func = format_op,
         args = function(_space) return random_space_format() end,
     },
+    ]]
 
     -- DDL.
+    --[[
     INDEX_ALTER_OP = {
         func = index_alter_op,
         args = function(space)
@@ -861,6 +864,7 @@ local ops = {
             return space.index[idx_n], index_opts(space, is_primary)
         end,
     },
+    ]]
     INDEX_COMPACT_OP = {
         func = index_compact_op,
         args = function(space)
@@ -868,6 +872,7 @@ local ops = {
             return space.index[idx_n]
         end,
     },
+    --[[
     INDEX_CREATE_OP = {
         func = index_create_op,
         args = function(_) return end,
@@ -882,6 +887,7 @@ local ops = {
             return space.index[idx_n]
         end,
     },
+    ]]
     INDEX_GET_OP = {
         func = index_get_op,
         args = function(space)
@@ -919,6 +925,7 @@ local ops = {
             return space.index[idx_n]
         end,
     },
+    --[[
     INDEX_COUNT_OP = {
         func = index_count_op,
         args = function(space)
@@ -926,6 +933,7 @@ local ops = {
             return space.index[idx_n]
         end,
     },
+    ]]
     INDEX_UPDATE_OP = {
         func = index_update_op,
         args = function(space)
@@ -942,6 +950,7 @@ local ops = {
             return idx, random_key(space, idx)
         end,
     },
+    --[[
     INDEX_RENAME_OP = {
         func = index_rename_op,
         args = function(space)
@@ -950,6 +959,7 @@ local ops = {
             return space.index[idx_n], idx_name
         end,
     },
+    ]]
     INDEX_STAT_OP = {
         func = index_stat_op,
         args = function(space)
@@ -974,6 +984,7 @@ local ops = {
         end,
         args = function(_) return end,
     },
+    --[[
     TX_ROLLBACK = {
         func = function()
             if box.is_in_txn() then
@@ -982,6 +993,7 @@ local ops = {
         end,
         args = function(_) return end,
     },
+    ]]
 
     SNAPSHOT_OP = {
         func = box_snapshot,
@@ -992,7 +1004,7 @@ local ops = {
 local function apply_op(space, op_name)
     local func = ops[op_name].func
     local args = { ops[op_name].args(space) }
-    log.info(('%s %s'):format(op_name, json.encode(args)))
+    -- log.info(('%s %s'):format(op_name, json.encode(args)))
     local pcall_args = {func, space, unpack(args)}
     local ok, err = pcall(unpack(pcall_args))
     if ok ~= true then
@@ -1024,6 +1036,24 @@ local function worker_func(id, space, test_gen, test_duration)
     return errors
 end
 
+local function disable_errinj(errinj, space)
+    local enabled_errinj = fun.iter(errinj):
+                           filter(function(i, x)
+                               if x.is_enabled then
+                                   return i
+                               end
+                           end):totable()
+    log.info(('Enabled fault injections: %s'):format(
+             json.encode(enabled_errinj)))
+    for _, errinj_name in pairs(enabled_errinj) do
+        local errinj_val = errinj[errinj_name].disable(space)
+        errinj[errinj_name].is_enabled = false
+        log.info(string.format('DISABLE ERROR INJECTION: %s -> %s',
+                               errinj_name, tostring(errinj_val)))
+        pcall(box.error.injection.set, errinj_name, errinj_val)
+    end
+end
+
 local function toggle_random_errinj(errinj, max_enabled, space)
     local enabled_errinj = fun.iter(errinj):
                            filter(function(i, x)
@@ -1302,10 +1332,12 @@ local errinj_set = {
         end,
     },
     -- Set to true to fail WAL write.
+    --[[
     ERRINJ_WAL_IO = {
         enable = enable_errinj_boolean,
         disable = disable_errinj_boolean,
     },
+    ]]
     -- Set to true to fail creation of new WAL file.
     ERRINJ_WAL_ROTATE = {
         enable = enable_errinj_boolean,
@@ -1429,6 +1461,7 @@ local function run_test(num_workers, test_duration, test_dir,
     table.insert(workers, errinj_f)
 
     local error_messages = {}
+    disable_errinj(errinj_set, space)
     for _, fb in ipairs(workers) do
         local ok, res = fiber.join(fb)
         if not ok then
```
- Run the test with command-line options below:

```
./build/src/tarantool ./test/fuzz/lua/test_engine.lua --workers 1000 --test_duration $((1*60*60)) --engine vinyl --verbose --seed 31755
```

**Actual behavior**

```c++
#0  __pthread_kill_implementation (no_tid=0, signo=6, threadid=<optimized out>) at ./nptl/pthread_kill.c:44
#1  __pthread_kill_internal (signo=6, threadid=<optimized out>) at ./nptl/pthread_kill.c:78
#2  __GI___pthread_kill (threadid=<optimized out>, signo=signo@entry=6) at ./nptl/pthread_kill.c:89
#3  0x000078fe7f44526e in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#4  0x000078fe7f4288ff in __GI_abort () at ./stdlib/abort.c:79
#5  0x00006146845b216f in crash_signal_cb (signo=11, siginfo=0x78fe3001cb30, context=0x78fe3001ca00)
    at /home/ubuntu/tarantool/src/lib/core/crash.c:204
#6  <signal handler called>
#7  0x00006146843a0c60 in tuple_format (tuple=0x0) at /home/ubuntu/tarantool/src/box/tuple.h:775
#8  0x00006146843a0fa7 in vy_stmt_is_key (stmt=0x0) at /home/ubuntu/tarantool/src/box/vy_stmt.h:282
#9  0x00006146843a116a in vy_stmt_compare (a=0x78fe302518f0, a_hint=5814982532124243135, b=0x0, b_hint=18446744073709551615, 
    key_def=0x614686699cc0) at /home/ubuntu/tarantool/src/box/vy_stmt.h:433
#10 0x00006146843a13b9 in vy_entry_compare (a=..., b=..., key_def=0x614686699cc0) at /home/ubuntu/tarantool/src/box/vy_stmt.h:783
#11 0x00006146843a1e95 in heap_less (heap=0x614689c1be08, src1=0x614687144120, src2=0x614687ff5680)
    at /home/ubuntu/tarantool/src/box/vy_write_iterator.c:231
#12 0x00006146843a1765 in vy_source_heap_sift_up (heap=0x614689c1be08, node=0x614687144130)
    at /home/ubuntu/tarantool/src/lib/salad/heap.h:334
#13 0x00006146843a163b in vy_source_heap_update_node (heap=0x614689c1be08, node=0x614687144130)
    at /home/ubuntu/tarantool/src/lib/salad/heap.h:314
#14 0x00006146843a1b43 in vy_source_heap_delete (heap=0x614689c1be08, value=0x78fd7227f320)
    at /home/ubuntu/tarantool/src/lib/salad/heap.h:461
#15 0x00006146843a36b6 in vy_write_iterator_build_history (stream=0x614689c1bdf0, count=0x78fd7227f3e0, is_first_insert=0x78fd7227f3df)
    at /home/ubuntu/tarantool/src/box/vy_write_iterator.c:816
#16 0x00006146843a3f17 in vy_write_iterator_build_read_views (stream=0x614689c1bdf0, count=0x78fd7227f45c)
    at /home/ubuntu/tarantool/src/box/vy_write_iterator.c:1013
#17 0x00006146843a4268 in vy_write_iterator_next (vstream=0x614689c1bdf0, ret=0x78fd7227f4e0)
    at /home/ubuntu/tarantool/src/box/vy_write_iterator.c:1104
#18 0x00006146843cc78d in vy_task_write_run (task=0x614688fb0ec0, no_compression=false)
    at /home/ubuntu/tarantool/src/box/vy_scheduler.c:1128
#19 0x00006146843cdc51 in vy_task_compaction_execute (task=0x614688fb0ec0) at /home/ubuntu/tarantool/src/box/vy_scheduler.c:1507
#20 0x00006146843cf00f in vy_task_f (va=0x78fd720104a8) at /home/ubuntu/tarantool/src/box/vy_scheduler.c:1826
#21 0x00006146842db143 in fiber_cxx_invoke(fiber_func, typedef __va_list_tag __va_list_tag *) (f=0x6146843cee52 <vy_task_f>, 
    ap=0x78fd720104a8) at /home/ubuntu/tarantool/src/lib/core/fiber.h:1324
#22 0x00006146845be35b in fiber_loop (data=0x0) at /home/ubuntu/tarantool/src/lib/core/fiber.c:1162
#23 0x000061468499d498 in coro_init () at /home/ubuntu/tarantool/third_party/coro/coro.c:108
```

```c++
(gdb) frame 7
#7  0x00006146843a0c60 in tuple_format (tuple=0x0) at /home/ubuntu/tarantool/src/box/tuple.h:775
775             struct tuple_format *format = tuple_format_by_id(tuple->format_id);
(gdb) print tuple
$3 = (struct tuple *) 0x0
(gdb) frame 8
#8  0x00006146843a0fa7 in vy_stmt_is_key (stmt=0x0) at /home/ubuntu/tarantool/src/box/vy_stmt.h:282
282             return vy_stmt_is_key_format(tuple_format(stmt));
(gdb) print stmt
$4 = (struct tuple *) 0x0
(gdb) frame 9
#9  0x00006146843a116a in vy_stmt_compare (a=0x78fe302518f0, a_hint=5814982532124243135, b=0x0, b_hint=18446744073709551615, 
    key_def=0x614686699cc0) at /home/ubuntu/tarantool/src/box/vy_stmt.h:433
433             bool b_is_tuple = !vy_stmt_is_key(b);
(gdb) print b
$5 = (struct tuple *) 0x0
```

tarantool binary + log + workdir content + patch: https://drive.google.com/file/d/1UWnN38BCOPLe7NqMwfxO7FfgyuCuGtiG/view?usp=sharing

**Expected behavior**

tarantool does not crash

**Comment by locker** [comment]
The issue can be reproduced on the attached data directory using the following script:

```lua
local fiber = require('fiber')
box.cfg{}
box.error.injection.set('ERRINJ_VY_READ_PAGE_TIMEOUT', 0.1)
box.space.test_1.index.idx_1:compact()
fiber.sleep(0.5)
box.error.injection.set('ERRINJ_VYRUN_DATA_READ', true)
```

However, I've failed to create a standalone reproducer so far.

**Comment by locker** [comment]
Reproducer:

```lua
os.execute('rm -rf [0-9]*')

box.cfg{log_level = 'warn'}

local s = box.schema.space.create('test', {engine = 'vinyl'})
s:create_index('pk')

box.error.injection.set('ERRINJ_VY_COMPACTION_DELAY', true)

for i = 1, 6 do
    box.begin()
    for i = 1, 100 do
        s:replace({i})
    end
    box.commit()
    box.snapshot()
end

box.error.injection.set('ERRINJ_VY_STMT_ALLOC', 400)

s.index.pk:compact()
box.error.injection.set('ERRINJ_VY_COMPACTION_DELAY', false)
```

Output:

```
Segmentation fault
  code: SEGV_MAPERR
  addr: 0x2
  context: 0x773da800e300
  siginfo: 0x773da800e430
  rax      0x0                0
  rbx      0x2000             8192
  rcx      0xffffffffffffffff -1
  rdx      0x26               38
  rsi      0x2800000000000028 2882303761517117480
  rdi      0x0                0
  rsp      0x773dbda7f200     131107058610688
  rbp      0x773dbda7f220     131107058610720
  r8       0x62f8407e70f0     108818373439728
  r9       0x2800000000000028 2882303761517117480
  r10      0xffffffff         4294967295
  r11      0x293              659
  r12      0x62f8407e9a60     108818373450336
  r13      0x0                0
  r14      0x0                0
  r15      0x0                0
  rip      0x62f83f2ac6de     108818351179486
  eflags   0x10206            66054
  cs       0x33               51
  gs       0x0                0
  fs       0x0                0
  cr2      0x2                2
  err      0x4                4
  oldmask  0xfffffffe7ffbfa37 -6442714569
  trapno   0xe                14
Current time: 1726826313
Please file a bug at https://github.com/tarantool/tarantool/issues
Attempting backtrace... Note: since the server has already crashed,
this may fail as well
#1  0x62f83f4be43c in crash_collect+256
#2  0x62f83f4bee78 in crash_signal_cb+100
#3  0x773ded445320 in __sigaction+80
#4  0x62f83f2ac6de in tuple_format+16
#5  0x62f83f2aca25 in vy_stmt_is_key+24
#6  0x62f83f2acbe8 in vy_stmt_compare+89
#7  0x62f83f2ace37 in vy_entry_compare+74
#8  0x62f83f2ad913 in heap_less+88
#9  0x62f83f2ad1e3 in vy_source_heap_sift_up+255
#10 0x62f83f2ad0b9 in vy_source_heap_update_node+54
#11 0x62f83f2ad5c1 in vy_source_heap_delete+249
#12 0x62f83f2addda in vy_write_iterator_remove_src+63
#13 0x62f83f2ae420 in vy_write_iterator_stop+186
#14 0x62f83f2d82f5 in vy_task_write_run+1192
#15 0x62f83f2d977d in vy_task_compaction_execute+124
#16 0x62f83f2dab3b in vy_task_f+445
#17 0x62f83f1e5143 in fiber_cxx_invoke(int (*)(__va_list_tag*), __va_list_tag*)+34
#18 0x62f83f4cb112 in fiber_loop+219
#19 0x62f83f8ac318 in coro_init+120
Aborted
```
