### ISSUE TITLE
Segfault in `index_replace`

### ISSUE THREAD

**Issue by Buristan** [tarantool/tarantool#10620]
See the following workflow run:
https://github.com/tarantool/tarantool/actions/runs/10964314154/job/30447684362
Seed: 74203

--- 
Backtrace
```
2024-09-20T18:31:23.8137880Z #1  0x5564606dd5e8 in crash_collect+256
2024-09-20T18:31:23.8138184Z #2  0x5564606ddffa in crash_signal_cb+100
2024-09-20T18:31:23.8138423Z #3  0x7fefbc7d8420 in __restore_rt+0
2024-09-20T18:31:23.8138631Z #4  0x556460488c21 in index_replace+77
2024-09-20T18:31:23.8138891Z #5  0x55646048d4fe in memtx_build_on_replace_rollback+250
2024-09-20T18:31:23.8139119Z #6  0x5564607145a5 in trigger_run_list(rlist*, void*)+126
2024-09-20T18:31:23.8139276Z #7  0x556460714671 in trigger_run+169
2024-09-20T18:31:23.8139459Z #8  0x55646054b300 in txn_rollback_one_stmt+58
2024-09-20T18:31:23.8139635Z #9  0x55646054cf21 in txn_complete_fail+420
2024-09-20T18:31:23.8139955Z #10 0x55646054d66b in txn_on_journal_write+765
2024-09-20T18:31:23.8140178Z #11 0x5564605b475c in journal_async_complete+93
2024-09-20T18:31:23.8140338Z #12 0x5564605b51ab in tx_schedule_queue+54
2024-09-20T18:31:23.8140528Z #13 0x5564605b526a in tx_complete_rollback+95
2024-09-20T18:31:23.8140836Z #14 0x5564605b5300 in tx_complete_batch+87
2024-09-20T18:31:23.8140980Z #15 0x5564606f30fb in cmsg_deliver+52
2024-09-20T18:31:23.8141212Z #16 0x5564606f3a71 in cbus_process+100
2024-09-20T18:31:23.8141485Z #17 0x556460574067 in tx_prio_cb(ev_loop*, ev_watcher*, int)+176
2024-09-20T18:31:23.8141687Z #18 0x556460aa9e09 in ev_invoke_pending+205
2024-09-20T18:31:23.8141839Z #19 0x556460aaad66 in ev_run+1501
2024-09-20T18:31:23.8142036Z #20 0x5564606ad26e in tarantool_lua_run_script+435
2024-09-20T18:31:23.8142166Z #21 0x55646041bb7d in main+2656
2024-09-20T18:31:23.8142403Z #22 0x7fefbc2aa083 in __libc_start_main+243
2024-09-20T18:31:23.8142531Z #23 0x556460418a2e in _start+46
```
Can't reproduce the issue locally.

**Comment by drewdzzz** [comment]
Reproducer:
```lua
local fiber = require('fiber')

box.cfg{}
local space = box.schema.space.create('test')
space:create_index('pk')
for i = 1, 100 do
    space:replace({i, i})
end
local ch = fiber.channel(1)
box.error.injection.set('ERRINJ_WAL_DELAY', true)
fiber.create(function()
    box.begin()
    space:create_index('sk')
    ch:put(true)
    box.commit()
end)
fiber.create(function()
    box.begin()
    for i = 1, 100 do
        space:replace{i, i}
    end
    ch:put(true)
    box.commit()
end)
ch:get()
ch:get()
box.error.injection.set('ERRINJ_WAL_WRITE', true)
box.error.injection.set('ERRINJ_WAL_DELAY', false)
box.space.test.index.sk:alter({parts = {2, 'unsigned'}})
os.exit()
```

Actually, the problem here is the same as in https://github.com/tarantool/tarantool/issues/10235.
