### ISSUE TITLE
Memory leak in runtime_tuple_new()

### ISSUE THREAD

**Issue by ligurio** [tarantool/tarantool#10698]
**Bug description**

* OS: Linux
* OS Version: Ubuntu Jammy
* Architecture: amd64

Branch https://github.com/ligurio/tarantool/tree/ligurio/gh-xxxx-bump-clang-19-3.2

**Steps to reproduce**

workflow `debug_asan_clang`

**Actual behavior**

```c
 [025] box-tap/session.test.lua                                      [ pass ]
[020] 
[020] 
[020] [Instance "box" killed by signal: 11 (SIGSEGV)]
[020] 
[020] [test-run server "box"] Last 15 lines of the log file /tmp/t/020_box/box.log:
[020]     #10 0x55c614823c1a  (<unknown module>)
[020] 
[020] Direct leak of 66 byte(s) in 1 object(s) allocated from:
[020]     #0 0x55c5e929916f in malloc (/__w/tarantool/tarantool/src/tarantool+0x12ad16f) (BuildId: b4b95db1d41d904a6230cad03a29a4ac5b4a50a5)
[020]     #1 0x55c5eb3a319e in small_asan_alloc /__w/tarantool/tarantool/src/lib/small/small/util.c:94:24
[020]     #2 0x55c5eb39fb94 in smalloc /__w/tarantool/tarantool/src/lib/small/small/small_asan.c:57:5
[020]     #3 0x55c5ead51180 in runtime_tuple_new /__w/tarantool/tarantool/src/box/tuple.c:138:27
[020]     #4 0x55c5ead4dbf5 in tuple_new /__w/tarantool/tarantool/src/box/tuple.h:801:9
[020]     #5 0x55c5ead4e2c8 in box_tuple_new /__w/tarantool/tarantool/src/box/tuple.c:845:22
[020]     #6 0x55c5e9600255 in session_settings_index_get /__w/tarantool/tarantool/src/box/session_settings.c:261:12
[020]     #7 0x55c5e938fb7c in index_get(index*, char const*, unsigned int, tuple**) /__w/tarantool/tarantool/src/box/index.h:909:9
[020]     #8 0x55c5e938e5a7 in box_index_get /__w/tarantool/tarantool/src/box/index.cc:384:11
[020]     #9 0x55c61481d92e  (<unknown module>)
[020] 
[020] SUMMARY: AddressSanitizer: 138 byte(s) leaked in 2 allocation(s).
```

Full CI log: https://github.com/tarantool/tarantool/actions/runs/11345457610/job/31578247204?pr=10692

[logs_29637096935.zip](https://github.com/user-attachments/files/17391933/logs_29637096935.zip)

**Expected behavior**

no memory leak

**Comment by Buristan** [comment]
Looks like Clang-unrelated: I got the same leak report for 2.11 during the LuaJIT bump:
https://github.com/tarantool/luajit/actions/runs/11367129005/job/31619134132#step:8:8083

**Comment by locker** [comment]
See also:
- #10701
- #11740
