### ISSUE TITLE
Assertion `victim->psn == 0' failed in memtx_tx_handle_conflict()

### ISSUE THREAD

**Issue by ligurio** [tarantool/tarantool#10715]
**Bug description**

* OS: Linux
* OS Version: Ubuntu 24.04
* Architecture: amd64

Tarantool 3.3.0-entrypoint-161-gbf09135880
Target: Linux-x86_64-Debug
Build options: cmake . -DCMAKE_INSTALL_PREFIX=/usr/local -DENABLE_BACKTRACE=TRUE
Compiler: Clang-18.1.3
C_FLAGS: -fexceptions -funwind-tables -fasynchronous-unwind-tables -fno-common -msse2 -fsanitize=address -Wformat -Wformat-security -Werror=format-security -fstack-protector-strong -fPIC -fmacro-prefix-map=/home/ubuntu/tarantool=. -std=c11 -Wall -Wextra -Wno-gnu-alignof-expression -Wno-cast-function-type -Werror -g -ggdb -O0 
CXX_FLAGS: -fexceptions -funwind-tables -fasynchronous-unwind-tables -fno-common -msse2 -fsanitize=address -Wformat -Wformat-security -Werror=format-security -fstack-protector-strong -fPIC -fmacro-prefix-map=/home/ubuntu/tarantool=. -std=c++11 -Wall -Wextra -Wno-invalid-offsetof -Wno-gnu-alignof-expression -Wno-cast-function-type -Werror -g -ggdb -O0 

**Steps to reproduce**

`./build/src/tarantool ./test/fuzz/lua/test_engine.lua --workers 1800 --test_duration 60 --engine vinyl --verbose --seed 17326`

**Actual behavior**

```
<snipped>

2024-10-18 06:57:18.913 [582307] main/1183/WRK #1068/..test.fuzz.lua.test_engine I> ERROR: opname "INDEX_UPDATE_OP", err "failed to read from file: Input/output error", args [["431abd63-9771-432f-b1c3-579f5d5de22c",463690488686,971084909917.45],{"unique":true,"parts":[{"fieldno":3,"sort_order":"asc","type":"uuid","exclude_null":false,"is_nullable":false},{"fieldno":2,"sort_order":"asc","type":"unsigned","exclude_null":false,"is_nullable":false},{"fieldno":1,"sort_order":"asc","type":"double","exclude_null":false,"is_nullable":false}],"options":{"page_size":2048,"run_count_per_level":3,"run_size_ratio":5,"bloom_fpr":0.5,"range_size":1073741824},"id":0,"space_id":512,"type":"TREE","name":"idx_1"},[["-",1,714444347063.12],["-",2,581701618565],["=",3,"8d1f420e-d91c-4111-9acb-877f955d048e"]]]
2024-10-18 06:57:18.913 [582307] main/1183/WRK #1068/..test.fuzz.lua.test_engine I> ERROR: opname "INDEX_CREATE_OP", err "Storage engine 'memtx' does not support cross-engine transactions", args []
2024-10-18 06:57:18.914 [582307] main/1112/WRK #997/..test.fuzz.lua.test_engine I> ERROR: opname "INDEX_GET_OP", err "failed to read from file: Input/output error", args [{"unique":true,"parts":[{"fieldno":3,"sort_order":"asc","type":"uuid","exclude_null":false,"is_nullable":false},{"fieldno":2,"sort_order":"asc","type":"unsigned","exclude_null":false,"is_nullable":false},{"fieldno":1,"sort_order":"asc","type":"double","exclude_null":false,"is_nullable":false}],"options":{"page_size":2048,"run_count_per_level":3,"run_size_ratio":5,"bloom_fpr":0.5,"range_size":1073741824},"id":0,"space_id":512,"type":"TREE","name":"idx_1"},["893fe638-e1d9-442e-8256-2fad2c59ca4d",848212856838,55347079295.925]]
2024-10-18 06:57:18.915 [582307] main/1881/WRK #1766/..test.fuzz.lua.test_engine I> ERROR: opname "UPSERT_OP", err "failed to read from file: Input/output error", args [[313939472593.49,981808514589,"a4b5c1fc-1165-4650-b1db-7b40ee8d9232",226319329138,"bvbarvrjnc",322030354274,false,"683264593497","2024-10-18T06:57:18Z",[1,2,3,4,5,6,7,8,9,10,11,12,13,14],{"4":4,"8":8,"1":1,"5":5,"9":9,"6":6,"3":3,"7":7,"2":2}],[["-",1,468861014578.57]]]
tarantool: src/box/memtx_tx.c:839: void memtx_tx_handle_conflict(struct txn *, struct txn *): Assertion `victim->psn == 0' failed.
```

log and tarantool binary [gh-10715.zip](https://github.com/user-attachments/files/17429725/gh-10715.zip)

**Expected behavior**

no assertion violation

**Comment by drewdzzz** [comment]
It seems to be a duplicate of #10614.
What a pity there is no coredump this time!

**Comment by ligurio** [comment]
reproduced with [coredump](https://drive.google.com/file/d/1ZvHBbzy8MEacjfsOH0Uq3cd-stc4yUPN/view?usp=drive_link)

Backtrace:

```c++
#0  __pthread_kill_implementation (no_tid=0, signo=6, threadid=<optimized out>) at ./nptl/pthread_kill.c:44
#1  __pthread_kill_internal (signo=6, threadid=<optimized out>) at ./nptl/pthread_kill.c:78
#2  __GI___pthread_kill (threadid=<optimized out>, signo=signo@entry=6) at ./nptl/pthread_kill.c:89
#3  0x00007e4c5684526e in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#4  0x00007e4c568288ff in __GI_abort () at ./stdlib/abort.c:79
#5  0x00007e4c5682881b in __assert_fail_base (fmt=0x7e4c569d01e8 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", 
    assertion=assertion@entry=0x64a80a197420 <str> "victim->psn == 0", file=file@entry=0x64a80a193e80 <str> "src/box/memtx_tx.c", 
    line=line@entry=839, 
    function=function@entry=0x64a80a197380 <__PRETTY_FUNCTION__.memtx_tx_handle_conflict> "void memtx_tx_handle_conflict(struct txn *, struct txn *)") at ./assert/assert.c:94
#6  0x00007e4c5683b507 in __assert_fail (assertion=0x64a80a197420 <str> "victim->psn == 0", 
    file=0x64a80a193e80 <str> "src/box/memtx_tx.c", line=839, 
    function=0x64a80a197380 <__PRETTY_FUNCTION__.memtx_tx_handle_conflict> "void memtx_tx_handle_conflict(struct txn *, struct txn *)")
    at ./assert/assert.c:103
#7  0x000064a80905de24 in memtx_tx_handle_conflict (breaker=0x51700005ad38, victim=0x517000034fb8)
    at /home/ubuntu/tarantool/src/box/memtx_tx.c:839
#8  0x000064a80905dabc in memtx_tx_handle_conflict_story_readers (story=0x512000041460, writer=0x51700005ad38)
    at /home/ubuntu/tarantool/src/box/memtx_tx.c:2453
#9  0x000064a8090477f6 in memtx_tx_history_prepare_insert_stmt (stmt=0x51100122f938) at /home/ubuntu/tarantool/src/box/memtx_tx.c:2587
#10 0x000064a809046b94 in memtx_tx_history_prepare_stmt (stmt=0x51100122f938) at /home/ubuntu/tarantool/src/box/memtx_tx.c:2720
#11 0x000064a809076224 in memtx_engine_prepare (engine=0x52100000c900, txn=0x51700005ad38)
    at /home/ubuntu/tarantool/src/box/memtx_engine.cc:625
#12 0x000064a8092a01dc in engine_prepare (engine=0x52100000c900, txn=0x51700005ad38) at /home/ubuntu/tarantool/src/box/engine.h:414
#13 0x000064a80929e268 in txn_prepare (txn=0x51700005ad38) at /home/ubuntu/tarantool/src/box/txn.c:1094
#14 0x000064a809296b0d in txn_commit_impl (txn=0x51700005ad38, wait_mode=TXN_COMMIT_WAIT_MODE_COMPLETE)
  at /home/ubuntu/tarantool/src/box/txn.c:1173
#15 0x000064a809297c57 in txn_commit (txn=0x51700005ad38) at /home/ubuntu/tarantool/src/box/txn.c:1291
#16 0x000064a8092bd0c4 in box_process_rw (request=0x7e4b98df5e20, space=0x5160000d0880, result=0x7e4b98c8c5e0)
    at /home/ubuntu/tarantool/src/box/box.cc:516
#17 0x000064a8092d0d56 in box_process1 (request=0x7e4b98df5e20, result=0x7e4b98c8c5e0) at /home/ubuntu/tarantool/src/box/box.cc:3785
#18 0x000064a8092d3939 in box_update (space_id=280, index_id=0, key=0x5060004ea9d1 "\221\315\002", key_end=0x5060004ea9d5 "\276", 
    ops=0x51300034eb31 "\221\223\241=\a\233\202\244name\247field_1\244type\246double\202\244name\247field_2\244type\250unsigned\202\244name\247field_3\244type\244uuid\202\244name\247field_4\244type\247integer\202\244name\247field_5\244type\246string\202\244name\247field_6\244type\246number\202\244name\247field_7\244type\247boolean\202\244name\247fie"..., ops_end=0x51300034ec58 "\276", index_base=1, 
    result=0x7e4b98c8c5e0) at /home/ubuntu/tarantool/src/box/box.cc:4017
#19 0x000064a8095a6986 in lbox_index_update (L=0x4077cd70) at /home/ubuntu/tarantool/src/box/lua/index.c:113
#20 0x000064a80979ba87 in lj_BC_FUNCC () at /home/ubuntu/tarantool/build/third_party/luajit/src/lj_vm.S:811
#21 0x000064a8097c661b in lua_pcall (L=0x4077cd70, nargs=4, nresults=-1, errfunc=0)
    at /home/ubuntu/tarantool/third_party/luajit/src/lj_api.c:1173
#22 0x000064a809635703 in luaT_call (L=0x4077cd70, nargs=4, nreturns=-1) at /home/ubuntu/tarantool/src/lua/utils.c:695
#23 0x000064a8096201cf in lua_fiber_run_f (ap=0x51500043b8c8) at /home/ubuntu/tarantool/src/lua/fiber.c:435
#24 0x000064a808f6e04a in fiber_cxx_invoke (f=0x64a809620050 <lua_fiber_run_f>, ap=0x51500043b8c8)
    at /home/ubuntu/tarantool/src/lib/core/fiber.h:1324
#25 0x000064a8096998fa in fiber_loop (data=0x0) at /home/ubuntu/tarantool/src/lib/core/fiber.c:1162
#26 0x000064a80a0e9dda in coro_init () at /home/ubuntu/tarantool/third_party/coro/coro.c:108
(gdb)

**Comment by ligurio** [comment]
coredump packed by `tarabrt.sh`: https://drive.google.com/file/d/1RGelyzLIaa4ue91-8pKj_BsQwIGKQGHE/view?usp=sharing
