### ISSUE TITLE
1.6.7 Start crash

### ISSUE THREAD

**Issue by Sulverus** [tarantool/tarantool#1083]
During microb tests run. crash after restart.
This bug is blocking for 1.6.7 benchmarks
Reproduced in release build
```
#0 0x42a500 in sig_fatal_cb(int)+112
#1 0x7f6a4c6d6340 in ?
#2 0x48f011 in coeio_async_cb(ev_loop*, ev_async*, int)+17
#3 0x56b07d in ev_invoke_pending+93
#4 0x56e2f9 in ev_run+2089
#5 0x49c9dc in tarantool_lua_run_script(char*, int, char**)+108
#6 0x428fdb in main+299
```

**Comment by Sulverus** [comment]
Seems like fix is not working: after night benchmark:
```
#0  0x42a500 in sig_fatal_cb(int)+112
#1  0x7fbf261bb340 in ?
#2  0x48f011 in coeio_async_cb(ev_loop*, ev_async*, int)+17
#3  0x56b09d in ev_invoke_pending+93
#4  0x56e319 in ev_run+2089
#5  0x49c9dc in tarantool_lua_run_script(char*, int, char**)+108
#6  0x428fdb in main+299
```

**Comment by Sulverus** [comment]
It works! http://sh5.tarantool.org/?first=1.6.6-221-g7142aad&last=1.6.7-197-g008c20c
