### ISSUE TITLE
Memory leak in `replica_def_new_from_tuple`

### ISSUE THREAD

**Issue by Serpentian** [tarantool/tarantool#10881]
**Bug description**

Memory leaks during Tarantool shutdown in transactions with `SUBMIT` commit mode. 

* OS: Linux
* OS Version: Ubuntu Jammy
* Architecture: amd64

**Steps to reproduce**

```sh
cmake -DCMAKE_BUILD_TYPE=Debug -DENABLE_ASAN=ON .
make -j
./test-run.py --builddir=.. $(yes replication/gc.test | head -100)
```

[Workflow link](https://github.com/tarantool/tarantool/actions/runs/12084633916/job/33700227206?pr=10861#step:8:7060)
Logs: [logs_31478315951.zip](https://github.com/user-attachments/files/17962104/logs_31478315951.zip)

**Actual behavior**

```c
=================================================================
==783121==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 140 byte(s) in 1 object(s) allocated from:
    #0 0x7f367dab4887 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:145
    #1 0x55bc0fa0939c in small_asan_alloc /home/serpentian/Programming/tnt/tarantool/src/lib/small/small/util.c:94
    #2 0x55bc0fa0790b in region_prepare_buf /home/serpentian/Programming/tnt/tarantool/src/lib/small/small/region_asan.c:39
    #3 0x55bc0fa07cb2 in region_aligned_alloc /home/serpentian/Programming/tnt/tarantool/src/lib/small/small/region_asan.c:94
    #4 0x55bc0edf84e9 in replica_def_new_from_tuple /home/serpentian/Programming/tnt/tarantool/src/box/alter.cc:4553
    #5 0x55bc0edfab1b in on_replace_dd_cluster /home/serpentian/Programming/tnt/tarantool/src/box/alter.cc:4867
    #6 0x55bc0f1f7f11 in trigger_run_list /home/serpentian/Programming/tnt/tarantool/src/lib/core/trigger.cc:100
    #7 0x55bc0f1f81a9 in trigger_run /home/serpentian/Programming/tnt/tarantool/src/lib/core/trigger.cc:133
    #8 0x55bc0eda0939 in space_on_replace /home/serpentian/Programming/tnt/tarantool/src/box/space.c:1036
    #9 0x55bc0ee2611f in txn_commit_stmt /home/serpentian/Programming/tnt/tarantool/src/box/txn.c:758
    #10 0x55bc0ee4d49c in box_process_rw /home/serpentian/Programming/tnt/tarantool/src/box/box.cc:513
    #11 0x55bc0eebc844 in apply_request /home/serpentian/Programming/tnt/tarantool/src/box/applier.cc:313
    #12 0x55bc0eec52e8 in apply_plain_tx /home/serpentian/Programming/tnt/tarantool/src/box/applier.cc:1412
    #13 0x55bc0eec6eb6 in applier_apply_tx /home/serpentian/Programming/tnt/tarantool/src/box/applier.cc:1695
    #14 0x55bc0eec7d52 in applier_process_batch /home/serpentian/Programming/tnt/tarantool/src/box/applier.cc:1899
    #15 0x55bc0eecc058 in applier_subscribe /home/serpentian/Programming/tnt/tarantool/src/box/applier.cc:2506
    #16 0x55bc0eecc565 in applier_f /home/serpentian/Programming/tnt/tarantool/src/box/applier.cc:2586
    #17 0x55bc0eb5881a in fiber_cxx_invoke /home/serpentian/Programming/tnt/tarantool/src/lib/core/fiber.h:1324
    #18 0x55bc0f19ab78 in fiber_loop /home/serpentian/Programming/tnt/tarantool/src/lib/core/fiber.c:1167
    #19 0x55bc0fa63063 in coro_init /home/serpentian/Programming/tnt/tarantool/third_party/coro/coro.c:108

SUMMARY: AddressSanitizer: 140 byte(s) leaked in 1 allocation(s).
```

<details><summary>Full instance log</summary>
<p>

```
Starting instance replica2...
started
Run console at unix/:/tmp/t/002_replication/replica2.control
tcp_server: remove dead UNIX socket: /tmp/t/002_replication/replica2.control
started
2024-11-29 17:20:19.152 [783121] main/105/replica2 main.cc:497 I> Tarantool 3.3.0-entrypoint-268-g89cd7f43fd Linux-x86_64-Debug
2024-11-29 17:20:19.152 [783121] main/105/replica2 main.cc:500 I> log level 5 (INFO)
2024-11-29 17:20:19.152 [783121] main/105/replica2 gc.c:131 I> wal/engine cleanup is paused
2024-11-29 17:20:19.152 [783121] main/105/replica2 tuple.c:410 I> mapping 117440512 bytes for memtx tuple arena...
2024-11-29 17:20:19.152 [783121] main/105/replica2 memtx_engine.cc:1769 I> Actual slab_alloc_factor calculated on the basis of desired slab_alloc_factor = 1.050000
2024-11-29 17:20:19.152 [783121] main/105/replica2 tuple.c:410 I> mapping 134217728 bytes for vinyl tuple arena...
2024-11-29 17:20:19.158 [783121] main/105/replica2/box.upgrade upgrade.lua:1591 I> Recovering snapshot with schema version 3.3.0
2024-11-29 17:20:19.166 [783121] main/105/replica2 box.cc:2238 I> update replication_synchro_quorum = 1
2024-11-29 17:20:19.166 [783121] main/105/replica2 box.cc:3270 I> The option replication_synchro_queue_max_size will actually take effect after the recovery is finished
2024-11-29 17:20:19.166 [783121] main/105/replica2 box.cc:5434 I> instance uuid 99929522-8bb6-4600-92d7-a1e1ee64ca54
2024-11-29 17:20:19.168 [783121] main/105/replica2 box.cc:5463 I> instance vclock {1: 331}
2024-11-29 17:20:19.168 [783121] main/105/replica2 evio.c:267 I> tx_binary: bound to unix/:(socket)
2024-11-29 17:20:19.168 [783121] main/105/replica2 replication.cc:1095 I> connecting to 1 replicas
2024-11-29 17:20:19.171 [783121] main/115/applier/unix/:/tmp/t/002_replication/master.i applier.cc:670 I> remote master 8445ec5e-37b6-4f3a-94e2-c178d8b7faf3 at unix/:/tmp/t/002_replication/master.i running Tarantool 3.3.0
2024-11-29 17:20:19.172 [783121] main/105/replica2 replication.cc:1171 I> connected to 1 replicas
2024-11-29 17:20:19.172 [783121] main/105/replica2 memtx_engine.cc:286 I> recovery start
2024-11-29 17:20:19.172 [783121] main/105/replica2 memtx_engine.cc:291 I> recovering from `/tmp/t/002_replication/replica2/00000000000000000330.snap'
2024-11-29 17:20:19.172 [783121] main/105/replica2 alter.cc:4163 I> replicaset uuid 0716bb90-eee4-41b5-8a63-35ef8b6d755b
2024-11-29 17:20:19.302 [783121] main/105/replica2 replication.cc:411 I> assigned id 1 to replica 8445ec5e-37b6-4f3a-94e2-c178d8b7faf3
2024-11-29 17:20:19.303 [783121] main/105/replica2 box.cc:2238 I> update replication_synchro_quorum = 1
2024-11-29 17:20:19.305 [783121] main/105/replica2 replication.cc:411 I> assigned id 2 to replica 1a7570a5-8f90-458e-a9ef-5d8364baed9c
2024-11-29 17:20:19.306 [783121] main/105/replica2 box.cc:2238 I> update replication_synchro_quorum = 2
2024-11-29 17:20:19.306 [783121] main/105/replica2 raft.c:637 I> RAFT: fencing paused
2024-11-29 17:20:19.306 [783121] main/105/replica2 replication.cc:411 I> assigned id 3 to replica 99929522-8bb6-4600-92d7-a1e1ee64ca54
2024-11-29 17:20:19.306 [783121] main/105/replica2 box.cc:2238 I> update replication_synchro_quorum = 2
2024-11-29 17:20:19.306 [783121] main/105/replica2 recovery.cc:370 I> recover from `/tmp/t/002_replication/replica2/00000000000000000330.xlog'
2024-11-29 17:20:19.306 [783121] main/105/replica2 replication.cc:411 I> assigned id 4 to replica f2b0c3b1-b6b3-4e6c-8556-ff705c25f81f
2024-11-29 17:20:19.308 [783121] main/105/replica2 box.cc:2238 I> update replication_synchro_quorum = 3
2024-11-29 17:20:19.308 [783121] main/105/replica2 raft.c:637 I> RAFT: fencing paused
2024-11-29 17:20:19.308 [783121] main/105/replica2 recovery.cc:159 I> done `/tmp/t/002_replication/replica2/00000000000000000330.xlog'
2024-11-29 17:20:19.308 [783121] main/105/replica2 recovery.cc:370 I> recover from `/tmp/t/002_replication/replica2/00000000000000000331.xlog'
2024-11-29 17:20:19.308 [783121] main/105/replica2 recovery.cc:159 I> done `/tmp/t/002_replication/replica2/00000000000000000331.xlog'
2024-11-29 17:20:19.314 [783121] main/105/replica2 box.cc:5841 I> ready to accept requests
2024-11-29 17:20:19.314 [783121] main/105/replica2 replication.cc:1304 I> synchronizing with 1 replicas
2024-11-29 17:20:19.317 [783121] main/115/applier/unix/:/tmp/t/002_replication/master.i applier.cc:2424 I> subscribed
2024-11-29 17:20:19.317 [783121] main/115/applier/unix/:/tmp/t/002_replication/master.i applier.cc:2425 I> remote vclock {1: 371} local vclock {1: 331}
2024-11-29 17:20:19.318 [783121] main/115/applier/unix/:/tmp/t/002_replication/master.i raft.c:507 I> RAFT: message {term: 1, state: follower} from 1
2024-11-29 17:20:19.322 [783121] main box.cc:592 I> leaving orphan mode
2024-11-29 17:20:19.322 [783121] main/105/replica2 replication.cc:1330 I> replica set sync complete
2024-11-29 17:20:19.322 [783121] main/105/replica2 box.cc:592 I> leaving orphan mode
2024-11-29 17:20:19.323 [783121] main/105/replica2/box.load_cfg load_cfg.lua:939 I> set 'replication_sync_timeout' configuration option to 100
2024-11-29 17:20:19.323 [783121] main/105/replica2/box.load_cfg load_cfg.lua:939 I> set 'replication_timeout' configuration option to 0.1
2024-11-29 17:20:19.323 [783121] main/105/replica2/box.load_cfg load_cfg.lua:939 I> set 'log' configuration option to "/tmp/t/002_replication/replica2.log"
2024-11-29 17:20:19.323 [783121] main/105/replica2/box.load_cfg load_cfg.lua:939 I> set 'listen' configuration option to "/tmp/t/002_replication/replica2.i"
2024-11-29 17:20:19.323 [783121] main/105/replica2/box.load_cfg load_cfg.lua:939 I> set 'replication' configuration option to ["/tmp/t/002_replication/master.i"]
2024-11-29 17:20:19.323 [783121] main/105/replica2/box.load_cfg load_cfg.lua:939 I> set 'bootstrap_strategy' configuration option to "legacy"
2024-11-29 17:20:19.323 [783121] main/105/replica2/box.load_cfg load_cfg.lua:939 I> set 'memtx_memory' configuration option to 107374182
2024-11-29 17:20:19.323 [783121] main/109/checkpoint_daemon gc.c:643 I> scheduled next checkpoint for Fri Nov 29 19:18:28 2024
2024-11-29 17:20:19.324 [783121] main main.cc:1075 I> entering the event loop
2024-11-29 17:20:20.426 [783121] main replication.cc:461 I> removed replica 1a7570a5-8f90-458e-a9ef-5d8364baed9c
2024-11-29 17:20:20.426 [783121] main box.cc:2238 I> update replication_synchro_quorum = 2
2024-11-29 17:20:20.533 [783121] main main.cc:201 C> got signal 15 - Terminated
2024-11-29 17:20:20.533 [783121] main/124/console/unix/: utils.c:700 E> LuajitError: builtin/socket.lua:89: attempt to use closed socket
2024-11-29 17:20:20.533 [783121] main/127/iproto.shutdown evio.c:516 I> tx_binary: stopped
2024-11-29 17:20:20.534 [783121] applier_1/103/writer/unix/:/tmp/t/002_replication/master.i exception.cc:200 I> fiber `writer/unix/:/tmp/t/002_replication/master.i' has been cancelled
2024-11-29 17:20:20.534 [783121] applier_1/103/writer/unix/:/tmp/t/002_replication/master.i exception.cc:202 I> fiber `writer/unix/:/tmp/t/002_replication/master.i': exiting

=================================================================
==783121==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 140 byte(s) in 1 object(s) allocated from:
    #0 0x7f367dab4887 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:145
    #1 0x55bc0fa0939c in small_asan_alloc /home/serpentian/Programming/tnt/tarantool/src/lib/small/small/util.c:94
    #2 0x55bc0fa0790b in region_prepare_buf /home/serpentian/Programming/tnt/tarantool/src/lib/small/small/region_asan.c:39
    #3 0x55bc0fa07cb2 in region_aligned_alloc /home/serpentian/Programming/tnt/tarantool/src/lib/small/small/region_asan.c:94
    #4 0x55bc0edf84e9 in replica_def_new_from_tuple /home/serpentian/Programming/tnt/tarantool/src/box/alter.cc:4553
    #5 0x55bc0edfab1b in on_replace_dd_cluster /home/serpentian/Programming/tnt/tarantool/src/box/alter.cc:4867
    #6 0x55bc0f1f7f11 in trigger_run_list /home/serpentian/Programming/tnt/tarantool/src/lib/core/trigger.cc:100
    #7 0x55bc0f1f81a9 in trigger_run /home/serpentian/Programming/tnt/tarantool/src/lib/core/trigger.cc:133
    #8 0x55bc0eda0939 in space_on_replace /home/serpentian/Programming/tnt/tarantool/src/box/space.c:1036
    #9 0x55bc0ee2611f in txn_commit_stmt /home/serpentian/Programming/tnt/tarantool/src/box/txn.c:758
    #10 0x55bc0ee4d49c in box_process_rw /home/serpentian/Programming/tnt/tarantool/src/box/box.cc:513
    #11 0x55bc0eebc844 in apply_request /home/serpentian/Programming/tnt/tarantool/src/box/applier.cc:313
    #12 0x55bc0eec52e8 in apply_plain_tx /home/serpentian/Programming/tnt/tarantool/src/box/applier.cc:1412
    #13 0x55bc0eec6eb6 in applier_apply_tx /home/serpentian/Programming/tnt/tarantool/src/box/applier.cc:1695
    #14 0x55bc0eec7d52 in applier_process_batch /home/serpentian/Programming/tnt/tarantool/src/box/applier.cc:1899
    #15 0x55bc0eecc058 in applier_subscribe /home/serpentian/Programming/tnt/tarantool/src/box/applier.cc:2506
    #16 0x55bc0eecc565 in applier_f /home/serpentian/Programming/tnt/tarantool/src/box/applier.cc:2586
    #17 0x55bc0eb5881a in fiber_cxx_invoke /home/serpentian/Programming/tnt/tarantool/src/lib/core/fiber.h:1324
    #18 0x55bc0f19ab78 in fiber_loop /home/serpentian/Programming/tnt/tarantool/src/lib/core/fiber.c:1167
    #19 0x55bc0fa63063 in coro_init /home/serpentian/Programming/tnt/tarantool/third_party/coro/coro.c:108

SUMMARY: AddressSanitizer: 140 byte(s) leaked in 1 allocation(s).

```

</p>
</details> 

**Possible reason**

The leak is probably caused by an nonfreed `txn->region`. Applier commits transaction with `SUBMIT` mode, which means that we add them to the WAL queue and don't wait for end, relying on `txn_on_journal_write` or `txn_limbo` to call `txn_free`, which will truncate the region. However, when Tarantool fails, it seems we don't call `txn_free` for transactions in WAL queue, which causes that leak. Must be investigated, not very sure about the reason.

**Comment by sergepetrenko** [comment]
Another failure:
https://github.com/tarantool/tarantool/actions/runs/13703672816/job/38323614295

An excerpt from the replica logs:
```
==46040==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 140 byte(s) in 1 object(s) allocated from:
    #0 0x55f1d788758f in malloc (/__w/tarantool/tarantool/src/tarantool+0x33c58f) (BuildId: 7e66c42da94eb3668e92870808d9b717b8644e7f)
    #1 0x55f1d84e416a in small_asan_alloc /__w/tarantool/tarantool/src/lib/small/small/util.c:94:24
    #2 0x55f1d84e3112 in region_prepare_buf /__w/tarantool/tarantool/src/lib/small/small/region_asan.c:39:4
    #3 0x55f1d84e31d7 in region_aligned_alloc /__w/tarantool/tarantool/src/lib/small/small/region_asan.c:94:14
    #4 0x55f1d7b04218 in replica_def_new_from_tuple(tuple*, region*) /__w/tarantool/tarantool/src/box/alter.cc:4579:28
    #5 0x55f1d7ae5f8b in on_replace_dd_cluster(trigger*, void*) /__w/tarantool/tarantool/src/box/alter.cc:4893:13
    #6 0x55f1d7e727c2 in trigger_run_list(rlist*, void*) /__w/tarantool/tarantool/src/lib/core/trigger.cc:100:7
    #7 0x55f1d7e7215f in trigger_run /__w/tarantool/tarantool/src/lib/core/trigger.cc:133:9
    #8 0x55f1d7aa755c in space_on_replace /__w/tarantool/tarantool/src/box/space.c:1043:11
    #9 0x55f1d7b1f918 in txn_commit_stmt /__w/tarantool/tarantool/src/box/txn.c:721:13
    #10 0x55f1d7b403c6 in box_process_rw /__w/tarantool/tarantool/src/box/box.cc:509:6
    #11 0x55f1d7bb55b9 in apply_request(request*) /__w/tarantool/tarantool/src/box/applier.cc:313:6
    #12 0x55f1d7bb55b9 in apply_plain_tx(unsigned int, stailq*) /__w/tarantool/tarantool/src/box/applier.cc:1413:13
    #13 0x55f1d7bb55b9 in applier_apply_tx(applier*, stailq*) /__w/tarantool/tarantool/src/box/applier.cc:1696:8
    #14 0x55f1d7bb9b43 in applier_process_batch(cmsg*) /__w/tarantool/tarantool/src/box/applier.cc:1900:14
    #15 0x55f1d7badf44 in applier_subscribe(applier*) /__w/tarantool/tarantool/src/box/applier.cc:2507:3
    #16 0x55f1d7ba96e5 in applier_f(__va_list_tag*) /__w/tarantool/tarantool/src/box/applier.cc:2587:4
    #17 0x55f1d78cd2cb in fiber_cxx_invoke(int (*)(__va_list_tag*), __va_list_tag*) /__w/tarantool/tarantool/src/lib/core/fiber.h:1324:10
    #18 0x55f1d7e1c70b in fiber_loop /__w/tarantool/tarantool/src/lib/core/fiber.c:1167:18
    #19 0x55f1d853074c in coro_init /__w/tarantool/tarantool/third_party/coro/coro.c:108:3

SUMMARY: AddressSanitizer: 140 byte(s) leaked in 1 allocation(s).
```

**Comment by Shevchenko-Daniil** [comment]
Комментарий для комментария

**Comment by mkostoevr** [comment]
Might be fixed with 91ff7c899917513adcc4d3c51ae904ee7fdc9885, but I haven't found a viable reproduce.

None of the links provided above are working, and the test from #12245 doesn't fail before the fix it provides applied (as I've tried to run it, I might have done it wrong).
