### ISSUE TITLE
update crashes during bitset index iteration

### ISSUE THREAD

**Issue by alyapunov** [tarantool/tarantool#1088]
There is a space with secondary bitset index and there are several fibers running lua code, that iterates tuples with BITSET_ALL_NOT_SET iterator and updates one of them (not a bitset field). And tarantool crashes..

```
#0  0x43db10 in sig_fatal_cb(int)+112
#1  0x7fd5346d5710 in ?
#2  0x418e55 in tuple_alloc(tuple_format*, unsigned long)+37
#3  0x419369 in tuple_update(tuple_format*, void* (*)(void*, unsigned long), void*, tuple const*, char const*, char const*)+105
#4  0x42e7e2 in request_execute(request*, txn*, port*)+994
#5  0x42f507 in process_rw(port*, unsigned int, char const*, unsigned int)+87
#6  0x430bd4 in lbox_process(lua_State*)+148
#7  0x48f188 in lj_BC_FUNCC+52
```

https://jira.mail.ru/browse/MNT-117151

**Comment by PSIAlt** [comment]
Can be reproduced when iterating BITSET
```
for v in box.space[0].index[1]:iterator(box.index.BITS_ALL_NOT_SET, 1) do
  ...
  if cond then
       return box.update(0, v[0], .....
  end
  box.fiber.sleep(0)
end
```
Need to make concurrent calls for this lua from different connections.
