### ISSUE TITLE
luajit assertion failure in rtree_misc.test

### ISSUE THREAD

**Issue by kostja** [tarantool/tarantool#1099]
The server crashes in a LuaJIT assert if `rtree_misc.test` is run repeatedly for some time. 
This test also crashes once in a while as part of the main test suite.
```
 % gdb ../src/tarantool -c var/core 
GNU gdb (Ubuntu 7.7.1-0ubuntu5~14.04.2) 7.7.1
Reading symbols from ../src/tarantool...done.
[New LWP 13021]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `tarantool tarantoolctl: running@box                                          '.
Program terminated with signal SIGABRT, Aborted.
#0  0x00007f293871bcc9 in __GI_raise (sig=sig@entry=6)
    at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
56	../nptl/sysdeps/unix/sysv/linux/raise.c: No such file or directory.
Traceback (most recent call last):
  File "/usr/share/gdb/auto-load/usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.19-gdb.py", line 63, in <module>
    from libstdcxx.v6.printers import register_libstdcxx_printers
ImportError: No module named 'libstdcxx'
(gdb) bt
#0  0x00007f293871bcc9 in __GI_raise (sig=sig@entry=6)
    at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x00007f293871f0d8 in __GI_abort () at abort.c:89
#2  0x00007f2938714b86 in __assert_fail_base (
    fmt=0x7f2938865830 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", 
    assertion=assertion@entry=0x692d20 "itype2irt(tv) == ((IRType)(((tr)>>24) & IRT_TYPE))", file=file@entry=0x692550 "lj_record.c", line=line@entry=113, 
    function=function@entry=0x694080 <__PRETTY_FUNCTION__.5405> "rec_check_slots") at assert.c:92
#3  0x00007f2938714c32 in __GI___assert_fail (
    assertion=0x692d20 "itype2irt(tv) == ((IRType)(((tr)>>24) & IRT_TYPE))", 
    file=0x692550 "lj_record.c", line=113, 
    function=0x694080 <__PRETTY_FUNCTION__.5405> "rec_check_slots")
    at assert.c:101
#4  0x000000000054eb61 in rec_check_slots (J=0x4166f550) at lj_record.c:113
#5  0x0000000000558cf1 in lj_record_ins (J=0x4166f550) at lj_record.c:1708
#6  0x000000000051ddd2 in trace_state (L=0x41fb8560, dummy=0x0, ud=0x4166f550)
    at lj_trace.c:597
#7  0x000000000053746b in lj_vm_cpcall ()
#8  0x000000000051e1f5 in lj_trace_ins (J=0x4166f550, pc=0x4166f4a4)
    at lj_trace.c:656
#9  0x00000000005065f5 in lj_dispatch_call (L=0x41fb8560, pc=0x4166f4a8)
    at lj_dispatch.c:468
#10 0x0000000000538b6e in lj_vm_hotcall ()
#11 0x000000000050ea16 in lua_call (L=0x41fb8560, nargs=3, nresults=-1)
    at lj_api.c:1034
#12 0x00000000004a2d20 in lbox_call (L=0x41fb8560, nargs=3, nreturns=-1)
    at /home/kostja/work/tarantool-1.6/src/lua/utils.h:527
#13 0x00000000004a3854 in box_lua_fiber_run(typedef __va_list_tag __va_list_tag *) (ap=0x7f29374001b8) at /home/kostja/work/tarantool-1.6/src/lua/fiber.cc:303
#14 0x00000000004b2783 in fiber_loop (data=0x0)
    at /home/kostja/work/tarantool-1.6/src/fiber.cc:415
#15 0x00000000005f6e67 in coro_init ()
    at /home/kostja/work/tarantool-1.6/third_party/coro/coro.c:96
```

**Comment by rtsisyk** [comment]
Fixed by upgrading LuaJIT to v2.1 and applying patch from https://github.com/LuaJIT/LuaJIT/issues/103. Thanks @mraleph for the fix in upstream.
