### ISSUE TITLE
search: segfault on commit during test

### ISSUE THREAD

**Issue by pmwkaa** [tarantool/tarantool#1116]
```
Segmentation fault
Current time: 1446030945
Please file a bug at http://github.com/tarantool/tarantool/issues
Attempting backtrace... Note: since the server has already crashed,
this may fail as well
#0 0x42a810 in sig_fatal_cb(int)+112
#1 0x7f80c4866790 in ?
#2 0x44f478 in txn_commit(txn*)+440
#3 0x44f9b8 in box_txn_commit+40
#4 0x7f8076dedb5e in ?
#5 0x7f8076ded888 in ?
#6 0x473623 in box_lua_call(request*, obuf*)+1651
#7 0x461898 in tx_process_msg(cmsg*)+440
#8 0x4adb28 in cpipe_fiber_pool_f+120
#9 0x4ab969 in fiber_loop(void*)+41
#10 0x6099af in coro_init+63
#11 0x422fa0 in ?
```

```
#0 0x00007f80c3b39625 in raise () from /lib64/libc.so.6
#1 0x00007f80c3b3ae05 in abort () from /lib64/libc.so.6
#2 0x000000000042a84c in sig_fatal_cb (signo=<optimized out>) at /mnt/24/tarantool-instance-bench-2/tarantool/src/main.cc:222
#3 <signal handler called>
#4 0x0000000000600510 in region_free (region=0x7f80bc000c38)
 at /mnt/24/tarantool-instance-bench-2/tarantool/src/lib/small/region.c:58
#5 0x000000000044f478 in txn_commit (txn=0x7f80bc328038) at /mnt/24/tarantool-instance-bench-2/tarantool/src/box/txn.cc:184
#6 0x000000000044f9b8 in box_txn_commit () at /mnt/24/tarantool-instance-bench-2/tarantool/src/box/txn.cc:271
```

core file is available upon request.

**Comment by kostja** [comment]
Should be solved after the last rebase.

**Comment by kostja** [comment]
Too old with no feedback.
