### ISSUE TITLE
"Broken tarantool console handshake" from test-run

### ISSUE THREAD

**Issue by kostja** [tarantool/tarantool#1163]
```
box/cfg.test.lua                                                Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/gevent/greenlet.py", line 327, in run
    result = self._run(*self.args, **self.kwargs)
  File "/opt/local/work/tarantool/test-run/lib/tarantool_connection.py", line 54, in _addOne
    c = self._new_connection()
  File "/opt/local/work/tarantool/test-run/lib/admin_connection.py", line 38, in _new_connection
    raise RuntimeError('Broken tarantool console handshake')
RuntimeError: Broken tarantool console handshake
<Greenlet at 0x2ba65bafd190: <bound method AdminPool._addOne of <lib.admin_connection.AdminPool object at 0x2ba65bae1bd0>>> failed with RuntimeError

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/gevent/greenlet.py", line 327, in run
    result = self._run(*self.args, **self.kwargs)
  File "/opt/local/work/tarantool/test-run/lib/tarantool_connection.py", line 54, in _addOne
    c = self._new_connection()
  File "/opt/local/work/tarantool/test-run/lib/admin_connection.py", line 38, in _new_connection
    raise RuntimeError('Broken tarantool console handshake')
RuntimeError: Broken tarantool console handshake
<Greenlet at 0x2ba65bacbe10: <bound method AdminPool._addOne of <lib.admin_connection.AdminPool object at 0x2ba65baf1cd0>>> failed with RuntimeError

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/gevent/greenlet.py", line 327, in run
    result = self._run(*self.args, **self.kwargs)
  File "/opt/local/work/tarantool/test-run/lib/tarantool_connection.py", line 54, in _addOne
    c = self._new_connection()
  File "/opt/local/work/tarantool/test-run/lib/admin_connection.py", line 38, in _new_connection
    raise RuntimeError('Broken tarantool console handshake')
RuntimeError: Broken tarantool console handshake
<Greenlet at 0x2ba65bacbf50: <bound method AdminPool._addOne of <lib.admin_connection.AdminPool object at 0x2ba65b6aa790>>> failed with RuntimeError

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/gevent/greenlet.py", line 327, in run
    result = self._run(*self.args, **self.kwargs)
  File "/opt/local/work/tarantool/test-run/lib/tarantool_connection.py", line 54, in _addOne
    c = self._new_connection()
  File "/opt/local/work/tarantool/test-run/lib/admin_connection.py", line 38, in _new_connection
    raise RuntimeError('Broken tarantool console handshake')
RuntimeError: Broken tarantool console handshake
<Greenlet at 0x2ba65bafd0f0: <bound method AdminPool._addOne of <lib.admin_connection.AdminPool object at 0x2ba65bae1bd0>>> failed with RuntimeError

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/gevent/greenlet.py", line 327, in run
    result = self._run(*self.args, **self.kwargs)
  File "/opt/local/work/tarantool/test-run/lib/tarantool_connection.py", line 54, in _addOne
    c = self._new_connection()
  File "/opt/local/work/tarantool/test-run/lib/admin_connection.py", line 38, in _new_connection
    raise RuntimeError('Broken tarantool console handshake')
RuntimeError: Broken tarantool console handshake
<Greenlet at 0x2ba65bacba50: <bound method AdminPool._addOne of <lib.admin_connection.AdminPool object at 0x2ba65baf1cd0>>> failed with RuntimeError

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/gevent/greenlet.py", line 327, in run
    result = self._run(*self.args, **self.kwargs)
  File "/opt/local/work/tarantool/test-run/lib/tarantool_connection.py", line 54, in _addOne
    c = self._new_connection()
  File "/opt/local/work/tarantool/test-run/lib/admin_connection.py", line 38, in _new_connection
    raise RuntimeError('Broken tarantool console handshake')
RuntimeError: Broken tarantool console handshake
<Greenlet at 0x2ba65bafd050: <bound method AdminPool._addOne of <lib.admin_connection.AdminPool object at 0x2ba65b6aa790>>> failed with RuntimeError
```

**Comment by Sulverus** [comment]
Test run updated: https://github.com/tarantool/test-run/commit/babae1315fc5671dea13ef8f0f17f5555fb8b8f9

**Comment by rtsisyk** [comment]
```
engine/recover_snapshot_wal.test.lua            memtx           Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/gevent/greenlet.py", line 327, in run
    result = self._run(*self.args, **self.kwargs)
  File "/home/roman/rpmbuild/BUILD/tarantool-1.6.8.459/test-run/lib/tarantool_connection.py", line 54, in _addOne
    c = self._new_connection()
  File "/home/roman/rpmbuild/BUILD/tarantool-1.6.8.459/test-run/lib/admin_connection.py", line 47, in _new_connection
    raise RuntimeError('Broken tarantool console handshake')
RuntimeError: Broken tarantool console handshake
<Greenlet at 0x1f37690: <bound method AdminPool._addOne of <lib.admin_connection.AdminPool object at 0x1f9dd90>>> failed with RuntimeError

Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/gevent/greenlet.py", line 327, in run
    result = self._run(*self.args, **self.kwargs)
  File "/home/roman/rpmbuild/BUILD/tarantool-1.6.8.459/test-run/lib/tarantool_connection.py", line 54, in _addOne
    c = self._new_connection()
  File "/home/roman/rpmbuild/BUILD/tarantool-1.6.8.459/test-run/lib/admin_connection.py", line 47, in _new_connection
    raise RuntimeError('Broken tarantool console handshake')
RuntimeError: Broken tarantool console handshake
<Greenlet at 0x1ee2f50: <bound method AdminPool._addOne of <lib.admin_connection.AdminPool object at 0x1f9d2d0>>> failed with RuntimeError

Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/gevent/greenlet.py", line 327, in run
    result = self._run(*self.args, **self.kwargs)
  File "/home/roman/rpmbuild/BUILD/tarantool-1.6.8.459/test-run/lib/tarantool_connection.py", line 54, in _addOne
    c = self._new_connection()
  File "/home/roman/rpmbuild/BUILD/tarantool-1.6.8.459/test-run/lib/admin_connection.py", line 47, in _new_connection
    raise RuntimeError('Broken tarantool console handshake')
RuntimeError: Broken tarantool console handshake
<Greenlet at 0x1ee24b0: <bound method AdminPool._addOne of <lib.admin_connection.AdminPool object at 0x1f9d2d0>>> failed with RuntimeError

Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/gevent/greenlet.py", line 327, in run
    result = self._run(*self.args, **self.kwargs)
  File "/home/roman/rpmbuild/BUILD/tarantool-1.6.8.459/test-run/lib/tarantool_connection.py", line 54, in _addOne
    c = self._new_connection()
  File "/home/roman/rpmbuild/BUILD/tarantool-1.6.8.459/test-run/lib/admin_connection.py", line 47, in _new_connection
    raise RuntimeError('Broken tarantool console handshake')
RuntimeError: Broken tarantool console handshake
<Greenlet at 0x1f37b90: <bound method AdminPool._addOne of <lib.admin_connection.AdminPool object at 0x1f9dd10>>> failed with RuntimeError

Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/gevent/greenlet.py", line 327, in run
    result = self._run(*self.args, **self.kwargs)
  File "/home/roman/rpmbuild/BUILD/tarantool-1.6.8.459/test-run/lib/tarantool_connection.py", line 54, in _addOne
    c = self._new_connection()
  File "/home/roman/rpmbuild/BUILD/tarantool-1.6.8.459/test-run/lib/admin_connection.py", line 47, in _new_connection
    raise RuntimeError('Broken tarantool console handshake')
RuntimeError: Broken tarantool console handshake
<Greenlet at 0x1f37e10: <bound method AdminPool._addOne of <lib.admin_connection.AdminPool object at 0x1f9dd10>>> failed with RuntimeError

Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/gevent/greenlet.py", line 327, in run
    result = self._run(*self.args, **self.kwargs)
  File "/home/roman/rpmbuild/BUILD/tarantool-1.6.8.459/test-run/lib/tarantool_connection.py", line 54, in _addOne
    c = self._new_connection()
  File "/home/roman/rpmbuild/BUILD/tarantool-1.6.8.459/test-run/lib/admin_connection.py", line 47, in _new_connection
    raise RuntimeError('Broken tarantool console handshake')
RuntimeError: Broken tarantool console handshake
<Greenlet at 0x1f37cd0: <bound method AdminPool._addOne of <lib.admin_connection.AdminPool object at 0x1f9dd90>>> failed with RuntimeError

[ pass ]
engine/recover_snapshot_wal.test.lua            sophia          [ pass ]

```

I tired to see this garbage. Please fix ASAP.

**Comment by rtsisyk** [comment]
```
engine/replica_join.test.lua                    sophia          Traceback (most recent call last):

  File "/usr/lib64/python2.7/site-packages/gevent/greenlet.py", line 534, in run

    result = self._run(*self.args, **self.kwargs)

  File "/home/travis/rpmbuild/BUILD/tarantool-1.7.0.723/test-run/lib/tarantool_connection.py", line 54, in _addOne

    c = self._new_connection()

  File "/home/travis/rpmbuild/BUILD/tarantool-1.7.0.723/test-run/lib/admin_connection.py", line 54, in _new_connection

    raise RuntimeError('Broken tarantool console handshake')

RuntimeError: Broken tarantool console handshake

<Greenlet at 0x7f688013e690: <bound method AdminPool._addOne of <lib.admin_connection.AdminPool object at 0x7f6880129090>>> failed with RuntimeError

Traceback (most recent call last):

  File "/usr/lib64/python2.7/site-packages/gevent/greenlet.py", line 534, in run

    result = self._run(*self.args, **self.kwargs)

  File "/home/travis/rpmbuild/BUILD/tarantool-1.7.0.723/test-run/lib/tarantool_connection.py", line 54, in _addOne

    c = self._new_connection()

  File "/home/travis/rpmbuild/BUILD/tarantool-1.7.0.723/test-run/lib/admin_connection.py", line 54, in _new_connection

    raise RuntimeError('Broken tarantool console handshake')

RuntimeError: Broken tarantool console handshake

<Greenlet at 0x7f688013e4b0: <bound method AdminPool._addOne of <lib.admin_connection.AdminPool object at 0x7f68800f0d50>>> failed with RuntimeError

Traceback (most recent call last):

  File "/usr/lib64/python2.7/site-packages/gevent/greenlet.py", line 534, in run

    result = self._run(*self.args, **self.kwargs)

  File "/home/travis/rpmbuild/BUILD/tarantool-1.7.0.723/test-run/lib/tarantool_connection.py", line 54, in _addOne

    c = self._new_connection()

  File "/home/travis/rpmbuild/BUILD/tarantool-1.7.0.723/test-run/lib/admin_connection.py", line 54, in _new_connection

    raise RuntimeError('Broken tarantool console handshake')

RuntimeError: Broken tarantool console handshake

<Greenlet at 0x7f688013ea50: <bound method AdminPool._addOne of <lib.admin_connection.AdminPool object at 0x7f68800f0750>>> failed with RuntimeError

[ fail ]

Test failed! Result content mismatch:

--- engine/replica_join.result	Sat Apr  2 12:32:30 2016

+++ engine/replica_join.reject	Sat Apr  2 12:37:13 2016

@@ -283,6 +283,21 @@

   - [123, 15129]

 ...

 test_run:cmd('switch default')

+Handshake error {

+Tarantool 1.7.0 (Binary) d7ebf5b3-9c62-48f9-929b-cd4cbaaa1df1  

+TZHHT1AtfNlL2Th9LLRlp43YKtt2r/w7vkuS3TwmhAo=                   

+

+}

+Handshake error {

+Tarantool 1.7.0 (Binary) d7ebf5b3-9c62-48f9-929b-cd4cbaaa1df1  

+mD5Ey5UfyqSysegGH5j8/peAepI+svkdBe+bMzoIqWE=                   

+

+}

+Handshake error {

+Tarantool 1.7.0 (Binary) d7ebf5b3-9c62-48f9-929b-cd4cbaaa1df1  

+8Pj0+9WfNGj2EzO4HkNH5fFxaWESMSx5Ti+WaseG36o=                   

+

+}

 ---

 - true

 ...
```

**Comment by rtsisyk** [comment]
!!!!
```
2016-09-09 20:08:22.063 [11856] main/101/tarantoolctl I> ready to accept requests
2016-09-09 20:08:22.063 [11856] main/101/replica I> Run console at unix/:/data/work/tarantool/1.7/test/var/replica.control
2016-09-09 20:08:22.063 [11856] main/101/replica I> tcp_server: remove dead UNIX socket: /data/work/tarantool/1.7/test/var/replica.control
2016-09-09 20:08:22.063 [11856] main/104/console/unix/:/data/work/tara I> started
2016-09-09 20:08:22.064 [11856] main/101/replica tarantoolctl:415 E> Start failed: builtin/console.lua:372: failed to create server localhost:3302: Address already in use

````
