### ISSUE TITLE
box_set_xxx() must not raise C++ exceptions

### ISSUE THREAD

**Issue by rtsisyk** [tarantool/tarantool#1216]
FreeBSD 10 x86:
```
TAP version 13
1..35
ok - box is not started
ok - invalid replication_source

Program received signal SIGBUS, Bus error.
[Switching to Thread 802806400 (LWP 100185/tarantool)]
0x000000080193df45 in __cxa_free_exception () from /lib/libcxxrt.so.1
(gdb) bt


#0  0x000000080193df45 in __cxa_free_exception () from /lib/libcxxrt.so.1
#1  0x000000000054af99 in lj_err_unwind_dwarf (version=1, actions=6, uexclass=5138137972254386944, uex=0x80282e0d8, ctx=0x80301f638) at lj_err.c:254
#2  0x0000000801b4e936 in _Unwind_RaiseException () from /lib/libgcc_s.so.1
#3  0x0000000801b4e63c in _Unwind_RaiseException () from /lib/libgcc_s.so.1
#4  0x000000080193e46c in __cxa_throw () from /lib/libcxxrt.so.1
#5  0x000000000045e20e in box_check_wal_mode (mode_name=0x80099d1d0 "invalid") at /home/rt/tarantool/src/box/box.cc:241
#6  0x000000000045dfad in box_check_config () at /home/rt/tarantool/src/box/box.cc:267
#7  0x00000000004289f9 in check_cfg () at /home/rt/tarantool/src/main.cc:334
#8  0x00000000005a2d09 in lj_vm_ffi_call ()
```

All box_set_XXX() functions must not raise C++ exceptions because LUAJIT_EXTERNAL_UNWIND is OFF.

Please convert these functions to Lua/C API and use luaL_error() or lbox_error().

**Comment by rtsisyk** [comment]
I need this fix to update package in FreeBSD.

**Comment by rtsisyk** [comment]
Fixed.
