### ISSUE TITLE
`test-run.py` hangs up on Mac OS 

### ISSUE THREAD

**Issue by bigbes** [tarantool/tarantool#1362]
```
box/sql.test.lua                                                ^CTraceback (most recent call last):
  File "/Library/Python/2.7/site-packages/gevent/greenlet.py", line 327, in run
    result = self._run(*self.args, **self.kwargs)
  File "/Users/blikh/src/work/tarantool/test-run/lib/tarantool_connection.py", line 54, in _addOne
    c = self._new_connection()
  File "/Users/blikh/src/work/tarantool/test-run/lib/admin_connection.py", line 45, in _new_connection
    handshake = get_handshake(s)
  File "/Users/blikh/src/work/tarantool/test-run/lib/admin_connection.py", line 39, in get_handshake
    result = "%s%s" % (result, sock.recv(length-len(result)))
  File "/Library/Python/2.7/site-packages/gevent/socket.py", line 387, in recv
    return sock.recv(*args)
KeyboardInterrupt
<Greenlet at 0x102d73f50: <bound method AdminPool._addOne of <lib.admin_connection.AdminPool object at 0x102d7dc10>>> failed with KeyboardInterrupt


---------------------------------------------------------------------------
Stopping the server ...
^CTraceback (most recent call last):
  File "./test-run.py", line 215, in <module>
    exit(main())
  File "./test-run.py", line 193, in main
    failed_tests.extend(suite.run_all())
  File "/Users/blikh/src/work/tarantool/test-run/lib/test_suite.py", line 163, in run_all
    self.server.stop(silent=False)
  File "/Users/blikh/src/work/tarantool/test-run/lib/tarantool_server.py", line 599, in stop
    self.wait_stop()
  File "/Users/blikh/src/work/tarantool/test-run/lib/tarantool_server.py", line 577, in wait_stop
    self.process.wait()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1384, in wait
    pid, sts = _eintr_retry_call(os.waitpid, self.pid, 0)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 476, in _eintr_retry_call
    return func(*args)
KeyboardInterrupt
[INFO/MainProcess] process shutting down
make[3]: *** [test/CMakeFiles/test] Error 1
make[2]: *** [test/CMakeFiles/test.dir/all] Interrupt: 2
make[1]: *** [test/CMakeFiles/test.dir/rule] Interrupt: 2
make: *** [test] Interrupt: 2
```

**Comment by bigbes** [comment]
test/var/box.log:
```
2016-03-04 13:21:28.902 [35898] main/104/console/unix/:/Users/blikh/sr I> started
2016-03-04 13:21:28.902 [35898] main/105/console/unix/:/Users/blikh/sr I> started
2016-03-04 13:21:28.902 [35898] main C> entering the event loop
2016-03-04 13:21:28.904 [35898] main/106/console/unix/: I> client unix/: connected
2016-03-04 13:21:28.905 [35898] main/106/console/unix/: I> client unix/: disconnected
2016-03-04 13:21:33.113 [35898] main C> got signal 2 - Interrupt: 2
```
test/var/sql.result
```
test_run:cmd('restart server default')
```

**Comment by pgulutzan** [comment]
For me, test.run.py is hanging on Ubuntu 12.04.

**Comment by Sulverus** [comment]
Merged. Confirmed in travis https://travis-ci.org/tarantool/tarantool/builds/116362765
@pgulutzan please check, that you use latest tarantool 1.6 sources and latest test-run (`git submodule update --init --recursive`)

**Comment by pgulutzan** [comment]
@Sulverus --Yes I used the latest Tarantool 1.6 sources, yes I said git submodule update --init --recursive, and test-run.py is still hanging today. However, I now believe that the relevant issue report for this problem is issue#1341, not issue#1362.
