### ISSUE TITLE
Segmentation fault if shutdown under load (Phia)

### ISSUE THREAD

**Issue by kostja** [tarantool/tarantool#1479]
```
box.cfg{}
box.schema.space.create('test', {engine='phia'})
box.space.test:create_index('pk')
for i=1,100000000 do box.space.test:insert{i, 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa'} end
```
```
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `tarantool <r'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00000000004931d1 in sd_read_page (i=0x7f30bbff9bb3, ref=0x7860) at /home/kostja/work/tarantool/src/box/phia.c:8246
8246            int rc = ss_bufensure(arg->buf, r->a, ref->sizeorigin);
(gdb) bt
#0  0x00000000004931d1 in sd_read_page (i=0x7f30bbff9bb3, ref=0x7860) at /home/kostja/work/tarantool/src/box/phia.c:8246
#1  0x000000000049372c in sd_read_openpage (i=0x7f30bbff9bb3, key=0x0, keysize=0) at /home/kostja/work/tarantool/src/box/phia.c:8316
#2  0x0000000000493ad5 in sd_read_next (iptr=0x7f30bbff9bab) at /home/kostja/work/tarantool/src/box/phia.c:8398
#3  0x000000000048cd2e in sv_mergeiter_gt (i=0x7f30bbff98f8) at /home/kostja/work/tarantool/src/box/phia.c:5551
#4  0x000000000048d05d in sv_mergeiter_next (it=0x7f30bbff98f0) at /home/kostja/work/tarantool/src/box/phia.c:5645
#5  0x000000000048da12 in sv_writeiter_next (i=0x7f30bbff9570) at /home/kostja/work/tarantool/src/box/phia.c:5914
#6  0x00000000004964a8 in sd_mergepage (m=0x7f30bbff9520, offset=100488504) at /home/kostja/work/tarantool/src/box/phia.c:9191
#7  0x000000000049ce0b in si_split (index=0xfe28b0, c=0x7f30bc000a50, result=0x7f30bc000ed8, parent=0x7f30b0009a60, i=0x7f30bbff98f0, size_node=67108864, 
    size_stream=108522850, stream=1205293, vlsn=10903089, vlsn_lru=0) at /home/kostja/work/tarantool/src/box/phia.c:11465
#8  0x000000000049d0e4 in si_merge (index=0xfe28b0, c=0x7f30bc000a50, node=0x7f30b0009a60, vlsn=10903089, vlsn_lru=0, stream=0x7f30bbff98f0, 
    size_stream=108522850, n_stream=1205293) at /home/kostja/work/tarantool/src/box/phia.c:11532
#9  0x000000000049bbbc in si_compact (index=0xfe28b0, c=0x7f30bc000a50, plan=0x7f30bbffa5e0, vlsn=10903089, vlsn_lru=0, vindex=0x0, vindex_used=0)
    at /home/kostja/work/tarantool/src/box/phia.c:11145
#10 0x000000000049ac74 in si_execute (i=0xfe28b0, c=0x7f30bc000a50, plan=0x7f30bbffa5e0, vlsn=10903089, vlsn_lru=0)
    at /home/kostja/work/tarantool/src/box/phia.c:10846
#11 0x00000000004a6004 in sc_execute (t=0x7f30bbffa5e0, w=0x7f30bc0009a0, vlsn=10903089) at /home/kostja/work/tarantool/src/box/phia.c:14326
#12 0x00000000004a70a7 in sc_step (s=0xf15d88, w=0x7f30bc0009a0, vlsn=10903089) at /home/kostja/work/tarantool/src/box/phia.c:14665
#13 0x00000000004a51f0 in sc_ctl_call (s=0xf15d88, vlsn=10903089) at /home/kostja/work/tarantool/src/box/phia.c:14123
#14 0x00000000004b2353 in phia_service (env=0xf15520) at /home/kostja/work/tarantool/src/box/phia.c:18033
#15 0x0000000000479d4d in phia_worker (arg=0xf15520) at /home/kostja/work/tarantool/src/box/phia_engine.cc:171
#16 0x00000000004fa270 in cord_thread_func (p=0x7f3101c1f550) at /home/kostja/work/tarantool/src/fiber.c:716
#17 0x00007f3103ac7182 in start_thread (arg=0x7f30bbfff700) at pthread_create.c:312
#18 0x00007f3102dc547d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
```

**Comment by kostja** [comment]
Roman, I believe you fixed this, true?

**Comment by rtsisyk** [comment]
I can't reproduce this bug on the current code base.
Test case is too large. Can I reduce the number of inserts from 100000000 to 1000000?

**Comment by rtsisyk** [comment]
Fixed long time ago. Covered by vinyl/stress.test.lua
