### ISSUE TITLE
phia memory corruption on parallel phia_get() +  phia_replace()

### ISSUE THREAD

**Issue by rtsisyk** [tarantool/tarantool#1505]
```
while ./src/tarantool ./parallel.test.lua; do sleep 1; done
```

```
==5546== Thread 4 coeio:
==5546== Invalid read of size 8
==5546==    at 0x6F0BEB: load_u64 (bit.h:101)
==5546==    by 0x487C45: sf_cmpu64 (phia.c:3085)
==5546==    by 0x487D96: sf_schemecompare (phia.c:3116)
==5546==    by 0x487161: sf_compare (phia.c:2804)
==5546==    by 0x49037F: sx_match (phia.c:6081)
==5546==    by 0x490A6F: sx_get (phia.c:6174)
==5546==    by 0x4AA82F: phia_index_read (phia.c:13822)
==5546==    by 0x4ABFE4: phia_get (phia.c:14264)
==5546==    by 0x47C21B: phia_get_cb(coio_task*) (phia_engine.cc:254)
==5546==    by 0x4CB9AD: coio_on_exec (coeio.c:157)
==5546==    by 0x50C682: eio_execute (eio.c:2015)
==5546==    by 0x5091AB: etp_proc (etp.c:373)
==5546==  Address 0xf9fd6ef is 15 bytes inside a block of size 31 free'd
==5546==    at 0x4C2ED4A: free (vg_replace_malloc.c:530)
==5546==    by 0x485B08: ss_stdafree (phia.c:2088)
==5546==    by 0x481DDE: ss_free (phia.c:402)
==5546==    by 0x48B2FA: phia_tuple_unref (phia.c:4102)
==5546==    by 0x48E59E: sx_vfree (phia.c:5514)
==5546==    by 0x4908A7: sx_set (phia.c:6149)
==5546==    by 0x4ABD62: phia_tx_write (phia.c:14207)
==5546==    by 0x4ABDD6: phia_replace (phia.c:14218)
==5546==    by 0x47E3B3: PhiaSpace::executeReplace(txn*, space*, request*) (phia_space.cc:145)
==5546==    by 0x448C01: process_rw(request*, tuple**) (box.cc:114)
==5546==    by 0x44A2E8: box_process1(request*, tuple**) (box.cc:584)
==5546==    by 0x44A4BA: box_insert (box.cc:624)
==5546==  Block was alloc'd at
==5546==    at 0x4C2DB9D: malloc (vg_replace_malloc.c:299)
==5546==    by 0x485AA1: ss_stdamalloc (phia.c:2077)
==5546==    by 0x481D7F: ss_malloc (phia.c:392)
==5546==    by 0x48AB6E: phia_tuple_build (phia.c:4038)
==5546==    by 0x4AB5C7: phia_document_build (phia.c:14086)
==5546==    by 0x4ABF87: phia_get (phia.c:14258)
==5546==    by 0x47FC7E: PhiaIndex::findByKey(char const*, unsigned int) const (phia_index.cc:159)
==5546==    by 0x47E22D: PhiaSpace::executeReplace(txn*, space*, request*) (phia_space.cc:128)
==5546==    by 0x448C01: process_rw(request*, tuple**) (box.cc:114)
==5546==    by 0x44A2E8: box_process1(request*, tuple**) (box.cc:584)
==5546==    by 0x44A4BA: box_insert (box.cc:624)
==5546==    by 0x4624BD: lbox_insert (index.c:54)

```

**Comment by rtsisyk** [comment]
one more problem:
```
#0  0x000000000049faac in si_cachepool_pop (p=0x19f4790) at /data/work/tarantool/1.7/src/box/phia.c:8717
#1  0x000000000049ed25 in phia_index_read (db=0x1a456b0, key=0x1a41410, order=PHIA_EQ, result=0x7f1bcb7fa588, x=0x1a412f8, x_search=1, cache=0x0, 
    cache_only=false, statget=0x7f1bcb7fa578) at /data/work/tarantool/1.7/src/box/phia.c:13481
#2  0x00000000004a5183 in phia_get (t=0x1a41240, key=0x1a60560, result=0x7f1c110504b8, cache_only=false)
    at /data/work/tarantool/1.7/src/box/phia.c:13904
#3  0x0000000000495f5e in phia_get_cb (ptr=0x7f1c110503b0) at /data/work/tarantool/1.7/src/box/phia_engine.cc:254
#4  0x00000000004f9a20 in coio_on_exec (req=0x7f1c110503b0) at /data/work/tarantool/1.7/src/coeio.c:157
#5  0x000000000054e6e1 in eio_execute (self=0x7f1bcb7fa748, req=0x7f1c110503b0) at /data/work/tarantool/1.7/third_party/libeio/eio.c:2015
#6  0x000000000054d4fd in etp_proc (thr_arg=0x9d2fb0 <eio_pool>) at /data/work/tarantool/1.7/third_party/libeio/etp.c:373
#7  0x00007f1c1256f454 in start_thread (arg=0x7f1bcb7ff700) at pthread_create.c:334
#8  0x00007f1c11a18eed in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
```

**Comment by rtsisyk** [comment]
one more problem:
```
#0  0x000000000049faac in si_cachepool_pop (p=0x19f4790) at /data/work/tarantool/1.7/src/box/phia.c:8717
#1  0x000000000049ed25 in phia_index_read (db=0x1a456b0, key=0x1a41410, order=PHIA_EQ, result=0x7f1bcb7fa588, x=0x1a412f8, x_search=1, cache=0x0, 
    cache_only=false, statget=0x7f1bcb7fa578) at /data/work/tarantool/1.7/src/box/phia.c:13481
#2  0x00000000004a5183 in phia_get (t=0x1a41240, key=0x1a60560, result=0x7f1c110504b8, cache_only=false)
    at /data/work/tarantool/1.7/src/box/phia.c:13904
#3  0x0000000000495f5e in phia_get_cb (ptr=0x7f1c110503b0) at /data/work/tarantool/1.7/src/box/phia_engine.cc:254
#4  0x00000000004f9a20 in coio_on_exec (req=0x7f1c110503b0) at /data/work/tarantool/1.7/src/coeio.c:157
#5  0x000000000054e6e1 in eio_execute (self=0x7f1bcb7fa748, req=0x7f1c110503b0) at /data/work/tarantool/1.7/third_party/libeio/eio.c:2015
#6  0x000000000054d4fd in etp_proc (thr_arg=0x9d2fb0 <eio_pool>) at /data/work/tarantool/1.7/third_party/libeio/etp.c:373
#7  0x00007f1c1256f454 in start_thread (arg=0x7f1bcb7ff700) at pthread_create.c:334
#8  0x00007f1c11a18eed in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
```
