### ISSUE TITLE
vinyl: index decompression error

### ISSUE THREAD

**Issue by GeorgyKirichenko** [tarantool/tarantool#1527]
Under load phia raises: ER_PHIA: index file './514:0/00000000000000006922.index' decompression error

index with zstd compression

**Comment by GeorgyKirichenko** [comment]
Same error i have with lz4 compression

**Comment by rtsisyk** [comment]
```
#0  0x00000000006a4d8f in LZ4F_isError (code=4) at /data/work/tarantool/1.7/third_party/lz4/lib/lz4frame.c:162
#1  0x000000000048f84c in vy_filter_lz4_next (f=0x7f95d6ff9fd0, dest=0x7f95d6ffa140, buf=0x7f95d023d9b8 "\004\"M\030@@\300\226\002", size=1213)
    at /data/work/tarantool/1.7/src/box/vinyl.c:1055
#2  0x000000000048f1fa in vy_filter_next (c=0x7f95d6ff9fd0, dest=0x7f95d6ffa140, buf=0x7f95d023d9b8 "\004\"M\030@@\300\226\002", size=1213)
    at /data/work/tarantool/1.7/src/box/vinyl.c:838
#3  0x00000000004a3e81 in vy_run_load_page (run=0x7f959c007a70, pos=92, file=0x1c16a15, compression=0xa5abc0 <vy_filterif_lz4>)
    at /data/work/tarantool/1.7/src/box/vinyl.c:3797
#4  0x00000000004b93ab in vy_run_iterator_load_page (itr=0x7f95d06ca251, page=92) at /data/work/tarantool/1.7/src/box/vinyl.c:8853
#5  0x00000000004b95dc in vy_iterator_pos_mid_next (itr=0x7f95d06ca251, mid=..., end=..., result=0x7f95d6ffa290)
    at /data/work/tarantool/1.7/src/box/vinyl.c:8929
#6  0x00000000004b9827 in vy_run_iterator_search (itr=0x7f95d06ca251, key=0x7f95943ed14f "\t", vlsn=18446744073709551615, pos=0x7f95d06ca289, 
    equal_key=0x7f95d6ffa2df) at /data/work/tarantool/1.7/src/box/vinyl.c:9005
#7  0x00000000004b9e1e in vy_run_iterator_start (itr=0x7f95d06ca251) at /data/work/tarantool/1.7/src/box/vinyl.c:9184
#8  0x00000000004ba097 in vy_run_iterator_get (itr=0x7f95d06ca251, result=0x7f95d6ffa370) at /data/work/tarantool/1.7/src/box/vinyl.c:9275
#9  0x00000000004ba86a in vy_tmp_iterator_get (virt_iterator=0x7f95d06ca249) at /data/work/tarantool/1.7/src/box/vinyl.c:9484
#10 0x0000000000491591 in sv_mergeiter_next (im=0x7f95d6ffa490) at /data/work/tarantool/1.7/src/box/vinyl.c:1824
#11 0x00000000004916df in sv_mergeiter_open (im=0x7f95d6ffa490, m=0x7f95d6ffa6f0, o=VINYL_LT) at /data/work/tarantool/1.7/src/box/vinyl.c:1861
#12 0x00000000004aeadd in si_range (q=0x7f95d6ffa6d0) at /data/work/tarantool/1.7/src/box/vinyl.c:5994
#13 0x00000000004b59ca in vy_index_read (index=0x1b1aea0, key=0x7f95943ed140, order=VINYL_LT, result=0x7f95d70a88b8, upsert=0x0, 
    tx=0x7f95d7170200, cache_only=false) at /data/work/tarantool/1.7/src/box/vinyl.c:7667
#14 0x00000000004b83ef in vy_cursor_next_cb (ptr=0x7f95d70a87b0) at /data/work/tarantool/1.7/src/box/vinyl.c:8484
#15 0x00000000004d9613 in coio_on_exec (req=0x7f95d70a87b0) at /data/work/tarantool/1.7/src/coeio.c:163
#16 0x000000000051a849 in eio_execute (self=0x7f95d6ffa880, req=0x7f95d70a87b0) at /data/work/tarantool/1.7/third_party/libeio/eio.c:2015
#17 0x0000000000517372 in etp_proc (thr_arg=0xa81900 <eio_pool>) at /data/work/tarantool/1.7/third_party/libeio/etp.c:373
#18 0x00007f95d8887464 in start_thread (arg=0x7f95d6fff700) at pthread_create.c:333
#19 0x00007f95d7afd30d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
```

coredump, binary, sources, data directory:
https://cloud.mail.ru/public/MpVH/2w4Cviv8u

**Comment by rtsisyk** [comment]
ztsd:
```
#0  0x00007ffff5c1e1c8 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
#1  0x00007ffff5c1f64a in __GI_abort () at abort.c:89
#2  0x00007ffff5c17107 in __assert_fail_base (fmt=<optimized out>, assertion=assertion@entry=0x71b0b0 "page < itr->run->index.header.count", 
    file=file@entry=0x718cb8 "/data/work/tarantool/1.7/src/box/vinyl.c", line=line@entry=8849, 
    function=function@entry=0x71c610 <__PRETTY_FUNCTION__.17218> "vy_run_iterator_load_page") at assert.c:92
#3  0x00007ffff5c171b2 in __GI___assert_fail (assertion=0x71b0b0 "page < itr->run->index.header.count", 
    file=0x718cb8 "/data/work/tarantool/1.7/src/box/vinyl.c", line=8849, 
    function=0x71c610 <__PRETTY_FUNCTION__.17218> "vy_run_iterator_load_page") at assert.c:101
#4  0x00000000004b9357 in vy_run_iterator_load_page (itr=0x7ffff060f5b1, page=296) at /data/work/tarantool/1.7/src/box/vinyl.c:8849
#5  0x00000000004ba129 in vy_run_iterator_get (itr=0x7ffff060f5b1, result=0x7ffff53fa370) at /data/work/tarantool/1.7/src/box/vinyl.c:9290
#6  0x00000000004ba86a in vy_tmp_iterator_get (virt_iterator=0x7ffff060f5a9) at /data/work/tarantool/1.7/src/box/vinyl.c:9484
#7  0x0000000000491591 in sv_mergeiter_next (im=0x7ffff53fa490) at /data/work/tarantool/1.7/src/box/vinyl.c:1824
#8  0x0000000000491c90 in sv_readiter_forward (im=0x7ffff53fa440) at /data/work/tarantool/1.7/src/box/vinyl.c:1997
#9  0x00000000004aec6c in si_range (q=0x7ffff53fa6d0) at /data/work/tarantool/1.7/src/box/vinyl.c:6025
#10 0x00000000004b59ca in vy_index_read (index=0xaf0530, key=0x7ffff5920090, order=VINYL_GE, result=0x7ffff5480688, upsert=0x0, 
    tx=0x7fff9e539a20, cache_only=false) at /data/work/tarantool/1.7/src/box/vinyl.c:7667
#11 0x00000000004b836f in vy_get_cb (ptr=0x7ffff5480580) at /data/work/tarantool/1.7/src/box/vinyl.c:8475
#12 0x00000000004d9613 in coio_on_exec (req=0x7ffff5480580) at /data/work/tarantool/1.7/src/coeio.c:163
#13 0x000000000051a849 in eio_execute (self=0x7ffff53fa880, req=0x7ffff5480580) at /data/work/tarantool/1.7/third_party/libeio/eio.c:2015
#14 0x0000000000517372 in etp_proc (thr_arg=0xa81900 <eio_pool>) at /data/work/tarantool/1.7/third_party/libeio/etp.c:373
#15 0x00007ffff6a5c464 in start_thread (arg=0x7ffff53ff700) at pthread_create.c:333
#16 0x00007ffff5cd230d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
```

coredump, binary, sources, data directory:
https://cloud.mail.ru/public/MpVH/2w4Cviv8u

**Comment by rtsisyk** [comment]
Please try to update ztsd to the latest version: https://github.com/facebook/zstd

**Comment by kostja** [comment]
Update done, compression is now part of xlog infrastructure and has been removed from vinyl.
