### ISSUE TITLE
lj segfault with test script

### ISSUE THREAD

**Issue by GeorgyKirichenko** [tarantool/tarantool#1528]
#0  0x42a5d5 in sig_fatal_cb(int)+214
#1  0x7f9f3c499df0 in ?
#2  0x546744 in rehashtab+274
#3  0x546c23 in lj_tab_newkey+206
#4  0x5473f7 in lj_tab_set+461
#5  0x56fe46 in lj_cdata_setfin+561
#6  0x4ede51 in luaL_setcdatagc+550
#7  0x46090c in lbox_pushtuple+155
#8  0x463d07 in lbox_port_to_table(lua_State*, port*)+100
#9  0x463edd in lbox_select(lua_State*)+423
#10 0x581ebb in lj_BC_FUNCC+52
Aborted

[ptest.test.lua.txt](https://github.com/tarantool/tarantool/files/302479/ptest.test.lua.txt)

**Comment by GeorgyKirichenko** [comment]
Luajit update fix this
