### ISSUE TITLE
phia: segfault in lj (possibly caused by compressed reads fail)

### ISSUE THREAD

**Issue by GeorgyKirichenko** [tarantool/tarantool#1531]
#0  0x42a5d5 in sig_fatal_cb(int)+214
#1  0x7fc45bf35df0 in ?
#2  0x546c1e in rehashtab+274
#3  0x5470fd in lj_tab_newkey+206
#4  0x5478d1 in lj_tab_set+461
#5  0x570320 in lj_cdata_setfin+561
#6  0x4ee32b in luaL_setcdatagc+550
#7  0x46090c in lbox_pushtuple+155
#8  0x463d07 in lbox_port_to_table(lua_State*, port*)+100
#9  0x463edd in lbox_select(lua_State*)+423
#10 0x58238b in lj_BC_FUNCC+52
Aborted (core dumped)

I mean, if phia can't read compressed data it does something wrong with result return

**Comment by GeorgyKirichenko** [comment]
Doesn't reproduce after luajit update
