### ISSUE TITLE
phia: occasional crashes after dropping index

### ISSUE THREAD

**Issue by rtsisyk** [tarantool/tarantool#1558]
### Case 1

si_planner incorrectly uses `phia_index` reference counter.

Run the following tests for 10-20 minutes:

```
while ./test-run.py engine/ddl engine/insert --conf phia; do sleep 0.1; rm -rf var; done
```

### Case 2

1. Create phia space
2. Start a fiber which makes selects in background
3. Drop space

coeio thread may use dead `struct phia_index` in some cases.  This race is very hard to reproduce, but please just take a look at code.

### Case 3

phia_iterator_next() may use dead `struct phia_index`  if space was dropped.

**Comment by rtsisyk** [comment]
Is not critical for 1.7.0 (alpha), moving to 1.7.1 (beta).

**Comment by rtsisyk** [comment]
```
#0  __lll_lock_wait () at ../sysdeps/unix/sysv/linux/x86_64/lowlevellock.S:135
#1  0x00007f5e13e9cb05 in __GI___pthread_mutex_lock (mutex=mutex@entry=0x1a66380) at ../nptl/pthread_mutex_lock.c:81
#2  0x00000000004febd4 in sc_ctl_shutdown (i=0x1aa1100, s=0x1a66380) at /data/work/tarantool/1.7/src/box/vinyl.c:8450
#3  vinyl_index_unref (index=index@entry=0x1aa1100) at /data/work/tarantool/1.7/src/box/vinyl.c:9486
#4  0x00000000004ff337 in vinyl_index_drop (index=0x1aa1100) at /data/work/tarantool/1.7/src/box/vinyl.c:9522
#5  0x00000000004d584d in VinylEngine::dropIndex (this=<optimized out>, index=0x1a8b350) at /data/work/tarantool/1.7/src/box/vinyl_engine.cc:262
#6  0x0000000000515a59 in DropIndex::commit (this=<optimized out>, alter=0x7f5e128081d0) at /data/work/tarantool/1.7/src/box/alter.cc:921
#7  0x0000000000515dd5 in alter_space_commit (trigger=<optimized out>) at /data/work/tarantool/1.7/src/box/alter.cc:637
#8  0x0000000000483d49 in trigger_run (event=0x7f5e12808098, list=0x7f5e12808110) at /data/work/tarantool/1.7/src/trigger.h:77
#9  txn_commit (txn=txn@entry=0x7f5e12808098) at /data/work/tarantool/1.7/src/box/txn.cc:250
#10 0x000000000048428e in txn_commit_stmt (txn=txn@entry=0x7f5e12808098, request=request@entry=0x7f5e12808040)
    at /data/work/tarantool/1.7/src/box/txn.cc:175
#11 0x00000000004862c8 in process_rw (request=request@entry=0x7f5e12808040, result=result@entry=0x7f5e1281fe88)
    at /data/work/tarantool/1.7/src/box/box.cc:168
#12 0x00000000004884ad in box_process1 (request=request@entry=0x7f5e12808040, result=result@entry=0x7f5e1281fe88)
    at /data/work/tarantool/1.7/src/box/box.cc:594
```

**Comment by rtsisyk** [comment]
Related to #1592
