### ISSUE TITLE
SIGPIPE on master if replica closes socket during SUBSCRIBE

### ISSUE THREAD

**Issue by rtsisyk** [tarantool/tarantool#1627]
```
Program received signal SIGPIPE, Broken pipe.
0x00007ffff6a66f1d in write () at ../sysdeps/unix/syscall-template.S:84
84      ../sysdeps/unix/syscall-template.S: No such file or directory.

(gdb) bt
#0  0x00007ffff6a66f1d in write () at ../sysdeps/unix/syscall-template.S:84
#1  0x0000000000479d03 in iproto_write_error (fd=30, e=0x7fffb4000f18) at /data/work/tarantool/1.7/src/box/iproto_port.cc:138
#2  0x0000000000478a29 in tx_process_join_subscribe (m=0x7fffe3830170) at /data/work/tarantool/1.7/src/box/iproto.cc:874
#3  0x000000000050b6b2 in cmsg_deliver (msg=0x7fffe3830170) at /data/work/tarantool/1.7/src/cbus.c:258
#4  0x000000000050aa07 in fiber_pool_f (ap=0x7ffff5400650) at /data/work/tarantool/1.7/src/cbus.c:76
#5  0x0000000000438606 in fiber_cxx_invoke(fiber_func, typedef __va_list_tag __va_list_tag *) (f=0x50a88a <fiber_pool_f>, ap=0x7ffff5400650)
    at /data/work/tarantool/1.7/src/fiber.h:593
#6  0x00000000005084c3 in fiber_loop (data=0x0) at /data/work/tarantool/1.7/src/fiber.c:483
#7  0x0000000000705333 in coro_init () at /data/work/tarantool/1.7/third_party/coro/coro.c:11

(gdb) up
#2  0x0000000000478a29 in tx_process_join_subscribe (m=0x7fffe3830170) at /data/work/tarantool/1.7/src/box/iproto.cc:874
874                     iproto_write_error(con->input.fd, e);
(gdb) p e->type->name
$1 = 0x745a18 "SocketError"
(gdb) p e->errmsg
$2 = "writev(3), called on fd 30, aka [::1]:3753", '\000' <repeats 469 times>
```

**Comment by rtsisyk** [comment]
Fixed in 1.6.8-744-g18481f3. A test is not added because it is very hard to to make.
