### ISSUE TITLE
vinyl: exit() stucks on cord_join() after engine_long/ tests

### ISSUE THREAD

**Issue by rtsisyk** [tarantool/tarantool#1631]
```
cmake . -DCMAKE_BUILD_TYPE=RelWithDebInfo -DENABLE_GCOV=ON
make -j8
# Enable --long tests for coverage
cd test && /usr/bin/python test-run.py --long
```

```
================================================================================
TEST                                            PARAMS          RESULT
---------------------------------------------------------------------------
engine_long/delete_insert.test.lua              memtx           [ pass ]
engine_long/delete_insert.test.lua              vinyl           [ pass ]
engine_long/delete_replace_update.test.lua      memtx           [ pass ]
engine_long/delete_replace_update.test.lua      vinyl           [ pass ]
---------------------------------------------------------------------------
Stopping the server ...
[STUCK]
```

```
(gdb) bt
#0  0x00007ff8aa22c6dd in pthread_join (threadid=140705712305920, thread_return=thread_return@entry=0x7ffe72b420b8) at pthread_join.c:90
#1  0x00000000005911df in cord_join (cord=0x1b8a7e0) at /data/work/tarantool/1.7/src/fiber.c:869
#2  0x00000000004d4d59 in vinyl_workers_stop () at /data/work/tarantool/1.7/src/box/vinyl_engine.cc:112
#3  VinylEngine::~VinylEngine (this=0x1b59c70, __in_chrg=<optimized out>) at /data/work/tarantool/1.7/src/box/vinyl_engine.cc:126
#4  0x00000000004d4da9 in VinylEngine::~VinylEngine (this=0x1b59c70, __in_chrg=<optimized out>)
    at /data/work/tarantool/1.7/src/box/vinyl_engine.cc:129
#5  0x000000000046fd43 in engine_shutdown () at /data/work/tarantool/1.7/src/box/engine.cc:242
#6  0x000000000048cfc5 in box_free () at /data/work/tarantool/1.7/src/box/box.cc:1204
#7  0x0000000000440b02 in tarantool_free () at /data/work/tarantool/1.7/src/main.cc:472
#8  0x00007ff8a93f4de8 in __run_exit_handlers (status=0, listp=0x7ff8a975d5f8 <__exit_funcs>, run_list_atexit=run_list_atexit@entry=true)
    at exit.c:82
```

**Comment by rtsisyk** [comment]
Related to #1592
