### ISSUE TITLE
Segmentation fault on 1.7 vinyl

### ISSUE THREAD

**Issue by vmakhaev** [tarantool/tarantool#1669]
```
tarantool --version
Tarantool 1.7.1-148-g49a8f21
Target: Darwin-x86_64-Release
Build options: cmake . -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/tarantool/HEAD-49a8f21 -DENABLE_BACKTRACE=OFF
Compiler: /usr/local/Library/Homebrew/shims/super/clang /usr/local/Library/Homebrew/shims/super/clang++
C_FLAGS: -fexceptions -funwind-tables -fno-common -fopenmp -msse2 -std=c11 -Wall -Wextra -Wno-strict-aliasing -Wno-unused-value
CXX_FLAGS: -fexceptions -funwind-tables -fno-common -fopenmp -msse2 -std=c++11 -Wall -Wextra -Wno-strict-aliasing -Wno-unused-value
```

Init db with lua script:
```lua
box.cfg{listen = 3301}
s = box.schema.space.create('tester', {engine='vinyl'})
s:create_index('primary', {
  type = 'tree',
  parts = {1, 'unsigned'}
})

box.schema.user.grant('guest', 'read,write,execute', 'universe')
```

then run this go app:
```go
package main

import (
	"log"
	"math/rand"
	"time"

	"github.com/tarantool/go-tarantool"
)

var opsCount int64
var opsTime int64

func showOpsPerSec() {
	time.Sleep(time.Second)
	var averageOpsTime int64
	if opsCount > 0 {
		averageOpsTime = opsTime / opsCount / 1000
	}
	log.Println("ops/s:", opsCount, averageOpsTime)
	opsCount = 0
	opsTime = 0
	showOpsPerSec()
}

func insert(n int, k int) {
	server := "127.0.0.1:3301"
	opts := tarantool.Opts{
		Timeout:       500 * time.Millisecond,
		Reconnect:     1 * time.Second,
		MaxReconnects: 3,
		// User:          "guest",
		// Pass:          "test",
	}
	client, err := tarantool.Connect(server, opts)
	if err != nil {
		log.Fatal("connection ", err)
	}
	defer client.Close()

	for i := k; i < k+(1*1000000); i++ {
		date := time.Now().UnixNano()
		number := rand.Intn(1)
		success := false
		if number == 1 {
			success = true
		}
		_, err := client.Insert("tester", []interface{}{uint(i), date, n, success, date, date, date})
		if err != nil {
			log.Fatal("insert ", err)
		}
		opsCount++
		opTime := time.Now().UnixNano() - date
		opsTime = opsTime + opTime
	}
}

func main() {
	log.Println("Start")

	go showOpsPerSec()
	for i := 1; i < 100; i++ {
		go insert(i, i*1*1000000)
	}

	time.Sleep(time.Second * 10000)
}
```

it's end up with:
```
tarantool> Segmentation fault
Current time: 1470392109
Please file a bug at http://github.com/tarantool/tarantool/issues
[1]    27229 abort (core dumped)  tarantool
```

core dump: https://www.dropbox.com/s/iz6axkbim8qblxg/core.27229?dl=0

Let me know if you need anything else.

**Comment by rtsisyk** [comment]
```
#0  0x0000000000512c60 in mp_load_u8 (data=0x7fff91ffa320) at /data/work/tarantool/1.7/src/lib/msgpuck/msgpuck.h:232
#1  0x000000000051385b in mp_compare_uint (data_a=0xc09979 "", data_b=0x23e4c2e2 <error: Cannot access memory at address 0x23e4c2e2>)
    at /data/work/tarantool/1.7/src/lib/msgpuck/msgpuck.h:1386
#2  0x000000000044127e in tuple_compare_field (field_a=0xc09978 <incomplete sequence \316>, 
    field_b=0x23e4c2e2 <error: Cannot access memory at address 0x23e4c2e2>, type=FIELD_TYPE_UNSIGNED)
    at /data/work/tarantool/1.7/src/box/tuple.cc:565
#3  0x00000000004b7cb4 in vy_tuple_compare (tuple_data_a=0xc0996f "\t", tuple_data_b=0xc19fbf "\t", key_def=0xac7560)
    at /data/work/tarantool/1.7/src/box/vinyl.c:8799
#4  0x000000000049df60 in txv_tree_key_cmp (rbtree=0xac5e28, a=0x7fff91ffa490, b=0xc3eed0) at /data/work/tarantool/1.7/src/box/vinyl.c:2990
#5  0x000000000049c57a in txv_tree_search (rbtree=0xac5e28, key=0x7fff91ffa490) at /data/work/tarantool/1.7/src/box/vinyl.c:2954
#6  0x000000000049de71 in txv_tree_search_key (rbtree=0xac5e28, data=0xc0996f "\t", size=14, tsn=4552)
    at /data/work/tarantool/1.7/src/box/vinyl.c:2964
#7  0x00000000004a0ad1 in tx_get (tx=0xc3e3c0, index=0xac5c50, key=0xc09960, result=0x7fff91ffa6d8)
    at /data/work/tarantool/1.7/src/box/vinyl.c:3371
#8  0x00000000004b5b92 in vinyl_index_read (index=0xac5c50, key=0xc09960, order=VINYL_EQ, result=0x7ffff549bbf8, tx=0xc3e3c0, cache=0x0, 
    cache_only=false, statget=0x7fff91ffa780) at /data/work/tarantool/1.7/src/box/vinyl.c:8291
#9  0x00000000004b8a25 in vy_get (tx=0xc3e3c0, index=0xac5c50, key=0xc09960, result=0x7ffff549bbf8, cache_only=false)
    at /data/work/tarantool/1.7/src/box/vinyl.c:9094
#10 0x00000000004b8f8d in vy_get_cb (ptr=0x7ffff549baf0) at /data/work/tarantool/1.7/src/box/vinyl.c:9233
#11 0x00000000004d8d5d in coio_on_exec (req=0x7ffff549baf0) at /data/work/tarantool/1.7/src/coeio.c:163
#12 0x0000000000519f89 in eio_execute (self=0x7fff91ffa880, req=0x7ffff549baf0) at /data/work/tarantool/1.7/third_party/libeio/eio.c:2015
#13 0x0000000000516ab2 in etp_proc (thr_arg=0xa812c0 <eio_pool>) at /data/work/tarantool/1.7/third_party/libeio/etp.c:373
#14 0x00007ffff6a5c464 in start_thread (arg=0x7fff91fff700) at pthread_create.c:333
#15 0x00007ffff5cd230d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
```

**Comment by rtsisyk** [comment]
Caused by #1603

**Comment by kostja** [comment]
Please re-open if you have any other trouble with this test case.
