### ISSUE TITLE
vinyl: crash in vy_rollback on ER_WAL_IO

### ISSUE THREAD

**Issue by rtsisyk** [tarantool/tarantool#1681]
```
2016-08-10 15:12:04.66

3 [9075] wal/102/wal fio.c:132 !> writev, [/data/work/tarantool/cbench/00000000000000000004.xlog]: No space left on device
2016-08-10 15:12:04.663 [9075] main/103/cbench txn.cc:224 E> ER_WAL_IO: Failed to write to disk

Thread 1 "tarantool" received signal SIGSEGV, Segmentation fault.
0x00000000004a0baa in tx_tree_remove (rbtree=0xaae9a0, node=0x182a150) at /data/work/tarantool/1.7/src/box/vinyl.c:3017
3017    rb_gen_ext_key(, tx_tree_, tx_tree_t, struct vy_tx, tree_node,
(gdb) bt
#0  0x00000000004a0baa in tx_tree_remove (rbtree=0xaae9a0, node=0x182a150) at /data/work/tarantool/1.7/src/box/vinyl.c:3017
#1  0x00000000004a22fc in tx_manager_end (m=0xaae9a0, tx=0x182a150) at /data/work/tarantool/1.7/src/box/vinyl.c:3125
#2  0x00000000004a252d in tx_rollback (tx=0x182a150) at /data/work/tarantool/1.7/src/box/vinyl.c:3163
#3  0x00000000004ba84f in vy_rollback (e=0xaae330, tx=0x182a150) at /data/work/tarantool/1.7/src/box/vinyl.c:8889
#4  0x000000000048929c in VinylEngine::rollback (this=0xaae2f0, txn=0x7ffff5431090) at /data/work/tarantool/1.7/src/box/vinyl_engine.cc:283
#5  0x0000000000454488 in txn_rollback () at /data/work/tarantool/1.7/src/box/txn.cc:297
#6  0x000000000045435c in txn_rollback_stmt () at /data/work/tarantool/1.7/src/box/txn.cc:274
#7  0x0000000000456164 in process_rw (request=0x7ffff5431038, result=0x0) at /data/work/tarantool/1.7/src/box/box.cc:175
#8  0x00000000004575b9 in box_process1 (request=0x7ffff5431038, result=0x0) at /data/work/tarantool/1.7/src/box/box.cc:594
#9  0x0000000000457a8c in box_upsert (space_id=512, index_id=0, tuple=0x7ffff544fe10 "\222\316G\360", <incomplete sequence \352>, 
    tuple_end=0x7ffff544fe17 'P' <repeats 121 times>, "\221\223\241+\001\001", 'P' <repeats 73 times>..., 
    ops=0x7ffff544fe90 "\221\223\241+\001\001", 'P' <repeats 122 times>, "7\274\244Z\266\263\312@G4\257Z\266\263\312@\226\376D\365\377\177", 
    ops_end=0x7ffff544fe96 'P' <repeats 122 times>, "7\274\244Z\266\263\312@G4\257Z\266\263\312@\226\376D\365\377\177", index_base=0, result=0x0)
    at /data/work/tarantool/1.7/src/box/box.cc:704
#10 0x00007fffed1f65f5 in wl_upserts_uint_f (ap=0x7ffff5400400) at /data/work/tarantool/cbench/cbench/bench.c:41
#11 0x0000000000437ea6 in fiber_cxx_invoke(fiber_func, typedef __va_list_tag __va_list_tag *) (f=0x7fffed1f62e0 <wl_upserts_uint_f>, 
    ap=0x7ffff5400400) at /data/work/tarantool/1.7/src/fiber.h:593
#12 0x0000000000504521 in fiber_loop (data=0x0) at /data/work/tarantool/1.7/src/fiber.c:483
#13 0x0000000000701349 in coro_init () at /data/work/tarantool/1.7/third_party/coro/coro.c:110
```

coredump + binary: https://cloud.mail.ru/public/K1fW/vR2RkAJWv

**Comment by rtsisyk** [comment]
Any news?
