### ISSUE TITLE
Tarantool SIGABRT inside lua

### ISSUE THREAD

**Issue by 0xBF** [tarantool/tarantool#1682]
OS: Debian wheezy amd64
Tarantool: 1.6.8.745.gb5173ac-1

Backtrace:

```
#0  0x00007f61e3799125 in raise () from /lib/x86_64-linux-gnu/libc.so.6
(gdb) bt
#0  0x00007f61e3799125 in raise () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007f61e379c3a0 in abort () from /lib/x86_64-linux-gnu/libc.so.6
#2  0x000000000043968d in sig_fatal_cb (signo=<optimized out>) at /home/travis/build/tarantool/tarantool/build/root/deb-debian-wheezy/tarantool-1.6.8.745/src/main.cc:196
#3  <signal handler called>
#4  0x00000000004f4baf in lj_vm_growstack_f () at buildvm_x86.dasc:1180
#5  0x000000000046c197 in execute_lua_call (L=0x42a548b0) at /home/travis/build/tarantool/tarantool/build/root/deb-debian-wheezy/tarantool-1.6.8.745/src/box/lua/call.c:282
#6  0x00000000004f49a7 in lj_BC_FUNCC () at buildvm_x86.dasc:809
#7  0x00000000004e0f92 in lua_cpcall (L=L@entry=0x42a548b0, func=func@entry=0x46c090 <execute_lua_call>, ud=ud@entry=0x7f61e304fd60) at lj_api.c:1079
#8  0x00000000004b8503 in lbox_cpcall (L=L@entry=0x42a548b0, func=func@entry=0x46c090 <execute_lua_call>, ud=ud@entry=0x7f61e304fd60)
    at /home/travis/build/tarantool/tarantool/build/root/deb-debian-wheezy/tarantool-1.6.8.745/src/lua/utils.c:944
#9  0x000000000046c61e in box_process_lua (handler=0x46c090 <execute_lua_call>, out=0x7f61e0821500, request=<optimized out>)
    at /home/travis/build/tarantool/tarantool/build/root/deb-debian-wheezy/tarantool-1.6.8.745/src/box/lua/call.c:372
#10 box_lua_call (request=<optimized out>, out=0x7f61e0821500) at /home/travis/build/tarantool/tarantool/build/root/deb-debian-wheezy/tarantool-1.6.8.745/src/box/lua/call.c:395
#11 0x0000000000460239 in box_process_call (request=0x7f61e08410d8, out=0x7f61e0821500)
    at /home/travis/build/tarantool/tarantool/build/root/deb-debian-wheezy/tarantool-1.6.8.745/src/box/box.cc:837
#12 0x00000000004751a0 in tx_process_msg (m=0x7f61e0841070) at /home/travis/build/tarantool/tarantool/build/root/deb-debian-wheezy/tarantool-1.6.8.745/src/box/iproto.cc:715
#13 0x00000000004c4f08 in cmsg_deliver (msg=0x7f61e0841070) at /home/travis/build/tarantool/tarantool/build/root/deb-debian-wheezy/tarantool-1.6.8.745/src/cbus.h:443
#14 cpipe_fiber_pool_f (ap=<error reading variable: value has been optimized out>)
    at /home/travis/build/tarantool/tarantool/build/root/deb-debian-wheezy/tarantool-1.6.8.745/src/cbus.c:288
#15 0x000000000043914c in fiber_cxx_invoke(fiber_func, typedef __va_list_tag __va_list_tag *) (f=<optimized out>, ap=<optimized out>)
    at /home/travis/build/tarantool/tarantool/build/root/deb-debian-wheezy/tarantool-1.6.8.745/src/fiber.h:533
#16 0x00000000004c3220 in fiber_loop (data=<optimized out>) at /home/travis/build/tarantool/tarantool/build/root/deb-debian-wheezy/tarantool-1.6.8.745/src/fiber.c:472
#17 0x000000000060e0af in coro_init () at /home/travis/build/tarantool/tarantool/build/root/deb-debian-wheezy/tarantool-1.6.8.745/third_party/coro/coro.c:110

```

Core dumps uploaded to ftp.

**Comment by mejedi** [comment]
Confirmed that this issue was yet another manifestation of #1638.
