### ISSUE TITLE
tarantool does not start: Vinyl does not support altering not empty space

### ISSUE THREAD

**Issue by stepan-mitkin** [tarantool/tarantool#1723]
Tarantool version 1.7.1-231-g20729da
1. `box.begin()`
2. write to memtx-based spaces several times.
3. write to a vinyl-based space.
4. tarantool throws. catch the exception with pcall.
5. stop the tarantool instance with `Ctrl-C` from console.
6. start tarantool.
7. tarantool does not start. The error message is: Vinyl does not support altering not empty space

The database is lost forever.

This one is hard to reproduce. It takes some special pattern of reads and writes to happen.

Log:

```
2016-08-28 19:40:05.001 [20726] main/104/snapshot_daemon I> making snapshot...
2016-08-28 19:40:05.002 [20726] snapshot/101/main I> creating `/dewt/data/00000000000000205315.snap.inprogress'
2016-08-28 19:40:05.002 [20726] snapshot/101/main I> saving snapshot `/dewt/data/00000000000000205315.snap.inprogress'
2016-08-28 19:40:05.192 [20726] snapshot/101/main I> done
2016-08-28 19:40:58.218 [20726] main C> got signal 2 - Interrupt
2016-08-28 19:40:59.350 [21560] main/101/dbgcfg.lua C> version 1.7.1-231-g20729da
2016-08-28 19:40:59.350 [21560] main/101/dbgcfg.lua C> log level 5
2016-08-28 19:40:59.350 [21560] main/101/dbgcfg.lua I> mapping 536870912 bytes for tuple arena...
2016-08-28 19:40:59.393 [21560] main/101/dbgcfg.lua I> recovery start
2016-08-28 19:40:59.393 [21560] main/101/dbgcfg.lua I> recovering from `/dewt/data/00000000000000205315.snap'
2016-08-28 19:40:59.397 [21560] main/101/dbgcfg.lua memtx_engine.cc:288 E> rollback: Vinyl does not support altering not empty space
2016-08-28 19:40:59.397 [21560] main/101/dbgcfg.lua vinyl_space.cc:594 E> ER_UNSUPPORTED: Vinyl does not support altering not empty space
2016-08-28 19:40:59.397 [21560] main/101/dbgcfg.lua F> can't initialize storage: Vinyl does not support altering not empty space
```

**Comment by kostja** [comment]
Hi, I tried the steps described in the ticket and did not get a failure:
```
% ./tarantool 
./tarantool: version 1.7.1-300-gcbfb7e8
type 'help' for interactive help
tarantool> box.cfg{}
2016-09-08 21:19:26.081 [12714] main/101/interactive C> version 1.7.1-300-gcbfb7e8
2016-09-08 21:19:26.081 [12714] main/101/interactive C> log level 5
2016-09-08 21:19:26.081 [12714] main/101/interactive I> mapping 1073741824 bytes for tuple arena...
2016-09-08 21:19:26.088 [12714] main/101/interactive I> recovery start
2016-09-08 21:19:26.089 [12714] main/101/interactive I> recovering from `./00000000000000000004.snap'
2016-09-08 21:19:26.104 [12714] main/101/interactive I> ready to accept requests
---
...

tarantool> box.schema.space.create('test')
---
- error: Space 'test' already exists
...

tarantool> box.space
---
- test:
    temporary: false
    engine: memtx
...

tarantool> box.schema.space.create('t2', {engine='vinyl'})
2016-09-08 21:19:46.529 [12714] wal/102/wal I> creating `./00000000000000000004.xlog.inprogress'
---
- index: []
  on_replace: 'function: 0x41913fd8'
  temporary: false
  id: 513
  engine: vinyl
  enabled: false
  name: t2
  field_count: 0
- created
...

tarantool> box.space.t2:create_index('pk')
---
- unique: true
  parts:
  - type: unsigned
    fieldno: 1
  id: 0
  space_id: 513
  name: pk
  type: TREE
...

tarantool> function f() box.begin(); box.space.test:insert{3} box.space.t2:insert{1} box.commit() end
---
...

tarantool> pcall(f)
---
- false
- A multi-statement transaction can not use multiple storage engines
...

tarantool> %                                                                    kostja@atlas ~/work/tarantool/src
 % ./tarantool
./tarantool: version 1.7.1-300-gcbfb7e8
type 'help' for interactive help
tarantool> box.cfg{}
2016-09-08 21:20:32.010 [12745] main/101/interactive C> version 1.7.1-300-gcbfb7e8
2016-09-08 21:20:32.010 [12745] main/101/interactive C> log level 5
2016-09-08 21:20:32.010 [12745] main/101/interactive I> mapping 1073741824 bytes for tuple arena...
2016-09-08 21:20:32.011 [12745] main/101/interactive I> recovery start
2016-09-08 21:20:32.011 [12745] main/101/interactive I> recovering from `./00000000000000000004.snap'
2016-09-08 21:20:32.016 [12745] main/101/interactive I> recover from `./00000000000000000004.xlog'
2016-09-08 21:20:32.019 [12745] main/101/interactive I> done `./00000000000000000004.xlog'
2016-09-08 21:20:32.019 [12745] main/103/hot_standby I> recover from `./00000000000000000004.xlog'
2016-09-08 21:20:32.020 [12745] main/101/interactive I> done `./00000000000000000004.xlog'
2016-09-08 21:20:32.021 [12745] main/101/interactive I> ready to accept requests
---
...

tarantool> box.space
---
- test:
    temporary: false
    engine: memtx
  t2:
    temporary: false
    engine: vinyl
...
```

**Comment by kostja** [comment]
What did I do wrong? Could you please retry the described steps on the latest version or send us a reproducible test case?

**Comment by kostja** [comment]
Crash uploaded to the support ftp, dew-bugdb.zip

**Comment by kostja** [comment]
We believe the problem is gone by now, could you please re-check?

**Comment by kostja** [comment]
* stepan-mitkin <notifications@github.com> [16/09/28 13:48]:

Hi,

We changed the binary layout of data in Vinyl.
I'm afraid you can't start with this layout at all, so you need to
start from scratch, or connect to old server with a replica
to get data converted to a new format.

We'll look into the core file to avoid a crash in the future (but
it will be replaced with abort on start).

> When I start tarantool with the crash db, I get this in the console:
> 
> $ tarantool dbgcfg.lua
> starting console...
> tarantool> Segmentation fault
> Current time: 1475047391
> Please file a bug at http://github.com/tarantool/tarantool/issues
> Attempting backtrace... Note: since the server has already crashed, 
> this may fail as well
> #0  0x40f351 in sig_fatal_cb(int)+129
> #1  0x7fe85e563330 in ?
> #2  0x468ee2 in vy_scheduler_f+738
> #3  0x40eecc in fiber_cxx_invoke(int (*)(__va_list_tag*), __va_list_tag*)+12
> #4  0x4c0300 in fiber_loop+48
> #5  0x5e56bf in coro_init+63
> #6  (nil) in ?
> Avbrutt (SIGABRT) (kjerne lagret i fil) == "core saved in file"
> 
> Note that I commented out line "require("init")" in dbgcfg.lua.
> 
> Uploaded the core file to ftp://build.tarantool.org
> core.tarantool.3266.anton.1475047391.zip
> 
> tarantool: version 1.7.1-489-ge5f67b9
> 
> uname -a
> Linux anton 4.4.0-38-generic #57~14.04.1-Ubuntu SMP Tue Sep 6 17:20:43 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
> 
> 
> -- 
> You are receiving this because you were assigned.
> Reply to this email directly or view it on GitHub:
> https://github.com/tarantool/tarantool/issues/1723#issuecomment-250092864

-- 
Konstantin Osipov, Moscow, Russia, +7 903 626 22 32
http://tarantool.org - www.twitter.com/kostja_osipov

**Comment by stepan-mitkin** [comment]
I started testing from an earlier snapshot file and the original error does not show up.
As before, I do several writes both in memtx and vinyl inside a transaction and get an exception:
"A multi-statement transaction can not use multiple storage engines"
So far so good.

Then I shut down tarantool with Ctrl+C. 
When I start tarantool again, it does not start. Here is the log:
2016-09-28 19:16:28.173 [5817] main/101/dbgcfg.lua C> version 1.7.1-489-ge5f67b9
2016-09-28 19:16:28.173 [5817] main/101/dbgcfg.lua C> log level 5
2016-09-28 19:16:28.173 [5817] main/101/dbgcfg.lua I> mapping 536870912 bytes for tuple arena...
2016-09-28 19:16:28.199 [5817] main/101/dbgcfg.lua I> recovery start
2016-09-28 19:16:28.199 [5817] main/101/dbgcfg.lua I> recovering from `/home/stipan/baddew/data/00000000000000205277.snap'
2016-09-28 19:16:28.235 [5817] main/101/dbgcfg.lua memtx_engine.cc:288 E> rollback: Vinyl does not support altering not empty space
2016-09-28 19:16:28.235 [5817] main/101/dbgcfg.lua vinyl_space.cc:594 E> ER_UNSUPPORTED: Vinyl does not support altering not empty space
2016-09-28 19:16:28.235 [5817] main/101/dbgcfg.lua F> can't initialize storage: Vinyl does not support altering not empty space

**Comment by rtsisyk** [comment]
Your problem is caused by #1899, which is already fixed.
