### ISSUE TITLE
vinyl: segfault in si_redistribute

### ISSUE THREAD

**Issue by rtsisyk** [tarantool/tarantool#1726]
```
Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffe77fe700 (LWP 29148)]
0x00000000004a8613 in si_redistribute (index=0xae0740, c=0x7fffec41fe80, node=0x7fffd40416a0, result=0x7fffec41fe80)
    at /data/work/tarantool/1.7/src/box/vinyl.c:3977
3977                            int rc = vy_tuple_compare((*v)->data,
(gdb) bt
#0  0x00000000004a8613 in si_redistribute (index=0xae0740, c=0x7fffec41fe80, node=0x7fffd40416a0, result=0x7fffec41fe80)
    at /data/work/tarantool/1.7/src/box/vinyl.c:3977
#1  0x00000000004a8f83 in si_merge (index=0xae0740, c=0x7fffec41fe80, range=0x7fffd40416a0, vlsn=2519427, 
    stream=0x7fffec41fda0, size_stream=84325888, n_stream=2406881) at /data/work/tarantool/1.7/src/box/vinyl.c:4180
#2  0x00000000004a82d5 in si_compact (index=0xae0740, c=0x7fffec41fe80, node=0x7fffd40416a0, vlsn=2519427, vindex=0x0, 
    vindex_used=0) at /data/work/tarantool/1.7/src/box/vinyl.c:3919
#3  0x00000000004ac0cc in vy_task_execute (task=0x7fffec808080, c=0x7fffec41fe80, vlsn=2519427)
    at /data/work/tarantool/1.7/src/box/vinyl.c:5199
```

https://github.com/rtsisyk/tarantool-vinyl-histogram

**Comment by rtsisyk** [comment]
test case:

```
#!./src/tarantool

os.execute("rm -rf *.snap* *.xlog* 51?/")

box.cfg {
    slab_alloc_arena = 0.1,
    wal_mode = "none",
    snap_dir = ".",
    work_dir = ".";
    rows_per_wal = 100000000;
    vinyl = {
        threads = 1;
    };
}

box.once("bootstrap", function()
    box.schema.space.create("vinyl", { engine = 'vinyl' })
    box.space.vinyl:create_index('primary', { parts = { 1, 'unsigned' } })
    --box.snapshot()
end)

local fiber = require('fiber')

local workers_n = 4

local ch = fiber.channel(workers_n)
local function worker()
    for i=1,1000000 do
        box.space.vinyl:replace({math.random(4294967295)})
        fiber.sleep(0)
    end
    print('done')
    ch:put(true)
end

for i=1,workers_n do
    fiber.create(worker)
end

for i=1,workers_n do
    ch:get()
end

os.exit(0)
```
