### ISSUE TITLE
vinyl: don't block TX read on disk I/O

### ISSUE THREAD

**Issue by rtsisyk** [tarantool/tarantool#1756]
Use coio_pread() instead of pread(). It was already fixed by reverted by mistake. See 5fe04531f25d5d3e689efe4e34c481c9a0d319d3 and 16ae0d5441ab1a991c61c75c0711feea323e71d3 (reversion).

**Comment by rtsisyk** [comment]
I replaced read()/pread() with coeio_read()/coeio_pread():

```
#0  0x00007ffff5bee1c8 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
#1  0x00007ffff5bef64a in __GI_abort () at abort.c:89
#2  0x00007ffff5be7107 in __assert_fail_base (fmt=<optimized out>, assertion=assertion@entry=0x6e38ce "id < v->block_count", 
    file=file@entry=0x6e3898 "/data/work/tarantool/1.7/src/lib/small/small/matras.h", line=line@entry=342, 
    function=function@entry=0x6e5fd0 <__PRETTY_FUNCTION__.12387> "matras_view_get_no_check") at assert.c:92
#3  0x00007ffff5be71b2 in __GI___assert_fail (assertion=0x6e38ce "id < v->block_count", 
    file=0x6e3898 "/data/work/tarantool/1.7/src/lib/small/small/matras.h", line=342, 
    function=0x6e5fd0 <__PRETTY_FUNCTION__.12387> "matras_view_get_no_check") at assert.c:101
#4  0x000000000044b864 in matras_view_get_no_check (m=0xabd710, v=0xabd710, id=11) at /data/work/tarantool/1.7/src/lib/small/small/matras.h:342
#5  0x000000000044b91b in matras_view_get (m=0xabd710, v=0x1083410, id=11) at /data/work/tarantool/1.7/src/lib/small/small/matras.h:360
#6  0x000000000044c120 in bps_tree_vy_mem_tree_restore_block_ver (tree=0xabd6d0, id=11, view=0x1083410)
    at /data/work/tarantool/1.7/src/lib/salad/bps_tree.h:1200
#7  0x000000000044c5f1 in bps_tree_vy_mem_tree_get_leaf_safe (tree=0xabd6d0, itr=0x1083408)
    at /data/work/tarantool/1.7/src/lib/salad/bps_tree.h:1421
#8  0x000000000044cd7f in vy_mem_tree_itr_get_elem (tree=0xabd6d0, itr=0x1083408) at /data/work/tarantool/1.7/src/lib/salad/bps_tree.h:1649
#9  0x000000000046c9b1 in vy_mem_iterator_check_version (itr=0x10833e8) at /data/work/tarantool/1.7/src/box/vinyl.c:7649
#10 0x000000000046cc1b in vy_mem_iterator_next_key (itr=0x10833e8) at /data/work/tarantool/1.7/src/box/vinyl.c:7716
#11 0x000000000046e090 in vy_mem_iterator_iface_next_key (vitr=0x10833e0) at /data/work/tarantool/1.7/src/box/vinyl.c:8298
#12 0x000000000046e808 in vy_merge_iterator_propagate (itr=0x7ffff552fc48) at /data/work/tarantool/1.7/src/box/vinyl.c:8596
#13 0x000000000046ee0b in vy_merge_iterator_next_key (itr=0x7ffff552fc48) at /data/work/tarantool/1.7/src/box/vinyl.c:8746
#14 0x000000000046f85d in vy_read_iterator_next (itr=0x7ffff552fbf0) at /data/work/tarantool/1.7/src/box/vinyl.c:9044
#15 0x000000000046fa5a in vy_read_iterator_get (itr=0x7ffff552fbf0, result=0x7ffff552fd08) at /data/work/tarantool/1.7/src/box/vinyl.c:9096
#16 0x000000000046fb90 in vy_index_read (index=0xabb0f0, key=0x2531280, order=VINYL_EQ, result=0x7ffff552fd08, tx=0x0)
    at /data/work/tarantool/1.7/src/box/vinyl.c:9129
#17 0x000000000046a03f in vy_get (tx=0x0, index=0xabb0f0, key=0x7ffff5509039 "\315\036(PPPP", part_count=1, result=0x7ffff552fd50)
    at /data/work/tarantool/1.7/src/box/vinyl.c:6355
#18 0x0000000000446995 in VinylIndex::findByKey (this=0xa68570, key=0x7ffff5509039 "\315\036(PPPP", part_count=1)
    at /data/work/tarantool/1.7/src/box/vinyl_index.cc:77
```

It seems that iterator re-position is broken. Please see branch gh-1756-coeio-read
