### ISSUE TITLE
lua preprocessor error: "Server 'replica1' already exists"

### ISSUE THREAD

**Issue by rtsisyk** [tarantool/tarantool#1763]
while ./test-run.py prune --long; do sleep 0.1; done

```
replication/prune.test.lua                                      Traceback (most recent call last):
  File "/data/work/tarantool/1.6/test-run/lib/inspector.py", line 58, in handle
    result = self.parser.parse_preprocessor(line)
  File "/data/work/tarantool/1.6/test-run/lib/preprocessor.py", line 97, in parse_preprocessor
    return self.server(stype, sname, options)
  File "/data/work/tarantool/1.6/test-run/lib/preprocessor.py", line 262, in server
    getattr(self, attr)(ctype, sname, opts)
  File "/data/work/tarantool/1.6/test-run/lib/preprocessor.py", line 170, in server_create
    raise LuaPreprocessorException('Server {0} already exists'.format(repr(sname)))
LuaPreprocessorException: lua preprocessor error: "Server 'replica1' already exists"
^CKeyboardInterrupt
```

**Comment by rtsisyk** [comment]
Fixed by 85df49039857d897b3ed48bf52370399cf0ff2dc
