### ISSUE TITLE
vinyl: segfault at vy_cursor_delete

### ISSUE THREAD

**Issue by rtsisyk** [tarantool/tarantool#1780]
while ./test-run.py vinyl/; do sleep 0.5; done (multiple times)

```
(gdb) bt
#0  0x00007f342e390478 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:55
#1  0x00007f342e3918fa in __GI_abort () at abort.c:89
#2  0x000000000040be9a in sig_fatal_cb (signo=11) at /work/tarantool/1.7/src/main.cc:196
#3  <signal handler called>
#4  0x00000000004633c2 in vy_cursor_delete (c=0x7f342dc68210) at /work/tarantool/1.7/src/box/vinyl.c:4097
#5  0x00000000004475c6 in vinyl_iterator_free (ptr=0x161d650) at /work/tarantool/1.7/src/box/vinyl_index.cc:316
#6  0x000000000042af61 in box_iterator_free (it=0x161d650) at /work/tarantool/1.7/src/box/index.cc:528
#7  0x00000000004e2228 in lj_vm_ffi_call ()
#8  0x000000000056dcff in lj_ccall_func (L=0x407641d0, cd=0x40579ae0) at lj_ccall.c:985
#9  0x0000000000592ea9 in lj_cf_ffi_meta___call (L=0x407641d0) at lib_ffi.c:230
#10 0x00000000004e027b in lj_BC_FUNCC ()
#11 0x00000000004e44e6 in gc_call_finalizer (g=0x4011c3b8, L=0x407641d0, mo=0x7f342dd1fb20, o=0x40cab968) at lj_gc.c:466
#12 0x00000000004e4821 in gc_finalize (L=0x407641d0) at lj_gc.c:500
#13 0x00000000004e508e in gc_onestep (L=0x407641d0) at lj_gc.c:650
#14 0x00000000004e51a0 in lj_gc_step (L=0x407641d0) at lj_gc.c:680
#15 0x00000000004bec25 in luaL_pushcdata (L=0x407641d0, ctypeid=582) at /work/tarantool/1.7/src/lua/utils.c:94
#16 0x0000000000496f52 in lbox_pushtuple (L=0x407641d0, tuple=0x7f3408004a00)
    at /work/tarantool/1.7/src/box/lua/tuple.c:364
#17 0x00000000004979fe in lbox_pushtupleornil (L=0x407641d0, tuple=0x7f3408004a00)
    at /work/tarantool/1.7/src/box/lua/tuple.h:55
#18 0x0000000000497d01 in lbox_index_update (L=0x407641d0) at /work/tarantool/1.7/src/box/lua/index.c:94
#19 0x00000000004e027b in lj_BC_FUNCC ()
#20 0x0000000000501230 in lua_pcall (L=0x407641d0, nargs=3, nresults=0, errfunc=0) at lj_api.c:1055
#21 0x00000000004c0e90 in lbox_call (L=0x407641d0, nargs=3, nreturns=0)
    at /work/tarantool/1.7/src/lua/utils.c:946
#22 0x00000000004bb133 in lua_fiber_run_f (ap=0x7f342dc00d40) at /work/tarantool/1.7/src/lua/fiber.c:267
#23 0x000000000040bbd6 in fiber_cxx_invoke(fiber_func, typedef __va_list_tag __va_list_tag *) (f=0x4bb073 <lua_fiber_run_f>, 
    ap=0x7f342dc00d40) at /work/tarantool/1.7/src/fiber.h:593
#24 0x00000000004ce757 in fiber_loop (data=0x0) at /work/tarantool/1.7/src/fiber.c:477
#25 0x0000000000688b86 in coro_init () at /work/tarantool/1.7/third_party/coro/coro.c:110
```

```
(gdb) p c
$1 = (struct vy_cursor *) 0x7f342dc68210
(gdb) p *c
$2 = {tx_autocommit = {log = {first = 0x5050505050505050, last = 0x5050505050505050}, write_set = {
      rbt_root = 0x5050505050505050, rbt_nil = {tsn = 5787213827046133840, index = 0x5050505050505050, 
        tuple = 0x5050505050505050, tx = 0x5050505050505050, next_in_log = {next = 0x5050505050505050}, in_read_set = {
          rbn_left = 0x5050505050505050, rbn_right_red = 0x5050505050505050}, in_write_set = {rbn_left = 0x5050505050505050, 
          rbn_right_red = 0x5050505050505050}, is_read = 80}}, write_set_version = 1347440720, start = 5787213827046133840, 
    type = (unknown: 1347440720), state = (unknown: 1347440720), is_aborted = 80, tsn = 5787213827046133840, 
    vlsn = 5787213827046133840, tree_node = {rbn_left = 0x5050505050505050, rbn_right_red = 0x5050505050505050}, cursors = {
      prev = 0x5050505050505050, next = 0x5050505050505050}, manager = 0x5050505050505050}, index = 0x16c2750, 
  key = 0x15eb530, tx = 0x0, order = VINYL_GT, n_reads = 1, start = 949306336355858, next_in_tx = {prev = 0x1614c58, 
    next = 0x1614c58}}
(gdb) 
```

**Comment by kostja** [comment]
Fixed.
