### ISSUE TITLE
vinyl: can't initialize storage: index file '0000000000000001.range' open error: No such file or directory

### ISSUE THREAD

**Issue by rtsisyk** [tarantool/tarantool#1781]
1.7.1-406-ga46865d

./test-run.py engine/recover_snapshot --conf viny

```
Tarantool 1.7.1-406-ga46865d
Target: Linux-x86_64-Debug
Build options: cmake . -DCMAKE_INSTALL_PREFIX=/usr/local -DENABLE_BACKTRACE=ON
Compiler: /usr/bin/cc /usr/bin/c++
C_FLAGS: -fexceptions -funwind-tables -fno-omit-frame-pointer -fno-stack-protector -fno-common -fopenmp -msse2 -std=c11 -Wall -Wextra -Wno-strict-aliasing -fno-gnu89-inline -Werror
CXX_FLAGS: -fexceptions -funwind-tables -fno-omit-frame-pointer -fno-stack-protector -fno-common -fopenmp -msse2 -std=c++11 -Wall -Wextra -Wno-strict-aliasing -Wno-invalid-offsetof -Werror
================================================================================
TEST                                            PARAMS          RESULT
---------------------------------------------------------------------------
engine/recover_snapshot.test.lua                vinyl           Traceback (most recent call last):
  File "/data/work/tarantool/1.7/test-run/lib/inspector.py", line 58, in handle
    result = self.parser.parse_preprocessor(line)
  File "/data/work/tarantool/1.7/test-run/lib/preprocessor.py", line 97, in parse_preprocessor
    return self.server(stype, sname, options)
  File "/data/work/tarantool/1.7/test-run/lib/preprocessor.py", line 262, in server
    getattr(self, attr)(ctype, sname, opts)
  File "/data/work/tarantool/1.7/test-run/lib/preprocessor.py", line 253, in server_restart
    self.server_start(ctype, sname, opts)
  File "/data/work/tarantool/1.7/test-run/lib/preprocessor.py", line 154, in server_start
    self.servers[sname].start(silent=True)
  File "/data/work/tarantool/1.7/test-run/lib/tarantool_server.py", line 579, in start
    self.wait_until_started(wait_load)
  File "/data/work/tarantool/1.7/test-run/lib/tarantool_server.py", line 681, in wait_until_started
    msg, self.process if not self.gdb and not self.lldb else None)
  File "/data/work/tarantool/1.7/test-run/lib/tarantool_server.py", line 170, in seek_wait
    raise OSError("Can't start Tarantool")
OSError: Can't start Tarantool
[ fail ]

Test failed! Result content mismatch:
--- engine/recover_snapshot.result      Tue Sep 20 11:32:21 2016
+++ engine/recover_snapshot.reject      Tue Sep 20 13:33:37 2016
@@ -42,367 +42,22 @@
 - ok
 ...
 test_run:cmd('restart server default')
+('error', OSError("Can't start Tarantool",))
 space = box.space['test']
 ---
 ...
 index = space.index['primary']
 ---
+- error: '[string "index = space.index[''primary''] "]:1: attempt to index global
+    ''space'' (a nil value)'
 ...
 index:select({}, {iterator = box.index.ALL})

```

```
/data/work/tarantool/1.7/extra/dist/tarantoolctl: Starting instance...
2016-09-20 13:33:37.656 [4886] main/101/tarantoolctl C> version 1.7.1-406-ga46865d
2016-09-20 13:33:37.656 [4886] main/101/tarantoolctl C> log level 5
2016-09-20 13:33:37.656 [4886] main/101/tarantoolctl I> mapping 107374184 bytes for tuple arena...
2016-09-20 13:33:37.666 [4886] main/101/tarantoolctl I> recovery start
2016-09-20 13:33:37.666 [4886] main/101/tarantoolctl I> recovering from `/data/work/tarantool/1.7/test/var/box/00000000000000000355.snap'
2016-09-20 13:33:37.670 [4886] main/101/tarantoolctl memtx_engine.cc:288 E> rollback: index file '/data/work/tarantool/1.7/test/var/box/512/0/0000000000000001.range' open error: No such file or directory 
2016-09-20 13:33:37.670 [4886] main/101/tarantoolctl vinyl.c:2051 E> ER_VINYL: index file '/data/work/tarantool/1.7/test/var/box/512/0/0000000000000001.range' open error: No such file or directory 
2016-09-20 13:33:37.670 [4886] main/101/tarantoolctl F> can't initialize storage: index file '/data/work/tarantool/1.7/test/var/box/512/0/0000000000000001.range' open error: No such file or directory 
2016-09-20 13:33:37.670 [4886] main/101/tarantoolctl F> can't initialize storage: index file '/data/work/tarantool/1.7/test/var/box/512/0/0000000000000001.range' open error: No such file or directory
```

See also #1727

**Comment by rtsisyk** [comment]
This problem definitely blocks production - tarantool doesn't start (sometime).
Any news about this ticket?

**Comment by kostja** [comment]
We removed range index files, should be fixed by now.
