### ISSUE TITLE
Vinyl: duplicate key exists in unique index

### ISSUE THREAD

**Issue by andrew-statsenko** [tarantool/tarantool#1881]
Hello,

Tarantool (version 1.7.2-131-g20775fa) process receive a SISEGV  is case of concurrent tuple replacement.  The log message is:

2016-10-25 19:11:50.129 [11446] main C> entering the event loop
Segmentation fault
Current time: 1477681090
Please file a bug at http://github.com/tarantool/tarantool/issues
Attempting backtrace... Note: since the server has already crashed,
this may fail as well
#0  0x40f3d1 in sig_fatal_cb(int)+129
#1  0x7f151bb61100 in ?
#2  0x5e1a1c in smalloc+380
#3  0x41c73a in tuple_alloc(tuple_format*, unsigned long)+42
#4  0x41d88f in tuple_new(tuple_format*, char const*, char const*)+31
#5  0x41dd4e in box_tuple_new+14
#6  0x498e10 in lbox_tuple_new+208
#7  0x4d0f27 in lj_BC_FUNCC+52
2016-10-28 21:58:10.488 [23813] main/101/tarantoolctl C> version 1.7.2-131-g20775fa
2016-10-28 21:58:10.488 [23813] main/101/tarantoolctl C> log level 5
2016-10-28 21:58:10.488 [23813] main/101/tarantoolctl I> mapping 1073741824 bytes for tuple arena...
2016-10-28 21:58:10.491 [23813] main/101/tarantoolctl I> recovery start
2016-10-28 21:58:10.492 [23813] main/101/tarantoolctl I> recovering from `/var/lib/tarantool/hashdb/00000000000000000000.snap'
2016-10-28 21:58:10.497 [23813] main/101/tarantoolctl I> recover from `/var/lib/tarantool/hashdb/00000000000000000000.xlog'
2016-10-28 21:58:10.506 [23813] main/101/tarantoolctl vinyl_space.cc:65 E> ER_TUPLE_FOUND: Duplicate key exists in unique index 'sha1' in space 'hashdb'
2016-10-28 21:58:10.506 [23813] main/101/tarantoolctl F> can't initialize storage: Duplicate key exists in unique index 'sha1' in space 'hashdb'
2016-10-28 21:58:10.506 [23813] main/101/tarantoolctl F> can't initialize storage: Duplicate key exists in unique index 'sha1' in space 'hashdb'

All configs/data/logs mailed, please, see gh-1881.tar.gz .

**Comment by rtsisyk** [comment]
@alyapunov any news?

**Comment by rtsisyk** [comment]
This problem will be fixed by #1908
