### ISSUE TITLE
YCSB load test fails

### ISSUE THREAD

**Issue by hengestone** [tarantool/tarantool#2004]
Using YCSB from git, along with tarantool-1.7.2.416.g683f412-1 from the Ubuntu Xenial repository, I get lots of errors as follows:
./bin/ycsb run tarantool -p tarantool.port=3303 -s -P workloads/workloada
`Dec 21, 2016 1:02:54 PM com.yahoo.ycsb.db.TarantoolClient replace
SEVERE: Can't replace element
org.tarantool.TarantoolException: Failed to allocate 146 bytes in slab allocator for tuple
	at org.tarantool.TarantoolConnection16Base.readPacket(TarantoolConnection16Base.java:80)
	at org.tarantool.TarantoolConnection16Base.read(TarantoolConnection16Base.java:69)
	at org.tarantool.TarantoolConnection16Impl.exec(TarantoolConnection16Impl.java:26)
	at org.tarantool.TarantoolConnection16Base.replace(TarantoolConnection16Base.java:109)
	at com.yahoo.ycsb.db.TarantoolClient.replace(TarantoolClient.java:144)
	at com.yahoo.ycsb.db.TarantoolClient.update(TarantoolClient.java:131)
	at com.yahoo.ycsb.DBWrapper.update(DBWrapper.java:216)
	at com.yahoo.ycsb.workloads.CoreWorkload.doTransactionUpdate(CoreWorkload.java:801)
	at com.yahoo.ycsb.workloads.CoreWorkload.doTransaction(CoreWorkload.java:634)
	at com.yahoo.ycsb.ClientThread.run(Client.java:458)
	at java.lang.Thread.run(Thread.java:745)
[tarantool-tree.txt](https://github.com/tarantool/tarantool/files/667369/tarantool-tree.txt)
[workloada.txt](https://github.com/tarantool/tarantool/files/667370/workloada.txt)

`

**Comment by hengestone** [comment]
Needed to adjust the slab_alloc_arena size to accomodate the database size
