### ISSUE TITLE
vinyl: seg fault

### ISSUE THREAD

**Issue by vmakhaev** [tarantool/tarantool#2019]
```
2016-12-31 14:26:52.142 [7] main/101/init.lua C> version 1.7.2-287-g085f6e4
2016-12-31 14:26:52.143 [7] main/101/init.lua C> log level 5
2016-12-31 14:26:52.144 [7] main/101/init.lua I> mapping 536870912 bytes for tuple arena...
```

```
2016-12-31 16:12:27.387 [7] main/105/snapshot_daemon I> making snapshot...
2016-12-31 16:12:27.388 [7] vinyl.worker/101/main xlog.cc:694 !> ./521/0/000000000000002b.000000000000001d.1.run: failed to open: File exists
Segmentation fault
Current time: 1483200747
Please file a bug at http://github.com/tarantool/tarantool/issues
Attempting backtrace... Note: since the server has already crashed,
this may fail as well
#0  0x560e4d476049 in ?
#1  0x7f2682221e0c in ?
#2  0x560e4d4760cc in ?
#3  0x560e4d569550 in ?
#4  0x560e4d689a4f in ?
#5  0 in ?
Aborted (core dumped)
```

This is reproducible. Give me some contact where I can send core dump and wal/snapshots files.

**Comment by vmakhaev** [comment]
I'm gonna close this, because this is not reproduced with data files, created with last tarantool version.
