### ISSUE TITLE
Segfault in vy_cursor_next

### ISSUE THREAD

**Issue by dmitry-sobolev** [tarantool/tarantool#2023]
Today I've got another segfault:
```
Segmentation fault
Current time: 1484114401
Please file a bug at http://github.com/tarantool/tarantool/issues
Attempting backtrace... Note: since the server has already crashed, 
this may fail as well
#0  0x40e6f1 in sig_fatal_cb(int)+129
#1  0x7f549836f390 in ?
#2  0x4764df in vy_cursor_next+255
#3  0x4559d9 in iterator_next(iterator*)+25
#4  0x44d85d in Handler::executeSelect(txn*, space*, unsigned int, unsigned int, unsigned int, unsigned int, char const*, char const*, port*)+189
#5  0x51f388 in box_select+216
#6  0x410425 in tx_process_select(cmsg*)+165
#7  0x561d04 in fiber_pool_f+212
#8  0x40e1fc in fiber_cxx_invoke(int (*)(__va_list_tag*), __va_list_tag*)+12
#9  0x55f1e0 in fiber_loop+48
#10 0x6a7eff in coro_init+63
#11 (nil) in ?
```
This time tarantool was installed from packagecloud.io, package version is 1.7.3.28.g75ec202-1.

**Comment by kostja** [comment]
Sorry, we will not be able to fix this - we changed the code too significantly to be able to guess the cause of the error, and we couldn't reproduce it. Please reopen the bug if you experience it with the latest 1.7.
Thanks!
