### ISSUE TITLE
tarantool crashes on fiber wakeup from tarantool-queue

### ISSUE THREAD

**Issue by GeorgyKirichenko** [tarantool/tarantool#2066]
Tarantool spontaneously crashes with tarantool-queue module

```
017-02-03 04:03:26.845 [26460] main/11297/main txn.cc:228 W> too long WAL write: 4.840 sec
2017-02-03 04:03:26.845 [26460] main/109/minute-log-balance txn.cc:228 W> too long WAL write: 4.840 sec
2017-02-03 04:03:26.845 [26460] main/108/fifottl txn.cc:230 E> ER_WAL_IO: Failed to write to disk
2017-02-03 04:03:26.845 [26460] main/108/fifottl txn.cc:230 E> ER_WAL_IO: Failed to write to disk
Segmentation fault
Current time: 1486083806
Please file a bug at http://github.com/tarantool/tarantool/issues
Attempting backtrace... Note: since the server has already crashed, 
this may fail as well
#0  0x40e2d1 in sig_fatal_cb(int)+129
#1  0x7f7b729957e0 in ?
#2  0x599af0 in fiber_loop+48
#3  0x6d9e0f in coro_init+63
#4  (nil) in ?
```

**Comment by GeorgyKirichenko** [comment]
Crash can be reproduced with lua script:
```
