### ISSUE TITLE
vinyl/stress crashes if vinyl_memory = 4 MB

### ISSUE THREAD

**Issue by locker** [tarantool/tarantool#2207]
Branch 1.7, commit 91368a78ba30f32d7a4b42970432e7a41712bcdd
```
$ git diff
diff --git a/test/vinyl/vinyl.lua b/test/vinyl/vinyl.lua
index ff8fe306..f1bde49e 100644
--- a/test/vinyl/vinyl.lua
+++ b/test/vinyl/vinyl.lua
@@ -6,7 +6,7 @@ box.cfg {
     memtx_max_tuple_size = 4 * 1024 * 1024,
     rows_per_wal      = 1000000,
     vinyl_threads = 3;
-    vinyl_memory = 512 * 1024 * 1024;
+    vinyl_memory = 4 * 1024 * 1024;
     vinyl_range_size = 1024 * 64;
     vinyl_page_size = 1024;
     vinyl_run_count_per_level = 1;
```
```
================================================================================
TEST                                            PARAMS          RESULT
---------------------------------------------------------------------------
vinyl/stress.test.lua                                           [ fail ]

Test failed! Result content mismatch:
--- vinyl/stress.result Wed Mar  1 15:24:33 2017
+++ vinyl/stress.reject Wed Mar 15 16:50:52 2017
@@ -9,6 +9,5 @@
 ...
 test_run:cmd('restart server default')
 require('stress').stress(10)
----
-...
 test_run:cmd('restart server default')
+[Lost current connection]

Last 15 lines of Tarantool Log file:
[Instance "vinyl" crash detected]
[ReturnCode=-6]
Segmentation fault
Current time: 1489585852
Please file a bug at http://github.com/tarantool/tarantool/issues
Attempting backtrace... Note: since the server has already crashed,
this may fail as well
#0  0x40bff7 in sig_fatal_cb(int)+214
#1  0x7f51ea956890 in ?
#2  0x44e74c in vy_tuple_compare+32
#3  0x46d3a7 in vy_merge_iterator_next_key+1369
#4  0x46eaf0 in vy_read_iterator_merge_next_key+248
#5  0x46ed13 in vy_read_iterator_next+173
#6  0x46fe6e in vy_cursor_next+353
#7  0x44d2f4 in iterator_next(iterator*)+65
#8  0x440999 in Handler::executeSelect(txn*, space*, unsigned int, unsigned int, unsigned int, unsigned int, char const*, char const*, port*)+585
#9  0x49c019 in box_select+167
#10 0x4bf02f in lbox_select(lua_State*)+365
#11 0x506e5b in lj_BC_FUNCC+52

Fatal error: Failed to run test vinyl/stress.test.lua: wrong test output. Execution aborted.
```

**Comment by rtsisyk** [comment]
Status: this patch requires the test cases
