### ISSUE TITLE
Relay does not work if last (on subscribe time) xlog is not active and not properly closed

### ISSUE THREAD

**Issue by GeorgyKirichenko** [tarantool/tarantool#2294]
Deploy the master instance and join the replica. Then do something with master to write a new xlog file. Kill master with 9 signal and restart. Any new records from master will not to be replaeyd to slave until slave restarts.
At least from 5c6c4a8dc

**Comment by kostja** [comment]
I was able to reproduce this. Replication simply hangs, status: follow. This goes on until the xlog is reopened.

**Comment by kostja** [comment]
```
kostja@atlas ~ % cat master.lua
#!/usr/bin/env tarantool

box.cfg{}

box.schema.user.grant('guest', 'replication')

box.cfg{listen=3303}

box.schema.space.create('test')
box.space.test:create_index('pk')

fiber = require('fiber')

function f()
    while true do
        box.space.test:auto_increment{fiber.time()}
        fiber.sleep(3)
    end
end

fiber.create(f)

require('console').start()
kostja@atlas ~ % cat slave.lua 
#!/usr/bin/env tarantool
box.cfg{replication="3303"}
require('console').start()
kostja@atlas ~ % 
```

**Comment by kostja** [comment]
Master relay is stuck on the xlog which has no eof:
```
(gdb) info thread
  Id   Target Id         Frame 
  1    Thread 0x7f0e29cbfac0 (LWP 3892) "tarantool" 0x00007f0e2778e9d3 in epoll_wait () at ../sysdeps/unix/syscall-template.S:84
  2    Thread 0x7f0e0a7ff700 (LWP 3903) "iproto" 0x00007f0e2778e9d3 in epoll_wait () at ../sysdeps/unix/syscall-template.S:84
  3    Thread 0x7f0e097ff700 (LWP 3904) "wal" 0x00007f0e2778e9d3 in epoll_wait
    () at ../sysdeps/unix/syscall-template.S:84
  4    Thread 0x7f0e03fff700 (LWP 3905) "coio" pthread_cond_wait@@GLIBC_2.3.2
    () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  5    Thread 0x7f0e037fe700 (LWP 3906) "vinyl.reader.0" 0x00007f0e2778e9d3 in epoll_wait () at ../sysdeps/unix/syscall-template.S:84
* 6    Thread 0x7f0e02ffd700 (LWP 3907) "relay/127.0.0.1" 0x00007f0e2778e9d3 in epoll_wait () at ../sysdeps/unix/syscall-template.S:84

(gdb) bt
#0  0x00007f0e2778e9d3 in epoll_wait ()
    at ../sysdeps/unix/syscall-template.S:84
#1  0x00000000006ad6dc in epoll_poll (loop=0x25252a0, 
    timeout=0.94375749599930714)
    at /home/kostja/work/tarantool/third_party/libev/ev_epoll.c:153
#2  0x00000000006a8843 in ev_run (loop=0x25252a0, flags=0)
    at /home/kostja/work/tarantool/third_party/libev/ev.c:3542
#3  0x00000000005378e4 in cord_costart_thread_func (arg=0x257f780)
    at /home/kostja/work/tarantool/src/fiber.c:1173
#4  0x00000000005365f7 in cord_thread_func (p=0x7f0e2283e628)
    at /home/kostja/work/tarantool/src/fiber.c:974
#5  0x00007f0e27ff06ba in start_thread (arg=0x7f0e02ffd700)
    at pthread_create.c:333
#6  0x00007f0e2778e3dd in clone ()
    at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

(gdb) frame 3
#3  0x00000000005378e4 in cord_costart_thread_func (arg=0x257f780)
    at /home/kostja/work/tarantool/src/fiber.c:1173
1173			ev_run(loop(), 0);
(gdb) p ((struct relay*) ctx.arg)->r->cursor.name
$22 = "./", '0' <repeats 18 times>, "20.xlog", '\000' <repeats 4068 times>
```
