### ISSUE TITLE
vinyl: vinyl/write_iterator_rand fails with "single upserts error"

### ISSUE THREAD

**Issue by rtsisyk** [tarantool/tarantool#2318]
1.7.3-526-gbe89e652b
cmake . -DCMAKE_BUILD_TYPE=Debug -DENABLE_GCOV=ON
while ./test-run.py write_iterator_rand --long; do sleep 0.1; done

```
vinyl/write_iterator_rand.test.lua                              [ fail ]
Test failed! Result content mismatch:
--- vinyl/write_iterator_rand.result	Tue Apr 11 12:23:47 2017
+++ vinyl/write_iterator_rand.reject	Tue Apr 11 12:31:27 2017
@@ -236,5 +236,5 @@
 ...
 fill_space_with_sizes(page_size, range_size, 900)
 ---
-- ok
-...
+- single upserts error
+...
Last 15 lines of Tarantool Log file [Instance "vinyl"][/home/travis/build/tarantool/tarantool/test/var/vinyl.log
Last 15 lines of Tarantool Log file [Instance "vinyl"][/home/travis/build/tarantool/tarantool/test/var/vinyl.log]:
2017-04-11 12:31:26.715 [19155] main/102/vinyl.scheduler I> 567/0: completed dumping range (-inf..inf)
2017-04-11 12:31:26.724 [19155] main/110/console/unix/: I> vinyl checkpoint done
2017-04-11 12:31:27.290 [19155] main/102/vinyl.scheduler I> 567/0: started dumping range (-inf..inf)
2017-04-11 12:31:27.290 [19155] snapshot/101/main I> saving snapshot `/home/travis/build/tarantool/tarantool/test/var/vinyl/00000000000000120573.snap.inprogress'
2017-04-11 12:31:27.291 [19155] snapshot/101/main I> done
2017-04-11 12:31:27.300 [19155] main/102/vinyl.scheduler I> 567/0: completed dumping range (-inf..inf)
2017-04-11 12:31:27.309 [19155] main/110/console/unix/: I> vinyl checkpoint done
2017-04-11 12:31:27.317 [19155] main/102/vinyl.scheduler I> 567/0: started compacting range (-inf..inf), runs 0/2
2017-04-11 12:31:27.334 [19155] main/102/vinyl.scheduler I> 567/0: completed compacting range (-inf..inf)
2017-04-11 12:31:27.369 [19155] main/102/vinyl.scheduler I> 567/0: started dumping range (-inf..inf)
2017-04-11 12:31:27.375 [19155] snapshot/101/main I> saving snapshot `/home/travis/build/tarantool/tarantool/test/var/vinyl/00000000000000121473.snap.inprogress'
2017-04-11 12:31:27.376 [19155] snapshot/101/main I> done
2017-04-11 12:31:27.382 [19155] main/102/vinyl.scheduler I> 567/0: completed dumping range (-inf..inf)
2017-04-11 12:31:27.391 [19155] main/110/console/unix/: I> vinyl checkpoint done
2017-04-11 12:31:27.392 [19155] main/102/vinyl.scheduler I> 567/0: started compacting range (-inf..inf), runs 0/2
Fatal error: Failed to run test vinyl/write_iterator_rand.test.lua: wrong test output. Execution aborted.
[INFO/MainProcess] process shutting down
make: *** [coverage] Error 255
```

100% reproducibility.

**Comment by rtsisyk** [comment]
Caused by 
```
commit 8116f2096fefdbda9684dbc1f5194d7038bd1b8a
Author: Vladimir Davydov <vdavydov.dev@gmail.com>
Date:   Wed Apr 5 18:32:01 2017 +0300

    vinyl: pin in-memory trees on tx prepare

    Pin each in-memory tree which is going to be modified by a transaction
    on Engine::prepare, unpin it on commit or rollback. Pinned in-memory
    trees can't be dumped until they are unpinned - dump/compaction task
    constructors wait until pin_count drops to 0 before handing the task
    over to a worker thread. Since the constructors rotate the in-memory
    tree before waiting and new transaction can only go to active in-memory
    trees, they won't wait forever, only until all transactions that were
    started before the task was scheduled are over.
```

**Comment by rtsisyk** [comment]
```
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:58
#1  0x00007f866ee0040a in __GI_abort () at abort.c:89
#2  0x000055ad9f85a48d in sig_fatal_cb (signo=11) at /data/work/tarantool/1.7/src/main.cc:198
#3  <signal handler called>
#4  0x000055ad9f91c569 in tuple_format_id (format=0x2323232323232323) at /data/work/tarantool/1.7/src/box/tuple_format.h:161
#5  0x000055ad9f9274b7 in vy_mem_insert (mem=0x55ada0b5b6f0, stmt=0x7f8644400020) at /data/work/tarantool/1.7/src/box/vy_mem.c:152
#6  0x000055ad9f8f2c85 in vy_range_set (range=0x55ada0b6b790, mem=0x55ada0b5b6f0, stmt=0x55ada0c228f0, region_stmt=0x7f866e41fbb0)
    at /data/work/tarantool/1.7/src/box/vinyl.c:3652
#7  0x000055ad9f8f3a80 in vy_tx_write (index=0x55ada0b57f40, mem=0x55ada0b5b6f0, stmt=0x55ada0c228f0, region_stmt=0x7f866e41fbb0,
    status=VINYL_ONLINE) at /data/work/tarantool/1.7/src/box/vinyl.c:3879
#8  0x000055ad9f907a93 in vy_commit (e=0x55ada0afa7b0, tx=0x55ada0b69de0, lsn=65419) at /data/work/tarantool/1.7/src/box/vinyl.c:7267
#9  0x000055ad9f8d3809 in VinylEngine::commit (this=0x55ada0afa770, txn=0x7f866e537098, lsn=65419)
    at /data/work/tarantool/1.7/src/box/vinyl_engine.cc:223
#10 0x000055ad9f96afa7 in txn_commit (txn=0x7f866e537098) at /data/work/tarantool/1.7/src/box/txn.cc:248
#11 0x000055ad9f96a829 in txn_commit_stmt (txn=0x7f866e537098, request=0x7f866e537040) at /data/work/tarantool/1.7/src/box/txn.cc:181
#12 0x000055ad9f97067a in process_rw (request=0x7f866e537040, space=0x55ada0b45f40, result=0x7f866e41fe20)
    at /data/work/tarantool/1.7/src/box/box.cc:211
#13 0x000055ad9f973aae in box_process1 (request=0x7f866e537040, result=0x7f866e41fe20) at /data/work/tarantool/1.7/src/box/box.cc:688
#14 0x000055ad9f973fb2 in box_replace (space_id=515, tuple=0x7f866e537038 "\221\001\261\240\255U", tuple_end=0x7f866e53703a "\261\240\255U",
    result=0x7f866e41fe20) at /data/work/tarantool/1.7/src/box/box.cc:742
#15 0x000055ad9f9a9890 in lbox_replace (L=0x41035230) at /data/work/tarantool/1.7/src/box/lua/index.c:70
#16 0x000055ad9fa3d8fb in lj_BC_FUNCC ()
#17 0x000055ad9fa6f706 in lua_pcall (L=0x41035230, nargs=3, nresults=0, errfunc=0) at lj_api.c:1055
#18 0x000055ad9fa02396 in luaT_call (L=0x41035230, nargs=3, nreturns=0) at /data/work/tarantool/1.7/src/lua/utils.c:954
#19 0x000055ad9f9f69a2 in lua_fiber_run_f (ap=0x7f866e4001b0) at /data/work/tarantool/1.7/src/lua/fiber.c:267
#20 0x000055ad9f859e35 in fiber_cxx_invoke(fiber_func, typedef __va_list_tag __va_list_tag *) (f=0x55ad9f9f6898 <lua_fiber_run_f>,
    ap=0x7f866e4001b0) at /data/work/tarantool/1.7/src/fiber.h:550
#21 0x000055ad9fa1de6d in fiber_loop (data=0x0) at /data/work/tarantool/1.7/src/fiber.c:557
#22 0x000055ad9fcc3cf8 in coro_init () at /data/work/tarantool/1.7/third_party/coro/coro.c:110
```
