### ISSUE TITLE
Tarantool crashes, if do space:format twice during snapshoting

### ISSUE THREAD

**Issue by Mons** [tarantool/tarantool#2336]
init.lua:
```lua
box.cfg { slab_alloc_arena = 0.1 }

local sp = box.space.sp
if not sp then
	sp = box.schema.space.create('sp')
	box.space.sp:create_index('primary',{ parts = { 1,'str' } })
end

sp:truncate()

sp:format({
	[1] = { name ="key"; type = "string" };
	[2] = { name ="dataAB"; type = "string" };
})

local str = string.rep("t",1024)
for i = 1,10000 do
	box.space.sp:insert{tostring(i), str}
end

local fiber = require 'fiber'
local log = require 'log'

fiber.create(function()
	fiber.yield()
	log.info("start snap")
	box.snapshot()
	log.info("snap was done")
end)

for i = 1,2 do
fiber.create(function()
	fiber.yield()
	log.info("set format")
	sp:format({
		[1] = { name ="key"; type = "string" };
		[2] = { name ="dataAB"; type = "string" };
	})
	log.info("format was set")
end)
end
```

This gives the following crash:
```
2017-04-18 17:44:23.493 [5644] main/101/test.lua C> version 1.6.9-80-g2672373
2017-04-18 17:44:23.493 [5644] main/101/test.lua C> log level 5
2017-04-18 17:44:23.493 [5644] main/101/test.lua I> mapping 107374184 bytes for tuple arena...
2017-04-18 17:44:23.505 [5644] main/101/test.lua I> initializing an empty data directory
2017-04-18 17:44:23.511 [5644] snapshot/101/main I> creating `./00000000000000000000.snap.inprogress'
2017-04-18 17:44:23.511 [5644] snapshot/101/main I> saving snapshot `./00000000000000000000.snap.inprogress'
2017-04-18 17:44:23.511 [5644] snapshot/101/main I> done
2017-04-18 17:44:23.599 [5644] main/101/test.lua I> ready to accept requests
2017-04-18 17:44:23.600 [5644] wal/101/main I> creating `./00000000000000000000.xlog.inprogress'
2017-04-18 17:44:23.890 [5644] main C> entering the event loop
2017-04-18 17:44:23.890 [5644] main/104/lua I> start snap
2017-04-18 17:44:23.891 [5644] main/106/lua I> set format
2017-04-18 17:44:23.891 [5644] main/105/lua I> set format
2017-04-18 17:44:23.893 [5644] snapshot/101/main I> creating `./00000000000000010006.snap.inprogress'
2017-04-18 17:44:23.893 [5644] snapshot/101/main I> saving snapshot `./00000000000000010006.snap.inprogress'
2017-04-18 17:44:24.001 [5644] snapshot/101/main I> done
2017-04-18 17:44:24.194 [5644] main/104/lua I> snap was done
2017-04-18 17:44:24.194 [5644] main/106/lua I> format was set
Segmentation fault
Current time: 1492526664
Please file a bug at http://github.com/tarantool/tarantool/issues
Attempting backtrace... Note: since the server has already crashed,
this may fail as well
#0  0x424c51 in sig_fatal_cb(int)+129
#1  0x7fb86367a100 in ?
#2  0x44a7d2 in txn_commit(txn*)+594
#3  0x44b810 in process_rw(request*, tuple**)+144
#4  0x44ce1d in box_process1+29
#5  0x44d1bd in box_update+109
#6  0x45d0b9 in lbox_index_update+281
#7  0x4dfeb7 in lj_BC_FUNCC+52
Aborted
```

**Comment by rtsisyk** [comment]
1.7.4-348-g87fb9470d
