### ISSUE TITLE
cursors after index's death

### ISSUE THREAD

**Issue by alyapunov** [tarantool/tarantool#2342]
I wanted to add the code to test/vinyl/iterator.test.lua:
```
--cursors after death of index
s = box.schema.space.create('test', { engine = 'vinyl' })
pk = s:create_index('primary', { parts = { 1, 'uint' } })
s:replace{1, 2, 3}
s:replace{4, 5, 6}
s:replace{7, 8, 9}
itr = create_iterator(s, {})
iterator_next(itr)
s:drop()
itr = nil
collectgarbage('collect')
```
But I do not like the result:
```
Segmentation fault
Current time: 1492618222
Please file a bug at http://github.com/tarantool/tarantool/issues
Attempting backtrace... Note: since the server has already crashed, 
this may fail as well
#0  0x40c385 in sig_fatal_cb(int)+214
#1  0x7f6f0b9b3340 in ?
#2  0x452f3f in read_set_remove+91
#3  0x46791e in vy_tx_destroy+122
#4  0x468171 in vy_tx_rollback+35
#5  0x46de22 in vy_cursor_delete+100
#6  0x44ea24 in vinyl_iterator_free(iterator*)+90
#7  0x430cb4 in box_iterator_free+42
#8  0x50f3b8 in lj_vm_ffi_call+132
#9  0x59aba5 in lj_ccall_func+964
#10 0x5bfc00 in lj_cf_ffi_meta___call+170
#11 0x50d40b in lj_BC_FUNCC+52
```

**Comment by rtsisyk** [comment]
1.7.4-473-ge3c5fde4b
