### ISSUE TITLE
vinyl:  segfault in vy_merge_iterator_next_key on LinkBench

### ISSUE THREAD

**Issue by rtsisyk** [tarantool/tarantool#2423]
```
#0 0x40c5dc in sig_fatal_cb(int)+214
#1 0x7f0f64fd6390 in ?
#2 0x46c02b in vy_merge_iterator_next_key+1460
#3 0x46d7e6 in vy_read_iterator_merge_next_key+250
#4 0x46da36 in vy_read_iterator_next+173
#5 0x46f9c1 in vy_cursor_next+561
#6 0x44f6e7 in iterator_next(iterator*)+43
#7 0x4427d7 in Handler::executeSelect(txn*, space*, unsigned int, unsigned int, unsigned int, unsigned int, char const*, char const*, port*)+525
#8 0x4ab6ba in box_select+167
#9 0x4caddd in lbox_select(lua_State*)+365
#10 0x514d4b in lj_BC_FUNCC+52
```

100% reproducibility. Please ask @IlyaMarkovMipt how to run [LinkBench](https://github.com/tarantool/linkbench) with Vinyl.

**Comment by rtsisyk** [comment]
Fixed
