### ISSUE TITLE
Segfault in vinyl upsert

### ISSUE THREAD

**Issue by IlyaMarkovMipt** [tarantool/tarantool#2461]
I have Tarantool 1.7.4-29-g4a02c32
And following script:

```
box.cfg{}
space = box.schema.space.create('test', { engine = 'vinyl'})
index1 = space:create_index('primary', { parts = {1, 'unsigned', 3, 'unsigned'} })
space:upsert({100, 100, 100}, {{'+', 2, 200}})
space:upsert({200, 100, 200}, {{'+', 2, 300}})
space:upsert({300, 100, 300}, {{'+', 2, 400}})
index1:select{}
```

It fails with segmentation fault:

```
Segmentation fault
Current time: 1495541040
Please file a bug at http://github.com/tarantool/tarantool/issues
Attempting backtrace... Note: since the server has already crashed, 
this may fail as well
#0  0x4115f1 in sig_fatal_cb(int)+129
#1  0x7faebcb2d390 in ?
#2  0x46e1db in vy_read_iterator_merge_next_key+107
#3  0x4769fb in vy_read_iterator_next+123
#4  0x47a7e2 in vy_cursor_next+290
#5  0x46223b in iterator_next(iterator*)+27
#6  0x45893d in Handler::executeSelect(txn*, space*, unsigned int, unsigned int, unsigned int, unsigned int, char const*, char const*, port*)+221
#7  0x4bf778 in box_select+216
#8  0x4d8cd9 in lbox_select(lua_State*)+297
#9  0x50f7c7 in lj_BC_FUNCC+52
Aborted (core dumped)
```

**Comment by Gerold103** [comment]
I have catched the another segfault already on first-second upsert.
```
tarantool> space:upsert({200, 100, 200}, {{'+', 2, 300}})
Process 86434 stopped
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x85f03542)
    frame #0: 0x0000000100244b9f tarantool`mp_load_u8(data=0x000000000182f228) at msgpuck.h:235
   232 		return data + sizeof(type);						\
   233 	}
   234 	
-> 235 	MP_LOAD_STORE(u8, uint8_t, mp_identity);
   236 	
   237 	#if __BYTE_ORDER__ == __ORDER_LITTLE_ENDIAN__

```
