### ISSUE TITLE
Crash in relay_cbus_detach when running replication tests

### ISSUE THREAD

**Issue by locker** [tarantool/tarantool#2497]
Branch 1.7 commit 5e26af20eea1a724787137a5750068d6795858a1

The following command
```
$ ./test-run.py -j -1 replication/catch.test.lua replication/prune.test.lua --conf memtx --long
```
crashes tarantool with the following stack trace
```
#0  0x0000000000504096 in rlist_del (item=0x7fa7f8c4f650) at /home/vlad/src/tarantool/src/lib/small/small/rlist.h:93
#1  0x000000000050568f in cbus_endpoint_destroy (endpoint=0x7fa7f8c4f630, process_cb=0x505f2b <cbus_process>) at /home/vlad/src/tarantool/src/cbus.c:207
#2  0x00000000004c1d2b in relay_cbus_detach (relay=0x7fa7f8c4ef80) at /home/vlad/src/tarantool/src/box/relay.cc:282
#3  0x00000000004c1d5e in <lambda()>::operator()(void) const (__closure=0x7fa7d681ff00) at /home/vlad/src/tarantool/src/box/relay.cc:305
#4  0x00000000004c2998 in ScopedGuard<relay_subscribe_f(__va_list_tag*)::<lambda()> >::~ScopedGuard(void) (this=0x7fa7d681ff00, __in_chrg=<optimized out>) at /home/vlad/src/tarantool/src/scoped_guard.h:54
#5  0x00000000004c2250 in relay_subscribe_f(typedef __va_list_tag __va_list_tag *) (ap=0x7fa7d6800228) at /home/vlad/src/tarantool/src/box/relay.cc:387
#6  0x000000000040c15d in fiber_cxx_invoke(fiber_func, typedef __va_list_tag __va_list_tag *) (f=0x4c1d60 <relay_subscribe_f(typedef __va_list_tag __va_list_tag *)>, ap=0x7fa7d6800228) at /home/vlad/src/tarantool/src/fiber.h:646
#7  0x0000000000501e97 in fiber_loop (data=0x0) at /home/vlad/src/tarantool/src/fiber.c:641
#8  0x00000000006bada1 in coro_init () at /home/vlad/src/tarantool/third_party/coro/coro.c:110
```
The bug was triggered by commit 067a31b43c8558a919170e2c39fe6e99311b27dd

**Comment by locker** [comment]
Another manifestation of the same bug:
```
$ ./test-run.py -j -1 replication/catch.test.lua replication/gc.test.lua --conf memtx --long
```
results in
```
#0  0x00007fea548be067 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x00007fea548bf448 in __GI_abort () at abort.c:89
#2  0x000000000040c3f9 in sig_fatal_cb (signo=11) at /home/vlad/src/tarantool/src/main.cc:186
#3  <signal handler called>
#4  0x000000000050419e in stailq_concat (head1=0x7fea5443f688, head2=0x7fea5444f730) at /home/vlad/src/tarantool/src/lib/salad/stailq.h:142
#5  0x0000000000505a02 in cpipe_flush_cb (loop=0xa85900 <default_loop_struct>, watcher=0x7fea5444f748, events=16777216) at /home/vlad/src/tarantool/src/cbus.c:239
#6  0x00000000006b677c in ev_invoke_pending (loop=0xa85900 <default_loop_struct>) at /home/vlad/src/tarantool/third_party/libev/ev.c:3176
#7  0x00000000006b766a in ev_run (loop=0xa85900 <default_loop_struct>, flags=0) at /home/vlad/src/tarantool/third_party/libev/ev.c:3576
#8  0x000000000040d889 in main (argc=3, argv=0x14814b8) at /home/vlad/src/tarantool/src/main.cc:646
```
