### ISSUE TITLE
Crash at log.info(true)

### ISSUE THREAD

**Issue by stepan-mitkin** [tarantool/tarantool#2516]
`log.info(true)` causes segfault

```
$ uname -a
Linux anton 4.4.0-79-generic #100-Ubuntu SMP Wed May 17 19:58:14 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

$ tarantool 
version 1.8.1-143-g47b70d9
type 'help' for interactive help

tarantool> log = require("log")
---
...

tarantool> log.info(true)
Segmentation fault
Current time: 1497206301
Please file a bug at http://github.com/tarantool/tarantool/issues
Attempting backtrace... Note: since the server has already crashed, 
this may fail as well
#0  0x40fc51 in sig_fatal_cb(int)+129
#1  0x7f5829725390 in ?
#2  0x7f58288d7ef1 in ?
#3  0x7f582899e296 in ?
Avbrutt (SIGABRT) (kjerne lagret i fil)
```

**Comment by bigbes** [comment]
Well, this is regression caused by https://github.com/tarantool/tarantool/commit/8c3b6310abdbf2ef74b93324797dcf0b27c6b0dd this commit.
