### ISSUE TITLE
truncate() segfaults in transactions

### ISSUE THREAD

**Issue by rtsisyk** [tarantool/tarantool#2525]
```
#!./src/tarantool

local yaml = require('yaml')

box.cfg()

box.once('xx', function()
    box.schema.space.create('test')
    box.space.test:create_index('primary')

    box.begin()
    box.space.test:truncate()
    box.space.test:insert({1, 'hello'})
    box.rollback()
end)

print(yaml.encode(box.space.test:select()))
```

```
(gdb) bt
#0  0x0000000000000000 in ?? ()
#1  0x00005555555dcbe3 in MemtxEngine::rollbackStatement (this=0x555555c9a660, stmt=0x7ffff11023a8)
    at /home/roman/tarantool/1.7/src/box/memtx_engine.cc:344
#2  0x00005555555dccc2 in MemtxEngine::rollback (this=0x555555c9a660, txn=0x7ffff1102038) at /home/roman/tarantool/1.7/src/box/memtx_engine.cc:363
#3  0x0000555555646b83 in txn_rollback () at /home/roman/tarantool/1.7/src/box/txn.cc:293
#4  0x0000555555647069 in box_txn_rollback () at /home/roman/tarantool/1.7/src/box/txn.cc:363
#5  0x0000555555664e56 in lbox_rollback (L=0x40000378) at /home/roman/tarantool/1.7/src/box/lua/init.c:93
#6  0x00005555556bcc2b in lj_BC_FUNCC ()
#7  0x00005555556defbf in lua_pcall (L=0x40000378, nargs=0, nresults=0, errfunc=0) at lj_api.c:1129
#8  0x0000555555698c8f in luaT_call (L=0x40000378, nargs=0, nreturns=0) at /home/roman/tarantool/1.7/src/lua/utils.c:954
#9  0x0000555555691dca in run_script_f (ap=0x7ffff1000228) at /home/roman/tarantool/1.7/src/lua/init.c:496
#10 0x00005555555a06fe in fiber_cxx_invoke(fiber_func, typedef __va_list_tag __va_list_tag *) (f=0x555555691a51 <run_script_f>, ap=0x7ffff1000228)
    at /home/roman/tarantool/1.7/src/fiber.h:646
#11 0x00005555556a821e in fiber_loop (data=0x0) at /home/roman/tarantool/1.7/src/fiber.c:641
#12 0x00005555558752a9 in coro_init () at /home/roman/tarantool/1.7/third_party/coro/coro.c:110
```

1.7.4-163-g73a39ad33

**Comment by rtsisyk** [comment]
50a4a87a63cc9db9a162db8993548f3a473f6157
