### ISSUE TITLE
curl: POST with empty body cause libcurl to read data from stdin

### ISSUE THREAD

**Issue by rtsisyk** [tarantool/tarantool#2530]
A test case:

```
console1$ nc -l 8000
console2$ tarantool> require('http.client').post('http://127.0.0.1:8000/') <!-- empty body
<stuck>
gdb$

#0  0x00007f7886d2d5a0 in __read_nocancel () at ../sysdeps/unix/syscall-template.S:84
#1  0x00007f7886cc4a54 in __GI__IO_file_xsgetn (fp=0x7f7886fea8c0 <_IO_2_1_stdin_>, data=<optimized out>, n=16384) at fileops.c:1442
#2  0x00007f7886cb9aa9 in __GI__IO_fread (buf=<optimized out>, size=1, count=16384, fp=0x7f7886fea8c0 <_IO_2_1_stdin_>) at iofread.c:38
#3  0x00007f788832cd63 in ?? () from /usr/lib/x86_64-linux-gnu/libcurl-gnutls.so.4
#4  0x00007f788832d56a in ?? () from /usr/lib/x86_64-linux-gnu/libcurl-gnutls.so.4
#5  0x00007f78883386d6 in ?? () from /usr/lib/x86_64-linux-gnu/libcurl-gnutls.so.4
#6  0x00007f78883395aa in ?? () from /usr/lib/x86_64-linux-gnu/libcurl-gnutls.so.4
#7  0x00007f7888339687 in curl_multi_socket_action () from /usr/lib/x86_64-linux-gnu/libcurl-gnutls.so.4
#8  0x00005593af6ca665 in curl_multi_process (multi=0x5593b0317ac0, sockfd=6, events=2) at /home/roman/tarantool/1.7/src/httpc.c:61
#9  0x00005593af6caa35 in curl_sock_cb (loop=0x5593afc97260 <default_loop_struct>, watcher=0x7f788280c070, revents=2)
    at /home/roman/tarantool/1.7/src/httpc.c:168
#10 0x00005593af8bf0c6 in ev_invoke_pending (loop=0x5593afc97260 <default_loop_struct>) at /home/roman/tarantool/1.7/third_party/libev/ev.c:3176
#11 0x00005593af8bffce in ev_run (loop=0x5593afc97260 <default_loop_struct>, flags=0) at /home/roman/tarantool/1.7/third_party/libev/ev.c:3576
#12 0x00005593af6e05b3 in tarantool_lua_run_script (path=0x0, argc=1, argv=0x5593b0310d90) at /home/roman/tarantool/1.7/src/lua/init.c:531
#13 0x00005593af5efe8c in main (argc=1, argv=0x5593b0310d90) at /home/roman/tarantool/1.7/src/main.cc:634

(gdb) frame 2
#2  0x00007f7886cb9aa9 in __GI__IO_fread (buf=<optimized out>, size=1, count=16384, fp=0x7f7886fea8c0 <_IO_2_1_stdin_>) at iofread.c:38
38      in iofread.c
```

**Comment by rtsisyk** [comment]
I fixed this bug, but failed to make a non-flaky test case:
```
test:test("bugs", function(test)
    test:plan(1)

    --
    -- gh-2530: POST with empty body cause libcurl to read data from stdin
    --
    local function gh2530_handler(client, peer)
        print('111')
        print(client:read(1))
        print('xx')
    end
    local s, addr = socketlib.tcp_server('127.0.0.1', 0,
        { handler = gh2530_handler})
    local host, port = s:name().host, s:name().port
    local r = client.post(string.format("http://%s:%s/", host, port), nil,
                        { timeout = 0.02 })
    s:close()
    test:is(r.status, 408, "gh-2530 post with empty body")
end)
```

**Comment by rtsisyk** [comment]
12bab610af0cbca08b975b44317c4a21dcf5e039
