### ISSUE TITLE
box.info() crash on uncofigured box

### ISSUE THREAD

**Issue by rtsisyk** [tarantool/tarantool#266]
```
./src/tarantool: version 1.6.2-17-gba44d4d
tarantool> box.info()
Segmentation fault
Current time: 1398181859
Please file a bug at http://github.com/tarantool/tarantool/issues
Attempting backtrace... Note: since the server has already crashed, 
this may fail as well
#0  0x41b0b1 in sig_fatal_cb(int)+191
#1  0x7f1b9f0a1210 in ?
#2  0x466ad2 in lbox_info_call(lua_State*)+116
#3  0x4df72c in lj_BC_FUNCC+52
Aborted
```

See also #285, #328

**Comment by rtsisyk** [comment]
```
tarantool> require('box.info')()

Program received signal SIGSEGV, Segmentation fault.
0x0000000000456528 in lbox_info_recovery_lag (L=0x40000378) at /data/work/tarantool/master2/src/box/lua/info.cc:48
48              lua_pushnumber(L, recovery->remote.recovery_lag);
(gdb) bt
#0  0x0000000000456528 in lbox_info_recovery_lag (L=0x40000378) at /data/work/tarantool/master2/src/box/lua/info.cc:48
#1  0x0000000000456b86 in lbox_info_call (L=0x40000378) at /data/work/tarantool/master2/src/box/lua/info.cc:227
#2  0x00000000004ebeec in lj_BC_FUNCC ()
#3  0x00000000004d678f in lua_call ()
#4  0x000000000047b34d in lbox_call (L=0x40000378, nargs=0, nreturns=0) at /data/work/tarantool/master2/src/lua/utils.h:443
#5  0x000000000047c4a2 in run_script(typedef __va_list_tag __va_list_tag *) (ap=0x7ffff58001d0) at /data/work/tarantool/master2/src/lua/init.cc:421
#6  0x000000000048c0e4 in fiber_loop (data=0x0) at /data/work/tarantool/master2/src/fiber.cc:388
#7  0x000000000055ed2d in coro_init () at /data/work/tarantool/master2/third_party/coro/coro.c:96
```
