### ISSUE TITLE
Crash in tx_conflict test

### ISSUE THREAD

**Issue by alyapunov** [tarantool/tarantool#2675]
If one increases the number of tests in tx_conflict.test
```
diff --git a/test/vinyl/tx_conflict.test.lua b/test/vinyl/tx_conflict.test.lua
index 1dfa533..04abacb 100644
--- a/test/vinyl/tx_conflict.test.lua
+++ b/test/vinyl/tx_conflict.test.lua
@@ -20,7 +20,7 @@ txn_proxy = require('txn_proxy')
 --settings
 num_tx = 10 --number of concurrent transactions
 num_key = 5 --number of keys that transactions use
-num_tests = 50 --number of test rounds to run
+num_tests = 500 --number of test rounds to run
 
 txs = {}
 order_of_commit = {}
```
the test crashes with the following backtrace
```
#0  0x00007ffff5d2dcc9 in __GI_raise (sig=sig@entry=6)
    at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x00007ffff5d310d8 in __GI_abort () at abort.c:89
#2  0x00007ffff5d26b86 in __assert_fail_base (
    fmt=0x7ffff5e77830 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", 
    assertion=assertion@entry=0x66b012 "nodep->node == node", 
    file=file@entry=0x66afc0 "/home/alyapunov/Work/tarantool/src/box/vy_tx.h", 
    line=line@entry=124, 
    function=function@entry=0x66b810 <__PRETTY_FUNCTION__.7444> "read_set_remove") at assert.c:92
#3  0x00007ffff5d26c32 in __GI___assert_fail (
    assertion=0x66b012 "nodep->node == node", 
    file=0x66afc0 "/home/alyapunov/Work/tarantool/src/box/vy_tx.h", line=124, 
    function=0x66b810 <__PRETTY_FUNCTION__.7444> "read_set_remove")
    at assert.c:101
#4  0x0000000000469636 in read_set_remove (rbtree=0xa39b58, 
    node=0x7ffff085d8f0) at /home/alyapunov/Work/tarantool/src/box/vy_tx.h:123
#5  0x000000000046cc2c in vy_tx_destroy (tx=0x7ffff0930230)
    at /home/alyapunov/Work/tarantool/src/box/vy_tx.c:278
#6  0x0000000000447b0a in vy_cursor_delete (env=0xa39690, c=0x7ffff0930230)
    at /home/alyapunov/Work/tarantool/src/box/vinyl.c:5011
#7  0x0000000000436d07 in iterator_next (base_it=0xa41460)
    at /home/alyapunov/Work/tarantool/src/box/vinyl_index.cc:178
---Type <return> to continue, or q <return> to quit---
#8  0x0000000000428c85 in Handler::executeSelect (this=0xa0c1c0, 
    space=0xa6dbf0, index_id=0, iterator=2, offset=0, limit=4294967295, 
    key=0x7ffff09d5039 "\004\315", <incomplete sequence \355>, 
    port=0x7ffff081fdf0)
    at /home/alyapunov/Work/tarantool/src/box/engine.cc:202
#9  0x00000000004a260c in box_select (port=0x7ffff081fdf0, space_id=512, 
    index_id=0, iterator=2, offset=0, limit=4294967295, 
    key=0x7ffff09d5038 "\220\004\315", <incomplete sequence \355>, 
    key_end=0x7ffff09d5039 "\004\315", <incomplete sequence \355>)
    at /home/alyapunov/Work/tarantool/src/box/box.cc:772
#10 0x00000000004c20ed in lbox_select (L=0x40153f98)
    at /home/alyapunov/Work/tarantool/src/box/lua/misc.cc:95
#11 0x0000000000503b2b in lj_BC_FUNCC ()
#12 0x0000000000524e77 in lua_pcall (L=0x40153f98, nargs=3, nresults=0, 
    errfunc=0) at lj_api.c:1129
#13 0x00000000004d404f in luaT_call (L=0x40153f98, nargs=3, nreturns=0)
    at /home/alyapunov/Work/tarantool/src/lua/utils.c:931
#14 0x00000000004cdc2d in lua_fiber_run_f (ap=0x7ffff08001b0)
    at /home/alyapunov/Work/tarantool/src/lua/fiber.c:264
#15 0x000000000040b894 in fiber_cxx_invoke(fiber_func, typedef __va_list_tag __va_list_tag *) (f=0x4cdb67 <lua_fiber_run_f>, ap=0x7ffff08001b0)
    at /home/alyapunov/Work/tarantool/src/fiber.h:644
#16 0x00000000004e2cf3 in fiber_loop (data=0x0)
```

**Comment by rtsisyk** [comment]
1.7.4-453-geb5cd536d
