### ISSUE TITLE
vinyl: crash in vy_env_quota_timer_cb

### ISSUE THREAD

**Issue by rtsisyk** [tarantool/tarantool#2681]
```
Current time: 1502522013
Please file a bug at http://github.com/tarantool/tarantool/issues
Attempting backtrace... Note: since the server has already crashed,
this may fail as well
#0  0x1040fdbd7 in print_backtrace+9
#1  0x10406c518 in _ZL12sig_fatal_cbi+ad
#2  0x7fffb6023b3a in _sigtramp+1a
#3  0x10419ebe5 in histogram_percentile+5
#4  0x10408d52d in vy_env_quota_timer_cb+31
#5  0x1041cdc71 in ev_invoke_pending+5f
#6  0x1041ce2bb in ev_run+62b
#7  0x10406bfa4 in main+339
GitHub
tarantool/tarantool
tarantool - Get your data in RAM. Get compute close to data. Enjoy the performance.
```

logs:
```
10:15:26 storage3.1 | 2017-08-12 10:15:26.150 [46146] wal/101/main F> LSN for 0 is used twice or COMMIT order is broken: confirmed: 0, new: 0
10:15:26 storage3.1 | 2017-08-12 10:15:26.150 [46146] wal/101/main fiber.c:1018 !> cord_join error 11: No such file or directory
```

**Comment by rtsisyk** [comment]
Segfault at exit is fixed by #2686 
"Commit order" problem is move to #2682  which has a reproducible test case.
