### ISSUE TITLE
vinyl: latch_destroy: Assertion `l->owner == NULL' failed

### ISSUE THREAD

**Issue by rtsisyk** [tarantool/tarantool#2686]
```
Starting instance...
Run console at unix/:/home/r.tsisyk/1.7/test/var/001_vinyl/join_quota.control
started
mkdir /home/r.tsisyk/1.7/test/var/001_vinyl/join_quota
2017-08-14 23:13:53.349 [25679] main/101/join_quota C> version 1.7.4-417-g362559e
2017-08-14 23:13:53.350 [25679] main/101/join_quota C> log level 5
2017-08-14 23:13:53.350 [25679] main/101/join_quota I> mapping 268435456 bytes for memtx tuple arena...
2017-08-14 23:13:53.350 [25679] main/101/join_quota I> mapping 4194304 bytes for vinyl tuple arena...
2017-08-14 23:13:53.358 [25679] iproto/101/main I> binary: bound to [::1]:38080
2017-08-14 23:13:53.360 [25679] main/105/applier/localhost:38129 I> remote master is 1.7.4 at [::1]:38129

2017-08-14 23:13:53.360 [25679] main/105/applier/localhost:38129 I> authenticated
2017-08-14 23:13:53.360 [25679] main/101/join_quota I> bootstrapping replica from [::1]:38129
2017-08-14 23:13:53.407 [25679] main/103/vinyl.scheduler I> 536/0: dump started
2017-08-14 23:13:53.434 [25679] main/103/vinyl.scheduler I> 536/0: dump completed
2017-08-14 23:13:53.436 [25679] main/105/applier/localhost:38129 I> initial data received
2017-08-14 23:13:53.454 [25679] main/103/vinyl.scheduler I> 536/0: dump started
2017-08-14 23:13:53.479 [25679] main/103/vinyl.scheduler I> 536/0: dump completed
2017-08-14 23:13:53.481 [25679] main/105/applier/localhost:38129 I> final data received
2017-08-14 23:13:53.485 [25679] main/103/vinyl.scheduler I> 536/0: started compacting range (-inf..inf), runs 2/2
2017-08-14 23:13:53.486 [25679] main/103/vinyl.scheduler I> 536/0: dump started
2017-08-14 23:13:53.487 [25679] snapshot/101/main I> saving snapshot `/home/r.tsisyk/1.7/test/var/001_vinyl/join_quota/00000000000000007189.snap.inprogress'
2017-08-14 23:13:53.488 [25679] snapshot/101/main I> done
2017-08-14 23:13:53.493 [25679] main/103/vinyl.scheduler I> 536/0: dump completed
2017-08-14 23:13:53.494 [25679] main/101/join_quota I> vinyl checkpoint done
2017-08-14 23:13:53.494 [25679] main/101/join_quota I> ready to accept requests
2017-08-14 23:13:53.494 [25679] main/106/checkpoint_daemon I> started
2017-08-14 23:13:53.494 [25679] main/106/checkpoint_daemon I> scheduled the next snapshot at Tue Aug 15 01:05:18 2017
2017-08-14 23:13:53.495 [25679] main/107/console/::1:38795 I> started
2017-08-14 23:13:53.495 [25679] main C> entering the event loop
2017-08-14 23:13:53.533 [25679] main C> got signal 15 - Terminated
tarantool: /home/r.tsisyk/1.7/src/latch.h:81: latch_destroy: Assertion `l->owner == NULL' failed.
```

```
(gdb) bt
#0  0x00007f8237aac428 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
#1  0x00007f8237aae02a in __GI_abort () at abort.c:89
#2  0x00007f8237aa4bd7 in __assert_fail_base (fmt=<optimized out>, assertion=assertion@entry=0x68019f "l->owner == NULL", 
    file=file@entry=0x680180 "/home/r.tsisyk/1.7/src/latch.h", line=line@entry=81, 
    function=function@entry=0x680d98 <__PRETTY_FUNCTION__.10547> "latch_destroy") at assert.c:92
#3  0x00007f8237aa4c82 in __GI___assert_fail (assertion=0x68019f "l->owner == NULL", file=0x680180 "/home/r.tsisyk/1.7/src/latch.h", line=81, 
    function=0x680d98 <__PRETTY_FUNCTION__.10547> "latch_destroy") at assert.c:101
#4  0x0000000000483774 in latch_destroy (l=0x9c1130 <vy_log+4752>) at /home/r.tsisyk/1.7/src/latch.h:81
#5  0x0000000000486114 in vy_log_free () at /home/r.tsisyk/1.7/src/box/vy_log.c:793
#6  0x0000000000445b49 in vy_env_delete (e=0x27a5ce0) at /home/r.tsisyk/1.7/src/box/vinyl.c:3924
#7  0x0000000000434dbd in VinylEngine::~VinylEngine (this=0x27997f0, __in_chrg=<optimized out>) at /home/r.tsisyk/1.7/src/box/vinyl_engine.cc:69
#8  0x0000000000434df8 in VinylEngine::~VinylEngine (this=0x27997f0, __in_chrg=<optimized out>) at /home/r.tsisyk/1.7/src/box/vinyl_engine.cc:70
#9  0x0000000000429361 in engine_shutdown () at /home/r.tsisyk/1.7/src/box/engine.cc:299
#10 0x00000000004a47d8 in box_free () at /home/r.tsisyk/1.7/src/box/box.cc:1221
#11 0x000000000040c847 in tarantool_free () at /home/r.tsisyk/1.7/src/main.cc:467
#12 0x00007f8237ab0ff8 in __run_exit_handlers (status=0, listp=0x7f8237e3a5f8 <__exit_funcs>, run_list_atexit=run_list_atexit@entry=true)
    at exit.c:82
#13 0x00007f8237ab1045 in __GI_exit (status=<optimized out>) at exit.c:104
#14 0x00007f8237a97837 in __libc_start_main (main=0x40c92e <main(int, char**)>, argc=4, argv=0x7ffd120d4768, init=<optimized out>, 
    fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7ffd120d4758) at ../csu/libc-start.c:325
#15 0x000000000040b569 in _start ()
```

**Comment by rtsisyk** [comment]
Coredump - https://cloud.mail.ru/public/KGBr/TmAFkU2Az

**Comment by rtsisyk** [comment]
1.7.4-422-gfa7597189
