### ISSUE TITLE
ER_UNKNOWN_REQUEST_TYPE on bootstrapping replica

### ISSUE THREAD

**Issue by ivankosenko** [tarantool/tarantool#2726]
Replication stopped after bootstrapping in some cases. Reproducing isn't stable in synthetic test, but it very stable on my production environment.

These scripts seem to allow you to reproduce the problem with a fairly high probability.

```lua
-- master
box.cfg{
    listen = '127.0.0.1:53301',
}

box.schema.user.passwd('admin', 'admin')
box.schema.create_space('ballast')
box.space.ballast:create_index('primary',{parts={1,'unsigned'}})
for i=1, 150000 do box.space.ballast:insert{i} end
```

```lua
-- slave
box.cfg{
    replication = 'admin:admin@127.0.0.1:53301',
}
```

On my machine these scripts produce the following output.
```
MASTER

tarantool> box.cfg{
         >     listen = '127.0.0.1:53301',
         > }
2017-08-30 19:46:49.481 [1] main/101/interactive I> systemd: NOTIFY_SOCKET variable is empty, skipping
2017-08-30 19:46:49.481 [1] main/101/interactive C> version 1.7.5-0-g24b70de
2017-08-30 19:46:49.481 [1] main/101/interactive C> log level 5
2017-08-30 19:46:49.481 [1] main/101/interactive I> mapping 268435456 bytes for memtx tuple arena...
2017-08-30 19:46:49.482 [1] main/101/interactive I> mapping 134217728 bytes for vinyl tuple arena...
2017-08-30 19:46:49.486 [1] iproto/101/main I> binary: bound to 127.0.0.1:53301
2017-08-30 19:46:49.487 [1] main/101/interactive I> initializing an empty data directory
2017-08-30 19:46:49.495 [1] main/101/interactive xlog.c:1765 E> can't open tx: bootstrap: has some data after eof marker at 1210
2017-08-30 19:46:49.500 [1] snapshot/101/main I> saving snapshot `./00000000000000000000.snap.inprogress'
2017-08-30 19:46:49.503 [1] snapshot/101/main I> done
2017-08-30 19:46:49.690 [1] main/101/interactive I> vinyl checkpoint done
2017-08-30 19:46:49.691 [1] main/101/interactive I> ready to accept requests
2017-08-30 19:46:49.691 [1] main/104/checkpoint_daemon I> started
2017-08-30 19:46:49.691 [1] main/104/checkpoint_daemon I> scheduled the next snapshot at Wed Aug 30 21:06:24 2017
---
...

tarantool> box.schema.user.passwd('admin', 'admin')
---
...

tarantool> box.schema.create_space('ballast')
---
- index: []
  on_replace: 'function: 0x407a2030'
  temporary: false
  id: 512
  engine: memtx
  enabled: false
  name: ballast
  field_count: 0
- created
...

tarantool> box.space.ballast:create_index('primary',{parts={1,'unsigned'}})
---
- unique: true
  parts:
  - type: unsigned
    fieldno: 1
  id: 0
  space_id: 512
  name: primary
  type: TREE
...

tarantool> for i=1, 150000 do box.space.ballast:insert{i} end
---
...

tarantool> 2017-08-30 19:47:06.981 [1] main/105/main I> initial data sent.
2017-08-30 19:47:06.981 [1] relay/127.0.0.1:42994/101/main I> recover from `./00000000000000000000.xlog'
2017-08-30 19:47:07.890 [1] relay/127.0.0.1:42994/101/main I> 0.1M rows processed
2017-08-30 19:47:08.330 [1] main/105/main I> final data sent.
2017-08-30 19:47:08.330 [1] iproto iproto.cc:665 E> ER_UNKNOWN_REQUEST_TYPE: Unknown request type 0
2017-08-30 19:47:08.594 [1] relay_0x7f466543ee80/101/main I> recover from `./00000000000000000000.xlog'
2017-08-30 19:47:08.635 [1] relay_0x7f466543ee80/101/main I> done `./00000000000000000000.xlog'
2017-08-30 19:47:08.635 [1] relay/<unknown>/101/main C> exiting the relay loop
2017-08-30 19:47:08.635 [1] main/105/main coio.cc:369 !> SystemError unexpected EOF when reading from socket, called on fd 16, aka 127.0.0.1:53301: Broken pipe
```

```
SLAVE

tarantool> box.cfg{
         >     replication = 'admin:admin@127.0.0.1:53301',
         > }
2017-08-30 19:47:06.972 [1] main/101/interactive I> systemd: NOTIFY_SOCKET variable is empty, skipping
2017-08-30 19:47:06.973 [1] main/101/interactive C> version 1.7.5-0-g24b70de
2017-08-30 19:47:06.973 [1] main/101/interactive C> log level 5
2017-08-30 19:47:06.973 [1] main/101/interactive I> mapping 268435456 bytes for memtx tuple arena...
2017-08-30 19:47:06.973 [1] main/101/interactive I> mapping 134217728 bytes for vinyl tuple arena...
2017-08-30 19:47:06.977 [1] main/104/applier/admin@127.0.0.1:53301 I> remote master is 1.7.5 at 127.0.0.1:53301

2017-08-30 19:47:06.978 [1] main/104/applier/admin@127.0.0.1:53301 I> authenticated
2017-08-30 19:47:06.978 [1] main/101/interactive I> bootstrapping replica from 127.0.0.1:53301
2017-08-30 19:47:06.986 [1] main/104/applier/admin@127.0.0.1:53301 I> initial data received
2017-08-30 19:47:08.330 [1] main/104/applier/admin@127.0.0.1:53301 I> final data received
2017-08-30 19:47:08.335 [1] snapshot/101/main I> saving snapshot `./00000000000000150005.snap.inprogress'
2017-08-30 19:47:08.368 [1] snapshot/101/main C> 0.1M rows written
2017-08-30 19:47:08.384 [1] snapshot/101/main I> done
2017-08-30 19:47:08.446 [1] main/101/interactive I> vinyl checkpoint done
2017-08-30 19:47:08.447 [1] main/101/interactive I> ready to accept requests
2017-08-30 19:47:08.447 [1] main/106/checkpoint_daemon I> started
2017-08-30 19:47:08.447 [1] main/106/checkpoint_daemon I> scheduled the next snapshot at Wed Aug 30 21:14:14 2017
2017-08-30 19:47:08.447 [1] main/104/applier/admin@127.0.0.1:53301 I> can't read row
2017-08-30 19:47:08.447 [1] main/104/applier/admin@127.0.0.1:53301 xrow.c:748 E> ER_UNKNOWN_REQUEST_TYPE: Unknown request type 0
---
...

tarantool> box.info
---
- version: 1.7.5-0-g24b70de
  id: 2
  ro: false
  vclock: {1: 150005}
  uptime: 129
  lsn: 0
  vinyl: []
  cluster:
    uuid: 2987e8ac-91df-46ae-a9a2-75297c5f3afa
  pid: 1
  status: running
  signature: 150005
  replication:
    1:
      id: 1
      uuid: 710de7cf-550e-4445-9cdc-6a28578266cc
      lsn: 150005
      upstream:
        status: stopped
        idle: 127.38452935219
        message: Unknown request type 0
        lag: 0
    2:
      id: 2
      uuid: c49c61ca-f514-4999-8ee8-202495e93fe4
      lsn: 0
  uuid: c49c61ca-f514-4999-8ee8-202495e93fe4
...
```

**Comment by ivankosenko** [comment]
I ran the program under gdb and put a breakpoint in the function xrow_decode_error to locate error.

This is backtrace I received:
```#0  xrow_decode_error (row=0x7fffee46fe70) at /srv/tarantool-dev/src/box/xrow.c:714
#1  0x00000000004c1f85 in xrow_decode_error_xc (row=0x7fffee46fe70) at /srv/tarantool-dev/src/box/xrow.h:440
#2  0x00000000004c37ad in applier_subscribe (applier=0xa738f0) at /srv/tarantool-dev/src/box/applier.cc:376
#3  0x00000000004c3c54 in applier_f(typedef __va_list_tag __va_list_tag *) (ap=0x7fffee400540) at /srv/tarantool-dev/src/box/applier.cc:475
#4  0x000000000040bcbe in fiber_cxx_invoke(fiber_func, typedef __va_list_tag __va_list_tag *) (f=0x4c3bb1 <applier_f(typedef __va_list_tag __va_list_tag *)>, ap=0x7fffee400540) at /srv/tarantool-dev/src/fiber.h:665
#5  0x00000000004f5aad in fiber_loop (data=0x0) at /srv/tarantool-dev/src/fiber.c:631
#6  0x000000000068d36b in coro_init () at /srv/tarantool-dev/third_party/coro/coro.c:110```

**Comment by ivankosenko** [comment]
I captured traffic from replica to master and decrypted it. Here's the data:
```
[{code: 7 /* auth */}, {33: ['chap-sha1', '\x8a\xf5s&P\x92#(\xf2iE\xdf\x7fr\xd6\xf1;\xce\xeb\x80'], 35: 'admin'}]
[{code: 65 /* join */}, {36: '68791395-e830-470e-9eeb-05454d955fe9'}]
[{code: 0}, {38: {1: 31499}}] // VCLOCK
[{code: 0}, {38: {1: 62729}}] // VCLOCK
[{code: 0}, {38: {1: 93978}}] // VCLOCK
[{code: 0}, {38: {1: 124863}}] // VCLOCK
[{code: 66 /* subscribe */}, {6: 67333, 36: '68791395-e830-470e-9eeb-05454d955fe9', 37: 'db4c7ef9-b3be-4c44-8c5b-e16b9a287521', 38: {1: 150005}}]
```
As I understand, master did not expect packets with vclock at this stage but they came and caused the error.

**Comment by ivankosenko** [comment]
this is backtrace which send vclock packet
```
#0  coio_write_xrow (coio=0x7fffee43fef0, row=0x7fffee43fea0) at /srv/tarantool-dev/src/box/xrow_io.cc:100
#1  0x00000000004c2615 in applier_writer_f(typedef __va_list_tag __va_list_tag *) (ap=0x7fffee400410) at /srv/tarantool-dev/src/box/applier.cc:121
#2  0x000000000040bcbe in fiber_cxx_invoke(fiber_func, typedef __va_list_tag __va_list_tag *) (f=0x4c2517 <applier_writer_f(typedef __va_list_tag __va_list_tag *)>, ap=0x7fffee400410) at /srv/tarantool-dev/src/fiber.h:665
#3  0x00000000004f5ab5 in fiber_loop (data=0x0) at /srv/tarantool-dev/src/fiber.c:631
#4  0x000000000068d37b in coro_init () at /srv/tarantool-dev/third_party/coro/coro.c:110
```

**Comment by ivankosenko** [comment]
this is backtrace from master, when unexpected command received
```#0  diag_add_error (diag=0x9e2b80 <iproto_init()::net_cord+1152>, e=0x7fffd0001218) at /srv/tarantool-dev/src/diag.h:172
#1  0x0000000000410052 in iproto_decode_msg (msg=0x7fffee008210, pos=0x7fffd5fe4a68, reqend=0x7fffee02006f <incomplete sequence \316>, stop_input=0x7fffd5fe4a76) at /srv/tarantool-dev/src/box/iproto.cc:713
#2  0x000000000041031c in iproto_enqueue_batch (con=0x7fffee040100, in=0x7fffee040100) at /srv/tarantool-dev/src/box/iproto.cc:749
#3  0x00000000004107c3 in iproto_connection_on_input (loop=0xa725b0, watcher=0x7fffee040888) at /srv/tarantool-dev/src/box/iproto.cc:877
#4  0x000000000068312a in ev_invoke_pending (loop=0xa725b0) at /srv/tarantool-dev/third_party/libev/ev.c:3347
#5  0x0000000000684019 in ev_run (loop=0xa725b0, flags=0) at /srv/tarantool-dev/third_party/libev/ev.c:3750
#6  0x00000000004f76f1 in cord_costart_thread_func (arg=0xa63080) at /srv/tarantool-dev/src/fiber.c:1157
#7  0x00000000004f6a2a in cord_thread_func (p=0x7fffee41f9d0) at /srv/tarantool-dev/src/fiber.c:958
#8  0x00007ffff66c66ba in start_thread (arg=0x7fffd5fff700) at pthread_create.c:333
#9  0x00007ffff54ff3dd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
```

**Comment by rtsisyk** [comment]
1.7.5-281-g0a0731f4d

**Comment by ivankosenko** [comment]
unfortunately the problem is still reproduced in build 1.7.6-0-g7b2945d

**Comment by rtsisyk** [comment]
1.7.6-6-ge4bcc2ba9

**Comment by ivankosenko** [comment]
I confirm. The problem is not reproduced in 1.7.6-6-ge4bcc2ba9
