### ISSUE TITLE
http.client hangs at an empty POST request

### ISSUE THREAD

**Issue by Totktonada** [tarantool/tarantool#2734]
Steps to reproduce:

```
tarantool> require('http.client').new():post('https://jsonplaceholder.typicode.com/posts')
… hangs …
tarantool> require('http.client').new():post('https://jsonplaceholder.typicode.com/posts', '')
… hangs ...
tarantool> require('http.client').new():post('https://jsonplaceholder.typicode.com/posts', '\n')
… works …
```

Additional info:

```
$ strace tarantool <(echo "require('http.client').new():post('https://jsonplaceholder.typicode.com/posts')")
…
read(0,
```

```
0x00007f48b4ee2580 in __read_nocancel () from /lib64/libc.so.6
(gdb) bt
#0  0x00007f48b4ee2580 in __read_nocancel () from /lib64/libc.so.6
#1  0x00007f48b4e7a4d0 in __GI__IO_file_xsgetn () from /lib64/libc.so.6
#2  0x00007f48b4e6ec2d in fread () from /lib64/libc.so.6
#3  0x00007f48b631f9c3 in ?? () from /usr/lib64/libcurl.so.4
#4  0x00007f48b6320173 in ?? () from /usr/lib64/libcurl.so.4
#5  0x00007f48b6329ee9 in ?? () from /usr/lib64/libcurl.so.4
#6  0x00007f48b632ab3c in ?? () from /usr/lib64/libcurl.so.4
#7  0x00007f48b632ad77 in curl_multi_socket_action () from /usr/lib64/libcurl.so.4
#8  0x00000000004e3b64 in curl_multi_process (multi=0x20dbdd0, sockfd=6, events=2) at /usr/src/debug/dev-db/tarantool-1.7.4.175/tarantool-1.7.4.175/src/httpc.c:61
#9  0x00000000004e3f28 in curl_sock_cb (loop=0x9367e0 <default_loop_struct>, watcher=0x7f48b400c070, revents=2)
    at /usr/src/debug/dev-db/tarantool-1.7.4.175/tarantool-1.7.4.175/src/httpc.c:168
#10 0x00000000005ad0a3 in ev_invoke_pending (loop=0x9367e0 <default_loop_struct>) at /usr/src/debug/dev-db/tarantool-1.7.4.175/tarantool-1.7.4.175/third_party/libev/ev.c:3176
#11 0x00000000005adf8f in ev_run (loop=0x9367e0 <default_loop_struct>, flags=0) at /usr/src/debug/dev-db/tarantool-1.7.4.175/tarantool-1.7.4.175/third_party/libev/ev.c:3576
#12 0x00000000004f84c7 in tarantool_lua_run_script (path=0x20ade30 "/dev/fd/63", argc=1, argv=0x20afd08) at /usr/src/debug/dev-db/tarantool-1.7.4.175/tarantool-1.7.4.175/src/lua/init.c:531
#13 0x000000000040dbbf in main (argc=1, argv=0x20afd08) at /usr/src/debug/dev-db/tarantool-1.7.4.175/tarantool-1.7.4.175/src/main.cc:635
(gdb) frame 8
#8  0x00000000004e3b64 in curl_multi_process (multi=0x20dbdd0, sockfd=6, events=2) at /usr/src/debug/dev-db/tarantool-1.7.4.175/tarantool-1.7.4.175/src/httpc.c:61
61			code = curl_multi_socket_action(multi, sockfd, events,
(gdb) list
56		 * You don't have to do it immediately, but the return code means that
57		 * libcurl may have more data available to return or that there may be
58		 * more data to send off before it is "satisfied".
59		 */
60		do {
61			code = curl_multi_socket_action(multi, sockfd, events,
62							&still_running);
63		} while (code == CURLM_CALL_MULTI_PERFORM);
64		if (code != CURLM_OK) {
65			/* Sic: we can't handle errors properly in EV callbacks */
```

```
$ curl --version
curl 7.53.1 (x86_64-pc-linux-gnu) libcurl/7.53.1 OpenSSL/1.0.2k zlib/1.2.11
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp smtp smtps telnet tftp 
Features: IPv6 Largefile NTLM SSL libz TLS-SRP UnixSockets HTTPS-proxy 
```

**Comment by Totktonada** [comment]
Looks similar to #2530, but appears on an actual version of http.client.

**Comment by GeorgyKirichenko** [comment]
works on 1.7.5-165-ge3d97f6d1
