### ISSUE TITLE
vinyl: segfault in vy_run_iterator_read

### ISSUE THREAD

**Issue by rtsisyk** [tarantool/tarantool#2784]
1. Download [tnt_vetis.7z](https://yadi.sk/d/_zFTLHnc3NFY2y) data directory
2. Run query:

```
box.space.stock_reserved.index.primary:select({}, {limit=100}) 
```

```
(gdb) bt
#0  __memmove_avx_unaligned_erms () at ../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S:416
#1  0x00005555555b0dd2 in vy_stmt_new_surrogate_from_key (key=<optimized out>, type=type@entry=IPROTO_DELETE,
    cmp_def=cmp_def@entry=0x555555b4d9b0, format=format@entry=0x555555eaadf0)
    at /work/tarantool/1.7/src/box/vy_stmt.c:402
#2  0x00005555555b2704 in vy_stmt_decode (xrow=xrow@entry=0x7f14b781f8e0, key_def=key_def@entry=0x555555b4d9b0,
    format=format@entry=0x555555eaadf0, upsert_format=upsert_format@entry=0x555556007f10,
    is_primary=is_primary@entry=true) at /work/tarantool/1.7/src/box/vy_stmt.c:569
#3  0x00005555555c1f3e in vy_page_stmt (page=<optimized out>, stmt_no=<optimized out>, cmp_def=0x555555b4d9b0,
    format=0x555555eaadf0, upsert_format=0x555556007f10, is_primary=<optimized out>)
    at /work/tarantool/1.7/src/box/vy_run.c:738
#4  0x00005555555c2d84 in vy_run_iterator_read (itr=itr@entry=0x555555b501e0, pos=..., stmt=stmt@entry=0x7f14b781f9e8)
    at /work/tarantool/1.7/src/box/vy_run.c:1075
#5  0x00005555555c45a5 in vy_run_iterator_find_lsn (itr=itr@entry=0x555555b501e0,
    iterator_type=iterator_type@entry=ITER_GE, key=0x555555be0560, ret=ret@entry=0x555555b50278)
    at /work/tarantool/1.7/src/box/vy_run.c:1225
#6  0x00005555555c507b in vy_run_iterator_start_from (ret=0x555555b50278, key=<optimized out>,
    iterator_type=<optimized out>, itr=0x555555b501e0) at /work/tarantool/1.7/src/box/vy_run.c:1427
#7  vy_run_iterator_start (ret=0x555555b50278, itr=0x555555b501e0) at /work/tarantool/1.7/src/box/vy_run.c:1494
#8  vy_run_iterator_next_key (vitr=0x555555b501e0, ret=0x555555b50278, stop=<optimized out>)
    at /work/tarantool/1.7/src/box/vy_run.c:1596
#9  0x00005555555d8922 in vy_merge_iterator_next_key (itr=itr@entry=0x7f14b79201e8, ret=ret@entry=0x7f14b781fbc8)
    at /work/tarantool/1.7/src/box/vy_read_iterator.c:264
#10 0x00005555555d92c8 in vy_read_iterator_merge_next_key (ret=<optimized out>, itr=<optimized out>)
    at /work/tarantool/1.7/src/box/vy_read_iterator.c:737
#11 vy_read_iterator_next (itr=itr@entry=0x7f14b7920190, result=result@entry=0x7f14b781fc58)
    at /work/tarantool/1.7/src/box/vy_read_iterator.c:832
#12 0x00005555555b0315 in vy_cursor_next (env=env@entry=0x555555b49be0, c=0x7f14b79200e0,
    result=result@entry=0x7f14b781fca8) at /work/tarantool/1.7/src/box/vinyl.c:4955
#13 0x00005555555a2b04 in iterator_next (base_it=0x555555b4ce30) at /work/tarantool/1.7/src/box/vinyl_index.cc:165
#14 0x00005555555992ee in Handler::executeSelect (this=<optimized out>, space=<optimized out>,
    index_id=<optimized out>, iterator=<optimize
```

Reported by Alex Sem @alps1 from tarantool-ru && Telegram Chat.

**Comment by locker** [comment]
Fixed in 1.7.5-126-g223c6265
