### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by iGusev** [tarantool/tarantool#2791]
Tarantool 1.8.2-150-g9fe1e71

```
2017-09-29 10:02:53.491 [2915] main/35739/main txn.cc:211 W> too long WAL write: 1.461 sec
2017-09-29 10:02:53.492 [2915] main/35746/main txn.cc:211 W> too long WAL write: 1.461 sec
2017-09-29 10:02:53.492 [2915] main/35748/main txn.cc:211 W> too long WAL write: 1.461 sec
2017-09-29 10:02:53.492 [2915] main/35743/main txn.cc:211 W> too long WAL write: 1.461 sec
2017-09-29 10:02:53.492 [2915] main/32437/main txn.cc:211 W> too long WAL write: 1.461 sec
2017-09-29 10:02:53.492 [2915] main/35771/main txn.cc:211 W> too long WAL write: 1.461 sec
2017-09-29 10:02:53.492 [2915] main/35749/main txn.cc:211 W> too long WAL write: 1.461 sec
2017-09-29 10:02:53.492 [2915] main/35733/main txn.cc:211 W> too long WAL write: 1.461 sec
2017-09-29 10:02:54.636 [2915] main/35769/main txn.cc:211 W> too long WAL write: 0.717 sec
2017-09-29 10:02:54.636 [2915] main/35765/main txn.cc:211 W> too long WAL write: 0.717 sec
2017-09-29 10:02:55.935 [2915] main/35757/main txn.cc:211 W> too long WAL write: 0.905 sec
2017-09-29 10:02:55.935 [2915] main/35746/main txn.cc:211 W> too long WAL write: 0.905 sec
2017-09-29 10:02:55.935 [2915] main/32436/main txn.cc:211 W> too long WAL write: 0.905 sec
2017-09-29 10:02:55.935 [2915] main/35749/main txn.cc:211 W> too long WAL write: 0.905 sec
2017-09-29 10:02:55.935 [2915] main/35743/main txn.cc:211 W> too long WAL write: 0.905 sec
2017-09-29 10:02:55.935 [2915] main/35752/main txn.cc:211 W> too long WAL write: 0.905 sec
2017-09-29 10:02:55.935 [2915] main/35741/main txn.cc:211 W> too long WAL write: 0.905 sec
2017-09-29 10:02:55.935 [2915] main/35771/main txn.cc:211 W> too long WAL write: 0.905 sec
2017-09-29 10:02:55.935 [2915] main/35748/main txn.cc:211 W> too long WAL write: 0.905 sec
2017-09-29 10:02:55.935 [2915] main/35772/main txn.cc:211 W> too long WAL write: 0.905 sec
2017-09-29 10:02:56.791 [2915] main/35738/main txn.cc:211 W> too long WAL write: 0.836 sec
2017-09-29 10:02:56.791 [2915] main/35731/main txn.cc:211 W> too long WAL write: 0.836 sec
2017-09-29 10:02:57.590 [2915] main/35737/main txn.cc:211 W> too long WAL write: 0.531 sec
2017-09-29 10:02:57.590 [2915] main/35762/main txn.cc:211 W> too long WAL write: 0.531 sec
2017-09-29 10:02:57.590 [2915] main/35774/main txn.cc:211 W> too long WAL write: 0.531 sec
2017-09-29 10:02:57.590 [2915] main/35731/main txn.cc:211 W> too long WAL write: 0.531 sec
2017-09-29 10:02:57.590 [2915] main/35738/main txn.cc:211 W> too long WAL write: 0.531 sec
2017-09-29 10:02:57.590 [2915] main/35758/main txn.cc:211 W> too long WAL write: 0.531 sec
2017-09-29 10:02:57.590 [2915] main/35753/main txn.cc:211 W> too long WAL write: 0.531 sec
2017-09-29 10:02:57.590 [2915] main/32435/main txn.cc:211 W> too long WAL write: 0.531 sec
2017-09-29 10:02:57.590 [2915] main/35765/main txn.cc:211 W> too long WAL write: 0.531 sec
2017-09-29 10:02:57.590 [2915] main/35740/main txn.cc:211 W> too long WAL write: 0.531 sec
2017-09-29 10:02:57.590 [2915] main/35779/main txn.cc:211 W> too long WAL write: 0.531 sec
2017-09-29 10:02:57.590 [2915] main/32434/main txn.cc:211 W> too long WAL write: 0.531 sec
2017-09-29 10:02:58.185 [2915] main/35769/main txn.cc:211 W> too long WAL write: 0.667 sec
2017-09-29 10:02:58.185 [2915] main/35734/main txn.cc:211 W> too long WAL write: 0.667 sec
2017-09-29 10:02:58.185 [2915] main/35777/main txn.cc:211 W> too long WAL write: 0.667 sec
2017-09-29 10:02:58.185 [2915] main/35744/main txn.cc:211 W> too long WAL write: 0.667 sec
2017-09-29 10:02:58.185 [2915] main/35751/main txn.cc:211 W> too long WAL write: 0.667 sec
Segmentation fault
Current time: 1506679378
Please file a bug at http://github.com/tarantool/tarantool/issues
Attempting backtrace... Note: since the server has already crashed,
this may fail as well
#0  0x4eed29 in print_backtrace+9
#1  0x412181 in _ZL12sig_fatal_cbi+81
#2  0x7f036507f330 in __restore_rt+0
#3  0x5d81c3 in matras_touch+73
#4  0x47bda9 in bps_tree_vy_cache_tree_move_elems_to_right_leaf+39
#5  0x7eff83a2fc40 in +39
```

```
Linux 3.13.0-74-generic #118-Ubuntu SMP Thu Dec 17 22:52:10 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by alyapunov** [comment]
Could you please upload logs for at least 30 minutes?
Information about engines, spaces and indexes also could help.

**Comment by kostja** [comment]
We will not be able to fix it without feedback.
