### ISSUE TITLE
box.schema.func.reload crash

### ISSUE THREAD

**Issue by tonyfreeman** [tarantool/tarantool#2816]
`box.schema.func.reload()` - crash even without any modules/functions
`box.schema.func.reload('function1_module')` - crash
`box.schema.func.reload('function1')` - ok

Tarantool 1.7.5-169-g5a03f36
```bash
tarantool> box.schema.func.reload('function1_module')
Segmentation fault
Current time: 1507633751
Please file a bug at http://github.com/tarantool/tarantool/issues
Attempting backtrace... Note: since the server has already crashed,
this may fail as well
#0  0x4e0109 in print_backtrace+9
#1  0x40ea51 in _ZL12sig_fatal_cbi+81
#2  0x7fb0d8f6b390 in __restore_rt+0
#3  0x4bd470 in box_func_reload+1f0
#4  0x4bf2a5 in lbox_func_reload+25
#5  0x4f5a97 in lj_BC_FUNCC+34
#6  0x507044 in lua_pcall+34
#7  0x4d22c3 in luaT_call+13
#8  0x4cc9b9 in lua_main+59
#9  0x4ccbbc in run_script_f+19c
#10 0x40e55c in _ZL16fiber_cxx_invokePFiP13__va_list_tagES0_+c
#11 0x4dda50 in fiber_loop+30
#12 0x5dffef in coro_init+3f
#13 (nil) in +3f
Aborted
```

**Comment by locker** [comment]
Fixed in 1.7.5-277-gd02f0281
