### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by ja1cap** [tarantool/tarantool#2831]
```
geonames_tarantool_1  | Segmentation fault
geonames_tarantool_1  | Current time: 1508008895
geonames_tarantool_1  | Please file a bug at http://github.com/tarantool/tarantool/issues
geonames_tarantool_1  | Attempting backtrace... Note: since the server has already crashed,
geonames_tarantool_1  | this may fail as well
geonames_tarantool_1  | #0  0x4e6479 in print_backtrace+9
geonames_tarantool_1  | #1  0x40f351 in _ZL12sig_fatal_cbi+81
geonames_tarantool_1  | #2  0x7ff819b7b5e0 in _L_unlock_13+34
geonames_tarantool_1  | #3  0x5d61f4 in matras_touch+74
geonames_tarantool_1  | #4  0x475106 in bps_tree_vy_cache_tree_move_elems_to_left_leaf+36
geonames_tarantool_1  | #5  0x7ff814c1fd40 in +36
```

**Comment by rtsisyk** [comment]
Hi, do you a Lua script which reproduces this crash?

**Comment by rtsisyk** [comment]
Can't reproduce.
