### ISSUE TITLE
vinyl: crash in read iterator

### ISSUE THREAD

**Issue by locker** [tarantool/tarantool#2926]
Branch 1.7-next, commit 8c48aa47ef2c240e28407821d40f98c455c16829, debug build.

`vinyl/select_consistency.test.lua` seldom crashes while trying to restore the iterator over the active in-memory tree after a yield:
```
tarantool: /home/vlad/src/tarantool/src/box/vy_read_iterator.c:421: vy_read_iterator_restore_mem: Assertion `itr->curr_src == itr->txw_src' failed.
```
A quick glance at the core dump shows that right before the crash the read iterator was positioned at a statement stored in the cache; the statement was prepared, but not committed (its lsn > MAX_LSN):
```
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007fd2c9ce43fa in __GI_abort () at abort.c:89
#2  0x00007fd2c9cdbe37 in __assert_fail_base (fmt=<optimized out>, assertion=assertion@entry=0x55a7c2110a65 "itr->curr_src == itr->txw_src",
    file=file@entry=0x55a7c2110920 "/home/vlad/src/tarantool/src/box/vy_read_iterator.c", line=line@entry=421,
    function=function@entry=0x55a7c2110e10 <__PRETTY_FUNCTION__.14317> "vy_read_iterator_restore_mem") at assert.c:92
#3  0x00007fd2c9cdbee2 in __GI___assert_fail (assertion=0x55a7c2110a65 "itr->curr_src == itr->txw_src",
    file=0x55a7c2110920 "/home/vlad/src/tarantool/src/box/vy_read_iterator.c", line=421,
    function=0x55a7c2110e10 <__PRETTY_FUNCTION__.14317> "vy_read_iterator_restore_mem") at assert.c:101
#4  0x000055a7c1ed39ec in vy_read_iterator_restore_mem (itr=0x7fd2c34e01d8) at /home/vlad/src/tarantool/src/box/vy_read_iterator.c:421
#5  0x000055a7c1ed3ca9 in vy_read_iterator_next_key (itr=0x7fd2c34e01d8, ret=0x7fd2c341fc58) at /home/vlad/src/tarantool/src/box/vy_read_iterator.c:521
#6  0x000055a7c1ed4ff9 in vy_read_iterator_next (itr=0x7fd2c34e01d8, result=0x7fd2c341fce0) at /home/vlad/src/tarantool/src/box/vy_read_iterator.c:999
#7  0x000055a7c1ea1b73 in vinyl_iterator_next (base=0x7fd2c34e0190, ret=0x7fd2c341fd68) at /home/vlad/src/tarantool/src/box/vinyl.c:3856
#8  0x000055a7c1e77706 in iterator_next (it=0x7fd2c34e0190, ret=0x7fd2c341fd68) at /home/vlad/src/tarantool/src/box/index.cc:456
#9  0x000055a7c1f13e27 in box_select (port=0x7fd2c341fdf0, space_id=537, index_id=1, iterator=0, offset=0, limit=4294967295, key=0x7fd25e8bf0e9 "\b\r%n§U",
    key_end=0x7fd25e8bf0ea "\r%n§U") at /home/vlad/src/tarantool/src/box/box.cc:824
#10 0x000055a7c1f387e4 in lbox_select (L=0x410dbf50) at /home/vlad/src/tarantool/src/box/lua/misc.cc:94
#11 0x000055a7c1f7fd4b in lj_BC_FUNCC ()
#12 0x000055a7c1fa28c3 in lua_pcall (L=0x410dbf50, nargs=3, nresults=0, errfunc=0) at lj_api.c:1139
#13 0x000055a7c1f4ba72 in luaT_call (L=0x410dbf50, nargs=3, nreturns=0) at /home/vlad/src/tarantool/src/lua/utils.c:931
#14 0x000055a7c1f45163 in lua_fiber_run_f (ap=0x7fd2c34001b0) at /home/vlad/src/tarantool/src/lua/fiber.c:290
#15 0x000055a7c1e6b6f4 in fiber_cxx_invoke(fiber_func, typedef __va_list_tag __va_list_tag *) (f=0x55a7c1f450a3 <lua_fiber_run_f>, ap=0x7fd2c34001b0)
    at /home/vlad/src/tarantool/src/fiber.h:665
#16 0x000055a7c1f5cf9d in fiber_loop (data=0x0) at /home/vlad/src/tarantool/src/fiber.c:631
#17 0x000055a7c20fe99b in coro_init () at /home/vlad/src/tarantool/third_party/coro/coro.c:110
(gdb) frame 4
#4  0x000055a7c1ed39ec in vy_read_iterator_restore_mem (itr=0x7fd2c34e01d8) at /home/vlad/src/tarantool/src/box/vy_read_iterator.c:421
421                     assert(itr->curr_src == itr->txw_src);
(gdb) p itr->curr_src
$1 = 1
(gdb) p itr->txw_src
$2 = 0
(gdb) p itr->cache_src
$3 = 1
(gdb) p *(struct vy_stmt *)itr->src[itr->cache_src].stmt
$4 = {base = {refs = 2, format_id = 146, bsize = 6, data_offset = 44}, lsn = 4611686018427697809, type = 3 '\003'}
(gdb) p *(struct vy_stmt *)itr->src[itr->mem_src].stmt
$5 = {base = {refs = 1, format_id = 146, bsize = 5, data_offset = 44}, lsn = 739866, type = 5 '\005'}
```
The current implementation of the read iterator doesn't expect that there can be uncommitted statements in the cache so if the statement inserted into the active in-memory tree equals to the current statement by key and is older, then it reckons it must be a txw statement the iterator is positioned at (as there could not be a cache statement committed before the yield which is newer than the statement inserted after the yield) hence the assertion.

There doesn't seem to be much sense in keeping uncommitted statements in the cache as we invalidate the cache after committing a statement anyway (see `vy_index_commit_stmt()`). Actually, we invalidate the cache before preparing a statement as well (see `vy_tx_write()`) - what a mess! So a quick fix would be to make `vy_cache_add()` ignore uncommitted statements; it would also allow us to remove cache invalidation from `vy_index_commit_stmt()`.

Link to travis ci test failure: https://travis-ci.org/tarantool/tarantool/jobs/303618524#L2695

**Comment by rtsisyk** [comment]
44b4d7ec13716133b38c103fb52db0f98ddae726
