### ISSUE TITLE
vinyl: assertion failure in vy_read_iterator_evaluate_src

### ISSUE THREAD

**Issue by locker** [tarantool/tarantool#3003]
Branch 1.7-next, commit 33874b44a7a7a19c8a7070551daeef4e3ccf3374, debug build

Running the following script
```
box.cfg{log_level=4}
box.schema.space.create('test', {engine = 'vinyl'})
box.space.test:create_index('pk')
box.space.test:replace{1, 1}
box.snapshot()
box.space.test:upsert({1, 1}, {{'+', 2, 1}})
box.space.test:select({1}, 'GE')
```
results in an assertion failure:
```
2017-12-15 18:32:54.469 [6862] main/101/test.lua C> Tarantool 1.7.6-93-g33874b44
2017-12-15 18:32:54.469 [6862] main/101/test.lua C> log level 4
tarantool: /home/vlad/src/tarantool/src/box/vy_read_iterator.c:227: vy_read_iterator_evaluate_src: Assertion `vy_read_iterator_cmp_stmt(itr, src->stmt, itr->curr_stmt) < 0' failed.
```
Stack trace:
```
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007f59cfe653fa in __GI_abort () at abort.c:89
#2  0x00007f59cfe5ce37 in __assert_fail_base (fmt=<optimized out>, assertion=assertion@entry=0x55f3aceaa740 "vy_read_iterator_cmp_stmt(itr, src->stmt, itr->curr_stmt) < 0",
    file=file@entry=0x55f3aceaa6f8 "/home/vlad/src/tarantool/src/box/vy_read_iterator.c", line=line@entry=227, function=function@entry=0x55f3aceaab20 <__PRETTY_FUNCTION__.14280> "vy_read_iterator_evaluate_src") at assert.c:92
#3  0x00007f59cfe5cee2 in __GI___assert_fail (assertion=0x55f3aceaa740 "vy_read_iterator_cmp_stmt(itr, src->stmt, itr->curr_stmt) < 0", file=0x55f3aceaa6f8 "/home/vlad/src/tarantool/src/box/vy_read_iterator.c", line=227,
    function=0x55f3aceaab20 <__PRETTY_FUNCTION__.14280> "vy_read_iterator_evaluate_src") at assert.c:101
#4  0x000055f3acc6d22b in vy_read_iterator_evaluate_src (itr=0x7f59c98401c0, src=0x55f3af269c30, stop=0x7f59c981fb1f) at /home/vlad/src/tarantool/src/box/vy_read_iterator.c:226
#5  0x000055f3acc6d84b in vy_read_iterator_scan_disk (itr=0x7f59c98401c0, disk_src=3, stop=0x7f59c981fb1f) at /home/vlad/src/tarantool/src/box/vy_read_iterator.c:370
#6  0x000055f3acc6dff2 in vy_read_iterator_next_lsn (itr=0x7f59c98401c0, ret=0x7f59c981fb58) at /home/vlad/src/tarantool/src/box/vy_read_iterator.c:608
#7  0x000055f3acc6e1cf in vy_read_iterator_squash_upsert (itr=0x7f59c98401c0, ret=0x7f59c981fbd8) at /home/vlad/src/tarantool/src/box/vy_read_iterator.c:660
#8  0x000055f3acc6ef97 in vy_read_iterator_next (itr=0x7f59c98401c0, result=0x7f59c981fc60) at /home/vlad/src/tarantool/src/box/vy_read_iterator.c:1005
#9  0x000055f3acc3bab1 in vinyl_iterator_next (base=0x7f59c9840178, ret=0x7f59c981fce8) at /home/vlad/src/tarantool/src/box/vinyl.c:3846
#10 0x000055f3acc11746 in iterator_next (it=0x7f59c9840178, ret=0x7f59c981fce8) at /home/vlad/src/tarantool/src/box/index.cc:456
#11 0x000055f3accadd12 in box_select (port=0x7f59c981fd70, space_id=512, index_id=0, iterator=5, offset=0, limit=4294967295, key=0x7f59c990a039 "\001\220\311Y\177", key_end=0x7f59c990a03a "\220\311Y\177")
    at /home/vlad/src/tarantool/src/box/box.cc:843
#12 0x000055f3accd2c51 in lbox_select (L=0x40479378) at /home/vlad/src/tarantool/src/box/lua/misc.cc:94
#13 0x000055f3acd1a18b in lj_BC_FUNCC ()
#14 0x000055f3acd3cd03 in lua_pcall (L=0x40479378, nargs=0, nresults=0, errfunc=0) at lj_api.c:1139
#15 0x000055f3acce5f42 in luaT_call (L=0x40479378, nargs=0, nreturns=0) at /home/vlad/src/tarantool/src/lua/utils.c:931
#16 0x000055f3accddd66 in lua_main (L=0x40479378, argc=1, argv=0x55f3af2171f8) at /home/vlad/src/tarantool/src/lua/init.c:490
#17 0x000055f3accde3fc in run_script_f (ap=0x7f59c98001b0) at /home/vlad/src/tarantool/src/lua/init.c:564
#18 0x000055f3acc05944 in fiber_cxx_invoke(fiber_func, typedef __va_list_tag __va_list_tag *) (f=0x55f3accdddef <run_script_f>, ap=0x7f59c98001b0) at /home/vlad/src/tarantool/src/fiber.h:665
#19 0x000055f3accf73d7 in fiber_loop (data=0x0) at /home/vlad/src/tarantool/src/fiber.c:631
#20 0x000055f3ace989eb in coro_init () at /home/vlad/src/tarantool/third_party/coro/coro.c:110
```

**Comment by locker** [comment]
Fixed by 310e0715fa7a97bf8565e34be9b4bb0f3a6687e7
