### ISSUE TITLE
msgpuck.h:1687: mp_decode_strl: Assertion `0' failed

### ISSUE THREAD

**Issue by Totktonada** [tarantool/tarantool#3101]
tarantool: /var/tmp/portage/dev-db/tarantool-1.7.6.0/work/tarantool-1.7.6.0/src/lib/msgpuck/msgpuck.h:1687: mp_decode_strl: Assertion `0' failed.

```
(gdb) bt
#0  0x00007f39fe8aa010 in raise () from /lib64/libc.so.6
#1  0x00007f39fe8abc0d in abort () from /lib64/libc.so.6
#2  0x00007f39fe8a17e7 in __assert_fail_base () from /lib64/libc.so.6
#3  0x00007f39fe8a18a2 in __assert_fail () from /lib64/libc.so.6
#4  0x00000000005868c1 in mp_decode_strl (data=0x7f39fc01fd30) at /usr/src/debug/dev-db/tarantool-1.7.6.0/tarantool-1.7.6.0/src/lib/msgpuck/msgpuck.h:1687
#5  0x000000000059d97d in field_compare_with_key_and_next<2> (field_a=0x7f39fc01fd10, field_b=0x7f39fc01fd30)
    at /usr/src/debug/dev-db/tarantool-1.7.6.0/tarantool-1.7.6.0/src/box/tuple_compare.cc:992
#6  0x00000000005a0981 in (anonymous namespace)::FieldCompareWithKey<0, 0, 2, 1, 1, 2, 1>::compare (tuple=0x7f39fc090aa0, key=0x4186f614 "\367\377\377\377\t\002", part_count=134, 
    key_def=0x1fc0fd0, format=0x1fc7780, field=0x7f39fc090aac "user_id_10\255first name 10\254last name 10#######\020\v\t\374\071\177")
    at /usr/src/debug/dev-db/tarantool-1.7.6.0/tarantool-1.7.6.0/src/box/tuple_compare.cc:1020
#7  0x000000000059f6fc in (anonymous namespace)::TupleCompareWithKey<0, 0, 2, 1, 1, 2, 1>::compare (tuple=0x7f39fc090aa0, key=0x4186f613 "A\367\377\377\377\t\002", part_count=134, 
    key_def=0x1fc0fd0) at /usr/src/debug/dev-db/tarantool-1.7.6.0/tarantool-1.7.6.0/src/box/tuple_compare.cc:1089
#8  0x000000000059c2a8 in tuple_compare_with_key (tuple=0x7f39fc090aa0, key=0x4186f613 "A\367\377\377\377\t\002", part_count=134, key_def=0x1fc0fd0)
    at /usr/src/debug/dev-db/tarantool-1.7.6.0/tarantool-1.7.6.0/src/box/tuple_compare.h:106
#9  0x000000000059dbf8 in box_tuple_compare_with_key (tuple_a=0x7f39fc090aa0, key_b=0x4186f613 "A\367\377\377\377\t\002", key_def=0x1fc0fd0)
    at /usr/src/debug/dev-db/tarantool-1.7.6.0/tarantool-1.7.6.0/src/box/tuple_compare.cc:1168
#10 0x00007f39f8dfb7bc in ?? () from /usr/lib64/tarantool/shard/driver.so
#11 0x000000000051accb in lj_BC_FUNCC () at buildvm_x86.dasc:809
#12 0x000000000052f853 in lua_pcall (L=0x40c3a5d0, nargs=<optimized out>, nresults=<optimized out>, errfunc=<optimized out>) at lj_api.c:1139
#13 0x00000000004e8310 in luaT_call (L=0x40c3a5d0, nargs=3, nreturns=0) at /usr/src/debug/dev-db/tarantool-1.7.6.0/tarantool-1.7.6.0/src/lua/utils.c:931
#14 0x00000000004e1d67 in lua_fiber_run_f (ap=0x7f39fc0001b0) at /usr/src/debug/dev-db/tarantool-1.7.6.0/tarantool-1.7.6.0/src/lua/fiber.c:290
#15 0x000000000040cebe in fiber_cxx_invoke(fiber_func, typedef __va_list_tag __va_list_tag *) (f=0x4e1ca7 <lua_fiber_run_f>, ap=0x7f39fc0001b0)
    at /usr/src/debug/dev-db/tarantool-1.7.6.0/tarantool-1.7.6.0/src/fiber.h:665
#16 0x00000000004f8df9 in fiber_loop (data=0x0) at /usr/src/debug/dev-db/tarantool-1.7.6.0/tarantool-1.7.6.0/src/fiber.c:631
#17 0x000000000061f235 in coro_init () at /usr/src/debug/dev-db/tarantool-1.7.6.0/tarantool-1.7.6.0/third_party/coro/coro.c:110
(gdb) frame 4
#4  0x00000000005868c1 in mp_decode_strl (data=0x7f39fc01fd30) at /usr/src/debug/dev-db/tarantool-1.7.6.0/tarantool-1.7.6.0/src/lib/msgpuck/msgpuck.h:1687
1687                            mp_unreachable();
(gdb) list
1682                    return mp_load_u16(data);
1683            case 0xdb:
1684                    return mp_load_u32(data);
1685            default:
1686                    if (mp_unlikely(c < 0xa0 || c > 0xbf))
1687                            mp_unreachable();
1688                    return c & 0x1f;
1689            }
1690    }
1691    
(gdb) p c
$1 = 65 'A'
```

**Comment by Totktonada** [comment]
This is the bug on the shard side. The reason of this issue was fixed here: https://github.com/tarantool/shard/commit/58cbb50532f1f43b7e36a33f202bfdec0de80d9e
