### ISSUE TITLE
Segfault in tarntoolctl enter upon wakeup

### ISSUE THREAD

**Issue by kevpie** [tarantool/tarantool#3191]
- Entered cli 
- Server did not crash
- Laptop sleep and wake cycle may be involved
```
unix/:/usr/local/var/run/tarantool/example.control> Segmentation fault
Current time: 1519318548
Please file a bug at http://github.com/tarantool/tarantool/issues
Attempting backtrace... Note: since the server has already crashed, 
this may fail as well
#0  0x1081f339a in print_backtrace+9
#1  0x108157fd8 in _ZL12sig_fatal_cbi+ad
#2  0x7fff78f7bf5a in _sigtramp+1a
#3  0x1082e61e3 in ev_timer_again+55
#4  0x1082e548e in ev_invoke_pending+5d
#5  0x1082e5ad8 in ev_run+62b
#6  0x1081e2927 in tarantool_lua_run_script+93
#7  0x108157a4f in main+4ba
Abort trap: 6
```

Using homebrew for Server
```
tarantool --version
Tarantool 1.7.6-12-g2db448b
Target: Darwin-x86_64-Release
Build options: cmake . -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/tarantool/1.7.6.12_1 -DENABLE_BACKTRACE=ON
Compiler: /usr/local/Homebrew/Library/Homebrew/shims/super/clang /usr/local/Homebrew/Library/Homebrew/shims/super/clang++
C_FLAGS: -fexceptions -funwind-tables -fno-omit-frame-pointer -fno-stack-protector -fno-common -fopenmp -msse2 -std=c11 -Wall -Wextra -Wno-strict-aliasing -Wno-char-subscripts -Wno-format-truncation
CXX_FLAGS:-Wno-c++11-narrowing -fexceptions -funwind-tables -fno-omit-frame-pointer -fno-stack-protector -fno-common -fopenmp -msse2 -std=c++11 -Wall -Wextra -Wno-strict-aliasing -Wno-char-subscripts -Wno-format-truncation
```

Crash epoch matches wake time this morning after night of sleep. `Current time: 1519318548`
```
GMT: Thursday, February 22, 2018 4:55:48 PM
Your time zone: Thursday, February 22, 2018 8:55:48 AM GMT-08:00
```

**Comment by kyukhin** [comment]
We cannot reproduce that. If there'll be reproducer - feel free to reopen.
