### ISSUE TITLE
There is an error in the benchmark. (Connection refused)

### ISSUE THREAD

**Issue by voiddeveloper** [tarantool/tarantool#3219]
I am now benchmarking redis and tarantool for what nosql is right for my app.
The tool is using "ycsb" and redis has already run the benchmark.

 ./bin/ycsb load tarantool -s -P workloads/workloada"

When I entered the command, an error " java.net.ConnectException: connection refused" occurred.

First, I accepted the 3301 port and I still turned off the firewall because I got the same error

second, I also changed the listen of the network configuration  to "*: 3301" . but I still get the same error.

I do not know what to do.
I would appreciate it if you could help  me   

```
"$ ./bin/ycsb load tarantool -s -P workloads/workloada

[WARN]  Running against a source checkout. In order to get our runtime dependencies we'll have to invoke Maven. Depending on the state of your system, this may take ~30-45 seconds
[DEBUG]  Running 'mvn -pl com.yahoo.ycsb:tarantool-binding -am package -DskipTests dependency:build-classpath -DincludeScope=compile -Dmdep.outputFilterFile=true'
java -cp /home/teamnova/YCSB/tarantool/conf:/home/teamnova/YCSB/tarantool/target/tarantool-binding-0.14.0-SNAPSHOT.jar:/home/teamnova/YCSB/core/target/core-0.14.0-SNAPSHOT.jar:/home/teamnova/.m2/repository/org/apache/htrace/htrace-core4/4.1.0-incubating/htrace-core4-4.1.0-incubating.jar:/home/teamnova/.m2/repository/org/hdrhistogram/HdrHistogram/2.1.4/HdrHistogram-2.1.4.jar:/home/teamnova/.m2/repository/org/codehaus/jackson/jackson-mapper-asl/1.9.4/jackson-mapper-asl-1.9.4.jar:/home/teamnova/.m2/repository/org/codehaus/jackson/jackson-core-asl/1.9.4/jackson-core-asl-1.9.4.jar:/home/teamnova/.m2/repository/org/tarantool/connector/1.6.5/connector-1.6.5.jar com.yahoo.ycsb.Client -db com.yahoo.ycsb.db.TarantoolClient -s -P workloads/workloada -load
Command line: -db com.yahoo.ycsb.db.TarantoolClient -s -P workloads/workloada -loadYCSB Client 0.14.0-SNAPSHOT

Loading workload...
Starting test.
com.yahoo.ycsb.DBException: Can't initialize Tarantool connection
	at com.yahoo.ycsb.db.TarantoolClient.init(TarantoolClient.java:54)
	at com.yahoo.ycsb.DBWrapper.init(DBWrapper.java:86)
	at com.yahoo.ycsb.ClientThread.run(Client.java:423)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.ConnectException: connection refused
	at sun.nio.ch.Net.connect0(Native Method)
	at sun.nio.ch.Net.connect(Net.java:454)
	at sun.nio.ch.Net.connect(Net.java:446)
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:648)
	at java.nio.channels.SocketChannel.open(SocketChannel.java:189)
	at org.tarantool.TarantoolConnection16Impl.<init>(TarantoolConnection16Impl.java:20)
	at com.yahoo.ycsb.db.TarantoolClient.init(TarantoolClient.java:52)
	... 3 more
com.yahoo.ycsb.DBException: Can't initialize Tarantool connection
	at com.yahoo.ycsb.db.TarantoolClient.init(TarantoolClient.java:54)
	at com.yahoo.ycsb.DBWrapper.init(DBWrapper.java:86)
	at com.yahoo.ycsb.ClientThread.run(Client.java:423)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.ConnectException: connection refused
	at sun.nio.ch.Net.connect0(Native Method)
	at sun.nio.ch.Net.connect(Net.java:454)
	at sun.nio.ch.Net.connect(Net.java:446)
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:648)
	at java.nio.channels.SocketChannel.open(SocketChannel.java:189)
	at org.tarantool.TarantoolConnection16Impl.<init>(TarantoolConnection16Impl.java:20)
	at com.yahoo.ycsb.db.TarantoolClient.init(TarantoolClient.java:52)
	... 3 more
2018-03-07 15:47:26:339 0 sec: 0 operations; est completion in 0 second 
2018-03-07 15:47:26:340 0 sec: 0 operations; est completion in 106751991167300 days 15 hours 
[OVERALL], RunTime(ms), 8
[OVERALL], Throughput(ops/sec), 0.0
[TOTAL_GCS_PS_Scavenge], Count, 0
[TOTAL_GC_TIME_PS_Scavenge], Time(ms), 0
[TOTAL_GC_TIME_%_PS_Scavenge], Time(%), 0.0
[TOTAL_GCS_PS_MarkSweep], Count, 0
[TOTAL_GC_TIME_PS_MarkSweep], Time(ms), 0
[TOTAL_GC_TIME_%_PS_MarkSweep], Time(%), 0.0
[TOTAL_GCs], Count, 0
[TOTAL_GC_TIME], Time(ms), 0
[TOTAL_GC_TIME_%], Time(%), 0.0

```

**Comment by kostja** [comment]
Please feel free to send us a patch.
