### ISSUE TITLE
Segfault in box_tuple_ref

### ISSUE THREAD

**Issue by opomuc** [tarantool/tarantool#3246]
Case: secondary select by incomplete key in index which has nullable fields and row with `null` in them

```
13:31:18 front_01.1               | Segmentation fault
13:31:18 front_01.1               |   code: SEGV_MAPERR
13:31:18 front_01.1               |   addr: 0x0
13:31:18 front_01.1               |   context: 0x11204fbc0
13:31:18 front_01.1               |   siginfo: 0x11204fb58
13:31:18 front_01.1               | Current time: 1521455478
13:31:18 front_01.1               | Please file a bug at http://github.com/tarantool/tarantool/issues
13:31:18 front_01.1               | Attempting backtrace... Note: since the server has already crashed,
13:31:18 front_01.1               | this may fail as well
13:31:18 front_01.1               | #0  0x10fa506ef in print_backtrace+9
13:31:18 front_01.1               | #1  0x10f9ad123 in _ZL12sig_fatal_cbiP9__siginfoPv+158
13:31:18 front_01.1               | #2  0x7fff8e279b3a in _sigtramp+1a
13:31:18 front_01.1               | #3  0x10facd9b4 in box_tuple_ref+1
13:31:18 front_01.1               | #4  0x10fa65215 in lj_BC_FUNCC+44
13:31:18 front_01.1               | #5  0x10fa31640 in execute_lua_call+e5
13:31:18 front_01.1               | #6  0x10fa65215 in lj_BC_FUNCC+44
13:31:18 front_01.1               | #7  0x10fa7533b in lua_pcall+97
13:31:18 front_01.1               | #8  0x10fa43720 in luaT_call+13
13:31:18 front_01.1               | #9  0x10fa3151d in box_lua_call+7d
13:31:18 front_01.1               | #10 0x10fa30dd5 in box_process_call+280
13:31:18 front_01.1               | #11 0x10f9af9f3 in _ZL15tx_process_callP4cmsg+d3
13:31:18 front_01.1               | #12 0x10fa51ad1 in cmsg_deliver+14
13:31:18 front_01.1               | #13 0x10fa52b29 in fiber_pool_f+104
13:31:18 front_01.1               | #14 0x10f9acd44 in _ZL16fiber_cxx_invokePFiP13__va_list_tagES0_+c
13:31:18 front_01.1               | #15 0x10fa4e8e2 in fiber_loop+2a
13:31:18 front_01.1               | #16 0x10fb65f15 in coro_init+4b
```
Tarantool version: `1.9.0-3-g64faad37d`

Dump: [dump](https://drive.google.com/file/d/1yVCTVwnFNTj3mFXWwYtbAkskQ9UiU_bl/view?usp=sharing)

Debug log before crash:
```
2018-03-19 14:04:20.105 [6065] main D> cpipe_flush_cb: locking &endpoint->mutex
2018-03-19 14:04:20.105 [6065] main D> cpipe_flush_cb: unlocking &endpoint->mutex
2018-03-19 14:04:20.105 [6065] iproto/101/main D> cbus_endpoint_fetch: locking &endpoint->mutex
2018-03-19 14:04:20.105 [6065] iproto/101/main D> cbus_endpoint_fetch: unlocking &endpoint->mutex
2018-03-19 14:04:20.106 [6065] main/457/main D> ClientError at /tmp/tarantool-20180227-60568-1352egj/src/box/key_def.h:396
2018-03-19 14:04:20.106 [6065] main/457/main D> runtime_tuple_delete(0x103d7c068)
```

Assumed perpetrator: [merger_start in tarantool/shard](https://github.com/tarantool/shard/blob/bastida-shard/driver.c#L115)

**Comment by opomuc** [comment]
moved to [tarantool/shard](https://github.com/tarantool/shard/issues/61)
