### ISSUE TITLE
segmentation fault

### ISSUE THREAD

**Issue by ctpo6** [tarantool/tarantool#3332]
Тарантул собирался с бранча debug-netbox (сейчас фикс с нее переехал в gh-3326-sql-iproto-fix).

```
Segmentation fault
  code: SEGV_MAPERR
  addr: (nil)
  context: 0x7f681a27f040
  siginfo: 0x7f681a27f170
  rax      0x0                0
  rbx      0x0                0
  rcx      0x2858968          42305896
  rdx      0x2856168          42295656
  rsi      0x2856168          42295656
  rdi      0x0                0
  rsp      0x7f681a27f600     140085092152832
  rbp      0x7f681a27f610     140085092152848
  r8       0x285df68          42327912
  r9       0x0                0
  r10      0x0                0
  r11      0xfffffffffffffffc -4
  r12      0x0                0
  r13      0x0                0
  r14      0x0                0
  r15      0x0                0
  rip      0x499e09           4824585
  eflags   0x10206            66054
  cs       0x33               51
  gs       0x0                0
  fs       0x0                0
  cr2      0x0                0
  err      0x4                4
  oldmask  0x0                0
  trapno   0xe                14


(gdb) bt
#0  0x00007f6861314428 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
#1  0x00007f686131602a in __GI_abort () at abort.c:89
#2  0x000000000040e3fe in sig_fatal_cb (signo=11, siginfo=0x7f681a27f170, context=0x7f681a27f040)
    at /home/ctpo6/work/tarantool/src/main.cc:257
#3  <signal handler called>
#4  0x0000000000499e09 in space_delete_ephemeral (space=0x0) at /home/ctpo6/work/tarantool/src/box/space.c:218
#5  0x00000000004dcddc in tarantoolSqlite3EphemeralDrop (pCur=0x28561c4) at /home/ctpo6/work/tarantool/src/box/sql.c:473
#6  0x0000000000765524 in sqlite3CloseCursor (pCur=0x28561c4) at /home/ctpo6/work/tarantool/src/box/sql/cursor.c:78
#7  0x000000000073e43b in sqlite3VdbeFreeCursor (p=0x2858368, pCx=0x2856168) at /home/ctpo6/work/tarantool/src/box/sql/vdbeaux.c:2220
#8  0x000000000073e49f in closeCursorsInFrame (p=0x2858368) at /home/ctpo6/work/tarantool/src/box/sql/vdbeaux.c:2237
#9  0x000000000073e667 in closeTopFrameCursors (p=0x2858368) at /home/ctpo6/work/tarantool/src/box/sql/vdbeaux.c:2287
#10 0x000000000073ef1f in sqlite3VdbeHalt (p=0x2858368) at /home/ctpo6/work/tarantool/src/box/sql/vdbeaux.c:2569
#11 0x0000000000737201 in sqlite3VdbeExec (p=0x2858368) at /home/ctpo6/work/tarantool/src/box/sql/vdbe.c:5509
#12 0x0000000000738200 in sqlite3Step (p=0x2858368) at /home/ctpo6/work/tarantool/src/box/sql/vdbeapi.c:586
#13 0x00000000007383d6 in sqlite3_step (pStmt=0x2858368) at /home/ctpo6/work/tarantool/src/box/sql/vdbeapi.c:639
#14 0x00000000004e279c in sql_execute (db=0x28531a8, stmt=0x2858368, column_count=3, port=0x7f681a27fdc0, region=0x7f685a4051d8)
    at /home/ctpo6/work/tarantool/src/box/execute.c:560
#15 0x00000000004e293d in sql_execute_and_encode (db=0x28531a8, stmt=0x2858368, out=0x7f685a040880, sync=4387389, region=0x7f685a4051d8)
    at /home/ctpo6/work/tarantool/src/box/execute.c:599
#16 0x00000000004e2e1e in sql_prepare_and_execute (request=0x7f685a00fd38, out=0x7f685a040880, region=0x7f685a4051d8)
    at /home/ctpo6/work/tarantool/src/box/execute.c:672
#17 0x0000000000414129 in tx_process_sql (m=0x7f685a00fcd0) at /home/ctpo6/work/tarantool/src/box/iproto.cc:1408
#18 0x00000000005191a4 in cmsg_deliver (msg=0x7f685a00fcd0) at /home/ctpo6/work/tarantool/src/cbus.c:353
#19 0x000000000051a203 in fiber_pool_f (ap=0x7f685a405270) at /home/ctpo6/work/tarantool/src/fiber_pool.c:64
#20 0x000000000040ddce in fiber_cxx_invoke(fiber_func, typedef __va_list_tag __va_list_tag *) (f=0x51a070 <fiber_pool_f>, 
    ap=0x7f685a405270) at /home/ctpo6/work/tarantool/src/fiber.h:667
#21 0x00000000005148f0 in fiber_loop (data=0x0) at /home/ctpo6/work/tarantool/src/fiber.c:634
#22 0x00000000006de17b in coro_init () at /home/ctpo6/work/tarantool/third_party/coro/coro.c:110
```

**Comment by kyukhin** [comment]
We need a reproducer.

**Comment by Korablev77** [comment]
Eventually, I have managed to write simple reproducer:
```
box.cfg{}
\set language sql
CREATE TABLE t1(id UNSIGNED BIG INT PRIMARY KEY,max_players INTEGER,n_players INTEGER,flags INTEGER);
CREATE INDEX IDX_MAX_PLAYERS ON t1(max_players);
CREATE INDEX IDX_N_PLAYERS ON t1(n_players);
CREATE INDEX IDX_FLAGS ON t1(flags);
\set language lua
for i = 1, 100 do
	box.sql.execute(string.format("INSERT INTO t1 VALUES (%s, %s, %s, %s);", i, 15, 6, 3));
end
for i = 101, 1100 do
	box.sql.execute(string.format("INSERT INTO t1 VALUES (%s, %s, %s, %s);", i, 15, 6, 0));
end
for i = 1, 100000 do
	box.sql.execute("SELECT id,max_players,n_players FROM t1 WHERE flags=3 AND max_players>=15 ORDER BY id LIMIT 70");
end
```

Execution ends in VDBE after error from Tarantool's core: 'Tuple format limit reached'.
