### ISSUE TITLE
libunwind segfault while creating fiber backtrace

### ISSUE THREAD

**Issue by Totktonada** [tarantool/tarantool#3448]
app/fiber.test.lua segfaults in RelWithDebInfo build (but not in Debug) when ENABLE_BACKTRACE is enabled (on 1.9, 1.10 and 2.0). The minimal reproducer is the following:

```
tarantool> fiber = require('fiber')
tarantool> fiber.create(function() fiber.sleep(100) end)
tarantool> fiber.info()
```

```
Current time: 1528407082
Please file a bug at http://github.com/tarantool/tarantool/issues
Attempting backtrace... Note: since the server has already crashed, 
this may fail as well
#0  0x5633ae2489c9 in print_backtrace+9
#1  0x5633ae178503 in _ZL12sig_fatal_cbiP9siginfo_tPv+d3
#2  0x7f793b390140 in funlockfile+80
#3  0x7f793ad2e60f in _Ux86_64_get_save_loc+38f
#4  0x7f793ad3418d in _Ux86_64_step+4d7d
#5  0x7f793ad35b1f in _Ux86_64_step+670f
#6  0x7f793ad37069 in _Ux86_64_step+7c59
#7  0x7f793ad2f440 in _Ux86_64_step+30
#8  0x5633ae24889d in backtrace_foreach+dd
#9  0x5633ae2328ed in lbox_fiber_statof+1cd
#10 0x5633ae247d36 in fiber_stat+46
#11 0x5633ae232514 in lbox_fiber_info+34
#12 0x5633ae25ebf7 in lj_BC_FUNCC+34
#13 0x5633ae2706e4 in lua_pcall+64
#14 0x5633ae2378d1 in luaT_call+11
#15 0x5633ae23246c in lua_fiber_run_f+4c
#16 0x5633ae17794c in _ZL16fiber_cxx_invokePFiP13__va_list_tagES0_+c
#17 0x5633ae245fc0 in fiber_loop+30
#18 0x5633ae384f7f in coro_init+3f
[001] app/fiber.test.lua  
```

```
Thread 1 "tarantool" received signal SIGSEGV, Segmentation fault.
0x00007ffff593660f in access_mem () from /usr/lib64/libunwind-x86_64.so.8
(gdb) bt
#0  0x00007ffff593660f in access_mem () from /usr/lib64/libunwind-x86_64.so.8
#1  0x00007ffff593c18d in apply_reg_state () from /usr/lib64/libunwind-x86_64.so.8
#2  0x00007ffff593db1f in _Ux86_64_dwarf_find_save_locs () from /usr/lib64/libunwind-x86_64.so.8
#3  0x00007ffff593f069 in _Ux86_64_dwarf_step () from /usr/lib64/libunwind-x86_64.so.8
#4  0x00007ffff5937440 in _Ux86_64_step () from /usr/lib64/libunwind-x86_64.so.8
#5  0x000055555564689d in backtrace_foreach (cb=cb@entry=0x555555630640 <fiber_backtrace_cb>, coro_ctx=coro_ctx@entry=0x7ffff2405080, cb_ctx=cb_ctx@entry=0x40049998)
    at /home/alex/p/tarantool-meta/tarantool-2/src/backtrace.cc:379
#6  0x00005555556308ed in lbox_fiber_statof (f=0x7ffff2405080, cb_ctx=0x40049998, backtrace=<optimized out>) at /home/alex/p/tarantool-meta/tarantool-2/src/lua/fiber.c:235
#7  0x0000555555645d36 in fiber_stat (cb=cb@entry=0x555555630950 <lbox_fiber_statof_bt>, cb_ctx=cb_ctx@entry=0x40049998) at /home/alex/p/tarantool-meta/tarantool-2/src/fiber.c:1239
#8  0x0000555555630514 in lbox_fiber_info (L=0x40049998) at /home/alex/p/tarantool-meta/tarantool-2/src/lua/fiber.c:279
#9  0x000055555565cbf7 in lj_BC_FUNCC ()
#10 0x000055555566e6e4 in lua_pcall ()
#11 0x00005555556358d1 in luaT_call (L=L@entry=0x40049998, nargs=<optimized out>, nreturns=nreturns@entry=0) at /home/alex/p/tarantool-meta/tarantool-2/src/lua/utils.c:931
#12 0x000055555563046c in lua_fiber_run_f (ap=<optimized out>) at /home/alex/p/tarantool-meta/tarantool-2/src/lua/fiber.c:300
#13 0x000055555557594c in fiber_cxx_invoke(fiber_func, typedef __va_list_tag __va_list_tag *) (f=<optimized out>, ap=<optimized out>)
    at /home/alex/p/tarantool-meta/tarantool-2/src/fiber.h:665
#14 0x0000555555643fc0 in fiber_loop (data=<optimized out>) at /home/alex/p/tarantool-meta/tarantool-2/src/fiber.c:631
#15 0x0000555555782f7f in coro_init () at /home/alex/p/tarantool-meta/tarantool-2/third_party/coro/coro.c:110
```

OS: Gentoo/amd64 17.0 profile, gcc-7.3.30, libunwind-1.2.1. 17.0 profile has PIE enabled by default, but I tried to disable it manually for tarantool and nothing was changed.

I tried to reproduce in docker on packpack/packpack:ubuntu-bionic image (with tarantool builded inside the container), but got always empty backtraces.

**Comment by Totktonada** [comment]
Fixed by @GeorgyKirichenko in 5c3b30016bc65a77804f995de0024a66a699ccc1.
