### ISSUE TITLE
Tarantool crash on mac os

### ISSUE THREAD

**Issue by vmakhaev** [tarantool/tarantool#3465]
Steps to reproduce:
- start tarantool on mac os
- go to sleeping mode
- quit sleeping mode
- profit

```
Mac OS High Sierra
10.13.4
```

```
➜  ~ tarantool -v
Tarantool 1.9.0-61-gcd48321
Target: Darwin-x86_64-Release
Build options: cmake . -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/tarantool/1.9.0.61 -DENABLE_BACKTRACE=ON
Compiler: /usr/local/Homebrew/Library/Homebrew/shims/super/clang /usr/local/Homebrew/Library/Homebrew/shims/super/clang++
C_FLAGS: -fexceptions -funwind-tables -fno-omit-frame-pointer -fno-stack-protector -fno-common -fopenmp -msse2 -std=c11 -Wall -Wextra -Wno-strict-aliasing -Wno-char-subscripts -Wno-format-truncation
CXX_FLAGS: -fexceptions -funwind-tables -fno-omit-frame-pointer -fno-stack-protector -fno-common -fopenmp -msse2 -std=c++11 -Wall -Wextra -Wno-strict-aliasing -Wno-char-subscripts -Wno-format-truncation
```

```
Segmentation fault
  code: SEGV_MAPERR
  addr: 0x7f9649f20b40
  context: 0x7ffee5808348
  siginfo: 0x7ffee58082e0
Current time: 1529138961
Please file a bug at http://github.com/tarantool/tarantool/issues
Attempting backtrace... Note: since the server has already crashed,
this may fail as well
#0  0x10a49c6be in print_backtrace+9
#1  0x10a3fab03 in _ZL12sig_fatal_cbiP9__siginfoPv+158
#2  0x7fff6382ef5a in _sigtramp+1a
#3  0x10a5a9c0f in ev_timer_again+49
#4  0x10a5a8ec6 in ev_invoke_pending+5d
#5  0x10a5a9510 in ev_run+62b
#6  0x10a3fa53b in main+566
```

**Comment by kyukhin** [comment]
Could you pls try w/ newer version of 1.9 release series? We cannot reproduce the issue,
so it might be already fixed.

**Comment by kyukhin** [comment]
More than 2 wws w/o feedback. Consider resolved.
