### ISSUE TITLE
Assertion failure in build.c after "rework VIEW internals" patch

### ISSUE THREAD

**Issue by kshcherbatov** [tarantool/tarantool#3471]
Came with patch dc358cb014280f5835740b6c2b25608383b14763.
It could came into existence accidentally, to increase probability, start concurrent tests:
PATH=~/tarantool/bin:$PATH ./test-run.py sql/  sql/ sql/ sql/ --force | grep Assertion 
multiple times.
There are some other problems with concurrent tests, but this task is not about them.. Just ignore. 

1. 
```
struct key_def*
sql_index_key_def(struct Index *idx)
{
	uint32_t space_id = SQLITE_PAGENO_TO_SPACEID(idx->tnum);
	uint32_t index_id = SQLITE_PAGENO_TO_INDEXID(idx->tnum);
	struct space *space = space_by_id(space_id);
	assert(space != NULL);
	struct index *index = space_index(space, index_id);
	**assert(index != NULL && index->def != NULL);**
	return index->def->key_def;
}

(gdb) bt
#3  0x00007fca2bf6bc82 in __GI___assert_fail (assertion=0x8663d8 "index != NULL && index->def != NULL", file=0x865ee8 "/home/kir/tarantool/src/box/sql/build.c", line=1105, 
    function=0x8672f0 <__PRETTY_FUNCTION__.13555> "sql_index_key_def") at assert.c:101
#4  0x00000000006e4f4f in sql_index_key_def (idx=0x1a89d18) at /home/kir/tarantool/src/box/sql/build.c:1105
#5  0x000000000073c312 in sql_vdbe_set_p4_key_def (parse=0x7fca2481fab0, idx=0x1a89d18) at /home/kir/tarantool/src/box/sql/vdbeaux.c:1168
#6  0x00000000006fee64 in sqlite3OpenTableAndIndices (pParse=0x7fca2481fab0, pTab=0x1a89788, op=99, p5=0 '\000', iBase=2, aToOpen=0x0, piDataCur=0x7fca2481f674, 
    piIdxCur=0x7fca2481f670, overrideError=6 '\006', isUpdate=0 '\000') at /home/kir/tarantool/src/box/sql/insert.c:1630
#7  0x00000000006fcf0a in sqlite3Insert (pParse=0x7fca2481fab0, pTabList=0x1a7fbe8, pSelect=0x0, pColumn=0x0, on_error=ON_CONFLICT_ACTION_DEFAULT)
    at /home/kir/tarantool/src/box/sql/insert.c:637
#8  0x000000000075c5b1 in yy_reduce (yypParser=0x1a8a0b8, yyruleno=134) at /home/kir/tarantool/src/box/sql/parse.y:780
#9  0x000000000075e95e in sqlite3Parser (yyp=0x1a8a0b8, yymajor=1, yyminor=..., pParse=0x7fca2481fab0) at parse.c:3849
#10 0x0000000000722964 in sqlite3RunParser (pParse=0x7fca2481fab0, zSql=0x1a81be8 "INSERT INTO t2 VALUES (9)", pzErrMsg=0x7fca2481fcf8)
    at /home/kir/tarantool/src/box/sql/tokenize.c:493
#11 0x000000000070c2a1 in sqlite3Prepare (db=0x1a75a58, zSql=0x409318f8 "INSERT INTO t2 VALUES (9)", nBytes=25, saveSqlFlag=1, pReprepare=0x0, ppStmt=0x7fca2481fe10, 
    pzTail=0x7fca2481fe18) at /home/kir/tarantool/src/box/sql/prepare.c:256
#12 0x000000000070c659 in sqlite3LockAndPrepare (db=0x1a75a58, zSql=0x409318f8 "INSERT INTO t2 VALUES (9)", nBytes=25, saveSqlFlag=1, pOld=0x0, ppStmt=0x7fca2481fe10, 
    pzTail=0x7fca2481fe18) at /home/kir/tarantool/src/box/sql/prepare.c:353
#13 0x000000000070c8ca in sqlite3_prepare_v2 (db=0x1a75a58, zSql=0x409318f8 "INSERT INTO t2 VALUES (9)", nBytes=25, ppStmt=0x7fca2481fe10, pzTail=0x7fca2481fe18)
    at /home/kir/tarantool/src/box/sql/prepare.c:430
#14 0x00000000004f4bcc in lua_sql_execute (L=0x4060b2c8) at /home/kir/tarantool/src/box/lua/sql.c:74

(gdb) frame 4
(gdb) p *idx
$3 = {zName = 0x1a89d98 "sqlite_autoindex_T2_1", aiColumn = 0x1a89d8c, aiRowLogEst = 0x1a89d88, pTable = 0x1a89788, zColAff = 0x0, pNext = 0x0, pSchema = 0x1a73178, 
  sort_order = 0x1a89d8e, coll_array = 0x1a89d78, coll_id_array = 0x1a89d80, pPartIdxWhere = 0x0, tnum = 540672, nColumn = 1, onError = 6 '\006', idxType = 2}
(gdb) p *space
$4 = {vtab = 0x7733a0 <memtx_space_vtab>, access = {{granted = 0, effective = 0} <repeats 32 times>}, engine = 0x1a63f40, before_replace = {prev = 0x1ac0150, 
    next = 0x1ac0150}, on_replace = {prev = 0x1ac0160, next = 0x1ac0160}, on_stmt_begin = {prev = 0x1ac0170, next = 0x1ac0170}, index_count = 0, index_id_max = 0, 
  def = 0x1ac01d0, sequence = 0x0, run_triggers = true, format = 0x1abcc80, index_map = 0x1abefe0, index = 0x1abefe8}
(gdb) p index
$2 = (struct index *) 0x0

```
2.
```
uint32_t
index_column_count(const Index *idx)
{
	assert(idx != NULL);
	uint32_t space_id = SQLITE_PAGENO_TO_SPACEID(idx->tnum);
	struct space *space = space_by_id(space_id);
	/* It is impossible to find an ephemeral space by id. */
	if (space == NULL)
		return idx->nColumn;

	uint32_t index_id = SQLITE_PAGENO_TO_INDEXID(idx->tnum);
	struct index *index = space_index(space, index_id);
	**assert(index != NULL);**
	return index->def->key_def->part_count;
}

(gdb) bt
#3  0x00007f57efbcac82 in __GI___assert_fail (assertion=0x866d48 "index != NULL", file=0x865ee8 "/home/kir/tarantool/src/box/sql/build.c", line=3111, 
    function=0x867520 <__PRETTY_FUNCTION__.14013> "index_column_count") at assert.c:101
#4  0x00000000006e9aff in index_column_count (idx=0x19c1798) at /home/kir/tarantool/src/box/sql/build.c:3111
#5  0x0000000000760ad7 in analyzeOneTable (pParse=0x7f57e841fab0, pTab=0x19c1208, pOnlyIdx=0x0, iStatCur=0, iMem=11, iTab=5) at /home/kir/tarantool/src/box/sql/analyze.c:865
#6  0x0000000000761528 in sql_analyze_database (parser=0x7f57e841fab0) at /home/kir/tarantool/src/box/sql/analyze.c:1127
#7  0x000000000076167c in sqlite3Analyze (pParse=0x7f57e841fab0, pName=0x0) at /home/kir/tarantool/src/box/sql/analyze.c:1175
#8  0x000000000075e348 in yy_reduce (yypParser=0x19c1b38, yyruleno=242) at /home/kir/tarantool/src/box/sql/parse.y:1443
#9  0x000000000075e95e in sqlite3Parser (yyp=0x19c1b38, yymajor=1, yyminor=..., pParse=0x7f57e841fab0) at parse.c:3849
#10 0x0000000000722964 in sqlite3RunParser (pParse=0x7f57e841fab0, zSql=0x19b9de8 "ANALYZE;", pzErrMsg=0x7f57e841fcf8) at /home/kir/tarantool/src/box/sql/tokenize.c:493
#11 0x000000000070c2a1 in sqlite3Prepare (db=0x19ada58, zSql=0x40afd268 "ANALYZE;", nBytes=8, saveSqlFlag=1, pReprepare=0x0, ppStmt=0x7f57e841fe10, pzTail=0x7f57e841fe18)
    at /home/kir/tarantool/src/box/sql/prepare.c:256
#12 0x000000000070c659 in sqlite3LockAndPrepare (db=0x19ada58, zSql=0x40afd268 "ANALYZE;", nBytes=8, saveSqlFlag=1, pOld=0x0, ppStmt=0x7f57e841fe10, pzTail=0x7f57e841fe18)
    at /home/kir/tarantool/src/box/sql/prepare.c:353
#13 0x000000000070c8ca in sqlite3_prepare_v2 (db=0x19ada58, zSql=0x40afd268 "ANALYZE;", nBytes=8, ppStmt=0x7f57e841fe10, pzTail=0x7f57e841fe18)
    at /home/kir/tarantool/src/box/sql/prepare.c:430
#14 0x00000000004f4bcc in lua_sql_execute (L=0x411cde00) at /home/kir/tarantool/src/box/lua/sql.c:74

(gdb) p *idx
$1 = {zName = 0x19c1818 "sqlite_autoindex_T2_1", aiColumn = 0x19c180c, aiRowLogEst = 0x19c1808, pTable = 0x19c1208, zColAff = 0x0, pNext = 0x0, pSchema = 0x19ab178, 
  sort_order = 0x19c180e, coll_array = 0x19c17f8, coll_id_array = 0x19c1800, pPartIdxWhere = 0x0, tnum = 558080, nColumn = 1, onError = 6 '\006', idxType = 2}
(gdb) p *space
$2 = {vtab = 0x7733a0 <memtx_space_vtab>, access = {{granted = 0, effective = 0} <repeats 32 times>}, engine = 0x199bf40, before_replace = {prev = 0x1b3c2e0, 
    next = 0x1b3c2e0}, on_replace = {prev = 0x1b3c2f0, next = 0x1b3c2f0}, on_stmt_begin = {prev = 0x1b3c300, next = 0x1b3c300}, index_count = 0, index_id_max = 0, 
  def = 0x1b3c360, sequence = 0x0, run_triggers = true, format = 0x1b3d060, index_map = 0x1b3d150, index = 0x1b3d158}
(gdb) p index
$3 = (struct index *) 0x0
```

**Comment by Korablev77** [comment]
Could you please provide reproducer?

**Comment by Korablev77** [comment]
I guess this issue is tightly connected with this one: https://github.com/tarantool/tarantool/issues/3472

It seems like table was created via SQL facilities, dropped by Lua and therefore insertion failed with assertion fault. But it is only guess, though.

**Comment by kshcherbatov** [comment]
@Korablev77 you are right; with pathes fixing part of problems #3472 , this doesn't reproduce.
