### ISSUE TITLE
Master may delete files needed for joining replica

### ISSUE THREAD

**Issue by locker** [tarantool/tarantool#3708]
To reproduce the issue, start a new replica in a clean directory:
```Lua
box.cfg{replication = 12345}
```

Then in another terminal start a master running the following script:
```Lua
box.cfg{
    listen = 12345,
    checkpoint_count = 1,
}

s = box.schema.space.create('test', {engine = 'vinyl'})
s:create_index('primary', {run_count_per_level = 1})

for i = 101, 110 do s:replace{i} end
box.snapshot()
for i = 111, 120 do s:replace{i} end
box.snapshot()

box.error.injection.set('ERRINJ_RELAY_TIMEOUT', 0.1)
box.schema.user.grant('guest', 'replication')
require('fiber').sleep(2)

for i = 121, 130 do s:replace{i} end
box.snapshot()
```

The replica bootstrap will never finish.

Log from the replica:
```
Tarantool 1.10.1-397-g4baa71bc
type 'help' for interactive help
tarantool> box.cfg{replication=12345}
2018-10-01 19:31:31.977 [30792] main/101/interactive C> Tarantool 1.10.1-397-g4baa71bc
2018-10-01 19:31:31.977 [30792] main/101/interactive C> log level 5
2018-10-01 19:31:31.977 [30792] main/101/interactive I> mapping 268435456 bytes for memtx tuple arena...
2018-10-01 19:31:31.977 [30792] main/101/interactive I> mapping 134217728 bytes for vinyl tuple arena...
2018-10-01 19:31:31.987 [30792] main/101/interactive I> connecting to 1 replicas
2018-10-01 19:31:31.988 [30792] main/105/applier/ I> can't connect to master
2018-10-01 19:31:31.988 [30792] main/105/applier/ coio.cc:106 !> SystemError connect, called on fd 11, aka [::1]:55804: Connection refused
2018-10-01 19:31:31.988 [30792] main/105/applier/ I> will retry every 1.00 second
2018-10-01 19:31:34.995 [30792] main/105/applier/ I> remote master is 1.10.1 at 0.0.0.0:12345
2018-10-01 19:31:34.996 [30792] main/101/interactive I> connected to 1 replicas
2018-10-01 19:31:34.996 [30792] main/101/interactive I> bootstrapping replica from cead34e9-9dc2-4dae-9113-f25f5c1f0390 at 0.0.0.0:12345
```

Log from the master:
```
2018-10-01 19:31:34.348 [30796] main/101/test.lua C> Tarantool 1.10.1-397-g4baa71bc
2018-10-01 19:31:34.348 [30796] main/101/test.lua C> log level 5
2018-10-01 19:31:34.348 [30796] main/101/test.lua I> mapping 268435456 bytes for memtx tuple arena...
2018-10-01 19:31:34.348 [30796] main/101/test.lua I> mapping 134217728 bytes for vinyl tuple arena...
2018-10-01 19:31:34.357 [30796] iproto/101/main I> binary: bound to 0.0.0.0:12345
2018-10-01 19:31:34.358 [30796] main/101/test.lua I> initializing an empty data directory
2018-10-01 19:31:34.381 [30796] snapshot/101/main I> saving snapshot `./00000000000000000000.snap.inprogress'
2018-10-01 19:31:34.406 [30796] snapshot/101/main I> done
2018-10-01 19:31:34.407 [30796] main/101/test.lua I> ready to accept requests
2018-10-01 19:31:34.407 [30796] main/107/checkpoint_daemon I> started
2018-10-01 19:31:34.407 [30796] main/107/checkpoint_daemon I> scheduled the next snapshot at Mon Oct  1 20:54:55 2018
2018-10-01 19:31:34.408 [30796] main/101/test.lua I> set 'checkpoint_count' configuration option to 1
2018-10-01 19:31:34.411 [30796] main/101/test.lua I> vinyl checkpoint started
2018-10-01 19:31:34.440 [30796] main/103/vinyl.scheduler I> 512/0: dump started
2018-10-01 19:31:34.440 [30796] vinyl.dump.0/102/task I> writing `./512/0/00000000000000000002.run'
2018-10-01 19:31:34.443 [30796] snapshot/101/main I> saving snapshot `./00000000000000000013.snap.inprogress'
2018-10-01 19:31:34.490 [30796] vinyl.dump.0/102/task I> writing `./512/0/00000000000000000002.index'
2018-10-01 19:31:34.515 [30796] snapshot/101/main I> done
2018-10-01 19:31:34.566 [30796] main/103/vinyl.scheduler I> 512/0: dump completed
2018-10-01 19:31:34.566 [30796] main/103/vinyl.scheduler I> dumped 49492 bytes in 0.2 sec
2018-10-01 19:31:34.566 [30796] main/101/test.lua I> vinyl checkpoint completed
2018-10-01 19:31:34.667 [30796] main/101/test.lua I> removed ./00000000000000000000.snap
2018-10-01 19:31:34.667 [30796] wal/101/main I> removed ./00000000000000000000.xlog
2018-10-01 19:31:34.669 [30796] main/101/test.lua I> vinyl checkpoint started
2018-10-01 19:31:34.692 [30796] main/103/vinyl.scheduler I> 512/0: dump started
2018-10-01 19:31:34.692 [30796] vinyl.dump.0/103/task I> writing `./512/0/00000000000000000004.run'
2018-10-01 19:31:34.696 [30796] snapshot/101/main I> saving snapshot `./00000000000000000023.snap.inprogress'
2018-10-01 19:31:34.734 [30796] vinyl.dump.0/103/task I> writing `./512/0/00000000000000000004.index'
2018-10-01 19:31:34.767 [30796] snapshot/101/main I> done
2018-10-01 19:31:34.818 [30796] main/103/vinyl.scheduler I> 512/0: dump completed
2018-10-01 19:31:34.818 [30796] main/103/vinyl.scheduler I> dumped 49492 bytes in 0.1 sec
2018-10-01 19:31:34.825 [30796] main/101/test.lua I> vinyl checkpoint completed
2018-10-01 19:31:34.825 [30796] main/103/vinyl.scheduler I> 512/0: started compacting range (-inf..inf), runs 2/2
2018-10-01 19:31:34.825 [30796] vinyl.compact.0/102/task I> writing `./512/0/00000000000000000006.run'
2018-10-01 19:31:34.893 [30796] vinyl.compact.0/102/task I> writing `./512/0/00000000000000000006.index'
2018-10-01 19:31:34.978 [30796] main/101/test.lua I> removed ./00000000000000000013.snap
2018-10-01 19:31:34.978 [30796] main/101/test.lua I> removed ./00000000000000000000.vylog
2018-10-01 19:31:34.978 [30796] wal/101/main I> removed ./00000000000000000013.xlog
2018-10-01 19:31:34.995 [30796] main/103/vinyl.scheduler I> 512/0: completed compacting range (-inf..inf)
2018-10-01 19:31:36.982 [30796] main/101/test.lua I> vinyl checkpoint started
2018-10-01 19:31:37.020 [30796] main/103/vinyl.scheduler I> 512/0: dump started
2018-10-01 19:31:37.020 [30796] vinyl.dump.0/104/task I> writing `./512/0/00000000000000000008.run'
2018-10-01 19:31:37.022 [30796] snapshot/101/main I> saving snapshot `./00000000000000000034.snap.inprogress'
2018-10-01 19:31:37.053 [30796] vinyl.dump.0/104/task I> writing `./512/0/00000000000000000008.index'
2018-10-01 19:31:37.078 [30796] snapshot/101/main I> done
2018-10-01 19:31:37.121 [30796] main/103/vinyl.scheduler I> 512/0: dump completed
2018-10-01 19:31:37.121 [30796] main/103/vinyl.scheduler I> dumped 49495 bytes in 0.1 sec
2018-10-01 19:31:37.121 [30796] main/101/test.lua I> vinyl checkpoint completed
2018-10-01 19:31:37.215 [30796] main/101/test.lua I> removed ./00000000000000000023.snap
2018-10-01 19:31:37.215 [30796] main/101/test.lua I> removed ./00000000000000000013.vylog
2018-10-01 19:31:37.215 [30796] main/101/test.lua I> removed ./512/0/00000000000000000004.index
2018-10-01 19:31:37.215 [30796] main/101/test.lua I> removed ./512/0/00000000000000000004.run
2018-10-01 19:31:37.216 [30796] main/101/test.lua I> removed ./512/0/00000000000000000002.index
2018-10-01 19:31:37.216 [30796] main/101/test.lua I> removed ./512/0/00000000000000000002.run
2018-10-01 19:31:37.216 [30796] main C> entering the event loop
2018-10-01 19:31:44.131 [30796] main/104/main xlog.c:1923 !> SystemError failed to open './512/0/00000000000000000004.index' file: No such file or directory
2018-10-01 19:31:44.131 [30796] main/104/main vy_run.c:1722 E> failed to load `./512/0/00000000000000000004.index'
Segmentation fault
  code: SEGV_MAPERR
  addr: (nil)
  context: 0x7fe9c304ed80
  siginfo: 0x7fe9c304eeb0
  rax      0x0                0
  rbx      0x55f813bd1031     94523971407921
  rcx      0x55f81529d900     94523995314432
  rdx      0x55f8152aa450     94523995366480
  rsi      0x0                0
  rdi      0x55f8152aa450     94523995366480
  rsp      0x7fe9c304f320     140641975989024
  rbp      0x7fe9c304f3b0     140641975989168
  r8       0x0                0
  r9       0x1                1
  r10      0x73               115
  r11      0x0                0
  r12      0x0                0
  r13      0x0                0
  r14      0x0                0
  r15      0x0                0
  rip      0x55f813b03d45     94523970567493
  eflags   0x10206            66054
  cs       0x33               51
  gs       0x0                0
  fs       0x0                0
  cr2      0x0                0
  err      0x4                4
  oldmask  0x0                0
  trapno   0xe                14
Current time: 1538411504
Please file a bug at http://github.com/tarantool/tarantool/issues
Attempting backtrace... Note: since the server has already crashed,
this may fail as well
#0  0x55f813bd7677 in print_backtrace+9
#1  0x55f813acb43d in _ZL12sig_fatal_cbiP9siginfo_tPv+1e7
#2  0x7fe9c92d30c0 in __restore_rt+0
#3  0x55f813b03d45 in vy_send_range+27c
#4  0x55f813b03ef4 in vy_send_lsm+184
#5  0x55f813b0432c in vinyl_engine_join+2a2
#6  0x55f813aedc37 in engine_join+4a
#7  0x55f813b99759 in _ZL14engine_join_xcPK6vclockP7xstream+23
#8  0x55f813b99fbe in _Z18relay_initial_joinimP6vclock+61
#9  0x55f813b81769 in _Z16box_process_joinP5ev_ioP11xrow_header+539
#10 0x55f813ad1406 in _ZL25tx_process_join_subscribeP4cmsg+59
#11 0x55f813bda0a5 in cmsg_deliver+30
#12 0x55f813bdb0f0 in fiber_pool_f+19d
#13 0x55f813acae24 in _ZL16fiber_cxx_invokePFiP13__va_list_tagES0_+1e
#14 0x55f813bd44a9 in fiber_loop+82
#15 0x55f813da7d6b in coro_init+4c
#16 (nil) in +4c
Aborted (core dumped)
```

The master crash is a side effect - looks like there's a bug on `vy_send_range()` error path. The real reason why bootstrap failed lies here:
```
2018-10-01 19:31:44.131 [30796] main/104/main xlog.c:1923 !> SystemError failed to open './512/0/00000000000000000004.index' file: No such file or directory
2018-10-01 19:31:44.131 [30796] main/104/main vy_run.c:1722 E> failed to load `./512/0/00000000000000000004.index'
```
It means that files needed for joining the replica were garbage collected.

The bug was introduced by commit 9c5d851d7830ad2095f66eef8285a5001dc9e647.

**Comment by locker** [comment]
Fixed by bae6f037c0df9bcde56611d411bf600341e008b3
