### ISSUE TITLE
box/bad_trigger.test fails on FreeBSD

### ISSUE THREAD

**Issue by rtsisyk** [tarantool/tarantool#376]
```
box/bad_trigger.test.py                         Traceback (most recent call last):
  File "/usr/home/buildslave/tarantool/test/lib/test.py", line 111, in run
    self.execute(server)
  File "/usr/home/buildslave/tarantool/test/lib/tarantool_server.py", line 113, in execute
    execfile(self.name, dict(locals(), **server.__dict__))
  File "box/bad_trigger.test.py", line 29, in <module>
    packet_len = unpacker.unpack()
  File "/usr/home/buildslave/tarantool/test/lib/msgpack-python/msgpack/fallback.py", line 452, in unpack
    ret = self._fb_unpack(EX_CONSTRUCT, write_bytes)
  File "/usr/home/buildslave/tarantool/test/lib/msgpack-python/msgpack/fallback.py", line 381, in _fb_unpack
    typ, n, obj = self._read_header(execute, write_bytes)
  File "/usr/home/buildslave/tarantool/test/lib/msgpack-python/msgpack/fallback.py", line 271, in _read_header
    c = self._fb_read(1, write_bytes)
  File "/usr/home/buildslave/tarantool/test/lib/msgpack-python/msgpack/fallback.py", line 262, in _fb_read
    raise OutOfData
OutOfData
```

**Comment by mejedi** [comment]
worksforme

**Comment by rtsisyk** [comment]
Reproduced on arm-linux-gnueabihf
```
box/bad_trigger.test.py                         Traceback (most recent call last):
  File "/home/roman/tarantool/test-run/lib/test.py", line 117, in run
    self.execute(server)
  File "/home/roman/tarantool/test-run/lib/tarantool_server.py", line 92, in execute
    execfile(self.name, dict(locals(), **server.__dict__))
  File "box/bad_trigger.test.py", line 34, in <module>
    packet_len = unpacker.unpack()
  File "/home/roman/tarantool/test-run/lib/msgpack-python/msgpack/fallback.py", line 570, in unpack
    ret = self._fb_unpack(EX_CONSTRUCT, write_bytes)
  File "/home/roman/tarantool/test-run/lib/msgpack-python/msgpack/fallback.py", line 498, in _fb_unpack
    typ, n, obj = self._read_header(execute, write_bytes)
  File "/home/roman/tarantool/test-run/lib/msgpack-python/msgpack/fallback.py", line 346, in _read_header
    c = self._fb_read(1, write_bytes)
  File "/home/roman/tarantool/test-run/lib/msgpack-python/msgpack/fallback.py", line 337, in _fb_read
    raise OutOfData
OutOfData
```
