### ISSUE TITLE
replication/replicaset_ro_mostly.test causing segmentation fault

### ISSUE THREAD

**Issue by sergw** [tarantool/tarantool#3765]
Tarantool version: **1.10**

OS version: travis or **docker-image:packpack/packpack:debian-stretch**

Bug description:
https://travis-ci.org/tarantool/tarantool/jobs/443475291#L2591
```
[001] replication/replicaset_ro_mostly.test.lua       vinyl
[001]
[001] [Instance "replica_uuid_ro1" killed by signal: 11 (SIGSEGV)]
```

Steps to reproduce:
```
cat <<EOF> Dockerfile.sigsegv-on-replicaset-test3
FROM packpack/packpack:debian-stretch
WORKDIR /tarantool
RUN set -x \
    && sudo apt-get update \
    && apt-get install -y -f \
       build-essential cmake coreutils sed \
       libreadline-dev libncurses5-dev libyaml-dev libssl-dev \
       libcurl4-openssl-dev libunwind-dev libicu-dev \
       python python-pip python-setuptools python-dev \
       python-msgpack python-yaml python-argparse python-six python-gevent \
       lcov ruby \
    && git clone https://github.com/tarantool/tarantool --recurse-submodules . \
    && git checkout sergw/travis-reproduce-segfault \
    && cmake . -DCMAKE_BUILD_TYPE=RelWithDebInfoWError \
    && make -j
ENTRYPOINT /bin/bash
EOF
docker image build . -f Dockerfile.sigsegv-on-replicaset-test -t reproduce1
docker run --rm -it reproduce1
# from inside docker
cd test && python test-run.py --reproduce reproduce.yml
```

**Comment by Totktonada** [comment]
@sergw, please try:

```
diff --git a/src/box/relay.cc b/src/box/relay.cc
index 81f2b821c..17d85c6ba 100644
--- a/src/box/relay.cc
+++ b/src/box/relay.cc
@@ -632,7 +632,7 @@ static void
 relay_send(struct relay *relay, struct xrow_header *packet)
 {
        struct errinj *inj = errinj(ERRINJ_RELAY_SEND_DELAY, ERRINJ_BOOL);
-       while (inj->bparam) {
+       while (inj != NULL && inj->bparam) {
                fiber_sleep(0.01);
                inj = errinj(ERRINJ_RELAY_SEND_DELAY, ERRINJ_BOOL);
        }
```

For more info:

```
<_ZL10relay_sendP5relayP11xrow_header>
push   %rbp
mov    %rsp,%rbp
sub    $0x30,%rsp
mov    %rdi,-0x18(%rbp)
mov    %rsi,-0x20(%rbp)
movq   $0x0,-0x8(%rbp) ; move 0 to local var 
mov    -0x8(%rbp),%rax ; move 0 from the var to %rax
movzbl 0x10(%rax),%eax ; !! SIGSEGV
```

```
(gdb) bt
#0  0x0000561b17600b3e in relay_send(relay*, xrow_header*) ()
#1  0x0000561b17600c40 in relay_send_initial_join_row(xstream*, xrow_header*) ()
#2  0x0000561b175fb98c in xstream_write ()
#3  0x0000561b175690b1 in memtx_initial_join_f ()
#4  0x0000561b17546d9f in fiber_cxx_invoke(int (*)(__va_list_tag*), __va_list_tag*) ()
#5  0x0000561b17636321 in fiber_loop ()
#6  0x0000561b1779a86f in coro_init ()
```

**Comment by sergw** [comment]
> ```
> diff --git a/src/box/relay.cc b/src/box/relay.cc
> index 81f2b821c..17d85c6ba 100644
> --- a/src/box/relay.cc
> +++ b/src/box/relay.cc
> @@ -632,7 +632,7 @@ static void
>  relay_send(struct relay *relay, struct xrow_header *packet)
>  {
>         struct errinj *inj = errinj(ERRINJ_RELAY_SEND_DELAY, ERRINJ_BOOL);
> -       while (inj->bparam) {
> +       while (inj != NULL && inj->bparam) {
>                 fiber_sleep(0.01);
>                 inj = errinj(ERRINJ_RELAY_SEND_DELAY, ERRINJ_BOOL);
>         }
> ```
Fixed
