### ISSUE TITLE
test: vinyl/ddl with is_parallel enabled crashed with SIGABRT

### ISSUE THREAD

**Issue by sergw** [tarantool/tarantool#3771]
Tarantool version: **1.10**

OS version: OSX with docker image **packpack/packpack:debian-stretch**

Bug description:
Trying to make vinyl testsuite work in parallel, but this test sometimes crashed with trace.
```
Segmentation fault
  code: SEGV_MAPERR
  addr: 0x108
  context: 0x7f8b5390f580
  siginfo: 0x7f8b5390f6b0
  rax      0x108              264
  rbx      0x7f8b53b82128     140236381757736
  rcx      0x56472fb8c730     94863743305520
  rdx      0x8                8
  rsi      0x7f8b539345d0     140236379342288
  rdi      0x56472fb8c730     94863743305520
  rsp      0x7f8b5390fb40     140236379192128
  rbp      0x7f8b5390fb90     140236379192208
  r8       0x6                6
  r9       0x50               80
  r10      0x41d53048         1104490568
  r11      0x0                0
  r12      0x41cd73b8         1103983544
  r13      0x0                0
  r14      0x41cd8000         1103986688
  r15      0x56472f236ea7     94863733517991
  rip      0x56472f1a242d     94863732909101
  eflags   0x10202            66050
  cs       0x33               51
  gs       0x0                0
  fs       0x0                0
  cr2      0x108              264
  err      0x4                4
  oldmask  0x0                0
  trapno   0xe                14
Current time: 1540586848
Please file a bug at http://github.com/tarantool/tarantool/issues
Attempting backtrace... Note: since the server has already crashed,
this may fail as well
#0  0x56472f2650ba in print_backtrace+9
#1  0x56472f1733b8 in _ZL12sig_fatal_cbiP9siginfo_tPv+1e7
#2  0x7f8b596ee0c0 in __restore_rt+0
#3  0x56472f1a242d in vy_check_is_unique+dc
#4  0x56472f1a38f4 in vy_upsert+4da
#5  0x56472f1a4141 in vinyl_space_execute_upsert+66
#6  0x56472f1f30b0 in space_execute_dml+211
#7  0x56472f210cdd in _ZL10process_rwP7requestP5spacePP5tuple+91
#8  0x56472f214023 in box_process1+8d
#9  0x56472f21463c in box_upsert+c4
#10 0x56472f236fd8 in lbox_upsert+131
#11 0x56472f286de7 in lj_BC_FUNCC+34
#12 0x56472f2984f4 in lua_pcall+34
#13 0x56472f24d9f3 in luaT_call+29
#14 0x56472f247ab0 in lua_fiber_run_f+74
#15 0x56472f172d9f in _ZL16fiber_cxx_invokePFiP13__va_list_tagES0_+1e
#16 0x56472f26232b in fiber_loop+41
#17 0x56472f3c687f in coro_init+4c
#18 (nil) in +4c
[001] vinyl/ddl.test.lua
[001]
```
And also got this mismach. May be it somehow connected.
```
[001] vinyl/ddl.test.lua                                              [ fail ]
[001]
[001] Test failed! Result content mismatch:
[001] --- vinyl/ddl.result	Fri Oct 26 21:19:14 2018
[001] +++ ddl.reject	Fri Oct 26 21:45:16 2018
[001] @@ -115,6 +115,7 @@
[001]  ...
[001]  pk:alter{parts = {2, 'unsigned'}} -- success: space is empty now
[001]  ---
[001] +- error: Vinyl does not support rebuilding the primary index of a non-empty space
[001]  ...
[001]  space:replace{1, 2}
[001]  ---
[001] @@ -127,7 +128,8 @@
[001]  ...
[001]  space:select()
[001]  ---
[001] -- - [2, 2]
[001] +- - [1, 2]
[001] +  - [2, 2]
[001]  ...
[001]  space:drop()
```

Steps to reproduce:
```
cat <<EOF> Dockerfile.sigabrt-vinyl-ddl
FROM packpack/packpack:debian-stretch
WORKDIR /tarantool
RUN set -x \
    && sudo apt-get update \
    && apt-get install -y -f \
       build-essential cmake coreutils sed \
       libreadline-dev libncurses5-dev libyaml-dev libssl-dev \
       libcurl4-openssl-dev libunwind-dev libicu-dev \
       python python-pip python-setuptools python-dev \
       python-msgpack python-yaml python-argparse python-six python-gevent \
       lcov ruby \
    && git clone https://github.com/tarantool/tarantool --recurse-submodules . \
    && git checkout 1.10 \
    && cmake . -DCMAKE_BUILD_TYPE=RelWithDebInfoWError \
    && make -j
ENTRYPOINT /bin/bash
EOF
docker image build . -f Dockerfile.sigabrt-vinyl-ddl -t reproduce2
docker run --rm -it reproduce2
# from inside docker
sed -i 's/is_parallel = False/is_parallel = True/' test/vinyl/suite.ini
cd test && python test-run.py $(for i in $(seq 1 10); do echo -n " vinyl/iterator.test vinyl/ddl.test"; done)
```

**Comment by locker** [comment]
Duplicate #3420
