### ISSUE TITLE
assertion filure in lj_debug_funcname()

### ISSUE THREAD

**Issue by edam** [tarantool/tarantool#3826]
Tarantool version:
1.10.2 (built from source)

OS version:
64-bit Linux
kernel 4.11.0-1-amd64

Bug description:
Sporadic assertion failure inside LuaJIT. During daily development usage, it happens about once every day or two.

Steps to reproduce:
Unknown. :'(

Optional (but very desirable):
```
tarantool: lj_debug.c:302: lj_debug_funcname: Assertion `pc < pt->sizebc' failed.

Thread 1 "tarantool" received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
51      ../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007ffff4310231 in __GI_abort () at abort.c:79
#2  0x00007ffff43079da in __assert_fail_base (
    fmt=0x7ffff445ad48 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", 
    assertion=assertion@entry=0x55555590b2c0 "pc < pt->sizebc", 
    file=file@entry=0x55555590ac40 "lj_debug.c", line=line@entry=302, 
    function=function@entry=0x55555590b980 <__PRETTY_FUNCTION__.5190> "lj_debug_funcname") at assert.c:92
#3  0x00007ffff4307a52 in __GI___assert_fail (
    assertion=0x55555590b2c0 "pc < pt->sizebc", file=0x55555590ac40 "lj_debug.c", 
    line=302, function=0x55555590b980 <__PRETTY_FUNCTION__.5190> "lj_debug_funcname")
    at assert.c:101
#4  0x00005555556b375a in lj_debug_funcname (L=0x40ba6698, frame=0x40bce520, 
    name=0x7fffefd4fa78) at lj_debug.c:302
#5  0x00005555556b445d in lj_debug_getinfo (L=0x40ba6698, what=0x55555590b884 "nlf", 
    ar=0x7fffefd4fa70, ext=0) at lj_debug.c:483
#6  0x00005555556b49b6 in lua_getinfo (L=0x40ba6698, what=0x55555590b883 "Snlf", 
    ar=0x7fffefd4fa70) at lj_debug.c:528
#7  0x00005555556b5408 in luaL_traceback (L=0x40ba6698, L1=0x40ba6698, msg=0x0, level=2)
    at lj_debug.c:674
#8  0x00005555557573fb in lj_cf_debug_traceback (L=0x40ba6698) at lib_debug.c:392
#9  0x00005555556a2c3b in lj_BC_FUNCC ()
#10 0x00005555556a9984 in lj_err_run (L=0x40ba6698) at lj_err.c:620
#11 0x00005555556a9b1e in err_msgv (L=0x40ba6698, em=LJ_ERR_BADOPRV) at lj_err.c:635
#12 0x00005555556a9d95 in lj_err_optype (L=0x40ba6698, o=0x40bce6c8, opm=LJ_ERR_OPINDEX)
    at lj_err.c:671
#13 0x00005555556b09fe in lj_meta_tset (L=0x40ba6698, o=0x40bce6c8, k=0x7fffefd4fe50)
    at lj_meta.c:185
#14 0x00005555556a316a in lj_vmeta_tsetv ()
#15 0x00005555556c579e in lua_pcall (L=0x40ba6698, nargs=1, nresults=-1, errfunc=0)
#16 0x00005555556661e1 in luaT_call (L=0x40ba6698, nargs=1, nreturns=-1)
    at /home/edam/src/work/tarantool/tarantool/src/lua/utils.c:947
#17 0x000055555565f233 in lua_fiber_run_f (ap=0x7fffefc01310)
    at /home/edam/src/work/tarantool/tarantool/src/lua/fiber.c:301
#18 0x00005555555718fe in fiber_cxx_invoke(fiber_func, typedef __va_list_tag __va_list_tag *) (f=0x55555565f1bf <lua_fiber_run_f>, ap=0x7fffefc01310)
    at /home/edam/src/work/tarantool/tarantool/src/fiber.h:657
#19 0x000055555567ba0a in fiber_loop (data=0x0)
    at /home/edam/src/work/tarantool/tarantool/src/fiber.c:640
#20 0x000055555584e193 in coro_init ()
    at /home/edam/src/work/tarantool/tarantool/third_party/coro/coro.c:110
```

Since I am not able to provide any step to reproduce this, if you can suggest anything that I can run/do anything on my machine, I'm more than happy to help.

**Comment by kyukhin** [comment]
They only think we need is a way to reproduce. Maybe some VM exists where it fails?

**Comment by kyukhin** [comment]
No answer, closing.
