### ISSUE TITLE
Vinyl replica join fails

### ISSUE THREAD

**Issue by locker** [tarantool/tarantool#3968]
**Tarantool version:**
2.1.1-225-gaae0bb6c
1.10.2-124-gc2cc388f

**OS version:**
Linux

**Bug description:**
An attempt to join a replica to a cluster that has vinyl spaces fails - the replica crashes with:
```
Segmentation fault
  code: SEGV_MAPERR
  addr: (nil)
  context: 0x7f42d4d4f7c0
  siginfo: 0x7f42d4d4f8f0
  rax      0x0                0
  rbx      0x0                0
  rcx      0x348              840
  rdx      0x7f42d4d78a98     139925015464600
  rsi      0x8                8
  rdi      0x7f42d4d78a70     139925015464560
  rsp      0x7f42d4d4fd50     139925015297360
  rbp      0x7f42d4d4fd60     139925015297376
  r8       0x56115755e180     94632479678848
  r9       0x7f42c3008000     139924716158976
  r10      0x3350cc3dbb4698   14444061951477400
  r11      0x7f42c30081e1     139924716159457
  r12      0x0                0
  r13      0x0                0
  r14      0x0                0
  r15      0x0                0
  rip      0x561155c162db     94632453169883
  eflags   0x10206            66054
  cs       0x33               51
  gs       0x0                0
  fs       0x0                0
  cr2      0x0                0
  err      0x4                4
  oldmask  0x0                0
  trapno   0xe                14
Current time: 1549549520
Please file a bug at http://github.com/tarantool/tarantool/issues
Attempting backtrace... Note: since the server has already crashed,
this may fail as well
#0  0x561155c7fe6d in print_backtrace+9
#1  0x561155b5f376 in _ZL12sig_fatal_cbiP9siginfo_tPv+1e7
#2  0x7f42dac110c0 in __restore_rt+0
#3  0x561155c162db in journal_write+13
#4  0x561155c16fd7 in txn_write_to_wal+168
#5  0x561155c1732f in txn_commit+159
#6  0x561155bebbca in vy_deferred_delete_batch_process_f+11d
#7  0x561155c8289b in cmsg_deliver+30
#8  0x561155c838e6 in fiber_pool_f+19d
#9  0x561155b5ec73 in _ZL16fiber_cxx_invokePFiP13__va_list_tagES0_+1e
#10 0x561155c7cc84 in fiber_loop+82
#11 0x561155e5bd7c in coro_init+4c
#12 (nil) in +4c
Aborted
```

**Steps to reproduce:**
1. Create a Tarantool instance with a vinyl space
```
box.cfg{
    listen = 12345,
    checkpoint_interval = 0,
}

box.once('init', function()
    local s = box.schema.space.create('test', {engine = 'vinyl'})
    s:create_index('pk')
    s:create_index('sk', {parts = {2, 'unsigned'}, unique = false})
    box.schema.user.grant('guest', 'replication')
    box.snapshot()
    local pad = string.rep('x', 1000)
    for i = 1, 10 * 1000 do
        s:replace{math.random(1000), math.random(100000), pad}
    end
end)
```
2. Attempt to join a replica with a tight memory limit:
```
box.cfg{vinyl_memory = 4 * 1024 * 1024, replication = 12345}
```

**Optional (but very desirable):**
Full log from the replica:
```
2019-02-07 17:31:05.564 [31569] main/102/interactive C> Tarantool 2.1.1-209-g76edf94b
2019-02-07 17:31:05.564 [31569] main/102/interactive C> log level 5
2019-02-07 17:31:05.564 [31569] main/102/interactive I> mapping 268435456 bytes for memtx tuple arena...
2019-02-07 17:31:05.564 [31569] main/102/interactive I> mapping 16777216 bytes for vinyl tuple arena...
2019-02-07 17:31:05.575 [31569] main/102/interactive I> connecting to 1 replicas
2019-02-07 17:31:05.579 [31569] main/108/applier/ I> remote master is 2.1.1 at 0.0.0.0:12345
2019-02-07 17:31:05.579 [31569] main/102/interactive I> connected to 1 replicas
2019-02-07 17:31:05.579 [31569] main/102/interactive I> bootstrapping replica from 00042e64-d050-4e47-b7b1-1c5cd244a911 at 0.0.0.0:12345
2019-02-07 17:31:05.612 [31569] main/108/applier/ I> initial data received
2019-02-07 17:31:05.807 [31569] main/106/vinyl.scheduler I> 512/1: dump started
2019-02-07 17:31:05.808 [31569] vinyl.dump.0/102/task I> writing `./512/1/00000000000000000004.run'
2019-02-07 17:31:05.857 [31569] vinyl.dump.0/102/task I> writing `./512/1/00000000000000000004.index'
2019-02-07 17:31:05.950 [31569] main/106/vinyl.scheduler I> 512/1: dump completed
2019-02-07 17:31:05.950 [31569] main/106/vinyl.scheduler I> 512/0: dump started
2019-02-07 17:31:05.950 [31569] vinyl.dump.0/103/task I> writing `./512/0/00000000000000000006.run'
2019-02-07 17:31:06.000 [31569] vinyl.dump.0/103/task I> writing `./512/0/00000000000000000006.index'
2019-02-07 17:31:06.059 [31569] main/106/vinyl.scheduler I> 512/0: dump completed
2019-02-07 17:31:06.059 [31569] main/106/vinyl.scheduler I> dumped 4192605 bytes in 0.3 sec
2019-02-07 17:31:06.419 [31569] main/106/vinyl.scheduler I> 512/1: dump started
2019-02-07 17:31:06.419 [31569] vinyl.dump.0/104/task I> writing `./512/1/00000000000000000008.run'
2019-02-07 17:31:06.501 [31569] vinyl.dump.0/104/task I> writing `./512/1/00000000000000000008.index'
2019-02-07 17:31:06.559 [31569] main/106/vinyl.scheduler I> 512/1: dump completed
2019-02-07 17:31:06.559 [31569] main/106/vinyl.scheduler I> 512/0: dump started
2019-02-07 17:31:06.569 [31569] vinyl.dump.0/105/task I> writing `./512/0/00000000000000000010.run'
2019-02-07 17:31:06.570 [31569] main/106/vinyl.scheduler I> 512/1: started compacting range (-inf..inf), runs 2/2
2019-02-07 17:31:06.570 [31569] vinyl.compaction.0/102/task I> writing `./512/1/00000000000000000011.run'
2019-02-07 17:31:06.618 [31569] vinyl.dump.0/105/task I> writing `./512/0/00000000000000000010.index'
2019-02-07 17:31:06.660 [31569] vinyl.compaction.0/102/task I> writing `./512/1/00000000000000000011.index'
2019-02-07 17:31:06.761 [31569] main/106/vinyl.scheduler I> 512/0: dump completed
2019-02-07 17:31:06.761 [31569] main/106/vinyl.scheduler I> dumped 4192940 bytes in 0.4 sec
2019-02-07 17:31:06.761 [31569] main/106/vinyl.scheduler I> 512/0: started compacting range (-inf..inf), runs 2/2
2019-02-07 17:31:06.761 [31569] vinyl.compaction.1/102/task I> writing `./512/0/00000000000000000013.run'
2019-02-07 17:31:06.777 [31569] main/106/vinyl.scheduler I> removed ./512/1/00000000000000000004.index
2019-02-07 17:31:06.777 [31569] main/106/vinyl.scheduler I> removed ./512/1/00000000000000000004.run
2019-02-07 17:31:06.778 [31569] main/106/vinyl.scheduler I> removed ./512/1/00000000000000000008.index
2019-02-07 17:31:06.778 [31569] main/106/vinyl.scheduler I> removed ./512/1/00000000000000000008.run
2019-02-07 17:31:06.778 [31569] main/106/vinyl.scheduler I> 512/1: completed compacting range (-inf..inf)
2019-02-07 17:31:07.017 [31569] main/108/applier/ I> final data received
2019-02-07 17:31:07.021 [31569] main/102/interactive I> vinyl checkpoint started
2019-02-07 17:31:07.021 [31569] main/106/vinyl.scheduler I> 512/1: dump started
2019-02-07 17:31:07.021 [31569] vinyl.dump.0/106/task I> writing `./512/1/00000000000000000015.run'
2019-02-07 17:31:07.024 [31569] snapshot/101/main I> saving snapshot `./00000000000000010007.snap.inprogress'
2019-02-07 17:31:07.028 [31569] vinyl.compaction.1/102/task I> writing `./512/0/00000000000000000013.index'
2019-02-07 17:31:07.061 [31569] snapshot/101/main I> done
2019-02-07 17:31:07.095 [31569] vinyl.dump.0/106/task I> writing `./512/1/00000000000000000015.index'
2019-02-07 17:31:07.179 [31569] main/106/vinyl.scheduler I> removed ./512/0/00000000000000000006.index
2019-02-07 17:31:07.180 [31569] main/106/vinyl.scheduler I> removed ./512/0/00000000000000000006.run
2019-02-07 17:31:07.180 [31569] main/106/vinyl.scheduler I> removed ./512/0/00000000000000000010.index
2019-02-07 17:31:07.180 [31569] main/106/vinyl.scheduler I> removed ./512/0/00000000000000000010.run
2019-02-07 17:31:07.180 [31569] main/106/vinyl.scheduler I> 512/0: completed compacting range (-inf..inf)
2019-02-07 17:31:07.229 [31569] main/106/vinyl.scheduler I> 512/1: dump completed
2019-02-07 17:31:07.229 [31569] main/106/vinyl.scheduler I> 512/0: dump started
2019-02-07 17:31:07.229 [31569] main/106/vinyl.scheduler I> 512/1: started compacting range (-inf..inf), runs 2/2
2019-02-07 17:31:07.229 [31569] vinyl.dump.0/107/task I> writing `./512/0/00000000000000000018.run'
2019-02-07 17:31:07.230 [31569] vinyl.compaction.1/103/task I> writing `./512/1/00000000000000000019.run'
2019-02-07 17:31:07.313 [31569] vinyl.dump.0/107/task I> writing `./512/0/00000000000000000018.index'
2019-02-07 17:31:07.338 [31569] vinyl.compaction.1/103/task I> writing `./512/1/00000000000000000019.index'
2019-02-07 17:31:07.439 [31569] main/106/vinyl.scheduler I> 512/0: dump completed
2019-02-07 17:31:07.439 [31569] main/106/vinyl.scheduler I> dumped 2932387 bytes in 0.5 sec
2019-02-07 17:31:07.439 [31569] main/102/interactive I> vinyl checkpoint completed
2019-02-07 17:31:07.439 [31569] main/106/vinyl.scheduler I> 512/0: started compacting range (-inf..inf), runs 2/2
2019-02-07 17:31:07.439 [31569] vinyl.compaction.0/103/task I> writing `./512/0/00000000000000000021.run'
Segmentation fault
  code: SEGV_MAPERR
  addr: (nil)
  context: 0x7f17f114f7c0
  siginfo: 0x7f17f114f8f0
  rax      0x0                0
  rbx      0x0                0
  rcx      0x348              840
  rdx      0x7f17f1174a98     139740805810840
  rsi      0x8                8
  rdi      0x7f17f1174a70     139740805810800
  rsp      0x7f17f114fd50     139740805659984
  rbp      0x7f17f114fd60     139740805660000
  r8       0x5577295a7ae0     93970283264736
  r9       0x7f17e0008000     139740519104512
  r10      0xa53e522f6251d    2906993366279453
  r11      0x7f17e00081e1     139740519104993
  r12      0x0                0
  r13      0x0                0
  r14      0x0                0
  r15      0x0                0
  rip      0x5577274f82db     93970248991451
  eflags   0x10206            66054
  cs       0x33               51
  gs       0x0                0
  fs       0x0                0
  cr2      0x0                0
  err      0x4                4
  oldmask  0x0                0
  trapno   0xe                14
Current time: 1549549867
Please file a bug at http://github.com/tarantool/tarantool/issues
Attempting backtrace... Note: since the server has already crashed,
this may fail as well
#0  0x557727561e6d in print_backtrace+9
#1  0x557727441376 in _ZL12sig_fatal_cbiP9siginfo_tPv+1e7
#2  0x7f17f72a70c0 in __restore_rt+0
#3  0x5577274f82db in journal_write+13
#4  0x5577274f8fd7 in txn_write_to_wal+168
#5  0x5577274f932f in txn_commit+159
#6  0x5577274cdbca in vy_deferred_delete_batch_process_f+11d
#7  0x55772756489b in cmsg_deliver+30
#8  0x5577275658e6 in fiber_pool_f+19d
#9  0x557727440c73 in _ZL16fiber_cxx_invokePFiP13__va_list_tagES0_+1e
#10 0x55772755ec84 in fiber_loop+82
#11 0x55772773dd7c in coro_init+4c
#12 (nil) in +4c
Aborted
```

**Comment by locker** [comment]
Affects Mail.ru FRS.
