### ISSUE TITLE
Segfault on pragma table_info executed over binary protocol

### ISSUE THREAD

**Issue by Totktonada** [tarantool/tarantool#3974]
Version: 2.1.1-237-gf1bd33a8a.

How to reproduce:

```
#!/usr/bin/env tarantool

local net_box = require('net.box')
local yaml = require('yaml')

box.cfg({listen = 3301})
box.schema.user.grant('guest', 'read,write,execute,create,drop', 'universe',
    nil, {if_not_exists = true})

local conn = net_box.connect('localhost:3301')
print(yaml.encode(conn:execute('create table T(ID int primary key)')))
print(yaml.encode(conn:execute('pragma table_info(T)')))
```

It does not matter whether the table exists.

Backtrace:

```
#0  0x00007ffff6c50e91 in __strlen_avx2 () from /lib64/libc.so.6
#1  0x000055555565c4b7 in sql_get_description (stmt=0x555555a97158, out=0x7fffdb040468, column_count=6) at /usr/src/debug/dev-db/tarantool-9999/tarantool-9999/src/box/execute.c:491
#2  0x000055555565cbbb in sql_response_dump (response=0x7ffff408fe50, out=0x7fffdb040468) at /usr/src/debug/dev-db/tarantool-9999/tarantool-9999/src/box/execute.c:573
#3  0x0000555555580736 in tx_process_sql (m=0x7fffdb0080d0) at /usr/src/debug/dev-db/tarantool-9999/tarantool-9999/src/box/iproto.cc:1648
#4  0x00005555556a1e95 in cmsg_deliver (msg=0x7fffdb0080d0) at /usr/src/debug/dev-db/tarantool-9999/tarantool-9999/src/cbus.c:353
#5  0x00005555556a2edc in fiber_pool_f (ap=0x7ffff40008c0) at /usr/src/debug/dev-db/tarantool-9999/tarantool-9999/src/fiber_pool.c:64
#6  0x0000555555579b49 in fiber_cxx_invoke(fiber_func, typedef __va_list_tag __va_list_tag *) (f=0x5555556a2d3f <fiber_pool_f>, ap=0x7ffff40008c0)
    at /usr/src/debug/dev-db/tarantool-9999/tarantool-9999/src/fiber.h:653
#7  0x000055555569c290 in fiber_loop (data=0x0) at /usr/src/debug/dev-db/tarantool-9999/tarantool-9999/src/fiber.c:650
#8  0x00005555557f84fc in coro_init () at /usr/src/debug/dev-db/tarantool-9999/tarantool-9999/third_party/coro/coro.c:110
```

Tarantool-c ODBC branch uses pragma_info in the [SQLSpecialColumns()][1] function implementation.

[1]: https://docs.microsoft.com/en-us/sql/odbc/reference/syntax/sqlspecialcolumns-function?view=sql-server-2017

**Comment by Korablev77** [comment]
This example doesn't explode on this branch: https://github.com/tarantool/tarantool/tree/imeevma/gh-3832-no-column-types

When it hits 2.1, this issue will be closed.

Problem is in absence of types for resulting set during 'pragma' execution.

**Comment by Totktonada** [comment]
@Korablev77 Thank you for the clarification. I'm okay.
