### ISSUE TITLE
regression: lack of SQL_BIND lead to an assertion fault

### ISSUE THREAD

**Issue by rybakit** [tarantool/tarantool#4077]
Tarantool version:
2.2.0-5-g51e2d002e

OS version:
https://github.com/tarantool/docker/blob/master/2.x/Dockerfile#L1

Bug description:
Tarantool segfaults while sending iproto execute request. The same requests were working w/o any problem on 2.1.x.

Steps to reproduce:

```
git clone https://github.com/tarantool-php/client.git
cd client
git checkout 52034ad
./dockerfile.sh | docker build -t client -
docker network create tarantool-php
docker run -d --net=tarantool-php -p 3301:3301 --name=tarantool -v `pwd`:/client tarantool/tarantool:2 tarantool /client/tests/Integration/client.lua
docker run --rm --net=tarantool-php --name client -v $(pwd):/client -w /client client
```

Error:
```
Segmentation fault                                                                                                                                     [5/881]
  code: SEGV_MAPERR
  addr: 0
  context: 0x7f69a5bff880
  siginfo: 0x7f69a5bff9b0
  rax      0x7f69a5800940     140091724925248
  rbx      0x7f69a5410140     140091720794432
  rcx      0x7f69a5818068     140091725021288
  rdx      0x7f69a5818090     140091725021328
  rsi      0x7f69a5bffe88     140091729116808
  rdi      0x0                0
  rsp      0x7f69a5bffe20     140091729116704
  rbp      0x7f69a5bffe70     140091729116784
  r8       0x0                0
  r9       0x0                0
  r10      0x0                0
  r11      0x246              582
  r12      0xfffffffffffefa20 -67040
  r13      0xfffffffffffefa20 -67040
  r14      0x55efad6f7860     94487895308384
  r15      0x55efad975298     94487897920152
  rip      0x55efad48f1e8     94487892783592
  eflags   0x10202            66050
  cs       0x33               51
  gs       0x0                0
  fs       0x0                0
  cr2      0x0                0
  err      0x4                4
  oldmask  0x0                0
  trapno   0xe                14
Current time: 1553285639
Please file a bug at http://github.com/tarantool/tarantool/issues
Attempting backtrace... Note: since the server has already crashed,
this may fail as well
#0  0x55efad4c2d79 in print_backtrace+9
#1  0x55efad3c272a in _ZL12sig_fatal_cbiP9siginfo_tPv+ca
#2  0x7f69a9b58e17 in sigwaitinfo+8
#3  0x55efad3c551b in _ZL14tx_process_sqlP4cmsg+ab
#4  0x55efad4c4544 in cmsg_deliver+14
#5  0x55efad4c50ef in fiber_pool_f+ff
#6  0x55efad3c20ec in _ZL16fiber_cxx_invokePFiP13__va_list_tagES0_+c
#7  0x55efad4bf9a0 in fiber_loop+30
#8  0x55efad60b54f in coro_init+3f
```

@Totktonada's findings:

```
Кажется, мы SQL_BIND стали ждать в обязательном порядке.
После этого:

diff --git a/src/box/iproto.cc b/src/box/iproto.cc
index 3b0ba6234..98bfcbc18 100644
--- a/src/box/iproto.cc
+++ b/src/box/iproto.cc
@@ -1633,7 +1633,8 @@ tx_process_sql(struct cmsg *m)
                goto error;
        assert(msg->header.type == IPROTO_EXECUTE);
        tx_inject_delay();
-       bind_count = sql_bind_list_decode(msg->sql.bind, &bind);
+       if (msg->sql.bind != NULL)
+               bind_count = sql_bind_list_decode(msg->sql.bind, &bind);
        if (bind_count < 0)
                goto error;
        sql = msg->sql.sql_text;



Проходит.
Вот такой пакет от коннектора приходит:

ce 00 00 00 27 82 00 0b
01 00 81 40 bf 44 52 4f
50 20 54 41 42 4c 45 20
49 46 20 45 58 49 53 54
53 20 74 61 62 6c 65 5f
65 78 65 63

Воркэраунд — энкодить пустой массив для bind-параметров.
```

**Comment by Totktonada** [comment]
The fail appears after that update: https://github.com/tarantool/docker/commit/a04277c0361b1b3b9612996304659ef058a5fa65

**Comment by rybakit** [comment]
@Totktonada @kyukhin thanks!
