### ISSUE TITLE
Segfault  (sql, transaction)

### ISSUE THREAD

**Issue by R-omk** [tarantool/tarantool#4157]
Tarantool version:
2.2.0-128-g7b56f1fef   
OS version:
Ubuntu 18.04.2 LTS
Linux 4.15.0-46-generic
Docker 18.09.5
Docker base image alpine:3.5

Bug description:
 Segmentation fault

Steps to reproduce:

install docker , docker-compose, make

https://gist.github.com/R-omk/2ed809c0f890fef98882596e82d9f8ba

```
git clone https://gist.github.com/2ed809c0f890fef98882596e82d9f8ba.git

cd 2ed809c0f890fef98882596e82d9f8ba

make RUN
```

Optional (but very desirable):
```
 Segmentation fault
   code: SEGV_MAPERR
   addr: 0
   context: 0x7f1fcb9ff300
   siginfo: 0x7f1fcb9ff430
   rax      0x7f20144501b8     139775755747768
   rbx      0x7f2014400e80     139775755423360
   rcx      0x180              384
   rdx      0x0                0
   rsi      0x1                1
   rdi      0x55fb792746a8     94538557769384
   rsp      0x7f1fcb9ff9b0     139774536972720
   rbp      0x7f1fcb9ff9e0     139774536972768
   r8       0x7f2014460200     139775755813376
   r9       0x7f2014460200     139775755813376
   r10      0x7f1fcb9ff100     139774536970496
   r11      0x7f2014460000     139775755812864
   r12      0x55fb792746a8     94538557769384
   r13      0x1                1
   r14      0x4                4
   r15      0x3                3
   rip      0x55fb7894f4f9     94538548180217
   eflags   0x10206            66054
   cs       0x33               51
   gs       0x0                0
   fs       0x0                0
   cr2      0x0                0
   err      0x6                6
   oldmask  0x0                0
   trapno   0xe                14
 Current time: 1555310964
 Please file a bug at http://github.com/tarantool/tarantool/issues
 Attempting backtrace... Note: since the server has already crashed, 
 this may fail as well
 #0  0x55fb787cd339 in print_backtrace+9
 #1  0x55fb786cb93a in _ZL12sig_fatal_cbiP9siginfo_tPv+ca
 #2  0x7f2018850e17 in sigwaitinfo+8
 #3  0x55fb7875c4d5 in sequence_next+2c5
 #4  0x55fb78757f7c in request_handle_sequence+14c
 #5  0x55fb78759047 in space_execute_dml+187
 #6  0x55fb7877e297 in box_process_rw+67
 #7  0x55fb78794ab4 in tarantoolsqlInsert+44
 #8  0x55fb78952c60 in sqlVdbeExec+3630
 #9  0x55fb7895587d in sql_step+16d
 #10 0x55fb7879acd9 in sql_prepare_and_execute+929
 #11 0x55fb787adf5d in lbox_execute+9d
 #12 0x55fb787e4167 in lj_BC_FUNCC+34
 #13 0x55fb787f5884 in lua_pcall+34
 #14 0x55fb787b8193 in luaT_call+13
 #15 0x55fb787b28a6 in lua_fiber_run_f+56
 #16 0x55fb786cb2fc in _ZL16fiber_cxx_invokePFiP13__va_list_tagES0_+c
 #17 0x55fb787c9f60 in fiber_loop+30
 #18 0x55fb7891721f in coro_init+3f
```

**Comment by Korablev77** [comment]
Simple reproducer:

```
box.execute("create table t(id int primary key autoincrement);")
box.execute('start transaction;') box.execute('insert into t values(null)') box.commit()
```
