### ISSUE TITLE
segfault on insert to temporary space with hash index with sequence

### ISSUE THREAD

**Issue by rtokarev** [tarantool/tarantool#4266]
Tarantool version: 1.10.3-68-geacf912

OS version: CentOS 7

Steps to reproduce:

```
Tarantool 1.10.3-68-geacf912
type 'help' for interactive help
tarantool> box.cfg()
2019-06-03 15:05:52.029 [12685] main/101/interactive C> Tarantool 1.10.3-68-geacf912
2019-06-03 15:05:52.029 [12685] main/101/interactive C> log level 5
2019-06-03 15:05:52.029 [12685] main/101/interactive I> mapping 268435456 bytes for memtx tuple arena...
2019-06-03 15:05:52.029 [12685] main/101/interactive I> mapping 134217728 bytes for vinyl tuple arena...
2019-06-03 15:05:52.030 [12685] main/101/interactive I> instance uuid 9b4c439f-ba56-45ec-a65a-552b2754c6a7
2019-06-03 15:05:52.030 [12685] main/101/interactive I> initializing an empty data directory
2019-06-03 15:05:52.033 [12685] main/101/interactive I> assigned id 1 to replica 9b4c439f-ba56-45ec-a65a-552b2754c6a7
2019-06-03 15:05:52.033 [12685] main/101/interactive I> cluster uuid 90994bc4-687c-4530-a0f8-65466b1a0ba1
2019-06-03 15:05:52.033 [12685] snapshot/101/main I> saving snapshot `./00000000000000000000.snap.inprogress'
2019-06-03 15:05:52.066 [12685] snapshot/101/main I> done
2019-06-03 15:05:52.067 [12685] main/101/interactive I> ready to accept requests
2019-06-03 15:05:52.067 [12685] main/107/checkpoint_daemon I> started
2019-06-03 15:05:52.067 [12685] main/107/checkpoint_daemon I> scheduled the next snapshot at Mon Jun  3 16:17:47 2019
---
...

tarantool> box.schema.sequence.create('seq', { cycle = true })
2019-06-03 15:05:56.739 [12685] wal/101/main xlog.c:1024 W> fallocate is not supported, proceeding without it
---
- step: 1
  id: 1
  min: 1
  cache: 0
  uid: 1
  max: 9223372036854775807
  cycle: true
  name: seq
  start: 1
...

tarantool> s = box.schema.space.create('test', { temporary = true })
---
...

tarantool> s:create_index('primary', { sequence = 'seq', type = 'HASH' })
---
- unique: true
  parts:
  - type: unsigned
    is_nullable: false
    fieldno: 1
  sequence_id: 1
  id: 0
  space_id: 512
  name: primary
  type: HASH
...

tarantool> s:on_replace(function(old, new) end)
---
- 'function: 0x40d53950'
...

tarantool> s:insert{nil, 1}
Segmentation fault
  code: SEGV_MAPERR
  addr: (nil)
  context: 0x7f9d0bcff840
  siginfo: 0x7f9d0bcff970
  rax      0x0                0
  rbx      0x4100a378         1090560888
  rcx      0x74736574         1953719668
  rdx      0x41289ae8         1093180136
  rsi      0x1                1
  rdi      0x41e8f830         1105786928
  rsp      0x7f9d0bcffcb0     140312484773040
  rbp      0x7f9d0bcffcc0     140312484773056
  r8       0x4                4
  r9       0x4100a3b8         1090560952
  r10      0x4100a378         1090560888
  r11      0x41e8f820         1105786912
  r12      0x7f9d0bc26100     140312483881216
  r13      0x7f9d0bc26040     140312483881024
  r14      0xffffffff         4294967295
  r15      0x2                2
  rip      0x4d4f12           5066514
  eflags   0x10283            66179
  cs       0x33               51
  gs       0x0                0
  fs       0x0                0
  cr2      0x0                0
  err      0x4                4
  oldmask  0x0                0
  trapno   0xe                14
Current time: 1559563570
Please file a bug at http://github.com/tarantool/tarantool/issues
Attempting backtrace... Note: since the server has already crashed,
this may fail as well
#0  0x4fb399 in print_backtrace+9
#1  0x40fa97 in _ZL12sig_fatal_cbiP7siginfoPv+c7
#2  0x7f9d161107e0 in _L_unlock_16+2d
#3  0x4d4f12 in _ZL18lbox_push_txn_stmtP9lua_StatePv+72
#4  0x4e2c93 in lbox_trigger_run+63
#5  0x50a442 in trigger_run+32
#6  0x4b453b in txn_commit_stmt+9b
#7  0x4b6e3a in _ZL10process_rwP7requestP5spacePP5tuple+aa
#8  0x4b9c3d in box_insert+3d
#9  0x4d4b81 in lbox_insert+81
#10 0x5149e7 in lj_BC_FUNCC+34
#11 0x525f44 in lua_pcall+34
#12 0x4e6983 in luaT_call+13
#13 0x4dffe9 in lua_main+59
#14 0x4e0357 in run_script_f+307
#15 0x40ef8c in _ZL16fiber_cxx_invokePFiP13__va_list_tagES0_+c
#16 0x4f7f60 in fiber_loop+30
#17 0x6326ff in coro_init+3f
Aborted
```

**Comment by locker** [comment]
@rtokarev says the issue appeared right after commit 5dc6d79f4b73479d71f8438f8c5c00171637ba70

**Comment by sergepetrenko** [comment]
A simpler reproducer:
```
box.cfg{}
box.schema.space.create('test', {temporary = true})
box.space.test:create_index('pk')
box.space.test:on_replace(function(old, new) end)
box.space.test:insert{1}
```
