### ISSUE TITLE
Invalid read of size 4 in tarantool_lua_load_cfg

### ISSUE THREAD

**Issue by rtsisyk** [tarantool/tarantool#427]
```
valgrind ../../src/box/tarantool_box 
==19017== Memcheck, a memory error detector
==19017== Copyright (C) 2002-2013, and GNU GPL'd, by Julian Seward et al.
==19017== Using Valgrind-3.9.0 and LibVEX; rerun with -h for copyright info
==19017== Command: ../../src/box/tarantool_box
==19017== 
../../src/box/tarantool_box: updating a stale pid file
2014-08-05 18:15:19.931 [19017] 1/sched I> Mapping 109051904 bytes for a shared arena
2014-08-05 18:15:20.005 [19017] 1/sched C> version 1.5.4-1-gca38bc1
2014-08-05 18:15:20.028 [19017] 1/sched I> space 0 successfully configured
2014-08-05 18:15:20.036 [19017] 1/sched I> recovery start
2014-08-05 18:15:20.052 [19017] 1/sched I> recover from `./00000000000000000001.snap'
2014-08-05 18:15:20.060 [19017] 1/sched I> snapshot recovered, confirmed lsn: 1
2014-08-05 18:15:20.064 [19017] 1/sched I> building secondary indexes
==19017== Invalid read of size 4
==19017==    at 0x495697: lua_pushfstring (in /data/work/tarantool/stable/src/box/tarantool_box)
==19017==    by 0x4456C2: tarantool_lua_load_cfg(lua_State*, tarantool_cfg*) (init.cc:1421)
==19017==    by 0x4424A0: main (tarantool.cc:914)
==19017==  Address 0x8 is not stack'd, malloc'd or (recently) free'd
==19017== 
Segmentation fault
Current time: 1407248120
Please file a bug at http://github.com/tarantool/tarantool/issues
Attempting backtrace... Note: since the server has already crashed, 
this may fail as well
#0  0x440e42 in ?
#1  0x4e428d0 in ?
#2  0x4456c3 in ?
#3  0x4424a1 in ?
#4  0x5cacb45 in ?
```

Server works properly without valgrind.

BTW, I have debug build and don't have stack traces.

**Comment by kostja** [comment]
I've seen this before and tried to fix it - and couldn't find any cause in our code. Seems to be valgrind + luajit issue. 
Hardly relevant to our users. 
Won't fix.
