### ISSUE TITLE
Test-run (or console?) looses connection on a complex map

### ISSUE THREAD

**Issue by Gerold103** [tarantool/tarantool#4421]
Try add this to a .test.lua file, and run the test
```Lua
t = {}                                                  \
t[2] = {						\
        d = {                           		\
                [{k = 'v'}] = -1,       		\
        },                              		\
        [-1] = -1,                                      \
        h = {                           		\
                i = {                   		\
                        [true] = false, 		\
                },                      		\
                [0] = {1, 2, 3, {k = 'v'}}		\
        }                               		\
}
t
```
You will see:
```
[001] +t
[001] +[Lost current connection]
```
I don't know if the bug is about console, or test-run. But in an interactive local console it does not loose connection. And it is not a crash, because a core file is not created, and lldb sees nothing.

**Comment by Totktonada** [comment]
It is due to a key of the map type and pyyaml (that is used in test-run):

```
tarantool> {[{k = 'v'}] = 1}
---
- ? k: v
  : 1
...
```

```
>>> yaml.safe_load("""---
... - ? k: v
...   : 1
... ...
... """)
Traceback (most recent call last):
  File "<stdin>", line 5, in <module>
  File "/usr/lib/python3.7/site-packages/yaml/__init__.py", line 94, in safe_load
    return load(stream, SafeLoader)
  File "/usr/lib/python3.7/site-packages/yaml/__init__.py", line 72, in load
    return loader.get_single_data()
  File "/usr/lib/python3.7/site-packages/yaml/constructor.py", line 37, in get_single_data
    return self.construct_document(node)
  File "/usr/lib/python3.7/site-packages/yaml/constructor.py", line 46, in construct_document
    for dummy in generator:
  File "/usr/lib/python3.7/site-packages/yaml/constructor.py", line 398, in construct_yaml_map
    value = self.construct_mapping(node)
  File "/usr/lib/python3.7/site-packages/yaml/constructor.py", line 204, in construct_mapping
    return super().construct_mapping(node, deep=deep)
  File "/usr/lib/python3.7/site-packages/yaml/constructor.py", line 128, in construct_mapping
    "found unhashable key", key_node.start_mark)
yaml.constructor.ConstructorError: while constructing a mapping
  in "<unicode string>", line 2, column 3:
    - ? k: v
      ^
found unhashable key
  in "<unicode string>", line 2, column 5:
    - ? k: v
```

I don't know why test-run tries to parse a response. It seems that this patch for test-run allows your test to pass:

```diff
diff --git a/lib/admin_connection.py b/lib/admin_connection.py
index 005a56a..e82cd00 100644
--- a/lib/admin_connection.py
+++ b/lib/admin_connection.py
@@ -75,11 +75,8 @@ class ExecMixIn(object):
             if (res.rfind("\n...\n") >= 0 or res.rfind("\r\n...\r\n") >= 0):
                 break
 
-        try:
-            yaml.safe_load(res)
-        finally:
-            if not silent:
-                sys.stdout.write(res.replace("\r\n", "\n"))
+        if not silent:
+            sys.stdout.write(res.replace("\r\n", "\n"))
         return res
```

I need to dig a bit deeper to understand why this code is (was?) needed.

**Comment by Totktonada** [comment]
See https://github.com/yaml/pyyaml/issues/88 re pyyaml and a map type as a key.

**Comment by Gerold103** [comment]
I need it to test JSON updates for complex maps.

**Comment by Totktonada** [comment]
I can suggest to map a map to a list of pairs of a key and a value as the temporary workaround for now.

**Comment by Gerold103** [comment]
An array as a key does not work either. But ok, I just will use scalar non-string values like booleans and numbers.

**Comment by Totktonada** [comment]
The `safe_load()` call seems to be to a check a yaml output for correctness. Don't sure whether we really need it. I think it worth to remove the check at least because it does not handle all needed cases. I'll proceed with that.
