### ISSUE TITLE
lua: pwd.getpwall() hangs on CentOS 6

### ISSUE THREAD

**Issue by Totktonada** [tarantool/tarantool#4447]
Tarantool version: 2.1.2-155-gc87609e.

pwd.getpwall() hangs when called on CentOS 6.

After a preliminary [patch](f5d8331e833d6a29dc7a869e681e03fb8e03a5f8) tarantool calls it during initialization. We need to skip this call for now (to allow tarantool to be runned on CentOS 6) and then investigate the issue itself.

Looks limilar to #4428, but don't sure.

```
[root@ee0df9c7eee9 tarantool]# gdb ./src/tarantool
<...>
(gdb) run
<...>
tarantool> require('pwd').getpwall()

Program received signal SIGINT, Interrupt.
0x00007f9700ec561a in mmap64 () from /lib64/libc.so.6
(gdb) bt
#0  0x00007f9700ec561a in mmap64 () from /lib64/libc.so.6
#1  0x00007f9700e461cc in _IO_file_doallocate_internal () from /lib64/libc.so.6
#2  0x00007f9700e5368c in _IO_doallocbuf_internal () from /lib64/libc.so.6
#3  0x00007f9700e51c44 in _IO_new_file_underflow () from /lib64/libc.so.6
#4  0x00007f9700e536ce in _IO_default_uflow_internal () from /lib64/libc.so.6
#5  0x00007f9700e47daa in _IO_getline_info_internal () from /lib64/libc.so.6
#6  0x00007f9700e50be1 in fgets_unlocked () from /lib64/libc.so.6
#7  0x00007f96ff815651 in _nss_files_getgrgid_r () from /lib64/libnss_files.so.2
#8  0x00007f9700e8a5fd in getgrgid_r@@GLIBC_2.2.5 () from /lib64/libc.so.6
#9  0x00007f9700e89d3f in getgrgid () from /lib64/libc.so.6
#10 0x00000000005537eb in lj_vm_ffi_call ()
#11 0x00000000005e15c1 in lj_ccall_func (L=0x41d13378, cd=0x41940900) at lj_ccall.c:1150
#12 0x0000000000606a37 in lj_cf_ffi_meta___call (L=0x41d13378) at lib_ffi.c:230
#13 0x000000000055183b in lj_BC_FUNCC ()
#14 0x00000000005735b6 in lua_pcall (L=0x41d13378, nargs=0, nresults=0, errfunc=0) at lj_api.c:1139
#15 0x0000000000517f9f in luaT_call (L=0x41d13378, nargs=0, nreturns=0) at /tarantool/src/lua/utils.c:975
#16 0x000000000050ff29 in lua_main (L=0x41d13378, argc=1, argv=0x1518fc0) at /tarantool/src/lua/init.c:534
#17 0x0000000000510738 in run_script_f (ap=0x7f96ff400378) at /tarantool/src/lua/init.c:632
#18 0x0000000000410417 in fiber_cxx_invoke(fiber_func, typedef __va_list_tag __va_list_tag *) (f=0x50ffaf <run_script_f>, ap=0x7f96ff400378) at /tarantool/src/lib/core/fiber.h:666
#19 0x000000000052d765 in fiber_loop (data=0x0) at /tarantool/src/lib/core/fiber.c:694
#20 0x0000000000739f7f in coro_init () at /tarantool/third_party/coro/coro.c:110
(gdb) cont
Continuing.

Program received signal SIGINT, Interrupt.
0x00007f9700ebb7f0 in __read_nocancel () from /lib64/libc.so.6
(gdb) bt
#0  0x00007f9700ebb7f0 in __read_nocancel () from /lib64/libc.so.6
#1  0x00007f9700e51a7e in _IO_file_read_internal () from /lib64/libc.so.6
#2  0x00007f9700e51bc8 in _IO_new_file_underflow () from /lib64/libc.so.6
#3  0x00007f9700e536ce in _IO_default_uflow_internal () from /lib64/libc.so.6
#4  0x00007f9700e47daa in _IO_getline_info_internal () from /lib64/libc.so.6
#5  0x00007f9700e50be1 in fgets_unlocked () from /lib64/libc.so.6
#6  0x00007f96ff815a61 in _nss_files_getpwent_r () from /lib64/libnss_files.so.2
#7  0x00007f9700edd882 in __nss_getent_r () from /lib64/libc.so.6
#8  0x00007f9700e8bab6 in getpwent_r@@GLIBC_2.2.5 () from /lib64/libc.so.6
#9  0x00007f9700edd493 in __nss_getent () from /lib64/libc.so.6
#10 0x00007f9700e8b6e2 in getpwent () from /lib64/libc.so.6
#11 0x00000000005537eb in lj_vm_ffi_call ()
#12 0x00000000005e15c1 in lj_ccall_func (L=0x41d13378, cd=0x41940650) at lj_ccall.c:1150
#13 0x0000000000606a37 in lj_cf_ffi_meta___call (L=0x41d13378) at lib_ffi.c:230
#14 0x000000000055183b in lj_BC_FUNCC ()
#15 0x00000000005735b6 in lua_pcall (L=0x41d13378, nargs=0, nresults=0, errfunc=0) at lj_api.c:1139
#16 0x0000000000517f9f in luaT_call (L=0x41d13378, nargs=0, nreturns=0) at /tarantool/src/lua/utils.c:975
#17 0x000000000050ff29 in lua_main (L=0x41d13378, argc=1, argv=0x1518fc0) at /tarantool/src/lua/init.c:534
#18 0x0000000000510738 in run_script_f (ap=0x7f96ff400378) at /tarantool/src/lua/init.c:632
#19 0x0000000000410417 in fiber_cxx_invoke(fiber_func, typedef __va_list_tag __va_list_tag *) (f=0x50ffaf <run_script_f>, ap=0x7f96ff400378) at /tarantool/src/lib/core/fiber.h:666
#20 0x000000000052d765 in fiber_loop (data=0x0) at /tarantool/src/lib/core/fiber.c:694
#21 0x0000000000739f7f in coro_init () at /tarantool/third_party/coro/coro.c:110
(gdb) cont
Continuing.

Program received signal SIGINT, Interrupt.
0x00007f9700ebb600 in __open_nocancel () from /lib64/libc.so.6
(gdb) bt
#0  0x00007f9700ebb600 in __open_nocancel () from /lib64/libc.so.6
#1  0x00007f9700e52ebb in _IO_new_file_fopen () from /lib64/libc.so.6
#2  0x00007f9700e46e06 in __fopen_internal () from /lib64/libc.so.6
#3  0x00007f96ff814ff3 in internal_setent () from /lib64/libnss_files.so.2
#4  0x00007f96ff8155b5 in _nss_files_getgrgid_r () from /lib64/libnss_files.so.2
#5  0x00007f9700e8a5fd in getgrgid_r@@GLIBC_2.2.5 () from /lib64/libc.so.6
#6  0x00007f9700e89d3f in getgrgid () from /lib64/libc.so.6
#7  0x00000000005537eb in lj_vm_ffi_call ()
#8  0x00000000005e15c1 in lj_ccall_func (L=0x41d13378, cd=0x41940900) at lj_ccall.c:1150
#9  0x0000000000606a37 in lj_cf_ffi_meta___call (L=0x41d13378) at lib_ffi.c:230
#10 0x000000000055183b in lj_BC_FUNCC ()
#11 0x00000000005735b6 in lua_pcall (L=0x41d13378, nargs=0, nresults=0, errfunc=0) at lj_api.c:1139
#12 0x0000000000517f9f in luaT_call (L=0x41d13378, nargs=0, nreturns=0) at /tarantool/src/lua/utils.c:975
#13 0x000000000050ff29 in lua_main (L=0x41d13378, argc=1, argv=0x1518fc0) at /tarantool/src/lua/init.c:534
#14 0x0000000000510738 in run_script_f (ap=0x7f96ff400378) at /tarantool/src/lua/init.c:632
#15 0x0000000000410417 in fiber_cxx_invoke(fiber_func, typedef __va_list_tag __va_list_tag *) (f=0x50ffaf <run_script_f>, ap=0x7f96ff400378) at /tarantool/src/lib/core/fiber.h:666
#16 0x000000000052d765 in fiber_loop (data=0x0) at /tarantool/src/lib/core/fiber.c:694
#17 0x0000000000739f7f in coro_init () at /tarantool/third_party/coro/coro.c:110
```

**Comment by Totktonada** [comment]
See https://github.com/tarantool/tarantool/issues/4428#issuecomment-524118617 for a small reproducer.

**Comment by locker** [comment]
The issue affects a customer running 1.10. Probably the fix should be back-ported to all stable branches.
