### ISSUE TITLE
Assertion with least()

### ISSUE THREAD

**Issue by pgulutzan** [tarantool/tarantool#4453]
I have Ubuntu 18.04.
I have Tarantool 2.3, pulled from source today.
I execute this statement:
SELECT LEAST('a');
The result is:
tarantool> select least('a');
tarantool: /home/pgulutzan/tarantool/src/box/sql/func.c:84: minmaxFunc: Assertion `argc > 1' failed.
Aborted (core dumped)

**Comment by Korablev77** [comment]
Tarantool also crashes if invoke LEAST/GREATEST functions without arguments:
```
tarantool> select least()
Segmentation fault
  code: SEGV_MAPERR
  addr: 0x8
  context: 0x11017e598
  siginfo: 0x11017e530
Current time: 1567005047
Please file a bug at http://github.com/tarantool/tarantool/issues
Attempting backtrace... Note: since the server has already crashed, 
this may fail as well
#0  0x10d6ff02d in print_backtrace+d
#1  0x10d57c3f3 in _ZL12sig_fatal_cbiP9__siginfoPv+1f3
#2  0x7fff7cab0b5d in _sigtramp+1d
#3  0x10d9b6c5d in sqlExprCodeTarget+12cd
#4  0x10d9b9ebe in sqlExprCodeExprList+21e
#5  0x10d9e5c9a in selectInnerLoop+4fa
#6  0x10d9e0e8b in sqlSelect+157b
#7  0x10d9916d9 in yy_reduce+e39
#8  0x10d9902fb in sqlParser+11b
#9  0x10d9f0ba2 in sqlRunParser+502
#10 0x10d9d3471 in sqlPrepare+1d1
#11 0x10d9d38ef in sql_prepare_v2+4f
#12 0x10d6a6422 in sql_prepare_and_execute+42
#13 0x10d6c7c88 in lbox_execute+158
#14 0x10d73b39d in lj_BC_FUNCC+44
#15 0x10d769b90 in lua_pcall+210
#16 0x10d6de5f3 in luaT_call+23
#17 0x10d6d5341 in lua_main+d1
#18 0x10d6d5128 in run_script_f+8e8
#19 0x10d57bbea in _ZL16fiber_cxx_invokePFiP13__va_list_tagES0_+1a
#20 0x10d6fa67b in fiber_loop+bb
#21 0x10d98fd27 in coro_init+57
Abort trap: 6
```
