### ISSUE TITLE
Make sure fiber's stack guard page is created

### ISSUE THREAD

**Issue by cyrillos** [tarantool/tarantool#4541]
Strictly speaking `mprotect` call may exit with errors and on fiber creation procedure we should test for return code instead of processing without guard page set.

**Comment by cyrillos** [comment]
Here is more info from reporter
```
Error in munmap(0x7f017b800000, 4194304): Out of memory
2019-10-02 12:18:55.848 [1] main fiber.c:911 !> mprotect: Out of memory
2019-10-02 12:18:55.850 [1] main fiber.c:911 !> mprotect: Out of memory
2019-10-02 12:18:55.851 [1] main fiber.c:911 !> mprotect: Out of memory
2019-10-02 12:18:55.852 [1] main fiber.c:911 !> mprotect: Out of memory
2019-10-02 12:18:55.853 [1] main fiber.c:911 !> mprotect: Out of memory
2019-10-02 12:18:55.854 [1] main fiber.c:911 !> mprotect: Out of memory
2019-10-02 12:18:55.854 [1] main fiber.c:911 !> mprotect: Out of memory```

**Comment by cyrillos** [comment]
```
remote vclock {1: 148668295, 2: 513974653, 3: 148867454, 4: 331742779, 5: 285245761, 6: 318733319, 7: 490341983, 8: 40313943, 9: 623959902, 12: 147016437, 13: 405200773, 14: 223749671, 15: 265983318, 16: 146616619, 17: 77081471, 18: 97332886, 19: 191921278, 20: 192385911, 21: 313370, 24: 2, 28: 3} local vclock {1: 148668295, 2: 513974653, 3: 148867454, 4: 331742779, 5: 285245761, 6: 318733319, 7: 490341983, 8: 40313943, 9: 623959902, 12: 147016437, 13: 402712981, 14: 221258645, 15: 265983318, 16: 146616619, 17: 74586767, 18: 93871588, 19: 188371225, 20: 188827835, 21: 48269418, 24: 2, 28: 3}
Segmentation fault
  code: SEGV_MAPERR
  addr: 0
  context: 0x7fcca197f500
  siginfo: 0x7fcca197f630
  rax      0x7fcca197fbc8     140516861148104
  rbx      0x1                1
  rcx      0x0                0
  rdx      0x0                0
  rsi      0x1e98             7832
  rdi      0x7fd042426f28     140532441575208
  rsp      0x7fcca197fab0     140516861147824
  rbp      0x7fcca197fb90     140516861148048
  r8       0xef0              3824
  r9       0x0                0
  r10      0x7fd042426010     140532441571344
  r11      0x7fd0468b58da     140532513462490
  r12      0x55aa847b8b00     94190855490304
  r13      0x0                0
  r14      0x7fd042400c18     140532441418776
  r15      0x7fd042400be0     140532441418720
  rip      0x55aa82c7e4cc     94190826939596
  eflags   0x10206            66054
  cs       0x33               51
  gs       0x0                0
  fs       0x0                0
  cr2      0x0                0
  err      0x4                4
  oldmask  0x0                0
  trapno   0xe                14
Current time: 1569509720
Please file a bug at http://github.com/tarantool/tarantool/issues
Attempting backtrace... Note: since the server has already crashed, 
this may fail as well
#0  0x55aa82bfefc9 in print_backtrace+9
#1  0x55aa82afa80a in _ZL12sig_fatal_cbiP9siginfo_tPv+ca
#2  0x7fd046873e17 in sigwaitinfo+8
#3  0x55aa82b35b98 in vy_stmt_new_with_ops+88
#4  0x55aa82b7fcbc in vy_apply_upsert+14c
#5  0x55aa82b80875 in vy_history_apply+75
#6  0x55aa82b63c8c in vy_point_lookup+27c
#7  0x55aa82b2d605 in vy_squash_queue_f+d5
#8  0x55aa82afa1cc in _ZL16fiber_cxx_invokePFiP13__va_list_tagES0_+c
#9  0x55aa82bfbb70 in fiber_loop+30
#10 0x55aa82d47ebf in coro_init+3f```
