### ISSUE TITLE
replication/join_vclock.test.lua error: AF_UNIX path too long

### ISSUE THREAD

**Issue by Gerold103** [tarantool/tarantool#4607]
Tarantool version: Master
OS version: Mac
Bug description:
```
replication/join_vclock.test.lua                memtx           
TarantoolInpector.handle() received the following error:
Traceback (most recent call last):
  File "/Users/gerold/Work/Repositories/tarantool/test-run/lib/inspector.py", line 92, in handle
    result = self.parser.parse_preprocessor(line)
  File "/Users/gerold/Work/Repositories/tarantool/test-run/lib/preprocessor.py", line 106, in parse_preprocessor
    return self.server(stype, sname, options)
  File "/Users/gerold/Work/Repositories/tarantool/test-run/lib/preprocessor.py", line 338, in server
    return getattr(self, attr)(ctype, sname, opts)
  File "/Users/gerold/Work/Repositories/tarantool/test-run/lib/preprocessor.py", line 196, in server_start
    wait_load=wait_load, args=args)
  File "/Users/gerold/Work/Repositories/tarantool/test-run/lib/tarantool_server.py", line 822, in start
    self.wait_until_started(wait_load)
  File "/Users/gerold/Work/Repositories/tarantool/test-run/lib/tarantool_server.py", line 1017, in wait_until_started
    ans = yaml.safe_load(temp.execute('box.info.status'))[0]
  File "/Users/gerold/Work/Repositories/tarantool/test-run/lib/tarantool_connection.py", line 161, in execute
    self.opt_reconnect()
  File "/Users/gerold/Work/Repositories/tarantool/test-run/lib/tarantool_connection.py", line 155, in opt_reconnect
    self.reconnect()
  File "/Users/gerold/Work/Repositories/tarantool/test-run/lib/tarantool_connection.py", line 138, in reconnect
    self.connect()
  File "/Users/gerold/Work/Repositories/tarantool/test-run/lib/admin_connection.py", line 91, in connect
    super(AdminConnection, self).connect()
  File "/Users/gerold/Work/Repositories/tarantool/test-run/lib/tarantool_connection.py", line 124, in connect
    self.socket.connect(self.port)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: AF_UNIX path too long

[ fail ]

```

**Comment by ksosnin** [comment]
@Totktonada could you give your feedback on this issue? Any test that needs to open a socket will fail if the path exceeds the limit (to be precise it won't even run, instead showing an error message). As you mentioned in #4634 we can bypass the limitation by using relative path. Should we do something similar here?

**Comment by Totktonada** [comment]
@ligurio It is not Mac OS specific: UNIX_PATH_MAX is 108 on Linux and 104 on Mac OS, but both have such restriction.

@slumber We can bypass the limitation in test-run, but it would not have much sense if we'll not allow tarantool console to listen of a unix socket with long real (absolute) path. So it worth either do both or nothing.

I would do it with some low priority.

**Comment by Totktonada** [comment]
@Gerold103 It does not look as the flaky test: either it fails (due to the long working directory path) or not.
