### ISSUE TITLE
out of bound access

### ISSUE THREAD

**Issue by parihaaraka** [tarantool/tarantool#4636]
https://github.com/tarantool/tarantool/blob/9fba29abb4e05babb9b23b4413bd8083f0fba933/src/lib/core/backtrace.cc#L176

snprintf man:
> Returns the number of characters that would have been written if n had been sufficiently large, not counting the terminating null character.

`(p > end ? *end : *p) = '\0';` ? Or reallocate and adapt the code to capture all the output in.

**Comment by parihaaraka** [comment]
this is about:
```
#0  0x52da49 in print_backtrace+9
#1  0x50ff59 in tarantool_panic_handler+29
#2  0x554b83 in lj_err_throw+73
#3  0x554dbb in lj_err_mem+3b
#4  0x5547d4 in lj_mem_realloc+44
#5  0x5571da in lj_tab_resize+26a
#6  0x557422 in rehashtab+202
#7  0x5574e1 in lj_tab_newkey+71
#8  0x13f5ad30 in +71
2019-10-31 15:40:48.376 [1] main/127/ C> not enough memory
2019-10-31 15:40:48.376 [1] main/127/ C> #2 strsplit (upvalue), /opt/tarantool/luaunit.lua:240
2019-10-31 15:40:48.376 [1] main/127/ C> #3 stripLuaunitTrace (upvalue), /opt/tarantool/luaunit.lua:398
2019-10-31 15:40:48.376 [1] main/127/ C> #4 protectedCall (method), /opt/tarantool/luaunit.lua:2781
2019-10-31 15:40:48.376 [1] main/127/ C> #5 execOneFunction (method), /opt/tarantool/luaunit.lua:2828
2019-10-31 15:40:48.376 [1] main/127/ C> #6 runSuiteByInstances (method), /opt/tarantool/luaunit.lua:2943
2019-10-31 15:40:48.376 [1] main/127/ C> #7 runSuiteByNames (method), /opt/tarantool/luaunit.lua:3007
```
It looks like the problem is fixed with the suggested small workaround.
