### ISSUE TITLE
Segfault with a lot amount of data

### ISSUE THREAD

**Issue by bhavenger** [tarantool/tarantool#4678]
Tarantool version: 1.7.6, 1.10.3, 2.1.2

OS version: docker, alpine 3.5

Server: r4.8xlarge, 32 vCPUs, 244 GiB

Bug description:
During the active writes we get a segfault. Everything used to be ok earlier.

Steps to reproduce:
1. Start tarantool with data.
2. Start active (1k to 8k RPS) writing.
3. In a 5-40 minutes get segfault.

What we tried:
* Upgrade tarantool version - from 1.7.6 to 1.10.3 and 2.1.2.
* ![image](https://user-images.githubusercontent.com/5215734/70615470-8210f480-1c1d-11ea-9807-a36e1baa24a1.png)

Also we tried to write to empty tarantool - and everything works ok.

Optional (but very desirable):
* coredump - by request, 250gb.
```
Core was generated by `tarantool-entrypoint.lua <running>               '.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f288cf88f21 in abort () from /home/ubuntu/lib/ld-musl-x86_64.so.1
[Current thread is 1 (LWP 1)]
(gdb) where
#0  0x00007f288cf88f21 in abort () from /home/ubuntu/lib/ld-musl-x86_64.so.1
#1  0x00007f288d1f40c0 in ?? () from /home/ubuntu/lib/ld-musl-x86_64.so.1
#2  0x000055e71d20c7b6 in sig_fatal_cb (signo=<optimized out>, siginfo=<optimized out>, context=<optimized out>) at /usr/src/tarantool/src/main.cc:298
#3  <signal handler called>
#4  light_index_insert (value=<optimized out>, hash=<optimized out>, ht=0x55e71f3e5020) at /usr/src/tarantool/src/lib/salad/light.h:793
#5  memtx_hash_index_replace (base=0x55e71f3e5000, old_tuple=0x0, new_tuple=<optimized out>, mode=DUP_REPLACE_OR_INSERT, result=0x7f28882ffa18)
    at /usr/src/tarantool/src/box/memtx_hash.c:302
#6  0x000055e71d237007 in index_replace (result=0x7f28882ffa18, mode=DUP_REPLACE_OR_INSERT, new_tuple=0x7f0a8f23344c, old_tuple=<optimized out>, index=<optimized out>)
    at /usr/src/tarantool/src/box/index.h:603
#7  memtx_space_replace_all_keys (space=0x55e71f3e4ce0, old_tuple=<optimized out>, new_tuple=0x7f0a8f23344c, mode=DUP_REPLACE_OR_INSERT, result=0x7f2888c75140)
    at /usr/src/tarantool/src/box/memtx_space.c:265
#8  0x000055e71d23525f in memtx_space_execute_upsert (space=0x55e71f3e4ce0, txn=<optimized out>, request=<optimized out>) at /usr/src/tarantool/src/box/memtx_space.c:534
#9  0x000055e71d299f9f in space_execute_dml (space=space@entry=0x55e71f3e4ce0, txn=txn@entry=0x7f2888c75038, request=request@entry=0x7f28882ffba0, result=result@entry=0x7f28882ffb68)
    at /usr/src/tarantool/src/box/space.c:525
#10 0x000055e71d2bf377 in box_process_rw (request=request@entry=0x7f28882ffba0, space=0x55e71f3e4ce0, result=result@entry=0x7f28882ffc68) at /usr/src/tarantool/src/box/box.cc:180
#11 0x000055e71d2c16d7 in box_process1 (request=request@entry=0x7f28882ffba0, result=result@entry=0x7f28882ffc68) at /usr/src/tarantool/src/box/box.cc:1012
#12 0x000055e71d2c210e in box_upsert (space_id=space_id@entry=2, index_id=index_id@entry=0, 
    tuple=tuple@entry=0x7f2888c75108 "\222\316ÅZ\261\226\300\300\300\300\300\221\316-վ\204\221\223\241=\002\226\300\300\300\300\300\221\316-վ\204\016\316'\310", <incomplete sequence \343>, tuple_end=<optimized out>, ops=<optimized out>, ops_end=<optimized out>, index_base=1, result=0x7f28882ffc68) at /usr/src/tarantool/src/box/box.cc:1171
#13 0x000055e71d2e4a24 in lbox_upsert (L=0x41653010) at /usr/src/tarantool/src/box/lua/index.c:114
#14 0x000055e71d324157 in lj_BC_FUNCC ()
#15 0x000055e71d2e05ec in execute_lua_call (L=0x41653010) at /usr/src/tarantool/src/box/lua/call.c:307
#16 0x000055e71d324157 in lj_BC_FUNCC ()
#17 0x000055e71d335874 in lua_pcall ()
#18 0x000055e71d2f8183 in luaT_call (L=0x41653010, nargs=<optimized out>, nreturns=<optimized out>) at /usr/src/tarantool/src/lua/utils.c:975
#19 0x000055e71d2e0a6a in box_process_lua (handler=0x55e71d2e0520 <execute_lua_call>, base=0x7f28882ffea0, request=0x7f28888101c0, request@entry=0x41653010)
    at /usr/src/tarantool/src/box/lua/call.c:446
#20 box_lua_call (request=request@entry=0x7f28888101c0, port=port@entry=0x7f28882ffea0) at /usr/src/tarantool/src/box/lua/call.c:456
#21 0x000055e71d2debd3 in box_process_call (request=request@entry=0x7f28888101c0, port=port@entry=0x7f28882ffea0) at /usr/src/tarantool/src/box/call.c:204
#22 0x000055e71d20e09b in tx_process_call (m=0x7f2888810140) at /usr/src/tarantool/src/box/iproto.cc:1520
#23 0x000055e71d30eaf4 in cmsg_deliver (msg=msg@entry=0x7f2888810140) at /usr/src/tarantool/src/lib/core/cbus.c:353
#24 0x000055e71d30f69f in fiber_pool_f (ap=<optimized out>) at /usr/src/tarantool/src/lib/core/fiber_pool.c:64
#25 0x000055e71d20c13c in fiber_cxx_invoke(fiber_func, typedef __va_list_tag __va_list_tag *) (f=<optimized out>, ap=<optimized out>) at /usr/src/tarantool/src/lib/core/fiber.h:666
#26 0x000055e71d309f50 in fiber_loop (data=<optimized out>) at /usr/src/tarantool/src/lib/core/fiber.c:694
#27 0x000055e71d4563ef in coro_init () at /usr/src/tarantool/third_party/coro/coro.c:110
```
* backtrace:
```
Segmentation fault
  code: SEGV_MAPERR
  addr: 0x3ff8
  context: 0x7f3887d7f400
  siginfo: 0x7f3887d7f530
  rax      0x3ff0             16368
  rbx      0xf41efbe0         4095671264
  rcx      0x7ff              2047
  rdx      0x0                0
  rsi      0x10               16
  rdi      0x7f3891160000     139880929034240
  rsp      0x7f3887d7f990     139880773974416
  rbp      0x7f3887d7fa70     139880773974640
  r8       0xa                10
  r9       0x1fffff           2097151
  r10      0x3ff              1023
  r11      0x15               21
  r12      0x741efbe0         1948187616
  r13      0x56422fe50040     94842271367232
  r14      0x7f5598b1cae4     140005610736356
  r15      0xffffffff         4294967295
  rip      0x56422ebe8225     94842252067365
  eflags   0x10206            66054
  cs       0x33               51
  gs       0x0                0
  fs       0x0                0
  cr2      0x3ff8             16376
  err      0x4                4
  oldmask  0x0                0
  trapno   0xe                14
Current time: 1576053460
Please file a bug at http://github.com/tarantool/tarantool/issues
Attempting backtrace... Note: since the server has already crashed,
this may fail as well

traps: tarantool[14137] general protection ip:7f7394ee5f21 sp:7f3887d7f320 error:0 in ld-musl-x86_64.so.1[7f7394ec8000+88000]

#0  0x56422ecda329 in print_backtrace+9
#1  0x56422ebd977a in _ZL12sig_fatal_cbiP9siginfo_tPv+ca
#2  0x7f7394f0de17 in sigwaitinfo+8
#3  0x56422ec04007 in memtx_space_replace_all_keys+67
#4  0x56422ec01d0b in memtx_space_execute_replace+8b
#5  0x56422ec66fd2 in space_execute_dml+c2
#6  0x56422ec8c377 in box_process_rw+67
#7  0x56422ec8eccd in box_replace+3d
#8  0x56422ecb2541 in lbox_replace+81
#9  0x56422ecf1157 in lj_BC_FUNCC+34
#10 0x56422ecad5ec in execute_lua_call+cc
#11 0x56422ecf1157 in lj_BC_FUNCC+34
#12 0x56422ed02874 in lua_pcall+34
#13 0x56422ecc5183 in luaT_call+13
#14 0x56422ecada6a in box_lua_call+8a
#15 0x56422ecabbd3 in box_process_call+133
#16 0x56422ebdb09b in _ZL15tx_process_callP4cmsg+eb
#17 0x56422ecdbaf4 in cmsg_deliver+14
#18 0x56422ecdc69f in fiber_pool_f+ff
#19 0x56422ebd913c in _ZL16fiber_cxx_invokePFiP13__va_list_tagES0_+c
#20 0x56422ecd6f50 in fiber_loop+30
#21 0x56422ee233ef in coro_init+3f
```

**Comment by sergepetrenko** [comment]
This looks quite similar to #3594 if you have around 2 billion tuples stored in memtx

**Comment by bhavenger** [comment]
Yeah, we have around 2B tuples in one space.
We've already fixed it by dividing the data into several spaces, so we can close this issue.
