### ISSUE TITLE
SIGABRT at test replication/anon after commit "replication: use wal memory buffer to fetch rows"

### ISSUE THREAD

**Issue by avtikhon** [tarantool/tarantool#4716]
Tarantool version:
master

OS version:
Debian 9 (Stretch)

Bug description:
After commit "replication: use wal memory buffer to fetch rows"
23cc8edfaad3eb5497efec305558591bedc12526

Failed test
test replication/anon.test.lua

```
Segmentation fault
3664   code: SEGV_MAPERR
3665   addr: 0x170
3666   context: 0x7f61166ff940
3667   siginfo: 0x7f61166ffa70
3668   rax      0x5580727006d0     94010164119248
3669   rbx      0x55807270aed0     94010164162256
3670   rcx      0x0                0
3671   rdx      0x20               32
3672   rsi      0x55807270aef0     94010164162288
3673   rdi      0x0                0
3674   rsp      0x7f61166ffef8     140054964993784
3675   rbp      0x7f61166fff10     140054964993808
3676   r8       0x55807270aef0     94010164162288
3677   r9       0x10               16
3678   r10      0x1                1
3679   r11      0x0                0
3680   r12      0x55807270aed0     94010164162256
3681   r13      0xffffffffffffcc60 -13216
3682   r14      0x7f61174012d0     140054978630352
3683   r15      0x5580722ebcb8     94010159840440
3684   rip      0x558071d32eb0     94010153840304
3685   eflags   0x10206            66054
3686   cs       0x33               51
3687   gs       0x0                0
3688   fs       0x0                0
3689   cr2      0x170              368
3690   err      0x4                4
3691   oldmask  0x0                0
3692   trapno   0xe                14
3693 Current time: 1577728774
3694 Please file a bug at http://github.com/tarantool/tarantool/issues
3695 Attempting backtrace... Note: since the server has already crashed, 
3696 this may fail as well
3697 #0  0x558071d87bb9 in print_backtrace+9
3698 #1  0x558071c6c199 in _ZL12sig_fatal_cbiP9siginfo_tPv+c9
3699 #2  0x7f61198e30e0 in __restore_rt+0
3700 #3  0x558071d32eb0 in gc_consumer_advance+0
3701 #4  0x558071d41b71 in _ZL16tx_status_updateP4cmsg+81
3702 #5  0x558071d895a4 in cmsg_deliver+14
3703 #6  0x558071d8a1b2 in fiber_pool_f+102
3704 #7  0x558071c6baec in _ZL16fiber_cxx_invokePFiP13__va_list_tagES0_+c
3705 #8  0x558071d84370 in fiber_loop+30
3706 #9  0x558071f3e18f in coro_init+3f
3707 #10 (nil) in +3f
```
Steps to reproduce:

Optional (but very desirable):
* coredump
* backtrace
* netstat

**Comment by kyukhin** [comment]
Commit was rolled back.
