### ISSUE TITLE
replication/anon test segfaults

### ISSUE THREAD

**Issue by sergepetrenko** [tarantool/tarantool#4731]
replication/anon test segfaults occasionally. (Can be seen on gitlab: https://gitlab.com/tarantool/tarantool/-/jobs/406984797)

OS version: CentOS 8

Example:
```
3877 [052] replication/anon.test.lua                                       
3878 [052] 
3879 [052] [Instance "master" killed by signal: 11 (SIGSEGV)]
3880 [052] 
3881 [052] Last 15 lines of Tarantool Log file [Instance "master"][/builds/zEqw3h-j/0/tarantool/tarantool/test/var/052_replication/master.log]:
3882 [052] 2020-01-17 14:45:48.668 [27861] main/105/checkpoint_daemon I> scheduled next checkpoint for Fri Jan 17 15:52:29 2020
3883 [052] 2020-01-17 14:45:48.668 [27861] main/102/master I> set 'memtx_memory' configuration option to 107374182
3884 [052] 2020-01-17 14:45:48.668 [27861] main/102/master I> set 'listen' configuration option to "\/builds\/zEqw3h-j\/0\/tarantool\/tarantool\/test\/var\/052_replication\/master.socket-iproto"
3885 [052] 2020-01-17 14:45:48.668 [27861] main/116/console/unix/:/builds/zEqw3h-j/0 I> started
3886 [052] 2020-01-17 14:45:48.668 [27861] main C> entering the event loop
3887 [052] 2020-01-17 14:45:48.868 [27861] main/109/main I> sending current read-view to replica at fd 19, aka unix/:(socket), peer of unix/:(socket)
3888 [052] 2020-01-17 14:45:48.907 [27861] main/109/main I> read-view sent.
3889 [052] 2020-01-17 14:45:48.961 [27861] main/109/main I> subscribed replica 7b296440-2aba-463b-a0fc-6806a878f8c2 at fd 19, aka unix/:(socket), peer of unix/:(socket)
3890 [052] 2020-01-17 14:45:48.961 [27861] main/109/main I> remote vclock {1: 11} local vclock {1: 11}
3891 [052] 2020-01-17 14:45:48.980 [27861] relay/unix/:(socket)/101/main I> recover from `/builds/zEqw3h-j/0/tarantool/tarantool/test/var/052_replication/master/00000000000000000000.xlog'
3892 [052] 2020-01-17 14:45:49.325 [27861] main/119/main I> registering replica 7b296440-2aba-463b-a0fc-6806a878f8c2 at fd 18, aka unix/:(socket), peer of unix/:(socket)
3893 [052] 2020-01-17 14:45:49.325 [27861] main I> assigned id 2 to replica 7b296440-2aba-463b-a0fc-6806a878f8c2
3894 [052] 2020-01-17 14:45:49.327 [27861] relay/unix/:(socket)/101/main sio.c:268 !> SystemError writev(2), called on fd 19, aka unix/:(socket), peer of unix/:(socket): Broken pipe
3895 [052] 2020-01-17 14:45:49.327 [27861] relay/unix/:(socket)/101/main C> exiting the relay loop
3896 [052] 2020-01-17 14:45:49.327 [27861] relay/unix/:(socket)/101/main I> recover from `/builds/zEqw3h-j/0/tarantool/tarantool/test/var/052_replication/master/00000000000000000000.xlog'
3897 [052] [ fail ]
```

**Comment by ligurio** [comment]
Stable reproduction on CentOS Linux release 8.0.1905 (Core), a82ec30466b87e1e54f75806223c2b2657bb20f9

Minimal testcase:
```
env = require('test_run')
test_run = env.new()

box.schema.user.grant('guest', 'replication')
box.space.test:insert{1}

test_run:cmd('create server replica_anon with rpl_master=default, script="replication/anon1.lua"')
test_run:cmd('start server replica_anon')
test_run:cmd('switch replica_anon')

box.cfg{replication_anon=false}
box.cfg{replication_anon=true}
```

```
Program terminated with signal SIGSEGV, Segmentation fault.
#0  rlist_del (item=0x7f50540ffee0) at /home/s.bronnikov/tarantool/src/lib/small/small/rlist.h:93
93              item->prev->next = item->next;
[Current thread is 1 (Thread 0x7f5040fff700 (LWP 28726))]
Missing separate debuginfos, use: yum debuginfo-install glibc-2.28-72.el8_1.1.x86_64 libblkid-2.32.1-8.el8.x86_64 libcap-2.25-9.el8.x86_64 libgcc-8.3.1-4.5.el8.x86_64 libgomp-8.3.1-4.5.el8.x86_64 libicu-60.3-1.el8.x86_64 libmount-2.32.1-8.el8.x86_64 libselinux-2.9-2.1.el8.x86_64 libstdc++-8.3.1-4.5.el8.x86_64 libunwind-1.3.1-3.el8.x86_64 libuuid-2.32.1-8.el8.x86_64 ncurses-libs-6.1-7.20180224.el8.x86_64 openssl-libs-1.1.1c-2.el8.x86_64 pcre2-10.32-1.el8.x86_64 readline-7.0-10.el8.x86_64 systemd-libs-239-13.el8_0.5.x86_64 zlib-1.2.11-10.el8.x86_64
(gdb) bt
#0  rlist_del (item=0x7f50540ffee0) at /home/s.bronnikov/tarantool/src/lib/small/small/rlist.h:93
#1  0x0000000000500108 in trigger_clear (trigger=0x7f50540ffee0)
    at /home/s.bronnikov/tarantool/src/lib/core/trigger.h:101
#2  0x000000000050193b in relay_subscribe_f(typedef __va_list_tag __va_list_tag *) (ap=0x7f5054000158)
    at /home/s.bronnikov/tarantool/src/box/relay.cc:667
#3  0x0000000000411627 in fiber_cxx_invoke(fiber_func, typedef __va_list_tag __va_list_tag *) (
    f=0x501449 <relay_subscribe_f(typedef __va_list_tag __va_list_tag *)>, ap=0x7f5054000158)
    at /home/s.bronnikov/tarantool/src/lib/core/fiber.h:782
#4  0x00000000005593b6 in fiber_loop (data=0x0) at /home/s.bronnikov/tarantool/src/lib/core/fiber.c:869
#5  0x00000000007a1aeb in coro_init () at /home/s.bronnikov/tarantool/third_party/coro/coro.c:110
(gdb) 
```
