### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by rybakit** [tarantool/tarantool#4745]
Tarantool version: 2.3.1-2-g92750c828
OS version: Fedora 30

Steps to reproduce:

```lua
box.execute([[ PRAGMA table_info("_vinyl_deferred_delete") ]])
```

Error:
```
Segmentation fault                                                                                                                                                                
  code: SEGV_MAPERR                                                                                                                                                               
  addr: 0x10                                                                                                                                                                      
  context: 0x7fd1af87f080                                                                                                                                                         
  siginfo: 0x7fd1af87f1b0                                                                                                                                                         
  rax      0x0                0                                                                                                                                                   
  rbx      0x0                0                                                          
  rcx      0x4                4                                                          
  rdx      0x0                0                                                          
  rsi      0x0                0                                                          
  rdi      0x55effabaa420     94489192080416                                             
  rsp      0x7fd1af87f618     140538569815576                                            
  rbp      0x7fd1af87f6c0     140538569815744                                            
  r8       0xfefefefefefefe01 -72340172838076927                                         
  r9       0x3                3                                                          
  r10      0x16               22                                                         
  r11      0x55effab07dc0     94489191415232 
  r12      0x55effabaa420     94489192080416 
  r13      0x55effabaa93f     94489192081727 
  r14      0x55effab23be8     94489191529448 
  r15      0x55effa99d160     94489189929312 
  rip      0x55effa60669c     94489186166428 
  eflags   0x10293            66195
  cs       0x33               51
  gs       0x0                0
  fs       0x0                0
  cr2      0x10               16
  err      0x4                4
  oldmask  0x0                0
  trapno   0xe                14
```
```
#0  0x55effa44c059 in print_backtrace+9
#1  0x55effa32ce1a in _ZL12sig_fatal_cbiP9siginfo_tPv+ca
#2  0x7fd1cc72ae17 in sigwaitinfo+8
#3  0x55effa65650c in sqlParser+125c
#4  0x55effa633a06 in sqlRunParser+a6
#5  0x55effa6227b8 in sql_stmt_compile+108
#6  0x55effa40c94c in sql_prepare_and_execute+2c
#7  0x55effa425d9c in lbox_execute+15c
#8  0x55effa46ea57 in lj_BC_FUNCC+34
#9  0x55effa4144ce in execute_lua_eval+7e
#10 0x55effa46ea57 in lj_BC_FUNCC+34
#11 0x55effa480234 in lua_pcall+34
#12 0x55effa4349e3 in luaT_call+13
#13 0x55effa415635 in box_lua_eval+d5
#14 0x55effa412354 in box_process_eval+94
#15 0x55effa32fd9d in _ZL15tx_process_callP4cmsg+13d
#16 0x55effa44d824 in cmsg_deliver+14
#17 0x55effa44e3d2 in fiber_pool_f+102
#18 0x55effa32c7ac in _ZL16fiber_cxx_invokePFiP13__va_list_tagES0_+c
#19 0x55effa448940 in fiber_loop+30
#20 0x55effa6022cf in coro_init+3f
```

**Comment by Totktonada** [comment]
Reproduced on 2.4.0-16-gcdf502c66:

```
$ tarantool --version | head -n 2
Tarantool 2.4.0-16-gcdf502c66
Target: Linux-x86_64-Debug

$ tarantool -e 'box.execute([[ PRAGMA table_info("_vinyl_deferred_delete") ]])'
<...>
tarantool: /var/tmp/portage/dev-db/tarantool-9999/work/tarantool-9999/src/box/sql/build.c:144: sql_space_column_is_in_pk: Assertion `primary_idx != NULL' failed.
Aborted (core dumped)

$ gdb tarantool core -ex 'bt' -ex 'quit'
<...>
#0  0x00007f75fddee1f1 in raise () from /lib64/libc.so.6
#1  0x00007f75fddd655b in abort () from /lib64/libc.so.6
#2  0x00007f75fddd642f in __assert_fail_base.cold () from /lib64/libc.so.6
#3  0x00007f75fdde59e2 in __assert_fail () from /lib64/libc.so.6
#4  0x00005619405f338a in sql_space_column_is_in_pk (space=0x561942236130, column=0) at /usr/src/debug/dev-db/tarantool-9999/tarantool-9999/src/box/sql/build.c:144
#5  0x000056194067c2d7 in sql_pragma_table_info (parse=0x7f75fb97fa00, tbl_name=0x5619421b2f38 "_vinyl_deferred_delete")
    at /usr/src/debug/dev-db/tarantool-9999/tarantool-9999/src/box/sql/pragma.c:115
#6  0x000056194067cf9e in sqlPragma (pParse=0x7f75fb97fa00, pragma=0x5619421b4358, table=0x5619421b4398, index=0x0)
    at /usr/src/debug/dev-db/tarantool-9999/tarantool-9999/src/box/sql/pragma.c:378
#7  0x0000561940678d1a in yy_reduce (yypParser=0x5619421b42d8, yyruleno=221) at /usr/src/debug/dev-db/tarantool-9999/tarantool-9999/src/box/sql/parse.y:1550
#8  0x000056194067a1ea in sqlParser (yyp=0x5619421b42d8, yymajor=1, yyminor=..., pParse=0x7f75fb97fa00) at parse.c:4373
#9  0x0000561940637395 in sqlRunParser (pParse=0x7f75fb97fa00, zSql=0x5619421b3538 " PRAGMA table_info(\"_vinyl_deferred_delete\") ")
    at /usr/src/debug/dev-db/tarantool-9999/tarantool-9999/src/box/sql/tokenize.c:526
#10 0x000056194061d466 in sql_stmt_compile (zSql=0x4186ba48 " PRAGMA table_info(\"_vinyl_deferred_delete\") ", nBytes=45, pReprepare=0x0, ppStmt=0x7f75fb97fd70, pzTail=0x0)
    at /usr/src/debug/dev-db/tarantool-9999/tarantool-9999/src/box/sql/prepare.c:83
#11 0x0000561940466bfa in sql_prepare_and_execute (sql=0x4186ba48 " PRAGMA table_info(\"_vinyl_deferred_delete\") ", len=45, bind=0x0, bind_count=0, port=0x7f75fb97fda0, 
    region=0x7f75fb800330) at /usr/src/debug/dev-db/tarantool-9999/tarantool-9999/src/box/execute.c:732
#12 0x0000561940485eb6 in lbox_execute (L=0x40ea9378) at /usr/src/debug/dev-db/tarantool-9999/tarantool-9999/src/box/lua/execute.c:454
#13 0x00005619404e7f6b in lj_BC_FUNCC () at buildvm_x86.dasc:809
#14 0x00005619404fd9fe in lua_pcall (L=<optimized out>, nargs=<optimized out>, nresults=0, errfunc=<optimized out>) at lj_api.c:1139
#15 0x000056194049a821 in luaT_call (L=0x40ea9378, nargs=0, nreturns=0) at /usr/src/debug/dev-db/tarantool-9999/tarantool-9999/src/lua/utils.c:1036
#16 0x0000561940491a08 in run_script_f (ap=0x7f75fb8003e8) at /usr/src/debug/dev-db/tarantool-9999/tarantool-9999/src/lua/init.c:597
#17 0x0000561940369de9 in fiber_cxx_invoke(fiber_func, typedef __va_list_tag __va_list_tag *) (f=0x5619404915fd <run_script_f>, ap=0x7f75fb8003e8)
    at /usr/src/debug/dev-db/tarantool-9999/tarantool-9999/src/lib/core/fiber.h:761
#18 0x00005619404b453c in fiber_loop (data=0x0) at /usr/src/debug/dev-db/tarantool-9999/tarantool-9999/src/lib/core/fiber.c:830
#19 0x00005619405ebf38 in coro_init () at /usr/src/debug/dev-db/tarantool-9999/tarantool-9999/third_party/coro/coro.c:110
```
