### ISSUE TITLE
Assertion fail in vy_cache_on_write()

### ISSUE THREAD

**Issue by Totktonada** [tarantool/tarantool#4784]
Tarantool version: 1.10.4-31-g07814084d.
OS version: Linux.

The relevant code snippet:

https://github.com/tarantool/tarantool/blob/07814084dae51800d9654336e23234b8d6265e52/src/box/vy_cache.c#L465-L470

Backtrace:

```
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `tarantool tagger_027_03.lua <running> '.
Program terminated with signal 6, Aborted.
#0 0x00007feddef46337 in raise () from /lib64/libc.so.6
#0 0x00007feddef46337 in raise () from /lib64/libc.so.6
#1 0x00007feddef47a28 in abort () from /lib64/libc.so.6
#2 0x00007feddef3f156 in __assert_fail_base () from /lib64/libc.so.6
#3 0x00007feddef3f202 in __assert_fail () from /lib64/libc.so.6
#4 0x0000000000488371 in vy_cache_on_write (cache=0x7fea33592e28, stmt=0x7fe897f8d7a0, deleted=0x0) at /build/usr/src/debug/tarantool-1.10.4.31/src/box/vy_cache.c:468
#5 0x0000000000474cbd in vy_tx_write (lsm=0x7fea33592b90, mem=0x7fe898121b00, stmt=0x7fe897f8d7a0, region_stmt=0x7fe64faff8c8) at /build/usr/src/debug/tarantool-1.10.4.31/src/box/vy_tx.c:526
#6 0x00000000004755e8 in vy_tx_prepare (tx=0x7fedd4d080b8) at /build/usr/src/debug/tarantool-1.10.4.31/src/box/vy_tx.c:777
#7 0x0000000000446ba5 in vinyl_engine_prepare (engine=0x24dacf0, txn=0x7fe5f01c8038) at /build/usr/src/debug/tarantool-1.10.4.31/src/box/vinyl.c:2374
#8 0x00000000004bcf02 in engine_prepare (engine=0x24dacf0, txn=0x7fe5f01c8038) at /build/usr/src/debug/tarantool-1.10.4.31/src/box/engine.h:267
#9 0x00000000004be20f in txn_commit (txn=0x7fe5f01c8038) at /build/usr/src/debug/tarantool-1.10.4.31/src/box/txn.c:331
#10 0x00000000004be81f in box_txn_commit () at /build/usr/src/debug/tarantool-1.10.4.31/src/box/txn.c:472
#11 0x00000000004e3cf0 in lbox_commit (L=0x40680528) at /build/usr/src/debug/tarantool-1.10.4.31/src/box/lua/init.c:90
#12 0x000000000053f42b in lj_BC_FUNCC () at buildvm_x86.dasc:809
#13 0x00000000004e575e in execute_lua_call (L=0x40680528) at /build/usr/src/debug/tarantool-1.10.4.31/src/box/lua/call.c:302
#14 0x000000000053f42b in lj_BC_FUNCC () at buildvm_x86.dasc:809
#15 0x0000000000554433 in lua_pcall (L=0x40680528, nargs=<optimized out>, nresults=<optimized out>, errfunc=<optimized out>) at lj_api.c:1139
#16 0x0000000000503bb2 in luaT_call (L=0x40680528, nargs=1, nreturns=-1) at /build/usr/src/debug/tarantool-1.10.4.31/src/lua/utils.c:974
#17 0x00000000004e5cab in box_process_lua (request=0x7fedd5416138, base=0x7fe64faffe30, handler=0x4e5630 <execute_lua_call>) at /build/usr/src/debug/tarantool-1.10.4.31/src/box/lua/call.c:442
#18 0x00000000004e5cf1 in box_lua_call (request=0x7fedd5416138, port=0x7fe64faffe30) at /build/usr/src/debug/tarantool-1.10.4.31/src/box/lua/call.c:452
#19 0x00000000004e38b1 in box_process_call (request=0x7fedd5416138, port=0x7fe64faffe30) at /build/usr/src/debug/tarantool-1.10.4.31/src/box/call.c:199
#20 0x0000000000416b2d in tx_process_call (m=0x7fedd54160c8) at /build/usr/src/debug/tarantool-1.10.4.31/src/box/iproto.cc:1528
#21 0x000000000051eb67 in cmsg_deliver (msg=0x7fedd54160c8) at /build/usr/src/debug/tarantool-1.10.4.31/src/cbus.c:353
#22 0x000000000051fb41 in fiber_pool_f (ap=0x7fe6cdad4a58) at /build/usr/src/debug/tarantool-1.10.4.31/src/fiber_pool.c:64
#23 0x000000000041098a in fiber_cxx_invoke(fiber_func, typedef __va_list_tag __va_list_tag *) (f=0x51f9ae <fiber_pool_f>, ap=0x7fe6cdad4a58) at /build/usr/src/debug/tarantool-1.10.4.31/src/fiber.h:666
#24 0x0000000000518ec3 in fiber_loop (data=0x0) at /build/usr/src/debug/tarantool-1.10.4.31/src/fiber.c:694
#25 0x0000000000697d83 in coro_init () at /build/usr/src/debug/tarantool-1.10.4.31/third_party/coro/coro.c:110
```

Hits FRS from time to time.

No extracted reproducer.

Jira: TNT-3.

**Comment by kyukhin** [comment]
No reproducer, closing.
