### ISSUE TITLE
Assertion `ls->p < ls->pe' failed: lj_bcread.c:122: uint32_t bcread_byte(LexState *)

### ISSUE THREAD

**Issue by ligurio** [tarantool/tarantool#4824]
Tarantool version:
```
[s.bronnikov@tarantool-core-dev-mcs1 build]$ ./src/tarantool -V
Tarantool 2.4.0-136-g2336be53a
Target: Linux-x86_64-Debug
Build options: cmake . -DCMAKE_INSTALL_PREFIX=/usr/local -DENABLE_BACKTRACE=ON
Compiler: /home/s.bronnikov/AFL/afl-clang /home/s.bronnikov/AFL/afl-clang++
C_FLAGS: -fexceptions -funwind-tables -fno-omit-frame-pointer -fno-stack-protector -fno-common -fopenmp -msse2 -std=c11 -Wall -Wextra -Wno-strict-aliasing -Wno-char-subscripts -Werror
CXX_FLAGS: -fexceptions -funwind-tables -fno-omit-frame-pointer -fno-stack-protector -fno-common -fopenmp -msse2 -std=c++11 -Wall -Wextra -Wno-strict-aliasing -Wno-char-subscripts -Werror
```

OS version:
CentOS Linux release 8.0.1905 (Core)

Bug description:

catched with AFL

Steps to reproduce:

- download snippet (contains non-printable symbols) https://bronevichok.ru/trash/id:000000,sig:06,src:000053,op:havoc,rep:64
```
$ `tarantool ./<snippet>`
$ ./src/tarantool out/crashes/id\:000000\,sig\:06\,src\:000053\,op\:havoc\,rep\:64 
tarantool: lj_bcread.c:122: uint32_t bcread_byte(LexState *): Assertion `ls->p < ls->pe' failed.
Aborted (core dumped)
$
```

Optional (but very desirable):

```
(gdb) bt
#0  0x00007f679a50f8df in raise () from /lib64/libc.so.6
#1  0x00007f679a4f9cf5 in abort () from /lib64/libc.so.6
#2  0x00007f679a4f9bc9 in __assert_fail_base.cold.0 () from /lib64/libc.so.6
#3  0x00007f679a507e96 in __assert_fail () from /lib64/libc.so.6
#4  0x00000000009b9649 in bcread_header (ls=0x7f679a1ffe68) at lj_bcread.c:122
#5  lj_bcread (ls=0x7f679a1ffe68) at lj_bcread.c:428
#6  0x00000000009be219 in cpparser (L=0x41005378, dummy=<optimized out>, ud=0x7f679a1ffe68)
    at lj_load.c:41
#7  0x000000000090e1aa in lj_vm_cpcall ()
#8  0x00000000009be814 in lua_loadx (L=<optimized out>, reader=<optimized out>, data=<optimized out>, 
    chunkname=0x402f0db8 "@out/crashes/id:000000,sig:06,src:000053,op:havoc,rep:64", 
    mode=<optimized out>) at lj_load.c:58
#9  luaL_loadfilex (L=0x41005378, 
    filename=0x1774f78 "out/crashes/id:000000,sig:06,src:000053,op:havoc,rep:64", mode=0x0)
    at lj_load.c:101
#10 0x00000000007f98bf in run_script_f (ap=<optimized out>)
    at /home/s.bronnikov/tarantool/src/lua/init.c:615
#11 0x0000000000417484 in fiber_cxx_invoke (f=0x0, ap=0x2)
    at /home/s.bronnikov/tarantool/src/lib/core/fiber.h:782
#12 0x00000000008593f9 in fiber_loop (data=<optimized out>)
    at /home/s.bronnikov/tarantool/src/lib/core/fiber.c:869
#13 0x00000000011351f4 in coro_init () at /home/s.bronnikov/tarantool/third_party/coro/coro.c:110
#14 0x0000000000000000 in ?? ()
(gdb) 
```

**Comment by ligurio** [comment]
`luajit` from LuaJIT 2.0.5 (current stable release) and master (e613105ca92fe25e7bd63031b409faa8c908ac35):
won't load file with reproducer:

```
$ cat print.lua 
local sum = 0
$ hexdump -x print.lua                                
0000000    6f6c    6163    206c    7573    206d    203d    0a30        
000000e
$ cat id\:000000\,sig\:06\,src\:000053\,op\:havoc\,rep\:64 >> print.lua
$ cat print.lua 
local sum = 0

$ hexdump -x print.lua                                 
0000000    6f6c    6163    206c    7573    206d    203d    0a30    0a1b
0000010
$ ./src/luajit print.lua                               
./src/luajit: print.lua:2: unexpected symbol near 'char(27)'
$ 
```

**Comment by ligurio** [comment]
Cannot reproduce on LuaJIT 2.1.0 beta3:
```
$ git describe 
v2.1.0-beta3
$ ./src/luajit print.lua                                     
./src/luajit: print.lua:2: unexpected symbol near 'char(27)'
$ 
```

**Comment by igormunkin** [comment]
@ligurio I don't face the issue even using our fork:
```bash
$ git lo -1
cf84758 (HEAD -> tarantool, origin/tarantool, origin/HEAD) test: rename test files
$ xxd ~/test.lua 
00000000: 6c6f 6361 6c20 7375 6d20 3d20 300a 1b    local sum = 0..
$ ./src/luajit ~/test.lua 
./src/luajit: /home/imun/test.lua:2: unexpected symbol near 'char(27)'
```
I also can't reproduce the problem on the current master:
```bash
$ git lo -1
fc55875e2 (HEAD -> master, origin/master, origin/HEAD) static build: create new build w/o dockerfile
$ git describe
2.4.0-146-gfc55875e2
$ ./src/tarantool -V
Tarantool 2.4.0-146-gfc55875e2
Target: Linux-x86_64-Debug
Build options: cmake . -DCMAKE_INSTALL_PREFIX=/usr/local -DENABLE_BACKTRACE=ON
Compiler: /usr/bin/cc /usr/bin/c++
C_FLAGS: -fexceptions -funwind-tables -fno-omit-frame-pointer -fno-stack-protector -fno-common -fopenmp -msse2 -std=c11 -Wall -Wextra -Wno-strict-aliasing -Wno-char-subscripts -Wno-format-truncation -fno-gnu89-inline -Wno-cast-function-type -Werror
CXX_FLAGS: -fexceptions -funwind-tables -fno-omit-frame-pointer -fno-stack-protector -fno-common -fopenmp -msse2 -std=c++11 -Wall -Wextra -Wno-strict-aliasing -Wno-char-subscripts -Wno-format-truncation -Wno-invalid-offsetof -Wno-cast-function-type -Werror
$ ./src/tarantool ~/test.lua 
LuajitError: /home/imun/test.lua:2: unexpected symbol near 'char(27)'
fatal error, exiting the event loop
```
---
But there are different results for the [original snippet](https://bronevichok.ru/trash/id:000000,sig:06,src:000053,op:havoc,rep:64), using the same builds for luajit and tarantool.
```bash
$ xxd ~/1b-test.lua 
00000000: 1b                                       .
$ ./src/luajit ~/1b-test.lua 
./src/luajit: /home/imun/1b-test.lua: cannot load incompatible bytecode
```
So the problem looks to be related to tarantool itself.
```bash
$ ./src/tarantool ~/1b-test.lua 
tarantool: lj_bcread.c:122: bcread_byte: Assertion `ls->p < ls->pe' failed.
Aborted
```

**Comment by igormunkin** [comment]
openresty/luajit2#96 looks quite similar to this one. I tried both Tarantool and our LuaJIT fork and reproduced the issue with `poc1.txt` from the mentioned ticket:
```bash
$ xxd poc1.txt 
00000000: 1b4c 4a02 011d 3030 3030 3030 3030 3030  .LJ...0000000000
00000010: 3030 3030 3030 3030 3030 3030 3030 3030  0000000000000000
00000020: 3030 3001 3030 3030 3030 95b0 30         000.000000..0
```
```bash
$ git lo -1
377198b (HEAD -> tarantool, origin/tarantool, origin/HEAD) jit: abort trace execution on JIT mode change
$ ./src/luajit poc1.txt 
Segmentation fault
```

```bash
$ git lo -1
55a29d1a2 (HEAD -> master, origin/master, origin/HEAD) uuid: fix unaligned memory access
$ ./src/tarantool poc1.txt 
tarantool: lj_bcread.c:130: bcread_uleb128: Assertion `ls->p <= ls->pe' failed.
Aborted
```

Returning luajit label.
