### ISSUE TITLE
merger: segmentation fault when called via net.box

### ISSUE THREAD

**Issue by olegrok** [tarantool/tarantool#4954]
```
Tarantool Enterprise For Mac 2.3.1-15-gd567fec81
Target: Darwin-x86_64-RelWithDebInfo
Build options: cmake . -DCMAKE_INSTALL_PREFIX=/usr/local -DENABLE_BACKTRACE=ON
Compiler: /Library/Developer/CommandLineTools/usr/bin/cc /Library/Developer/CommandLineTools/usr/bin/c++
C_FLAGS: -Wno-unknown-pragmas -fexceptions -funwind-tables -fno-omit-frame-pointer -fno-stack-protector -fno-common -msse2 -std=c11 -Wall -Wextra -Wno-strict-aliasing -Wno-char-subscripts
CXX_FLAGS: -Wno-unknown-pragmas -fexceptions -funwind-tables -fno-omit-frame-pointer -fno-stack-protector -fno-common -msse2 -std=c++11 -Wall -Wextra -Wno-strict-aliasing -Wno-char-subscripts
```

```
WARNING  localhost:11001:server.py:40 Segmentation fault
WARNING  localhost:11001:server.py:40   code: SEGV_MAPERR
WARNING  localhost:11001:server.py:40   addr: 0x28
WARNING  localhost:11001:server.py:40   context: 0x113f7fa98
WARNING  localhost:11001:server.py:40   siginfo: 0x113f7fa30
WARNING  localhost:11001:server.py:40 Current time: 1588241514
WARNING  localhost:11001:server.py:40 Please file a bug at http://github.com/tarantool/tarantool/issues
WARNING  localhost:11001:server.py:40 Attempting backtrace... Note: since the server has already crashed,
WARNING  localhost:11001:server.py:40 this may fail as well
WARNING  localhost:11001:server.py:40 #0  0x10e9c9689 in print_backtrace+9
WARNING  localhost:11001:server.py:40 #1  0x10e6d2778 in _ZL12sig_fatal_cbiP9__siginfoPv+158
WARNING  localhost:11001:server.py:40 #2  0x7fff771d9b5d in _sigtramp+1d
WARNING  localhost:11001:server.py:40 #3  0x10ea00585 in lua_gettop+5
WARNING  localhost:11001:server.py:40 #4  0x10e9b38d9 in luaL_iterator_next+19
WARNING  localhost:11001:server.py:40 #5  0x10e79f0b9 in luaL_merge_source_tuple_next+39
WARNING  localhost:11001:server.py:40 #6  0x10e78a465 in merger_next+e5
WARNING  localhost:11001:server.py:40 #7  0x10e79f2cf in lbox_merge_source_gen+7f
WARNING  localhost:11001:server.py:40 #8  0x10e9ee005 in lj_BC_FUNCC+44
WARNING  localhost:11001:server.py:40 #9  0x10e78b42b in execute_lua_eval+12b
WARNING  localhost:11001:server.py:40 #10 0x10e9ee005 in lj_BC_FUNCC+44
WARNING  localhost:11001:server.py:40 #11 0x10ea054f5 in lua_pcall+a5
WARNING  localhost:11001:server.py:40 #12 0x10e9b3473 in luaT_call+13
WARNING  localhost:11001:server.py:40 #13 0x10e78b2cc in box_lua_eval+dc
WARNING  localhost:11001:server.py:40 #14 0x10e789ea6 in box_process_eval+c6
WARNING  localhost:11001:server.py:40 #15 0x10e6d63ce in _ZL15tx_process_callP4cmsg+11e
WARNING  localhost:11001:server.py:40 #16 0x10e9cab24 in cmsg_deliver+14
WARNING  localhost:11001:server.py:40 #17 0x10e9cbdfc in fiber_pool_f+19c
WARNING  localhost:11001:server.py:40 #18 0x10e6d229c in _ZL16fiber_cxx_invokePFiP13__va_list_tagES0_+c
WARNING  localhost:11001:server.py:40 #19 0x10e9c6c03 in fiber_loop+43
WARNING  localhost:11001:server.py:40 #20 0x10ebe618b in coro_init+4b
```

**Comment by olegrok** [comment]
I used in code it in the following way, but I don't now why it shoots in my tests and don't in this example. Sorry.

```lua
merger_lib = require('merger')
key_def_lib = require('key_def')

box.cfg{}

space = box.schema.create_space('test')
space:format({{is_nullable = false, name = "bucket_id", type = "unsigned"}, {is_nullable = true, name = "deleted", type = "boolean"}, {is_nullable = false, name = "id", type = "integer"}, {is_nullable = true, name = "type", type = "string"}, {is_nullable = false, name = "version", type = "unsigned"}})
space:create_index('id', {type = 'TREE', unique = true, parts = {{field = 3, type = 'integer', is_nullable = false}, {field = 5, type = 'unsigned', is_nullable = false}}})

space:create_index('bucket_id', {type = 'TREE', unique = false, parts = {{field = 1, type = 'unsigned', is_nullable = false}}})

sources = {
    merger_lib.new_tuple_source(space:pairs()),
}
parts = space.index[0].parts
key_def = key_def_lib.new(parts)
merger = merger_lib.new(key_def, sources)
for _, tuple in merger:pairs() do end
```

**Comment by olegrok** [comment]
```
Program received signal SIGSEGV, Segmentation fault.
0x00000000006b4051 in lua_gettop ()
(gdb) bt
#0  0x00000000006b4051 in lua_gettop ()
#1  0x000000000066877c in luaL_iterator_next (L=L@entry=0x0, it=0xc14a5a0)
    at /tarantool/src/lua/utils.c:1203
#2  0x000000000065bfc6 in luaL_merge_source_tuple_fetch (source=<optimized out>, L=0x0)
    at /tarantool/src/box/lua/merger.c:769
#3  luaL_merge_source_tuple_next (base=<optimized out>, format=0xc14a740, out=0x7f68e677fb98)
    at /tarantool/src/box/lua/merger.c:816
#4  0x0000000000646e91 in merge_source_next (out=0x7f68e677fb98, format=<optimized out>, 
    source=<optimized out>) at /tarantool/src/box/merger.h:118
#5  merger_add_heap_node (node=0xc14ab70, merger=0xc14a5e0) at /tarantool/src/box/merger.c:174
#6  merger_next (base=0xc14a5e0, format=0x0, out=0x7f68e677fbf8)
    at /tarantool/src/box/merger.c:318
#7  0x000000000065b6c5 in merge_source_next (out=0x7f68e677fbf8, format=0x0, source=0xc14a5e0)
    at /tarantool/src/box/merger.h:118
#8  lbox_merge_source_gen (L=0x455f2e88) at /tarantool/src/box/lua/merger.c:873
#9  0x00000000006a5127 in lj_BC_FUNCC ()
#10 0x0000000000649207 in execute_lua_eval (L=0x455f2e88) at /tarantool/src/box/lua/call.c:375
#11 0x00000000006a5127 in lj_BC_FUNCC ()
#12 0x00000000006b6112 in lua_pcall ()
#13 0x0000000000668373 in luaT_call (L=0x455f2e88, nargs=<optimized out>, 
    nreturns=<optimized out>) at /tarantool/src/lua/utils.c:1036
#14 0x000000000064a083 in box_process_lua (ret=0x7f68e677feb0, ctx=0x7f68e677fd80, 
    handler=0x649120 <execute_lua_eval>) at /tarantool/src/box/lua/call.c:539
#15 box_lua_eval (expr=<optimized out>, expr_len=<optimized out>, 
    args=args@entry=0x7f68e677fdf0, ret=ret@entry=0x7f68e677feb0)
    at /tarantool/src/box/lua/call.c:565
#16 0x0000000000646bc2 in box_process_eval (request=0x7f68e5410b80, port=0x7f68e677feb0)
    at /tarantool/src/box/call.c:147
#17 0x000000000055b8dd in tx_process_call (m=0x7f68e5410b00)
```

**Comment by olegrok** [comment]
Reproducer:
```
box.cfg{listen = 'localhost:3301'}
function call()
    merger_lib = require('merger')
    key_def_lib = require('key_def')

    box.cfg{}

    if box.space.test ~= nil then
        box.space.test:drop()
    end

    space = box.schema.create_space('test')
    space:format({{is_nullable = false, name = "bucket_id", type = "unsigned"}, {is_nullable = true, name = "deleted", type = "boolean"}, {is_nullable = false, name = "id", type = "integer"}, {is_nullable = true, name = "type", type = "string"}, {is_nullable = false, name = "version", type = "unsigned"}})
    space:create_index('id', {type = 'TREE', unique = true, parts = {{field = 3, type = 'integer', is_nullable = false}, {field = 5, type = 'unsigned', is_nullable = false}}})

    space:create_index('bucket_id', {type = 'TREE', unique = false, parts = {{field = 1, type = 'unsigned', is_nullable = false}}})

    sources = {
        merger_lib.new_tuple_source(space:pairs()),
    }
    parts = space.index[0].parts
    key_def = key_def_lib.new(parts)
    merger = merger_lib.new(key_def, sources)
    for _, tuple in merger:pairs() do end
end

netbox = require('net.box')
box.schema.user.passwd('admin', 'test')
c = netbox.new('admin:test@localhost:3301')
c:call('call')
```

Output is following:
```
Segmentation fault
  code: SEGV_MAPERR
  addr: 0x28
  context: 0x11247fa68
  siginfo: 0x11247fa00
Current time: 1588267270
Please file a bug at http://github.com/tarantool/tarantool/issues
Attempting backtrace... Note: since the server has already crashed, 
this may fail as well
#0  0x106ad0689 in print_backtrace+9
#1  0x1067d9778 in _ZL12sig_fatal_cbiP9__siginfoPv+158
#2  0x7fff771d9b5d in _sigtramp+1d
#3  0x106b07585 in lua_gettop+5
#4  0x106aba8d9 in luaL_iterator_next+19
#5  0x1068a60b9 in luaL_merge_source_tuple_next+39
#6  0x106891465 in merger_next+e5
#7  0x1068a62cf in lbox_merge_source_gen+7f
#8  0x106af5005 in lj_BC_FUNCC+44
#9  0x1068921ca in execute_lua_call+7a
#10 0x106af5005 in lj_BC_FUNCC+44
#11 0x106b0c4f5 in lua_pcall+a5
#12 0x106aba473 in luaT_call+13
#13 0x10689211c in box_lua_call+dc
#14 0x106850d3c in func_call+13c
#15 0x106890c38 in box_process_call+c8
#16 0x1067dd3dc in _ZL15tx_process_callP4cmsg+12c
#17 0x106ad1b24 in cmsg_deliver+14
#18 0x106ad2dfc in fiber_pool_f+19c
#19 0x1067d929c in _ZL16fiber_cxx_invokePFiP13__va_list_tagES0_+c
#20 0x106acdc03 in fiber_loop+43
#21 0x106ced18b in coro_init+4b
[1]    63390 abort      tarantool
```
