### ISSUE TITLE
test: flaky replication/box_set_replication_stress.test.lua OSX on 1.10

### ISSUE THREAD

**Issue by avtikhon** [tarantool/tarantool#4986]
Tarantool version:
 Tarantool 1.10.6-18-g9dc2f263d
 Target: Darwin-x86_64-RelWithDebInfo
 Build options: cmake . -DCMAKE_INSTALL_PREFIX=/usr/local -DENABLE_BACKTRACE=ON
 Compiler: /Library/Developer/CommandLineTools/usr/bin/cc /Library/Developer/CommandLineTools/usr/bin/c++
 C_FLAGS: -Wno-unknown-pragmas -fexceptions -funwind-tables -fno-omit-frame-pointer -fno-stack-protector -fno-common -msse2 -std=c11 -Wall -Wextra -Wno-strict-aliasing -Wno-char-subscripts -Werror
 CXX_FLAGS: -Wno-unknown-pragmas -fexceptions -funwind-tables -fno-omit-frame-pointer -fno-stack-protector -fno-common -msse2 -std=c++11 -Wall -Wextra -Wno-strict-aliasing -Wno-char-subscripts -Werror

OS version:
OSX 14/15

Bug description:
https://gitlab.com/tarantool/tarantool/-/jobs/554597234
```
 [028] replication/box_set_replication_stress.test.lua vinyl           
 [028] 
 [028] [Instance "master_quorum1" killed by signal: 6 (SIGABRT)]
 [028] 
 [028] Last 15 lines of Tarantool Log file [Instance "master_quorum1"][/tmp/tnt/028_replication/master_quorum1.log]:
 [028] 2020-05-15 17:48:24.335 [4058] main/270/console/unix/: C> leaving orphan mode
 [028] 2020-05-15 17:48:24.335 [4058] main/270/console/unix/: I> set 'replication' configuration option to ["\/private\/tmp\/tnt\/028_replication\/master_quorum1.sock","\/private\/tmp\/tnt\/028_replication\/master_quorum2.sock"]
 [028] 2020-05-15 17:48:24.335 [4058] main/270/console/unix/: C> leaving orphan mode
 [028] 2020-05-15 17:48:24.335 [4058] main/270/console/unix/: I> set 'replication' configuration option to []
 [028] 2020-05-15 17:48:24.335 [4058] main/270/console/unix/: I> connecting to 2 replicas
 [028] 2020-05-15 17:48:24.335 [4058] main/270/console/unix/: C> failed to connect to 2 out of 2 replicas
 [028] 2020-05-15 17:48:24.335 [4058] main/270/console/unix/: C> leaving orphan mode
 [028] 2020-05-15 17:48:24.335 [4058] main/270/console/unix/: I> set 'replication' configuration option to ["\/private\/tmp\/tnt\/028_replication\/master_quorum1.sock","\/private\/tmp\/tnt\/028_replication\/master_quorum2.sock"]
 [028] 2020-05-15 17:48:24.335 [4058] main/270/console/unix/: C> leaving orphan mode
 [028] 2020-05-15 17:48:24.335 [4058] main/270/console/unix/: I> set 'replication' configuration option to []
 [028] 2020-05-15 17:48:24.335 [4058] main/270/console/unix/: I> connecting to 2 replicas
 [028] 2020-05-15 17:48:24.335 [4058] main/270/console/unix/: C> failed to connect to 2 out of 2 replicas
 [028] 2020-05-15 17:48:24.335 [4058] main/270/console/unix/: C> leaving orphan mode
 [028] 2020-05-15 17:48:24.335 [4058] main/270/console/unix/: I> set 'replication' configuration option to ["\/private\/tmp\/tnt\/028_replication\/master_quorum1.sock","\/private\/tmp\/tnt\/028_replication\/master_quorum2.sock"]
 [028] (libev) select: Invalid argument
```

Steps to reproduce:

Optional (but very desirable):
* coredump
* backtrace
* netstat

**Comment by avtikhon** [comment]
Reproduced on 
https://gitlab.com/tarantool/tarantool/-/jobs/575349827
```
 Tarantool 2.5.0-89-g9757c06b3
 Target: Darwin-x86_64-RelWithDebInfo
 Build options: cmake . -DCMAKE_INSTALL_PREFIX=/usr/local -DENABLE_BACKTRACE=ON
 Compiler: /Library/Developer/CommandLineTools/usr/bin/cc /Library/Developer/CommandLineTools/usr/bin/c++
 C_FLAGS: -Wno-unknown-pragmas -fexceptions -funwind-tables -fno-omit-frame-pointer -fno-stack-protector -fno-common -msse2 -std=c11 -Wall -Wextra -Wno-strict-aliasing -Wno-char-subscripts -Werror
 CXX_FLAGS: -Wno-unknown-pragmas -fexceptions -funwind-tables -fno-omit-frame-pointer -fno-stack-protector -fno-common -msse2 -std=c++11 -Wall -Wextra -Wno-strict-aliasing -Wno-char-subscripts -Werror
```

Issue output:
```
 Segmentation fault
   code: 0
 2020-06-01 13:10:31.257 [54164] iproto sio.c:268 !> SystemError writev(1), called on fd 1007, aka unix/:/private/tmp/tnt/036_replication/master_quor: Broken pipe
   addr: 0x0
 2020-06-01 13:10:31.257 [54164] iproto sio.c:268 !> SystemError writev(1), called on fd 1006, aka unix/:/private/tmp/tnt/036_replication/master_quor: Broken pipe
   context: 0x10c47fca0
   siginfo: 0x10c47fc38
 Current time: 2020-06-01 13:10:31.257 [54164] iproto sio.c:268 !> SystemError writev(1), called on fd 1005, aka unix/:/private/tmp/tnt/036_replication/master_quor: Broken pipe
 15910062312020-06-01 13:10:31.257 [54164] iproto sio.c:268 !> SystemError writev(1), called on fd 1004, aka unix/:/private/tmp/tnt/036_replication/master_quor: Broken pipe
 2020-06-01 13:10:31.258 [54164] iproto sio.c:268 !> SystemError writev(1), called on fd 1003, aka unix/:/private/tmp/tnt/036_replication/master_quor: Broken pipe
...
#0  0x108125ed9 in print_backtrace+9
 #1  0x10835a5a1 in _ZL12sig_fatal_cbiP9__siginfoPv+141
 #2  0x7fff6e2845fd in _sigtramp+1d
 2020-06-01 13:10:31.262 [54164] iproto sio.c:268 !> SystemError writev(1), called on fd 963, aka unix/:/private/tmp/tnt/036_replication/master_quoru: Broken pipe
```

**Comment by Totktonada** [comment]
The original problem was fixed in #3867. The new problem is not the same as the originally reported.

Alexander, please, reproduce it locally and try to catch a backtrace from a core file using lldb. At least we'll see where it crashes.

**Comment by avtikhon** [comment]
> The original problem was fixed in #3867. The new problem is not the same as the originally reported.
> 
> Alexander, please, reproduce it locally and try to catch a backtrace from a core file using lldb. At least we'll see where it crashes.

Right, corrected the message not to mess these 2 different issues.
