### ISSUE TITLE
test: flaky SEGFAULT on vinyl/gh-4810-dump-during-index-build.test.lua test

### ISSUE THREAD

**Issue by avtikhon** [tarantool/tarantool#5031]
Tarantool version:
 Tarantool 2.5.0-73-g5ca12a403
 Target: Linux-x86_64-RelWithDebInfo
 Build options: cmake . -DCMAKE_INSTALL_PREFIX=/usr -DENABLE_BACKTRACE=ON
 Compiler: /usr/bin/cc /usr/bin/c++
 C_FLAGS:-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches  -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fexceptions -funwind-tables -fno-omit-frame-pointer -fno-stack-protector -fno-common -fopenmp -msse2 -std=c11 -Wall -Wextra -Wno-strict-aliasing -Wno-char-subscripts -Wno-format-truncation -fno-gnu89-inline -Wno-cast-function-type
 CXX_FLAGS:-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches  -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fexceptions -funwind-tables -fno-omit-frame-pointer -fno-stack-protector -fno-common -fopenmp -msse2 -std=c++11 -Wall -Wextra -Wno-strict-aliasing -Wno-char-subscripts -Wno-format-truncation -Wno-invalid-offsetof -Wno-cast-function-type

OS version:
Fedora 28

Bug description:
```
 Segmentation fault
   code: SEGV_MAPERR
   addr: 0x178
   context: 0x7f4a81f7f180
   siginfo: 0x7f4a81f7f2b0
   rax      0x160              352
   rbx      0xe31f70           14884720
   rcx      0xa1               161
   rdx      0x19               25
   rsi      0xa1               161
   rdi      0xebccd0           15453392
   rsp      0x7f4a81f7f740     139957984819008
   rbp      0x7f4a81f7f770     139957984819056
   r8       0x7f4a81f7f808     139957984819208
   r9       0x0                0
   r10      0x1                1
   r11      0xf333e0           15938528
   r12      0xa1               161
   r13      0xf333e0           15938528
   r14      0x2                2
   r15      0x7f4a81f7f808     139957984819208
   rip      0x4c53a7           5002151
   eflags   0x10287            66183
   cs       0x33               51
   gs       0x0                0
   fs       0x0                0
   cr2      0x178              376
   err      0x4                4
   oldmask  0x0                0
   trapno   0xe                14
 Current time: 1590192613
 Please file a bug at http://github.com/tarantool/tarantool/issues
 Attempting backtrace... Note: since the server has already crashed, 
 this may fail as well
 #0  0x577a4d in print_backtrace+d
 #1  0x44de8b in _ZL12sig_fatal_cbiP9siginfo_tPv+cb
 #2  0x7f4a85458080 in funlockfile+50
 #3  0x4c53a7 in vy_stmt_dup_lsregion+47
 #4  0x4e4b4a in vy_lsm_set+4a
 #5  0x4ea3f0 in vy_tx_prepare+340
 #6  0x4ba8d1 in vinyl_engine_prepare+61
 #7  0x461ebc in txn_prepare+3c
 #8  0x462e82 in txn_commit+32
 #9  0x466270 in box_process_rw+310
 #10 0x469f91 in box_insert+41
 #11 0x494338 in lbox_insert+88
 #12 0x5c8e37 in lj_BC_FUNCC+34
 #13 0x5ab3b6 in lua_pcall+86
 #14 0x559ac7 in luaT_call+17
 #15 0x5531e9 in lua_fiber_run_f+59
 #16 0x44d340 in _ZL16fiber_cxx_invokePFiP13__va_list_tagES0_+10
 #17 0x574170 in fiber_loop+30
 #18 0x73ce73 in coro_init+43
```

Steps to reproduce:

Optional (but very desirable):
* coredump
* backtrace
* netstat

**Comment by locker** [comment]
On my local host applying the following patch increases the chance of hitting the bug:

```diff
diff --git a/test/vinyl/gh-4810-dump-during-index-build.test.lua b/test/vinyl/gh-4810-dump-during-index-build.test.lua
index 7ffbd5230785..d3b2a5b4c680 100644
--- a/test/vinyl/gh-4810-dump-during-index-build.test.lua
+++ b/test/vinyl/gh-4810-dump-during-index-build.test.lua
@@ -47,7 +47,10 @@ function insert_loop()
 end;

 function idx_build()
-    _ = s:create_index('i1', {unique = false, parts = {2, 'unsigned', 3, 'unsigned'}})
+    s:replace{1, 1, 1}
+    s:replace{2, 1, 1}
+    fiber.sleep(0.5)
+    _ = s:create_index('i1', {unique = true, parts = {2, 'unsigned', 3, 'unsigned'}})
     ch:put(true)
 end;
```
