### ISSUE TITLE
Memory leak in crypto (ASAN report)

### ISSUE THREAD

**Issue by Gerold103** [tarantool/tarantool#5062]
```
3813 [055] [Instance "app" returns with non-zero exit code: 1]
3814 [055] 
3815 [055] Last 15 lines of Tarantool Log file [Instance "app"][/builds/4BUsapPU/0/tarantool/tarantool/test/var/055_app/app.log]:
3816 [055] 2020-06-09 00:18:56.273 [25273] main/103/app I> set 'memtx_memory' configuration option to 107374182
3817 [055] 2020-06-09 00:18:56.273 [25273] main/103/app I> set 'listen' configuration option to "\/builds\/4BUsapPU\/0\/tarantool\/tarantool\/test\/var\/055_app\/app.socket-iproto"
3818 [055] 2020-06-09 00:18:56.273 [25273] main/103/app I> set 'log_format' configuration option to "plain"
3819 [055] 2020-06-09 00:18:56.276 [25273] main/117/console/unix/:/builds/4BUsapPU/0/tarantool/tarantool/test/var/055_app/app.socket-admin I> started
3820 [055] 2020-06-09 00:18:56.277 [25273] main C> entering the event loop
3821 [055] 2020-06-09 00:18:56.717 [25273] main C> got signal 15 - Terminated
3822 [055] 
3823 [055] =================================================================
3824 [055] ==25273==ERROR: LeakSanitizer: detected memory leaks
3825 [055] 
3826 [055] Indirect leak of 104 byte(s) in 1 object(s) allocated from:
3827 [055]     #0 0x513b93 in __interceptor_malloc (/builds/4BUsapPU/0/tarantool/tarantool/src/tarantool+0x513b93)
3828 [055]     #1 0x7fcb52361400 in EVP_MD_CTX_copy_ex (/usr/lib/x86_64-linux-gnu/libcrypto.so.1.1+0x174400)
3829 [055] 
3830 [055] SUMMARY: AddressSanitizer: 104 byte(s) leaked in 1 allocation(s).
```
Last test, running in [055] worker was `[055] app/crypto_hmac.test.lua                                        [ pass ]`.
Failed job: https://gitlab.com/tarantool/tarantool/-/jobs/586681415

**Comment by nshy** [comment]
Fixed by PR https://github.com/tarantool/tarantool/pull/10516.
