### ISSUE TITLE
json updates: Segmentation fault on invalid upsert

### ISSUE THREAD

**Issue by olegrok** [tarantool/tarantool#5135]
```lua
box.cfg{}
box.schema.create_space('test')
box.space.test:create_index('pk')
box.space.test:upsert({1, {1}}, {{'!', '[2][-1]', 2}})
box.space.test:upsert({1, {1}}, {{'!', '[2][-1]', 2}})
2020-07-04 16:27:04.776 [64047] main/102/interactive xrow_update.c:332 E> UPSERT operation failed:
2020-07-04 16:27:04.776 [64047] main/102/interactive xrow_update_field.c:99 E> ER_UPDATE_FIELD: Field '[2][-1]' UPDATE error: invalid JSON in position 5
Segmentation fault
  code: SEGV_MAPERR
  addr: 0x108823000
  context: 0x103d7f858
  siginfo: 0x103d7f7f0
Current time: 1593869224
Please file a bug at http://github.com/tarantool/tarantool/issues
Attempting backtrace... Note: since the server has already crashed, 
this may fail as well
#0  0x101390689 in print_backtrace+9
#1  0x101099778 in _ZL12sig_fatal_cbiP9__siginfoPv+158
#2  0x7fff6b01fb5d in _sigtramp+1d
[1]    64047 abort      tarantool
```

**Comment by olegrok** [comment]
For type mismatch similar symptoms:
```
tarantool> box.space.test:upsert({2, 2}, {{'=', '[2][2]', 1}})
tarantool> box.space.test:upsert({2, 2}, {{'=', '[2][2]', 1}})
2020-07-04 17:11:12.741 [66362] main/102/interactive xrow_update.c:332 E> UPSERT operation failed:
2020-07-04 17:11:12.741 [66362] main/102/interactive xrow_update_field.c:99 E> ER_UPDATE_FIELD: Field '[2][2]' UPDATE error: can not access by index a non-array field
[1]    66362 bus error  tarantool
```

**Comment by olegrok** [comment]
@Gerold103 
Seems you forgot to cherry-pick it to 2.3 and 2.4 branches. Milestone is 2.3.3 but I see only one commit.

**Comment by Gerold103** [comment]
Indeed. Pushed to 2.4 and 2.3 now.
