### ISSUE TITLE
gitlab-ci: restore testing lto on osx

### ISSUE THREAD

**Issue by avtikhon** [tarantool/tarantool#5160]
Tarantool version:

OS version:

Bug description:
After changes of OSX testing to new hosts the environment of the build was not completed updated.
After the following commit new issues in LTO for OSX appeared:
```
commit a94a9b3fd629b5abbc99a23ba527cd91e5c6ebf5 (HEAD)
Author: Cyrill Gorcunov <gorcunov@gmail.com>
Date:   Fri Jun 5 14:25:45 2020 +0300

    lua/log: add ability to configure logging early
    
    In the pcommit a94a9b3fd629b5abbc99a23ba527cd91e5c6ebf5 (HEAD)
Author: Cyrill Gorcunov <gorcunov@gmail.com>
Date:   Fri Jun 5 14:25:45 2020 +0300

    lua/log: add ability to configure logging early
    
    In the patch we introduce an ability to configure logging
    engine early without calling box.cfg{} at all. For this sake
    we have to modify the load_cfg.lua (main cfg loader) together
    with log.lua built in module.
    
    In particular the configuration entries which are supposed to
    be handled by modules are grouped in module_cfg table, where we
    list box.cfg{} keys and methods to fetch/set the values. Same time
    the template_cfg{} starts to carry 'module' keyword telling
    prepare_cfg routine to use modules.
    
    @TarantoolBot documnent
    Title: Module log
    
    To configure log module eary without initializing box module
    at all call the `log.cfg({})` method, where the following
    arguments are acceptable:
    
     - `log` to specify file, pipe or syslog (same as
       `box.cfg{log}` option); the default value is nil
       and stderr is used;
    
     - `level` to specify logging level; can be numbers (1-7) or
       strings (fatal,syserror,error,crit,warn,info,verbose,debug);
       the default value is 5 (i.e. 'info');
    
       While for symbolic representations of levels we allow only
       predefined keywords to be used, to keep backward compatibility
       the numbers can be any;
    
     - `format` to specify output encoding ('plain' or 'json');
       the default value is 'plain';
    
     - `nonblock` to open logging output in nonblocking mode
       (`true` or `false`); the default value is `false`.
    
    Fixes #689
    
    Signed-off-by: Cyrill Gorcunov <gorcunov@gmail.com>
atch we introduce an ability to configure logging
    engine early without calling box.cfg{} at all. For this sake
    we have to modify the load_cfg.lua (main cfg loader) together
    with log.lua built in module.
    
    In particular the configuration entries which are supposed to
    be handled by modules are grouped in module_cfg table, where we
    list box.cfg{} keys and methods to fetch/set the values. Same time
    the template_cfg{} starts to carry 'module' keyword telling
    prepare_cfg routine to use modules.
    
    @TarantoolBot documnent
    Title: Module log
    
    To configure log module eary without initializing box module
    at all call the `log.cfg({})` method, where the following
    arguments are acceptable:
    
     - `log` to specify file, pipe or syslog (same as
       `box.cfg{log}` option); the default value is nil
       and stderr is used;
    
     - `level` to specify logging level; can be numbers (1-7) or
       strings (fatal,syserror,error,crit,warn,info,verbose,debug);
       the default value is 5 (i.e. 'info');
    
       While for symbolic representations of levels we allow only
       predefined keywords to be used, to keep backward compatibility
       the numbers can be any;
    
     - `format` to specify output encoding ('plain' or 'json');
       the default value is 'plain';
    
     - `nonblock` to open logging output in nonblocking mode
       (`true` or `false`); the default value is `false`.
    
    Fixes #689
    
    Signed-off-by: Cyrill Gorcunov <gorcunov@gmail.com>
```
Issue:
```
[015] Starting instance master...
[015] Run console at unix/:/tmp/tnt/015_replication-py/master.control
[015] started
[015] mkdir /tmp/tnt/015_replication-py/master
[015] Configuration failed: builtin/box/load_cfg.lua:19: builtin/log.lua:187: dlsym(RTLD_DEFAULT, say_logger_initialized): symbol not found
[015] Starting instance master...
[015] Run console at unix/:/tmp/tnt/015_replication-py/master.control
[015] started
[015] mkdir /tmp/tnt/015_replication-py/master
[015] Configuration failed: builtin/box/load_cfg.lua:19: builtin/log.lua:187: dlsym(RTLD_DEFAULT, say_logger_initialized): symbol not found
[015] Worker "015_replication-py" cannot start tarantool server; the tasks will be ignored...
[015] The raised exception is '' of type '<class 'lib.tarantool_server.TarantoolStartError'>'.
[015] Worker "015_replication-py" received the following error:
[015] Traceback (most recent call last):
[015]   File "/Users/tntmac03.tarantool.i/tnt/test-run/lib/worker.py", line 250, in __init__
[015]     self.inspector = suite.start_server(self.server)
[015]   File "/Users/tntmac03.tarantool.i/tnt/test-run/lib/test_suite.py", line 207, in start_server
[015]     server.deploy(silent=False)
[015]   File "/Users/tntmac03.tarantool.i/tnt/test-run/lib/tarantool_server.py", line 750, in deploy
[015]     self.start(silent=silent, **kwargs)
[015]   File "/Users/tntmac03.tarantool.i/tnt/test-run/lib/tarantool_server.py", line 835, in start
[015]     self.wait_until_started(wait_load)
[015]   File "/Users/tntmac03.tarantool.i/tnt/test-run/lib/tarantool_server.py", line 1023, in wait_until_started
[015]     self.logfile_pos.seek_wait(msg, p, self.name)
[015]   File "/Users/tntmac03.tarantool.i/tnt/test-run/lib/tarantool_server.py", line 439, in seek_wait
[015]     raise TarantoolStartError(name)
[015] TarantoolStartError
```

Steps to reproduce:

Optional (but very desirable):
* coredump
* backtrace
* netstat

**Comment by cyrillos** [comment]
https://lists.tarantool.org/pipermail/tarantool-patches/2020-July/018898.html
