### ISSUE TITLE
asan: leak at src/lib/bitset/iterator.c:146

### ISSUE THREAD

**Issue by avtikhon** [tarantool/tarantool#5188]
Tarantool version:
2.6.0

OS version:
All

Bug description:
Currently LSAN disabled with:
asan/lsan.supp
```
# test: box/bitset.test.lua
# source: src/lib/bitset/iterator.c
leak:tt_bitset_iterator_init
```
Disabling suppression got issue:
```
[001] box/bitset.test.lua                                             [ pass ]
[001] 
[001] 
[001] [Instance "box" returns with non-zero exit code: 1]
[001] 
[001] Last 15 lines of Tarantool Log file [Instance "box"][/source/test/var/001_box/box.log]:
[001]     #3 0x96c2a3 in memtx_bitset_index_create_iterator /source/src/box/memtx_bitset.c:394:6
[001]     #4 0x55f6bc in index_create_iterator(index*, iterator_type, char const*, unsigned int) /source/src/box/index.h:637:9
[001]     #5 0x55f6bc in box_index_iterator /source/src/box/index.cc:379
[001]     #6 0x2ac0831a  (<unknown module>)
[001] 
[001] Indirect leak of 96 byte(s) in 3 object(s) allocated from:
[001]     #0 0x52101f in realloc (/source/src/tarantool+0x52101f)
[001]     #1 0xa2e9d6 in tt_bitset_iterator_conj_reserve /source/src/lib/bitset/iterator.c:146:19
[001]     #2 0xa2e9d6 in tt_bitset_iterator_init /source/src/lib/bitset/iterator.c:215
[001]     #3 0x96c2a3 in memtx_bitset_index_create_iterator /source/src/box/memtx_bitset.c:394:6
[001]     #4 0x55f6bc in index_create_iterator(index*, iterator_type, char const*, unsigned int) /source/src/box/index.h:637:9
[001]     #5 0x55f6bc in box_index_iterator /source/src/box/index.cc:379
[001]     #6 0x2ac094f6  (<unknown module>)
[001] 
[001] SUMMARY: AddressSanitizer: 31360 byte(s) leaked in 173 allocation(s).
```

Steps to reproduce:

Optional (but very desirable):
* coredump
* backtrace
* netstat

**Comment by igormunkin** [comment]
@avtikhon, I glanced the issue description and strongly doubt this one relates to LuaJIT, since I see no LuaJIT routines in backtraces reported by sanitizer. The problem might relate to some Lua code in Tarantool, but I still suggest replacing luajit label with the corresponding one.
