### ISSUE TITLE
Segmentation fault in lbox_tuple_field_by_path 

### ISSUE THREAD

**Issue by olegrok** [tarantool/tarantool#5224]
```
Segmentation fault
  code: SEGV_MAPERR
  addr: 0x21f06037e
  context: 0x13927fb28
  siginfo: 0x13927fac0
Current time: 1596526876
Please file a bug at http://github.com/tarantool/tarantool/issues
Attempting backtrace... Note: since the server has already crashed, 
this may fail as well
#0  0x10abd6839 in print_backtrace+9
#1  0x10ae192c1 in _ZL12sig_fatal_cbiP9__siginfoPv+141
#2  0x7fff6907eb5d in _sigtramp+1d
#3  0x10abba7f5 in luamp_decode+15
#4  0x10aba2130 in lbox_tuple_field_by_path+d0
#5  0x10abff645 in lj_BC_FUNCC+44
#6  0x10ab9c97a in execute_lua_call+7a
#7  0x10abff645 in lj_BC_FUNCC+44
#8  0x10ac17588 in lua_pcall+b8
#9  0x10abbd493 in luaT_call+13
#10 0x10ab9c8cc in box_lua_call+dc
#11 0x10ab9ab76 in box_process_call+266
#12 0x10aadc5e3 in _ZL15tx_process_callP4cmsg+133
#13 0x10abd7eb4 in cmsg_deliver+14
#14 0x10abd922d in fiber_pool_f+19d
#15 0x10aad848c in _ZL16fiber_cxx_invokePFiP13__va_list_tagES0_+c
#16 0x10abd3ba3 in fiber_loop+43
#17 0x10adbbecb in coro_init+4b
[1]    50062 abort (core dumped)  ./init.lua --bootstrap true
```

**Comment by olegrok** [comment]
```
Process 62477 stopped
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x21406037e)
    frame #0: 0x0000000100149104 tarantool`luamp_decode + 20
tarantool`luamp_decode:
->  0x100149104 <+20>: movzbl (%rbx), %r15d
    0x100149108 <+24>: leaq   0x2d62c1(%rip), %rax      ; mp_type_hint
    0x10014910f <+31>: movl   (%rax,%r15,4), %eax
    0x100149113 <+35>: cmpq   $0xa, %rax
Target 0: (tarantool) stopped.
(lldb) bt
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x21406037e)
  * frame #0: 0x0000000100149104 tarantool`luamp_decode + 20
    frame #1: 0x0000000100130810 tarantool`lbox_tuple_field_by_path + 208
    frame #2: 0x000000010018e485 tarantool`lj_BC_FUNCC + 68
    frame #3: 0x000000010012a0ea tarantool`execute_lua_call + 122
    frame #4: 0x000000010018e485 tarantool`lj_BC_FUNCC + 68
    frame #5: 0x00000001001a63c8 tarantool`lua_pcall + 184
    frame #6: 0x000000010014c053 tarantool`luaT_call + 19
    frame #7: 0x0000000100129341 tarantool`box_lua_call + 241
    frame #8: 0x00000001000ca4b9 tarantool`box_process_call + 617
    frame #9: 0x000000010000a543 tarantool`tx_process_call(cmsg*) + 307
    frame #10: 0x00000001001668e4 tarantool`cmsg_deliver + 20
    frame #11: 0x0000000100167c3d tarantool`fiber_pool_f + 365
    frame #12: 0x000000010000621c tarantool`fiber_cxx_invoke(int (*)(__va_list_tag*), __va_list_tag*) + 12
    frame #13: 0x00000001001625b3 tarantool`fiber_loop + 67
    frame #14: 0x000000010034e3bb tarantool`coro_init + 75

```

**Comment by olegrok** [comment]
```
tarantool> tuple:update({{'!', -1, {multiindex_position = 1}}})
---
- [25457, null, [{'tags': 'kalmar'}, {'tags': 'finban'}, {'tags': 'kibernetics'}],
  'Kiberkalmar', 1596526847572359000, {'multiindex_position': 1}]
...

tarantool> t = tuple:update({{'!', -1, {multiindex_position = 1}}})
---
...

tarantool> t
---
- [25457, null, [{'tags': 'kalmar'}, {'tags': 'finban'}, {'tags': 'kibernetics'}],
  'Kiberkalmar', 1596526847572359000, {'multiindex_position': 1}]
...

tarantool> t['meta[1].tags']
Segmentation fault
  code: SEGV_MAPERR
  addr: 0x224025946
  context: 0x11257fd48
  siginfo: 0x11257fce0
Current time: 1596528449
Please file a bug at http://github.com/tarantool/tarantool/issues
Attempting backtrace... Note: since the server has already crashed, 
this may fail as well
#0  0x10fd54fb9 in print_backtrace+9
#1  0x10ffc9811 in _ZL12sig_fatal_cbiP9__siginfoPv+141
#2  0x7fff6907eb5d in _sigtramp+1d
#3  0x10fd3c1c8 in luamp_decode+18
#4  0x10fb0cc40 in lbox_tuple_field_by_path+d0
#5  0x10fd79725 in lj_BC_FUNCC+44
#6  0x10fd91668 in lua_pcall+b8
#7  0x10fd3ec33 in luaT_call+13
#8  0x10fd39119 in run_script_f+529
#9  0x10fa4e2dc in _ZL16fiber_cxx_invokePFiP13__va_list_tagES0_+c
#10 0x10fd524b3 in fiber_loop+43
#11 0x10ff716db in coro_init+4b
[1]    62950 abort (core dumped)  ./init.lua
```

**Comment by olegrok** [comment]
```
tarantool> box.cfg()
tarantool> s = box.schema.create_space('test')
tarantool> s:create_index('test')
tarantool> s:format({{is_nullable = false, name = "bucket_id", type = "unsigned"}, {is_nullable = true, name = "deleted", type = "boolean"}, {is_nullable = true, name = "meta", type = "array"}, {is_nullable = false, name = "name", type = "string"}, {is_nullable = false, name = "version", type = "unsigned"}})
tarantool> s:create_index('metainfo', {parts = {{field = 3, is_nullable = true, path = "[*].tags", type = "string"}, {field = 4, is_nullable = false, type = "string"}}})
---
- unique: true
  parts:
  - type: string
    is_nullable: true
    path: '[*].tags'
    fieldno: 3
  - type: string
    is_nullable: false
    fieldno: 4
  id: 1
  space_id: 512
  type: TREE
  name: metainfo
...

tarantool> s:replace{29027, null, {{tags = 'octopus'}, {tags= 'petrogradka'}}, 'GM-octopus', 1596526860527830000}
---
- [29027, null, [{'tags': 'octopus'}, {'tags': 'petrogradka'}], 'GM-octopus', 1596526860527830016]
...

tarantool> t = s:select()[1]
---
...

tarantool> t
---
- [29027, null, [{'tags': 'octopus'}, {'tags': 'petrogradka'}], 'GM-octopus', 1596526860527830016]
...

tarantool> t = t:update({{'!', -1, {mydata = 1}}})
---
...

tarantool> t['meta[1].tags']
Segmentation fault
  code: SEGV_MAPERR
  addr: 0x21c06410e
  context: 0x1121ffd48
  siginfo: 0x1121ffce0
Current time: 1596528987
Please file a bug at http://github.com/tarantool/tarantool/issues
Attempting backtrace... Note: since the server has already crashed, 
this may fail as well
#0  0x10f9f2269 in print_backtrace+9
#1  0x10fbdbdc1 in _ZL12sig_fatal_cbiP9__siginfoPv+141
#2  0x7fff6907eb5d in _sigtramp+1d
#3  0x10f9d6105 in luamp_decode+15
#4  0x10f9bd810 in lbox_tuple_field_by_path+d0
#5  0x10fa1b485 in lj_BC_FUNCC+44
#6  0x10fa333c8 in lua_pcall+b8
#7  0x10f9d9053 in luaT_call+13
#8  0x10f9d2d89 in run_script_f+3a9
#9  0x10f89321c in _ZL16fiber_cxx_invokePFiP13__va_list_tagES0_+c
#10 0x10f9ef5b3 in fiber_loop+43
#11 0x10fbdb3bb in coro_init+4b
[1]    63234 abort      ./src/tarantool
```
