### ISSUE TITLE
asan: leak at box-tap/schema_mt.test.lua test

### ISSUE THREAD

**Issue by avtikhon** [tarantool/tarantool#5284]
Tarantool version:
2.6.0-57-g2a01ce912
OS version:
Linux

Bug description:
Found memory leak in test:
box-tap/schema_mt.test.lua
```
==75587==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 56 byte(s) in 1 object(s) allocated from:
    #0 0x520dfa in calloc (/tnt/src/tarantool+0x520dfa)
    #1 0xa120f8 in mh_i32ptr_new /source/src/lib/salad/mhash.h:402:39
    #2 0x9d21f3 in cord_create /source/src/lib/core/fiber.c:1375:25
    #3 0x9d368f in cord_thread_func /source/src/lib/core/fiber.c:1454:2
    #4 0x7fb14039dfa2 in start_thread (/lib/x86_64-linux-gnu/libpthread.so.0+0x7fa2)

Indirect leak of 56 byte(s) in 1 object(s) allocated from:
    #0 0x520dfa in calloc (/tnt/src/tarantool+0x520dfa)
    #1 0xa1210d in mh_i32ptr_new /source/src/lib/salad/mhash.h:403:32
    #2 0x9d21f3 in cord_create /source/src/lib/core/fiber.c:1375:25
    #3 0x9d368f in cord_thread_func /source/src/lib/core/fiber.c:1454:2
    #4 0x7fb14039dfa2 in start_thread (/lib/x86_64-linux-gnu/libpthread.so.0+0x7fa2)

Indirect leak of 48 byte(s) in 1 object(s) allocated from:
    #0 0x520dfa in calloc (/tnt/src/tarantool+0x520dfa)
    #1 0xa12184 in mh_i32ptr_new /source/src/lib/salad/mhash.h:406:23
    #2 0x9d21f3 in cord_create /source/src/lib/core/fiber.c:1375:25
    #3 0x9d368f in cord_thread_func /source/src/lib/core/fiber.c:1454:2
    #4 0x7fb14039dfa2 in start_thread (/lib/x86_64-linux-gnu/libpthread.so.0+0x7fa2)

Indirect leak of 4 byte(s) in 1 object(s) allocated from:
    #0 0x520dfa in calloc (/tnt/src/tarantool+0x520dfa)
    #1 0xa121aa in mh_i32ptr_new /source/src/lib/salad/mhash.h:408:22
    #2 0x9d21f3 in cord_create /source/src/lib/core/fiber.c:1375:25
    #3 0x9d368f in cord_thread_func /source/src/lib/core/fiber.c:1454:2
    #4 0x7fb14039dfa2 in start_thread (/lib/x86_64-linux-gnu/libpthread.so.0+0x7fa2)

SUMMARY: AddressSanitizer: 164 byte(s) leaked in 4 allocation(s).
```

Steps to reproduce:
Run:
```
cd /source
(rm -rf /tnt ; mkdir /tnt ; cd /tnt ; make -f /source/.travis.mk test_asan_debian_no_deps)

ASAN=ON LSAN_OPTIONS=suppressions=/source/asan/lsan.supp ASAN_OPTIONS=heap_profile=0:unmap_shadow_on_exit=1:detect_invalid_pointer_pairs=1:symbolize=1:detect_leaks=1:dump_instruction_bytes=1:print_suppressions=0 /source/test/test-run.py --builddir /tnt --vardir /tnt/test/var --force box-tap/schema_mt.test.lua
```

Optional (but very desirable):
* coredump
* backtrace
* netstat

**Comment by nshy** [comment]
Fixed by PR https://github.com/tarantool/tarantool/pull/10516.
