### ISSUE TITLE
test: flaky app-tap/http_client.test.lua test

### ISSUE THREAD

**Issue by avtikhon** [tarantool/tarantool#5346]
Tarantool version:
Tarantool 2.6.0-114-g6c04687566
Target: Linux-x86_64-RelWithDebInfo
Build options: cmake . -DCMAKE_INSTALL_PREFIX=/builds/M4RrgQZ3/0/tarantool/tarantool/static-build/tarantool-prefix -DENABLE_BACKTRACE=TRUE
Compiler: /usr/bin/cc /usr/bin/c++
C_FLAGS: -static-libstdc++ -fexceptions -funwind-tables -fno-omit-frame-pointer -fno-stack-protector -fno-common -fopenmp -msse2 -std=c11 -Wall -Wextra -Wno-strict-aliasing -Wno-char-subscripts -Wno-format-truncation -Wno-gnu-alignof-expression -fno-gnu89-inline -Wno-cast-function-type -Werror
CXX_FLAGS: -static-libstdc++ -fexceptions -funwind-tables -fno-omit-frame-pointer -fno-stack-protector -fno-common -fopenmp -msse2 -std=c++11 -Wall -Wextra -Wno-strict-aliasing -Wno-char-subscripts -Wno-format-truncation -Wno-invalid-offsetof -Wno-gnu-alignof-expression -Wno-cast-function-type -Werror

OS version:
CentOS 7

Bug description:
https://gitlab.com/tarantool/tarantool/-/jobs/759207861#L4888
https://gitlab.com/tarantool/tarantool/-/jobs/759236803#L2293
https://gitlab.com/tarantool/tarantool/-/jobs/759476184#L2185

Not possible to use results file for checksum creation due to a lot of changing information printing.
```
[034] app-tap/http_client.test.lua                                    [ fail ]
[034] Test failed! Output from reject file app-tap/http_client.reject:
[034] TAP version 13
[034] # TARANTOOL_SRC_DIR=/builds/M4RrgQZ3/0/tarantool/tarantool
[034] 1..2
[034]     # http over AF_INET
[034]     1..11
[034]     # starting HTTP server on 127.0.0.1:34324...
[034]     not ok - server started
[034]       ---
[034]       filename: /builds/M4RrgQZ3/0/tarantool/tarantool/test/app-tap/http_client.test.lua
[034]       line: 0
[034]       expected: heartbeat
[034]       trace:
[034]       - line: 25
[034]         source: '@/builds/M4RrgQZ3/0/tarantool/tarantool/test/app-tap/http_client.test.lua'
[034]         filename: /builds/M4RrgQZ3/0/tarantool/tarantool/test/app-tap/http_client.test.lua
[034]         what: Lua
[034]         namewhat: upvalue
[034]         name: start_server
[034]         src: '.../0/tarantool/tarantool/test/app-tap/http_client.test.lua'
[034]       - line: 585
[034]         source: '@/builds/M4RrgQZ3/0/tarantool/tarantool/test/app-tap/http_client.test.lua'
[034]         filename: /builds/M4RrgQZ3/0/tarantool/tarantool/test/app-tap/http_client.test.lua
[034]         what: Lua
[034]         namewhat: global
[034]         name: run_tests
[034]         src: '.../0/tarantool/tarantool/test/app-tap/http_client.test.lua'
[034]       - line: 616
[034]         source: '@/builds/M4RrgQZ3/0/tarantool/tarantool/test/app-tap/http_client.test.lua'
[034]         filename: /builds/M4RrgQZ3/0/tarantool/tarantool/test/app-tap/http_client.test.lua
[034]         what: Lua
[034]         namewhat: local
[034]         name: fun
[034]         src: '.../0/tarantool/tarantool/test/app-tap/http_client.test.lua'
[034]       - line: 218
[034]         source: '@builtin/tap.lua'
[034]         filename: builtin/tap.lua
[034]         what: Lua
[034]         namewhat: method
[034]         name: test
[034]         src: builtin/tap.lua
[034]       - line: 0
[034]         source: '@/builds/M4RrgQZ3/0/tarantool/tarantool/test/app-tap/http_client.test.lua'
[034]         filename: /builds/M4RrgQZ3/0/tarantool/tarantool/test/app-tap/http_client.test.lua
[034]         what: main
[034]         namewhat: 
[034]         src: '.../0/tarantool/tarantool/test/app-tap/http_client.test.lua'
[034]       ...
[034]     # trying to connect to http://127.0.0.1:34324/
[034]     not ok - connection is ok
[034]       ---
[034]       filename: /builds/M4RrgQZ3/0/tarantool/tarantool/test/app-tap/http_client.test.lua
[034]       trace:
[034]       - line: 25
[034]         source: '@/builds/M4RrgQZ3/0/tarantool/tarantool/test/app-tap/http_client.test.lua'
[034]         filename: /builds/M4RrgQZ3/0/tarantool/tarantool/test/app-tap/http_client.test.lua
[034]         what: Lua
[034]         namewhat: upvalue
[034]         name: start_server
[034]         src: '.../0/tarantool/tarantool/test/app-tap/http_client.test.lua'
[034]       - line: 585
[034]         source: '@/builds/M4RrgQZ3/0/tarantool/tarantool/test/app-tap/http_client.test.lua'
[034]         filename: /builds/M4RrgQZ3/0/tarantool/tarantool/test/app-tap/http_client.test.lua
[034]         what: Lua
[034]         namewhat: global
[034]         name: run_tests
[034]         src: '.../0/tarantool/tarantool/test/app-tap/http_client.test.lua'
[034]       - line: 616
[034]         source: '@/builds/M4RrgQZ3/0/tarantool/tarantool/test/app-tap/http_client.test.lua'
[034]         filename: /builds/M4RrgQZ3/0/tarantool/tarantool/test/app-tap/http_client.test.lua
[034]         what: Lua
[034]         namewhat: local
[034]         name: fun
[034]         src: '.../0/tarantool/tarantool/test/app-tap/http_client.test.lua'
[034]       - line: 218
[034]         source: '@builtin/tap.lua'
[034]         filename: builtin/tap.lua
[034]         what: Lua
[034]         namewhat: method
[034]         name: test
[034]         src: builtin/tap.lua
[034]       - line: 0
[034]         source: '@/builds/M4RrgQZ3/0/tarantool/tarantool/test/app-tap/http_client.test.lua'
[034]         filename: /builds/M4RrgQZ3/0/tarantool/tarantool/test/app-tap/http_client.test.lua
[034]         what: main
[034]         namewhat: 
[034]         src: '.../0/tarantool/tarantool/test/app-tap/http_client.test.lua'
[034]       line: 0
[034]       expected: 200
[034]       got: 595
[034]       ...
[034] 
[034] Last 15 lines of Tarantool Log file [Instance "app_server"][/builds/M4RrgQZ3/0/tarantool/tarantool/test/var/034_app-tap/http_client.test.lua.tarantool.log]:
[034] Traceback (most recent call last):
[034]   File "/builds/M4RrgQZ3/0/tarantool/tarantool/test/app-tap/httpd.py", line 141, in <module>
[034]     sock.bind(sock_addr)
[034]   File "<string>", line 1, in bind
[034] socket.error: [Errno 98] Address already in use
```

Steps to reproduce:

Optional (but very desirable):
* coredump
* backtrace
* netstat

**Comment by Totktonada** [comment]
Let's bind to zero port in httpd.py and catch the actual port from its stdout in the test.
