### ISSUE TITLE
PANIC: unprotected error in call to Lua API (not enough memory) on select from large space

### ISSUE THREAD

**Issue by Anei** [tarantool/tarantool#562]
Tarantool crashes on select from a large space:

In interactive mode run:

``` lua
box.cfg{slab_alloc_arena = 4.0}                                                  
s = box.schema.space.create('t')                                             
s:create_index('ind', {parts = {1, 'num'}})                                                                                                               
i = 0
console = require('console')
console.delimiter('!')                                                             
while i < 50000000 do                                                            
    s:auto_increment{i}                                                          
    i = i + 1                                                                    
end!

#s:select{}
```

(I used hash to suppress output if Tarantool will not crash)
I got:

> tarantool> #s:select{}
> PANIC: unprotected error in call to Lua API (not enough memory)
> 2014-10-07 17:49:09.258 [59753] main/101/spawner I> Exiting: master shutdown

After restart I got same error, but Tarantool did'nt shutdown, it just stopped to react.

tarantool: version 1.6.3-341-gf82473f

**Comment by nabihach** [comment]
One way to fix this is to install torch with Lua 5.2 instead of LuaJIT, as described here: [http://torch.ch/docs/getting-started.html#_](url)

**Comment by unera** [comment]
```txt
#0  0x4e68c9 in print_backtrace+9
#1  0x4ceb29 in tarantool_panic_handler+29
#2  0x500823 in lj_err_throw+73
#3  0x500a1b in lj_err_mem+3b
#4  0x500478 in lj_mem_realloc+48
#5  0x502d35 in lj_tab_resize+f5
#6  0x5030ad in rehashtab+1ad
#7  0x4fff5d in gc_onestep+59d
#8  0x500134 in lj_gc_step+54
#9  0x50d368 in lua_pushcclosure+e8
#10 0x4c0b63 in box_lua_call+43
#11 0x4bf249 in box_process_call+129
#12 0x410b42 in _ZL15tx_process_callP4cmsg+d2
#13 0x4e8194 in cmsg_deliver+14
#14 0x4e8d19 in fiber_pool_f+c9
#15 0x40e73c in _ZL16fiber_cxx_invokePFiP13__va_list_tagES0_+c
#16 0x4e3630 in fiber_loop+30
#17 0x613f3f in coro_init+3f
#18 (nil) in +3f
2018-03-24 06:08:56.351 [24160] main/134492/main C> not enough memory
```

- I don't select more than 150 tuples
- I don't use iproto select/insert/etc, only iproto lua call
- database size - 26 Mb, arena 6Gb, Host RAM - 10Gb

before dead situation (`box.runtime`):

![](https://hsto.org/webt/lk/r0/qo/lkr0qozpyqnlvugxhbwzhrpevye.png)

**Comment by Totktonada** [comment]
Possibly related to #3751.

**Comment by Totktonada** [comment]
Verified on tarantool 2.3.0-214-gd60e63d8d on Linux. Let's show my observations.

Built it as follows:

```sh
$ cmake . -DCMAKE_BUILD_TYPE=Debug -DENABLE_BACKTRACE=ON -DENABLE_DIST=ON && make -j
```

Run the test case twice:

```sh
$ cat test/long_run-py/lua/finalizers.lua
#!/usr/bin/env tarantool

function on_gc(t)
end;

function test_finalizers()
    local result = {}
    local i = 1
    local ffi = require('ffi')
    while true do
        result[i] = ffi.gc(ffi.cast('void *', 0), on_gc)
        i = i + 1
    end
    return "done"
end;

test_finalizers()
test_finalizers()

$ ./src/tarantool test/long_run-py/lua/finalizers.lua
LuajitError: not enough memory
fatal error, exiting the event loop
$ ./src/tarantool test/long_run-py/lua/finalizers.lua
#0  0x555a89102f83 in print_backtrace+9
#1  0x555a890dba43 in tarantool_panic_handler+39
#2  0x555a891394d7 in lj_err_throw+89
#3  0x555a89139662 in lj_err_mem+138
#4  0x555a89138aae in lj_mem_realloc+94
#5  0x555a8913d9e0 in lj_tab_resize+306
#6  0x555a8913e2d7 in rehashtab+110
#7  0x555a8913e7d4 in lj_tab_newkey+d6
#8  0x555a8913f0cd in lj_tab_set+1d5
#9  0x555a891bdff3 in lj_cdata_setfin+247
#10 0x555ab321fee2 in +247
not enough memory
#2 (null) (), test/long_run-py/lua/finalizers.lua:17
```

I added pcalls:

```
diff --git a/test/long_run-py/lua/finalizers.lua b/test/long_run-py/lua/finalizers.lua
index 69146a323..83c7c4896 100644
--- a/test/long_run-py/lua/finalizers.lua
+++ b/test/long_run-py/lua/finalizers.lua
@@ -14,6 +14,6 @@ function test_finalizers()
     return "done"
 end;
 
-test_finalizers()
-test_finalizers()
+pcall(test_finalizers)
+pcall(test_finalizers)
```

And the test fails 13 times in row (7 times in the first call, 6 times in the second one).

But if I run it as follows, 'not enough memory' exception is catched as should:

```sh
$ ./src/tarantool -e 'jit.off()' test/long_run-py/lua/finalizers.lua
```

I heard that @GeorgyKirichenko said that it is stack unwinding problem: we're unable to find a frame with pcall in some cases.

**Comment by rtsisyk** [comment]
Wow, it's been a while. Thanks for fixing.

**Comment by igormunkin** [comment]
The issue is finally resolved in scope of tarantool/luajit@7b98314 and submodule is bumped in scope of fcb41bb.
