### ISSUE TITLE
False positive panic  when yield in debug hook

### ISSUE THREAD

**Issue by Buristan** [tarantool/tarantool#5649]
`fiber.yield()` is forbidden only in GC finalizers. But unfortunately panic can be obtained in any of debug hooks.

Thanks to @filonenko-mikhail for report and @igormunkin for reproducer:
```bash 
$ tarantool -e 'debug.sethook(function(htype, ...) require"fiber".yield() end, "c") print(nil)'
```
Result:
```
#0  0x55a692433a89 in print_backtrace+9
#1  0x55a69240d466 in tarantool_panic_handler+26
#2  0x55a69241591a in cord_on_yield+6a
#3  0x55a69242fbe5 in fiber_yield+105
#4  0x55a69242fea2 in fiber_yield_timeout+62
#5  0x55a69242ff12 in fiber_sleep+42
#6  0x55a692410386 in lbox_fiber_yield+16
#7  0x55a692484667 in lj_BC_FUNCC+34
#8  0x55a69245e860 in callhook+80
#9  0x55a69245f5bf in lj_dispatch_call+25f
#10 0x55a69248605d in lj_vm_hotcall+1e
#11 0x55a692466561 in lua_pcall+81
#12 0x55a692415144 in luaT_call+14
#13 0x55a69240dba0 in run_script_f+110
#14 0x55a69229a11d in _ZL16fiber_cxx_invokePFiP13__va_list_tagES0_+d
#15 0x55a69242fd20 in fiber_loop+30
#16 0x55a692629710 in coro_init+40
fiber 103 is switched while running GC finalizer (i.e. __gc metamethod)
#2 (null) (), (command line):1
#3 print (global), [C]:-1
#4 (null) (), (command line):1
```

**Comment by igormunkin** [comment]
The degradation is introduced in scope of [these](https://github.com/tarantool/tarantool/issues/4518#issuecomment-704259323) changes.
