### ISSUE TITLE
Assertion with select and join and hash index

### ISSUE THREAD

**Issue by pgulutzan** [tarantool/tarantool#5678]
I have Ubuntu 18.04.
I have Tarantool 2.6, pulled from source today.
I execute these requests:
```lua
box.schema.space.create('T')
box.space.T:create_index('I',{type='hash'})
box.space.T:format({{name='COLUMN_1',type='unsigned'}})
box.execute([[SELECT a.column_1 FROM t a,t;]])
```
Result:
```
tarantool: /home/pgulutzan/tarantool-2.6/src/box/sql/vdbeaux.c:813: vdbeVComment: Assertion `p->aOp == 0 || p->aOp[p->nOp - 1].zComment == 0 || p->db->mallocFailed' failed.
Aborted (core dumped)
```

**Comment by Totktonada** [comment]
Reproduced on 2.11.0-entrypoint-164-ge797a7483.

```c
(gdb) bt
#0  0x00007ffff709006c in __pthread_kill_implementation () from /lib64/libc.so.6
#1  0x00007ffff7044792 in raise () from /lib64/libc.so.6
#2  0x00007ffff702f449 in abort () from /lib64/libc.so.6
#3  0x00007ffff702f375 in __assert_fail_base.cold () from /lib64/libc.so.6
#4  0x00007ffff703da72 in __assert_fail () from /lib64/libc.so.6
#5  0x000055555576c839 in vdbeVComment (p=0x555556ded928, zFormat=0x5555559e1620 "%s", ap=0x7ffff49ff140) at <...>/src/box/sql/vdbeaux.c:782
#6  0x000055555576c9c5 in sqlVdbeComment (p=0x555556ded928, zFormat=0x5555559e1620 "%s") at <...>/src/box/sql/vdbeaux.c:798
#7  0x0000555555780389 in sqlWhereBegin (pParse=0x7ffff49ff980, pTabList=0x555556decf28, pWhere=0x0, pOrderBy=0x0, pDistinctSet=0x555556ded528, wctrlFlags=0, iAuxArg=320)
    at <...>/src/box/sql/where.c:4647
#8  0x000055555574d66d in sqlSelect (pParse=0x7ffff49ff980, p=0x555556dec728, pDest=0x7ffff49ff7d0) at <...>/src/box/sql/select.c:6148
#9  0x00005555556e9ab2 in yy_reduce (yypParser=0x555556df7fb8, yyruleno=71) at <...>/src/box/sql/parse.y:462
#10 0x00005555556ef0a6 in sqlParser (yyp=0x555556df7fb8, yymajor=1, yyminor=..., pParse=0x7ffff49ff980) at <...>_build/src/box/sql/parse.c:4661
#11 0x0000555555750802 in sqlRunParser (pParse=0x7ffff49ff980, zSql=0x555556dedd28 "SELECT a.column_1 FROM t a,t;") at <...>/src/box/sql/tokenize.c:546
#12 0x0000555555733975 in sql_stmt_compile (zSql=0x401fddf8 "SELECT a.column_1 FROM t a,t;", nBytes=29, pReprepare=0x0, ppStmt=0x7ffff49ffd00, pzTail=0x0) at <...>/src/box/sql/prepare.c:81
#13 0x00005555556dcdc1 in sql_prepare_and_execute (sql=0x401fddf8 "SELECT a.column_1 FROM t a,t;", len=29, bind=0x0, bind_count=0, port=0x7ffff49ffd60, region=0x7ffff4800510)
    at <...>/src/box/execute.c:620
#14 0x00005555557b1b29 in lbox_execute (L=0x40000378) at <...>/src/box/lua/execute.c:492
#15 0x0000555555840987 in lj_BC_FUNCC () at buildvm_x86.dasc:811
#16 0x00005555558479cf in lua_pcall (L=0x40000378, nargs=<optimized out>, nresults=0, errfunc=<optimized out>) at <...>/third_party/luajit/src/lj_api.c:1187
#17 0x00005555557c7caa in luaT_call (L=0x40000378, nargs=0, nreturns=0) at <...>/src/lua/utils.c:471
#18 0x00005555557bf8d2 in lua_main (L=0x40000378, argc=1, argv=0x555555c74f50) at <...>/src/lua/init.c:848
#19 0x00005555557bff9e in run_script_f (ap=0x7ffff48005d0) at <...>/src/lua/init.c:964
#20 0x0000555555589ffa in fiber_cxx_invoke(fiber_func, typedef __va_list_tag __va_list_tag *) (f=0x5555557bf8eb <run_script_f>, ap=0x7ffff48005d0) at <...>/src/lib/core/fiber.h:976
#21 0x00005555557f0a4e in fiber_loop (data=0x0) at <...>/src/lib/core/fiber.c:940
#22 0x00005555559769be in coro_init () at <...>/third_party/coro/coro.c:108
```
