### ISSUE TITLE
box/insert.test.lua spontaneous crashes

### ISSUE THREAD

**Issue by rtsisyk** [tarantool/tarantool#586]
```
(gdb) bt
#0  0x00007f7d73dd7407 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x00007f7d73dd87e8 in __GI_abort () at abort.c:89
#2  0x000000000041d4b1 in sig_fatal_cb (signo=11) at /data/work/tarantool/master/src/tarantool.cc:212
#3  <signal handler called>
#4  0x000000000050ed97 in lj_alloc_free ()
#5  0x00000000005103d8 in lj_alloc_f ()
#6  0x000000000050a430 in lj_cdata_free ()
#7  0x00000000004f248e in gc_sweep ()
#8  0x00000000004f3b34 in gc_onestep ()
#9  0x00000000004f3d8e in lj_gc_step ()
#10 0x00000000004f8095 in lj_meta_cat ()
#11 0x0000000000514205 in lj_BC_CAT ()
#12 0x00000000004ffa19 in lua_call ()
#13 0x0000000000499dc5 in lbox_call (L=0x40c78d28, nargs=3, nreturns=-1) at /data/work/tarantool/master/src/lua/utils.h:442
#14 0x000000000049a76a in box_lua_fiber_run_detached(typedef __va_list_tag __va_list_tag *) (ap=0x7f7d73000128) at /data/work/tarantool/master/src/lua/fiber.cc:277
#15 0x000000000048005d in fiber_loop (data=0x0) at /data/work/tarantool/master/src/fiber.cc:391
#16 0x00000000004c711c in coro_init () at /data/work/tarantool/master/third_party/coro/coro.c:95
```

How to reproduce:
```
while ./run.sh; do sleep 1; done
```

1.6.3-514-g2ba3e80

**Comment by kostja** [comment]
Can you reproduce it now?

**Comment by rtsisyk** [comment]
I can't. It seems to be fixed.
