### ISSUE TITLE
Selecting a field of type 'uuid' via SQL results in a segfault

### ISSUE THREAD

**Issue by msiomkin** [tarantool/tarantool#5913]
OS: CentOS Linux release 8.0.1905

Tarantool version:
```
[vagrant@localhost ~]$ tarantool --version
Tarantool 2.8.0-0-gefc30ccf8
Target: Linux-x86_64-RelWithDebInfo
Build options: cmake . -DCMAKE_INSTALL_PREFIX=/usr/local -DENABLE_BACKTRACE=ON
Compiler: /bin/cc /bin/c++
C_FLAGS: -fexceptions -funwind-tables -fno-omit-frame-pointer -fno-stack-protector -fno-common -fopenmp -msse2 -std=c11 -Wall -Wextra -Wno-strict-aliasing -Wno-char-subscripts -Wno-format-truncation -Wno-gnu-alignof-expression -fno-gnu89-inline -Wno-cast-function-type
CXX_FLAGS: -fexceptions -funwind-tables -fno-omit-frame-pointer -fno-stack-protector -fno-common -fopenmp -msse2 -std=c++11 -Wall -Wextra -Wno-strict-aliasing -Wno-char-subscripts -Wno-format-truncation -Wno-invalid-offsetof -Wno-gnu-alignof-expression -Wno-cast-function-type
```

Reproducer script:
``` Lua
box.cfg{}
box.schema.create_space('my_space')
box.space.my_space:format({{name = "id", type = "number"}, {name = "key", type = "uuid"}})
box.space.my_space:insert({1, require("uuid").fromstr("03511f76-d562-459b-a670-c8489b2545fd")})

box.execute([[select * from "my_space"]])
```

Result:
```
Segmentation fault
  code: SEGV_MAPERR
  addr: (nil)
  context: 0x7eff72dff740
  siginfo: 0x7eff72dff870
  rax      0xa                10
  rbx      0x1                1
  rcx      0x4d00010000       330712547328
  rdx      0x4d00010000       330712547328
  rsi      0x40               64
  rdi      0x1903958          26229080
  rsp      0x7eff72dffd00     139635609042176
  rbp      0x7eff72dffd60     139635609042272
  r8       0x7eff62008d99     139635325963673
  r9       0x2                2
  r10      0xf                15
  r11      0x2                2
  r12      0x1954c88          26561672
  r13      0x7eff72c00390     139635606946704
  r14      0xa                10
  r15      0x1                1
  rip      0x0                0
  eflags   0x10246            66118
  cs       0x33               51
  gs       0x0                0
  fs       0x0                0
  cr2      0x0                0
  err      0x14               20
  oldmask  0x0                0
  trapno   0xe                14
Current time: 1616079230
Please file a bug at http://github.com/tarantool/tarantool/issues
Attempting backtrace... Note: since the server has already crashed,
this may fail as well
#0  0x5dafce in crash_signal_cb+8e
#1  0x7eff74253dd0 in funlockfile+50
#2  (nil) in +50
#3  0x597223 in sql_prepare_and_execute+d3
#4  0x5025dc in lbox_execute+16c
#5  0x635d7b in lj_BC_FUNCC+34
#6  0x617822 in lua_pcall+82
#7  0x5c5333 in luaT_call+13
#8  0x5bdf79 in lua_main+59
#9  0x5be1f1 in run_script_f+261
#10 0x45386c in _ZL16fiber_cxx_invokePFiP13__va_list_tagES0_+c
#11 0x5e0ea0 in fiber_loop+30
#12 0x7ca99f in coro_init+3f
Aborted (core dumped)
```

Expected behaviour (it works fine in 2.6.1 on MacOS(!)):
```
tarantool> box.execute([[select * from "my_space"]])
---
- metadata:
  - name: id
    type: number
  - name: key
    type: uuid
  rows:
  - [1, 03511f76-d562-459b-a670-c8489b2545fd]
...
```

**Comment by pgulutzan** [comment]
Segmentation fault with uuid is mentioned already in #5011 plus #5704
