### ISSUE TITLE
vinyl: crash after setting box.cfg.read_only option

### ISSUE THREAD

**Issue by Korablev77** [tarantool/tarantool#5934]
```
box.cfg{}
space = box.schema.space.create("SPACE", {
engine="vinyl", 
format = {
{name = "key", type = "unsigned"}, 
{name = "value", type = "unsigned"}}
})

space:create_index('key', { parts = { 'key' }, unique = true })
box.begin() space:update(1,  { { '+', 2, 1 } }) space:insert {1, 1} box.commit()
box.cfg({read_only=true})

#0  0x5634bd08bbf0 in crash_collect+c5
#1  0x5634bd08dc01 in crash_signal_cb+51
#2  0x7fda29be1890 in funlockfile+50
#3  0x5634bcffd085 in vy_tx_manager_abort_writers_for_ro+2e
#4  0x5634bcfcbe0b in vinyl_engine_switch_to_ro+2c
#5  0x5634bcfb2e4a in engine_switch_to_ro+3a
#6  0x5634bcecb894 in box_update_ro_summary+77
#7  0x5634bcecbcfb in box_set_ro+14
#8  0x5634bcf8d75e in _ZL22lbox_cfg_set_read_onlyP9lua_State+12
#9  0x5634bd140aab in lj_BC_FUNCC+34
#10 0x5634bd0d2743 in lua_pcall+1de
#11 0x5634bd070e4c in luaT_call+29
#12 0x5634bd0680d3 in lua_main+b9
#13 0x5634bd06877e in run_script_f+692
#14 0x5634bce8f063 in _ZL16fiber_cxx_invokePFiP13__va_list_tagES0_+1e
#15 0x5634bd095900 in fiber_loop+82
#16 0x5634bd35fa88 in coro_init+4c
```

**Comment by Korablev77** [comment]
Closed in c8e5670a81ff2cc73e1b5a3e377f7163d35a22aa
