### ISSUE TITLE
sql: ORDER BY and LIMIT on the generated column using LUA lead to a segmentation fault

### ISSUE THREAD

**Issue by Sunsh1neRus** [tarantool/tarantool#5942]
Tarantool version: 2.6.2-0-g34d504d7d / any_which_has_SQL
OS: Linux
OS Version: Debian / Ubuntu / doesnt_matter

Bug description: When I generate column in a SQL query using the LUA code, I cannot sort and specify a limit for this column at the same time, because there is a segmentation fault. If only limit or sorting, then everything works as it should.

Steps to reproduce:

```
-- segmentation fault:
box.execute([[SELECT lua('return math.random(1,100)') as "rand" FROM "_space" ORDER BY "rand" DESC LIMIT 1]])

-- its ok:
box.execute([[SELECT lua('return math.random(1,100)') as "rand" FROM "_space" LIMIT 1]])

-- its ok:
box.execute([[SELECT lua('return math.random(1,100)') as "rand" FROM "_space" ORDER BY "rand" DESC]])

-- its ok:
box.execute([[SELECT "id" FROM "_space" ORDER BY "id" DESC LIMIT 1]])
```
Logs:
```
tnt_1    | Segmentation fault
tnt_1    |   code: SEGV_MAPERR
tnt_1    |   addr: 0
tnt_1    |   context: 0x7f79271ff500
tnt_1    |   siginfo: 0x7f79271ff630
tnt_1    |   rax      0x55c85f9225c0     94319085233600
tnt_1    |   rbx      0x55c861819f00     94319117704960
tnt_1    |   rcx      0x0                0
tnt_1    |   rdx      0x7f76a70cc0d4     140147585499348
tnt_1    |   rsi      0x55c86181bd20     94319117712672
tnt_1    |   rdi      0x7f76a70cc0d4     140147585499348
tnt_1    |   rsp      0x7f79271ffaa8     140158324177576
tnt_1    |   rbp      0x7f79271ffb10     140158324177680
tnt_1    |   r8       0x7f79271ffb28     140158324177704
tnt_1    |   r9       0x7f7927040113     140158322344211
tnt_1    |   r10      0x2                2
tnt_1    |   r11      0x7f76a70cc000     140147585499136
tnt_1    |   r12      0x7f79271ffb28     140158324177704
tnt_1    |   r13      0x7f76a70cc0d4     140147585499348
tnt_1    |   r14      0x55c86181bd20     94319117712672
tnt_1    |   r15      0x0                0
tnt_1    |   rip      0x0                0
tnt_1    |   eflags   0x10206            66054
tnt_1    |   cs       0x33               51
tnt_1    |   gs       0x0                0
tnt_1    |   fs       0x0                0
tnt_1    |   cr2      0x0                0
tnt_1    |   err      0x14               20
tnt_1    |   oldmask  0x0                0
tnt_1    |   trapno   0xe                14
tnt_1    | Current time: 1616753474
tnt_1    | Please file a bug at http://github.com/tarantool/tarantool/issues
tnt_1    | Attempting backtrace... Note: since the server has already crashed,
tnt_1    | this may fail as well
tnt_1    | #0  0x55c85f5bd5c9 in crash_signal_cb+99
tnt_1    | #1  0x7f7929aff9b7 in sigwaitinfo+8
tnt_1    | #2  0x55c85f4f4f24 in memtx_space_replace_all_keys+74
tnt_1    | #3  0x55c85f4f2cec in memtx_space_ephemeral_replace+3c
tnt_1    | #4  0x55c85f4b449d in sqlVdbeExec+374d
tnt_1    | #5  0x55c85f4b6e2b in sql_step+4b
tnt_1    | #6  0x55c85f575708 in sql_execute+58
tnt_1    | #7  0x55c85f578353 in sql_prepare_and_execute+d3
tnt_1    | #8  0x55c85f4e261c in lbox_execute+16c
tnt_1    | #9  0x55c85f619a2b in lj_BC_FUNCC+34
tnt_1    | #10 0x55c85f5faed2 in lua_pcall+82
tnt_1    | #11 0x55c85f5a7353 in luaT_call+13
tnt_1    | #12 0x55c85f5a0c35 in lua_fiber_run_f+55
tnt_1    | #13 0x55c85f43176c in _ZL16fiber_cxx_invokePFiP13__va_list_tagES0_+c
tnt_1    | #14 0x55c85f5c3480 in fiber_loop+30
tnt_1    | #15 0x55c85f7b711f in coro_init+3f
```

The same functionality can be added via a stored function and there will be no error:
```
box.schema.func.create('RAND',
     {language = 'LUA',
      returns = 'integer',
      body = [[function (start,final)
          return math.random(start,final)
          end]],
     is_sandboxed = false,
     param_list = {'integer','integer'},
     exports = {'LUA', 'SQL'},
     is_deterministic = true})

box.execute([[SELECT RAND(1,100) as "rand" FROM "_space" ORDER BY "rand" DESC LIMIT 1]])
```

**Comment by ImeevMA** [comment]
Closed by commit https://github.com/tarantool/tarantool/commit/d61f39a083dbcf26cba8428c139ced036f736e17. The problem was that the field type that was used for ordering was calculated as ANY. However, fields of this type cannot be sorted.
