### ISSUE TITLE
rtree: iterator destroy crash

### ISSUE THREAD

**Issue by filonenko-mikhail** [tarantool/tarantool#5944]
**Bug description**

Hard to reproduce again.

It seems something wents wrong when using `rtree`.

```
#0  0x1006591a9 in print_backtrace+9
#1  0x1004e98a1 in _ZL12sig_fatal_cbiP9__siginfoPv+151
#2  0x7fff6f6635fd in _sigtramp+1d
#3  0x100e08e81 in rtree_iterator_destroy+11
#4  0x100512f52 in index_rtree_iterator_free+12
#5  0x100683b64 in lj_vm_ffi_call+84
#6  0x1006dee8e in lj_ccall_func+81e
#7  0x1006f3f57 in lj_cf_ffi_meta___call+67
#8  0x100681735 in lj_BC_FUNCC+44
#9  0x100683e82 in gc_finalize+1e2
#10 0x1006846bb in gc_onestep+47b
#11 0x100684948 in lj_gc_step_fixtop+88
#12 0x100680910 in lj_BC_TDUP+61
#13 0x1006996e8 in lua_pcall+a8
#14 0x10063e823 in luaT_call+13
#15 0x10063a057 in lua_fiber_run_f+57
#16 0x1004e93cc in _ZL16fiber_cxx_invokePFiP13__va_list_tagES0_+c
#17 0x100656263 in fiber_loop+43
#18 0x100e29b1b in coro_init+4b
```

Environment:

Make just simple space:

```lua
    box.schema.space.create('streets', {if_not_exists=true})
    box.space.streets:format({
            {name="_id", type="string"},
            {name="type", type="string"},
            {name="geometry.type", type="string"},
            {name="geometry.coordinates", type="array"},
            {name="properties.comment", type="string"},
            {name="properties.rate", type="unsigned"},
            {name="bucket_id", type="unsigned"},
    })
    box.space.streets:create_index('primary', {
        parts={{field="_id", type="string"}},
        type = 'TREE',
        if_not_exists=true,})
    box.space.streets:create_index('bucket_id', {
        parts={{field="bucket_id", type="unsigned"}},
        type = 'TREE',
        unique = false,
        if_not_exists=true,})
    box.space.streets:create_index('spatial', { 
        parts = {{ field="geometry.coordinates", type='array'} },
        type = 'RTREE', unique = false,
        if_not_exists=true,})
```

```lua
for _, place in box.space.streets.index.spatial:pairs({1, 1}, {iterator='neighbor'}) do 
  -- something
end
```

**Comment by kyukhin** [comment]
Does your sample reproduce the problem?

**Comment by filonenko-mikhail** [comment]
Still no. Come back later
