### ISSUE TITLE
test: luajit test gh-4427-ffi-sandwich.test.lua fails

### ISSUE THREAD

**Issue by avtikhon** [tarantool/tarantool#5986]
**Bug description**

In debug build luajit test 'gh-4427-ffi-sandwich.test.lua' fails running right after the build/rebuild, w/o prebuild it won't fail.

* OS: Linux
* OS Version: Ubuntu 20.04
* Architecture: amd64

Tarantool 2.8.0-227-gbd82e5c5a
Target: Linux-x86_64-Debug
Build options: cmake . -DCMAKE_INSTALL_PREFIX=/usr/local -DENABLE_BACKTRACE=ON
Compiler: /usr/bin/cc /usr/bin/c++
C_FLAGS: -fexceptions -funwind-tables -fno-omit-frame-pointer -fno-stack-protector -fno-common -fopenmp -msse2 -fprofile-arcs -ftest-coverage -std=c11 -Wall -Wextra -Wno-strict-aliasing -Wno-char-subscripts -Wno-format-truncation -Wno-gnu-alignof-expression -fno-gnu89-inline -Wno-cast-function-type -Werror
CXX_FLAGS: -fexceptions -funwind-tables -fno-omit-frame-pointer -fno-stack-protector -fno-common -fopenmp -msse2 -fprofile-arcs -ftest-coverage -std=c++11 -Wall -Wextra -Wno-strict-aliasing -Wno-char-subscripts -Wno-format-truncation -Wno-invalid-offsetof -Wno-gnu-alignof-expression -Wno-cast-function-type -Werror

**Steps to reproduce**

1. Build in debug
```
make -f .travis.mk coverage_ubuntu_ghactions
```
2. Reproduce the issue - rebuild luajit and run failing test:
```
cd ~/actions-runner/_work/tarantool/tarantool/third_party/luajit/test/tarantool-tests ; make clean ; cd ~/actions-runner/_work/tarantool/tarantool ; make -j ; make LuaJIT-test
```

**Actual behavior**

Test had to pass, but failed:
```
Running Tarantool tests
/home/ubuntu/actions-runner/_work/tarantool/tarantool/third_party/luajit/test/tarantool-tests/or-232-unsink-64-kptr.test.lua .............. ok   
/home/ubuntu/actions-runner/_work/tarantool/tarantool/third_party/luajit/test/tarantool-tests/gh-4427-ffi-sandwich.test.lua ............... 1/? 
not ok - Trace is aborted
/home/ubuntu/actions-runner/_work/tarantool/tarantool/third_party/luajit/test/tarantool-tests/gh-4427-ffi-sandwich.test.lua ............... Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/2 subtests 
/home/ubuntu/actions-runner/_work/tarantool/tarantool/third_party/luajit/test/tarantool-tests/gh-4773-tonumber-fail-on-NUL-char.test.lua .. ok   
/home/ubuntu/actions-runner/_work/tarantool/tarantool/third_party/luajit/test/tarantool-tests/lj-505-fold-no-strref-for-ptrdiff.test.lua .. ok   
/home/ubuntu/actions-runner/_work/tarantool/tarantool/third_party/luajit/test/tarantool-tests/misclib-getmetrics-capi.test.lua ............ libgcov profiling error:/home/ubuntu/actions-runner/_work/tarantool/tarantool/third_party/luajit/test/tarantool-tests/misclib-getmetrics-capi/CMakeFiles/testgetmetrics.dir/testgetmetrics.c.gcda:overwriting an existing profile data with a different timestamp
/home/ubuntu/actions-runner/_work/tarantool/tarantool/third_party/luajit/test/tarantool-tests/misclib-getmetrics-capi.test.lua ............ ok    
/home/ubuntu/actions-runner/_work/tarantool/tarantool/third_party/luajit/test/tarantool-tests/gh-4476-fix-string-find-recording.test.lua .. ok   
/home/ubuntu/actions-runner/_work/tarantool/tarantool/third_party/luajit/test/tarantool-tests/misclib-memprof-lapi.test.lua ............... ok   
/home/ubuntu/actions-runner/_work/tarantool/tarantool/third_party/luajit/test/tarantool-tests/gh-3196-incorrect-string-length.test.lua .... ok   
/home/ubuntu/actions-runner/_work/tarantool/tarantool/third_party/luajit/test/tarantool-tests/misclib-getmetrics-lapi.test.lua ............ ok    
/home/ubuntu/actions-runner/_work/tarantool/tarantool/third_party/luajit/test/tarantool-tests/lj-494-table-chain-infinite-loop.test.lua ... ok   
/home/ubuntu/actions-runner/_work/tarantool/tarantool/third_party/luajit/test/tarantool-tests/lj-flush-on-trace.test.lua .................. 1/? 
not ok - Trace is aborted
/home/ubuntu/actions-runner/_work/tarantool/tarantool/third_party/luajit/test/tarantool-tests/lj-flush-on-trace.test.lua .................. Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/2 subtests 
/home/ubuntu/actions-runner/_work/tarantool/tarantool/third_party/luajit/test/tarantool-tests/lj-524-fold-conv-respect-src-irt.test.lua ... ok   

Test Summary Report
-------------------
/home/ubuntu/actions-runner/_work/tarantool/tarantool/third_party/luajit/test/tarantool-tests/gh-4427-ffi-sandwich.test.lua             (Wstat: 256 Tests: 2 Failed: 1)
  Failed test:  1
  Non-zero exit status: 1
/home/ubuntu/actions-runner/_work/tarantool/tarantool/third_party/luajit/test/tarantool-tests/lj-flush-on-trace.test.lua                (Wstat: 256 Tests: 2 Failed: 1)
  Failed test:  1
  Non-zero exit status: 1
Files=12, Tests=44,  3 wallclock secs ( 0.07 usr  0.02 sys +  1.50 cusr  0.28 csys =  1.87 CPU)
Result: FAIL
make[3]: *** [third_party/luajit/test/tarantool-tests/CMakeFiles/tarantool-tests.dir/build.make:84: tarantool-tests] Error 1
make[2]: *** [CMakeFiles/Makefile2:2383: third_party/luajit/test/tarantool-tests/CMakeFiles/tarantool-tests.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:2306: third_party/luajit/test/CMakeFiles/LuaJIT-test.dir/rule] Error 2
make: *** [Makefile:621: LuaJIT-test] Error 2
```
After rerun 'make LuaJIT-test' or even manually all tests passed:
```
cd ~/actions-runner/_work/tarantool/tarantool/third_party/luajit/test/tarantool-tests ; /usr/bin/prove /home/ubuntu/actions-runner/_work/tarantool/tarantool/third_party/luajit/test/tarantool-tests --exec '/home/ubuntu/actions-runner/_work/tarantool/tarantool/src/tarantool -e dofile[[/home/ubuntu/actions-runner/_work/tarantool/tarantool/test/luajit-test-init.lua]]' --ext .test.lua --failures --verbose --shuffle
```

**Expected behavior**

Test had to pass.

Found that the root cause of the issue is existence of *.gcda files as:
```
ls third_party/luajit/test/tarantool-tests/*/CMakeFiles/*.dir/*.gcda
third_party/luajit/test/tarantool-tests/gh-4427-ffi-sandwich/CMakeFiles/libsandwich.dir/libsandwich.c.gcda
third_party/luajit/test/tarantool-tests/lj-flush-on-trace/CMakeFiles/libflush.dir/libflush.c.gcda
third_party/luajit/test/tarantool-tests/misclib-getmetrics-capi/CMakeFiles/testgetmetrics.dir/testgetmetrics.c.gcda
```
Temporary check fixed the issue:
```
diff --git a/test/tarantool-tests/CMakeLists.txt b/test/tarantool-tests/CMakeLists.txt
index 475e2e5d..95a4492d 100644
--- a/test/tarantool-tests/CMakeLists.txt
+++ b/test/tarantool-tests/CMakeLists.txt
@@ -118,7 +118,7 @@ add_custom_command(TARGET tarantool-tests
   COMMAND
   env
     ${LUA_TEST_ENV}
-    ${PROVE} ${CMAKE_CURRENT_SOURCE_DIR}
+    rm /home/ubuntu/actions-runner/_work/tarantool/tarantool/third_party/luajit/test/tarantool-tests/*/CMakeFiles/*.dir/*.gcda && ${PROVE} ${CMAKE_CURRENT_SOURCE_DIR}
       --exec '${LUAJIT_TEST_COMMAND}'
       --ext ${LUA_TEST_SUFFIX}
       ${LUA_TEST_FLAGS}
```
Seems that luajit make tries to recreate these *.gcda files and fails.

**Comment by Totktonada** [comment]
Can you clarify, why the test is declared as flaky? AFAIU, in the situation you show, it always fail. So, the described situation occurs in CI from time to time? I hope it should not occur in CI: we should never see an old build artifacts.

**Comment by avtikhon** [comment]
> Can you clarify, why the test is declared as flaky? AFAIU, in the situation you show, it always fail. So, the described situation occurs in CI from time to time? I hope it should not occur in CI: we should never see an old build artifacts.

This issue happens because of already existed *.gcda files in luajit path which were build just before the testing. Continue investigation why it triggered the issue.

**Comment by igormunkin** [comment]
[This](https://github.com/tarantool/tarantool/commit/07c83aab5c066ca75c149112b331b4dbb81b3f38#diff-4c1d8ec003f782870873e5623984a5d200aa8703a16768e363b6a8e5d43c3a75L206-L208) might be lost as a result of 07c83aa, but the tests were green all the time after this patch. BTW, is the repo used for tests cleaned prior to configuration/build step?

**Comment by avtikhon** [comment]
> [This](https://github.com/tarantool/tarantool/commit/07c83aab5c066ca75c149112b331b4dbb81b3f38#diff-4c1d8ec003f782870873e5623984a5d200aa8703a16768e363b6a8e5d43c3a75L206-L208) might be lost as a result of [07c83aa](https://github.com/tarantool/tarantool/commit/07c83aab5c066ca75c149112b331b4dbb81b3f38), but the tests were green all the time after this patch. BTW, is the repo used for tests cleaned prior to configuration/build step?

Cleanup equal to Github Actions use is:
`git clean -xffd`
it leaves "Untracked files:":
```
third_party/luajit$ git status
	tools/memprof.lua.c
	tools/memprof/humanize.lua.c
	tools/memprof/parse.lua.c
	tools/utils/bufread.lua.c
	tools/utils/symtab.lua.c
```

Running complete cleanup as was suggested in PR#5987 with fixes the issue:
```
git submodule foreach git clean -xffd
```

**Comment by igormunkin** [comment]
Trying to reproduce, I cloned tarantool/tarantool, but I failed to checkout on the specified version 2.8.0-227-gbd82e5c5a (bd82e5c):
```bash
$ git checkout bd82e5c5a9042e8f7af5173b58f3d23df1e1056b
fatal: reference is not a tree: bd82e5c5a9042e8f7af5173b58f3d23df1e1056b
```

So I decided the check the issue on the current master HEAD: 2.9.0-146-g9a6356808 (9a63568). I built Tarantool the way specified in `coverage_ubuntu_ghactions` (strictly saying `build_coverage_debian`).
```bash
$ cmake . -DCMAKE_BUILD_TYPE=Debug -DENABLE_GCOV=ON -DCMAKE_VERBOSE_MAKEFILE=ON
<snipped>
-- PACKAGE: Tarantool
-- VERSION: 2.9.0-146-g9a6356808
-- BUILD: Linux-x86_64-Debug
-- C_COMPILER: /usr/bin/cc
-- CXX_COMPILER: /usr/bin/c++
-- C_FLAGS:  -fexceptions -funwind-tables -fno-omit-frame-pointer -fno-stack-protector -fno-common -fopenmp -msse2 -fprofile-arcs -ftest-coverage -std=c11 -Wall -Wextra -
Wno-strict-aliasing -Wno-char-subscripts -Wno-format-truncation -Wno-gnu-alignof-expression -fno-gnu89-inline -Wno-cast-function-type -Werror
-- CXX_FLAGS:  -fexceptions -funwind-tables -fno-omit-frame-pointer -fno-stack-protector -fno-common -fopenmp -msse2 -fprofile-arcs -ftest-coverage -std=c++11 -Wall -Wext
ra -Wno-strict-aliasing -Wno-char-subscripts -Wno-format-truncation -Wno-invalid-offsetof -Wno-gnu-alignof-expression -Wno-cast-function-type -Werror
-- PREFIX: /usr/local
-- ENABLE_SSE2: ON
-- ENABLE_AVX: OFF
-- ENABLE_GCOV: ON
-- ENABLE_GPROF: OFF
-- ENABLE_VALGRIND: OFF
-- ENABLE_ASAN: OFF
-- ENABLE_UB_SANITIZER: OFF
-- ENABLE_FUZZER: OFF
-- ENABLE_BACKTRACE: ON
-- ENABLE_DIST: OFF
-- ENABLE_BUNDLED_LIBCURL: ON
-- ENABLE_BUNDLED_LIBYAML: ON
-- ENABLE_BUNDLED_MSGPUCK: ON
-- 
-- Configuring done
-- Generating done
-- Build files have been written to: /tarantool
$ make -j 
<snipped>
[100%] Built target tarantool
```

At this point all LuaJIT related tests are fine:
```bash
$ make LuaJIT-test
<snipped>
[100%] Built target LuaJIT-test
```

Then I clean all build artefacts:
```bash
$ make clean
<snipped>
```

If one runs `make LuaJIT-test` again, the following error occurs:
```bash
$ make LuaJIT-test
<snipped>
/tarantool/third_party/luajit/test/tarantool-tests/gh-4427-ffi-sandwich.test.lua ......................
TAP version 13
1..2
not ok - Trace is aborted
  expected:     3
  got:  libgcov profiling error:/tarantool/third_party/luajit/test/tarantool-tests/gh-4427-ffi-sandwich/CMakeFiles/libsandwich.dir/libsandwich.c.gcda:overwriting an existing profile data with a different timestamp
3
    filename:   /tarantool/third_party/luajit/test/tarantool-tests/gh-4427-ffi-sandwich.test.lua
    line:       0
    frame #1
      line:     28
      source:   @/tarantool/third_party/luajit/test/tarantool-tests/utils.lua
      filename: /tarantool/third_party/luajit/test/tarantool-tests/utils.lua
      what:     Lua
      namewhat: field
      name:     selfrun
      src:      ...antool/third_party/luajit/test/tarantool-tests/utils.lua
    frame #2
      line:     0
      source:   @/tarantool/third_party/luajit/test/tarantool-tests/gh-4427-ffi-sandwich.test.lua
      filename: /tarantool/third_party/luajit/test/tarantool-tests/gh-4427-ffi-sandwich.test.lua
      what:     main
      namewhat:
      src:      ...uajit/test/tarantool-tests/gh-4427-ffi-sandwich.test.lua
#0  0x56059d3406f0 in print_backtrace+3d
#1  0x56059d2f4c8d in tarantool_panic_handler+4a
#2  0x56059d389f58 in jit_secure_call+1bf
#3  0x56059d393998 in lua_call+eb
#4  0x7ffa67412762 in increment+b9
#5  0x5605c751ffd5 in +b9
Lua VM re-entrancy is detected while executing the trace
ok - Trace is recorded
# failed subtest: 1
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/2 subtests 
/tarantool/third_party/luajit/test/tarantool-tests/gh-4476-fix-string-find-recording.test.lua .........
TAP version 13
1..1
ok - nil
ok
/tarantool/third_party/luajit/test/tarantool-tests/lj-flush-on-trace.test.lua .........................
TAP version 13
1..2
not ok - Trace is aborted
  expected:     OK
  got:  libgcov profiling error:/tarantool/third_party/luajit/test/tarantool-tests/lj-flush-on-trace/CMakeFiles/libflush.dir/libflush.c.gcda:overwriting an existing profile data with a different timestamp
OK
    filename:   /tarantool/third_party/luajit/test/tarantool-tests/lj-flush-on-trace.test.lua
    line:       0
    frame #1
      line:     28
      source:   @/tarantool/third_party/luajit/test/tarantool-tests/utils.lua
      filename: /tarantool/third_party/luajit/test/tarantool-tests/utils.lua
      what:     Lua
      namewhat: field
      name:     selfrun
      src:      ...antool/third_party/luajit/test/tarantool-tests/utils.lua
    frame #2
      line:     0
      source:   @/tarantool/third_party/luajit/test/tarantool-tests/lj-flush-on-trace.test.lua
      filename: /tarantool/third_party/luajit/test/tarantool-tests/lj-flush-on-trace.test.lua
      what:     main
      namewhat:
      src:      ...y/luajit/test/tarantool-tests/lj-flush-on-trace.test.lua
#0  0x5636e80b66f0 in print_backtrace+3d
#1  0x5636e806ac8d in tarantool_panic_handler+4a
#2  0x5636e810fd68 in luaJIT_setmode+1d3
#3  0x7fe8cef55576 in flush+4d
#4  0x56371229fba5 in +4d
JIT mode change is detected while executing the trace
ok - Trace is recorded
# failed subtest: 1
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/2 subtests 

Test Summary Report
-------------------
/tarantool/third_party/luajit/test/tarantool-tests/gh-4427-ffi-sandwich.test.lua                    (Wstat: 256 Tests: 2 Failed: 1)
  Failed test:  1
  Non-zero exit status: 1
/tarantool/third_party/luajit/test/tarantool-tests/lj-flush-on-trace.test.lua                       (Wstat: 256 Tests: 2 Failed: 1)
  Failed test:  1
  Non-zero exit status: 1
Files=15, Tests=53,  3 wallclock secs ( 0.11 usr  0.04 sys +  1.85 cusr  0.39 csys =  2.39 CPU)
Result: FAIL
make[3]: *** [third_party/luajit/test/tarantool-tests/CMakeFiles/tarantool-tests.dir/build.make:68: tarantool-tests] Error 1
make[3]: Leaving directory '/tarantool'
make[2]: *** [CMakeFiles/Makefile2:2576: third_party/luajit/test/tarantool-tests/CMakeFiles/tarantool-tests.dir/all] Error 2
make[2]: Leaving directory '/tarantool'
make[1]: *** [CMakeFiles/Makefile2:2306: third_party/luajit/test/CMakeFiles/LuaJIT-test.dir/rule] Error 2
make[1]: Leaving directory '/tarantool'
make: *** [Makefile:579: LuaJIT-test] Error 2
```

As one can see, the output to be matched against the `expected` value, is spoiled with libgcov output about overwriting existing profile data with a different timestamp.

**Comment by igormunkin** [comment]
No failures for almost 2 years (I guess, the issue is gone, as a result of the 7ff87404 cleaning the workspace on self-hosted runners). Closing.
