### ISSUE TITLE
LuaJIT crash on trace when there is no enough mcode 

### ISSUE THREAD

**Issue by Buristan** [tarantool/tarantool#6015]
If one runs the following Lua chunk in Tarantool's console it leads to coredump:
```
tarantool> local a = {} a[a] = a local recf recf = function(t) local n = {} n[t] = setmetatable({}, {__serialize = recf}) return n end setmetatable(a, {__serialize = recf}) return a
Segmentation fault (core dumped)
```

Backtrace is the following:
```
#0  0x000055930cee8027 in lj_alloc_malloc (msp=0x5050505050505050, nsize=5787213827046133840) at /home/burii/reviews/tarantool/serialize/third_party/luajit/src/lj_alloc.c:1274
#1  0x000055930cee9c67 in lj_alloc_f (msp=0x40837010, ptr=0x0, osize=0, nsize=48) at /home/burii/reviews/tarantool/serialize/third_party/luajit/src/lj_alloc.c:1483
#2  0x000055930ceaf831 in lj_mem_realloc (L=0x40837378, p=0x0, osz=0, nsz=48) at /home/burii/reviews/tarantool/serialize/third_party/luajit/src/lj_gc.c:857
#3  0x000055930cebc764 in newhpart (hbits=1, t=0x40a9ed98, L=0x40837378) at /home/burii/reviews/tarantool/serialize/third_party/luajit/src/lj_tab.c:64
#4  lj_tab_resize (L=0x40837378, t=0x40a9ed98, asize=0, hbits=1) at /home/burii/reviews/tarantool/serialize/third_party/luajit/src/lj_tab.c:278
#5  0x000055930cebcfa3 in rehashtab (L=0x40837378, t=0x40a9ed98, ek=0x408374d8) at /home/burii/reviews/tarantool/serialize/third_party/luajit/src/lj_tab.c:387
#6  0x000055930cebd3c8 in lj_tab_newkey (L=0x40837378, t=0x40a9ed98, key=0x408374d8) at /home/burii/reviews/tarantool/serialize/third_party/luajit/src/lj_tab.c:471
#7  0x0000559336ffffc7 in ?? ()
#8  0x000000004175ebf0 in ?? ()
#9  0x00005c8640a9ed98 in ?? ()
#10 0x000055930ce64a53 in safe_write (fd=23686, buf=0x4175ebf0 "\310\353uA", size=1084878232) at /home/burii/reviews/tarantool/serialize/src/lib/core/say.c:1007
#11 0x0000000000000000 in ?? ()
```

VM state and Lua stack are the following:
```
(gdb) lj-state
VM state: TRACE
GC state: SWEEP
JIT state: IDLE

(gdb) lj-stack
0x41f45fb8:0x41f45fd8 [    ] 5 slots: Red zone
0x41f45fb0            [   M]
0x41f1e4e0:0x41f45fa8 [    ] 20314 slots: Free stack slots
0x41f1e4d8            [  T ]
0x41f1e4d0            [    ] VALUE: table @ 0x40a9ecd8 (asize: 0, hmask: 0x0)
0x41f1e4c8            [    ] VALUE: number 4.0212086698804873e-309
0x41f1e4c0            [    ] VALUE: table @ 0x40a9ecd8 (asize: 0, hmask: 0x0)
0x41f1e4b8            [    ] VALUE: table @ 0x40a9ebf0 (asize: 0, hmask: 0x0)
...
0x41ef00e8            [    ] VALUE: table @ 0x4175ed70 (asize: 0, hmask: 0x1)
0x41ef00e0            [    ] VALUE: table @ 0x4175ec78 (asize: 0, hmask: 0x0)
0x41ef00d8            [    ] VALUE: table @ 0x4175e2f8 (asize: 0, hmask: 0x1)
0x41ef00d0            [    ] VALUE: table @ 0x4175ec50 (asize: 0, hmask: 0x1)
0x41ef00c8            [    ] VALUE: table @ 0x4175e2f8 (asize: 0, hmask: 0x1)
0x41ef00c0            [    ] VALUE: number 1
0x41ef00b8            [    ] VALUE: table @ 0x4175e520 (asize: 2, hmask: 0x0)
0x41ef00b0            [    ] VALUE: table @ 0x4175ebf0 (asize: 0, hmask: 0x1fff)
0x41ef00a8            [    ] VALUE: table @ 0x4175ebc8 (asize: 0, hmask: 0x1fff)
0x41ef00a0            [    ] VALUE: thread @ 0x4175ea10
0x41ef0098            [ B  ] VALUE: table @ 0x4175e520 (asize: 2, hmask: 0x0)
0x41ef0090            [    ] FRAME: [PP] delta=1, C function @ 0x55930cd62aff
0x41ef0088            [    ] FRAME: [LP] delta=4, fast function #20
0x41ef0080            [    ] VALUE: nil
0x41ef0078            [    ] VALUE: nil
0x41ef0070            [    ] VALUE: true
0x41ef0068            [    ] FRAME: [V] delta=4, Lua function @ 0x40f81c50, 1 upvalues, "@builtin/box/console.lua":52
0x41ef0060            [    ] VALUE: table @ 0x4175e2f8 (asize: 0, hmask: 0x1)
0x41ef0058            [    ] VALUE: nil
0x41ef0050            [    ] VALUE: nil
0x41ef0048            [    ] FRAME: [LP] delta=3, Lua function @ 0x40f81c50, 1 upvalues, "@builtin/box/console.lua":52
0x41ef0040            [    ] VALUE: string "local a = {} a[a] = a local recf recf = function(t) local n = {} n[t] = setmetatable({}, {__serialize = recf}) return n end setmetatable(a, {__serialize = 
recf}) return a" @ 0x4175d8e0
0x41ef0038            [    ] VALUE: table @ 0x4175caa8 (asize: 0, hmask: 0x1)
0x41ef0030            [    ] FRAME: [L] delta=3, Lua function @ 0x41748fb8, 1 upvalues, "@builtin/box/console.lua":700
0x41ef0028            [    ] VALUE: string "/home/burii" @ 0x4175cb08
0x41ef0020            [    ] VALUE: table @ 0x4175caa8 (asize: 0, hmask: 0x1)
0x41ef0018            [    ] FRAME: [CP] delta=1, Lua function @ 0x41749058, 5 upvalues, "@builtin/box/console.lua":745
0x41ef0010            [S   ] FRAME: dummy L
```

Looks like mcode area for trace is not enough in some cases:
```
(gdb) x /i $rip
=> 0x55930cee8027 <lj_alloc_malloc+7>:  mov    QWORD PTR [rsp+0x8],rdi
(gdb) p $rsp
$19 = (void *) 0x7f8094d81fc0
(gdb) maintenance info sections
...
 [48]      0x7f8094d02000->0x7f8094d81000 at 0x00641000: load36 ALLOC LOAD HAS_CONTENTS
 [49]      0x7f8094d81000->0x7f8094d82000 at 0x006c0000: load37 ALLOC LOAD READONLY HAS_CONTENTS
...
```

Indeed, current trace has number 1:
```
(gdb) p G(L)->vmstate 
$43 = 1
```

Core occurs during this trace execution (see corresponding addresses):
```
x /56i ((GCtrace *)((GG_State *)(L))->J->trace[1]->gcptr32)->mcode
...
   0x559336ffffc0:      mov    DWORD PTR [rdx],ebx
   0x559336ffffc2:      call   0x55930cebd337 <lj_tab_newkey>
   0x559336ffffc7:      mov    ebx,eax

```

**Comment by Buristan** [comment]
This bug occurs with disabled JIT too. The primary reason is not enough C stack space. JIT uses the same C stack, that has no space. The core reason is deep recursive call during serialization, see also #3228. Close as invalid.
