### ISSUE TITLE
Crash on memtx_tx_track_point_slow with mvcc_engine enabled

### ISSUE THREAD

**Issue by olegrok** [tarantool/tarantool#6047]
```
Tarantool Enterprise 2.8.1-0-ge2a1ec0c2-r399-macos
Target: Darwin-x86_64-RelWithDebInfo
Build options: cmake . -DCMAKE_INSTALL_PREFIX=/opt/actions-runners/sdk_01/_work/sdk/sdk/build.sdk/tarantool-2.8/static-build/tarantool-prefix -DENABLE_BACKTRACE=TRUE
Compiler: /Library/Developer/CommandLineTools/usr/bin/cc /Library/Developer/CommandLineTools/usr/bin/c++
C_FLAGS: -Wno-unknown-pragmas -fexceptions -funwind-tables -fno-omit-frame-pointer -fno-stack-protector -fno-common -msse2 -std=c11 -Wall -Wextra -Wno-strict-aliasing -Wno-char-subscripts -Wno-gnu-alignof-expression
CXX_FLAGS: -Wno-unknown-pragmas -fexceptions -funwind-tables -fno-omit-frame-pointer -fno-stack-protector -fno-common -msse2 -std=c++11 -Wall -Wextra -Wno-strict-aliasing -Wno-char-subscripts -Wno-invalid-offsetof -Wno-gnu-alignof-expression
```

Steps to reproduce:
 - Enable `memtx_use_mvcc_engine` for TDG
 - Run `./init.lua --bootstrap true`

```
Process 98024 launched: '/Users/o.babin/Projects/tarantool-enterprise/tarantool' (x86_64)
2021-04-26 08:35:41.583 [98024] main/103/init.lua I> This server has more than one non-local IP address:
2021-04-26 08:35:41.583 [98024] main/103/init.lua I>   en0: 192.168.100.51
2021-04-26 08:35:41.583 [98024] main/103/init.lua I>   lo0: 127.0.0.1
2021-04-26 08:35:41.583 [98024] main/103/init.lua I> Auto-detection of IP address disabled. Use --advertise-uri argument or ADVERTISE_URI environment variable
2021-04-26 08:35:41.583 [98024] main/103/init.lua I> Using advertise_uri "localhost:3301"
2021-04-26 08:35:41.583 [98024] main/103/init.lua I> Membership encryption enabled
2021-04-26 08:35:41.586 [98024] main/103/init.lua I> Probe uri was successful
2021-04-26 08:35:41.587 [98024] main/103/init.lua I> Membership BROADCAST sent to 127.0.0.1:3302
2021-04-26 08:35:41.587 [98024] main/103/init.lua I> Membership BROADCAST sent to 192.168.100.255:3302
2021-04-26 08:35:41.587 [98024] main/103/init.lua I> Membership BROADCAST sent to 127.0.0.1:3301
2021-04-26 08:35:41.587 [98024] main/103/init.lua I> Membership BROADCAST sent to 192.168.100.255:3301
2021-04-26 08:35:41.587 [98024] main/103/init.lua I> Membership BROADCAST sent to 127.0.0.1:3300
2021-04-26 08:35:41.588 [98024] main/103/init.lua I> Membership BROADCAST sent to 192.168.100.255:3300
2021-04-26 08:35:41.588 [98024] main/111/http/0.0.0.0:8080 I> started
2021-04-26 08:35:41.590 [98024] main/103/init.lua I> Listening HTTP on 0.0.0.0:8080
2021-04-26 08:35:42.132 [98024] main/112/remote_control/0.0.0.0:3301 I> started
2021-04-26 08:35:42.132 [98024] main/103/init.lua I> Remote control bound to 0.0.0.0:3301
2021-04-26 08:35:42.132 [98024] main/103/init.lua I> Instance state changed:  -> ConfigFound
2021-04-26 08:35:42.134 [98024] main/103/init.lua I> Instance state changed: ConfigFound -> ConfigLoaded
2021-04-26 08:35:42.134 [98024] main/113/lua I> Instance state changed: ConfigLoaded -> RecoveringSnapshot
2021-04-26 08:35:42.134 [98024] main/113/lua confapplier.lua:435 W> Calling box.cfg()...
2021-04-26 08:35:42.136 [98024] main/113/lua C> Tarantool Enterprise 2.8.1-0-ge2a1ec0c2-r399-macos
2021-04-26 08:35:42.136 [98024] main/113/lua C> log level 5
2021-04-26 08:35:42.136 [98024] main/113/lua I> wal/engine cleanup is paused
2021-04-26 08:35:42.136 [98024] main/113/lua I> mapping 268435456 bytes for memtx tuple arena...
2021-04-26 08:35:42.136 [98024] main/113/lua I> Actual slab_alloc_factor calculated on the basis of desired slab_alloc_factor = 1.044274
2021-04-26 08:35:42.136 [98024] main/113/lua I> mapping 134217728 bytes for vinyl tuple arena...
2021-04-26 08:35:42.137 [98024] main/103/init.lua I> Cartridge 2.5.1-7-ge02a46f8
2021-04-26 08:35:42.137 [98024] main/103/init.lua I> server alias nil
2021-04-26 08:35:42.137 [98024] main/103/init.lua I> advertise uri localhost:3301
2021-04-26 08:35:42.137 [98024] main/103/init.lua I> working directory /Users/o.babin/Projects/tdg/dev/output/srv
tarantool> 2021-04-26 08:35:42.219 [98024] main/113/lua I> instance uuid b0b46b1b-8ce7-49dd-956e-0defda1bd621
2021-04-26 08:35:42.220 [98024] main/113/lua I> instance vclock {}
2021-04-26 08:35:42.220 [98024] main/114/lua I> Cartridge 2.5.1-7-ge02a46f8
2021-04-26 08:35:42.220 [98024] main/114/lua I> server alias nil
2021-04-26 08:35:42.220 [98024] main/114/lua I> advertise uri localhost:3301
2021-04-26 08:35:42.220 [98024] main/114/lua I> working directory /Users/o.babin/Projects/tdg/dev/output/srv
2021-04-26 08:35:42.220 [98024] main/113/lua I> recovery start
2021-04-26 08:35:42.220 [98024] main/113/lua I> recovering from `/Users/o.babin/Projects/tdg/dev/output/srv/00000000000000000000.snap'
2021-04-26 08:35:42.221 [98024] main/113/lua I> cluster uuid a069f9da-c34c-4a09-945f-13bdb97a0c90
2021-04-26 08:35:42.226 [98024] main/113/lua I> assigned id 1 to replica b0b46b1b-8ce7-49dd-956e-0defda1bd621
2021-04-26 08:35:42.227 [98024] main/113/lua I> ready to accept requests
2021-04-26 08:35:42.227 [98024] main/113/lua C> leaving orphan mode
2021-04-26 08:35:42.227 [98024] main/115/gc I> wal/engine cleanup is resumed
2021-04-26 08:35:42.227 [98024] main/113/lua I> set 'log_level' configuration option to 5
2021-04-26 08:35:42.227 [98024] main/116/checkpoint_daemon I> scheduled next checkpoint for Mon Apr 26 09:37:14 2021
2021-04-26 08:35:42.228 [98024] main/113/lua I> set 'vinyl_max_tuple_size' configuration option to 5242880
2021-04-26 08:35:42.228 [98024] main/113/lua I> set 'memtx_max_tuple_size' configuration option to 5242880
2021-04-26 08:35:42.229 [98024] main/113/lua I> set 'read_only' configuration option to true
2021-04-26 08:35:42.229 [98024] main/113/lua I> set 'log_format' configuration option to "plain"
2021-04-26 08:35:42.229 [98024] main/113/lua I> set 'readahead' configuration option to 10485760
2021-04-26 08:35:42.230 [98024] main/113/lua I> Making sure user "admin" exists...
2021-04-26 08:35:42.230 [98024] main/113/lua I> Setting password for user "admin" ...
2021-04-26 08:35:42.230 [98024] main/113/lua I> set 'read_only' configuration option to false
2021-04-26 08:35:42.231 [98024] main/113/lua I> Run box.schema.upgrade()...
Process 98024 stopped
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x10)
    frame #0: 0x0000000100037e90 tarantool`memtx_tx_track_point_slow + 48
tarantool`memtx_tx_track_point_slow:
->  0x100037e90 <+48>: movq   0x10(%rbx), %rax
    0x100037e94 <+52>: movq   0x80(%rax), %rax
    0x100037e9b <+59>: movl   0x70(%rax), %r10d
    0x100037e9f <+63>: testl  %r10d, %r10d
Target 0: (tarantool) stopped.
(lldb) bt
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x10)
  * frame #0: 0x0000000100037e90 tarantool`memtx_tx_track_point_slow + 48
    frame #1: 0x000000010001562a tarantool`int memtx_tree_index_get<true>(index*, char const*, unsigned int, tuple**) + 522
    frame #2: 0x000000010004418e tarantool`sysview_index_get + 158
    frame #3: 0x000000010000f11b tarantool`box_index_get + 427
    frame #4: 0x00000001001a9fcc tarantool`lj_vm_ffi_call + 132
    frame #5: 0x000000010020be6a tarantool`lj_ccall_func + 2138
    frame #6: 0x00000001001cbbb3 tarantool`lj_cf_ffi_meta___call + 99
    frame #7: 0x00000001001a78d3 tarantool`lj_BC_FUNCC + 68
    frame #8: 0x00000001001af438 tarantool`lua_pcall + 168
    frame #9: 0x0000000100162e33 tarantool`luaT_call + 19
    frame #10: 0x000000010015e6b7 tarantool`lua_fiber_run_f + 87
    frame #11: 0x00000001000063bc tarantool`fiber_cxx_invoke(int (*)(__va_list_tag*), __va_list_tag*) + 12
    frame #12: 0x000000010017ba53 tarantool`fiber_loop + 67
    frame #13: 0x00000001009b60fb tarantool`coro_init + 75
```

**Comment by olegrok** [comment]
I've found a source of issue:
```
tarantool
Tarantool Enterprise 2.8.1-0-ge2a1ec0c2-r407-macos
type 'help' for interactive help
tarantool> space_name = 'task_list'
---
...

tarantool> FIELDS = {
         >     { name = 'id',          type = 'string' },
         >     { name = 'finished',    type = 'number' },
         >     { name = 'status',      type = 'number' },
         >     { name = 'result',      type = 'string' },
         >     { name = 'bucket_id',   type = 'number' },
         > }
---
...

tarantool> box.cfg{memtx_use_mvcc_engine = true}
2021-07-10 10:00:54.338 [35028] main/103/interactive C> Tarantool Enterprise 2.8.1-0-ge2a1ec0c2-r407-macos
2021-07-10 10:00:54.338 [35028] main/103/interactive C> log level 5
2021-07-10 10:00:54.338 [35028] main/103/interactive I> wal/engine cleanup is paused
2021-07-10 10:00:54.339 [35028] main/103/interactive I> mapping 268435456 bytes for memtx tuple arena...
2021-07-10 10:00:54.339 [35028] main/103/interactive I> Actual slab_alloc_factor calculated on the basis of desired slab_alloc_factor = 1.044274
2021-07-10 10:00:54.339 [35028] main/103/interactive I> mapping 134217728 bytes for vinyl tuple arena...
2021-07-10 10:00:54.340 [35028] main/103/interactive I> instance uuid ca917380-6281-40b4-8346-205b9ecfe474
2021-07-10 10:00:54.340 [35028] main/103/interactive I> instance vclock {1: 10}
2021-07-10 10:00:54.341 [35028] main/103/interactive I> recovery start
2021-07-10 10:00:54.341 [35028] main/103/interactive I> recovering from `./00000000000000000005.snap'
2021-07-10 10:00:54.341 [35028] main/103/interactive I> cluster uuid 759bc15b-55f2-45a9-8f11-5cefe0fda264
2021-07-10 10:00:54.349 [35028] main/103/interactive I> assigned id 1 to replica ca917380-6281-40b4-8346-205b9ecfe474
2021-07-10 10:00:54.349 [35028] main/103/interactive I> recover from `./00000000000000000005.xlog'
2021-07-10 10:00:54.350 [35028] main/103/interactive I> done `./00000000000000000005.xlog'
2021-07-10 10:00:54.350 [35028] main/103/interactive I> recover from `./00000000000000000010.xlog'
2021-07-10 10:00:54.350 [35028] main/103/interactive I> done `./00000000000000000010.xlog'
2021-07-10 10:00:54.351 [35028] main/103/interactive I> ready to accept requests
2021-07-10 10:00:54.351 [35028] main/103/interactive C> leaving orphan mode
2021-07-10 10:00:54.351 [35028] main/104/gc I> wal/engine cleanup is resumed
2021-07-10 10:00:54.351 [35028] main/103/interactive I> set 'log_level' configuration option to 5
2021-07-10 10:00:54.351 [35028] main/105/checkpoint_daemon I> scheduled next checkpoint for Sat Jul 10 11:20:14 2021
2021-07-10 10:00:54.351 [35028] main/103/interactive I> set 'log_format' configuration option to "plain"
---
...

tarantool> do
         > box.begin()
         >     local space = box.schema.space.create(space_name, { if_not_exists = true })
         > 
         >     space:format(FIELDS, { if_not_exists = true })
         > 
         >     space:create_index('id',
         >         { parts = {{field = 'id', type = 'string' }}, type = 'HASH', unique = true, if_not_exists = true })
         >     space:create_index('bucket_id',
         >         { parts = {{field = 'bucket_id', type = 'number' }}, type = 'TREE', unique = false, if_not_exists = true})
         > 
         >     box.schema.func.create('storage.set_result_impl', { if_not_exists = true })
         >     box.schema.func.create('storage.delete_impl', { if_not_exists = true })
         >     box.schema.func.create('storage.get_impl', { if_not_exists = true })
         >     box.commit()
         > end
Segmentation fault
  code: SEGV_MAPERR
  addr: 0x10
  context: 0x75ff988
  siginfo: 0x75ff920
Current time: 1625900457
Please file a bug at http://github.com/tarantool/tarantool/issues
Attempting backtrace... Note: since the server has already crashed, 
this may fail as well
#0  0x1074bafd2 in crash_signal_cb+92
#1  0x7fff2055ed7d in _sigtramp+1d
#2  0x10737ce91 in memtx_tx_track_point_slow+31
#3  0x10735a62a in _ZL20memtx_tree_index_getILb1EEiP5indexPKcjPP5tuple+20a
#4  0x10738918e in sysview_index_get+9e
#5  0x10735411b in box_index_get+1ab
#6  0x1074eefcc in lj_vm_ffi_call+84
#7  0x107550e6a in lj_ccall_func+85a
#8  0x107510bb3 in lj_cf_ffi_meta___call+63
#9  0x1074ec8d3 in lj_BC_FUNCC+44
#10 0x1074f4438 in lua_pcall+a8
#11 0x1074a7e33 in luaT_call+13
#12 0x1074a1dc9 in run_script_f+399
#13 0x10734b3bc in _ZL16fiber_cxx_invokePFiP13__va_list_tagES0_+c
#14 0x1074c0a53 in fiber_loop+43
#15 0x107cfb0fb in coro_init+4b
```

And it seems to be fixed on Tarantool 2.9.0-139-gb68ae47b7. Let's close then.
