### ISSUE TITLE
MVCC crash

### ISSUE THREAD

**Issue by unera** [tarantool/tarantool#6131]
```trace

(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007f2e06f94537 in __GI_abort () at abort.c:79
#2  0x00000000005c236c in crash_signal_cb (signo=11, siginfo=<optimized out>, context=<optimized out>) at ./src/lib/core/crash.c:545
#3  <signal handler called>
#4  0x000000000045e8b8 in memtx_tx_story_find_visible_tuple (story=0x7f2dd133b890, stmt=stmt@entry=0x7f2dcf1ab220, index=index@entry=0, visible_replaced=visible_replaced@entry=0x7f2e04dffb70, 
    collected_conflicts=collected_conflicts@entry=0x7f2e04dffb68, region=region@entry=0x7f2dcf1ab040) at ./src/box/memtx_tx.c:769
#5  0x0000000000461ee7 in check_dup_dirty (region=0x7f2dcf1ab040, collected_conflicts=0x7f2e04dffb68, mode=DUP_REPLACE, old_tuple=<synthetic pointer>, replaced=0x7f2e04dffaf0, 
    new_tuple=0x7f2df498e984, stmt=0x7f2dcf1ab220) at ./src/box/memtx_tx.c:943
#6  memtx_tx_history_add_stmt (stmt=0x7f2dcf1ab220, old_tuple=0x7f2df408bee4, new_tuple=new_tuple@entry=0x7f2df498e984, mode=mode@entry=DUP_REPLACE, result=result@entry=0x7f2dcf1ab238)
    at ./src/box/memtx_tx.c:1131
#7  0x0000000000512a42 in memtx_space_replace_all_keys (space=0x254c3d0, old_tuple=<optimized out>, new_tuple=0x7f2df498e984, mode=DUP_REPLACE, result=0x7f2dcf1ab238)
    at ./src/box/memtx_space.c:281
#8  0x0000000000513052 in memtx_space_execute_update (space=0x254c3d0, txn=<optimized out>, request=0x7f2e04dffd60, result=0x7f2e04dffd18) at ./src/box/memtx_space.c:431
#9  0x0000000000467cc3 in space_execute_dml (space=space@entry=0x254c3d0, txn=txn@entry=0x7f2dcf1ab038, request=request@entry=0x7f2e04dffd60, result=result@entry=0x7f2e04dffd18)
    at ./src/box/space.c:563
#10 0x0000000000475f27 in box_process_rw (request=request@entry=0x7f2e04dffd60, space=0x254c3d0, result=result@entry=0x7f2e04dffe28) at ./src/box/box.cc:221
#11 0x00000000004793c3 in box_process1 (request=request@entry=0x7f2e04dffd60, result=result@entry=0x7f2e04dffe28) at ./src/box/box.cc:2047
#12 0x0000000000479fc3 in box_update (space_id=space_id@entry=512, index_id=index_id@entry=0, key=key@entry=0x7f2e04c3a038 "\221\252petya_0002\221\223\241=\247balance\366\246string", 
    key_end=<optimized out>, ops=<optimized out>, ops_end=<optimized out>, index_base=1, result=0x7f2e04dffe28) at ./src/box/box.cc:2187
#13 0x00000000004f6cbe in lbox_index_update (L=0x4167e378) at ./src/box/lua/index.c:93
#14 0x000000000062e6ab in lj_BC_FUNCC () at buildvm_x86.dasc:811
#15 0x00000000005f2a44 in lua_pcall (L=L@entry=0x4167e378, nargs=<optimized out>, nresults=<optimized out>, errfunc=errfunc@entry=0) at ./third_party/luajit/src/lj_api.c:1158
#16 0x00000000005ac9e4 in luaT_call (L=0x4167e378, nargs=<optimized out>, nreturns=<optimized out>) at ./src/lua/utils.c:1022
#17 0x00000000005a5939 in lua_main (L=L@entry=0x4167e378, argc=argc@entry=1, argv=argv@entry=0x2505f48) at ./src/lua/init.c:561
#18 0x00000000005a5dd8 in run_script_f (ap=<error reading variable: value has been optimized out>) at ./src/lua/init.c:650
#19 0x0000000000458acd in fiber_cxx_invoke(fiber_func, typedef __va_list_tag __va_list_tag *) (f=<optimized out>, ap=<optimized out>) at ./src/lib/core/fiber.h:902
#20 0x00000000005c8030 in fiber_loop (data=<optimized out>) at ./src/lib/core/fiber.c:916
#21 0x00000000007c0750 in coro_init () at ./third_party/coro/coro.c:110

```

* OS: Linux
* OS Version: bullseye/sid
* Architecture: amd64
Tarantool 2.9.0-61-g2b25ca6c7

Run two tarantool instances iteractively.

1. Main console: box.cfg{listen=3301}
2. Main console: create user, grant
3. Main console: create space
4. Main console: create a record in the space
5. Main console: box.begin()
6. Main console: `box.space.NAME:get 'record_id'`
7. Other console: `box.space.NAME:update('record_id', {{'=', 'value', 10}})`
8. Main console: `box.space.NAME:update('record_id', {{'=', 'value', 10}})`

Crash log:

```log
tarantool> box.space.accounts:update('petya_0002', {{'=', 'balance', -10}})
Segmentation fault
  code: SEGV_MAPERR
  addr: 0x8
  context: 0x7f2e04dfed80
  siginfo: 0x7f2e04dfeeb0
  rax      0x0                0
  rbx      0x7f2dcf1ab040     139834724888640
  rcx      0x7f2dcf1ab010     139834724888592
  rdx      0x7f2dcf1ab038     139834724888632
  rsi      0x7f2dcf1ab038     139834724888632
  rdi      0x7f2dd133b890     139834760083600
  rsp      0x7f2e04dffa60     139835627010656
  rbp      0x7f2e04dffad0     139835627010768
  r8       0x7f2e04dffa9f     139835627010719
  r9       0x0                0
  r10      0x89484            562308
  r11      0x7f2e04dffb70     139835627010928
  r12      0x7f2e04dffb70     139835627010928
  r13      0x7f2e04dffb68     139835627010920
  r14      0x7f2dcf1ab220     139834724889120
  r15      0x7f2dd133b890     139834760083600
  rip      0x45e8b8           4581560
  eflags   0x10202            66050
  cs       0x33               51
  gs       0x0                0
  fs       0x0                0
  cr2      0x8                8
  err      0x4                4
  oldmask  0x0                0
  trapno   0xe                14
Current time: 1623061840
Please file a bug at http://github.com/tarantool/tarantool/issues
Attempting backtrace... Note: since the server has already crashed, 
this may fail as well
#0  0x5c1e74 in crash_signal_cb+94
#1  0x7f2e074ad140 in funlockfile+50
#2  0x45e8b8 in memtx_tx_story_find_visible_tuple+98
#3  0x461ee7 in memtx_tx_history_add_stmt+7c7
#4  0x512a42 in memtx_space_replace_all_keys+2f2
#5  0x513052 in memtx_space_execute_update+172
#6  0x467cc3 in space_execute_dml+e3
#7  0x475f27 in box_process_rw+a7
#8  0x479fc3 in box_update+53
#9  0x4f6cbe in lbox_index_update+11e
#10 0x62e6ab in lj_BC_FUNCC+34
#11 0x5f2a44 in lua_pcall+74
#12 0x5ac9e4 in luaT_call+14
#13 0x5a5939 in lua_main+59
#14 0x5a5dd8 in run_script_f+478
#15 0x458acd in _ZL16fiber_cxx_invokePFiP13__va_list_tagES0_+d
#16 0x5c8030 in fiber_loop+30
#17 0x7c0750 in coro_init+40
zsh: abort (core dumped)  tarantool test.lua
```

**Comment by alyapunov** [comment]
We discussed expected behavior in the case of the issue with @unera and decided that that should be:
1. update from main console must complete without an error.
2. commit in main console must fail due to conflict.

BTW that behavior is identical to that of transaction manager in vinyl.
