### ISSUE TITLE
memtx: index creation inside tx in mvcc  mode leads to crash

### ISSUE THREAD

**Issue by Korablev77** [tarantool/tarantool#6137]
```
box.cfg{memtx_use_mvcc_engine = true}
box.schema.create_space('t')
txn_proxy = require('txn_proxy')
tx1 = txn_proxy.new()
tx1:commit()

tx1:begin()

tx1("box.space.t:create_index('i')")

tx1:commit()
```
Bt is similar to the one from #6047 so mb it's a duplicate:
```
#0  0x561309c4008e in crash_collect+c5
#1  0x561309c4209f in crash_signal_cb+51
#2  0x7f29bf61a890 in funlockfile+50
#3  0x561309a4bdbd in memtx_tx_track_point_slow+44
#4  0x561309bf4713 in memtx_tx_track_point+51
#5  0x561309c08890 in _Z20memtx_tree_index_getILb1EEiP5indexPKcjPP5tuple+125
#6  0x561309b72c6d in index_get+33
#7  0x561309b73ccd in sysview_index_get+16f
#8  0x561309a3f388 in index_get+33
#9  0x561309a40cf6 in box_index_get+206
#10 0x561309cf7974 in lj_vm_ffi_call+84
#11 0x561309ce44d4 in lj_ccall_func+352
#12 0x561309cb06f6 in lj_cf_ffi_meta___call+de
#13 0x561309cf56fb in lj_BC_FUNCC+34
#14 0x561309c8734e in lua_pcall+1de
#15 0x561309c25663 in luaT_call+29
#16 0x561309c1e81b in lua_fiber_run_f+74
#17 0x561309a3c5e3 in _ZL16fiber_cxx_invokePFiP13__va_list_tagES0_+1e
#18 0x561309c49f41 in fiber_loop+84
#19 0x561309f1d528 in coro_init+4c

```

**Comment by Korablev77** [comment]
This is fixed in https://github.com/tarantool/tarantool/pull/6194/commits/b5b5b199e506c8cb57be8f14d5b4309e85491812
