### ISSUE TITLE
Run Cartridge test suite with enabled mvcc and synchro before release 

### ISSUE THREAD

**Issue by olegrok** [tarantool/tarantool#6277]
The same as in https://github.com/tarantool/tarantool/issues/6275

It's easy to get at 2.9 (https://github.com/tarantool/cartridge/runs/3204318827?check_suite_focus=true):
```
main-1 | #0  0x10493afd2 in crash_signal_cb+92
main-1 | #1  0x7fff2055ed7d in _sigtramp+1d
main-1 | #2  0x1047fce91 in memtx_tx_track_point_slow+31
main-1 | #3  0x1047da62a in _ZL20memtx_tree_index_getILb1EEiP5indexPKcjPP5tuple+20a
main-1 | #4  0x10480918e in sysview_index_get+9e
main-1 | #5  0x1047d411b in box_index_get+1ab
main-1 | #6  0x10496efcc in lj_vm_ffi_call+84
main-1 | #7  0x1049d0e6a in lj_ccall_func+85a
main-1 | #8  0x104990bb3 in lj_cf_ffi_meta___call+63
main-1 | #9  0x10496c8d3 in lj_BC_FUNCC+44
main-1 | #10 0x1049049ba in execute_lua_call+7a
main-1 | #11 0x10496c8d3 in lj_BC_FUNCC+44
main-1 | #12 0x104974438 in lua_pcall+a8
main-1 | #13 0x104927e33 in luaT_call+13
main-1 | #14 0x104903cd4 in box_process_lua+b4
main-1 | #15 0x104903c11 in box_lua_call+21
main-1 | #16 0x1048a7dc9 in box_process_call+269
main-1 | #17 0x1047ce0ee in _ZL15tx_process_callP4cmsg+12e
main-1 | #18 0x104944f14 in cmsg_deliver+14
main-1 | #19 0x1049461bd in fiber_pool_f+16d
main-1 | #20 0x1047cb3bc in _ZL16fiber_cxx_invokePFiP13__va_list_tagES0_+c
main-1 | #21 0x104940a53 in fiber_loop+43
main-1 | #22 0x10517b0fb in coro_init+4b
```

Probably such but was even fixed https://github.com/tarantool/tarantool/issues/6047 but anyway we need such test to be sure that Tarantool is stable enough.

**Comment by olegrok** [comment]
I want to highlight again that issue is still relevant and helps to find real bugs - https://github.com/tarantool/tarantool/issues/6344 / https://github.com/tarantool/tarantool/pull/6788

**Comment by olegrok** [comment]
Probably it's not relevant anymore since 3.0
