### ISSUE TITLE
Segmentation fault while using prepared statements without closing them

### ISSUE THREAD

**Issue by mhthnz** [tarantool/tarantool#6422]
**Bug description**

While using prepared statements i got segmentation fault if i don't close them. When i add closing prepared statements it works fine.

* OS: Linux
* OS Version: Debian 10
* Architecture: amd64

Tested on `latest`, `2.7`, `2.6`, `2.5`, `2.4` tarantool versions using docker.
Tested on `php7.1`, `php7.3`, `php7.4`, `php8` i guess it reproduces on all php versions

**Steps to reproduce**

1. Set up tarantool using docker
2. Install https://github.com/tarantool-php/client
3. Install https://github.com/rybakit/msgpack.php
4. Put index.php from attachments in directory
5. Edit third line of index.php and run it

[index.php.zip](https://github.com/tarantool/tarantool/files/7121071/index.php.zip)

```
$ composer require tarantool/client
$ composer require rybakit/msgpack
$ php index.php
```

**Actual behavior**

```
2021-09-07 08:41:36.803 [1] main C> entering the event loop
Segmentation fault
  code: 128
0
  context: 0x7f3efc4ff740
  siginfo: 0x7f3efc4ff870
  rax      0x7f3efc82a0c0     139908501119168
  rbx      0x17fffffff        6442450943
  rcx      0xb                11
  rdx      0xb                11
  rsi      0x1f               31
  rdi      0x32656d614ea5c093 3631428939242913939
  rsp      0x7f3efc4ffdf0     139908497800688
  rbp      0x7f3efc4ffe70     139908497800816
  r8       0x0                0
  r9       0x7f3efc81d1a0     139908501066144
  r10      0xffffffff         4294967295
  r11      0x1                1
  r12      0x7f3efc041008     139908492824584
  r13      0x1                1
  r14      0x564298219588     94844020168072
  r15      0x1                1
  rip      0x5642976e825b     94844008432219
  eflags   0x10206            66054
  cs       0x33               51
  gs       0x0                0
  fs       0x0                0
  cr2      0x0                0
  err      0x0                0
  oldmask  0x0                0
  trapno   0xd                13

Current time: 1631004163
Please file a bug at http://github.com/tarantool/tarantool/issues
Attempting backtrace... Note: since the server has already crashed, 

this may fail as well
#0  0x56429772ece9 in crash_signal_cb+99
#1  0x7f3eff3089b7 in sigwaitinfo+8
#2  0x56429765a75e in _ZL14tx_process_sqlP4cmsg+11e
#3  0x56429773a2f4 in cmsg_deliver+14
#4  0x56429773ae3f in fiber_pool_f+7f
#5  0x56429759654c in _ZL16fiber_cxx_invokePFiP13__va_list_tagES0_+c
#6  0x564297734ac0 in fiber_loop+30
#7  0x56429796768f in coro_init+3f
```

**Expected behavior**

Working without crash

**Comment by ImeevMA** [comment]
Simplified reproducer:
```
id = box.prepare([[DROP TABLE IF EXISTS t;]]).stmt_id
box.execute(id)
id = box.prepare([[CREATE TABLE t (i int PRIMARY KEY AUTOINCREMENT, b int);]]).stmt_id
box.execute(id)
id = box.prepare([[INSERT INTO t (b) VALUES (:a);]]).stmt_id
box.execute(id, {{[':a'] = 1}})
id = box.prepare([[SELECT * FROM t;]]).stmt_id
box.execute(id)
id = box.prepare([[INSERT INTO t (b) VALUES (:a);]]).stmt_id
box.execute(id, {{[':a'] = 1}})
id = box.prepare([[DROP TABLE IF EXISTS t;]]).stmt_id
box.execute(id)
id = box.prepare([[CREATE TABLE t (i int PRIMARY KEY AUTOINCREMENT, b int);]]).stmt_id
box.execute(id)
id = box.prepare([[INSERT INTO t (b) VALUES (:a);]]).stmt_id
box.execute(id, {{[':a'] = 1}})
id = box.prepare([[SELECT * FROM t;]]).stmt_id
box.execute(id)
id = box.prepare([[INSERT INTO t (b) VALUES (:a);]]).stmt_id
box.execute(id, {{[':a'] = 1}})
```

It still can be reproduced on current master.
