### ISSUE TITLE
vinyl crashes on running expirationd regression tests

### ISSUE THREAD

**Issue by ligurio** [tarantool/tarantool#6609]
**Bug description**

* OS: Linux
* OS Version: Ubuntu 20.04
* Architecture: amd64

```
Tarantool 2.10.0-beta1-0-g7da4b1438
Target: Linux-x86_64-RelWithDebInfo
Build options: cmake . -DCMAKE_INSTALL_PREFIX=/usr -DENABLE_BACKTRACE=ON
Compiler: /usr/bin/cc /usr/lib/ccache/g++
C_FLAGS:-g -O2 -fdebug-prefix-map=/build/tarantool-2.10.0~beta1=. -specs=/usr/share/dpkg/no-pie-compile.specs -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fexceptions -funwind-tables -fno-omit-frame-pointer -fno-stack-protector -fno-common -fopenmp -msse2 -std=c11 -Wall -Wextra -Wno-strict-aliasing -Wno-char-subscripts -Wno-format-truncation -Wno-gnu-alignof-expression -fno-gnu89-inline -Wno-cast-function-type
CXX_FLAGS:-g -O2 -fdebug-prefix-map=/build/tarantool-2.10.0~beta1=. -specs=/usr/share/dpkg/no-pie-compile.specs -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fexceptions -funwind-tables -fno-omit-frame-pointer -fno-stack-protector -fno-common -fopenmp -msse2 -std=c++11 -Wall -Wextra -Wno-strict-aliasing -Wno-char-subscripts -Wno-format-truncation -Wno-invalid-offsetof -Wno-gnu-alignof-expression -Wno-cast-function-type
```

**Steps to reproduce**

1. `git clone https://github.com/tarantool/expirationd`
1. `git checkout ligurio/gh-80-parameterization`

**Actual behavior**

```
2021-11-15 19:49:02.609 [103901] main/107/vinyl.scheduler I> removed /tmp/AckhNI/651/0/00000000000000004430.run                                     [29/24643]
2021-11-15 19:49:02.609 [103901] main/107/vinyl.scheduler I> 651/0: completed compacting range (-inf..inf)
2021-11-15 19:49:02.672 [103901] main/363/worker of "clean_all" I> dumping 49184 bytes, expected rate 10.0 MB/s, ETA 0.0 s, write rate (avg/max) 0.0/0.0 MB/s
2021-11-15 19:49:02.673 [103901] main/107/vinyl.scheduler I> 651/0: dump started
2021-11-15 19:49:02.673 [103901] vinyl.dump.0/1520/task I> writing `/tmp/AckhNI/651/0/00000000000000004437.run'
2021-11-15 19:49:02.674 [103901] vinyl.dump.0/1520/task I> writing `/tmp/AckhNI/651/0/00000000000000004437.index'
2021-11-15 19:49:02.677 [103901] main/107/vinyl.scheduler I> 651/0: dump completed
2021-11-15 19:49:02.677 [103901] main/107/vinyl.scheduler I> dumped 49184 bytes in 0.0 s, rate 8.9 MB/s
2021-11-15 19:49:02.678 [103901] main/107/vinyl.scheduler I> 651/0: started compacting range (-inf..inf), runs 2/2
2021-11-15 19:49:02.678 [103901] vinyl.compaction.1/348/task I> writing `/tmp/AckhNI/651/0/00000000000000004439.run'
2021-11-15 19:49:02.685 [103901] main/103/luatest memtx_tx.c:298 W> Transaction committing DDL (id=3532) has aborted another TX (id=3530)
    iterator_type.engine:"vinyl".index_type:"TREE".test_tree_index_all ... (0.515s) Ok
    iterator_type.engine:"vinyl".index_type:"TREE".test_hash_index_all ... 
Segmentation fault              
  code: SEGV_MAPERR     
  addr: (nil)                                                                  
  context: 0x7f77d087f640                                                      
  siginfo: 0x7f77d087f770
  rax      0x0                0   
  rbx      0xc70              3184  
  rcx      0x10               16                                               
  rdx      0x7f77d1294231     140152586977841
  rsi      0x7f77d129422d     140152586977837
  rdi      0xb63620           11941408                                         
  rsp      0x7f77d087fd00     140152576408832
  rbp      0x7f77d087fda0     140152576408992
  r8       0x0                0                                                
  r9       0xc6fad0           13040336
  r10      0x7f77f887fdd0     140153247497680
  r11      0xc6fbd0           13040592
  r12      0x28b              651                                              
  r13      0x7f77d129422d     140152586977837
  r14      0x7f77d1294231     140152586977841
  r15      0x7f77fb02a040     140153289089088
  rip      0x474050           4669520
  eflags   0x10246            66118
  cs       0x33               51
  gs       0x0                0
  fs       0x0                0
  cr2      0x0                0
  err      0x4                4
  oldmask  0x0                0
  trapno   0xe                14
Please file a bug at http://github.com/tarantool/tarantool/issues
Attempting backtrace... Note: since the server has already crashed, 
this may fail as well
#0  0x5caea6 in crash_signal_cb+a6
#1  0x7f77fdb713c0 in funlockfile+60
#2  0x474050 in vy_deferred_delete_on_replace+370
#3  0x5e77d2 in trigger_run+32
#4  0x500245 in txn_commit_stmt+1e5
#5  0x4cf3f4 in vy_deferred_delete_batch_process_f+214
#6  0x5d6af8 in cmsg_deliver+18
#7  0x5d762f in fiber_pool_f+8f
#8  0x421101 in _ZL16fiber_cxx_invokePFiP13__va_list_tagES0_+11
#9  0x5d1060 in fiber_loop+30
#10 0x82e254 in coro_init+44
Aborted (core dumped)
```

**Expected behavior**

Passed tests.

**Comment by ligurio** [comment]
@locker said it is a duplicate of #6448
