### ISSUE TITLE
Yield from a GC hook from a fiber serving an iproto request leads to assertion fail

### ISSUE THREAD

**Issue by Totktonada** [tarantool/tarantool#6647]
1.10.11-46-g5c8c025da

```lua
-- box.cfg, grants, requires, create net.box connection.
tarantool> box.cfg({listen = 3301})
tarantool> box.schema.user.grant('guest', 'super')
tarantool> ffi = require('ffi')
tarantool> fiber = require('fiber')
tarantool> net_box = require('net.box')
tarantool> c = net_box.connect(3301)

-- Reproducer itself.
tarantool> f = function() local t = {__gh_hook = ffi.gc(ffi.new('void *'), fiber.yield)} t = nil collectgarbage() end
tarantool> c:call('f')
tarantool: /home/alex/p/tarantool-meta/1.10/src/lua/utils.c:730: cord_on_yield: Assertion `L != NULL' failed.
Aborted
```

AFAIR, we can see an empty lua state in the fibr local storage on master too in some cases. It should be revisited carefully as for master as well as for 1.10.

Info for inspiration:

https://github.com/tarantool/tarantool/commit/9be50ae745a176da128f2244e1777b9b1e9afb6c
https://github.com/tarantool/tarantool/commit/b4e186fa57461820eb8b82306c505833048c40a2
https://github.com/tarantool/tarantool/commit/ec9b544a123f3e0614ab94b83a7ac4b395326f34
https://github.com/tarantool/tuple-merger/issues/18

**Comment by kyukhin** [comment]
Reproduced on master (2.11.0-entrypoint-113-gede831).
Stack trace
```
#1  0x5e5f93 in tarantool_panic_handler+67
#2  0x5f1d4c in cord_on_yield+172
#3  0x618c70 in fiber_yield+192
#4  0x619c20 in fiber_sleep+288
#5  0x5e777c in lbox_fiber_yield.llvm.926667233294543737+12
#6  0x8613b3 in lj_BC_FUNCC+70
#7  0x6609f0 in gc_finalize.llvm.2025679844444349902+240
#8  0x6611ca in gc_onestep.llvm.2025679844444349902+970
#9  0x65a678 in lua_gc+504
#10 0x671534 in lj_cf_collectgarbage+148
#11 0x8613b3 in lj_BC_FUNCC+70
#12 0x5a3620 in execute_lua_call.llvm.15167021168380562020+512
#13 0x8613b3 in lj_BC_FUNCC+70
#14 0x5f0695 in luaT_call+69
#15 0x5a18c4 in box_process_lua.llvm.15167021168380562020+164
#16 0x528d0e in box_process_call+478
#17 0x41abd8 in tx_process_call(cmsg*)+696
#18 0x620662 in fiber_pool_f+322
#19 0x4166b9 in fiber_cxx_invoke(int (*)(__va_list_tag*), __va_list_tag*)+9
#20 0x61aa20 in fiber_loop+64
#21 0x85f9bd in coro_init.llvm.9707565685768942957+77
```
