### ISSUE TITLE
datetime crash on invalid msgpack

### ISSUE THREAD

**Issue by Gerold103** [tarantool/tarantool#6722]
```Lua
msgpack = require('msgpack')
mp = '\x91\xc7\x00\x04'
obj = msgpack.object_from_raw(mp)

box.cfg{}
s = box.schema.create_space('test', {format = {{name='pk', type='datetime'}}})
_ = s:create_index('pk')
s:replace(obj)
```
```
Segmentation fault
  code: SEGV_MAPERR
  addr: 0x0
  context: 0x10a9ff548
  siginfo: 0x10a9ff4e0
Current time: 1640037778
Please file a bug at http://github.com/tarantool/tarantool/issues
Attempting backtrace... Note: since the server has already crashed, 
this may fail as well
#0  0x107b63b52 in crash_collect+b2
#1  0x107b63a0c in crash_signal_cb+3c
#2  0x7fff6e6615fd in _sigtramp+1d
#3  0x107da8e81 in _ZL13hint_datetimeP8datetime+11
#4  0x107da9b2a in _ZL19field_hint_datetimePKc+ba
#5  0x107da9c69 in _ZL10field_hintIL10field_type11ELb0EEyPKcP4coll+19
#6  0x107da9c42 in _ZL10tuple_hintIL10field_type11ELb0EEyP5tupleP7key_def+82
#7  0x10790eff2 in _ZL10tuple_hintP5tupleP7key_def+22
#8  0x10790e9d0 in _ZL24memtx_tree_index_replaceILb1EEiP5indexP5tupleS3_16dup_replace_modePS3_S5_+60
#9  0x10793aa52 in index_replace+92
#10 0x10793ac2f in memtx_space_replace_all_keys+1cf
#11 0x10793b671 in memtx_space_execute_replace+e1
#12 0x1079c5efa in space_execute_dml+14a
#13 0x107a0957f in box_process_rw+10f
#14 0x107a11e18 in box_process1+188
#15 0x107a12e64 in box_replace+84
#16 0x107b16cc6 in lbox_replace+96
#17 0x107bbd2cb in lj_BC_FUNCC+44
#18 0x107bcb5a1 in lua_pcall+441
#19 0x107b45c13 in luaT_call+23
#20 0x107b3dc5c in lua_main+cc
#21 0x107b3d891 in run_script_f+811
#22 0x1078e2fca in _ZLAbort trap: 6
```

**Comment by Gerold103** [comment]
Sorry, false alarm. I didn't specify field type.

**Comment by tsafin** [comment]
This ticket is replaced by #6723
