### ISSUE TITLE
Iteration by a functional index is not stable

### ISSUE THREAD

**Issue by Totktonada** [tarantool/tarantool#6786]
Known affected tarantool versions:

2.4.1-57-g339ad6289
2.10.0-beta2-5-gdc19be406
2.10.0-beta2-40-g5cd399b77

The problem can be reproduced in the debug build:

> cmake . -DCMAKE_BUILD_TYPE=Debug -DENABLE_BACKTRACE=ON -DENABLE_DIST=ON -DENABLE_FEEDBACK_DAEMON=OFF -DENABLE_BUNDLED_LIBCURL=OFF && make -j

Reproducer:

```lua
box.cfg()

local findex_code = [[function(tuple)
    return {tuple[2]}
end]]
box.schema.func.create('findex_func', {
    body = findex_code,
    is_deterministic = true,
    is_sandboxed = true,
})

local space = box.schema.create_space('s', {
    engine = 'memtx',
    format = {
        {
            name = 'id',
            type = 'number',
        },
        {
            name = 'data',
            type = 'string',
        },
    }
})

space:create_index('primary', {
    type = 'TREE',
    parts = {
        {
            field = 1,
        }
    }
})
space:create_index('functional_index', {
    type = 'TREE',
    parts = {
        {
            field = 1,
            type = 'string',
        },
    },
    func = 'findex_func',
})

space:insert({1, '12'})
space:insert({2, '21'})

for _, tuple in space.index.functional_index:pairs() do
    space:delete({tuple[1]})
end
```

(The reproducer is extracted from expirationd 1.1.1-44-g838c2d1, from the `test_memtx_tree_functional_index` test case.)

Result (those particular line numbers are from 2.10.0-beta2-40-g5cd399b77):

> tarantool: /home/alex/p/tarantool-meta/r/t-6/src/box/tuple_compare.cc:1394: int func_index_compare(tuple*, hint_t, tuple*, hint_t, key_def*) [with bool is_nullable = false; hint_t = long unsigned int]: Assertion `mp_typeof(*key_b) == MP_ARRAY' failed.
> Aborted (core dumped)

C and Lua backtraces from the coredump:

```c
(gdb) bt
#0  0x00007f3c941581cc in __pthread_kill_implementation () from /lib64/libc.so.6
#1  0x00007f3c9410c982 in raise () from /lib64/libc.so.6
#2  0x00007f3c940f7449 in abort () from /lib64/libc.so.6
#3  0x00007f3c940f7375 in __assert_fail_base.cold () from /lib64/libc.so.6
#4  0x00007f3c94105af2 in __assert_fail () from /lib64/libc.so.6
#5  0x000055b88deb24c8 in func_index_compare<false> (tuple_a=0x7f3c83007824, tuple_a_hint=139897872611420, tuple_b=0x7f3c830077b4, tuple_b_hint=139897872611308, cmp_def=0x55b88e6dd650)
    at /home/alex/p/tarantool-meta/r/t-6/src/box/tuple_compare.cc:1394
#6  0x000055b88db1a7ef in tuple_compare (tuple_a=0x7f3c83007824, tuple_a_hint=139897872611420, tuple_b=0x7f3c830077b4, tuple_b_hint=139897872611308, key_def=0x55b88e6dd650)
    at /home/alex/p/tarantool-meta/r/t-6/src/box/key_def.h:971
#7  0x000055b88db24edd in NS_USE_HINT::bps_tree_memtx_tree_find_after_ins_point_elem (tree=0x55b88e6df158, arr=0x7f3c84128010, size=1, elem=..., exact=0x7f3c935ff814)
    at /home/alex/p/tarantool-meta/r/t-6/src/lib/salad/bps_tree.h:1517
#8  0x000055b88db25741 in NS_USE_HINT::memtx_tree_upper_bound_elem (tree=0x55b88e6df158, key=..., exact=0x7f3c935ff815) at /home/alex/p/tarantool-meta/r/t-6/src/lib/salad/bps_tree.h:1880
#9  0x000055b88db341e6 in tree_iterator_next_base<true> (iterator=0x7f3c9341c078, ret=0x41a6a418) at /home/alex/p/tarantool-meta/r/t-6/src/box/memtx_tree.cc:287
#10 0x000055b88db32f36 in tree_iterator_next<true> (iterator=0x7f3c9341c078, ret=0x41a6a418) at /home/alex/p/tarantool-meta/r/t-6/src/box/memtx_tree.cc:497
#11 0x000055b88db1368e in iterator_next (it=0x7f3c9341c078, ret=0x41a6a418) at /home/alex/p/tarantool-meta/r/t-6/src/box/index.cc:472
#12 0x000055b88db1344c in box_iterator_next (itr=0x7f3c9341c078, result=0x41a6a418) at /home/alex/p/tarantool-meta/r/t-6/src/box/index.cc:400
#13 0x000055b88dd79889 in lj_vm_ffi_call () at buildvm_x86.dasc:2629
#14 0x000055b88de2c0f0 in lj_ccall_func (L=0x41145378, cd=0x41c20500) at /home/alex/p/tarantool-meta/r/t-6/third_party/luajit/src/lj_ccall.c:1150
#15 0x000055b88ddb7560 in lj_cf_ffi_meta___call (L=0x41145378) at /home/alex/p/tarantool-meta/r/t-6/third_party/luajit/src/lib_ffi.c:230
#16 0x000055b88dd7760f in lj_BC_FUNCC () at buildvm_x86.dasc:811
#17 0x000055b88dd8281b in lua_pcall (L=0x41145378, nargs=0, nresults=0, errfunc=0) at /home/alex/p/tarantool-meta/r/t-6/third_party/luajit/src/lj_api.c:1187
#18 0x000055b88dd1135c in luaT_call (L=0x41145378, nargs=0, nreturns=0) at /home/alex/p/tarantool-meta/r/t-6/src/lua/utils.c:464
#19 0x000055b88dd094bc in lua_main (L=0x41145378, argc=1, argv=0x55b88e5bef58) at /home/alex/p/tarantool-meta/r/t-6/src/lua/init.c:797
#20 0x000055b88dd09a31 in run_script_f (ap=0x7f3c934004f0) at /home/alex/p/tarantool-meta/r/t-6/src/lua/init.c:886
#21 0x000055b88db00d5e in fiber_cxx_invoke(fiber_func, typedef __va_list_tag __va_list_tag *) (f=0x55b88dd094d5 <run_script_f>, ap=0x7f3c934004f0)
    at /home/alex/p/tarantool-meta/r/t-6/src/lib/core/fiber.h:922
#22 0x000055b88dd373fe in fiber_loop (data=0x0) at /home/alex/p/tarantool-meta/r/t-6/src/lib/core/fiber.c:918
#23 0x000055b88dffbef3 in coro_init () at /home/alex/p/tarantool-meta/r/t-6/third_party/coro/coro.c:110
(gdb) lj-stack
0x41c1c760:0x41c1c780 [    ] 5 slots: Red zone
0x41c1c758            [   M]
0x41c1c298:0x41c1c750 [    ] 152 slots: Free stack slots
0x41c1c290            [  T ]
0x41c1c288            [    ] VALUE: cdata @ 0x41a6a410
0x41c1c280            [    ] VALUE: cdata @ 0x41c20430
0x41c1c278            [ B  ] VALUE: cdata @ 0x41c20500
0x41c1c270            [    ] FRAME: [L] delta=3, fast function #170
0x41c1c268            [    ] VALUE: cdata @ 0x41c20430
0x41c1c260            [    ] VALUE: string "\220" @ 0x41c203b0
0x41c1c258            [    ] FRAME: [L] delta=6, Lua function @ 0x41a6a530, 5 upvalues, "@builtin/box/schema.lua":1442
0x41c1c250            [    ] VALUE: cdata @ 0x41c20430
0x41c1c248            [    ] VALUE: string "\220" @ 0x41c203b0
0x41c1c240            [    ] VALUE: table @ 0x41c20470 (asize: 0, hmask: 0x3)
0x41c1c238            [    ] VALUE: table @ 0x41c1a4c8 (asize: 0, hmask: 0xf)
0x41c1c230            [    ] VALUE: string "function(tuple)\n    return {tuple[2]}\nend" @ 0x41d9be28
0x41c1c228            [    ] FRAME: [V] delta=1, Lua function @ 0x41bed088, 0 upvalues, "@case.lua":0
0x41c1c220            [    ] FRAME: [CP] delta=1, Lua function @ 0x41bed088, 0 upvalues, "@case.lua":0
0x41c1c218            [S   ] FRAME: dummy L
```

If my diagnostics is correct (and the iteration is truthly not stable) and it is not supposed to be fixed soon, please, at least file an issue against the documentation to highlight this detail for users. It would be also good to leave a note in https://github.com/tarantool/doc/issues/2102.

If it is not correct, please, rename the issue appropriately.

**Comment by locker** [comment]
The problem is that functional index key parts (the ones returned by the user function; called "chunks" in the code) are not associated with a tuple - they are only stored in the index (in hints; a hint is a pointer pointing to a chunk for a functional index). As a result, when a tuple is deleted from an index, all its key parts are freed. An iterator pins a tuple to resume iteration after index modifications, but it doesn't pin key parts so it crashes trying to access freed data.

Possible ways to resolve the issue:
1. Reference each key part and pin the current key part in the iterator along with the tuple. This would increase memory consumption.
2. Copy key parts from the tree to the iterator. This would imply a memory allocation per each iteration, because a key part size isn't fixed.
3. When a key part is deleted from a tree, look up all iterators and update them. This would result in increased CPU consumption.
4. Store functional index key parts in a hidden field in a tuple so that pinning a tuple would imply pinning all its key parts. A hint would contain the key part number (like it does for multi-key indexes). This would require a massive rework.
5. Drop functional indexes.
6. Ignore the issue and update the documentation.

**Comment by locker** [comment]
Discussed with @alyapunov and @kyukhin. Decided to work around this issue by copying the current functional index key part to the iterator on each iteration. This is a quick and dirty fix that will affect performance, but it's better than a crash. In the meantime, we will schedule a rework of functional indexes that would move functional index key parts from the index tree hints to hidden tuple fields (we will need to introduce hidden fields first).

**Comment by olegrok** [comment]
> In the meantime, we will schedule a rework of functional indexes that would move functional index key parts from the index tree hints to hidden tuple fields (we will need to introduce hidden fields first).

Probably it's relevant for multikey indexes as well.
Firstly in the scope of https://github.com/tarantool/tarantool/issues/5270. And probably such decision is related to https://github.com/tarantool/tarantool/issues/5656.

**Comment by CuriousGeorgiy** [comment]
Am I the only one to observe the problems we get with the lack of value-semantics in the C language?

We recently had another issue with memtx TREE indexes (#6788) and the reference-semantics of tree elements breaking iterators after the introduction of MVCC transaction manager story garbage collection.

I see the absence of value-semantics being a general nuisance throughout our code: it introduces more and more code dependencies and makes the code base harder to maintain and change (given we are [humble programmers](https://www.cs.utexas.edu/~EWD/transcriptions/EWD03xx/EWD340.html)). 

There is even a [notion](https://youtu.be/vxv74Mjt9_0?t=968) that raw non-const pointers are as good as global variables in terms of sharing mutable state across code. When it comes to being able to reason about the code one uses, raw pointers make it nearly impossible for one to reason about code locally, leading to subtle bugs (because of the code dependencies not being respected. 

Considering these circumstances, perhaps we should take a step aside, and revise our first principles (reference-semantics and more) and the code using them that we currently have?

**Comment by locker** [comment]
Cherry-picked to 2.8.
