### ISSUE TITLE
Memory leak in SQL

### ISSUE THREAD

**Issue by msiomkin** [tarantool/tarantool#6789]
**Bug description**

~50 Mb leaks when executing an SQL query

* OS: Linux
* OS Version: Centos 8
* Architecture: amd64

```
Tarantool 2.8.2-24-g917823eac
Target: Linux-x86_64-RelWithDebInfo
Build options: cmake . -DCMAKE_INSTALL_PREFIX=/usr/local -DENABLE_BACKTRACE=ON
Compiler: /usr/lib64/ccache/cc /usr/lib64/ccache/c++
C_FLAGS: -fexceptions -funwind-tables -fno-omit-frame-pointer -fno-stack-protector -fno-common -fopenmp -msse2 -std=c11 -Wall -Wextra -Wno-strict-aliasing -Wno-char-subscripts -Wno-format-truncation -Wno-gnu-alignof-expression -fno-gnu89-inline -Wno-cast-function-type
CXX_FLAGS: -fexceptions -funwind-tables -fno-omit-frame-pointer -fno-stack-protector -fno-common -fopenmp -msse2 -std=c++11 -Wall -Wextra -Wno-strict-aliasing -Wno-char-subscripts -Wno-format-truncation -Wno-invalid-offsetof -Wno-gnu-alignof-expression -Wno-cast-function-type
```

**Steps to reproduce**

Download and unpack file: https://t.bk.ru/1RFdQSj/sqlleak.tar.gz

Run tarantool under valgrind in the created directory:

```
valgrind \
        --leak-check=full \
        --show-leak-kinds=all \
        --track-origins=yes \
        --keep-stacktraces=alloc-and-free \
        --verbose \
        --log-file=valgrind.log \
        tarantool
```

Load the DB:
```
box.cfg({ memtx_memory = 3500000000 })
```

Execute the query:
```
box.execute([[select (select "processAttr"."valueStr" from "processAttr" where "processAttr"."processUid" = "process"."uid" and "processAttr"."name" = 'mrf_name') as "#1", count(case when "eventName"."name" = 'CRM - Регистрация обращения' and "process"."eventCount" = 1 and not (select "processAttr"."valueStr" from "processAttr" where "processAttr"."processUid" = "process"."uid" and "processAttr"."name" = 'result') in ('Связано с ГП', 'Массовая проблема') and (select "processAttr"."valueStr" from "processAttr" where "processAttr"."processUid" = "process"."uid" and "processAttr"."name" = 'result') not like 'Блок%' then "cfn.pm_uid_to_str"("event"."processUid") else null end) as "#2", "processUid" as "#3", count(case when "eventName"."name" = 'CRM - Регистрация обращения' and "process"."eventCount" = 1 and (select "processAttr"."valueStr" from "processAttr" where "processAttr"."processUid" = "process"."uid" and "processAttr"."name" = 'result') not like 'Блок%' then "cfn.pm_uid_to_str"("event"."processUid") else null end) as "#4", count(distinct case when "eventName"."name" = 'CRM - Создание групповой проблемы' or "eventName"."name" = 'CRM - Регистрация обращения' and "process"."eventCount" = 1 and (select "processAttr"."valueStr" from "processAttr" where "processAttr"."processUid" = "process"."uid" and "processAttr"."name" = 'result') in ('Связано с ГП', 'Массовая проблема') then "cfn.pm_uid_to_str"("event"."processUid") else null end) as "#5", count(distinct case when (select "processAttr"."valueStr" from "processAttr" where "processAttr"."processUid" = "process"."uid" and "processAttr"."name" = 'd_gpl_fname') = 'Да' then "cfn.pm_uid_to_str"("event"."processUid") else null end) as "#6", count(distinct case when "cfn.pm_match_attr"(1642363404433, 1, "process"."uid", '"1ЛТП"  > "1ЛТП"* > "3ЛТП"+ > .*', 'supp_level', true) then "cfn.pm_uid_to_str"("event"."processUid") else null end) as "#7", count(distinct "event"."processUid") as "#8", count(distinct case when "cfn.pm_match_attr"(1642363404433, 2, "process"."uid", '"1ЛТП"  > "1ЛТП"* > ("2ЛТП" | "КДГ")+ > ("1ЛТП" | "2ЛТП" | "КДГ")* > "3ЛТП"+ > .*', 'supp_level', true) then "cfn.pm_uid_to_str"("event"."processUid") else null end) as "#9", count(distinct case when "cfn.pm_match_attr"(1642363404433, 3, "process"."uid", '"1ЛТП"  > "1ЛТП"* > ("2ЛТП" | "КДГ")+ > ("1ЛТП" | "2ЛТП" | "КДГ")* > ("1ЛТП" | "2ЛТП" | "КДГ")', 'supp_level', true) then "cfn.pm_uid_to_str"("event"."processUid") else null end) as "#10" from "process" as "process", "event" as "event" inner join "eventName" on "event"."modelUid" = "eventName"."modelUid" and "event"."nameId" = "eventName"."id" where exists(select 1 from "processAttr" where "processAttr"."processUid" = "process"."uid" and "processAttr"."name" = 'mrf_name' and "processAttr"."valueStr" in ('МРФ Волга', 'МРФ Дальний восток', 'МРФ Северо-Запад', 'МРФ Сибирь', 'МРФ Урал', 'МРФ Центр', 'МРФ Юг') limit 1) and "process"."modelUid" = "cfn.pm_str_to_uid"('03c66e84-e6b1-4eaa-904b-fe7200409440') and "process"."uid" = "event"."processUid" group by "#1", "#3";]])
```

**Actual behavior**

Memory shown in ps grows, valgrind reports memory leaks:

```
==700980== 30,888,880 bytes in 483,716 blocks are definitely lost in loss record 571 of 571
==700980==    at 0x4C360A5: malloc (vg_replace_malloc.c:380)
==700980==    by 0x4C1F71: sql_sized_malloc (malloc.c:53)
==700980==    by 0x4C208E: sqlMalloc (malloc.c:123)
==700980==    by 0x4C208E: dbMallocRawFinish (malloc.c:278)
==700980==    by 0x4C3E49: sqlVdbeMemGrow (mem.c:2188)
==700980==    by 0x4CA277: mem_from_mp (mem.c:2696)
==700980==    by 0x4E4201: vdbe_field_ref_fetch (vdbe.c:408)
==700980==    by 0x4E750D: sqlVdbeExec (vdbe.c:2077)
==700980==    by 0x4EA6BA: sqlStep (vdbeapi.c:304)
==700980==    by 0x4EA6BA: sql_step (vdbeapi.c:332)
==700980==    by 0x5A6CF6: sql_execute (execute.c:558)
==700980==    by 0x5A6CF6: sql_prepare_and_execute (execute.c:627)
==700980==    by 0x51299B: lbox_execute (execute.c:456)
==700980==    by 0x65545A: lj_BC_FUNCC (buildvm_x86.dasc:811)
==700980==    by 0x61B907: lua_pcall (lj_api.c:1158)
==700980== 
==700980== LEAK SUMMARY:
==700980==    definitely lost: 46,269,407 bytes in 804,016 blocks
==700980==    indirectly lost: 2,340 bytes in 14 blocks
==700980==      possibly lost: 19,300,320 bytes in 92,318 blocks
==700980==    still reachable: 4,059,750 bytes in 44,190 blocks
==700980==                       of which reachable via heuristic:
==700980==                         length64           : 64,720 bytes in 11 blocks
==700980==                         newarray           : 4,264 bytes in 1 blocks
==700980==         suppressed: 0 bytes in 0 blocks
```

See full log here: https://t.bk.ru/1eNoBEW/valgrind.log

**Expected behavior**

Memory usage is stable, no leaks are detected.

```
definitely lost: 0 bytes in 0 blocks
```

**Comment by ligurio** [comment]
Similar (according to stacktrace) leak can be achieved with fuzzer for `sql_expr_compile()`.

### Patch:

```diff
diff --git a/src/box/sql.c b/src/box/sql.c
index 2a78a96d5..1130cf3cb 100644
--- a/src/box/sql.c
+++ b/src/box/sql.c
@@ -69,7 +69,10 @@ sql_init(void)
 {
 	default_flags |= default_sql_flags;
 
-	current_session()->sql_flags |= default_sql_flags;
+	if (db != NULL)
+		return;
+
+	// current_session()->sql_flags |= default_sql_flags;
 
 	if (sql_init_db(&db) != 0)
 		panic("failed to initialize SQL subsystem");
diff --git a/src/lib/coll/coll.c b/src/lib/coll/coll.c
index a2dd14c59..875b1a8b2 100644
--- a/src/lib/coll/coll.c
+++ b/src/lib/coll/coll.c
@@ -415,6 +415,9 @@ coll_unref(struct coll *coll)
 void
 coll_init(void)
 {
+	if (icu_ucase_default_map != NULL)
+		return;
+
 	UErrorCode err = U_ZERO_ERROR;
 	coll_cache = mh_coll_new();
 	icu_ucase_default_map = ucasemap_open("", 0, &err);
diff --git a/test/fuzz/CMakeLists.txt b/test/fuzz/CMakeLists.txt
index f32bbe91e..62e3c20a2 100644
--- a/test/fuzz/CMakeLists.txt
+++ b/test/fuzz/CMakeLists.txt
@@ -44,8 +44,12 @@ target_link_libraries(swim_proto_member_fuzzer PUBLIC swim fuzzer_config)
 add_executable(swim_proto_meta_fuzzer swim_proto_meta_fuzzer.c)
 target_link_libraries(swim_proto_meta_fuzzer PUBLIC swim fuzzer_config)
 
+add_executable(sql_expr_compile_fuzzer sql_expr_compile_fuzzer.c)
+target_link_libraries(sql_expr_compile_fuzzer PUBLIC box fuzzer_config)
+
 set(fuzzing_binaries csv_fuzzer
                      http_parser_fuzzer
+                     sql_expr_compile_fuzzer
                      swim_proto_member_fuzzer
                      swim_proto_meta_fuzzer
                      uri_fuzzer)
diff --git a/test/fuzz/sql_expr_compile_fuzzer.c b/test/fuzz/sql_expr_compile_fuzzer.c
new file mode 100644
index 000000000..16c1887aa
--- /dev/null
+++ b/test/fuzz/sql_expr_compile_fuzzer.c
@@ -0,0 +1,35 @@
+#include <stddef.h>
+#include <stdlib.h>
+#include <string.h>
+#include "box/box.h"
+#include "box/sql.h"
+#include "coll/coll.h"
+#include "memory.h"
+#include "fiber.h"
+
+void cord_on_yield() {}
+
+int
+LLVMFuzzerTestOneInput(const uint8_t *data, size_t size)
+{
+        memory_init();
+        fiber_init(fiber_c_invoke);
+        coll_init();
+        sql_init();
+
+        char *buf = calloc(size + 1, sizeof(char));
+        if (!buf)
+                return 0;
+        memcpy(buf, data, size);
+        buf[size] = '\0';
+
+        struct Expr *expr = sql_expr_compile(sql_get(), (const char *)buf, (int)size);
+
+        if (!expr)
+                sql_expr_delete(sql_get(), expr, false);
+        free(buf);
+        fiber_free();
+        memory_free();
+
+        return 0;
+}
```

### How to build:

```sh
$ CC=clang CXX=clang++ cmake -DENABLE_FUZZER=ON -DENABLE_ASAN=ON -S . -B build
$ make fuzzers -C build -j
$ ./build/test/fuzz/sql_expr_compile_fuzzer                                                   
INFO: Seed: 980249272                                                                                                                   
INFO: Loaded 1 modules   (150951 inline 8-bit counters): 150951 [0x21dfae0, 0x2204887),                                   
INFO: Loaded 1 PC tables (150951 PCs): 150951 [0x2204888,0x24522f8),                                       
INFO: -max_len is not provided; libFuzzer will not generate inputs larger than 4096 bytes                                              
INFO: A corpus is not provided, starting from an empty corpus

...
        NEW_FUNC[1/1]: 0x663b30 in dbMallocRawFinish /home/sergeyb/sources/MRG/tarantool/src/box/sql/malloc.c:275
                                                                                                                                        =================================================================                                                                       
==1466139==ERROR: LeakSanitizer: detected memory leaks                                                                                                                                                      
Direct leak of 104 byte(s) in 1 object(s) allocated from:                                                                               
    #0 0x57181d in malloc (/home/sergeyb/sources/MRG/tarantool/build/test/fuzz/sql_expr_compile_fuzzer+0x57181d)
    #1 0x661fc2 in sql_sized_malloc /home/sergeyb/sources/MRG/tarantool/src/box/sql/malloc.c:53:6
    #2 0x661e7f in sqlMalloc /home/sergeyb/sources/MRG/tarantool/src/box/sql/malloc.c:123:7
    #3 0x663bdd in dbMallocRawFinish /home/sergeyb/sources/MRG/tarantool/src/box/sql/malloc.c:278:6
    #4 0x663b15 in sqlDbMallocRawNN /home/sergeyb/sources/MRG/tarantool/src/box/sql/malloc.c:339:9
    #5 0x607afa in sql_expr_dup /home/sergeyb/sources/MRG/tarantool/src/box/sql/expr.c:1479:12
    #6 0x602f2e in sqlExprDup /home/sergeyb/sources/MRG/tarantool/src/box/sql/expr.c:1617:13
    #7 0x6f7969 in sql_expr_extract_select /home/sergeyb/sources/MRG/tarantool/src/box/sql/select.c:6750:3
    #8 0xa392e1 in yy_reduce /home/sergeyb/sources/MRG/tarantool/src/box/sql/parse.y:468:11
    #9 0xa32ee7 in sqlParser /home/sergeyb/sources/MRG/tarantool/build/src/box/sql/parse.c:4540:7
    #10 0x719635 in sqlRunParser /home/sergeyb/sources/MRG/tarantool/src/box/sql/tokenize.c:543:4
    #11 0x71a918 in sql_expr_compile /home/sergeyb/sources/MRG/tarantool/src/box/sql/tokenize.c:591:6
    #12 0x5a39b3 in LLVMFuzzerTestOneInput /home/sergeyb/sources/MRG/tarantool/test/fuzz/sql_expr_compile_fuzzer.c:26:29
...
```
