### ISSUE TITLE
ASAN reports memory leak in readline

### ISSUE THREAD

**Issue by locker** [tarantool/tarantool#6817]
Tarantool version: 2.10.0-beta2-70-g5adc02f623f8

Steps to reproduce:

1. Build Tarantool with ASAN:
   ```sh
   CC=clang CXX=clang++ cmake -S. -Bbuild/release-asan -DCMAKE_BUILD_TYPE=RelWithDebInfo -DENABLE_ASAN=ON
   make -Cbuild/release-asan -j16
   ```
2. Enable ASAN:
   ```sh
   export ASAN=ON
   export LSAN_OPTIONS=suppressions=${PWD}/asan/lsan.supp
   export ASAN_OPTIONS=heap_profile=0:unmap_shadow_on_exit=1:detect_invalid_pointer_pairs=1:symbolize=1:detect_leaks=1:dump_instruction_bytes=1:print_suppressions=0
   ```
3. Start Tarantool and type something in the console, then exit:
   ```
   $ build/release-asan/src/tarantool
   Tarantool 2.10.0-beta2-70-g5adc02f623f8
   type 'help' for interactive help
   tarantool> test
   ---
   - null
   ...
   
   tarantool>
   =================================================================
   ==57860==ERROR: LeakSanitizer: detected memory leaks
   
   Direct leak of 5 byte(s) in 1 object(s) allocated from:
       #0 0x4a79ed in malloc (/home/vlad/src/tarantool/tarantool/build/release-asan/src/tarantool+0x4a79ed)
       #1 0x7f8784c9300c in xmalloc (/lib/x86_64-linux-gnu/libreadline.so.8+0x3c00c)
   
   SUMMARY: AddressSanitizer: 5 byte(s) leaked in 1 allocation(s).
   ```

Looks like the typed-in command was stored in the readline history buffer. We need to either clean up the buffer on exit or add an exception. This blocks https://github.com/tarantool/tarantool-ee/issues/17.

**Comment by locker** [comment]
Cherry-picked to 2.8 and 1.10.
