### ISSUE TITLE
catch exceptions in boxffi_iterator_next

### ISSUE THREAD

**Issue by pmwkaa** [tarantool/tarantool#708]
```
#0 0x00007fa47373b925 in *__GI_raise (sig=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:64
#1 0x00007fa47373d105 in *__GI_abort () at abort.c:92
#2 0x00007fa4741adc7d in __gnu_cxx::__verbose_terminate_handler () at ../../../../libstdc++-v3/libsupc++/vterminate.cc:95
#3 0x00007fa4741abcf6 in __cxxabiv1::__terminate (handler=<optimized out>) at ../../../../libstdc++-v3/libsupc++/eh_terminate.cc:47
#4 0x00007fa4741abd41 in std::terminate () at ../../../../libstdc++-v3/libsupc++/eh_terminate.cc:57
#5 0x00007fa4741abf59 in __cxxabiv1::__cxa_throw (obj=0x7fa292fb6ea0, tinfo=0x55f580 <typeinfo for OutOfMemory*>, dest=0x0)
   at ../../../../libstdc++-v3/libsupc++/eh_throw.cc:87
#6 0x0000000000438f89 in smalloc (alloc=0x822580 <memtx_alloc>, size=46, where=0x563909 "tuple")
   at /home/a.levshin/tarantool/src/lib/small/small.h:280
#7 0x0000000000439ad0 in tuple_alloc (format=0x1ef4830, size=34) at /home/a.levshin/tarantool/src/box/tuple.cc:256
#8 0x000000000043a465 in tuple_new (format=0x1ef4830, data=0x7fa292fb7067 "\222\276bad_vano@list.ru|w/\020\201nS7\321T\376\002", 
   end=0x7fa292fb7089 "\003") at /home/a.levshin/tarantool/src/box/tuple.cc:404
#9 0x0000000000442511 in sophia_iterator_next (ptr=0x7fa3c57f4f80) at /home/a.levshin/tarantool/src/box/sophia_index.cc:391
---Type <return> to continue, or q <return> to quit---
#10 0x0000000000453bc9 in boxffi_iterator_next (itr=0x7fa3c57f4f80) at /home/a.levshin/tarantool/src/box/lua/index.cc:126
#11 0x000000000f6787e4 in ?? ()
#12 0x0000000000000000 in ?? ()
```

**Comment by kostja** [comment]
Dmitry, I think it would be better if Sophia catches these exceptions, what do you think?
