### ISSUE TITLE
Memory leaks on using Curl_resolv

### ISSUE THREAD

**Issue by ligurio** [tarantool/tarantool#7080]
### How-to reproduce:

Terminal 1:
`$ python -m http.server 9000`

Terminal 2:

Content of `http_client_test.lua`:
```lua
local client = require('http.client')
local t = require('luatest')
local g = t.group('http_client', nil)

g.test_http_client = function()
    client.get("http://localhost:9000/")
    --local s = client:new():get('http://localhost:1')
    --print(require('log').info(s))
end
```

```
$ CC=clang-11 CXX=clang++-11 cmake -DENABLE_ASAN=ON -DCMAKE_BUILD_TYPE=Debug ..
...
$ ASAN=ON ASAN_OPTIONS=heap_profile=0:unmap_shadow_on_exit=1:detect_invalid_pointer_pairs=1:symbolize=1:detect_leaks=1:dump_instruction_bytes=1:print_suppressions=0 ../src/tarantool /home/sergeyb/sources/MRG/tarantool/test-run/lib/luatest/bin/luatest -v -c http_client_test.lua


=================================================================
==2063101==ERROR: LeakSanitizer: detected memory leaks

Indirect leak of 74264 byte(s) in 1 object(s) allocated from:
    #0 0x4a5e5d in malloc (/home/sergeyb/sources/MRG/tarantool/build/src/tarantool+0x4a5e5d)
    #1 0xcabd61 in ares_init_options (/home/sergeyb/sources/MRG/tarantool/build/src/tarantool+0xcabd61)
    #2 0xc360e8 in Curl_resolver_init /home/sergeyb/sources/MRG/tarantool/third_party/curl/lib/asyn-ares.c:179:12
    #3 0xc89525 in Curl_open /home/sergeyb/sources/MRG/tarantool/third_party/curl/lib/url.c:661:12
    #4 0xc44d4e in curl_easy_init /home/sergeyb/sources/MRG/tarantool/third_party/curl/lib/easy.c:305:12
    #5 0xc37fe3 in Curl_conncache_init /home/sergeyb/sources/MRG/tarantool/third_party/curl/lib/conncache.c:119:27
    #6 0xc64806 in Curl_multi_handle /home/sergeyb/sources/MRG/tarantool/third_party/curl/lib/multi.c:371:6
    #7 0xc64a62 in curl_multi_init /home/sergeyb/sources/MRG/tarantool/third_party/curl/lib/multi.c:420:10
    #8 0x7e141c in curl_env_create /home/sergeyb/sources/MRG/tarantool/src/curl.c:229:15
    #9 0x7e4de6 in httpc_env_create /home/sergeyb/sources/MRG/tarantool/src/httpc.c:90:9
    #10 0x818515 in luaT_httpc_new /home/sergeyb/sources/MRG/tarantool/src/lua/httpc.c:378:6
    #11 0x8e265a in lj_BC_FUNCC /home/sergeyb/sources/MRG/tarantool/build/third_party/luajit/src/lj_vm.S:809

Indirect leak of 29168 byte(s) in 1 object(s) allocated from:
    #0 0x4a5e5d in malloc (/home/sergeyb/sources/MRG/tarantool/build/src/tarantool+0x4a5e5d)
    #1 0xc5a8dd in curl_dbg_malloc /home/sergeyb/sources/MRG/tarantool/third_party/curl/lib/memdebug.c:143:9
    #2 0xc4b117 in Curl_hash_init /home/sergeyb/sources/MRG/tarantool/third_party/curl/lib/hash.c:73:14
    #3 0xc64a3f in sh_init /home/sergeyb/sources/MRG/tarantool/third_party/curl/lib/multi.c:337:10
    #4 0xc647e3 in Curl_multi_handle /home/sergeyb/sources/MRG/tarantool/third_party/curl/lib/multi.c:368:6
    #5 0xc64a62 in curl_multi_init /home/sergeyb/sources/MRG/tarantool/third_party/curl/lib/multi.c:420:10
    #6 0x7e141c in curl_env_create /home/sergeyb/sources/MRG/tarantool/src/curl.c:229:15
    #7 0x7e4de6 in httpc_env_create /home/sergeyb/sources/MRG/tarantool/src/httpc.c:90:9
    #8 0x818515 in luaT_httpc_new /home/sergeyb/sources/MRG/tarantool/src/lua/httpc.c:378:6
    #9 0x8e265a in lj_BC_FUNCC /home/sergeyb/sources/MRG/tarantool/build/third_party/luajit/src/lj_vm.S:809

Indirect leak of 5272 byte(s) in 1 object(s) allocated from:
    #0 0x4a5fd2 in calloc (/home/sergeyb/sources/MRG/tarantool/build/src/tarantool+0x4a5fd2)
    #1 0xc5ad42 in curl_dbg_calloc /home/sergeyb/sources/MRG/tarantool/third_party/curl/lib/memdebug.c:172:9
    #2 0xc894c6 in Curl_open /home/sergeyb/sources/MRG/tarantool/third_party/curl/lib/url.c:652:10
    #3 0xc44d4e in curl_easy_init /home/sergeyb/sources/MRG/tarantool/third_party/curl/lib/easy.c:305:12
    #4 0xc37fe3 in Curl_conncache_init /home/sergeyb/sources/MRG/tarantool/third_party/curl/lib/conncache.c:119:27
    #5 0xc64806 in Curl_multi_handle /home/sergeyb/sources/MRG/tarantool/third_party/curl/lib/multi.c:371:6
    #6 0xc64a62 in curl_multi_init /home/sergeyb/sources/MRG/tarantool/third_party/curl/lib/multi.c:420:10
    #7 0x7e141c in curl_env_create /home/sergeyb/sources/MRG/tarantool/src/curl.c:229:15
    #8 0x7e4de6 in httpc_env_create /home/sergeyb/sources/MRG/tarantool/src/httpc.c:90:9
    #9 0x818515 in luaT_httpc_new /home/sergeyb/sources/MRG/tarantool/src/lua/httpc.c:378:6
    #10 0x8e265a in lj_BC_FUNCC /home/sergeyb/sources/MRG/tarantool/build/third_party/luajit/src/lj_vm.S:809

Indirect leak of 3120 byte(s) in 1 object(s) allocated from:
    #0 0x4a5e5d in malloc (/home/sergeyb/sources/MRG/tarantool/build/src/tarantool+0x4a5e5d)
    #1 0xc5a8dd in curl_dbg_malloc /home/sergeyb/sources/MRG/tarantool/third_party/curl/lib/memdebug.c:143:9
    #2 0xc4b117 in Curl_hash_init /home/sergeyb/sources/MRG/tarantool/third_party/curl/lib/hash.c:73:14
    #3 0xc38027 in Curl_conncache_init /home/sergeyb/sources/MRG/tarantool/third_party/curl/lib/conncache.c:123:8
    #4 0xc64806 in Curl_multi_handle /home/sergeyb/sources/MRG/tarantool/third_party/curl/lib/multi.c:371:6
    #5 0xc64a62 in curl_multi_init /home/sergeyb/sources/MRG/tarantool/third_party/curl/lib/multi.c:420:10
    #6 0x7e141c in curl_env_create /home/sergeyb/sources/MRG/tarantool/src/curl.c:229:15
    #7 0x7e4de6 in httpc_env_create /home/sergeyb/sources/MRG/tarantool/src/httpc.c:90:9
    #8 0x818515 in luaT_httpc_new /home/sergeyb/sources/MRG/tarantool/src/lua/httpc.c:378:6
    #9 0x8e265a in lj_BC_FUNCC /home/sergeyb/sources/MRG/tarantool/build/third_party/luajit/src/lj_vm.S:809

Indirect leak of 416 byte(s) in 1 object(s) allocated from:
    #0 0x4a5fd2 in calloc (/home/sergeyb/sources/MRG/tarantool/build/src/tarantool+0x4a5fd2)
    #1 0xc5ad42 in curl_dbg_calloc /home/sergeyb/sources/MRG/tarantool/third_party/curl/lib/memdebug.c:172:9
    #2 0xc64788 in Curl_multi_handle /home/sergeyb/sources/MRG/tarantool/third_party/curl/lib/multi.c:358:30
    #3 0xc64a62 in curl_multi_init /home/sergeyb/sources/MRG/tarantool/third_party/curl/lib/multi.c:420:10
    #4 0x7e141c in curl_env_create /home/sergeyb/sources/MRG/tarantool/src/curl.c:229:15
    #5 0x7e4de6 in httpc_env_create /home/sergeyb/sources/MRG/tarantool/src/httpc.c:90:9
    #6 0x818515 in luaT_httpc_new /home/sergeyb/sources/MRG/tarantool/src/lua/httpc.c:378:6
    #7 0x8e265a in lj_BC_FUNCC /home/sergeyb/sources/MRG/tarantool/build/third_party/luajit/src/lj_vm.S:809

Indirect leak of 240 byte(s) in 1 object(s) allocated from:
    #0 0x4a5e5d in malloc (/home/sergeyb/sources/MRG/tarantool/build/src/tarantool+0x4a5e5d)
    #1 0xc5a8dd in curl_dbg_malloc /home/sergeyb/sources/MRG/tarantool/third_party/curl/lib/memdebug.c:143:9
    #2 0xc4b117 in Curl_hash_init /home/sergeyb/sources/MRG/tarantool/third_party/curl/lib/hash.c:73:14
    #3 0xc4ce9e in Curl_mk_dnscache /home/sergeyb/sources/MRG/tarantool/third_party/curl/lib/hostip.c:984:10
    #4 0xc647c0 in Curl_multi_handle /home/sergeyb/sources/MRG/tarantool/third_party/curl/lib/multi.c:365:6
    #5 0xc64a62 in curl_multi_init /home/sergeyb/sources/MRG/tarantool/third_party/curl/lib/multi.c:420:10
    #6 0x7e141c in curl_env_create /home/sergeyb/sources/MRG/tarantool/src/curl.c:229:15
    #7 0x7e4de6 in httpc_env_create /home/sergeyb/sources/MRG/tarantool/src/httpc.c:90:9
    #8 0x818515 in luaT_httpc_new /home/sergeyb/sources/MRG/tarantool/src/lua/httpc.c:378:6
    #9 0x8e265a in lj_BC_FUNCC /home/sergeyb/sources/MRG/tarantool/build/third_party/luajit/src/lj_vm.S:809

Indirect leak of 128 byte(s) in 1 object(s) allocated from:
    #0 0x4a6179 in realloc (/home/sergeyb/sources/MRG/tarantool/build/src/tarantool+0x4a6179)
    #1 0xcaf40e in config_nameserver (/home/sergeyb/sources/MRG/tarantool/build/src/tarantool+0xcaf40e)
    #2 0xcacbd2 in init_by_resolv_conf (/home/sergeyb/sources/MRG/tarantool/build/src/tarantool+0xcacbd2)
    #3 0xcac057 in ares_init_options (/home/sergeyb/sources/MRG/tarantool/build/src/tarantool+0xcac057)
    #4 0xc360e8 in Curl_resolver_init /home/sergeyb/sources/MRG/tarantool/third_party/curl/lib/asyn-ares.c:179:12
    #5 0xc89525 in Curl_open /home/sergeyb/sources/MRG/tarantool/third_party/curl/lib/url.c:661:12
    #6 0xc44d4e in curl_easy_init /home/sergeyb/sources/MRG/tarantool/third_party/curl/lib/easy.c:305:12
    #7 0xc37fe3 in Curl_conncache_init /home/sergeyb/sources/MRG/tarantool/third_party/curl/lib/conncache.c:119:27
    #8 0xc64806 in Curl_multi_handle /home/sergeyb/sources/MRG/tarantool/third_party/curl/lib/multi.c:371:6
    #9 0xc64a62 in curl_multi_init /home/sergeyb/sources/MRG/tarantool/third_party/curl/lib/multi.c:420:10
    #10 0x7e141c in curl_env_create /home/sergeyb/sources/MRG/tarantool/src/curl.c:229:15
    #11 0x7e4de6 in httpc_env_create /home/sergeyb/sources/MRG/tarantool/src/httpc.c:90:9
    #12 0x818515 in luaT_httpc_new /home/sergeyb/sources/MRG/tarantool/src/lua/httpc.c:378:6
    #13 0x8e265a in lj_BC_FUNCC /home/sergeyb/sources/MRG/tarantool/build/third_party/luajit/src/lj_vm.S:809

Indirect leak of 102 byte(s) in 1 object(s) allocated from:
    #0 0x4a5fd2 in calloc (/home/sergeyb/sources/MRG/tarantool/build/src/tarantool+0x4a5fd2)
    #1 0xc5ad42 in curl_dbg_calloc /home/sergeyb/sources/MRG/tarantool/third_party/curl/lib/memdebug.c:172:9
    #2 0xc4d901 in get_localhost6 /home/sergeyb/sources/MRG/tarantool/third_party/curl/lib/hostip.c:473:8
    #3 0xc4cc5c in get_localhost /home/sergeyb/sources/MRG/tarantool/third_party/curl/lib/hostip.c:531:17
    #4 0xc4c97b in Curl_resolv /home/sergeyb/sources/MRG/tarantool/third_party/curl/lib/hostip.c:710:16
    #5 0xc4cd35 in Curl_resolv_timeout /home/sergeyb/sources/MRG/tarantool/third_party/curl/lib/hostip.c:896:8
    #6 0xc8f682 in resolve_server /home/sergeyb/sources/MRG/tarantool/third_party/curl/lib/url.c:3402:12
    #7 0xc8b826 in create_conn /home/sergeyb/sources/MRG/tarantool/third_party/curl/lib/url.c:4031:12
    #8 0xc8a8eb in Curl_connect /home/sergeyb/sources/MRG/tarantool/third_party/curl/lib/url.c:4121:12
    #9 0xc67bf3 in multi_runsingle /home/sergeyb/sources/MRG/tarantool/third_party/curl/lib/multi.c:1814:16
    #10 0xc6a586 in multi_socket /home/sergeyb/sources/MRG/tarantool/third_party/curl/lib/multi.c:3064:16
    #11 0xc6a6a7 in curl_multi_socket_action /home/sergeyb/sources/MRG/tarantool/third_party/curl/lib/multi.c:3185:12
    #12 0x7e35cd in curl_multi_process /home/sergeyb/sources/MRG/tarantool/src/curl.c:62:10
    #13 0x7e1eae in curl_timer_cb /home/sergeyb/sources/MRG/tarantool/src/curl.c:109:2
    #14 0x111d59b in ev_invoke_pending /home/sergeyb/sources/MRG/tarantool/third_party/libev/ev.c:3349:11
    #15 0x11324b8 in ev_run /home/sergeyb/sources/MRG/tarantool/third_party/libev/ev.c:3752:7
    #16 0x7f22ef in tarantool_lua_run_script /home/sergeyb/sources/MRG/tarantool/src/lua/init.c:699:2
    #17 0x4dd0b9 in main /home/sergeyb/sources/MRG/tarantool/src/main.cc:792:7
    #18 0x7fc5091070b2 in __libc_start_main /build/glibc-sMfBJT/glibc-2.31/csu/../csu/libc-start.c:308:16

Indirect leak of 90 byte(s) in 1 object(s) allocated from:
    #0 0x4a5fd2 in calloc (/home/sergeyb/sources/MRG/tarantool/build/src/tarantool+0x4a5fd2)
    #1 0xc5ad42 in curl_dbg_calloc /home/sergeyb/sources/MRG/tarantool/third_party/curl/lib/memdebug.c:172:9
    #2 0xc4cbab in get_localhost /home/sergeyb/sources/MRG/tarantool/third_party/curl/lib/hostip.c:519:8
    #3 0xc4c97b in Curl_resolv /home/sergeyb/sources/MRG/tarantool/third_party/curl/lib/hostip.c:710:16
    #4 0xc4cd35 in Curl_resolv_timeout /home/sergeyb/sources/MRG/tarantool/third_party/curl/lib/hostip.c:896:8
    #5 0xc8f682 in resolve_server /home/sergeyb/sources/MRG/tarantool/third_party/curl/lib/url.c:3402:12
    #6 0xc8b826 in create_conn /home/sergeyb/sources/MRG/tarantool/third_party/curl/lib/url.c:4031:12
    #7 0xc8a8eb in Curl_connect /home/sergeyb/sources/MRG/tarantool/third_party/curl/lib/url.c:4121:12
    #8 0xc67bf3 in multi_runsingle /home/sergeyb/sources/MRG/tarantool/third_party/curl/lib/multi.c:1814:16
    #9 0xc6a586 in multi_socket /home/sergeyb/sources/MRG/tarantool/third_party/curl/lib/multi.c:3064:16
    #10 0xc6a6a7 in curl_multi_socket_action /home/sergeyb/sources/MRG/tarantool/third_party/curl/lib/multi.c:3185:12
    #11 0x7e35cd in curl_multi_process /home/sergeyb/sources/MRG/tarantool/src/curl.c:62:10
    #12 0x7e1eae in curl_timer_cb /home/sergeyb/sources/MRG/tarantool/src/curl.c:109:2
    #13 0x111d59b in ev_invoke_pending /home/sergeyb/sources/MRG/tarantool/third_party/libev/ev.c:3349:11
    #14 0x11324b8 in ev_run /home/sergeyb/sources/MRG/tarantool/third_party/libev/ev.c:3752:7
    #15 0x7f22ef in tarantool_lua_run_script /home/sergeyb/sources/MRG/tarantool/src/lua/init.c:699:2
    #16 0x4dd0b9 in main /home/sergeyb/sources/MRG/tarantool/src/main.cc:792:7
    #17 0x7fc5091070b2 in __libc_start_main /build/glibc-sMfBJT/glibc-2.31/csu/../csu/libc-start.c:308:16

Indirect leak of 79 byte(s) in 1 object(s) allocated from:
    #0 0x4a5e5d in malloc (/home/sergeyb/sources/MRG/tarantool/build/src/tarantool+0x4a5e5d)
    #1 0xc5a8dd in curl_dbg_malloc /home/sergeyb/sources/MRG/tarantool/third_party/curl/lib/memdebug.c:143:9
    #2 0xc4b3b1 in mk_hash_element /home/sergeyb/sources/MRG/tarantool/third_party/curl/lib/hash.c:88:34
    #3 0xc4b319 in Curl_hash_add /home/sergeyb/sources/MRG/tarantool/third_party/curl/lib/hash.c:124:8
    #4 0xc4c452 in Curl_cache_addr /home/sergeyb/sources/MRG/tarantool/third_party/curl/lib/hostip.c:451:10
    #5 0xc4ca98 in Curl_resolv /home/sergeyb/sources/MRG/tarantool/third_party/curl/lib/hostip.c:743:13
    #6 0xc4cd35 in Curl_resolv_timeout /home/sergeyb/sources/MRG/tarantool/third_party/curl/lib/hostip.c:896:8
    #7 0xc8f682 in resolve_server /home/sergeyb/sources/MRG/tarantool/third_party/curl/lib/url.c:3402:12
    #8 0xc8b826 in create_conn /home/sergeyb/sources/MRG/tarantool/third_party/curl/lib/url.c:4031:12
    #9 0xc8a8eb in Curl_connect /home/sergeyb/sources/MRG/tarantool/third_party/curl/lib/url.c:4121:12
    #10 0xc67bf3 in multi_runsingle /home/sergeyb/sources/MRG/tarantool/third_party/curl/lib/multi.c:1814:16
    #11 0xc6a586 in multi_socket /home/sergeyb/sources/MRG/tarantool/third_party/curl/lib/multi.c:3064:16
    #12 0xc6a6a7 in curl_multi_socket_action /home/sergeyb/sources/MRG/tarantool/third_party/curl/lib/multi.c:3185:12
    #13 0x7e35cd in curl_multi_process /home/sergeyb/sources/MRG/tarantool/src/curl.c:62:10
    #14 0x7e1eae in curl_timer_cb /home/sergeyb/sources/MRG/tarantool/src/curl.c:109:2
    #15 0x111d59b in ev_invoke_pending /home/sergeyb/sources/MRG/tarantool/third_party/libev/ev.c:3349:11
    #16 0x11324b8 in ev_run /home/sergeyb/sources/MRG/tarantool/third_party/libev/ev.c:3752:7
    #17 0x7f22ef in tarantool_lua_run_script /home/sergeyb/sources/MRG/tarantool/src/lua/init.c:699:2
    #18 0x4dd0b9 in main /home/sergeyb/sources/MRG/tarantool/src/main.cc:792:7
    #19 0x7fc5091070b2 in __libc_start_main /build/glibc-sMfBJT/glibc-2.31/csu/../csu/libc-start.c:308:16

Indirect leak of 40 byte(s) in 1 object(s) allocated from:
    #0 0x4a5fd2 in calloc (/home/sergeyb/sources/MRG/tarantool/build/src/tarantool+0x4a5fd2)
    #1 0xc5ad42 in curl_dbg_calloc /home/sergeyb/sources/MRG/tarantool/third_party/curl/lib/memdebug.c:172:9
    #2 0xc4c384 in Curl_cache_addr /home/sergeyb/sources/MRG/tarantool/third_party/curl/lib/hostip.c:435:9
    #3 0xc4ca98 in Curl_resolv /home/sergeyb/sources/MRG/tarantool/third_party/curl/lib/hostip.c:743:13
    #4 0xc4cd35 in Curl_resolv_timeout /home/sergeyb/sources/MRG/tarantool/third_party/curl/lib/hostip.c:896:8
    #5 0xc8f682 in resolve_server /home/sergeyb/sources/MRG/tarantool/third_party/curl/lib/url.c:3402:12
    #6 0xc8b826 in create_conn /home/sergeyb/sources/MRG/tarantool/third_party/curl/lib/url.c:4031:12
    #7 0xc8a8eb in Curl_connect /home/sergeyb/sources/MRG/tarantool/third_party/curl/lib/url.c:4121:12
    #8 0xc67bf3 in multi_runsingle /home/sergeyb/sources/MRG/tarantool/third_party/curl/lib/multi.c:1814:16
    #9 0xc6a586 in multi_socket /home/sergeyb/sources/MRG/tarantool/third_party/curl/lib/multi.c:3064:16
    #10 0xc6a6a7 in curl_multi_socket_action /home/sergeyb/sources/MRG/tarantool/third_party/curl/lib/multi.c:3185:12
    #11 0x7e35cd in curl_multi_process /home/sergeyb/sources/MRG/tarantool/src/curl.c:62:10
    #12 0x7e1eae in curl_timer_cb /home/sergeyb/sources/MRG/tarantool/src/curl.c:109:2
    #13 0x111d59b in ev_invoke_pending /home/sergeyb/sources/MRG/tarantool/third_party/libev/ev.c:3349:11
    #14 0x11324b8 in ev_run /home/sergeyb/sources/MRG/tarantool/third_party/libev/ev.c:3752:7
    #15 0x7f22ef in tarantool_lua_run_script /home/sergeyb/sources/MRG/tarantool/src/lua/init.c:699:2
    #16 0x4dd0b9 in main /home/sergeyb/sources/MRG/tarantool/src/main.cc:792:7
    #17 0x7fc5091070b2 in __libc_start_main /build/glibc-sMfBJT/glibc-2.31/csu/../csu/libc-start.c:308:16

Indirect leak of 9 byte(s) in 1 object(s) allocated from:
    #0 0x491e74 in strdup (/home/sergeyb/sources/MRG/tarantool/build/src/tarantool+0x491e74)
    #1 0xcb808b in ares_strdup (/home/sergeyb/sources/MRG/tarantool/build/src/tarantool+0xcb808b)
    #2 0xcb8503 in ares_strsplit (/home/sergeyb/sources/MRG/tarantool/build/src/tarantool+0xcb8503)
    #3 0xcae892 in set_search (/home/sergeyb/sources/MRG/tarantool/build/src/tarantool+0xcae892)
    #4 0xcacb85 in init_by_resolv_conf (/home/sergeyb/sources/MRG/tarantool/build/src/tarantool+0xcacb85)
    #5 0xcac057 in ares_init_options (/home/sergeyb/sources/MRG/tarantool/build/src/tarantool+0xcac057)
    #6 0xc360e8 in Curl_resolver_init /home/sergeyb/sources/MRG/tarantool/third_party/curl/lib/asyn-ares.c:179:12
    #7 0xc89525 in Curl_open /home/sergeyb/sources/MRG/tarantool/third_party/curl/lib/url.c:661:12
    #8 0xc44d4e in curl_easy_init /home/sergeyb/sources/MRG/tarantool/third_party/curl/lib/easy.c:305:12
    #9 0xc37fe3 in Curl_conncache_init /home/sergeyb/sources/MRG/tarantool/third_party/curl/lib/conncache.c:119:27
    #10 0xc64806 in Curl_multi_handle /home/sergeyb/sources/MRG/tarantool/third_party/curl/lib/multi.c:371:6
    #11 0xc64a62 in curl_multi_init /home/sergeyb/sources/MRG/tarantool/third_party/curl/lib/multi.c:420:10
    #12 0x7e141c in curl_env_create /home/sergeyb/sources/MRG/tarantool/src/curl.c:229:15
    #13 0x7e4de6 in httpc_env_create /home/sergeyb/sources/MRG/tarantool/src/httpc.c:90:9
    #14 0x818515 in luaT_httpc_new /home/sergeyb/sources/MRG/tarantool/src/lua/httpc.c:378:6
    #15 0x8e265a in lj_BC_FUNCC /home/sergeyb/sources/MRG/tarantool/build/third_party/luajit/src/lj_vm.S:809

Indirect leak of 8 byte(s) in 1 object(s) allocated from:
    #0 0x4a5e5d in malloc (/home/sergeyb/sources/MRG/tarantool/build/src/tarantool+0x4a5e5d)
    #1 0xcb8442 in ares_strsplit (/home/sergeyb/sources/MRG/tarantool/build/src/tarantool+0xcb8442)
    #2 0xcae892 in set_search (/home/sergeyb/sources/MRG/tarantool/build/src/tarantool+0xcae892)
    #3 0xcacb85 in init_by_resolv_conf (/home/sergeyb/sources/MRG/tarantool/build/src/tarantool+0xcacb85)
    #4 0xcac057 in ares_init_options (/home/sergeyb/sources/MRG/tarantool/build/src/tarantool+0xcac057)
    #5 0xc360e8 in Curl_resolver_init /home/sergeyb/sources/MRG/tarantool/third_party/curl/lib/asyn-ares.c:179:12
    #6 0xc89525 in Curl_open /home/sergeyb/sources/MRG/tarantool/third_party/curl/lib/url.c:661:12
    #7 0xc44d4e in curl_easy_init /home/sergeyb/sources/MRG/tarantool/third_party/curl/lib/easy.c:305:12
    #8 0xc37fe3 in Curl_conncache_init /home/sergeyb/sources/MRG/tarantool/third_party/curl/lib/conncache.c:119:27
    #9 0xc64806 in Curl_multi_handle /home/sergeyb/sources/MRG/tarantool/third_party/curl/lib/multi.c:371:6
    #10 0xc64a62 in curl_multi_init /home/sergeyb/sources/MRG/tarantool/third_party/curl/lib/multi.c:420:10
    #11 0x7e141c in curl_env_create /home/sergeyb/sources/MRG/tarantool/src/curl.c:229:15
    #12 0x7e4de6 in httpc_env_create /home/sergeyb/sources/MRG/tarantool/src/httpc.c:90:9
    #13 0x818515 in luaT_httpc_new /home/sergeyb/sources/MRG/tarantool/src/lua/httpc.c:378:6
    #14 0x8e265a in lj_BC_FUNCC /home/sergeyb/sources/MRG/tarantool/build/third_party/luajit/src/lj_vm.S:809

Indirect leak of 3 byte(s) in 1 object(s) allocated from:
    #0 0x491e74 in strdup (/home/sergeyb/sources/MRG/tarantool/build/src/tarantool+0x491e74)
    #1 0xcb808b in ares_strdup (/home/sergeyb/sources/MRG/tarantool/build/src/tarantool+0xcb808b)
    #2 0xcaf1ce in config_lookup (/home/sergeyb/sources/MRG/tarantool/build/src/tarantool+0xcaf1ce)
    #3 0xcacd96 in init_by_resolv_conf (/home/sergeyb/sources/MRG/tarantool/build/src/tarantool+0xcacd96)
    #4 0xcac057 in ares_init_options (/home/sergeyb/sources/MRG/tarantool/build/src/tarantool+0xcac057)
    #5 0xc360e8 in Curl_resolver_init /home/sergeyb/sources/MRG/tarantool/third_party/curl/lib/asyn-ares.c:179:12
    #6 0xc89525 in Curl_open /home/sergeyb/sources/MRG/tarantool/third_party/curl/lib/url.c:661:12
    #7 0xc44d4e in curl_easy_init /home/sergeyb/sources/MRG/tarantool/third_party/curl/lib/easy.c:305:12
    #8 0xc37fe3 in Curl_conncache_init /home/sergeyb/sources/MRG/tarantool/third_party/curl/lib/conncache.c:119:27
    #9 0xc64806 in Curl_multi_handle /home/sergeyb/sources/MRG/tarantool/third_party/curl/lib/multi.c:371:6
    #10 0xc64a62 in curl_multi_init /home/sergeyb/sources/MRG/tarantool/third_party/curl/lib/multi.c:420:10
    #11 0x7e141c in curl_env_create /home/sergeyb/sources/MRG/tarantool/src/curl.c:229:15
    #12 0x7e4de6 in httpc_env_create /home/sergeyb/sources/MRG/tarantool/src/httpc.c:90:9
    #13 0x818515 in luaT_httpc_new /home/sergeyb/sources/MRG/tarantool/src/lua/httpc.c:378:6
    #14 0x8e265a in lj_BC_FUNCC /home/sergeyb/sources/MRG/tarantool/build/third_party/luajit/src/lj_vm.S:809

SUMMARY: AddressSanitizer: 112939 byte(s) leaked in 14 allocation(s).
```

```
Tarantool 1.10.12-87-g388fcaeb1
Target: Linux-x86_64-Debug
Build options: cmake . -DCMAKE_INSTALL_PREFIX=/usr/local -DENABLE_BACKTRACE=ON
Compiler: /usr/bin/clang-11 /usr/bin/clang++-11
C_FLAGS: -fexceptions -funwind-tables -fno-omit-frame-pointer -fno-stack-protector -fno-common -fopenmp -msse2 -fsanitize=address -fsanitize-blacklist=/home/sergeyb/sources/MRG/tarantool/asan/asan.supp -std=c11 -Wall -Wextra -Wno-strict-aliasing -Wno-char-subscripts -Wno-gnu-alignof-expression -Werror
CXX_FLAGS: -fexceptions -funwind-tables -fno-omit-frame-pointer -fno-stack-protector -fno-common -fopenmp -msse2 -fsanitize=address -fsanitize-blacklist=/home/sergeyb/sources/MRG/tarantool/asan/asan.supp -std=c++11 -Wall -Wextra -Wno-strict-aliasing -Wno-char-subscripts -Wno-invalid-offsetof -Wno-gnu-alignof-expression -Werror
```

**Comment by nshy** [comment]
Fixed by PR #10516

**Comment by Totktonada** [comment]
@nshy Out of curiosity: is it solved by the commit that closes the Lua state at exit?

**Comment by nshy** [comment]
> @nshy Out of curiosity: is it solved by the commit that closes the Lua state at exit?

I guess so.
