### ISSUE TITLE
Tarantool segfauls on SIGINT in hot_standby mode

### ISSUE THREAD

**Issue by rtsisyk** [tarantool/tarantool#721]
touch tarantool.sock;
> box.cfg { listen = 'unix/:tarantool.sock'}

or just 
> box.cfg { listen = '22' } <!-- any busy port

```
#0  0x00007f1e53dac819 in raise () from /lib64/libc.so.6
#1  0x00007f1e53dadf28 in abort () from /lib64/libc.so.6
#2  0x000000000041eb9b in sig_fatal_cb (signo=11) at /home/vagrant/tarantool/src/tarantool.cc:212
#3  <signal handler called>
#4  0x000000000048bf9d in fiber_yield () at /home/vagrant/tarantool/src/fiber.cc:249
#5  0x000000000048bbd4 in fiber_cancel (f=0x7f1e4b400238) at /home/vagrant/tarantool/src/fiber.cc:144
#6  0x000000000042b70b in recovery_stop_local (r=0x14781b0) at /home/vagrant/tarantool/src/box/recovery.cc:607
#7  0x000000000042a4f3 in recovery_delete (r=0x14781b0) at /home/vagrant/tarantool/src/box/recovery.cc:241
#8  0x00000000004218e0 in box_free () at /home/vagrant/tarantool/src/box/box.cc:408
#9  0x000000000041fadd in tarantool_free () at /home/vagrant/tarantool/src/tarantool.cc:497
#10 0x00007f1e53db00a9 in __run_exit_handlers () from /lib64/libc.so.6
#11 0x00007f1e53db00f5 in exit () from /lib64/libc.so.6
#12 0x00007f1e53d98b7c in __libc_start_main () from /lib64/libc.so.6
#13 0x000000000041e699 in _start ()
```

**Comment by rtsisyk** [comment]
This bug is fixed by @kostja patch. A test case will be overcomplicated.
May I close this ticket?
