### ISSUE TITLE
assert on SIGINT

### ISSUE THREAD

**Issue by pmwkaa** [tarantool/tarantool#726]
```
2015-02-16 18:05:28.726 [13178] main/103/lua txn.cc:230 W> too long REPLACE: 11.457 sec
tarantool: lj_gc.c:486: gc_finalize: Assertion `((GCobj *)(uintptr_t)(g->jit_L).gcptr32) == ((void *)0)' failed.

Program received signal SIGABRT, Aborted.
0xb7fde424 in __kernel_vsyscall ()
(gdb) backtrace 
#0  0xb7fde424 in __kernel_vsyscall ()
#1  0xb7afd267 in raise () from /lib/i386-linux-gnu/i686/cmov/libc.so.6
#2  0xb7afe923 in abort () from /lib/i386-linux-gnu/i686/cmov/libc.so.6
#3  0xb7af65e7 in __assert_fail_base () from /lib/i386-linux-gnu/i686/cmov/libc.so.6
#4  0xb7af6697 in __assert_fail () from /lib/i386-linux-gnu/i686/cmov/libc.so.6
#5  0x080fd7e9 in gc_finalize ()
#6  0x080fdaec in lj_gc_finalize_udata ()
#7  0x08104bfc in cpfinalize ()
#8  0x08120ff5 in lj_vm_cpcall ()
#9  0x08104fe1 in lua_close ()
#10 0x080bb42e in tarantool_lua_free () at /home/pmwkaa/dev/tarantool/src/lua/init.cc:488
#11 0x08062825 in tarantool_free () at /home/pmwkaa/dev/tarantool/src/tarantool.cc:496
#12 0xb7b00081 in __run_exit_handlers () from /lib/i386-linux-gnu/i686/cmov/libc.so.6
#13 0xb7b000dd in exit () from /lib/i386-linux-gnu/i686/cmov/libc.so.6
#14 0xb7ae8a6b in __libc_start_main () from /lib/i386-linux-gnu/i686/cmov/libc.so.6
#15 0x08061391 in _start ()
(gdb) quit
```

test code (press Ctrl+C to repeat)

```
print('test')

box.cfg{}

space = box.schema.create_space('test', { id = 101 })
index = space:create_index('primary')

require('fiber').create(function()
for key = 1, 1000000 do
    box.begin()
    space:replace({key, key})
    space:replace({key, key})
    space:replace({key, key})
    box.commit()
end
end)

require('console').start()
```

**Comment by kostja** [comment]
What's the difference between this bug an gh-728?

**Comment by pmwkaa** [comment]
gh-726 crashes on Ctrl+C during script run.
gh-728 crashes by executing lua statement (several attempts) from parallel admin console during script run.

**Comment by mejedi** [comment]
Presumable a718d469100a2992707c16cd251a56e5e5159be2   fixes this issue

**Comment by kostja** [comment]
Closing, should be fixed by now.
