### ISSUE TITLE
Crash and undefined behavior in transactions triggers on_commit /on_rollback

### ISSUE THREAD

**Issue by R-omk** [tarantool/tarantool#7331]
**Bug description**

Call `box.rollback() `  in  `on_commit` trigger lead to  

- vinyl:  Segmentation fault
- memtx: transaction is rolled back
- memtx + synhro:  transaction is not rolled back silently

---

* OS: Linux
* OS Version: ubutnu 20.04
* Architecture: amd64
* tarantool version: 2.10.0-0-g0a5ce0b9c

---

**Steps to reproduce**

run
`docker run -it --rm tarantool/tarantool:2.10.0-ubuntu`

execute in tnt console

```
s = box.schema.space.create('space1', { engine = 'vinyl' })
s:create_index('primary', {unique = true, parts = { {field = 1, type = 'unsigned'} }})
function c() box.rollback() end
box.begin();  s:insert{1,'C'}; box.on_commit(c);  box.commit();   
```
--- 

```
Segmentation fault
  code: SEGV_MAPERR
  addr: 0x48
  context: 0x7fb105dff580
  siginfo: 0x7fb105dff6b0
  rax      0x0                0
  rbx      0x7fb105c15258     140398282494552
  rcx      0x7fb105c15110     140398282494224
  rdx      0x7fb105c15258     140398282494552
  rsi      0x0                0
  rdi      0x0                0
  rsp      0x7fb105dffc30     140398284504112
  rbp      0x7fb105c15038     140398282494008
  r8       0x7fb105c15038     140398282494008
  r9       0x0                0
  r10      0x7fb105b244b0     140398281508016
  r11      0xfffffffffffffff7 -9
  r12      0x7fb105c15038     140398282494008
  r13      0x0                0
  r14      0x7fb1060ad3d8     140398287311832
  r15      0x5603f7dd5760     94575043368800
  rip      0x5603f7cde660     94575042356832
  eflags   0x10246            66118
  cs       0x33               51
  gs       0x0                0
  fs       0x0                0
  cr2      0x48               72
  err      0x4                4
  oldmask  0x0                0
  trapno   0xe                14
Current time: 1656498845
Please file a bug at http://github.com/tarantool/tarantool/issues
Attempting backtrace... Note: since the server has already crashed, 
this may fail as well
#1  0x5603f7e1b702 in crash_signal_cb+194
#2  0x7fb10819a420 in __restore_rt+0
#3  0x5603f7cde660 in vy_tx_rollback_statement+32
#4  0x5603f7d3f2fb in txn_rollback_one_stmt+43
#5  0x5603f7d40d83 in txn_complete_fail+147
#6  0x5603f7d41b28 in txn_rollback+104
#7  0x5603f7d42311 in box_txn_rollback+65
#8  0x5603f7dd576d in lbox_rollback+13
#9  0x5603f7e59813 in lj_BC_FUNCC+68
#10 0x5603f7e5e917 in lua_pcall+199
#11 0x5603f7e04c6f in luaT_call+15
#12 0x5603f7e00add in lbox_trigger_run+125
#13 0x5603f7e3a69a in trigger_run+42
#14 0x5603f7d40dbf in txn_complete_fail+207
#15 0x5603f7d41b28 in txn_rollback+104
#16 0x5603f7d42311 in box_txn_rollback+65
#17 0x5603f7dd576d in lbox_rollback+13
#18 0x5603f7e59813 in lj_BC_FUNCC+68
#19 0x5603f7e5e917 in lua_pcall+199
#20 0x5603f7e04c6f in luaT_call+15
#21 0x5603f7dfd649 in lua_main+89
#22 0x5603f7dfdac1 in run_script_f+1105
#23 0x5603f7c5c0d1 in fiber_cxx_invoke(int (*)(__va_list_tag*), __va_list_tag*)+17
#24 0x5603f7e22880 in fiber_loop+48
#25 0x5603f80bce38 in coro_in
```

**Expected behavior**

I don't know, but not a crash, the documentation should describe in detail the applicability of these triggers.

**Comment by locker** [comment]
Looks like [documented](https://www.tarantool.io/en/doc/latest/book/box/triggers/#triggers-box-triggers) undefined behavior:

![image](https://user-images.githubusercontent.com/1114511/176418891-11d4288c-1c3c-43de-8d48-e8ebe87efe3a.png)

**Comment by R-omk** [comment]
related https://github.com/tarantool/tarantool/issues/4264

**Comment by kyukhin** [comment]
This is documented UB, so consider it is not a bug.
