### ISSUE TITLE
Segmentation fault on msgpack decoding

### ISSUE THREAD

**Issue by ligurio** [tarantool/tarantool#7818]
**Bug description**

* OS: Linux
* OS Version: Ubuntu 22.04
* Architecture: amd64

`tarantool --version` output:

```
Tarantool 2.10.3-0-g8aca8a19a
Target: Linux-x86_64-RelWithDebInfo
Build options: cmake . -DCMAKE_INSTALL_PREFIX=/usr -DENABLE_BACKTRACE=ON
Compiler: /usr/bin/cc /usr/lib/ccache/g++
C_FLAGS:-g -O2 -ffile-prefix-map=/build/tarantool-2.10.3=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fexceptions -funwind-tables -fno-common -fopenmp -msse2 -Wformat -Wformat-security -Werror=format-security -fstack-protector-strong -fPIC -std=c11 -Wall -Wextra -Wno-strict-aliasing -Wno-char-subscripts -Wno-format-truncation -Wno-gnu-alignof-expression -fno-gnu89-inline -Wno-cast-function-type
CXX_FLAGS:-g -O2 -ffile-prefix-map=/build/tarantool-2.10.3=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fexceptions -funwind-tables -fno-common -fopenmp -msse2 -Wformat -Wformat-security -Werror=format-security -fstack-protector-strong -fPIC -std=c++11 -Wall -Wextra -Wno-strict-aliasing -Wno-char-subscripts -Wno-format-truncation -Wno-invalid-offsetof -Wno-gnu-alignof-expression -Wno-cast-function-type
```

**Steps to reproduce**

Prepare `decimal.lua`:

```lua
local msgpack = require("msgpack")
local testcase = io.open(arg[1]):read("*all")
msgpack.decode(testcase)
```

Download a file with input buffer - [crash-ae37d0fb877998dcd204acdb2e1823f2e8ba32b3.txt](https://github.com/tarantool/tarantool/files/9807819/crash-ae37d0fb877998dcd204acdb2e1823f2e8ba32b3.txt).

And run:

Just type `tarantool decimal.lua ./crash-ae37d0fb877998dcd204acdb2e1823f2e8ba32b3.txt
`.

**Actual behavior**

```
Segmentation fault             
  code: SEGV_MAPERR                                                   
  addr: 0x4024482a             
  context: 0x7f403a9ff6c0      
  siginfo: 0x7f403a9ff7f0       
  rax      0x40234840         1076054080
  rbx      0x4023482d         1076054061                         
  rcx      0x40234840         1076054080                            
  rdx      0x0                0
  rsi      0xfffe             65534      
  rdi      0x40234840         1076054080
  rsp      0x7f403a9ffd80     139913838198144
  rbp      0x40234840         1076054080
  r8       0x40234840         1076054080          
  r9       0x0                0                                       
  r10      0x40234840         1076054080
  r11      0x55c54ade6d68     94305853009256
  r12      0x7f403a9ffdb4     139913838198196
  r13      0x4024482a         1076119594
  r14      0x41bd4090         1102921872
  r15      0x55c54aa490a0     94305849217184                                                                                                
  rip      0x55c54acd5247     94305851888199
  eflags   0x10246            66118 
  cs       0x33               51
  gs       0x0                0  
  fs       0x0                0
  cr2      0x4024482a         1076119594
  err      0x4                4
  oldmask  0x0                0
  trapno   0xe                14
Current time: 1666079799
Please file a bug at http://github.com/tarantool/tarantool/issues
Attempting backtrace... Note: since the server has already crashed, 
this may fail as well
#1  0x55c54aa612af in crash_signal_cb+207
#2  0x7f403d12a520 in __sigaction+80
#3  0x55c54acd5247 in decPackedToNumber+39
#4  0x55c54aa81e35 in decimal_unpack+165
#5  0x55c54aa48c66 in luamp_decode.localalias+1430
#6  0x55c54aa48fa8 in lua_msgpack_decode_string+152
#7  0x55c54aa9f123 in lj_BC_FUNCC+70
#8  0x55c54aaa5d55 in lua_pcall+117 
#9  0x55c54aa4a3af in luaT_call+15
#10 0x55c54aa433e9 in lua_main+89
#11 0x55c54aa43893 in run_script_f+1155
#12 0x55c54a8d31a1 in fiber_cxx_invoke(int (*)(__va_list_tag*), __va_list_tag*)+17
#13 0x55c54aa6a75d in fiber_loop+61 
#14 0x55c54acdd18c in coro_init+76
Aborted (core dumped)
```

**Expected behavior**

`msgpack.decode()` raise a Lua error

**Additional information**

With tarantool built from a master branch (Tarantool 2.11.0-entrypoint-605-g98fcd437d9) crash looks an assert's condition violation:
```
tarantool: /home/sergeyb/sources/MRG/tarantool/src/lib/msgpuck/msgpuck.h:1722: uint32_t mp_decode_extl(const char **, int8_t *): Assertion `0' failed.
Aborted (core dumped)
```
msgpuck trying to decode msgpack extension type in `mp_decode_extl` and branch for unsupported types contains `mp_unreachable` macros with `assert(0)`. See https://github.com/tarantool/msgpuck/blob/0c6680a300e31714f475a7f90c2d95a02d001d80/msgpuck.h#L1722
It is debatable behavior and that's why I have created an issue about it.

**Comment by locker** [comment]
Caused by https://github.com/tarantool/msgpuck/issues/13
