### ISSUE TITLE
misc.memprof.start Segmentation fault

### ISSUE THREAD

**Issue by AMD-NICK** [tarantool/tarantool#7850]
_Текст issue на русском в самом низу этой Issue. Мой английский далек от идеала, использовал deepl для перевода_

---

**The `misc.memprof.start("filename.bin")` function crashes execution of the lua code. The error is attached at the bottom of Issue. Possibly it's caused by coroutines**

```
tarantool --version
Tarantool 2.10.3-4-g13a839e85
Target: Linux-x86_64-RelWithDebInfo
Build options: cmake . -DCMAKE_INSTALL_PREFIX=/usr/local -DENABLE_BACKTRACE=ON
Compiler: /usr/bin/cc /usr/bin/c++
C_FLAGS: -fexceptions -funwind-tables -fno-common -fopenmp -msse2 -Wformat -Wformat-security -Werror=format-security -fstack-protector-strong -fPIC -std=c11 -Wall -Wextra -Wno-strict-aliasing -Wno-char-subscripts -Wno-format-truncation -Wno-gnu-alignof-expression -fno-gnu89-inline -Wno-cast-function-type
CXX_FLAGS: -fexceptions -funwind-tables -fno-common -fopenmp -msse2 -Wformat -Wformat-security -Werror=format-security -fstack-protector-strong -fPIC -std=c++11 -Wall -Wextra -Wno-strict-aliasing -Wno-char-subscripts -Wno-format-truncation -Wno-invalid-offsetof -Wno-gnu-alignof-expression -Wno-cast-function-type
```

## Steps to reproduce

Run in any comfortable folder

```bash
git clone https://github.com/TRIGONIM/ggram.git

docker run --rm -it \
	-v $PWD/ggram:/opt/tarantool \
	-e LUA_PATH='/opt/tarantool/.rocks/share/tarantool/?.lua;/opt/tarantool/.rocks/share/tarantool/?/init.lua;/opt/tarantool/lua/?.lua;/opt/tarantool/lua/?/init.lua;./?.lua;./?/init.lua;;' \
	-e LUA_CPATH='/opt/tarantool/.rocks/lib/tarantool/?.so;;' \
	tarantool/tarantool sh

# dependencies for installing rocks
apk add gcc libc-dev

tarantoolctl rocks install copas
tarantoolctl rocks install lua-cjson
tarantoolctl rocks install luasec

# unload the integrated luasocket, so that the socket from the rocks can be loaded
# and start memprof
echo "package.loaded['socket'] = nil misc.memprof.start('prof.bin')" | cat - examples/echo.lua > temp && mv temp examples/echo.lua

tarantool examples/echo.lua
```

## Detailed description

I have a Telegram bot that runs on https://git.io/ggram and performs many asynchronous http requests, **using [copas](https://github.com/lunarmodules/copas)** to do so.

During this bot's work, it leaks memory, causing the `collectgarbage("count")` to grow to a gigabyte and more, which crashed normal LuaJit.

![screenshot_2022-10-26_06 00 20@2x](https://user-images.githubusercontent.com/9200174/197924649-9bcd7927-491d-42cf-982a-5156e04e86c3.png)

At first I found ujit (luavela), which has a built-in memory profiler, ran it while the application was running, got a dump, but my experience was not enough to figure out where the leak is.

Then I found Tarantool and succeeded to run my application on it (I had to deal with `export LUA_PATH='foobar'`, LUA_CPATH, `package.loaded["socket"] = nil`). With the code from [tarantool manual](https://www.tarantool.io/ru/doc/latest/reference/tooling/luajit_memprof/#profiler-usage-parse-command) the profiler works fine, but my code has a **Segmentation fault** when it runs. (The profiler from LuaVela (uJit) doesn't have this problem)

## My theories:

- I use luasocket from luarocks, having previously made `package.loaded["socket"] = nil` to unload integrated in tarantool, since it wouldn't let copas run (`socket.sourcet` and like `socket.gettime` were required). Maybe **profiler is using luasocket** somewhere?
- If I run the profiler, then run `require("ggram.core")`, it also crashes immediately. This might be the case, but.
- Even without `require("ggram.core")` the crash happens after `copas.loop()` (starts all coroutines). Maybe it's **the coroutines** that are the problem?
- Maybe the leak is somewhere in luasocket itself or in copas? But how do we know about it, if I can' t start profiler?

## Error

```
Segmentation fault
  code: SEGV_MAPERR
  addr: 0x278
  context: 0x7f42569fe640
  siginfo: 0x7f42569fe770
  rax      0x270              624
  rbx      0x7f42569ffcd0     139922897894608
  rcx      0x270              624
  rdx      0x7f4259321b90     139922941025168
  rsi      0x4ce98            315032
  rdi      0x131f0            78320
  rsp      0x7f42569fec00     139922897890304
  rbp      0x7f4256520010     139922892783632
  r8       0x0                0
  r9       0x1                1
  r10      0x2                2
  r11      0x7f4259080000     139922938265600
  r12      0x6c0              1728
  r13      0x7f42569ffd40     139922897894720
  r14      0x1b               27
  r15      0x2a21d0           2761168
  rip      0x56443dc68071     94851094184049
  eflags   0x10202            66050
  cs       0x33               51
  gs       0x0                0
  fs       0x0                0
  cr2      0x278              632
  err      0x4                4
  oldmask  0x0                0
  trapno   0xe                14
Current time: 1666759509
Please file a bug at http://github.com/tarantool/tarantool/issues
Attempting backtrace... Note: since the server has already crashed, 
this may fail as well
#1  0x56443dbffdac in crash_signal_cb+204
#2  0x7f425936bc8a in sigwaitinfo+8
Aborted (core dumped)
```

I'm sorry to bother you with not really Tarantool, but I really want to find a solution to the problem and I've tried so many things before I got to Tarantool. Unfortunately, the Tarantool dump parser does not work with LuaVela dumps (ujit), which could be a solution

# Оригинальный текст

<details>
  <summary> Оригинальный текст </summary>
  

**Функция `misc.memprof.start("filename.bin")` крашит выполнение lua кода. Ошибка прикреплена снизу Issue. Возможно, дело в корутинах**

```
tarantool --version
Tarantool 2.10.3-4-g13a839e85
Target: Linux-x86_64-RelWithDebInfo
Build options: cmake . -DCMAKE_INSTALL_PREFIX=/usr/local -DENABLE_BACKTRACE=ON
Compiler: /usr/bin/cc /usr/bin/c++
C_FLAGS: -fexceptions -funwind-tables -fno-common -fopenmp -msse2 -Wformat -Wformat-security -Werror=format-security -fstack-protector-strong -fPIC -std=c11 -Wall -Wextra -Wno-strict-aliasing -Wno-char-subscripts -Wno-format-truncation -Wno-gnu-alignof-expression -fno-gnu89-inline -Wno-cast-function-type
CXX_FLAGS: -fexceptions -funwind-tables -fno-common -fopenmp -msse2 -Wformat -Wformat-security -Werror=format-security -fstack-protector-strong -fPIC -std=c++11 -Wall -Wextra -Wno-strict-aliasing -Wno-char-subscripts -Wno-format-truncation -Wno-invalid-offsetof -Wno-gnu-alignof-expression -Wno-cast-function-type
```

## Steps to reproduce

Выполнять в любой удобной папке

```bash
git clone https://github.com/TRIGONIM/ggram.git

docker run --rm -it \
	-v $PWD/ggram:/opt/tarantool \
	-e LUA_PATH='/opt/tarantool/.rocks/share/tarantool/?.lua;/opt/tarantool/.rocks/share/tarantool/?/init.lua;/opt/tarantool/lua/?.lua;/opt/tarantool/lua/?/init.lua;./?.lua;./?/init.lua;;' \
	-e LUA_CPATH='/opt/tarantool/.rocks/lib/tarantool/?.so;;' \
	tarantool/tarantool sh

# dependencies for installing rocks
apk add gcc libc-dev

tarantoolctl rocks install copas
tarantoolctl rocks install lua-cjson
tarantoolctl rocks install luasec

# unload the integrated luasocket, so that the socket from the rocks can be loaded
# and start memprof
echo "package.loaded['socket'] = nil misc.memprof.start('prof.bin')" | cat - examples/echo.lua > temp && mv temp examples/echo.lua

tarantool examples/echo.lua
```

## Подробное описание

У меня есть Telegram бот, который работает на https://git.io/ggram и выполняет много асинхронных http запросов, **используя для этого [copas](https://github.com/lunarmodules/copas)**

В процессе работы бота происходит утечка памяти, в результате чего показатель `collectgarbage("count")` растет до гигабайта и более, что крашило обычный LuaJit. 

![screenshot_2022-10-26_06 00 20@2x](https://user-images.githubusercontent.com/9200174/197924649-9bcd7927-491d-42cf-982a-5156e04e86c3.png)

Сначала я нашел ujit (luavela), в котором есть встроенный профайлер памяти, запустил его во время работы приложения, получил дамп, но моего опыта не хватило, чтобы по нему понять, где происходит утечка.

Затем я нашел Tarantool и смог запустить свое приложение на нем (пришлось повозиться с `export LUA_PATH='foobar'`, LUA_CPATH, `package.loaded["socket"] = nil`). На коде из [руководства tarantool](https://www.tarantool.io/ru/doc/latest/reference/tooling/luajit_memprof/#profiler-usage-parse-command) профайлер работает отлично, но при запуске в моем коде происходит **Segmentation fault**. (В LuaVela (uJit) такой проблемы нет)

## Мои теории:

- Я использую luasocket с luarocks, при этом предварительно сделав `package.loaded["socket"] = nil`, чтобы выгрузить интегрированный в tarantool, так как он не давал запуститься copas (требовался `socket.sourcet` и вроде `socket.gettime`). Может быть, **профайлер где-то использует luasocket**?
- Если запустить профайлер, затем выполнить `require("ggram.core")`, то тоже сразу происходит краш. Возможно, дело в нем, но..
- Даже без `require("ggram.core")` краш происходит после `copas.loop()` (запускает все корутины). Возможно, **дело как раз в корутинах**?
- Может быть, утечка где-то в самом luasocket или в copas? Но как об этом узнать, если не получается запустить профайлер?

## Ошибка

```
Segmentation fault
  code: SEGV_MAPERR
  addr: 0x278
  context: 0x7f42569fe640
  siginfo: 0x7f42569fe770
  rax      0x270              624
  rbx      0x7f42569ffcd0     139922897894608
  rcx      0x270              624
  rdx      0x7f4259321b90     139922941025168
  rsi      0x4ce98            315032
  rdi      0x131f0            78320
  rsp      0x7f42569fec00     139922897890304
  rbp      0x7f4256520010     139922892783632
  r8       0x0                0
  r9       0x1                1
  r10      0x2                2
  r11      0x7f4259080000     139922938265600
  r12      0x6c0              1728
  r13      0x7f42569ffd40     139922897894720
  r14      0x1b               27
  r15      0x2a21d0           2761168
  rip      0x56443dc68071     94851094184049
  eflags   0x10202            66050
  cs       0x33               51
  gs       0x0                0
  fs       0x0                0
  cr2      0x278              632
  err      0x4                4
  oldmask  0x0                0
  trapno   0xe                14
Current time: 1666759509
Please file a bug at http://github.com/tarantool/tarantool/issues
Attempting backtrace... Note: since the server has already crashed, 
this may fail as well
#1  0x56443dbffdac in crash_signal_cb+204
#2  0x7f425936bc8a in sigwaitinfo+8
Aborted (core dumped)
```

Простите, что беспокою не совсем по теме Tarantool, но мне действительно очень хочется найти решение проблемы и я перепробовал уже очень много всего, пока добрался до Tarantool. К сожалению, парсер дампов Tarantool не работает с дампами LuaVela (ujit), что могло бы быть решением

</details>

**Comment by AMD-NICK** [comment]
linking: https://github.com/tarantool/tarantool/issues/5442

**Comment by NickVolynkin** [comment]
@AMD-NICK I've proofread your English text a little. Thanks for a well-written issue. :)

**Comment by AMD-NICK** [comment]
> you don't even need Tarantool — our [LuaJIT fork](https://github.com/tarantool/luajit) will suit you well

yeah, it works fine. Thanks. I think I even found the cause of the memory leak using your tool. But memprof generates hundreds of megabytes of data every second. This is sad, but not critical in my case.
