### ISSUE TITLE
LuaJIT crashes on OOM at trace exit

### ISSUE THREAD

**Issue by CuriousGeorgiy** [tarantool/tarantool#7956]
# Core dump collected by `tarabrt.sh`
https://drive.google.com/file/d/1FWvy1dE26Ly2PGAgk7i1n8k5Ru9M9Fhp/view?usp=sharing

# Steps to reproduce
1. Take snapshot from https://www.notion.so/tarantool/Vinyl-Customization-for-business-requirements-0fbced0af1bc4b7997edb733e8d90c61#b8e3a89df2384345928510f64b6d80dd
2. Call `generate_get_dataset` many times (it took me around 10 times) until Tarantool crashes instead of returning an OOM error:
```lua
function generate_get_dataset()
    local fh = fio.open('get_dataset.json', {'O_CREAT', 'O_WRONLY'}, {'S_IRUSR', 'S_IWUSR'})
    assert(fh ~= nil)

    fh:write(json.encode(box.space.storage_Stock:select({}, {limit = 11598485})))
end
```

# Console output
```console
tarantool> generate_get_dataset()
2022-11-19 13:46:14.286 [136429] main/103/init_core_raw.lua C> Potentially long select from space 'storage_Stock' (548)
 stack traceback:
	builtin/box/schema.lua:2382: in function 'check_select_safety'
	builtin/box/schema.lua:2421: in function 'select'
	init_core_raw.lua:36: in function <init_core_raw.lua:32>
	[C]: in function 'pcall'
	builtin/box/console.lua:404: in function 'eval'
	builtin/box/console.lua:710: in function 'repl'
	builtin/box/console.lua:759: in function 'start'
	init_core_raw.lua:42: in main chunk
2022-11-19 13:47:26.905 [136429] main/103/init_core_raw.lua backtrace.c:257 E> unwinding error: `get_proc_name` accessor failed: unspecified (general) error
Segmentation fault
  code: SEGV_MAPERR
  addr: 0x3e7ee617
  context: 0x7f48791fe580
  siginfo: 0x7f48791fe6b0
  rax      0x7f48791ff800     139949246511104
  rbx      0x4c55414a49543204 5500374307216568836
  rcx      0x7f487995a970     139949254224240
  rdx      0x0                0
  rsi      0x7f48791ff800     139949246511104
  rdi      0x3e7ee5e7         1048503783
  rsp      0x7f48791ff250     139949246509648
  rbp      0x7f48791ff3b0     139949246510000
  r8       0x7f48791ff3b0     139949246510000
  r9       0x0                0
  r10      0x1da62010         497426448
  r11      0x41228b00         1092782848
  r12      0x3                3
  r13      0x7f487995a970     139949254224240
  r14      0x1                1
  r15      0x3e7ee5e7         1048503783
  rip      0x5566510965c9     93897934595529
  eflags   0x10206            66054
  cs       0x33               51
  gs       0x0                0
  fs       0x0                0
  cr2      0x3e7ee617         1048503831
  err      0x4                4
  oldmask  0x0                0
  trapno   0xe                14
Current time: 1668865646
Please file a bug at http://github.com/tarantool/tarantool/issues
Attempting backtrace... Note: since the server has already crashed,
this may fail as well
#1  0x55665104f1c6 in crash_signal_cb+198
#2  0x7f487b98c520 in __sigaction+80
#3  0x5566510965c9 in err_unwind+9
#4  0x5566510969ba in lj_err_unwind_dwarf+234
#5  0x7f487bb89167 in _Unwind_RaiseException+343
#6  0x55665109686b in lj_err_throw+91
#7  0x556651096aab in lj_err_mem+59
#8  0x556651098fec in lj_mem_realloc+108
#9  0x5566510a10fb in lj_tab_resize+507
#10 0x556651098a8e in gc_onestep+1438
#11 0x556651098c7c in lj_gc_step+92
#12 0x5566510d5e8d in lj_trace_exit+845
#13 0x55665108e478 in lj_vm_exit_handler+225
#14 0x829082908290829 in ??+0
Aborted (core dumped)
```

**Comment by kyukhin** [comment]
Closing as duplicate.
