### ISSUE TITLE
cpipe is not ready when relay is already 'RELAY_FOLLOW'

### ISSUE THREAD

**Issue by sergos** [tarantool/tarantool#7991]
Found as one of the reasons for `replication-luatest/linearizable_test.lua` fail - just run it gadzillion times.
The backtrace is:
```C
Thread 1 (Thread 0x7efe95209b80 (LWP 51431)):
#0  __GI_raise (sig=sig@entry=0x6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007efe926b17f1 in __GI_abort () at abort.c:79
#2  0x00007efe926a13fa in __assert_fail_base (fmt=0x7efe928286c0 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=assertion@entry=0x558f13443550 "loop() == pipe->producer", file=file@entry=0x558f13443528 "/workspaces/t.qa277/src/lib/core/cbus.h", line=line@entry=0xe0, function=function@entry=0x558f13443830 <__PRETTY_FUNCTION__.7330> "cpipe_push_input") at assert.c:92
#3  0x00007efe926a1472 in __GI___assert_fail (assertion=0x558f13443550 "loop() == pipe->producer", file=0x558f13443528 "/workspaces/t.qa277/src/lib/core/cbus.h", line=0xe0, function=0x558f13443830 <__PRETTY_FUNCTION__.7330> "cpipe_push_input") at assert.c:101
#4  0x0000558f12f8d537 in cpipe_push_input (pipe=0x558f14788d18, msg=0x558f14861370) at ./src/lib/core/cbus.h:224
#5  0x0000558f12f8d5b8 in cpipe_push (pipe=0x558f14788d18, msg=0x558f14861370) at ./src/lib/core/cbus.h:241
#6  0x0000558f12f90231 in cbus_call_timeout (callee=0x558f14788d18, caller=0x558f14788cb8, msg=0x558f14861370, func=0x558f12e64367 <relay_trigger_vclock_sync_f(cbus_call_msg*)>, free_cb=0x558f12e64348 <relay_trigger_vclock_sync_msg_free(cbus_call_msg*)>, timeout=0.099816612899303436) at ./src/lib/core/cbus.c:432
#7  0x0000558f12e644d4 in relay_trigger_vclock_sync (relay=0x558f14787ec0, vclock_sync=0x7efe903ff620, deadline=54520571.198392823) at ./src/box/relay.cc:891
#8  0x0000558f12e37b28 in box_collect_confirmed_vclock (confirmed_vclock=0x7efe903ff780, deadline=54520571.198392823) at ./src/box/box.cc:1945
#9  0x0000558f12e38198 in box_wait_linearization_point (timeout=0.10000000000000001) at ./src/box/box.cc:2040
#10 0x0000558f12e258d2 in txn_make_linearizable (txn=0x7efe90425038) at ./src/box/txn.c:1413
#11 0x0000558f12e25d92 in box_txn_set_isolation (level=0x4) at ./src/box/txn.c:1468
#12 0x0000558f12f3354e in lbox_txn_set_isolation (L=0x417ac458) at ./src/box/lua/misc.cc:279
#13 0x0000558f12fdc727 in lj_BC_FUNCC () at buildvm_x86.dasc:811
#14 0x0000558f12fdf5fd in jit_secure_call (L=0x417ac458, base=0x40d5c170, nres=0x0) at ./third_party/luajit/src/lj_api.c:88
#15 0x0000558f12fe70ec in lua_call (L=0x417ac458, nargs=0x1, nresults=0xffffffff) at ./third_party/luajit/src/lj_api.c:1138
#16 0x0000558f12f1f19d in execute_lua_eval (L=0x417ac458) at ./src/box/lua/call.c:433
#17 0x0000558f12fdc727 in lj_BC_FUNCC () at buildvm_x86.dasc:811
#18 0x0000558f12fe743f in lua_pcall (L=0x417ac458, nargs=0x1, nresults=0xffffffff, errfunc=0x0) at ./third_party/luajit/src/lj_api.c:1163
#19 0x0000558f12f5de75 in luaT_call (L=0x417ac458, nargs=0x1, nreturns=0xffffffff) at ./src/lua/utils.c:497
#20 0x0000558f12f1fb11 in box_process_lua (handler=HANDLER_EVAL, ctx=0x7efe903ffc80, ret=0x7efe903ffe10) at ./src/box/lua/call.c:644
#21 0x0000558f12f1fcc4 in box_lua_eval (expr=0x7efe7602403e "        local dump, args = ...\n        local fn = loadstring(dump)\n        if args == nil then\n", ' ' <repeats 12 times>, "return pcall(fn)\n        else\n", ' ' <repeats 12 times>, "return pcall(fn, unpack(args))\n        end\n    !\221\332\002"..., expr_len=0xc4, args=0x7efe903ffce0, ret=0x7efe903ffe10) at ./src/box/lua/call.c:690
#22 0x0000558f12e76a13 in box_process_eval (request=0x7efe760106d8, port=0x7efe903ffe10) at ./src/box/call.c:199
#23 0x0000558f12d206fc in tx_process_call (m=0x7efe76010650) at ./src/box/iproto.cc:2158
#24 0x0000558f12f8ffe2 in cmsg_deliver (msg=0x7efe76010650) at ./src/lib/core/cbus.c:375
#25 0x0000558f12f91158 in fiber_pool_f (ap=0x7efe90401850) at ./src/lib/core/fiber_pool.c:64
#26 0x0000558f12d1492d in fiber_cxx_invoke(fiber_func, typedef __va_list_tag __va_list_tag *) (f=0x558f12f90f29 <fiber_pool_f>, ap=0x7efe90401850) at ./src/lib/core/fiber.h:1175
#27 0x0000558f12f882b7 in fiber_loop (data=0x0) at ./src/lib/core/fiber.c:912
#28 0x0000558f132e7cbf in coro_init () at ./third_party/coro/coro.c:108
```

It can happen that the relevant relay thread is informative too:
```C
Thread 3 (Thread 0x7efe673fe700 (LWP 55925)):
#0  __memset_avx2_erms () at ../sysdeps/x86_64/multiarch/memset-vec-unaligned-erms.S:145
#1  0x0000558f132bd8ad in slab_poison (slab=0x7efe66400000) at ./src/lib/small/small/slab_cache.c:113
#2  0x0000558f132bde62 in slab_get_with_order (cache=0x558f14788050, order=0x4) at ./src/lib/small/small/slab_cache.c:240
#3  0x0000558f132c3079 in mempool_alloc (pool=0x558f14787fe0) at ./src/lib/small/small/mempool.c:197
#4  0x0000558f12f88df7 in fiber_new_ex (name=0x558f13442dce "main", fiber_attr=0x558f134426a0 <fiber_attr_default>, f=0x558f12e64509 <relay_subscribe_f(typedef __va_list_tag __va_list_tag *)>) at ./src/lib/core/fiber.c:1229
#5  0x0000558f12f89128 in fiber_new (name=0x558f13442dce "main", f=0x558f12e64509 <relay_subscribe_f(typedef __va_list_tag __va_list_tag *)>) at ./src/lib/core/fiber.c:1288
#6  0x0000558f12f8bf26 in cord_costart_thread_func (arg=0x558f147e36e0) at ./src/lib/core/fiber.c:1799
#7  0x0000558f12f8ae9e in cord_thread_func (p=0x7efe900ff790) at ./src/lib/core/fiber.c:1619
#8  0x00007efe9366f6db in start_thread (arg=0x7efe673fe700) at pthread_create.c:463
#9  0x00007efe9279261f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

**Comment by sergos** [comment]
Relevant to tarantool/tarantool-qa#277

**Comment by sergepetrenko** [comment]
The issue is only present in 2.11 and later, because it's caused by 70bf99c8331482be4aeb105c11ef2d2c606982ea.
