### ISSUE TITLE
Yielding in a trigger results in a segfault

### ISSUE THREAD

**Issue by msiomkin** [tarantool/tarantool#8027]
**Bug description**

Yielding in a trigger results in a segfault.

* OS: Linux
* OS Version: Centos 8
* Architecture: amd64

```
Tarantool 2.4.3-1-g986fab717
Target: Linux-x86_64-RelWithDebInfo
Build options: cmake . -DCMAKE_INSTALL_PREFIX=/usr/local -DENABLE_BACKTRACE=ON
Compiler: /usr/lib64/ccache/cc /usr/lib64/ccache/c++
C_FLAGS: -fexceptions -funwind-tables -fno-omit-frame-pointer -fno-stack-protector -fno-common -fopenmp -msse2 -std=c11 -Wall -Wextra -Wno-strict-aliasing -Wno-char-subscripts -Wno-format-truncation -Wno-gnu-alignof-expression -fno-gnu89-inline -Wno-cast-function-type
CXX_FLAGS: -fexceptions -funwind-tables -fno-omit-frame-pointer -fno-stack-protector -fno-common -fopenmp -msse2 -std=c++11 -Wall -Wextra -Wno-strict-aliasing -Wno-char-subscripts -Wno-format-truncation -Wno-invalid-offsetof -Wno-gnu-alignof-expression -Wno-cast-function-type
```

**Steps to reproduce**

Run the following script:

```Lua
#!/usr/bin/env tarantool

local log = require("log")
local fiber = require("fiber")

box.cfg{}

local test = box.space.test
if test ~= nil then
    test:drop()
end

test = box.schema.create_space("test", {
    format = {
        { name = "id", type = "unsigned" },
        { name = "col1", type = "string" }
    }
})

test:create_index("primary")

test:before_replace(function(old, new)
    log.info(new)

    fiber.yield()

    return new
end)

test:insert({ 1, "qqq1" })
test:insert({ 2, "qqq2" })

os.exit()
```

**Actual behavior**

```
Segmentation fault
  code: SEGV_MAPERR
  addr: 0x18
  context: 0x7efc041ff640
  siginfo: 0x7efc041ff770
  rax      0x2                2
  rbx      0x3                3
  rcx      0x369              873
  rdx      0x369              873
  rsi      0x3                3
  rdi      0x40951378         1083511672
  rsp      0x7efc041ffbd0     139620866063312
  rbp      0x7efc041ffbf0     139620866063344
  r8       0x1                1
  r9       0x7efc04000400     139620863968256
  r10      0x27e2b60          41823072
  r11      0x0                0
  r12      0x40951378         1083511672
  r13      0x0                0
  r14      0x7efc0402c070     139620864147568
  r15      0x7efc04015038     139620864053304
  rip      0x50d144           5296452
  eflags   0x10202            66050
  cs       0x33               51
  gs       0x0                0
  fs       0x0                0
  cr2      0x18               24
  err      0x4                4
  oldmask  0x0                0
  trapno   0xe                14
Current time: 1669523079
Please file a bug at http://github.com/tarantool/tarantool/issues
Attempting backtrace... Note: since the server has already crashed,
this may fail as well
#0  0x543b39 in print_backtrace+9
#1  0x41a49d in _ZL12sig_fatal_cbiP9siginfo_tPv+bd
#2  0x7efc05ab6ce0 in funlockfile+50
#3  0x50d144 in _ZL17lbox_pop_txn_stmtP9lua_StateiPv+64
#4  0x523fd6 in lbox_trigger_run+a6
#5  0x556432 in trigger_run+32
#6  0x4b0ced in space_execute_dml+31d
#7  0x4da834 in box_process_rw+114
#8  0x4de50d in box_insert+3d
#9  0x50cfe0 in lbox_insert+80
#10 0x5683b7 in lj_BC_FUNCC+34
#11 0x579d62 in lua_pcall+82
#12 0x528153 in luaT_call+13
#13 0x520b79 in lua_main+59
#14 0x520fe3 in run_script_f+453
#15 0x419e6c in _ZL16fiber_cxx_invokePFiP13__va_list_tagES0_+c
#16 0x540070 in fiber_loop+30
#17 0x704fff in coro_init+3f
Aborted (core dumped)
```

**Expected behavior**

Something like:

```
2022-12-08 14:04:45.656 [73745] main/103/run.lua txn.c:705 E> ER_TRANSACTION_YIELD: Transaction has been aborted by a fiber yield
2022-12-08 14:04:45.657 [73745] main txn.c:705 E> ER_TRANSACTION_YIELD: Transaction has been aborted by a fiber yield
```

**Comment by Gumix** [comment]
Tarantool 2.11.0:
```
Thread 1 "tarantool" received signal SIGSEGV, Segmentation fault.
0x00005555557b5709 in lbox_pop_txn_stmt_and_check_format (L=0x40000378, nret=1, event=0x7ffff4c30038) at ./src/box/lua/space.cc:119
119             struct tuple *tuple = stmt->new_tuple;

(gdb) p stmt
$1 = (txn_stmt *) 0x0

(gdb) bt
#0  0x00005555557b5709 in lbox_pop_txn_stmt_and_check_format (L=0x40000378, nret=1, event=0x7ffff4c30038) at ./src/box/lua/space.cc:119
#1  0x00005555557e09b0 in lbox_trigger_run (ptr=0x555556017fa0, event=0x7ffff4c30038) at ./src/lua/trigger.c:114
#2  0x0000555555835804 in trigger_run_list (list=0x7ffff4dff9d0, event=0x7ffff4c30038) at ./src/lib/core/trigger.cc:119
#3  0x00005555558358d4 in trigger_run (list=0x555555f11fc0, event=0x7ffff4c30038) at ./src/lib/core/trigger.cc:152
#4  0x000055555566f774 in space_before_replace (space=0x555555f11f30, txn=0x7ffff4c30038, request=0x7ffff4dffc30) at ./src/box/space.c:635
#5  0x000055555566fb3e in space_execute_dml (space=0x555555f11f30, txn=0x7ffff4c30038, request=0x7ffff4dffc30, result=0x7ffff4dffba8)
```
