### ISSUE TITLE
Assertion failed: (pm_atomic_load(&cord_count) == 0), function fiber_free, file fiber.c, line 2036

### ISSUE THREAD

**Issue by sergepetrenko** [tarantool/tarantool#8082]
Caught while running the tests on Tarantool 2.11.0-entrypoint-805-g5493db7c7 with some additional patches. 
I'm not sure if the failure was induced by my changes or not, but still paste the output here for reference.
At first glance, my changes were unrelated to fiber cleanup or cord creation.

```
[008] replication/replicaset_ro_mostly.test.lua       memtx           
[008] 
[008] [Instance "replica_uuid_ro1" killed by signal: 6 (SIGABRT)]
[008] 
[008] Last 15 lines of Tarantool Log file [Instance "replica_uuid_ro1"][/tmp/t/008_replication/replica_uuid_ro1.log]:
[008] 2022-12-20 17:27:51.568 [94744] main/112/main I> subscribed replica 16d31a86-20f1-4654-b135-772898d319be at fd 24, aka unix/:/private/tmp/t/008_replication/replica_uuid_ro1.sock, peer of unix/:(socket)
[008] 2022-12-20 17:27:51.568 [94744] main/112/main I> remote vclock {1: 10} local vclock {1: 10}
[008] 2022-12-20 17:27:51.570 [94744] relay/unix/:(socket)/101/main I> recover from `/tmp/t/008_replication/replica_uuid_ro1/00000000000000000000.xlog'
[008] 2022-12-20 17:27:52.124 [94744] main/114/applier/cluster@unix/:/private/tmp/t/008_replication/replica_uuid_ro2.sock I> authenticated
[008] 2022-12-20 17:27:52.125 [94744] main/114/applier/cluster@unix/:/private/tmp/t/008_replication/replica_uuid_ro2.sock I> subscribed
[008] 2022-12-20 17:27:52.125 [94744] main/114/applier/cluster@unix/:/private/tmp/t/008_replication/replica_uuid_ro2.sock I> remote vclock {1: 10} local vclock {1: 10}
[008] 2022-12-20 17:27:52.125 [94744] main/114/applier/cluster@unix/:/private/tmp/t/008_replication/replica_uuid_ro2.sock I> RAFT: message {term: 1, state: follower} from 2
[008] 2022-12-20 17:27:52.128 [94744] main/114/applier/cluster@unix/:/private/tmp/t/008_replication/replica_uuid_ro2.sock I> leaving orphan mode
[008] 2022-12-20 17:27:52.816 [94744] main/179/main I> joining replica 4353153e-4195-423c-a89c-1011f48cd8e7 at fd 29, aka unix/:/private/tmp/t/008_replication/replica_uuid_ro1.sock, peer of unix/:(socket)
[008] 2022-12-20 17:27:52.960 [94744] main/179/main I> initial data sent.
[008] 2022-12-20 17:27:52.960 [94744] main/179/main I> assigned id 3 to replica 4353153e-4195-423c-a89c-1011f48cd8e7
[008] 2022-12-20 17:27:52.961 [94744] main/179/main I> update replication_synchro_quorum = 2
[008] 2022-12-20 17:27:52.994 [94744] main C> got signal 15 - Terminated: 15
[008] 2022-12-20 17:27:52.994 [94744] main/233/iproto.shutdown I> tx_binary: stopped
[008] Assertion failed: (pm_atomic_load(&cord_count) == 0), function fiber_free, file fiber.c, line 2036
[008] 
[008] Test.run() received the following error:
[008] Traceback (most recent call last):
[008]   File "/Users/s.petrenko/Source/sptnt/test-run/lib/test.py", line 195, in run
[008]     self.execute(server)
[008]   File "/Users/s.petrenko/Source/sptnt/test-run/lib/tarantool_server.py", line 390, in execute
[008]     ts.stop_nondefault(signal=signal.SIGKILL)
[008]   File "/Users/s.petrenko/Source/sptnt/test-run/lib/preprocessor.py", line 441, in stop_nondefault
[008]     for k, v in self.servers.items():
[008] RuntimeError: dictionary changed size during iteration
[008] 
[008] [ fail ]

```

Here are <details><summary>full replica_uuid_ro1 logs</summary>

```
Starting instance replica_uuid_ro1...
started
Run console at unix/:/tmp/t/008_replication/replica_uuid_ro1.control
started
mkdir /tmp/t/008_replication/replica_uuid_ro1
'strip_core' is set but unsupported
2022-12-20 17:27:49.844 [94744] main/103/replica_uuid_ro1 I> Tarantool 2.11.0-entrypoint-820-g16b42228c
2022-12-20 17:27:49.846 [94744] main/103/replica_uuid_ro1 I> log level 5
2022-12-20 17:27:49.846 [94744] main/103/replica_uuid_ro1 I> wal/engine cleanup is paused
2022-12-20 17:27:49.850 [94744] main/103/replica_uuid_ro1 I> mapping 268435456 bytes for memtx tuple arena...
2022-12-20 17:27:49.850 [94744] main/103/replica_uuid_ro1 I> Actual slab_alloc_factor calculated on the basis of desired slab_alloc_factor = 1.044274
2022-12-20 17:27:49.850 [94744] main/103/replica_uuid_ro1 I> mapping 134217728 bytes for vinyl tuple arena...
2022-12-20 17:27:49.866 [94744] main/103/replica_uuid_ro1 I> update replication_synchro_quorum = 1
2022-12-20 17:27:49.866 [94744] main/103/replica_uuid_ro1 I> instance uuid e684ab64-158d-4a1c-9784-fafa0452c555
2022-12-20 17:27:49.867 [94744] main/103/replica_uuid_ro1 I> tx_binary: bound to unix/:/private/tmp/t/008_replication/replica_uuid_ro1.sock
2022-12-20 17:27:49.867 [94744] main/103/replica_uuid_ro1 I> connecting to 2 replicas
2022-12-20 17:27:49.868 [94744] main/114/applier/cluster@unix/:/private/tmp/t/008_replication/replica_uuid_ro2.sock I> can't connect to master
2022-12-20 17:27:49.868 [94744] main/114/applier/cluster@unix/:/private/tmp/t/008_replication/replica_uuid_ro2.sock sio.c:210 E> SocketError: connect to unix/:/private/tmp/t/008_replication/replica_uuid_ro2.sock, called on fd 25, aka unix/:(socket): No such file or directory
2022-12-20 17:27:49.868 [94744] main/114/applier/cluster@unix/:/private/tmp/t/008_replication/replica_uuid_ro2.sock I> will retry every 1.00 second
2022-12-20 17:27:49.872 [94744] main/113/applier/cluster@unix/:/private/tmp/t/008_replication/replica_uuid_ro1.sock I> remote master e684ab64-158d-4a1c-9784-fafa0452c555 at unix/:/private/tmp/t/008_replication/replica_uuid_ro1.sock running Tarantool 2.11.0
2022-12-20 17:27:50.867 [94744] main/114/applier/cluster@unix/:/private/tmp/t/008_replication/replica_uuid_ro2.sock I> remote master 16d31a86-20f1-4654-b135-772898d319be at unix/:/private/tmp/t/008_replication/replica_uuid_ro2.sock running Tarantool 2.11.0
2022-12-20 17:27:50.868 [94744] main/103/replica_uuid_ro1 I> connected to 2 replicas
2022-12-20 17:27:50.868 [94744] main/103/replica_uuid_ro1 I> Checking if 16d31a86-20f1-4654-b135-772898d319be at cluster@unix/:/private/tmp/t/008_replication/replica_uuid_ro2.sock chose this instance as bootstrap leader
2022-12-20 17:27:50.868 [94744] main/103/replica_uuid_ro1 I> Checking if e684ab64-158d-4a1c-9784-fafa0452c555 at cluster@unix/:/private/tmp/t/008_replication/replica_uuid_ro1.sock chose this instance as bootstrap leader
2022-12-20 17:27:50.868 [94744] main/103/replica_uuid_ro1 I> initializing an empty data directory
2022-12-20 17:27:51.112 [94744] main/103/replica_uuid_ro1 I> assigned id 1 to replica e684ab64-158d-4a1c-9784-fafa0452c555
2022-12-20 17:27:51.112 [94744] main/103/replica_uuid_ro1 I> update replication_synchro_quorum = 1
2022-12-20 17:27:51.113 [94744] main/103/replica_uuid_ro1 I> cluster uuid c555db93-0ebb-444d-be07-360c9c8e01ee
2022-12-20 17:27:51.116 [94744] snapshot/101/main I> saving snapshot `/tmp/t/008_replication/replica_uuid_ro1/00000000000000000000.snap.inprogress'
2022-12-20 17:27:51.122 [94744] snapshot/101/main I> done
2022-12-20 17:27:51.123 [94744] main/103/replica_uuid_ro1 I> ready to accept requests
2022-12-20 17:27:51.123 [94744] main/107/gc I> wal/engine cleanup is resumed
2022-12-20 17:27:51.123 [94744] main/115/applier_ballot_watcher I> fiber `applier_ballot_watcher' has been cancelled
2022-12-20 17:27:51.123 [94744] main/115/applier_ballot_watcher I> fiber `applier_ballot_watcher': exiting
2022-12-20 17:27:51.124 [94744] main/114/applier/cluster@unix/:/private/tmp/t/008_replication/replica_uuid_ro2.sock I> failed to authenticate
2022-12-20 17:27:51.124 [94744] main/114/applier/cluster@unix/:/private/tmp/t/008_replication/replica_uuid_ro2.sock box.cc:3335 E> ER_LOADING: Instance bootstrap hasn't finished yet
2022-12-20 17:27:51.124 [94744] main/114/applier/cluster@unix/:/private/tmp/t/008_replication/replica_uuid_ro2.sock I> will retry every 1.00 second
2022-12-20 17:27:51.124 [94744] main/146/applier_ballot_watcher I> fiber `applier_ballot_watcher' has been cancelled
2022-12-20 17:27:51.124 [94744] main/146/applier_ballot_watcher I> fiber `applier_ballot_watcher': exiting
2022-12-20 17:27:51.124 [94744] main/103/replica_uuid_ro1/box.load_cfg I> set 'replication_sync_timeout' configuration option to 100
2022-12-20 17:27:51.124 [94744] main/103/replica_uuid_ro1/box.load_cfg I> set 'log' configuration option to "\/tmp\/t\/008_replication\/replica_uuid_ro1.log"
2022-12-20 17:27:51.124 [94744] main/103/replica_uuid_ro1/box.load_cfg I> set 'replication' configuration option to ["cluster@unix\/:\/private\/tmp\/t\/008_replication\/replica_uuid_ro1.sock","cluster@unix\/:\/private\/tmp\/t\/008_replication\/replica_uuid_ro2.sock"]
2022-12-20 17:27:51.124 [94744] main/103/replica_uuid_ro1/box.load_cfg I> set 'listen' configuration option to "\/private\/tmp\/t\/008_replication\/replica_uuid_ro1.sock"
2022-12-20 17:27:51.124 [94744] main/103/replica_uuid_ro1/box.load_cfg I> set 'instance_uuid' configuration option to "e684ab64-158d-4a1c-9784-fafa0452c555"
2022-12-20 17:27:51.125 [94744] main/108/checkpoint_daemon I> scheduled next checkpoint for Tue Dec 20 19:27:11 2022
2022-12-20 17:27:51.167 [94744] main I> entering the event loop
2022-12-20 17:27:51.390 [94744] main/112/main I> joining replica 16d31a86-20f1-4654-b135-772898d319be at fd 24, aka unix/:/private/tmp/t/008_replication/replica_uuid_ro1.sock, peer of unix/:(socket)
2022-12-20 17:27:51.448 [94744] main/112/main I> initial data sent.
2022-12-20 17:27:51.448 [94744] main/112/main I> assigned id 2 to replica 16d31a86-20f1-4654-b135-772898d319be
2022-12-20 17:27:51.448 [94744] main/112/main I> update replication_synchro_quorum = 2
2022-12-20 17:27:51.448 [94744] main/112/main I> RAFT: fencing paused
2022-12-20 17:27:51.553 [94744] relay/unix/:(socket)/101/main I> recover from `/tmp/t/008_replication/replica_uuid_ro1/00000000000000000000.xlog'
2022-12-20 17:27:51.554 [94744] main/112/main I> final data sent.
2022-12-20 17:27:51.568 [94744] main/112/main I> subscribed replica 16d31a86-20f1-4654-b135-772898d319be at fd 24, aka unix/:/private/tmp/t/008_replication/replica_uuid_ro1.sock, peer of unix/:(socket)
2022-12-20 17:27:51.568 [94744] main/112/main I> remote vclock {1: 10} local vclock {1: 10}
2022-12-20 17:27:51.570 [94744] relay/unix/:(socket)/101/main I> recover from `/tmp/t/008_replication/replica_uuid_ro1/00000000000000000000.xlog'
2022-12-20 17:27:52.124 [94744] main/114/applier/cluster@unix/:/private/tmp/t/008_replication/replica_uuid_ro2.sock I> authenticated
2022-12-20 17:27:52.125 [94744] main/114/applier/cluster@unix/:/private/tmp/t/008_replication/replica_uuid_ro2.sock I> subscribed
2022-12-20 17:27:52.125 [94744] main/114/applier/cluster@unix/:/private/tmp/t/008_replication/replica_uuid_ro2.sock I> remote vclock {1: 10} local vclock {1: 10}
2022-12-20 17:27:52.125 [94744] main/114/applier/cluster@unix/:/private/tmp/t/008_replication/replica_uuid_ro2.sock I> RAFT: message {term: 1, state: follower} from 2
2022-12-20 17:27:52.128 [94744] main/114/applier/cluster@unix/:/private/tmp/t/008_replication/replica_uuid_ro2.sock I> leaving orphan mode
2022-12-20 17:27:52.816 [94744] main/179/main I> joining replica 4353153e-4195-423c-a89c-1011f48cd8e7 at fd 29, aka unix/:/private/tmp/t/008_replication/replica_uuid_ro1.sock, peer of unix/:(socket)
2022-12-20 17:27:52.960 [94744] main/179/main I> initial data sent.
2022-12-20 17:27:52.960 [94744] main/179/main I> assigned id 3 to replica 4353153e-4195-423c-a89c-1011f48cd8e7
2022-12-20 17:27:52.961 [94744] main/179/main I> update replication_synchro_quorum = 2
2022-12-20 17:27:52.994 [94744] main C> got signal 15 - Terminated: 15
2022-12-20 17:27:52.994 [94744] main/233/iproto.shutdown I> tx_binary: stopped
Assertion failed: (pm_atomic_load(&cord_count) == 0), function fiber_free, file fiber.c, line 2036.
```

</details>

**Comment by sergepetrenko** [comment]
Reproduced on latest master with no patches on top: 2.11.0-entrypoint-818-g1c80ce2d6

Just run `./test-run.py $(yes replicaset_ro_mostly | head -n 100)` and observe.

**Comment by Gerold103** [comment]
This means we exit without terminating at least one thread first.

**Comment by sergepetrenko** [comment]
The issue is with `relay_final_join` threads. We do not wait for their completion when tarantool is exiting.

Reproduced by @sergos when printing out where the counter is incremented and decremented:
```
2023-01-20 12:42:21.406 [25908] main/206/main I> assigned id 3 to replica 183ed830-c259-4097-88ed-690178ed9679
2023-01-20 12:42:21.406 [25908] main/206/main I> update replication_synchro_quorum = 2
2023-01-20 12:42:21.407 [25908] main/206/main I> cord_start           4 -> 5 : final_join
2023-01-20 12:42:21.423 [25908] main C> got signal 15 - Terminated
2023-01-20 12:42:21.423 [25908] relay/unix/:(socket)/101/main I> recover from /workspaces/t.sergos/test/var/038_replication/replica_uuid_ro1/00000000000000000000.xlog'
2023-01-20 12:42:21.423 [25908] main/260/iproto.shutdown I> tx_binary: stopped
2023-01-20 12:42:21.424 [25908] main I> cord_cancel_and_join 5 -> 4 : iproto
2023-01-20 12:42:21.424 [25908] main I> cord_cancel_and_join 4 -> 3 : relay/unix/:(socket)
2023-01-20 12:42:21.425 [25908] main I> cord_cancel_and_join 3 -> 2 : applier_1
2023-01-20 12:42:21.444 [25908] main I> cord_join            2 -> 1 : wal
tarantool: /workspaces/t.sergos/src/lib/core/fiber.c:2041: fiber_free: Assertion pm_atomic_load(&cord_count) == 0' failed.
```

**Comment by sergepetrenko** [comment]
The issue is present in 2.11 and later.
