### ISSUE TITLE
console escape match is slow and buggy

### ISSUE THREAD

**Issue by kostja** [tarantool/tarantool#826]
You can easily get a cpu hog when trying to "unescape" fiber.info() of a few thousand fibers. 
The bug only happens when using the binary protocol.

The trace of what the client is doing:
```
[10:39:34 PM] konstantinosipov: (gdb) 
Single stepping until exit from function match,
which has no line number information.
0x000000000051e8c8 in singlematch ()
(gdb) 
Single stepping until exit from function singlematch,
which has no line number information.
0x000000000051fffe in match ()
(gdb) 
Single stepping until exit from function match,
which has no line number information.
0x000000000051e92e in classend ()
(gdb) 
Single stepping until exit from function classend,
which has no line number information.
0x000000000051ff13 in match ()
(gdb) 
Single stepping until exit from function match,
which has no line number information.
0x000000000051e8c8 in singlematch ()
(gdb) 
Single stepping until exit from function singlematch,
which has no line number information.
0x000000000051fffe in match ()
(gdb) 
Single stepping until exit from function match,
which has no line number information.
0x000000000051e92e in classend ()
(gdb) 
Single stepping until exit from function classend,
which has no line number information.
0x000000000051ff13 in match ()
[10:39:45 PM] konstantinosipov: вот на чём усасывает
[10:39:48 PM] konstantinosipov: (gdb) bt
#0  0x000000000051ff13 in match ()
#1  0x000000000051ffe0 in match ()
#2  0x000000000052087a in str_find_aux ()
#3  0x0000000000520929 in lj_cf_string_match ()
#4  0x00000000004f3eaa in lj_BC_FUNCC ()
#5  0x00000000004de8aa in lua_call ()
#6  0x0000000000485105 in lbox_call (L=0x41066028, nargs=0, nreturns=-1)
    at /home/kostja/work/tarantool/src/lua/utils.h:447
#7  0x0000000000485ab6 in box_lua_fiber_run(typedef __va_list_tag __va_list_tag *) (ap=0x7f495f000428) at /home/kostja/work/tarantool/src/lua/fiber.cc:284
#8  0x0000000000493c88 in fiber_loop (data=0x0)
    at /home/kostja/work/tarantool/src/fiber.cc:402
#9  0x000000000057c275 in coro_init ()
    at /home/kostja/work/tarantool/third_party/coro/coro.c:96
```

**Comment by rtsisyk** [comment]
Fixed by 85281fc8cdfda4cd6d91b8e947e6f48be110173f
