### ISSUE TITLE
[2.11.0-rc] crash in vinyl_index_create_iterator

### ISSUE THREAD

**Issue by olegrok** [tarantool/tarantool#8372]
Tests shows that after update to 2.11.0-rc there is a regression that leads to crash in vinyl_index_create_iterator

```
WARNING  localhost:43969:server.py:42 2023-02-24 04:23:39.423 [807] main/128/main/box.load_cfg I> set 'vinyl_max_tuple_size' configuration option to 1
WARNING  localhost:43969:server.py:42 2023-02-24 04:23:39.427 [807] main/128/main vy_stmt.c:164 E> ER_VINYL_MAX_TUPLE_SIZE: Failed to allocate 41 bytes for tuple: tuple is too large. Check 'vinyl_max_tuple_size' configuration option.
WARNING  localhost:43969:server.py:42 Segmentation fault
WARNING  localhost:43969:server.py:42   code: SEGV_MAPERR
WARNING  localhost:43969:server.py:42   addr: (nil)
WARNING  localhost:43969:server.py:42   context: 0x7fa7d9f7ed40
WARNING  localhost:43969:server.py:42   siginfo: 0x7fa7d9f7ee70
WARNING  localhost:43969:server.py:42   rax      0x0                0
WARNING  localhost:43969:server.py:42   rbx      0x55897fe367d0     94049044490192
WARNING  localhost:43969:server.py:42   rcx      0x7fa7d9f7f1f0     140358893171184
WARNING  localhost:43969:server.py:42   rdx      0x7fa7d9f7f1f0     140358893171184
WARNING  localhost:43969:server.py:42   rsi      0x0                0
WARNING  localhost:43969:server.py:42   rdi      0x55897fe36838     94049044490296
WARNING  localhost:43969:server.py:42   rsp      0x7fa7d9f7fa40     140358893173312
WARNING  localhost:43969:server.py:42   rbp      0x0                0
WARNING  localhost:43969:server.py:42   r8       0x7fa7d9f7f1f0     140358893171184
WARNING  localhost:43969:server.py:42   r9       0x7fa79fae0000     140357915246592
WARNING  localhost:43969:server.py:42   r10      0x0                0
WARNING  localhost:43969:server.py:42   r11      0x0                0
WARNING  localhost:43969:server.py:42   r12      0x5589827b23d0     94049087988688
WARNING  localhost:43969:server.py:42   r13      0x7fa79fad0070     140357915181168
WARNING  localhost:43969:server.py:42   r14      0x0                0
WARNING  localhost:43969:server.py:42   r15      0x7fa7e3462039     140359049289785
WARNING  localhost:43969:server.py:42   rip      0x55897b9cfc55     94048972766293
WARNING  localhost:43969:server.py:42   eflags   0x10246            66118
WARNING  localhost:43969:server.py:42   cs       0x33               51
WARNING  localhost:43969:server.py:42   gs       0x0                0
WARNING  localhost:43969:server.py:42   fs       0x0                0
WARNING  localhost:43969:server.py:42   cr2      0x0                0
WARNING  localhost:43969:server.py:42   err      0x4                4
WARNING  localhost:43969:server.py:42   oldmask  0x0                0
WARNING  localhost:43969:server.py:42   trapno   0xe                14
WARNING  localhost:43969:server.py:42 Current time: 1677212619
WARNING  localhost:43969:server.py:42 Please file a bug at https://github.com/tarantool/tarantool/issues
WARNING  localhost:43969:server.py:42 Attempting backtrace... Note: since the server has already crashed,
WARNING  localhost:43969:server.py:42 this may fail as well
WARNING  localhost:43969:server.py:42 #1  0x55897bb6d68b in crash_signal_cb+155
WARNING  localhost:43969:server.py:42 #2  0x7fa7e4160630 in __restore_rt+0
WARNING  localhost:43969:server.py:42 #3  0x55897b9cfc55 in vinyl_index_create_iterator+933
WARNING  localhost:43969:server.py:42 #4  0x55897b988880 in generic_index_max+32
WARNING  localhost:43969:server.py:42 #5  0x55897b985da7 in box_index_max+423
WARNING  localhost:43969:server.py:42 #6  0x55897bb08927 in lbox_index_max+247
WARNING  localhost:43969:server.py:42 #7  0x55897bbb3251 in lj_BC_FUNCC+86
WARNING  localhost:43969:server.py:42 #8  0x55897bafe613 in execute_lua_call+147
WARNING  localhost:43969:server.py:42 #9  0x55897bbb3251 in lj_BC_FUNCC+86
WARNING  localhost:43969:server.py:42 #10 0x55897bbb84ff in lua_pcall+191
WARNING  localhost:43969:server.py:42 #11 0x55897bb5057b in luaT_call+11
WARNING  localhost:43969:server.py:42 #12 0x55897bafef29 in box_lua_call+297
WARNING  localhost:43969:server.py:42 #13 0x55897ba9caa4 in box_process_call+548
WARNING  localhost:43969:server.py:42 #14 0x55897b979654 in tx_process_call(cmsg*)+1060
WARNING  localhost:43969:server.py:42 #15 0x55897bb7adc3 in cmsg_deliver+19
WARNING  localhost:43969:server.py:42 #16 0x55897bb7b942 in fiber_pool_f+146
WARNING  localhost:43969:server.py:42 #17 0x55897b9741ad in fiber_cxx_invoke(int (*)(__va_list_tag*), __va_list_tag*)+13
WARNING  localhost:43969:server.py:42 #18 0x55897bb77ac6 in fiber_loop+70
WARNING  localhost:43969:server.py:42 #19 0x55897c4792c8 in coro_init+72
```

**Comment by olegrok** [comment]
Reproducer:
```
box.schema.space.create('test', {engine = 'vinyl'})
box.space.test:create_index('pk')
box.space.test:replace({1, 2, 3})
box.cfg{vinyl_max_tuple_size = 1}
box.space.test.index[0]:max()

2023-02-24 07:44:26.865 [16313] main/103/interactive vy_stmt.c:165 E> ER_VINYL_MAX_TUPLE_SIZE: Failed to allocate 25 bytes for tuple: tuple is too large. Check 'vinyl_max_tuple_size' configuration option.
Segmentation fault
  code: SEGV_MAPERR
  addr: 0x0
  context: 0x1111ffc38
  siginfo: 0x1111ffbd0
Current time: 1677213866
Please file a bug at https://github.com/tarantool/tarantool/issues
Attempting backtrace... Note: since the server has already crashed, 
this may fail as well
#1  0x10dcf4a37 in crash_signal_cb+151
#2  0x7ff81caa9dfd in _sigtramp+29
#3  0x10db8b27a in vinyl_index_create_iterator+1274
#4  0x10db44273 in generic_index_max+35
#5  0x10db42cb5 in box_index_max+245
#6  0x10dca28b2 in lbox_index_max+194
#7  0x10dd3ac53 in lj_BC_FUNCC+68
#8  0x10dd427d8 in lua_pcall+168
#9  0x10dcda583 in luaT_call+19
#10 0x10dcd2ac2 in run_script_f+1970
#11 0x10db3465c in fiber_cxx_invoke(int (*)(__va_list_tag*), __va_list_tag*)+12
#12 0x10dcfb25c in fiber_loop+92
#13 0x10e695a2c in coro_init+92
[1]    16313 abort      tarantool
```
