### ISSUE TITLE
segfault at 0 ip 0000563c09f3a547 sp 00007f534e7eba80 error 4 in tarantool[563c09d31000+68b000]

### ISSUE THREAD

**Issue by seet61** [tarantool/tarantool#8500]
**At system log messages I saw crash report and restart of some instance. segfault at 0 ip 0000563c09f3a547 sp 00007f534e7eba80 error 4 in tarantool[563c09d31000+68b000]**

*Mar 27 03:13:28 t2ru-esb-tnt-ferrari-app-01 kernel: tarantool[3037956]: segfault at 0 ip 0000563c09f3a547 sp 00007f534e7eba80 error 4 in tarantool[563c09d31000+68b000]
Mar 27 03:13:28 t2ru-esb-tnt-ferrari-app-01 kernel: Code: 10 44 89 25 db f3 6d 00 48 89 05 cc f3 6d 00 64 48 8b 04 25 00 00 00 00 48 8d 80 80 cc ff ff ba 01 00 00 00 48 89 df 48 8b 00 <48> 8b 30 e8 b1 a0 00 00 be 00 04 00 00 48 8d 3d ad
f3 6d 00 48 89*

*Core was generated by `tarantool init.lua <running>: tarantool_ferrari@routerE           '.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x0000563c09f3a547 in ?? ()
[Current thread is 1 (LWP 3037956)]
(gdb) bt
#0  0x0000563c09f3a547 in ?? ()
Backtrace stopped: Cannot access memory at address 0x7f534e7eba80*

* OS: Centos
* OS Version: CentOS Linux release 8.5.2111
* Architecture: x86_64

 `Tarantool 2.10.5-0-g87d07d15e
Target: Linux-x86_64-RelWithDebInfo
Build options: cmake . -DCMAKE_INSTALL_PREFIX=/usr -DENABLE_BACKTRACE=ON
Compiler: GNU-8.5.0
C_FLAGS:-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fexceptions -funwind-tables -fno-common -fopenmp -msse2 -Wformat -Wformat-security -Werror=format-security -fstack-protector-strong -fPIC -fmacro-prefix-map=/build/usr/src/debug/tarantool-2.10.5=. -std=c11 -Wall -Wextra -Wno-strict-aliasing -Wno-char-subscripts -Wno-format-truncation -Wno-gnu-alignof-expression -fno-gnu89-inline -Wno-cast-function-type -Werror
CXX_FLAGS:-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fexceptions -funwind-tables -fno-common -fopenmp -msse2 -Wformat -Wformat-security -Werror=format-security -fstack-protector-strong -fPIC -fmacro-prefix-map=/build/usr/src/debug/tarantool-2.10.5=. -std=c++11 -Wall -Wextra -Wno-strict-aliasing -Wno-char-subscripts -Wno-format-truncation -Wno-invalid-offsetof -Wno-gnu-alignof-expression -Wno-cast-function-type -Werror
`

**core file**
[core.tarantool.0.0394000415964529a2e0e316c82743c4.3037918.1679876008000000.lz4.zip](https://github.com/tarantool/tarantool/files/11077984/core.tarantool.0.0394000415964529a2e0e316c82743c4.3037918.1679876008000000.lz4.zip)

**Comment by Gumix** [comment]
There are 1396 threads in the core. Is this intentional?
