### ISSUE TITLE
ER_CURSOR_NO_TRANSACTION in on_commit trigger for syncro space

### ISSUE THREAD

**Issue by R-omk** [tarantool/tarantool#8505]
**Bug description**

```
main/103/app.lua init.c:376 E> ER_CURSOR_NO_TRANSACTION: The transaction the cursor belongs to has ended
main/103/app.lua F> transaction commit trigger failed
```

 Tarantool 2.11.0-rc2-0-g2ae0c94a2 Linux-x86_64-RelWithDebInfo

**Steps to reproduce**

```lua

box.cfg{}
s1 = box.schema.space.create('s1', { if_not_exists = true, is_sync = true})
s1:create_index('primary', {if_not_exists = true, unique = true, parts = {{field = 1, type = 'unsigned'}}})
box.ctl.promote()

f_commit = function(row_pairs) row_pairs() end
on_replace_f = function(old,new) box.on_commit(f_commit) end

s1:on_replace(on_replace_f)
s1:insert({1})


```

**Comment by Gerold103** [comment]
Apparently this also affects transactions working with async spaces. If the limbo is not empty, then all txns go there, and on commit will get the same error.

**Comment by R-omk** [comment]
Initially this problem was found  during the process of moving a bucket in vshard, this fatal error can randomly occur on reciever side.

**Comment by Serpentian** [comment]
The error comes from the function:

https://github.com/tarantool/tarantool/blob/606e50c4d56bb76714dc41339102b32230fd751e/src/box/lua/init.c#L450-L465

`txn` is NULL, which means, that no transaction is assigned to the following fiber. Error have the following traceback:

```
#0  lbox_txn_pairs (L=0x5555559328e2 <lj_alloc_f(void*, void*, size_t, size_t)+81>) at /home/serpentian/Programming/tnt/tarantool/src/box/lua/init.c:451
#1  0x0000555555ad3387 in lj_BC_FUNCC () at buildvm_x86.dasc:811
#2  0x00005555558d9d34 in lua_pcall (L=0x40000378, nargs=1, nresults=-1, errfunc=0) at /home/serpentian/Programming/tnt/tarantool/third_party/luajit/src/lj_api.c:1163
#3  0x000055555585106a in luaT_call (L=0x40000378, nargs=1, nreturns=-1) at /home/serpentian/Programming/tnt/tarantool/src/lua/utils.c:618
#4  0x000055555584b3a2 in lbox_trigger_run (ptr=0x555556112320, event=0x7ffff440e038) at /home/serpentian/Programming/tnt/tarantool/src/lua/trigger.c:111
#5  0x00005555558a2b3e in trigger_run_list (list=0x7ffff45ffa40, event=0x7ffff440e038) at /home/serpentian/Programming/tnt/tarantool/src/lib/core/trigger.cc:119
#6  0x00005555558a2ce7 in trigger_run_reverse (list=0x7ffff440e198, event=0x7ffff440e038) at /home/serpentian/Programming/tnt/tarantool/src/lib/core/trigger.cc:166
#7  0x0000555555701f40 in txn_complete_success (txn=0x7ffff440e038) at /home/serpentian/Programming/tnt/tarantool/src/box/txn.c:795
#8  0x0000555555707afe in txn_limbo_read_confirm (limbo=0x555555e73a20 <txn_limbo>, lsn=4) at /home/serpentian/Programming/tnt/tarantool/src/box/txn_limbo.c:464
#9  0x0000555555708377 in txn_limbo_ack (limbo=0x555555e73a20 <txn_limbo>, replica_id=1, lsn=4) at /home/serpentian/Programming/tnt/tarantool/src/box/txn_limbo.c:657
#10 0x0000555555703185 in txn_commit (txn=0x7ffff440e038) at /home/serpentian/Programming/tnt/tarantool/src/box/txn.c:1140
#11 0x00005555557101a3 in box_process_rw (request=0x7ffff45ffc10, space=0x555555f543f0, result=0x7ffff45ffd08)
    at /home/serpentian/Programming/tnt/tarantool/src/box/box.cc:475
#12 0x000055555571bf37 in box_process1 (request=0x7ffff45ffc10, result=0x7ffff45ffd08) at /home/serpentian/Programming/tnt/tarantool/src/box/box.cc:3378
#13 0x000055555571cad8 in box_insert (space_id=512, tuple=0x7ffff4403240 "\221\001", 'P' <repeats 198 times>..., tuple_end=0x7ffff4403242 'P' <repeats 200 times>...,
    result=0x7ffff45ffd08) at /home/serpentian/Programming/tnt/tarantool/src/box/box.cc:3570
#14 0x0000555555818864 in lbox_insert (L=0x40000378) at /home/serpentian/Programming/tnt/tarantool/src/box/lua/index.c:61
```

`txn_limbo_ack` tries to confirm a request, which have triggers. These triggers need transaction to be set in the current fiber. The transaction is cleared in `txn_commit`:

https://github.com/tarantool/tarantool/blob/606e50c4d56bb76714dc41339102b32230fd751e/src/box/txn.c#L1124-L1145
