### ISSUE TITLE
Assertion fail in applier_pause()

### ISSUE THREAD

**Issue by Totktonada** [tarantool/tarantool#8675]
Tarantool 3.0.0-entrypoint-214-g96706b7b7 Linux-x86_64-Debug.

Reproducer:

```lua
#!/usr/bin/env tarantool

local fio = require('fio')

local instance_name = 'instance_001'

local wal_dir = instance_name
local memtx_dir = instance_name
local listen = ('unix/:./%s.iproto'):format(instance_name)
local replication = {
    ('replicator:topsecret@unix/:./%s.iproto'):format('instance_001'),
    ('replicator:topsecret@unix/:./%s.iproto'):format('instance_002'),
    ('replicator:topsecret@unix/:./%s.iproto'):format('instance_003'),
}

local function safe_mkdir(dir)
    if not fio.path.exists(dir) then
        fio.mkdir(dir)
    end
end

safe_mkdir(wal_dir)
safe_mkdir(memtx_dir)

box.cfg({
    wal_dir = wal_dir,
    memtx_dir = memtx_dir,
    listen = listen,
    replication = replication,
})
```

Wait for 30 seconds to observe the crash:

```
2023-05-19 19:49:11.386 [12428] main/103/repro.lua I> connecting to 3 replicas
2023-05-19 19:49:11.386 [12428] main/111/applier/replicator@unix/:./instance_002.iproto I> can't connect to master
2023-05-19 19:49:11.386 [12428] main/111/applier/replicator@unix/:./instance_002.iproto sio.c:209 E> SocketError: connect to unix/:./instance_002.iproto, called on fd 24, aka unix/:(socket): No such file or directory
2023-05-19 19:49:11.386 [12428] main/111/applier/replicator@unix/:./instance_002.iproto I> will retry every 1.00 second
2023-05-19 19:49:11.387 [12428] main/112/applier/replicator@unix/:./instance_003.iproto I> can't connect to master
2023-05-19 19:49:11.387 [12428] main/112/applier/replicator@unix/:./instance_003.iproto sio.c:209 E> SocketError: connect to unix/:./instance_003.iproto, called on fd 24, aka unix/:(socket): No such file or directory
2023-05-19 19:49:11.387 [12428] main/112/applier/replicator@unix/:./instance_003.iproto I> will retry every 1.00 second
2023-05-19 19:49:11.388 [12428] main/110/applier/replicator@unix/:./instance_001.iproto I> remote master 6caa5220-8e9c-47ba-8b85-c9a90c5c1cd7 at unix/:./instance_001.iproto running Tarantool 3.0.0
2023-05-19 19:49:41.386 [12428] main/103/repro.lua C> failed to connect to 2 out of 3 replicas
tarantool: ./src/box/applier.cc:2720: void applier_pause(applier*): Assertion `!applier->is_paused' failed.
Aborted (core dumped)
```

Backtrace:

```c
#0  0x00007f25db86051c in __pthread_kill_implementation () from /lib64/libc.so.6
#1  0x00007f25db811f02 in raise () from /lib64/libc.so.6
#2  0x00007f25db7fc472 in abort () from /lib64/libc.so.6
#3  0x00007f25db7fc395 in __assert_fail_base.cold () from /lib64/libc.so.6
#4  0x00007f25db80ae52 in __assert_fail () from /lib64/libc.so.6
#5  0x000055a92c0241b9 in applier_pause (applier=0x55a92e635440) at /usr/src/debug/dev-db/tarantool-9999/tarantool-9999/src/box/applier.cc:2720
#6  0x000055a92c0139f0 in applier_on_connect_f (trigger=0x7f25d91ff2e0, event=0x55a92e635440) at /usr/src/debug/dev-db/tarantool-9999/tarantool-9999/src/box/replication.cc:913
#7  0x000055a92c1808d6 in trigger_run_list (list=0x7f25d317fe20, event=0x55a92e635440) at /usr/src/debug/dev-db/tarantool-9999/tarantool-9999/src/lib/core/trigger.cc:119
#8  0x000055a92c1809bb in trigger_run (list=0x55a92e635a38, event=0x55a92e635440) at /usr/src/debug/dev-db/tarantool-9999/tarantool-9999/src/lib/core/trigger.cc:152
#9  0x000055a92c018db4 in trigger_run_xc (list=0x55a92e635a38, event=0x55a92e635440) at /usr/src/debug/dev-db/tarantool-9999/tarantool-9999/src/lib/core/trigger.h:173
#10 0x000055a92c01ae2a in applier_set_state (applier=0x55a92e635440, state=APPLIER_OFF) at /usr/src/debug/dev-db/tarantool-9999/tarantool-9999/src/box/applier.cc:83
#11 0x000055a92c0233b1 in applier_disconnect (applier=0x55a92e635440, state=APPLIER_OFF) at /usr/src/debug/dev-db/tarantool-9999/tarantool-9999/src/box/applier.cc:2445
#12 0x000055a92c023627 in applier_f(typedef __va_list_tag __va_list_tag *) (ap=0x7f25d9011168) at /usr/src/debug/dev-db/tarantool-9999/tarantool-9999/src/box/applier.cc:2511
#13 0x000055a92bec60cd in fiber_cxx_invoke(fiber_func, typedef __va_list_tag __va_list_tag *) (f=0x55a92c0233fa <applier_f(typedef __va_list_tag __va_list_tag *)>, ap=0x7f25d9011168)
    at /usr/src/debug/dev-db/tarantool-9999/tarantool-9999/src/lib/core/fiber.h:1233
#14 0x000055a92c158c54 in fiber_loop (data=0x0) at /usr/src/debug/dev-db/tarantool-9999/tarantool-9999/src/lib/core/fiber.c:998
#15 0x000055a92c2eb0ff in coro_init () at /usr/src/debug/dev-db/tarantool-9999/tarantool-9999/third_party/coro/coro.c:108
```

The failed `assert()` is on line 2720:

https://github.com/tarantool/tarantool/blob/96706b7b7e860f23ee59913e347f9b5fd306b662/src/box/applier.cc#L2715-L2724

**Comment by sergepetrenko** [comment]
A smaller reproducer (you shouldn't have anyone listening on port 3302):
```lua
#!/usr/bin/env tarantool

box.cfg{
    replication=3302,
    replication_connect_timeout=0.1,
    log_level=1,
}
```

Bisect shows the commit 0f12367f9040c72cb1b6d63e0183d68139e34ca2 is the reason, so only 3.0 is affected.
