### ISSUE TITLE
Assertion `iov->iov_len < buf->capacity[buf->pos]' failed

### ISSUE THREAD

**Issue by rtsisyk** [tarantool/tarantool#874]
```
(gdb) bt
#0  0x00007f5e1897d407 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x00007f5e1897e7e8 in __GI_abort () at abort.c:89
#2  0x00007f5e18976526 in __assert_fail_base (fmt=0x7f5e18aacd18 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=assertion@entry=0x5a9568 "iov->iov_len < buf->capacity[buf->pos]", 
    file=file@entry=0x5a9528 "/data/work/tarantool/master/src/iobuf.h", line=line@entry=211, function=function@entry=0x5a9960 <_ZZL10obuf_allocP4obufmE19__PRETTY_FUNCTION__> "void* obuf_alloc(obuf*, size_t)") at assert.c:92
#3  0x00007f5e189765d2 in __GI___assert_fail (assertion=0x5a9568 "iov->iov_len < buf->capacity[buf->pos]", file=0x5a9528 "/data/work/tarantool/master/src/iobuf.h", line=211, 
    function=0x5a9960 <_ZZL10obuf_allocP4obufmE19__PRETTY_FUNCTION__> "void* obuf_alloc(obuf*, size_t)") at assert.c:101
#4  0x0000000000479589 in obuf_alloc (buf=0x7f5e17c414a8, size=29) at /data/work/tarantool/master/src/iobuf.h:211
#5  0x000000000047a4a2 in obuf_book (buf=0x7f5e17c414a8, size=29) at /data/work/tarantool/master/src/iobuf.cc:296
#6  0x0000000000434c1d in iproto_prepare_select (buf=0x7f5e17c414a8) at /data/work/tarantool/master/src/box/iproto_port.cc:126
#7  0x0000000000434d53 in iproto_port_add_tuple (ptr=0x7f5cf9d9fe50, tuple=0x7f5d34d6b358) at /data/work/tarantool/master/src/box/iproto_port.cc:153
#8  0x0000000000456b99 in port_add_tuple (port=0x7f5cf9d9fe50, tuple=0x7f5d34d6b358) at /data/work/tarantool/master/src/box/port.h:77
#9  0x0000000000456d39 in execute_replace (request=0x7f5cfc811550, port=0x7f5cf9d9fe50) at /data/work/tarantool/master/src/box/request.cc:73
#10 0x0000000000457657 in process_rw (request=0x7f5cfc811550, port=0x7f5cf9d9fe50) at /data/work/tarantool/master/src/box/request.cc:211
#11 0x0000000000433f0e in iproto_process (ireq=0x7f5cfc8114e8) at /data/work/tarantool/master/src/box/iproto.cc:670
#12 0x0000000000432c58 in iproto_queue_handler(typedef __va_list_tag __va_list_tag *) (ap=0x7f5cfa28aca0) at /data/work/tarantool/master/src/box/iproto.cc:203
#13 0x0000000000499fef in fiber_loop (data=0x0) at /data/work/tarantool/master/src/fiber.cc:402
#14 0x0000000000581c55 in coro_init () at /data/work/tarantool/master/third_party/coro/coro.c:96
```

1.6 branch
Regression introduced by 7fa4c26873c1415345db98e9271da7b701a814f4

**Comment by rtsisyk** [comment]
How to reproduce.

1. Configure Tarantool with single space
```
box.cfg { listen = 3313 }
_ = box.schema.create_space('test')
_ = box.space.test:create_index('primary')
box.schema.role.grant('guest', 'read,write,execute', 'universe')
```

2. Run nosqlbench with default configuration and wait couple seconds
