### ISSUE TITLE
Memory leak in xrow_decode_error/diag_destroy

### ISSUE THREAD

**Issue by ligurio** [tarantool/tarantool#8921]
**Bug description**

On using function `xrow_decode_error` Address Sanitizers reports memory leak.
The bug (if it is really so) was found by fuzzing test in branch https://github.com/ligurio/tarantool/tree/ligurio/new-fuzzers and PR #8904.

* OS: Linux
* OS Version: Ubuntu 22.04
* Architecture: amd64
* Compiler: Clang 17

**Steps to reproduce**

How to run:

Apply a patch below and run `cmake -S . -B build -DENABLE_ASAN=ON && cmake --build build --parallel --target xrow.test && ./build/test/unit/xrow.test`

Download patch: [xrow_decode_error.txt](https://github.com/tarantool/tarantool/files/12183862/xrow_decode_error.txt)

```patch
diff --git a/test/unit/xrow.cc b/test/unit/xrow.cc
index 4b2e68c170..8064325d2d 100644
--- a/test/unit/xrow.cc
+++ b/test/unit/xrow.cc
@@ -540,13 +540,76 @@ test_xrow_decode_unknown_key(void)
 	footer();
 }
 
+static void
+test_xrow_decode_error(void)
+{
+	header();
+	plan(1);
+
+	uint8_t data[] = { 0x81, 0x52, 0x81, 0x00, 0x96, 0xdf, 0x00, 0x00,
+			   0x00, 0x4b, 0x42, 0x4b, 0x4b, 0x4b, 0x4b, 0x4b,
+			   0x05, 0x05, 0x05, 0x05, 0x05, 0x5e, 0x5e, 0x5e,
+			   0x5e, 0x5e, 0x5e, 0x5e, 0x7e, 0x5e, 0x5e, 0x5e,
+			   0x5e, 0x5e, 0x5e, 0x5e, 0x5e, 0x5e, 0x5e, 0x5e,
+			   0x5e, 0x5e, 0x5e, 0x5e, 0x5e, 0x5e, 0x5e, 0x5e,
+			   0x5e, 0x5e, 0x5e, 0x5e, 0x5e, 0x5e, 0x5e, 0x5e,
+			   0x00, 0xa1, 0x00, 0x03, 0xd9, 0x00, 0x5e, 0x5e,
+			   0x64, 0x64, 0x64, 0x64, 0x64, 0x5e, 0x5e, 0x5e,
+			   0x5e, 0x5e, 0x00, 0xa1, 0x00, 0x03, 0xd9, 0x00,
+			   0x5e, 0x5e, 0x64, 0x64, 0x64, 0x64, 0x64, 0x64,
+			   0x5e, 0x5e, 0x5e, 0x5e, 0x5e, 0x5e, 0x5e, 0x5e,
+			   0x5e, 0x5e, 0x5e, 0x5e, 0x5e, 0x5e, 0x5e, 0x5e,
+			   0x5e, 0x5e, 0x5e, 0x5e, 0x5e, 0x5e, 0x5e, 0x5e,
+			   0x01, 0xa1, 0x5e, 0x5e, 0x5e, 0x5e, 0x5e, 0x5e,
+			   0x5e, 0x5e, 0x5e, 0x5e, 0x5e, 0x5e, 0x5e, 0x5e,
+			   0x5f, 0x5e, 0x5e, 0x5e, 0x5e, 0x5e, 0x5e, 0x5e,
+			   0x5e, 0x00, 0xa1, 0x00, 0x03, 0xd9, 0x00, 0x5e,
+			   0x5e, 0x64, 0x64, 0x64, 0x64, 0x64, 0x5e, 0x5e,
+			   0x5e, 0x5e, 0x5e, 0x00, 0xa1, 0x00, 0x03, 0xd9,
+			   0x5e, 0x5e, 0x5e, 0x5e, 0x5e, 0x5e, 0x5e, 0x5e,
+			   0x5e, 0x5e, 0x5e, 0x5e, 0x5e, 0x00, 0xa1, 0x64,
+			   0x64, 0x5e, 0x5e, 0x5e, 0x5e, 0x5b, 0x00, 0xa1,
+			   0x00, 0x03, 0xd9, 0x00, 0x5e, 0x5e, 0x64, 0x64,
+			   0x64, 0x1c, 0x1c, 0x1c, 0x1c, 0x1c, 0x1c, 0x1c,
+			   0x18, 0x1c, 0x1c, 0x1c, 0x1c, 0x1e, 0x1c, 0x1c,
+			   0x1c, 0x1c, 0x1c, 0x1c, 0x1c, 0x1c, 0x1c, 0x1c,
+			   0x1c, 0x1c, 0x1c, 0x1c, 0x1c, 0x1c, 0x1c, 0x1c,
+			   0x1c, 0x1c, 0x1c, 0x1c, 0x1c, 0x1c, 0x1c, 0x1c,
+			   0x1c, 0x1c, 0x64, 0x64, 0x64, 0x64, 0x64, 0x64,
+			   0x22, 0x00, 0x00, 0x00, 0x00, 0x03, 0x41, 0xd9,
+			   0x00, 0x5e, 0x5e, 0x5e, 0x5e, 0x5e, 0x5e, 0x5e,
+			   0x5e, 0x64, 0x64, 0x64, 0x64, 0x64, 0x64, 0x64,
+			   0x64, 0x64, 0x64, 0x64, 0x64, 0x64, 0x64, 0x64,
+			   0x64, 0x64, 0x64, 0x64, 0x64, 0x64, 0x64, 0x64,
+			   0x64, 0x64, 0x64, 0x65, 0x64, 0x64, 0x64, 0x64,
+			   0x64, 0x22, 0x00, 0x00, 0x00, 0x64, 0x01, 0x00,
+			   0x00, 0x00, 0x00, 0x08, 0x23, 0x00, 0x02, 0x00,
+			   0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00 };
+
+	struct iovec body;
+	body.iov_base = (void *)data;
+	body.iov_len = sizeof(data);
+
+	struct xrow_header row;
+	row.body[0] = body;
+	row.bodycnt = 1;
+
+	xrow_decode_error(&row);
+
+	diag_destroy(diag_get());
+	is(diag_is_empty(diag_get()), true, "xrow_decode_error");
+
+	check_plan();
+	footer();
+}
+
 int
 main(void)
 {
 	memory_init();
 	fiber_init(fiber_c_invoke);
 	header();
-	plan(6);
+	plan(7);
 
 	random_init();
 
@@ -557,6 +620,7 @@ main(void)
 	test_xrow_fields();
 	test_xrow_encode_dml();
 	test_xrow_decode_unknown_key();
+	test_xrow_decode_error();
 
 	random_free();
 	fiber_free();
```

**Actual behavior**

```
<snipped>

# *** test_xrow_decode_unknown_key: done ***
# *** test_xrow_decode_error ***
    1..1
    ok 1 - xrow_decode_error
ok 7 - subtests
# *** test_xrow_decode_error: done ***
# *** main: done ***

=================================================================
==1103877==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 864 byte(s) in 1 object(s) allocated from:
    #0 0x563f29147b5e in malloc (/home/sergeyb/sources/MRG/tarantool/build/test/unit/xrow.test+0x294b5e) (BuildId: 1dd52fe6bc70ba099d23e525402253373444d0a8)
    #1 0x563f292bef9c in Exception::operator new(unsigned long) /home/sergeyb/sources/MRG/tarantool/src/lib/core/exception.cc:94:14
    #2 0x563f29209a42 in error_build_xc(mp_error*) /home/sergeyb/sources/MRG/tarantool/src/box/mp_error.cc:260:9
    #3 0x563f291fde5e in mp_decode_error_one(char const**) /home/sergeyb/sources/MRG/tarantool/src/box/mp_error.cc:377:9
    #4 0x563f291fc573 in error_unpack_unsafe /home/sergeyb/sources/MRG/tarantool/src/box/mp_error.cc:498:25
    #5 0x563f291d3407 in xrow_decode_error /home/sergeyb/sources/MRG/tarantool/src/box/xrow.c:1771:22
    #6 0x563f2919d00a in test_xrow_decode_error() /home/sergeyb/sources/MRG/tarantool/test/unit/xrow.cc:597:2
    #7 0x563f291927ae in main /home/sergeyb/sources/MRG/tarantool/test/unit/xrow.cc:623:2
    #8 0x7fb184c29d8f in __libc_start_call_main csu/../sysdeps/nptl/libc_start_call_main.h:58:16

SUMMARY: AddressSanitizer: 864 byte(s) leaked in 1 allocation(s).
```

**Expected behavior**

no memory leak, test succesfully finished with exit code 0

**Comment by Gumix** [comment]
Here's a reduced testcase:

```c
        uint8_t data[] = {
                0x81, /* MP_MAP of 1 element */
                0x52, /* IPROTO_ERROR: */
                0x81, /* MP_MAP of 1 element */
                0x00, /* MP_ERROR_STACK: */
                0x92, /* MP_ARRAY of 2 elements */
                0x83, /* MP_MAP of 3 elements */
                0x00, 0xa1, 0x00, /* MP_ERROR_TYPE: "" */
                0x01, 0xa1, 0x00, /* MP_ERROR_FILE: "" */
                0x03, 0xa1, 0x00, /* MP_ERROR_MESSAGE: "" */
                0x00 /* MP_INT instead of MP_MAP */
        };
```
