### ISSUE TITLE
Crash on M1 lbox_tuple_field_by_path

### ISSUE THREAD

**Issue by rayman1104** [tarantool/tarantool#9030]
**Bug description**

Tarantool crashes after some time with next output:

```
flare.edge1-master | Segmentation fault
flare.edge1-master |   code: SEGV_ACCERR
flare.edge1-master |   addr: 0x50
flare.edge1-master |   context: 0x10c27f538
flare.edge1-master |   siginfo: 0x10c27f4d0
flare.edge1-master | Current time: 1692868734
flare.edge1-master | Please file a bug at https://github.com/tarantool/tarantool/issues
flare.edge1-master | Attempting backtrace... Note: since the server has already crashed,
flare.edge1-master | this may fail as well
flare.edge1-master | #1  0xd86a000100ec79c0 in crash_signal_cb+15594276659723763844
flare.edge1-master | #2  0x2d070001b27e02a4 in _sigtramp+3244562056543731768
flare.edge1-master | #3  0x6566000100e8c800 in lbox_tuple_field_by_path+7306527445455208620
flare.edge1-master | #4  0x902e000100e8c800 in lbox_tuple_field_by_path+10389241390390313132
flare.edge1-master | #5  0xb07f000100f02504 in lj_BC_FUNCC+12717883872717570092
flare.edge1-master | #6  0x2640000100e83d94 in execute_lua_call+2756202971950743900
flare.edge1-master | #7  0x941000100f02504 in lj_BC_FUNCC+666814219827544108
flare.edge1-master | #8  0x9333000100f06a10 in lua_pcall+10606821547387650220
flare.edge1-master | #9  0x9319800100eb28bc in luaT_call+10599643935481528344
flare.edge1-master | #10 0xb45d800100e82fb8 in box_process_lua+12996684837149475004
flare.edge1-master | #11 0x374f800100e850a4 in func_lua_call+3985544932734533704
flare.edge1-master | #12 0x603d800100de09f4 in func_call_no_access_check+6934839738708787408
flare.edge1-master | #13 0xd44a000100e30fe4 in box_process_call+15297039084317311244
flare.edge1-master | #14 0x6a12800100d5c760 in tx_process_call(cmsg*)+7643312255089508644
flare.edge1-master | #15 0x2b18000100ed2394 in cmsg_deliver+3105231943071957020
flare.edge1-master | #16 0x6b31800100ed356c in fiber_pool_f+7724095573405466880
flare.edge1-master | #17 0x8501000100d57f24
```

* OS: MacOS
* OS Version: 13.2.1
* Architecture: arm

Place `tarantool --version` output here.
```
Tarantool 2.11.0-0-g247a9a4
Target: Darwin-arm64-Release
Build options: cmake . -DCMAKE_INSTALL_PREFIX=/opt/homebrew/Cellar/tarantool/2.11.0_1 -DENABLE_BACKTRACE=TRUE
Compiler: /usr/bin/clang /usr/bin/clang++
C_FLAGS: -fexceptions -funwind-tables -fasynchronous-unwind-tables -fno-common -fopenmp -Wformat -Wformat-security -Werror=format-security -fstack-protector-strong -fPIC -fmacro-prefix-map=/tmp/tarantool-20230620-52093-1mic7ro/tarantool-2.11.0=. -std=c11 -Wall -Wextra -Wno-gnu-alignof-expression -Wno-cast-function-type
CXX_FLAGS: -fexceptions -funwind-tables -fasynchronous-unwind-tables -fno-common -fopenmp -Wformat -Wformat-security -Werror=format-security -fstack-protector-strong -fPIC -fmacro-prefix-map=/tmp/tarantool-20230620-52093-1mic7ro/tarantool-2.11.0=. -std=c++11 -Wall -Wextra -Wno-invalid-offsetof -Wno-gnu-alignof-expression -Wno-cast-function-type
```

**Steps to reproduce**
Hard to tell, it was just on for 20 minutes, without load. But also what's important probably is that we have Rust code, used via tarantool-module.

**Comment by sergos** [comment]
No feedback/repro for more than 1 month. Feel free to reopen.
