### ISSUE TITLE
ASAN: memory leak in vinyl

### ISSUE THREAD

**Issue by nshy** [tarantool/tarantool#9158]
Found in `3.0.0-alpha2-61-g0dc373565`

Leak is reported with or without special allocators for ASAN (PR https://github.com/tarantool/tarantool/pull/8901) for `sql-tap/alter.test.lua` test (only **vynil**). Only reported in **debug** build. Looks like it is get suppressed in release mode. With `malloc_context_size=50` (default is `30`) in `ASAN_OPTIONS` issue is gone for debug mode too.

```
=================================================================
==1485751==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 208 byte(s) in 8 object(s) allocated from:
    #0 0x5639b9fe2419 in malloc (/home/shiny/dev/tarantool/build-asan-debug/src/tarantool+0x116b419) (BuildId: afd99d5b7af755fd775b60ab8290c769dd17ba1e)
    #1 0x5639ba3dc6e9 in vy_stmt_alloc /home/shiny/dev/tarantool/src/box/vy_stmt.c:186:24
    #2 0x5639ba3db80e in vy_stmt_dup /home/shiny/dev/tarantool/src/box/vy_stmt.c:213:22
    #3 0x5639ba6c4446 in vy_history_append_stmt /home/shiny/dev/tarantool/src/box/vy_history.c:58:16
    #4 0x5639ba3fbc36 in vy_mem_iterator_get_history /home/shiny/dev/tarantool/src/box/vy_mem.c:568:7
    #5 0x5639ba3fa0fc in vy_mem_iterator_next /home/shiny/dev/tarantool/src/box/vy_mem.c:582:10
    #6 0x5639ba60823b in vy_point_lookup_scan_mem /home/shiny/dev/tarantool/src/box/vy_point_lookup.c:106:11
    #7 0x5639ba601d15 in vy_point_lookup_scan_mems /home/shiny/dev/tarantool/src/box/vy_point_lookup.c:125:6
    #8 0x5639ba5fd2cb in vy_point_lookup /home/shiny/dev/tarantool/src/box/vy_point_lookup.c:243:7
    #9 0x5639ba396ac0 in vy_get /home/shiny/dev/tarantool/src/box/vinyl.c:1436:7
    #10 0x5639ba3a20e5 in vy_get_by_raw_key /home/shiny/dev/tarantool/src/box/vinyl.c:1510:11
    #11 0x5639ba3c93e5 in vinyl_index_get /home/shiny/dev/tarantool/src/box/vinyl.c:3875:11
    #12 0x5639ba7c3862 in index_get /home/shiny/dev/tarantool/src/box/index.h:965:9
    #13 0x5639ba7ca80a in tuple_constraint_fkey_check /home/shiny/dev/tarantool/src/box/tuple_constraint_fkey.c:326:6
    #14 0x5639bbb7a547 in tuple_check_constraint /home/shiny/dev/tarantool/src/box/tuple_format.c:1090:7
    #15 0x5639bbb7942f in tuple_field_map_create /home/shiny/dev/tarantool/src/box/tuple_format.c:1182:18
    #16 0x5639bbb47533 in tuple_validate_raw /home/shiny/dev/tarantool/src/box/tuple.c:164:11
    #17 0x5639ba3905e6 in vy_insert /home/shiny/dev/tarantool/src/box/vinyl.c:2259:6
    #18 0x5639ba386fe5 in vinyl_space_execute_replace /home/shiny/dev/tarantool/src/box/vinyl.c:2388:8
    #19 0x5639ba73f072 in space_execute_dml /home/shiny/dev/tarantool/src/box/space.c:962:7
    #20 0x5639ba926f21 in box_process_rw /home/shiny/dev/tarantool/src/box/box.cc:457:6
    #21 0x5639ba94dcc6 in box_process1 /home/shiny/dev/tarantool/src/box/box.cc:3608:9
    #22 0x5639bab057f0 in insertOrReplace /home/shiny/dev/tarantool/src/box/sql.c:457:9
    #23 0x5639bab05079 in tarantoolsqlInsert /home/shiny/dev/tarantool/src/box/sql.c:463:9
    #24 0x5639baf22d7e in sqlVdbeExec /home/shiny/dev/tarantool/src/box/sql/vdbe.c:3493:9
    #25 0x5639baf4b92c in sqlStep /home/shiny/dev/tarantool/src/box/sql/vdbeapi.c:133:8
    #26 0x5639baf4a89c in sql_step /home/shiny/dev/tarantool/src/box/sql/vdbeapi.c:155:9
    #27 0x5639bab335f0 in sql_execute /home/shiny/dev/tarantool/src/box/execute.c:218:8
    #28 0x5639bab33126 in sql_prepare_and_execute /home/shiny/dev/tarantool/src/box/execute.c:281:6
    #29 0x5639bb1336d2 in lbox_execute /home/shiny/dev/tarantool/src/box/lua/execute.c:478:7

SUMMARY: AddressSanitizer: 208 byte(s) leaked in 8 allocation(s).
```

**Comment by locker** [comment]
Not a bug: purging the vinyl cache helps. We should purge the cache at exit if ASAN is enabled.
