### ISSUE TITLE
ASAN: memory leak in SQL parser for column default

### ISSUE THREAD

**Issue by nshy** [tarantool/tarantool#9159]
Found in `3.0.0-alpha2-61-g0dc373565`

Leak is reported with or without special allocators for ASAN (PR https://github.com/tarantool/tarantool/pull/8901) for `sql-tap/where3.test.lua` test. Only reported in **debug** build. Looks like it is get suppressed in release mode. With `malloc_context_size=50` (default is `30`) in `ASAN_OPTIONS` issue is gone for debug mode too.

```
=================================================================
==1527966==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 744 byte(s) in 8 object(s) allocated from:
    #0 0x559cdb3d5419 in malloc (/home/shiny/dev/tarantool/build-asan-debug/src/tarantool+0x116b419) (BuildId: afd99d5b7af755fd775b60ab8290c769dd17ba1e)
    #1 0x559cdc11ec8b in sql_xmalloc /home/shiny/dev/tarantool/src/box/sql/malloc.c:85:9
    #2 0x559cdbfdd296 in spanExpr /home/shiny/dev/tarantool/src/box/sql/parse.y:909:9
    #3 0x559cdbfafa8d in yy_reduce /home/shiny/dev/tarantool/src/box/sql/parse.y:960:2
    #4 0x559cdbf8ee1e in sqlParser /home/shiny/dev/tarantool/build-asan-debug/src/box/sql/parse.c:4424:7
    #5 0x559cdc28f6b3 in sqlRunParser /home/shiny/dev/tarantool/src/box/sql/tokenize.c:577:4
    #6 0x559cdc292077 in sql_expr_compile /home/shiny/dev/tarantool/src/box/sql/tokenize.c:621:6
    #7 0x559cdbeebdf0 in sql_expr_compile_cb /home/shiny/dev/tarantool/src/box/sql.c:71:9
    #8 0x559cdcf64096 in tuple_format_create /home/shiny/dev/tarantool/src/box/tuple_format.c:564:5
    #9 0x559cdcf5fe0b in tuple_format_new /home/shiny/dev/tarantool/src/box/tuple_format.c:931:6
    #10 0x559cdbb5d218 in space_tuple_format_new /home/shiny/dev/tarantool/src/box/space_def.c:113:9
    #11 0x559cdb713bff in memtx_space_new /home/shiny/dev/tarantool/src/box/memtx_space.c:1424:3
    #12 0x559cdb6e7c24 in memtx_engine_create_space(engine*, space_def*, rlist*) /home/shiny/dev/tarantool/src/box/memtx_engine.cc:540:9
    #13 0x559cdbb2b75e in engine_create_space /home/shiny/dev/tarantool/src/box/engine.h:329:9
    #14 0x559cdbb2b2a9 in space_new /home/shiny/dev/tarantool/src/box/space.c:473:9
    #15 0x559cdbc3509c in space_new_xc(space_def*, rlist*) /home/shiny/dev/tarantool/src/box/space.h:721:24
    #16 0x559cdbc2b87c in alter_space_do(txn_stmt*, alter_space*) /home/shiny/dev/tarantool/src/box/alter.cc:1022:21
    #17 0x559cdbbfd726 in on_replace_dd_index(trigger*, void*) /home/shiny/dev/tarantool/src/box/alter.cc:2762:3
    #18 0x559cdc7c2706 in trigger_run_list(rlist*, void*) /home/shiny/dev/tarantool/src/lib/core/trigger.cc:119:7
    #19 0x559cdc7c0c86 in trigger_run /home/shiny/dev/tarantool/src/lib/core/trigger.cc:152:9
    #20 0x559cdbcc0a9f in txn_commit_stmt /home/shiny/dev/tarantool/src/box/txn.c:642:13
    #21 0x559cdbd1a165 in box_process_rw /home/shiny/dev/tarantool/src/box/box.cc:474:6
    #22 0x559cdbd40cc6 in box_process1 /home/shiny/dev/tarantool/src/box/box.cc:3608:9
    #23 0x559cdbef87f0 in insertOrReplace /home/shiny/dev/tarantool/src/box/sql.c:457:9
    #24 0x559cdbef8079 in tarantoolsqlInsert /home/shiny/dev/tarantool/src/box/sql.c:463:9
    #25 0x559cdc31a69f in sqlVdbeExec /home/shiny/dev/tarantool/src/box/sql/vdbe.c:3651:6
    #26 0x559cdc33e92c in sqlStep /home/shiny/dev/tarantool/src/box/sql/vdbeapi.c:133:8
    #27 0x559cdc33d89c in sql_step /home/shiny/dev/tarantool/src/box/sql/vdbeapi.c:155:9
    #28 0x559cdbf265f0 in sql_execute /home/shiny/dev/tarantool/src/box/execute.c:218:8
    #29 0x559cdbf26126 in sql_prepare_and_execute /home/shiny/dev/tarantool/src/box/execute.c:281:6

SUMMARY: AddressSanitizer: 744 byte(s) leaked in 8 allocation(s).
```

**Comment by nshy** [comment]
Minimal repro:
```lua
box.cfg{}
if box.space.aaa ~= nil then
    box.space.aaa:drop()
end
box.execute([[
CREATE TABLE aaa (id INTEGER PRIMARY KEY, type INTEGER,
                  fk TEXT DEFAULT NULL, parent INTEGER,
                  position INTEGER, title TEXT,
                  keyword_id INTEGER, folder_type TEXT,
                  dateAdded INTEGER, lastModified INTEGER);
]])
os.exit()
```
