### ISSUE TITLE
MacOS new XCode causes crash in libunwind

### ISSUE THREAD

**Issue by sergos** [tarantool/tarantool#9198]
With the latest version of XCode:
```
s.ostanevich@s-ostanevich:~/workspaces/t.sergos % xcodebuild -version 
Xcode 15.0
Build version 15A240d
```
I followed the build process on a fresh master:
```
s.ostanevich@s-ostanevich:~/workspaces/t.sergos % git describe                                     
3.0.0-alpha3-48-g9cf6100c1
s.ostanevich@s-ostanevich:~/workspaces/t.sergos % cmake . -G Ninja && cmake --build .
[...]
s.ostanevich@s-ostanevich:~/workspaces/t.sergos % ./src/tarantool -i        
Segmentation fault
  code: 0
  addr: 0x0
  context: 0x7ff7b02fa448
  siginfo: 0x7ff7b02fa3e0
Current time: 1695989030
Please file a bug at https://github.com/tarantool/tarantool/issues
Attempting backtrace... Note: since the server has already crashed, 
this may fail as well
#1  0x10fede45a in crash_collect+234
#2  0x10fede30c in crash_signal_cb+60
#3  0x7ff81b27737d in _sigtramp+29
#4  0x7ff828040768 in _Unwind_RaiseException+40
#5  0x10ff65206 in err_raise_ext+102
#6  0x10ff65163 in lj_err_throw+67
#7  0x10ff65b3d in lj_err_run+1565
#8  0x10ff66691 in lj_err_callermsg+385
#9  0x10ff66e3f in luaL_error+207
#10 0x10ff95a9f in lj_cf_package_require+383
#11 0x10ff4d93b in lj_BC_FUNCC+68
#12 0x10ff5c20d in lua_pcall+973
#13 0x10fe69961 in box_lua_init+657
#14 0x10fc0c49e in main+3086
#15 0x7ff81aec13a6 in start+1942
zsh: abort      ./src/tarantool -i
```

Apparently, new version of devtools brought in a new unwind library, that caused some inconsistency.

**Comment by kyukhin** [comment]
We are about to abandon macOS testing on x86.
See https://github.com/tarantool/infra/issues/187
