### ISSUE TITLE
ASAN: memory leak in luaT_push_key_def

### ISSUE THREAD

**Issue by nshy** [tarantool/tarantool#9213]
Found in `3.0.0-alpha3-69-gba9b012ac`

Leak is reported with special allocators for ASAN (PR https://github.com/tarantool/tarantool/pull/8901) for `box/net.box_iproto_transactions_over_streams.test.lua`. I guess PR does not make a difference taking the backtrace into account. It is only reported in **debug** build. Looks like it is get suppressed in release mode. With `malloc_context_size=50` (default is `30`) in `ASAN_OPTIONS` issue is gone for debug mode too.

Build options:
```bash
CC=/usr/bin/clang CXX=/usr/bin/clang++ cmake -B build-asan-debug \
        -DCMAKE_BUILD_TYPE=Debug \
        -DENABLE_WERROR=ON \
        -DENABLE_ASAN=ON \
        -DENABLE_UB_SANITIZER=ON \
        -DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION=OFF \
        -DFIBER_STACK_SIZE=640Kb \
        -DENABLE_FUZZER=ON \
        -DTEST_BUILD=ON
```
```
=================================================================
==3320211==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 1152 byte(s) in 6 object(s) allocated from:
    #0 0x55f70fa273c9 in malloc (/home/shiny/dev/tarantool/build-asan-debug/src/tarantool+0x11903c9) (BuildId: 50b4f8d425d61717239211bb327e4c0a466dabf8)
    #1 0x55f71175f161 in key_def_dup /home/shiny/dev/tarantool/src/box/key_def.c:144:24
    #2 0x55f710b87458 in luaT_push_key_def /home/shiny/dev/tarantool/src/box/lua/key_def.c:71:29
    #3 0x55f710b17a32 in luaT_add_index_parts_methods(lua_State*, key_def const*) /home/shiny/dev/tarantool/src/box/lua/space.cc:323:2
    #4 0x55f710b15354 in lbox_fillspace(lua_State*, space*, int) /home/shiny/dev/tarantool/src/box/lua/space.cc:523:3
    #5 0x55f710b123b1 in box_lua_space_new(lua_State*, space*) /home/shiny/dev/tarantool/src/box/lua/space.cc:634:2
    #6 0x55f710b11f76 in box_lua_space_new_or_delete(trigger*, void*) /home/shiny/dev/tarantool/src/box/lua/space.cc:664:3
    #7 0x55f710e222b6 in trigger_run_list(rlist*, void*) /home/shiny/dev/tarantool/src/lib/core/trigger.cc:119:7
    #8 0x55f710e20836 in trigger_run /home/shiny/dev/tarantool/src/lib/core/trigger.cc:152:9
    #9 0x55f7101a785e in space_cache_replace /home/shiny/dev/tarantool/src/box/space_cache.c:187:6
    #10 0x55f71028c12c in alter_space_do(txn_stmt*, alter_space*) /home/shiny/dev/tarantool/src/box/alter.cc:1066:2
    #11 0x55f71025419b in on_replace_dd_space(trigger*, void*) /home/shiny/dev/tarantool/src/box/alter.cc:2493:4
    #12 0x55f710e222b6 in trigger_run_list(rlist*, void*) /home/shiny/dev/tarantool/src/lib/core/trigger.cc:119:7
    #13 0x55f710e20836 in trigger_run /home/shiny/dev/tarantool/src/lib/core/trigger.cc:152:9
    #14 0x55f710187804 in space_on_replace /home/shiny/dev/tarantool/src/box/space.c:881:11
    #15 0x55f7103213a1 in txn_commit_stmt /home/shiny/dev/tarantool/src/box/txn.c:644:13
    #16 0x55f71037b665 in box_process_rw /home/shiny/dev/tarantool/src/box/box.cc:474:6
    #17 0x55f7103a21c6 in box_process1 /home/shiny/dev/tarantool/src/box/box.cc:3608:9
    #18 0x55f7103a9f3d in box_update /home/shiny/dev/tarantool/src/box/box.cc:3850:9
    #19 0x55f710577398 in sql_constraint_create /home/shiny/dev/tarantool/src/box/sql.c:1550:6
    #20 0x55f710578e44 in sql_check_create /home/shiny/dev/tarantool/src/box/sql.c:1664:9
    #21 0x55f710957a96 in sqlVdbeExec /home/shiny/dev/tarantool/src/box/sql/vdbe.c:2189:6
    #22 0x55f7109a042c in sqlStep /home/shiny/dev/tarantool/src/box/sql/vdbeapi.c:133:8
    #23 0x55f71099f39c in sql_step /home/shiny/dev/tarantool/src/box/sql/vdbeapi.c:155:9
    #24 0x55f7105879b0 in sql_execute /home/shiny/dev/tarantool/src/box/execute.c:218:8
    #25 0x55f7105874e6 in sql_prepare_and_execute /home/shiny/dev/tarantool/src/box/execute.c:281:6
    #26 0x55f710588760 in box_process_sql /home/shiny/dev/tarantool/src/box/execute.c:313:11
    #27 0x55f70fab8a36 in tx_process_sql(cmsg*) /home/shiny/dev/tarantool/src/box/iproto.cc:2440:6
    #28 0x55f710d45e75 in cmsg_deliver /home/shiny/dev/tarantool/src/lib/core/cbus.c:373:2
    #29 0x55f710d54df4 in fiber_pool_f /home/shiny/dev/tarantool/src/lib/core/fiber_pool.c:64:3

Direct leak of 384 byte(s) in 2 object(s) allocated from:
    #0 0x55f70fa273c9 in malloc (/home/shiny/dev/tarantool/build-asan-debug/src/tarantool+0x11903c9) (BuildId: 50b4f8d425d61717239211bb327e4c0a466dabf8)
    #1 0x55f71175f161 in key_def_dup /home/shiny/dev/tarantool/src/box/key_def.c:144:24
    #2 0x55f710b87458 in luaT_push_key_def /home/shiny/dev/tarantool/src/box/lua/key_def.c:71:29
    #3 0x55f710b17a32 in luaT_add_index_parts_methods(lua_State*, key_def const*) /home/shiny/dev/tarantool/src/box/lua/space.cc:323:2
    #4 0x55f710b15354 in lbox_fillspace(lua_State*, space*, int) /home/shiny/dev/tarantool/src/box/lua/space.cc:523:3
    #5 0x55f710b123b1 in box_lua_space_new(lua_State*, space*) /home/shiny/dev/tarantool/src/box/lua/space.cc:634:2
    #6 0x55f710b11f76 in box_lua_space_new_or_delete(trigger*, void*) /home/shiny/dev/tarantool/src/box/lua/space.cc:664:3
    #7 0x55f710e222b6 in trigger_run_list(rlist*, void*) /home/shiny/dev/tarantool/src/lib/core/trigger.cc:119:7
    #8 0x55f710e20836 in trigger_run /home/shiny/dev/tarantool/src/lib/core/trigger.cc:152:9
    #9 0x55f7101a785e in space_cache_replace /home/shiny/dev/tarantool/src/box/space_cache.c:187:6
    #10 0x55f71028c12c in alter_space_do(txn_stmt*, alter_space*) /home/shiny/dev/tarantool/src/box/alter.cc:1066:2
    #11 0x55f71025ce6d in on_replace_dd_truncate(trigger*, void*) /home/shiny/dev/tarantool/src/box/alter.cc:2906:3
    #12 0x55f710e222b6 in trigger_run_list(rlist*, void*) /home/shiny/dev/tarantool/src/lib/core/trigger.cc:119:7
    #13 0x55f710e20836 in trigger_run /home/shiny/dev/tarantool/src/lib/core/trigger.cc:152:9
    #14 0x55f710187804 in space_on_replace /home/shiny/dev/tarantool/src/box/space.c:881:11
    #15 0x55f7103213a1 in txn_commit_stmt /home/shiny/dev/tarantool/src/box/txn.c:644:13
    #16 0x55f71037b665 in box_process_rw /home/shiny/dev/tarantool/src/box/box.cc:474:6
    #17 0x55f7103a21c6 in box_process1 /home/shiny/dev/tarantool/src/box/box.cc:3608:9
    #18 0x55f7103aa7bd in box_upsert /home/shiny/dev/tarantool/src/box/box.cc:3870:9
    #19 0x55f7103ab4d6 in space_truncate(space*) /home/shiny/dev/tarantool/src/box/box.cc:3901:6
    #20 0x55f7103aa950 in box_truncate /home/shiny/dev/tarantool/src/box/box.cc:3911:3
    #21 0x55f71098155c in sqlVdbeExec /home/shiny/dev/tarantool/src/box/sql/vdbe.c:3828:7
    #22 0x55f7109a042c in sqlStep /home/shiny/dev/tarantool/src/box/sql/vdbeapi.c:133:8
    #23 0x55f71099f39c in sql_step /home/shiny/dev/tarantool/src/box/sql/vdbeapi.c:155:9
    #24 0x55f7105879b0 in sql_execute /home/shiny/dev/tarantool/src/box/execute.c:218:8
    #25 0x55f7105874e6 in sql_prepare_and_execute /home/shiny/dev/tarantool/src/box/execute.c:281:6
    #26 0x55f710588760 in box_process_sql /home/shiny/dev/tarantool/src/box/execute.c:313:11
    #27 0x55f70fab8a36 in tx_process_sql(cmsg*) /home/shiny/dev/tarantool/src/box/iproto.cc:2440:6
    #28 0x55f710d45e75 in cmsg_deliver /home/shiny/dev/tarantool/src/lib/core/cbus.c:373:2
    #29 0x55f710d54df4 in fiber_pool_f /home/shiny/dev/tarantool/src/lib/core/fiber_pool.c:64:3

SUMMARY: AddressSanitizer: 1536 byte(s) leaked in 8 allocation(s).

```

**Comment by nshy** [comment]
I guess it is similar to #8890. Backtraces looks different but issue is same. For example in in case of `box_tuple_iterator` in #8890 the leaked code is:

```
local function tuple_iterator(tuple)
    local it = builtin.box_tuple_iterator(tuple)
    if it == nil then
        box.error()
    end
    return ffi.gc(ffi.cast(tuple_iterator_ref_t, it),
        builtin.box_tuple_iterator_free)
end
```

And in case of this issue the leaked code is:
```
static void
luaT_push_key_def_nodup(struct lua_State *L, const struct key_def *key_def)
{
        void *ptr = luaL_pushcdata(L, CTID_STRUCT_KEY_DEF_REF);
        *(const struct key_def **)ptr = key_def;
        lua_pushcfunction(L, lbox_key_def_gc);
        luaL_setcdatagc(L, -2);
}
```
The allocation is assumed to be garbage collected but instead leaked. In the first case due to JIT the backtrace is cut at JIT frame (`<unknown module>`) and leak is not suppressed by current catch-all `leak:lj_BC_FUNCC` suppresssion. In the second case there is no suppression due to long stack (more than 30 frames).

**Comment by Buristan** [comment]
Maybe the root reason is the same as for #8890: Tarantool doesn't call `tarantool_lua_free()` before exit. See #3071 for details.
