### ISSUE TITLE
Tarantool crashes on interruption

### ISSUE THREAD

**Issue by psergee** [tarantool/tarantool#9275]
**Tarantool built from master crashes on interruption**

* OS: Linux
* OS Version: ubuntu 23.04
* Architecture: amd64

Tarantool 3.0.0-alpha3-119-g0ea1ba877
Target: Linux-x86_64-RelWithDebInfo
Build options: cmake . -DCMAKE_INSTALL_PREFIX=/usr/local -DENABLE_BACKTRACE=TRUE
Compiler: GNU-12.3.0
C_FLAGS: -fexceptions -funwind-tables -fasynchronous-unwind-tables -fno-common -msse2 -Wformat -Wformat-security -Werror=format-security -fstack-protector-strong -fPIC -fmacro-prefix-map=/home/psergee/work/tarantool=. -std=c11 -Wall -Wextra -Wno-gnu-alignof-expression -fno-gnu89-inline -Wno-cast-function-type
CXX_FLAGS: -fexceptions -funwind-tables -fasynchronous-unwind-tables -fno-common -msse2 -Wformat -Wformat-security -Werror=format-security -fstack-protector-strong -fPIC -fmacro-prefix-map=/home/psergee/work/tarantool=. -std=c++11 -Wall -Wextra -Wno-invalid-offsetof -Wno-gnu-alignof-expression -Wno-cast-function-type

**Steps to reproduce**

Here is the script:
```lua
local console = require('console')

box.cfg{}

local cons_listen_sock = console.listen('unix/:./haha.sock')
local function close_sock_tr()
    box.ctl.on_shutdown(nil, close_sock_tr)
    cons_listen_sock:close()
end
box.ctl.on_shutdown(close_sock_tr)
```

1. Start the script with tarantool: 
`tarantool dumb_test_app.lua`
1. Send SIGINT to the started process, or press Ctrl-C in the terminal.

**Actual behavior**

Crash after interruption:
```
2023-10-18 20:01:37.236 [235934] main/103/dumb_test_app.lua I> Tarantool 3.0.0-alpha3-119-g0ea1ba877 Linux-x86_64-RelWithDebInfo
2023-10-18 20:01:37.236 [235934] main/103/dumb_test_app.lua I> log level 5 (INFO)
2023-10-18 20:01:37.236 [235934] main/103/dumb_test_app.lua I> wal/engine cleanup is paused
2023-10-18 20:01:37.236 [235934] main/103/dumb_test_app.lua I> mapping 268435456 bytes for memtx tuple arena...
2023-10-18 20:01:37.236 [235934] main/103/dumb_test_app.lua I> Actual slab_alloc_factor calculated on the basis of desired slab_alloc_factor = 1.044274
2023-10-18 20:01:37.236 [235934] main/103/dumb_test_app.lua I> mapping 134217728 bytes for vinyl tuple arena...
2023-10-18 20:01:37.237 [235934] main/103/dumb_test_app.lua/box.upgrade I> Recovering snapshot with schema version 3.0.0
2023-10-18 20:01:37.238 [235934] main/103/dumb_test_app.lua I> update replication_synchro_quorum = 1
2023-10-18 20:01:37.238 [235934] main/103/dumb_test_app.lua I> instance uuid d21d0f43-d6a7-4252-bc1f-b2bf07f5abbb
2023-10-18 20:01:37.238 [235934] main/103/dumb_test_app.lua I> instance vclock {}
2023-10-18 20:01:37.238 [235934] main/103/dumb_test_app.lua I> recovery start
2023-10-18 20:01:37.238 [235934] main/103/dumb_test_app.lua I> recovering from `./00000000000000000000.snap'
2023-10-18 20:01:37.238 [235934] main/103/dumb_test_app.lua I> replicaset uuid 88862b46-6acc-4069-880e-8d943f341a49
2023-10-18 20:01:37.252 [235934] main/103/dumb_test_app.lua I> assigned id 1 to replica d21d0f43-d6a7-4252-bc1f-b2bf07f5abbb
2023-10-18 20:01:37.253 [235934] main/103/dumb_test_app.lua I> update replication_synchro_quorum = 1
2023-10-18 20:01:37.254 [235934] main/103/dumb_test_app.lua I> ready to accept requests
2023-10-18 20:01:37.254 [235934] main/103/dumb_test_app.lua I> leaving orphan mode
2023-10-18 20:01:37.254 [235934] main/104/gc I> wal/engine cleanup is resumed
2023-10-18 20:01:37.254 [235934] main/105/checkpoint_daemon I> scheduled next checkpoint for Wed Oct 18 21:10:05 2023
2023-10-18 20:01:37.255 [235934] main/113/console/unix/:./haha.sock/socket I> started
2023-10-18 20:01:37.255 [235934] main I> entering the event loop
^CSegmentation fault
  code: SEGV_MAPERR
  addr: 0x7f7b0bcfd451
  context: 0x7f7d02b808c0
  siginfo: 0x7f7d02b809f0
  rax      0x7f7b0bcfd441     140166455874625
  rbx      0x7f7cfc001600     140174780536320
  rcx      0x0                0
  rdx      0x1                1
  rsi      0xffffffff         4294967295
  rdi      0x7f7d02b80f60     140174893256544
  rsp      0x7f7d02b80f60     140174893256544
  rbp      0x7f7d02b80f60     140174893256544
  r8       0x8                8
  r9       0x302              770
  r10      0x40016180         1073832320
  r11      0xfffffffc         4294967292
  r12      0x0                0
  r13      0x0                0
  r14      0x0                0
  r15      0x0                0
  rip      0x5584b0eab4ef     94028392215791
  eflags   0x10246            66118
  cs       0x33               51
  gs       0x0                0
  fs       0x0                0
  cr2      0x7f7b0bcfd451     140166455874641
  err      0x4                4
  oldmask  0x0                0
  trapno   0xe                14
Current time: 1697648497
Please file a bug at https://github.com/tarantool/tarantool/issues
Attempting backtrace... Note: since the server has already crashed, 
this may fail as well
#1  0x5584b0e712a2 in crash_signal_cb+162
#2  0x7f7d2e63c460 in __sigaction+80
#3  0x5584b0eab4ef in on_shutdown_event_trigger_fiber_f+79
#4  0x5584b0cc6890 in fiber_cxx_invoke(int (*)(__va_list_tag*), __va_list_tag*)+16
#5  0x5584b0e7a9f6 in fiber_loop+70
#6  0x5584b111a39c in coro_init+76
Aborted (core dumped)
```

**Expected behavior**

No crash.
Here is how it looks on alpha3:
```
2023-10-18 20:03:13.007 [235955] main/103/dumb_test_app.lua I> Tarantool 3.0.0-alpha3-0-g1efac25 Linux-x86_64-Debug
2023-10-18 20:03:13.007 [235955] main/103/dumb_test_app.lua I> log level 5 (INFO)
2023-10-18 20:03:13.007 [235955] main/103/dumb_test_app.lua I> wal/engine cleanup is paused
2023-10-18 20:03:13.008 [235955] main/103/dumb_test_app.lua I> mapping 268435456 bytes for memtx tuple arena...
2023-10-18 20:03:13.008 [235955] main/103/dumb_test_app.lua I> Actual slab_alloc_factor calculated on the basis of desired slab_alloc_factor = 1.044274
2023-10-18 20:03:13.008 [235955] main/103/dumb_test_app.lua I> mapping 134217728 bytes for vinyl tuple arena...
2023-10-18 20:03:13.010 [235955] main/103/dumb_test_app.lua/box.upgrade I> Recovering snapshot with schema version 3.0.0
2023-10-18 20:03:13.015 [235955] main/103/dumb_test_app.lua I> update replication_synchro_quorum = 1
2023-10-18 20:03:13.015 [235955] main/103/dumb_test_app.lua I> instance uuid d21d0f43-d6a7-4252-bc1f-b2bf07f5abbb
2023-10-18 20:03:13.015 [235955] main/103/dumb_test_app.lua I> instance vclock {}
2023-10-18 20:03:13.016 [235955] main/103/dumb_test_app.lua I> recovery start
2023-10-18 20:03:13.016 [235955] main/103/dumb_test_app.lua I> recovering from `./00000000000000000000.snap'
2023-10-18 20:03:13.032 [235955] main/103/dumb_test_app.lua I> replicaset uuid 88862b46-6acc-4069-880e-8d943f341a49
2023-10-18 20:03:13.051 [235955] main/103/dumb_test_app.lua I> assigned id 1 to replica d21d0f43-d6a7-4252-bc1f-b2bf07f5abbb
2023-10-18 20:03:13.051 [235955] main/103/dumb_test_app.lua I> update replication_synchro_quorum = 1
2023-10-18 20:03:13.051 [235955] main/103/dumb_test_app.lua I> ready to accept requests
2023-10-18 20:03:13.051 [235955] main/103/dumb_test_app.lua I> leaving orphan mode
2023-10-18 20:03:13.051 [235955] main/104/gc I> wal/engine cleanup is resumed
2023-10-18 20:03:13.051 [235955] main/105/checkpoint_daemon I> scheduled next checkpoint for Wed Oct 18 21:34:56 2023
2023-10-18 20:03:13.053 [235955] main/113/console
```/unix/:./haha.sock/socket I> started
2023-10-18 20:03:13.053 [235955] main I> entering the event loop
^C2023-10-18 20:03:14.141 [235955] main/113/console/unix/:./haha.sock/socket I> stopped

**Comment by Gumix** [comment]
Introduced by:
- #9137

CC @drewdzzz
