### ISSUE TITLE
[svacer] dereference of NULL `old_space` in src/box/alter.cc

### ISSUE THREAD

**Issue by sergepetrenko** [tarantool/tarantool#9407]
Svacer: [link](https://svacer.tarantool.io/r/clmpi5no4crs72pj9630)

How to reproduce:
```lua
box.cfg{}
box.space._space:run_triggers(false)
box.space._space:insert{512, 1, "asd", "memtx", 0, setmetatable({}, {__serialize='map'}), {}}
box.space._space:run_triggers(true)
box.space._space:delete{512}
```
After running the commands observe the segmentation fault:
```
Segmentation fault
  code: SEGV_MAPERR
  addr: 0xe0
  context: 0x7fce6c99af48
  siginfo: 0x7fce6c99aee0
Current time: 1700837532
Please file a bug at https://github.com/tarantool/tarantool/issues
Attempting backtrace... Note: since the server has already crashed, 
this may fail as well
#1  0x103463d6a in crash_collect+234
#2  0x103463c1c in crash_signal_cb+60
#3  0x7ff80ecdf37d in _sigtramp+29
#4  0x103297748 in on_replace_dd_space(trigger*, void*)+1512
#5  0x10349c520 in trigger_run_list(rlist*, void*)+128
#6  0x10349c245 in trigger_run+213
#7  0x10327bf42 in space_on_replace+130
#8  0x1032bdf5d in txn_commit_stmt+381
#9  0x1032ce26c in box_process_rw+396
#10 0x1032d89d0 in box_process1+464
#11 0x1032da053 in box_delete+243
#12 0x1033fedce in lbox_index_delete+382
#13 0x1034d46bb in lj_BC_FUNCC+68
#14 0x1034e2f7e in lua_pcall+974
#15 0x1034417b3 in luaT_call+35
#16 0x1034357f7 in lua_main+311
#17 0x103434760 in run_script_f+3296
#18 0x10318305a in fiber_cxx_invoke(int (*)(__va_list_tag*), __va_list_tag*)+26
#19 0x10346ee08 in fiber_loop+248
#20 0x1037b8c4e in coro_init+110
```

**Comment by locker** [comment]
https://github.com/tarantool/tarantool/issues/9397#issuecomment-1827848149
