### ISSUE TITLE
relay: stack-use-after-return with txn_isolation = 'linearizable'

### ISSUE THREAD

**Issue by Totktonada** [tarantool/tarantool#9505]
## Version

Tarantool 3.0.0-beta1-91-g1262e99dbd Linux-x86_64-Debug

## Build

```sh
$ CC=clang-16 CXX=clang++-16 cmake . -DCMAKE_BUILD_TYPE=Debug -DFIBER_STACK_SIZE=640Kb -DENABLE_WERROR=ON -DENABLE_ASAN=ON -DENABLE_UB_SANITIZER=ON -DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION=OFF -DENABLE_FUZZER=ON -DTEST_BUILD=ON
```

## Script

```lua
-- t.lua
#!/usr/bin/env tarantool

local fiber = require('fiber')
local log = require('log')
local fio = require('fio')

local instance_name = arg[1]
assert(instance_name == 'i1' or instance_name == 'i2' or instance_name == 'i3')
fio.mktree(instance_name)
box.cfg({
    wal_dir = instance_name,
    memtx_dir = instance_name,
    listen = ('unix/:./%s.iproto'):format(instance_name),
    replication = {
        ('unix/:./%s.iproto'):format('i1'),
        ('unix/:./%s.iproto'):format('i2'),
        ('unix/:./%s.iproto'):format('i3'),
    },
    memtx_use_mvcc_engine = true,
    election_mode = 'candidate',
})
box.schema.user.grant('guest', 'super', nil, nil, {if_not_exists = true})

local cfg = {
    status_check_interval = 0.1,
}
local monitor_status_fiber
local current_status

local function monitor_status_step()
    -- Try to reach someone from quorum.
    local ok, err = pcall(box.begin, {
        txn_isolation = 'linearizable',
        timeout       = box.cfg.replication_synchro_timeout,
    })
    if ok then
        box.commit()
        current_status = 'connected'
    else
        log.info('status monitor: %s', err)
        current_status = 'disconnected'
    end
end

local function monitor_status_loop()
    fiber.self():name('monitor_status')
    while true do
        local next_step_time = fiber.time() + cfg.status_check_interval
        monitor_status_step()
        local time_to_sleep = next_step_time - fiber.time()
        if time_to_sleep > 0 then
            fiber.sleep(time_to_sleep)
        end
    end
end

local function init_schema()
    if not box.info.ro then
        box.once('init_schema', function()
            box.schema.create_space('s', {
                format = {{
                    type = 'string',
                    name = 'x',
                }, {
                    type = 'string',
                    name = 'y',
                }, {
                    type = 'unsigned',
                    name = 'z',
                }},
                is_sync = true,
            })
            box.space.s:create_index('primary', {
                unique = true,
                parts = {'x'},
            })
            box.schema.create_space('t', {
                format = {{
                    type = 'string',
                    name = 'x',
                }, {
                    type = 'scalar',
                    name = 'y',
                }},
                is_sync = true,
            })
            box.space.t:create_index('primary', {
                unique = true,
                parts = {'x'},
            })
        end)
    end
end

local function start()
    init_schema()

    if monitor_status_fiber == nil or
       monitor_status_fiber:status() == 'dead' then
        monitor_status_fiber = fiber.new(monitor_status_loop)
    end
end

start()
```

```sh
-- run.sh
#!/bin/sh

export ASAN=ON
export LSAN_OPTIONS=suppressions=$(realpath asan/lsan.supp)
export ASAN_OPTIONS=heap_profile=0:unmap_shadow_on_exit=1:detect_invalid_pointer_pairs=1:symbolize=1:detect_leaks=1:dump_instruction_bytes=1
export PATH=$(realpath src):$PATH

#rm -r i1 i2 i3 i1.iproto i2.iproto i3.iproto
./t.lua i1 &
./t.lua i2 &
./t.lua i3 &

wait
```

## Run

```sh
$ ./run.sh
Ctrl+C
$ ./run.sh
Ctrl+C
$ ./run.sh
Ctrl+C
$ ./run.sh
Ctrl+C
<...>
```

The problem is reproduced from time to time. I have no stable reproducer.

## Result

```c
==16681==ERROR: AddressSanitizer: stack-use-after-return on address 0x7f80b2817c38 at pc 0x55fafe3c4a2e bp 0x7f80cd0120d0 sp 0x7f80cd0120c8
WRITE of size 8 at 0x7f80b2817c38 thread T0
2023-12-19 03:30:42.564 [16680] relay/unix/:(socket)/101/main I> recover from `i2/00000000000000000026.xlog'
    #0 0x55fafe3c4a2d in relay_trigger_vclock_sync /home/alex/p/tarantool-meta/tarantool/src/box/relay.cc:918:15
    #1 0x55fafe252bf3 in relay_get_sync_on_start(trigger*, void*) /home/alex/p/tarantool-meta/tarantool/src/box/box.cc:2564:6
    #2 0x55fafece5bc6 in trigger_run_list(rlist*, void*) /home/alex/p/tarantool-meta/tarantool/src/lib/core/trigger.cc:100:7
    #3 0x55fafece4146 in trigger_run /home/alex/p/tarantool-meta/tarantool/src/lib/core/trigger.cc:133:9
    #4 0x55fafe3d26cd in relay_thread_on_start(void*) /home/alex/p/tarantool-meta/tarantool/src/box/relay.cc:864:2
    #5 0x55fafec0b57b in cbus_pair_perform /home/alex/p/tarantool-meta/tarantool/src/lib/core/cbus.c:487:3
    #6 0x55fafec07ac5 in cmsg_deliver /home/alex/p/tarantool-meta/tarantool/src/lib/core/cbus.c:373:2
    #7 0x55fafec16ac4 in fiber_pool_f /home/alex/p/tarantool-meta/tarantool/src/lib/core/fiber_pool.c:64:3
    #8 0x55fafd8dbfa8 in fiber_cxx_invoke(int (*)(__va_list_tag*), __va_list_tag*) /home/alex/p/tarantool-meta/tarantool/src/lib/core/fiber.h:1297:10
    #9 0x55fafebc7fbb in fiber_loop /home/alex/p/tarantool-meta/tarantool/src/lib/core/fiber.c:1160:18
    #10 0x55faffbde955 in coro_init /home/alex/p/tarantool-meta/tarantool/third_party/coro/coro.c:108:3

Address 0x7f80b2817c38 is a wild pointer inside of access range of size 0x000000000008.
SUMMARY: AddressSanitizer: stack-use-after-return /home/alex/p/tarantool-meta/tarantool/src/box/relay.cc:918:15 in relay_trigger_vclock_sync
Shadow bytes around the buggy address:
  0x7f80b2817980: f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5
  0x7f80b2817a00: f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5
  0x7f80b2817a80: f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5
  0x7f80b2817b00: f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5
  0x7f80b2817b80: f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5
=>0x7f80b2817c00: f5 f5 f5 f5 f5 f5 f5[f5]f5 f5 f5 f5 f5 f5 f5 f5
  0x7f80b2817c80: f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5
  0x7f80b2817d00: f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5
  0x7f80b2817d80: f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5
  0x7f80b2817e00: f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5
  0x7f80b2817e80: f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==16681==ABORTING
```

**Comment by sergepetrenko** [comment]
Unfortunately I couldn't reproduce this on Mac, but I have an idea what can go wrong here:
1. The stacktrace contains `relay_get_sync_on_start`, which is a trigger function for a trigger `on_relay_thread_start`. The trigger is created in scope of `box_collect_confirmed_vclock` on stack, together with `struct sync_trigger_data data`:
https://github.com/tarantool/tarantool/blob/1a0bafd5250eb8103d46e3437ce3b23c9ccbbdf7/src/box/box.cc#L2591-L2603
2. At first glance, everything is fine, because all exits from `box_collect_confirmed_vclock` also clear the trigger:
https://github.com/tarantool/tarantool/blob/1a0bafd5250eb8103d46e3437ce3b23c9ccbbdf7/src/box/box.cc#L2620-L2622
https://github.com/tarantool/tarantool/blob/1a0bafd5250eb8103d46e3437ce3b23c9ccbbdf7/src/box/box.cc#L2632-L2633
So it shouldn't be possible to access `data::vclock_syncs` after function scope exit.
3. But the trigger yields: `relay_get_sync_on_start` calls `relay_trigger_vclock_sync`, which yields in `cbus_call_timeout` before trying to set `*vclock_sync`:
https://github.com/tarantool/tarantool/blob/1a0bafd5250eb8103d46e3437ce3b23c9ccbbdf7/src/box/relay.cc#L914-L918

So it's possible to do `trigger_clear` **after** the trigger is run, but before the `*vclock_sync` assignment. In case the trigger is cleared while it yields.
